/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.RepresentationTheory.Basic
import Mathlib.RepresentationTheory.Irreducible
import Mathlib.RepresentationTheory.AlgebraRepresentation.Basic
import Mathlib.RingTheory.SimpleModule.Basic
import Mathlib.RingTheory.SimpleModule.IsAlgClosed
import Mathlib.RingTheory.Finiteness.Basic
import Mathlib.RingTheory.IntegralDomain
import Mathlib.RingTheory.TensorProduct.Finite
import Mathlib.RingTheory.LittleWedderburn
import Mathlib.RingTheory.Finiteness.Cardinality
import Mathlib.FieldTheory.IsAlgClosed.Basic
import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure
import Mathlib.LinearAlgebra.TensorProduct.Basis
import OddOrder.GroupTheory.RepresentationTheory.BaseChange

/-!
# Burnside's theorem over an algebraically closed field (BG §2 Prop 2.1)

`OddOrder.GroupTheory.RepresentationTheory` shared module: the
**Bender-Glauberman §2 Prop 2.1 / Burnside** statement that for a faithful
absolutely irreducible representation the *enveloping algebra* — the image of
the group ring inside `End_F V` — is the whole of `End_F V`.

We prove the general module-theoretic form: if `M` is a finite-dimensional
simple module over an `F`-algebra `A`, with `F` algebraically closed, then the
structure ring hom `A → End_F M` (sending `a` to the `F`-linear map `m ↦ a • m`)
is **surjective**.

## Proof

This is the classical Burnside theorem, and over an algebraically closed field
it follows directly from two facts already in mathlib:

* **Schur's lemma** (`IsSimpleModule.algebraMap_end_bijective_of_isAlgClosed`):
  over an algebraically closed `F`, the commutant `D := End_A M` is just the
  scalars, i.e. `algebraMap F D` is bijective.
* **The Jacobson density theorem**
  (`Module.Finite.toModuleEnd_moduleEnd_surjective`): for a semisimple module
  finite over its endomorphism ring `D`, the map `A → End_D M` is surjective.

Since `D = F` (scalars), an `F`-linear endomorphism of `M` is automatically
`D`-linear, so `End_D M = End_F M`, and Jacobson density becomes exactly the
surjectivity of `A → End_F M`.

## BG ↔ mathlib mapping

* **BG Thm 2.5** uses this as `E(P) = Hom_F(V, V)` for a faithful irreducible
  `V` of an extraspecial group `P` over an algebraically closed field.
  Faithfulness is *not* needed for surjectivity — simplicity suffices.
-/

namespace OddOrder.RepresentationTheory

open Module

section Burnside

variable {F : Type*} [Field F]
variable {A : Type*} [Ring A] [Algebra F A]
variable {M : Type*} [AddCommGroup M] [Module F M] [Module A M] [IsScalarTower F A M]
variable [IsSimpleModule A M] [FiniteDimensional F M]

/-- **Burnside's theorem / Jacobson density** (BG Prop 2.1(b), module form,
general field): for a finite-dimensional simple module `M` over an `F`-algebra
`A`, if every `A`-endomorphism of `M` is an `F`-scalar (`Hom_A(M, M) = F`),
then the structure ring hom `A → End_F M`, `a ↦ (m ↦ a • m)`, is surjective.

Equivalently: the *enveloping algebra* — the `F`-subalgebra of `End_F M`
generated by the image of `A` — is the whole of `End_F M`.  BG's (b) states
this for `M` a faithful irreducible `FG`-module with `Hom_FG(M,M) = F`;
faithfulness is not needed. -/
theorem toModuleEnd_surjective_of_algebraMap_end_surjective
    (hSchur : Function.Surjective (algebraMap F (Module.End A M))) :
    Function.Surjective (Module.toModuleEnd F M (S := A)) := by
  classical
  -- `F` commutes with `A` on `M` (both act through the central image of `F`).
  haveI : SMulCommClass A F M := ⟨fun a c m => by
    rw [← IsScalarTower.algebraMap_smul A c m, ← IsScalarTower.algebraMap_smul A c (a • m),
        smul_smul, smul_smul, Algebra.commutes]⟩
  -- `M` is finite over the (bigger) endomorphism ring `D := End_A M`.
  haveI : Module.Finite (Module.End A M) M :=
    Module.Finite.of_restrictScalars_finite F (Module.End A M) M
  -- The scalar action of `D` on `M` agrees with the `F`-action.
  have key : ∀ (c : F) (x : M), (algebraMap F (Module.End A M) c) • x = c • x := by
    intro c x
    rw [Module.End.smul_def, Algebra.algebraMap_eq_smul_one, LinearMap.smul_apply,
      Module.End.one_apply]
  intro g
  -- Realise `g : End_F M` as a `D`-linear map, using that every `d ∈ D` is a scalar.
  let g' : M →ₗ[Module.End A M] M :=
    { toFun := g
      map_add' := g.map_add
      map_smul' := by
        intro d m
        obtain ⟨c, hc⟩ := hSchur d
        simp only [RingHom.id_apply, ← hc, key c m, key c (g m), map_smul] }
  -- Jacobson density: `A → End_D M` is surjective; pull back `g'`.
  obtain ⟨a, ha⟩ := Module.Finite.toModuleEnd_moduleEnd_surjective (R := A) (M := M) g'
  refine ⟨a, ?_⟩
  ext m
  have hm := LinearMap.congr_fun ha m
  simpa [g'] using hm

/-- **Burnside's theorem** (BG Prop 2.1, module form): for a finite-dimensional
simple module `M` over an `F`-algebra `A` with `F` algebraically closed, the
structure ring hom `A → End_F M`, `a ↦ (m ↦ a • m)`, is surjective.

Equivalently: the *enveloping algebra* — the `F`-subalgebra of `End_F M`
generated by the image of `A` — is the whole of `End_F M`. -/
theorem toModuleEnd_surjective_of_isAlgClosed [IsAlgClosed F] :
    Function.Surjective (Module.toModuleEnd F M (S := A)) :=
  -- Schur over an algebraically closed field: `End_A M` is just the scalars.
  toModuleEnd_surjective_of_algebraMap_end_surjective
    (IsSimpleModule.algebraMap_end_bijective_of_isAlgClosed (A := A) (V := M) F).2

end Burnside

section Representation

open scoped MonoidAlgebra

variable {F : Type*} [Field F]
variable {G : Type*} [Monoid G] {V : Type*} [AddCommGroup V] [Module F V]

set_option backward.isDefEq.respectTransparency false in
/-- **Burnside's theorem** (BG Prop 2.1(b), representation form, general
field): for a finite-dimensional irreducible representation `ρ` of `G` over a
field `F` with `Hom_FG(V, V) = F` (every self-intertwiner is a scalar), the
algebra hom `ρ.asAlgebraHom : F[G] →ₐ[F] End_F V` is surjective.  Equivalently,
the *enveloping algebra* `E(G)` (the `F`-span of the image of `G` in `End_F V`)
is all of `End_F V = Hom_F(V, V)`. -/
theorem asAlgebraHom_surjective_of_algebraMap_intertwiningMap_surjective
    (ρ : Representation F G V) [ρ.IsIrreducible] [FiniteDimensional F V]
    (hEnd : Function.Surjective (algebraMap F (Representation.IntertwiningMap ρ ρ))) :
    Function.Surjective ρ.asAlgebraHom := by
  -- convert the intertwiner hypothesis into `End_{F[G]}(asModule) = F`
  have hSchur : Function.Surjective
      (algebraMap F (Module.End (MonoidAlgebra F G) ρ.asModule)) := by
    intro d
    obtain ⟨c, hc⟩ := hEnd ((Representation.IntertwiningMap.equivAlgEnd (ρ := ρ)).symm d)
    refine ⟨c, ?_⟩
    have h := congrArg (Representation.IntertwiningMap.equivAlgEnd (ρ := ρ)) hc
    rwa [AlgEquiv.commutes, AlgEquiv.apply_symm_apply] at h
  -- Module-form Burnside applied with `A := F[G]`, `M := ρ.asModule`.  `ρ.asModule` is
  -- definitionally `V` and the `F[G]`-action `r • x` is `ρ.asAlgebraHom r x`, so
  -- `Module.toModuleEnd F ρ.asModule` and `ρ.asAlgebraHom` are the *same* map.  The
  -- relaxed-transparency option lets instance search see through the `asModule` synonym
  -- (the idiom mathlib uses for the `IsScalarTower k k[G] ρ.asModule` instance).
  have hsurj := toModuleEnd_surjective_of_algebraMap_end_surjective (F := F)
    (A := MonoidAlgebra F G) (M := ρ.asModule) hSchur
  intro h
  obtain ⟨r, hr⟩ := hsurj h
  exact ⟨r, hr⟩

/-- **Burnside's theorem** (BG Prop 2.1, representation form): for a
finite-dimensional irreducible representation `ρ` of `G` over an algebraically
closed field `F`, the algebra hom `ρ.asAlgebraHom : F[G] →ₐ[F] End_F V` is
surjective. Equivalently, the *enveloping algebra* `E(G)` (the `F`-span of the
image of `G` in `End_F V`) is all of `End_F V = Hom_F(V, V)`.

This is the form `BG Thm 2.5` uses (as `E(P) = Hom_F(V, V)`). -/
theorem asAlgebraHom_surjective_of_isAlgClosed [IsAlgClosed F] (ρ : Representation F G V)
    [ρ.IsIrreducible] [FiniteDimensional F V] :
    Function.Surjective ρ.asAlgebraHom :=
  asAlgebraHom_surjective_of_algebraMap_intertwiningMap_surjective ρ
    (Representation.IsIrreducible.algebraMap_intertwiningMap_bijective_of_isAlgClosed
      (ρ := ρ)).2

/-- **Burnside, span form** (BG Prop 2.1(b), general field): for a
finite-dimensional irreducible `ρ` with `Hom_FG(V, V) = F`, the images
`{ρ g : g ∈ G}` span `End_F V`. -/
theorem span_range_representation_eq_top_of_algebraMap_intertwiningMap_surjective
    (ρ : Representation F G V) [ρ.IsIrreducible] [FiniteDimensional F V]
    (hEnd : Function.Surjective (algebraMap F (Representation.IntertwiningMap ρ ρ))) :
    Submodule.span F (Set.range fun g : G => ρ g) = ⊤ := by
  rw [eq_top_iff]
  rintro e -
  obtain ⟨r, rfl⟩ := asAlgebraHom_surjective_of_algebraMap_intertwiningMap_surjective ρ hEnd e
  induction r using MonoidAlgebra.induction_on with
  | hM g => rw [Representation.asAlgebraHom_of]; exact Submodule.subset_span ⟨g, rfl⟩
  | hadd x y hx hy => rw [map_add]; exact Submodule.add_mem _ hx hy
  | hsmul c x hx => rw [map_smul]; exact Submodule.smul_mem _ c hx

/-- **Burnside, span form** (BG Prop 2.1): for a finite-dimensional irreducible representation `ρ`
over an algebraically closed field, the images `{ρ g : g ∈ G}` span `End_F V`. (Equivalent to
`asAlgebraHom_surjective_of_isAlgClosed`; the convenient form for building the Burnside basis.) -/
theorem span_range_representation_eq_top [IsAlgClosed F] (ρ : Representation F G V)
    [ρ.IsIrreducible] [FiniteDimensional F V] :
    Submodule.span F (Set.range fun g : G => ρ g) = ⊤ :=
  span_range_representation_eq_top_of_algebraMap_intertwiningMap_surjective ρ
    (Representation.IsIrreducible.algebraMap_intertwiningMap_bijective_of_isAlgClosed
      (ρ := ρ)).2

end Representation

section CentralCharacter

variable {F : Type*} [Field F] [IsAlgClosed F]
variable {G : Type*} [Group G] {V : Type*} [AddCommGroup V] [Module F V]

/-- **Central scalar action** (Schur, central character): for a finite-dimensional irreducible
representation `ρ` over an algebraically closed field `F`, every central element `z ∈ Z(G)` acts
on `V` by a scalar `c • id`. (This is the existence half of the central character used in the
representation theory of extraspecial groups, BG Thm 2.5 / Gor 5.5.5.) -/
theorem center_isScalar (ρ : Representation F G V) [ρ.IsIrreducible] [FiniteDimensional F V]
    {z : G} (hz : z ∈ Subgroup.center G) :
    ∃ c : F, ρ z = c • LinearMap.id := by
  -- `ρ z` commutes with every `ρ g` (`z` is central), so it is an intertwiner `ρ → ρ`.
  have hcomm : ∀ (g : G) (v : V), (ρ z) ((ρ g) v) = (ρ g) ((ρ z) v) := fun g v => by
    rw [← Module.End.mul_apply, ← Module.End.mul_apply, ← map_mul, ← map_mul,
      Subgroup.mem_center_iff.mp hz g]
  -- Over an algebraically closed field every self-intertwiner of an irreducible is a scalar.
  have hbij :=
    (Representation.IsIrreducible.algebraMap_intertwiningMap_bijective_of_isAlgClosed (ρ := ρ)).2
  obtain ⟨c, hc⟩ := hbij ((ρ z).intertwiningMap_of_isIntertwiningMap ρ ρ hcomm)
  refine ⟨c, ?_⟩
  ext v
  -- `algebraMap F (IntertwiningMap ρ ρ) c` is `c • 1` and its coercion at `v` is `c • v`; the
  -- built intertwiner's coercion at `v` is `ρ z v`.  All these are `rfl`, so this typechecks.
  have hv : c • v = (ρ z) v := DFunLike.congr_fun hc v
  simpa using hv.symm

/-- **Gorenstein Theorem 3.2.2** (cyclic centre from a faithful irreducible).  A finite group `G`
with a faithful irreducible representation on a nonzero finite-dimensional space over an
algebraically closed field has cyclic centre `Z(G)`.

By `center_isScalar` each central `z` acts as a scalar `c(z) • 1`; the scalar is determined by the
operator (`V ≠ 0`), so `z ↦ c(z)` is a group homomorphism `Z(G) →* F` into the field's
multiplicative monoid, injective because `ρ` is faithful.  A finite group with an injective
homomorphism into an integral domain is cyclic (`isCyclic_of_injective_ringHom`).

This is the input to BG Theorem 3.4 (`Z(K) ⊆ Z(G)` cyclic ⟹ the special group `K` is
extraspecial). -/
theorem isCyclic_center_of_faithful_irreducible [Finite G] [FiniteDimensional F V] [Nontrivial V]
    (ρ : Representation F G V) [ρ.IsIrreducible] (hf : Function.Injective ρ) :
    IsCyclic (Subgroup.center G) := by
  classical
  -- the central scalar `c z`, characterised by `ρ z = c z • 1`
  let c : ↥(Subgroup.center G) → F := fun z => Classical.choose (center_isScalar ρ z.property)
  -- `1 : Module.End F V` is `LinearMap.id` definitionally, and `c z` is the chosen scalar
  have hc : ∀ z : ↥(Subgroup.center G), ρ (z : G) = c z • (1 : Module.End F V) := fun z =>
    Classical.choose_spec (center_isScalar ρ z.property)
  -- a nonzero operator determines its scalar (`V ≠ 0`)
  have huniq : ∀ {a b : F}, a • (1 : Module.End F V) = b • (1 : Module.End F V) → a = b := by
    intro a b hab
    obtain ⟨v, hv⟩ := exists_ne (0 : V)
    have hv2 : a • v = b • v := by simpa using DFunLike.congr_fun hab v
    rcases smul_eq_zero.mp (show (a - b) • v = 0 by rw [sub_smul, hv2, sub_self]) with h | h
    · exact sub_eq_zero.mp h
    · exact absurd h hv
  -- the central character `Z(G) →* F`
  let f : ↥(Subgroup.center G) →* F :=
    { toFun := c
      map_one' := by
        have h1 := hc 1
        rw [Subgroup.coe_one, map_one] at h1
        have h1' : (1 : F) • (1 : Module.End F V) = c 1 • 1 := by rw [one_smul]; exact h1
        exact (huniq h1').symm
      map_mul' := fun z₁ z₂ => by
        have h12 := hc (z₁ * z₂)
        rw [Subgroup.coe_mul, map_mul, hc z₁, hc z₂, smul_mul_smul_comm, mul_one] at h12
        exact (huniq h12).symm }
  -- faithfulness ⟹ injective
  have hf_inj : Function.Injective f := by
    intro z₁ z₂ h
    have hcc : c z₁ = c z₂ := h
    exact Subtype.ext (hf (by rw [hc z₁, hc z₂, hcc]))
  exact isCyclic_of_injective_ringHom f hf_inj

/-- **Burnside basis, spanning step.** A transversal `{ρ(out c) : c ∈ G/Z}` of the central cosets
still spans `End_F V`: every `ρ g` is a scalar multiple of `ρ(out (gZ))` (central character), so the
span is unchanged from `span_range_representation_eq_top`. -/
theorem span_range_quotient_out_eq_top (ρ : Representation F G V)
    [ρ.IsIrreducible] [FiniteDimensional F V] :
    Submodule.span F
      (Set.range fun c : G ⧸ Subgroup.center G => ρ (Quotient.out c)) = ⊤ := by
  rw [eq_top_iff, ← span_range_representation_eq_top ρ, Submodule.span_le]
  rintro _ ⟨g, rfl⟩
  set c₀ : G ⧸ Subgroup.center G := (g : G ⧸ Subgroup.center G) with hc₀
  have hz : (Quotient.out c₀)⁻¹ * g ∈ Subgroup.center G :=
    QuotientGroup.eq.mp (Quotient.out_eq c₀)
  obtain ⟨c, hc⟩ := center_isScalar ρ hz
  have hg : ρ g = c • ρ (Quotient.out c₀) := by
    have hsplit : g = Quotient.out c₀ * ((Quotient.out c₀)⁻¹ * g) := by group
    rw [hsplit, map_mul, hc]
    ext v
    simp [Module.End.mul_apply]
  change ρ g ∈ Submodule.span F (Set.range fun c : G ⧸ Subgroup.center G => ρ (Quotient.out c))
  rw [hg]
  exact Submodule.smul_mem _ c (Submodule.subset_span ⟨c₀, rfl⟩)

end CentralCharacter

section SchurField

open Representation

variable {F : Type*} [Field F]
variable {G : Type*} [Monoid G] {V : Type*} [AddCommGroup V] [Module F V]
variable {ρ : Representation F G V}

/-- An irreducible representation has a nontrivial underlying space. -/
theorem nontrivial_of_isIrreducible (ρ : Representation F G V) [ρ.IsIrreducible] :
    Nontrivial V := by
  by_contra h
  rw [not_nontrivial_iff_subsingleton] at h
  exact bot_ne_top (α := Subrepresentation ρ)
    (Subrepresentation.toSubmodule_injective (Subsingleton.elim _ _))

instance [ρ.IsIrreducible] : Nontrivial (IntertwiningMap ρ ρ) := by
  haveI : Nontrivial V := nontrivial_of_isIrreducible ρ
  obtain ⟨v, hv⟩ := exists_ne (0 : V)
  exact ⟨1, 0, fun h10 => hv (by simpa using DFunLike.congr_fun h10 v)⟩

instance : IntCast (IntertwiningMap ρ ρ) :=
  ⟨fun n => n • (1 : IntertwiningMap ρ ρ)⟩

/-- The self-intertwiners of a representation form a ring (mathlib only provides the
`Semiring` instance). -/
instance : Ring (IntertwiningMap ρ ρ) :=
  fast_instance%
  Function.Injective.ring (fun f : IntertwiningMap ρ ρ => f.toLinearMap)
    (Representation.IntertwiningMap.toLinearMap_injective ρ ρ) rfl rfl (fun _ _ => rfl)
    (fun _ _ => rfl) (fun _ => rfl) (fun _ _ => rfl) (fun _ _ => rfl) (fun _ _ => rfl)
    (fun f n => by
      induction n with
      | zero => rfl
      | succ n ih =>
        simp only [pow_succ, Representation.IntertwiningMap.coe_mul,
          show f ^ (n + 1) = f ^ n * f from rfl, ih])
    (fun _ => rfl) (fun n => zsmul_one n)

/-- **Schur's lemma, division-ring form**: the self-intertwiners `Hom_FG(V, V)` of an
irreducible representation form a division ring (every nonzero intertwiner is bijective,
and the inverse of a bijective intertwiner is an intertwiner). -/
noncomputable instance [ρ.IsIrreducible] : DivisionRing (IntertwiningMap ρ ρ) :=
  DivisionRing.ofIsUnitOrEqZero fun f => by
    rcases Representation.IsIrreducible.bijective_or_eq_zero f with hf | hf
    · refine Or.inl ⟨⟨f, (f.ofBijective hf).symm.toIntertwiningMap, ?_, ?_⟩, rfl⟩
      · apply Representation.IntertwiningMap.ext
        apply LinearMap.ext
        intro v
        exact (f.ofBijective hf).toLinearEquiv.apply_symm_apply v
      · apply Representation.IntertwiningMap.ext
        apply LinearMap.ext
        intro v
        exact (f.ofBijective hf).toLinearEquiv.symm_apply_apply v
    · exact Or.inr hf

/-- Over a finite field, the self-intertwiner algebra of a finite-dimensional representation
is finite.  Combined with the division-ring instance above, **Wedderburn's little theorem**
(the mathlib instance `littleWedderburn`) then makes `Hom_FG(V, V)` of an irreducible `ρ` a
**finite field** — the first half of BG Prop 2.1(c). -/
instance [Finite F] [FiniteDimensional F V] : Finite (IntertwiningMap ρ ρ) := by
  haveI : Finite V := Module.finite_of_finite F
  exact Finite.of_injective (fun f : IntertwiningMap ρ ρ => (f : V → V)) DFunLike.coe_injective

noncomputable example [Finite F] [FiniteDimensional F V] [ρ.IsIrreducible] :
    Field (IntertwiningMap ρ ρ) := inferInstance

/-- The tautological action of the self-intertwiners on the underlying space
(the analogue of `Module.End.applyModule`). -/
instance : SMul (IntertwiningMap ρ ρ) V :=
  ⟨fun f v => f v⟩

@[simp] theorem intertwiningMap_smul_def (f : IntertwiningMap ρ ρ) (v : V) : f • v = f v := rfl

instance : Module (IntertwiningMap ρ ρ) V where
  one_smul _ := rfl
  mul_smul _ _ _ := rfl
  smul_zero f := map_zero f.toLinearMap
  smul_add f v w := map_add f.toLinearMap v w
  add_smul _ _ _ := rfl
  zero_smul _ := rfl

instance : IsScalarTower F (IntertwiningMap ρ ρ) V :=
  ⟨fun _ _ _ => rfl⟩

variable (ρ) in
/-- `ρ`, regarded as a representation over the (bigger) coefficient ring
`K = Hom_FG(V, V)` of its self-intertwiners: each `ρ g` is `K`-linear precisely because the
elements of `K` intertwine `ρ`.  This is the "regard `M` as a `KG`-module" of
**BG Prop 2.1(c)**; see `isAbsolutelyIrreducible_overEnd` for the full statement. -/
def overEnd : Representation (IntertwiningMap ρ ρ) G V where
  toFun g :=
    { toFun := ρ g
      map_add' := (ρ g).map_add
      map_smul' := fun f v => (LinearMap.congr_fun (f.isIntertwining' g) v).symm }
  map_one' := by ext v; simp
  map_mul' g h := by ext v; simp [Module.End.mul_apply]

@[simp] theorem overEnd_apply (g : G) (v : V) : overEnd ρ g v = ρ g v := rfl

-- The statements below need the coefficients `K = Hom_FG(V, V)` of `overEnd ρ` to be a
-- (commutative) field, so they are stated over a finite `F`, where the `Field K` structure
-- is found by instance search (`littleWedderburn` on the `DivisionRing`/`Finite` instances
-- above).  Over a general `F` the same statements make sense over the division ring `K`,
-- but mathlib's `Representation.IsIrreducible` is field-specific.
variable [Finite F] [FiniteDimensional F V]

/-- A representation stays irreducible when regarded over its self-intertwiner field:
a `K`-subrepresentation is in particular an `F`-subrepresentation. -/
instance [ρ.IsIrreducible] : (overEnd ρ).IsIrreducible := by
  haveI : Nontrivial V := nontrivial_of_isIrreducible ρ
  haveI : Nontrivial (Subrepresentation (overEnd ρ)) := by
    obtain ⟨v, hv⟩ := exists_ne (0 : V)
    refine ⟨⊥, ⊤, fun h => hv ?_⟩
    have htop : v ∈ (⊤ : Subrepresentation (overEnd ρ)) :=
      Submodule.mem_top (R := IntertwiningMap ρ ρ) (M := V)
    rw [← h] at htop
    exact (Submodule.mem_bot (IntertwiningMap ρ ρ)).mp htop
  refine { eq_bot_or_eq_top := fun W => ?_ }
  -- the same carrier as an `F`-subrepresentation of `ρ`
  let W' : Subrepresentation ρ :=
    { toSubmodule := W.toSubmodule.restrictScalars F
      apply_mem_toSubmodule := fun g v hv => W.apply_mem_toSubmodule g hv }
  rcases eq_bot_or_eq_top W' with hW' | hW'
  · refine Or.inl (Subrepresentation.toSubmodule_injective ?_)
    have : W'.toSubmodule = ⊥ := by rw [hW']; rfl
    exact (Submodule.restrictScalars_eq_bot_iff F _ _).mp this
  · refine Or.inr (Subrepresentation.toSubmodule_injective ?_)
    have : W'.toSubmodule = ⊤ := by rw [hW']; rfl
    exact (Submodule.restrictScalars_eq_top_iff F _ _).mp this

/-- Every self-intertwiner of `overEnd ρ` is a `K`-scalar (`Hom_KG(V, V) = K` for
`K = Hom_FG(V, V)`): a `K`-linear intertwiner is in particular `F`-linear, hence an element
of `K`, and its `K`-scalar action is just its application. -/
theorem algebraMap_overEnd_intertwiningMap_surjective [ρ.IsIrreducible] :
    Function.Surjective
      (algebraMap (IntertwiningMap ρ ρ) (IntertwiningMap (overEnd ρ) (overEnd ρ))) := by
  intro φ
  -- `φ` restricted to `F`-scalars, as an element of `K = Hom_FG(V, V)`
  refine ⟨{ toFun := φ
            map_add' := φ.toLinearMap.map_add
            map_smul' := fun c v =>
              φ.toLinearMap.map_smul (algebraMap F (IntertwiningMap ρ ρ) c) v
            isIntertwining' := fun g => LinearMap.ext fun v =>
              LinearMap.congr_fun (φ.isIntertwining' g) v }, ?_⟩
  apply Representation.IntertwiningMap.ext
  apply LinearMap.ext
  intro v
  rfl

end SchurField

section AbsoluteIrreducibility

open scoped TensorProduct
open Representation

universe u

variable {F : Type u} [Field F]
variable {G : Type*} [Group G] {V : Type*} [AddCommGroup V] [Module F V]

/-- `baseChangeRepresentation K ρ g` is the base change of the linear map `ρ g`. -/
theorem baseChangeRepresentation_eq_baseChange (K : Type*) [Field K] [Algebra F K]
    (ρ : Representation F G V) (g : G) :
    baseChangeRepresentation K ρ g = LinearMap.baseChange K (ρ g) := by
  apply TensorProduct.AlgebraTensorModule.ext
  intro a v
  simp

/-- Base change maps the `F`-span of the image of `G` in `End_F V` into the `K`-span of the
image of `G` in `End_K (K ⊗ V)`. -/
theorem baseChange_mem_span_range (K : Type*) [Field K] [Algebra F K]
    (ρ : Representation F G V) {f : Module.End F V}
    (hf : f ∈ Submodule.span F (Set.range fun g : G => (ρ g : Module.End F V))) :
    LinearMap.baseChange K f ∈ Submodule.span K
      (Set.range fun g : G =>
        (baseChangeRepresentation K ρ g : Module.End K (K ⊗[F] V))) := by
  induction hf using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨g, rfl⟩ := hx
    exact Submodule.subset_span ⟨g, (baseChangeRepresentation_eq_baseChange K ρ g).symm⟩
  | zero => rw [LinearMap.baseChange_zero]; exact Submodule.zero_mem _
  | add x y _ _ ihx ihy => rw [LinearMap.baseChange_add]; exact Submodule.add_mem _ ihx ihy
  | smul c x _ ih =>
    rw [LinearMap.baseChange_smul, ← algebraMap_smul K c (LinearMap.baseChange K x)]
    exact Submodule.smul_mem _ _ ih

/-- **BG Prop 2.1(a), (⇐) direction** (general field extension, any universe): if every
self-intertwiner of the finite-dimensional irreducible `ρ` is an `F`-scalar
(`Hom_FG(M, M) = F`), then the base change of `ρ` to any extension field `K / F` remains
irreducible. -/
theorem isIrreducible_baseChangeRepresentation_of_algebraMap_surjective
    (ρ : Representation F G V) [ρ.IsIrreducible] [FiniteDimensional F V]
    (hEnd : Function.Surjective (algebraMap F (IntertwiningMap ρ ρ)))
    (K : Type*) [Field K] [Algebra F K] :
    (baseChangeRepresentation K ρ).IsIrreducible := by
  classical
  haveI : Nontrivial V := nontrivial_of_isIrreducible ρ
  -- an `F`-basis of `V` and its lift to a `K`-basis of `K ⊗ V`
  set b : Basis (Fin (Module.finrank F V)) F V := Module.finBasis F V with hb
  set bK : Basis (Fin (Module.finrank F V)) K (K ⊗[F] V) := b.baseChange K with hbK
  have hn : 0 < Module.finrank F V := Module.finrank_pos
  haveI : Nontrivial (K ⊗[F] V) := nontrivial_of_ne (bK ⟨0, hn⟩) 0 (bK.ne_zero ⟨0, hn⟩)
  haveI : Nontrivial (Subrepresentation (baseChangeRepresentation K ρ)) := by
    refine ⟨⊥, ⊤, fun h => bK.ne_zero ⟨0, hn⟩ ?_⟩
    have htop : bK ⟨0, hn⟩ ∈ (⊤ : Subrepresentation (baseChangeRepresentation K ρ)) :=
      Submodule.mem_top (R := K) (M := K ⊗[F] V)
    rw [← h] at htop
    exact (Submodule.mem_bot K).mp htop
  refine { eq_bot_or_eq_top := fun W => ?_ }
  rcases eq_or_ne W ⊥ with hW | hW
  · exact Or.inl hW
  refine Or.inr ?_
  -- a nonzero element of `W`, and a nonzero coordinate
  have hWsub : W.toSubmodule ≠ ⊥ := fun h =>
    hW (Subrepresentation.toSubmodule_injective (by rw [h]; rfl))
  obtain ⟨w, hwW, hw0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hWsub
  have hrepr : bK.repr w ≠ 0 := fun h0 => hw0 (by
    have h1 := congrArg bK.repr.symm h0
    simpa using h1)
  obtain ⟨j, hj⟩ := Finsupp.ne_iff.mp hrepr
  rw [Finsupp.coe_zero, Pi.zero_apply] at hj
  -- every pure vector `1 ⊗ m` lies in `W`
  have key : ∀ m : V, (1 : K) ⊗ₜ[F] m ∈ W.toSubmodule := by
    intro m
    -- the `F`-endomorphism `E` sending `b j ↦ m` and the other basis vectors to `0`
    set E : Module.End F V := b.constr ℕ (fun i => if i = j then m else 0) with hE_def
    have hE : E ∈ Submodule.span F (Set.range fun g : G => (ρ g : Module.End F V)) := by
      rw [span_range_representation_eq_top_of_algebraMap_intertwiningMap_surjective ρ hEnd]
      exact Submodule.mem_top
    have hEK := baseChange_mem_span_range K ρ hE
    -- every element of the `K`-span of the image of `G` preserves `W`
    have hstab : ∀ T ∈ Submodule.span K
        (Set.range fun g : G =>
          (baseChangeRepresentation K ρ g : Module.End K (K ⊗[F] V))),
        ∀ x ∈ W.toSubmodule, T x ∈ W.toSubmodule := by
      intro T hT
      induction hT using Submodule.span_induction with
      | mem T hT =>
        obtain ⟨g, rfl⟩ := hT
        exact fun x hx => W.apply_mem_toSubmodule g hx
      | zero =>
        intro x _
        rw [LinearMap.zero_apply]
        exact W.toSubmodule.zero_mem
      | add f g _ _ ihf ihg =>
        intro x hx
        rw [LinearMap.add_apply]
        exact W.toSubmodule.add_mem (ihf x hx) (ihg x hx)
      | smul c f _ ih =>
        intro x hx
        rw [LinearMap.smul_apply]
        exact W.toSubmodule.smul_mem c (ih x hx)
    -- compute `E_K w = (repr w j) • (1 ⊗ m)`
    have hEKw : LinearMap.baseChange K E w = bK.repr w j • ((1 : K) ⊗ₜ[F] m) := by
      conv_lhs => rw [← bK.sum_repr w, map_sum]
      have hterm : ∀ i, LinearMap.baseChange K E (bK.repr w i • bK i)
          = if i = j then bK.repr w i • ((1 : K) ⊗ₜ[F] m) else 0 := by
        intro i
        rw [map_smul]
        have hbKi : bK i = (1 : K) ⊗ₜ[F] b i := by simp [hbK]
        rw [hbKi, LinearMap.baseChange_tmul, hE_def, Basis.constr_basis]
        split_ifs with hij
        · rfl
        · rw [TensorProduct.tmul_zero, smul_zero]
      rw [Finset.sum_congr rfl fun i _ => hterm i]
      simp
    have hmem : bK.repr w j • ((1 : K) ⊗ₜ[F] m) ∈ W.toSubmodule := by
      rw [← hEKw]; exact hstab _ hEK w hwW
    have hmem' := W.toSubmodule.smul_mem (bK.repr w j)⁻¹ hmem
    rwa [smul_smul, inv_mul_cancel₀ hj, one_smul] at hmem'
  -- conclude `W = ⊤`
  apply Subrepresentation.toSubmodule_injective
  change W.toSubmodule = ⊤
  refine le_antisymm le_top ?_
  rw [← bK.span_eq, Submodule.span_le]
  rintro _ ⟨i, rfl⟩
  have hbKi : bK i = (1 : K) ⊗ₜ[F] b i := by simp [hbK]
  rw [hbKi]
  exact key (b i)

/-- **BG Prop 2.1(a), (⇒) direction** (via the algebraic closure): if the base change of `ρ`
to the algebraic closure of `F` is irreducible, then every self-intertwiner of `ρ` is an
`F`-scalar (`Hom_FG(M, M) = F`). -/
theorem algebraMap_surjective_of_isIrreducible_baseChangeRepresentation
    (ρ : Representation F G V) [FiniteDimensional F V]
    (h : (baseChangeRepresentation (AlgebraicClosure F) ρ).IsIrreducible) :
    Function.Surjective (algebraMap F (IntertwiningMap ρ ρ)) := by
  classical
  set K := AlgebraicClosure F with hK
  haveI : Nontrivial (K ⊗[F] V) := nontrivial_of_isIrreducible (baseChangeRepresentation K ρ)
  haveI : Nontrivial V := by
    by_contra hV
    rw [not_nontrivial_iff_subsingleton] at hV
    haveI : Subsingleton (K ⊗[F] V) := by
      refine ⟨fun x y => ?_⟩
      have hzero : ∀ z : K ⊗[F] V, z = 0 := by
        intro z
        induction z with
        | zero => rfl
        | tmul a v => rw [Subsingleton.elim v 0, TensorProduct.tmul_zero]
        | add x y ihx ihy => rw [ihx, ihy, add_zero]
      rw [hzero x, hzero y]
    exact false_of_nontrivial_of_subsingleton (K ⊗[F] V)
  intro f
  -- `f` base-changes to a self-intertwiner of `ρ_K`
  have hcomm : ∀ (g : G) (x : K ⊗[F] V),
      LinearMap.baseChange K f.toLinearMap (baseChangeRepresentation K ρ g x)
        = baseChangeRepresentation K ρ g (LinearMap.baseChange K f.toLinearMap x) := by
    intro g x
    induction x with
    | zero => simp
    | tmul a v =>
      rw [baseChangeRepresentation_apply_tmul, LinearMap.baseChange_tmul,
        LinearMap.baseChange_tmul, baseChangeRepresentation_apply_tmul]
      congr 1
      exact LinearMap.congr_fun (f.isIntertwining' g) v
    | add x y ihx ihy => rw [map_add, map_add, ihx, ihy, ← map_add, ← map_add]
  set fK : IntertwiningMap (baseChangeRepresentation K ρ) (baseChangeRepresentation K ρ) :=
    (LinearMap.baseChange K f.toLinearMap).intertwiningMap_of_isIntertwiningMap
      (baseChangeRepresentation K ρ) (baseChangeRepresentation K ρ) hcomm with hfK
  -- Schur over the algebraically closed `K`: `fK` is a `K`-scalar `c`
  obtain ⟨c, hc⟩ :=
    (Representation.IsIrreducible.algebraMap_intertwiningMap_bijective_of_isAlgClosed
      (ρ := baseChangeRepresentation K ρ)).2 fK
  have hcx : ∀ x : K ⊗[F] V, c • x = LinearMap.baseChange K f.toLinearMap x := by
    intro x
    have hx := DFunLike.congr_fun hc x
    rw [Representation.IntertwiningMap.algebraMap_apply] at hx
    simpa [hfK, Representation.IntertwiningMap.smul_apply] using hx
  -- read off the scalar in coordinates: `c = algebraMap F K a`
  set b : Basis (Fin (Module.finrank F V)) F V := Module.finBasis F V with hb
  set bK : Basis (Fin (Module.finrank F V)) K (K ⊗[F] V) := b.baseChange K with hbK
  have hn : 0 < Module.finrank F V := Module.finrank_pos
  set i₀ : Fin (Module.finrank F V) := ⟨0, hn⟩ with hi₀
  set a : F := b.repr (f.toLinearMap (b i₀)) i₀ with ha
  have hca : c = algebraMap F K a := by
    have hx := hcx ((1 : K) ⊗ₜ[F] b i₀)
    rw [LinearMap.baseChange_tmul] at hx
    have hx' := congrArg (fun z => bK.repr z i₀) hx
    simp only [map_smul, Finsupp.smul_apply, hbK, Basis.baseChange_repr_tmul,
      Basis.repr_self, Finsupp.single_eq_same, smul_eq_mul] at hx'
    rw [ha]
    calc c = c * ((1 : F) • (1 : K)) := by rw [one_smul, mul_one]
      _ = b.repr (f.toLinearMap (b i₀)) i₀ • (1 : K) := hx'
      _ = algebraMap F K (b.repr (f.toLinearMap (b i₀)) i₀) := by
          rw [Algebra.smul_def, mul_one]
  refine ⟨a, ?_⟩
  apply Representation.IntertwiningMap.ext
  apply LinearMap.ext
  intro v
  -- goal: `a • v = f v`; both sides agree after `1 ⊗ ·`, which is injective
  have h1 : (1 : K) ⊗ₜ[F] (a • v) = (1 : K) ⊗ₜ[F] (f.toLinearMap v) := by
    rw [TensorProduct.tmul_smul, ← algebraMap_smul K a ((1 : K) ⊗ₜ[F] v), ← hca,
      hcx ((1 : K) ⊗ₜ[F] v), LinearMap.baseChange_tmul]
  have hv := Module.FaithfullyFlat.tensorProduct_mk_injective (A := F) (B := K) V h1
  simpa using hv

variable (ρ : Representation F G V)

/-- **Absolute irreducibility** (BG §2, before Prop 2.1): `ρ` is absolutely irreducible if it
stays irreducible under every field extension `K / F`.

(`K` ranges over the universe of `F`; this loses no generality — see
`IsAbsolutelyIrreducible.baseChangeRepresentation_isIrreducible` for arbitrary universes.) -/
def IsAbsolutelyIrreducible : Prop :=
  ∀ (K : Type u) [Field K] [Algebra F K], (baseChangeRepresentation K ρ).IsIrreducible

variable {ρ}

/-- **BG Proposition 2.1(a)** (p. 10): an irreducible `FG`-module `M` is absolutely
irreducible if and only if `Hom_FG(M, M) = F` (every self-intertwiner is an `F`-scalar). -/
theorem isAbsolutelyIrreducible_iff_bijective_algebraMap
    [ρ.IsIrreducible] [FiniteDimensional F V] :
    IsAbsolutelyIrreducible ρ ↔ Function.Bijective (algebraMap F (IntertwiningMap ρ ρ)) := by
  constructor
  · intro h
    haveI : Nontrivial V := nontrivial_of_isIrreducible ρ
    haveI : Nontrivial (IntertwiningMap ρ ρ) := by
      obtain ⟨v, hv⟩ := exists_ne (0 : V)
      exact ⟨1, 0, fun h10 => hv (by simpa using DFunLike.congr_fun h10 v)⟩
    exact ⟨(algebraMap F (IntertwiningMap ρ ρ)).injective,
      algebraMap_surjective_of_isIrreducible_baseChangeRepresentation ρ
        (h (AlgebraicClosure F))⟩
  · intro h K _ _
    exact isIrreducible_baseChangeRepresentation_of_algebraMap_surjective ρ h.2 K

/-- Absolute irreducibility gives irreducibility of the base change to *any* extension field,
in any universe (removing the same-universe restriction in the definition). -/
theorem IsAbsolutelyIrreducible.baseChangeRepresentation_isIrreducible
    [ρ.IsIrreducible] [FiniteDimensional F V] (h : IsAbsolutelyIrreducible ρ)
    (K : Type*) [Field K] [Algebra F K] :
    (baseChangeRepresentation K ρ).IsIrreducible :=
  isIrreducible_baseChangeRepresentation_of_algebraMap_surjective ρ
    (isAbsolutelyIrreducible_iff_bijective_algebraMap.mp h).2 K

/-- **BG Proposition 2.1(c)** (p. 10): if `F` is a finite field and `M` is an irreducible
`FG`-module, then `K = Hom_FG(M, M)` is a finite field (Schur's lemma + Wedderburn's little
theorem — the `Field K` structure here is found by the mathlib instance `littleWedderburn`
through the `DivisionRing`/`Finite` instances above), and `M`, regarded as a `KG`-module via
`overEnd`, is *absolutely* irreducible. -/
theorem isAbsolutelyIrreducible_overEnd [Finite F] [ρ.IsIrreducible] [FiniteDimensional F V] :
    IsAbsolutelyIrreducible (overEnd ρ) := by
  haveI : FiniteDimensional (IntertwiningMap ρ ρ) V :=
    Module.Finite.of_restrictScalars_finite F (IntertwiningMap ρ ρ) V
  rw [isAbsolutelyIrreducible_iff_bijective_algebraMap]
  exact ⟨(algebraMap (IntertwiningMap ρ ρ)
      (IntertwiningMap (overEnd ρ) (overEnd ρ))).injective,
    algebraMap_overEnd_intertwiningMap_surjective⟩

end AbsoluteIrreducibility

end OddOrder.RepresentationTheory
