/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.RepresentationTheory.Basic
import Mathlib.RepresentationTheory.Irreducible
import Mathlib.RepresentationTheory.AlgebraRepresentation.Basic
import Mathlib.RingTheory.SimpleModule.Basic
import Mathlib.RingTheory.SimpleModule.IsAlgClosed
import Mathlib.RingTheory.Finiteness.Basic
import Mathlib.RingTheory.IntegralDomain
import Mathlib.FieldTheory.IsAlgClosed.Basic

/-!
# Burnside's theorem over an algebraically closed field (BG §2 Prop 2.1)

`OddOrder.GroupTheory.RepresentationTheory` shared module: the
**Bender-Glauberman §2 Prop 2.1 / Burnside** statement that for a faithful
absolutely irreducible representation the *enveloping algebra* — the image of
the group ring inside `End_F V` — is the whole of `End_F V`.

We prove the general module-theoretic form: if `M` is a finite-dimensional
simple module over an `F`-algebra `A`, with `F` algebraically closed, then the
structure ring hom `A → End_F M` (sending `a` to the `F`-linear map `m ↦ a • m`)
is **surjective**.

## Proof

This is the classical Burnside theorem, and over an algebraically closed field
it follows directly from two facts already in mathlib:

* **Schur's lemma** (`IsSimpleModule.algebraMap_end_bijective_of_isAlgClosed`):
  over an algebraically closed `F`, the commutant `D := End_A M` is just the
  scalars, i.e. `algebraMap F D` is bijective.
* **The Jacobson density theorem**
  (`Module.Finite.toModuleEnd_moduleEnd_surjective`): for a semisimple module
  finite over its endomorphism ring `D`, the map `A → End_D M` is surjective.

Since `D = F` (scalars), an `F`-linear endomorphism of `M` is automatically
`D`-linear, so `End_D M = End_F M`, and Jacobson density becomes exactly the
surjectivity of `A → End_F M`.

## BG ↔ mathlib mapping

* **BG Thm 2.5** uses this as `E(P) = Hom_F(V, V)` for a faithful irreducible
  `V` of an extraspecial group `P` over an algebraically closed field.
  Faithfulness is *not* needed for surjectivity — simplicity suffices.
-/

namespace OddOrder.RepresentationTheory

open Module

section Burnside

variable {F : Type*} [Field F] [IsAlgClosed F]
variable {A : Type*} [Ring A] [Algebra F A]
variable {M : Type*} [AddCommGroup M] [Module F M] [Module A M] [IsScalarTower F A M]
variable [IsSimpleModule A M] [FiniteDimensional F M]

/-- **Burnside's theorem** (BG Prop 2.1, module form): for a finite-dimensional
simple module `M` over an `F`-algebra `A` with `F` algebraically closed, the
structure ring hom `A → End_F M`, `a ↦ (m ↦ a • m)`, is surjective.

Equivalently: the *enveloping algebra* — the `F`-subalgebra of `End_F M`
generated by the image of `A` — is the whole of `End_F M`. -/
theorem toModuleEnd_surjective_of_isAlgClosed :
    Function.Surjective (Module.toModuleEnd F M (S := A)) := by
  classical
  -- `F` commutes with `A` on `M` (both act through the central image of `F`).
  haveI : SMulCommClass A F M := ⟨fun a c m => by
    rw [← IsScalarTower.algebraMap_smul A c m, ← IsScalarTower.algebraMap_smul A c (a • m),
        smul_smul, smul_smul, Algebra.commutes]⟩
  -- `M` is finite over the (bigger) endomorphism ring `D := End_A M`.
  haveI : Module.Finite (Module.End A M) M :=
    Module.Finite.of_restrictScalars_finite F (Module.End A M) M
  -- Schur over an algebraically closed field: `D = End_A M` is just the scalars.
  have hSchur : Function.Surjective (algebraMap F (Module.End A M)) :=
    (IsSimpleModule.algebraMap_end_bijective_of_isAlgClosed (A := A) (V := M) F).2
  -- The scalar action of `D` on `M` agrees with the `F`-action.
  have key : ∀ (c : F) (x : M), (algebraMap F (Module.End A M) c) • x = c • x := by
    intro c x
    rw [Module.End.smul_def, Algebra.algebraMap_eq_smul_one, LinearMap.smul_apply,
      Module.End.one_apply]
  intro g
  -- Realise `g : End_F M` as a `D`-linear map, using that every `d ∈ D` is a scalar.
  let g' : M →ₗ[Module.End A M] M :=
    { toFun := g
      map_add' := g.map_add
      map_smul' := by
        intro d m
        obtain ⟨c, hc⟩ := hSchur d
        simp only [RingHom.id_apply, ← hc, key c m, key c (g m), map_smul] }
  -- Jacobson density: `A → End_D M` is surjective; pull back `g'`.
  obtain ⟨a, ha⟩ := Module.Finite.toModuleEnd_moduleEnd_surjective (R := A) (M := M) g'
  refine ⟨a, ?_⟩
  ext m
  have hm := LinearMap.congr_fun ha m
  simpa [g'] using hm

end Burnside

section Representation

open scoped MonoidAlgebra

variable {F : Type*} [Field F] [IsAlgClosed F]
variable {G : Type*} [Monoid G] {V : Type*} [AddCommGroup V] [Module F V]

set_option backward.isDefEq.respectTransparency false in
/-- **Burnside's theorem** (BG Prop 2.1, representation form): for a
finite-dimensional irreducible representation `ρ` of `G` over an algebraically
closed field `F`, the algebra hom `ρ.asAlgebraHom : F[G] →ₐ[F] End_F V` is
surjective. Equivalently, the *enveloping algebra* `E(G)` (the `F`-span of the
image of `G` in `End_F V`) is all of `End_F V = Hom_F(V, V)`.

This is the form `BG Thm 2.5` uses (as `E(P) = Hom_F(V, V)`). -/
theorem asAlgebraHom_surjective_of_isAlgClosed (ρ : Representation F G V)
    [ρ.IsIrreducible] [FiniteDimensional F V] :
    Function.Surjective ρ.asAlgebraHom := by
  -- Module-form Burnside applied with `A := F[G]`, `M := ρ.asModule`.  `ρ.asModule` is
  -- definitionally `V` and the `F[G]`-action `r • x` is `ρ.asAlgebraHom r x`, so
  -- `Module.toModuleEnd F ρ.asModule` and `ρ.asAlgebraHom` are the *same* map.  The
  -- relaxed-transparency option lets instance search see through the `asModule` synonym
  -- (the idiom mathlib uses for the `IsScalarTower k k[G] ρ.asModule` instance).
  have hsurj := toModuleEnd_surjective_of_isAlgClosed (F := F) (A := MonoidAlgebra F G)
    (M := ρ.asModule)
  intro h
  obtain ⟨r, hr⟩ := hsurj h
  exact ⟨r, hr⟩

/-- **Burnside, span form** (BG Prop 2.1): for a finite-dimensional irreducible representation `ρ`
over an algebraically closed field, the images `{ρ g : g ∈ G}` span `End_F V`. (Equivalent to
`asAlgebraHom_surjective_of_isAlgClosed`; the convenient form for building the Burnside basis.) -/
theorem span_range_representation_eq_top (ρ : Representation F G V)
    [ρ.IsIrreducible] [FiniteDimensional F V] :
    Submodule.span F (Set.range fun g : G => ρ g) = ⊤ := by
  rw [eq_top_iff]
  rintro e -
  obtain ⟨r, rfl⟩ := asAlgebraHom_surjective_of_isAlgClosed ρ e
  induction r using MonoidAlgebra.induction_on with
  | hM g => rw [Representation.asAlgebraHom_of]; exact Submodule.subset_span ⟨g, rfl⟩
  | hadd x y hx hy => rw [map_add]; exact Submodule.add_mem _ hx hy
  | hsmul c x hx => rw [map_smul]; exact Submodule.smul_mem _ c hx

end Representation

section CentralCharacter

variable {F : Type*} [Field F] [IsAlgClosed F]
variable {G : Type*} [Group G] {V : Type*} [AddCommGroup V] [Module F V]

/-- **Central scalar action** (Schur, central character): for a finite-dimensional irreducible
representation `ρ` over an algebraically closed field `F`, every central element `z ∈ Z(G)` acts
on `V` by a scalar `c • id`. (This is the existence half of the central character used in the
representation theory of extraspecial groups, BG Thm 2.5 / Gor 5.5.5.) -/
theorem center_isScalar (ρ : Representation F G V) [ρ.IsIrreducible] [FiniteDimensional F V]
    {z : G} (hz : z ∈ Subgroup.center G) :
    ∃ c : F, ρ z = c • LinearMap.id := by
  -- `ρ z` commutes with every `ρ g` (`z` is central), so it is an intertwiner `ρ → ρ`.
  have hcomm : ∀ (g : G) (v : V), (ρ z) ((ρ g) v) = (ρ g) ((ρ z) v) := fun g v => by
    rw [← Module.End.mul_apply, ← Module.End.mul_apply, ← map_mul, ← map_mul,
      Subgroup.mem_center_iff.mp hz g]
  -- Over an algebraically closed field every self-intertwiner of an irreducible is a scalar.
  have hbij :=
    (Representation.IsIrreducible.algebraMap_intertwiningMap_bijective_of_isAlgClosed (ρ := ρ)).2
  obtain ⟨c, hc⟩ := hbij ((ρ z).intertwiningMap_of_isIntertwiningMap ρ ρ hcomm)
  refine ⟨c, ?_⟩
  ext v
  -- `algebraMap F (IntertwiningMap ρ ρ) c` is `c • 1` and its coercion at `v` is `c • v`; the
  -- built intertwiner's coercion at `v` is `ρ z v`.  All these are `rfl`, so this typechecks.
  have hv : c • v = (ρ z) v := DFunLike.congr_fun hc v
  simpa using hv.symm

/-- **Gorenstein Theorem 3.2.2** (cyclic centre from a faithful irreducible).  A finite group `G`
with a faithful irreducible representation on a nonzero finite-dimensional space over an
algebraically closed field has cyclic centre `Z(G)`.

By `center_isScalar` each central `z` acts as a scalar `c(z) • 1`; the scalar is determined by the
operator (`V ≠ 0`), so `z ↦ c(z)` is a group homomorphism `Z(G) →* F` into the field's
multiplicative monoid, injective because `ρ` is faithful.  A finite group with an injective
homomorphism into an integral domain is cyclic (`isCyclic_of_injective_ringHom`).

This is the input to BG Theorem 3.4 (`Z(K) ⊆ Z(G)` cyclic ⟹ the special group `K` is
extraspecial). -/
theorem isCyclic_center_of_faithful_irreducible [Finite G] [FiniteDimensional F V] [Nontrivial V]
    (ρ : Representation F G V) [ρ.IsIrreducible] (hf : Function.Injective ρ) :
    IsCyclic (Subgroup.center G) := by
  classical
  -- the central scalar `c z`, characterised by `ρ z = c z • 1`
  let c : ↥(Subgroup.center G) → F := fun z => Classical.choose (center_isScalar ρ z.property)
  -- `1 : Module.End F V` is `LinearMap.id` definitionally, and `c z` is the chosen scalar
  have hc : ∀ z : ↥(Subgroup.center G), ρ (z : G) = c z • (1 : Module.End F V) := fun z =>
    Classical.choose_spec (center_isScalar ρ z.property)
  -- a nonzero operator determines its scalar (`V ≠ 0`)
  have huniq : ∀ {a b : F}, a • (1 : Module.End F V) = b • (1 : Module.End F V) → a = b := by
    intro a b hab
    obtain ⟨v, hv⟩ := exists_ne (0 : V)
    have hv2 : a • v = b • v := by simpa using DFunLike.congr_fun hab v
    rcases smul_eq_zero.mp (show (a - b) • v = 0 by rw [sub_smul, hv2, sub_self]) with h | h
    · exact sub_eq_zero.mp h
    · exact absurd h hv
  -- the central character `Z(G) →* F`
  let f : ↥(Subgroup.center G) →* F :=
    { toFun := c
      map_one' := by
        have h1 := hc 1
        rw [Subgroup.coe_one, map_one] at h1
        have h1' : (1 : F) • (1 : Module.End F V) = c 1 • 1 := by rw [one_smul]; exact h1
        exact (huniq h1').symm
      map_mul' := fun z₁ z₂ => by
        have h12 := hc (z₁ * z₂)
        rw [Subgroup.coe_mul, map_mul, hc z₁, hc z₂, smul_mul_smul_comm, mul_one] at h12
        exact (huniq h12).symm }
  -- faithfulness ⟹ injective
  have hf_inj : Function.Injective f := by
    intro z₁ z₂ h
    have hcc : c z₁ = c z₂ := h
    exact Subtype.ext (hf (by rw [hc z₁, hc z₂, hcc]))
  exact isCyclic_of_injective_ringHom f hf_inj

/-- **Burnside basis, spanning step.** A transversal `{ρ(out c) : c ∈ G/Z}` of the central cosets
still spans `End_F V`: every `ρ g` is a scalar multiple of `ρ(out (gZ))` (central character), so the
span is unchanged from `span_range_representation_eq_top`. -/
theorem span_range_quotient_out_eq_top (ρ : Representation F G V)
    [ρ.IsIrreducible] [FiniteDimensional F V] :
    Submodule.span F
      (Set.range fun c : G ⧸ Subgroup.center G => ρ (Quotient.out c)) = ⊤ := by
  rw [eq_top_iff, ← span_range_representation_eq_top ρ, Submodule.span_le]
  rintro _ ⟨g, rfl⟩
  set c₀ : G ⧸ Subgroup.center G := (g : G ⧸ Subgroup.center G) with hc₀
  have hz : (Quotient.out c₀)⁻¹ * g ∈ Subgroup.center G :=
    QuotientGroup.eq.mp (Quotient.out_eq c₀)
  obtain ⟨c, hc⟩ := center_isScalar ρ hz
  have hg : ρ g = c • ρ (Quotient.out c₀) := by
    have hsplit : g = Quotient.out c₀ * ((Quotient.out c₀)⁻¹ * g) := by group
    rw [hsplit, map_mul, hc]
    ext v
    simp [Module.End.mul_apply]
  change ρ g ∈ Submodule.span F (Set.range fun c : G ⧸ Subgroup.center G => ρ (Quotient.out c))
  rw [hg]
  exact Submodule.smul_mem _ c (Submodule.subset_span ⟨c₀, rfl⟩)

end CentralCharacter

end OddOrder.RepresentationTheory
