/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.Analysis.Complex.Polynomial.Basic
import Mathlib.RepresentationTheory.Irreducible
import Mathlib.RepresentationTheory.Subrepresentation
import Mathlib.RepresentationTheory.Character
import Mathlib.LinearAlgebra.Trace
import Mathlib.Algebra.Algebra.Subalgebra.Basic
import Mathlib.Algebra.Group.Conj
import Mathlib.GroupTheory.PGroup
import Mathlib.RingTheory.IntegralClosure.IsIntegral.Basic
import Mathlib.RingTheory.IntegralClosure.IntegrallyClosed
import Mathlib.RingTheory.Finiteness.Basic
import Mathlib.LinearAlgebra.Eigenspace.Charpoly
import Mathlib.FieldTheory.IsAlgClosed.Basic
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.RingTheory.Polynomial.RationalRoot

/-!
# The class-sum algebra and central characters

This module formalizes the **class-sum algebra** of a finite group `G` and the **central
characters** attached to its irreducible representations, the apparatus used in **Isaacs,
_Character Theory of Finite Groups_ (Academic Press, 1976), §3 (p. 35)** and invoked by
**Peterfalvi (6.7.2)** (LMS LNS 272, pp. 31–32).

For a conjugacy class `C` of `G`, the **class sum** `classSum C = ∑_{x ∈ C} x` is an element of
the group algebra `ℂ[G]`.  Because conjugation permutes each class, every class sum is central in
`ℂ[G]`.  The products of class sums expand with *natural-number* structure coefficients
`a_{ijs}` (Peterfalvi's `a_{ijs} ∈ ℕ`): `C_i · C_j = ∑_s a_{ijs} · C_s`.

To each finite-dimensional irreducible complex representation `ρ` of `G` Schur's lemma attaches a
**central character** `ω_ρ : Z(ℂ[G]) →ₐ[ℂ] ℂ`: a central element `x` acts on `V` as a scalar
`ω_ρ(x)`, and `x ↦ ω_ρ(x)` is a `ℂ`-algebra homomorphism.  On a class sum it evaluates to
`ω_ρ(C) = |C| · χ_ρ(g) / χ_ρ(1)` for any `g ∈ C` (Isaacs (3.6); Peterfalvi (6.7.2)).

## Main definitions and results

* `OddOrder.RepresentationTheory.classSum` — the class sum `∑_{x ∈ C} x ∈ ℂ[G]`.
* `OddOrder.RepresentationTheory.classSum_mem_center` — each class sum is central in `ℂ[G]`.
* `OddOrder.RepresentationTheory.classSumCoeff` — the structure coefficients `a_{ijs} ∈ ℕ`.
* `OddOrder.RepresentationTheory.classSum_mul` — `C_i · C_j = ∑_s a_{ijs} · C_s`.
* `OddOrder.RepresentationTheory.exists_central_scalar_asAlgebraHom` — Schur: a central element of
  `ℂ[G]` acts on an irreducible representation as a scalar.
* `OddOrder.RepresentationTheory.centralCharacterOfRep` — the central-character algebra hom
  `ω_ρ : Z(ℂ[G]) →ₐ[ℂ] ℂ`.
* `OddOrder.RepresentationTheory.centralCharacterOfRep_classSum` — its value on a class sum,
  `ω_ρ(C) = |C| · χ_ρ(g) / χ_ρ(1)`.
* `OddOrder.RepresentationTheory.classSum_mul` — the explicit integer expansion
  `C_i · C_j = ∑_s m_s · C_s` (`m_s` = per-element factorization count, constant on the class).
* `OddOrder.RepresentationTheory.centralCharacterOfRep_classSum_isIntegral` — **`ω_ρ(C)` is an
  algebraic integer** (`IsIntegral ℤ`), the structure-coefficient integrality used in the `mod |P|`
  congruence of (6.7.3).  Proof: the `ℤ`-subalgebra of `ℂ` generated by the finitely many `ω_ρ(C_s)`
  is module-finite (it is closed under multiplication by `classSum_mul`), so all its elements are
  integral.  See `notes/peterfalvi/s08_coherence_theorems.md`.
* `OddOrder.RepresentationTheory.isIntegral_card_mul_character_div` — the explicit character-value
  form: **`|C| · χ_ρ(g) / χ_ρ(1)` is an algebraic integer**.
* `OddOrder.RepresentationTheory.character_isIntegral` — **character values `χ_ρ(g)` are algebraic
  integers** (sum of roots of unity; the eigenvalues of the finite-order `ρ g`).
* `OddOrder.RepresentationTheory.isIntegral_rat_imp_int` — **a rational algebraic integer is an
  integer** (`ℤ` integrally closed, transferred along `ℚ ↪ ℂ`).
* `OddOrder.RepresentationTheory.finrank_dvd_card` — **`χ_ρ(1) ∣ |G|`** (Isaacs Thm 3.11): for `ρ`
  irreducible, `dim V` divides `|G|`.  The first orthogonality relation regrouped over conjugacy
  classes writes `|G| / χ_ρ(1) = ∑_C ω_ρ(C) · χ_ρ((g_C)⁻¹)` as a sum of products of algebraic
  integers, hence a rational algebraic integer ⇒ integer.
* `OddOrder.RepresentationTheory.exists_finrank_eq_prime_pow_of_isPGroup` — **the degree of an
  irreducible representation of a finite `p`-group is a power of `p`** (Isaacs Cor. 3.12): from
  `finrank_dvd_card` together with `|G| = p ^ n` and `Nat.dvd_prime_pow`.

## References

* I. M. Isaacs, *Character Theory of Finite Groups*, Academic Press 1976, Thm 3.11
  (`finrank_dvd_card`).

* I. M. Isaacs, *Character Theory of Finite Groups*, Academic Press 1976, §3 (p. 35), (3.6).
* Peterfalvi, *Character Theory for the Odd Order Theorem*, (6.7.2).
-/

namespace OddOrder.RepresentationTheory

open scoped MonoidAlgebra
open Module (finrank)
open Representation

variable {G : Type*} [Group G]

section ClassSum

variable [Fintype G] [DecidableEq (ConjClasses G)]

/-- The **class sum** of a conjugacy class `C` of `G`: the element `∑_{x ∈ C} x` of the group
algebra `ℂ[G]`.  This is Peterfalvi's `C_s` and Isaacs' `\hat C` (§3, p. 35). -/
noncomputable def classSum (C : ConjClasses G) : ℂ[G] :=
  ∑ g : G, if ConjClasses.mk g = C then MonoidAlgebra.of ℂ G g else 0

/-- The coefficient of `classSum C` at a group element `x` is `1` if `x` lies in the class `C`
and `0` otherwise. -/
theorem classSum_apply (C : ConjClasses G) (x : G) :
    classSum C x = if ConjClasses.mk x = C then 1 else 0 := by
  classical
  have hsum : classSum C x
      = ∑ g : G, (if ConjClasses.mk g = C then MonoidAlgebra.of ℂ G g else 0) x := by
    rw [classSum]; exact map_sum (Finsupp.applyAddHom x) _ Finset.univ
  -- `(0 : ℂ[G]) y = 0` (the `MonoidAlgebra` zero coefficient), used below.
  have hzero : ∀ y : G, (0 : MonoidAlgebra ℂ G) y = 0 := fun _ => rfl
  -- The coefficient of each summand at `x`: `1` if `g = x` and `mk g = C`, else `0`.
  have hterm : ∀ g : G, (if ConjClasses.mk g = C then MonoidAlgebra.of ℂ G g else 0) x
      = if g = x then (if ConjClasses.mk g = C then (1 : ℂ) else 0) else 0 := by
    intro g
    rw [apply_ite (fun f : MonoidAlgebra ℂ G => f x), MonoidAlgebra.of_apply,
      MonoidAlgebra.single_apply, hzero x]
    by_cases hg : g = x
    · rw [if_pos hg, if_pos hg]
    · rw [if_neg hg, if_neg hg, ite_self]
  rw [hsum, Finset.sum_congr rfl (fun g _ => hterm g),
    Finset.sum_ite_eq' Finset.univ x (fun g => if ConjClasses.mk g = C then (1 : ℂ) else 0)]
  simp

/-- **Class sums are central in `ℂ[G]`.** Conjugation by any group element permutes each conjugacy
class, so `classSum C` commutes with every basis element `of ℂ G h`, hence with all of `ℂ[G]`.
(Isaacs §3; Peterfalvi (6.7.2).) -/
theorem classSum_mem_center (C : ConjClasses G) :
    classSum C ∈ Subalgebra.center ℂ (ℂ[G]) := by
  classical
  rw [Subalgebra.mem_center_iff]
  intro a
  -- Reduce to basis elements `a = single h r` by linearity.
  induction a using MonoidAlgebra.induction_linear with
  | zero => simp
  | add x y hx hy => rw [add_mul, mul_add, hx, hy]
  | single h r =>
    -- `single h r = r • of ℂ G h`, and scalars commute, so reduce to `of ℂ G h`.
    have hof : (MonoidAlgebra.single h r : ℂ[G]) = r • MonoidAlgebra.of ℂ G h := by
      rw [MonoidAlgebra.of_apply, MonoidAlgebra.smul_single, smul_eq_mul, mul_one]
    rw [hof, smul_mul_assoc, mul_smul_comm]
    congr 1
    -- Goal: `of h * classSum C = classSum C * of h`.
    rw [classSum, Finset.mul_sum, Finset.sum_mul]
    -- LHS term: `of h * (if mk g = C then of g else 0)`; reindex `g ↦ h * g * h⁻¹`.
    rw [← Equiv.sum_comp (MulAut.conj h).toEquiv
      (fun g => (if ConjClasses.mk g = C then MonoidAlgebra.of ℂ G g else 0) *
        MonoidAlgebra.of ℂ G h)]
    refine Finset.sum_congr rfl fun g _ => ?_
    have hconj : (MulAut.conj h).toEquiv g = h * g * h⁻¹ := by simp [MulAut.conj_apply]
    rw [hconj]
    have hclass : ConjClasses.mk (h * g * h⁻¹) = ConjClasses.mk g :=
      ConjClasses.mk_eq_mk_iff_isConj.mpr (isConj_iff.mpr ⟨h⁻¹, by group⟩)
    rw [hclass]
    by_cases h0 : ConjClasses.mk g = C
    · simp only [h0, if_true]
      rw [← map_mul, ← map_mul]
      congr 1
      group
    · simp [h0]

end ClassSum

section StructureCoeff

variable [Fintype G] [DecidableEq G] [DecidableEq (ConjClasses G)]

/-- The **structure coefficient** `a_{ijs}`: the number of ordered pairs `(u, v)` with `u ∈ C_i`,
`v ∈ C_j`, and `u·v ∈ C_s`.  These are the natural numbers in Peterfalvi's `C_i · C_j = ∑_s a_{ijs}
· C_s` (note that the coefficient of the *class sum* `C_s` in that combination is `a_{ijs}/|C_s|`;
the unscaled `a_{ijs}` counts pairs over the whole class). -/
noncomputable def classSumCoeff (Ci Cj Cs : ConjClasses G) : ℕ :=
  (Finset.univ.filter (fun p : G × G =>
    ConjClasses.mk p.1 = Ci ∧ ConjClasses.mk p.2 = Cj ∧ ConjClasses.mk (p.1 * p.2) = Cs)).card

/-- **Coefficient of a product of class sums at a group element.** The coefficient of `w` in
`classSum Ci * classSum Cj` is the number of factorizations `w = u·v` with `u ∈ C_i` and `v ∈ C_j`.
(This per-element count is constant on each conjugacy class; summing it over a class `C_s` recovers
the structure coefficient `classSumCoeff Ci Cj Cs`.) -/
theorem classSum_mul_apply (Ci Cj : ConjClasses G) (w : G) :
    (classSum Ci * classSum Cj) w =
      (Finset.univ.filter (fun p : G × G =>
        ConjClasses.mk p.1 = Ci ∧ ConjClasses.mk p.2 = Cj ∧ p.1 * p.2 = w)).card := by
  classical
  -- Expand the product coefficient over all pairs `(u, v)` with `u * v = w`.
  have hexp := MonoidAlgebra.mul_apply_antidiagonal (classSum Ci) (classSum Cj) w
    (Finset.univ.filter (fun p : G × G => p.1 * p.2 = w)) (by intro p; simp)
  rw [hexp]
  -- Each summand is the product of two `0/1` indicators; combine into a single indicator.
  have hbody : ∀ p : G × G,
      (classSum Ci p.1) * (classSum Cj p.2)
        = if ConjClasses.mk p.1 = Ci ∧ ConjClasses.mk p.2 = Cj then (1 : ℂ) else 0 := by
    intro p
    rw [classSum_apply, classSum_apply, ite_and]
    by_cases h1 : ConjClasses.mk p.1 = Ci <;> by_cases h2 : ConjClasses.mk p.2 = Cj <;>
      simp [h1, h2]
  rw [Finset.sum_congr rfl (fun p _ => hbody p)]
  -- Sum of a `0/1` indicator over the antidiagonal is the cardinality of the counted set.
  rw [Finset.sum_ite, Finset.sum_const_zero, add_zero, Finset.sum_const, nsmul_eq_mul, mul_one]
  norm_cast
  apply congrArg Finset.card
  ext p
  simp only [Finset.mem_filter, Finset.mem_univ, true_and]
  constructor
  · rintro ⟨hw, hi, hj⟩; exact ⟨hi, hj, hw⟩
  · rintro ⟨hi, hj, hw⟩; exact ⟨hw, hi, hj⟩

omit [Fintype G] [DecidableEq G] [DecidableEq (ConjClasses G)] in
/-- The conjugacy class of `h * g * h⁻¹` is the same as that of `g`. -/
private theorem mk_conj_eq (h g : G) : ConjClasses.mk (h * g * h⁻¹) = ConjClasses.mk g :=
  ConjClasses.mk_eq_mk_iff_isConj.mpr (isConj_iff.mpr ⟨h⁻¹, by group⟩)

omit [DecidableEq G] in
/-- The per-element product coefficient `(classSum Ci * classSum Cj) w` is a **class function** of
`w`: conjugating `w` by any group element leaves the number of factorizations unchanged.  (The
bijection `(u, v) ↦ (h u h⁻¹, h v h⁻¹)` preserves the class of each factor and maps `u·v = w` to
`(h u h⁻¹)·(h v h⁻¹) = h w h⁻¹`.) -/
theorem classSum_mul_apply_conj (Ci Cj : ConjClasses G) (h w : G) :
    (classSum Ci * classSum Cj) (h * w * h⁻¹) = (classSum Ci * classSum Cj) w := by
  classical
  rw [classSum_mul_apply, classSum_mul_apply]
  norm_cast
  -- `i` sends a factorization of `h·w·h⁻¹` to one of `w` by conjugating *down* by `h`.
  refine Finset.card_nbij' (fun p => (h⁻¹ * p.1 * h, h⁻¹ * p.2 * h))
    (fun p => (h * p.1 * h⁻¹, h * p.2 * h⁻¹)) ?_ ?_ ?_ ?_
  · rintro ⟨u, v⟩ hp
    simp only [Finset.coe_filter, Set.mem_setOf_eq, Finset.mem_univ, true_and] at hp ⊢
    obtain ⟨hi, hj, huv⟩ := hp
    refine ⟨?_, ?_, ?_⟩
    · rw [show h⁻¹ * u * h = h⁻¹ * u * h⁻¹⁻¹ by group, mk_conj_eq, hi]
    · rw [show h⁻¹ * v * h = h⁻¹ * v * h⁻¹⁻¹ by group, mk_conj_eq, hj]
    · rw [show h⁻¹ * u * h * (h⁻¹ * v * h) = h⁻¹ * (u * v) * h by group, huv]; group
  · rintro ⟨u, v⟩ hp
    simp only [Finset.coe_filter, Set.mem_setOf_eq, Finset.mem_univ, true_and] at hp ⊢
    obtain ⟨hi, hj, huv⟩ := hp
    refine ⟨?_, ?_, ?_⟩
    · rw [mk_conj_eq, hi]
    · rw [mk_conj_eq, hj]
    · rw [show h * u * h⁻¹ * (h * v * h⁻¹) = h * (u * v) * h⁻¹ by group, huv]
  · rintro ⟨u, v⟩ _; simp only [Prod.mk.injEq]; constructor <;> group
  · rintro ⟨u, v⟩ _; simp only [Prod.mk.injEq]; constructor <;> group

omit [DecidableEq G] in
/-- The per-element product coefficient equals the count taken at the chosen class representative
`(ConjClasses.mk w).out`. -/
theorem classSum_mul_apply_out (Ci Cj : ConjClasses G) (w : G) :
    (classSum Ci * classSum Cj) w = (classSum Ci * classSum Cj) (ConjClasses.mk w).out := by
  classical
  -- `(mk w).out` is conjugate to `w`, so write it as `h * w * h⁻¹` and apply class-invariance.
  have hmk : ConjClasses.mk (ConjClasses.mk w).out = ConjClasses.mk w := by
    rw [← ConjClasses.quotient_mk_eq_mk, Quotient.out_eq]
  have hconj : IsConj w (ConjClasses.mk w).out :=
    ConjClasses.mk_eq_mk_iff_isConj.mp hmk.symm
  obtain ⟨c, hc⟩ := isConj_iff.mp hconj
  rw [← hc, classSum_mul_apply_conj]

variable [Fintype (ConjClasses G)]

omit [DecidableEq G] in
/-- **Product of class sums as an integer combination of class sums** (Isaacs §3; Peterfalvi
(6.7.2)): `C_i · C_j = ∑_s a_{ijs}^∘ · C_s`, where the coefficient of `C_s` is the per-element
factorization count `(classSum Ci * classSum Cj) (out C_s)` — a natural number that is *constant*
on the class (this is the coefficient that is actually consistent with `classSum_mul_apply`, **not**
the pair-count `classSumCoeff` divided by `|C_s|`). -/
theorem classSum_mul (Ci Cj : ConjClasses G) :
    classSum Ci * classSum Cj =
      ∑ Cs : ConjClasses G, ((classSum Ci * classSum Cj) Cs.out : ℂ) • classSum Cs := by
  classical
  -- Compare coefficients at an arbitrary group element `w`.
  apply MonoidAlgebra.ext
  intro w
  -- Push the coefficient evaluation `· w` through the finite sum (as an additive hom).
  have hrhs : (∑ Cs : ConjClasses G,
        ((classSum Ci * classSum Cj) Cs.out : ℂ) • classSum Cs) w
      = ∑ Cs : ConjClasses G, (((classSum Ci * classSum Cj) Cs.out : ℂ) • classSum Cs) w :=
    map_sum (Finsupp.applyAddHom w) _ Finset.univ
  rw [hrhs]
  -- RHS coefficient at `w`: only the `Cs = mk w` term survives, contributing `κ((mk w).out)`.
  have hterm : ∀ Cs : ConjClasses G,
      (((classSum Ci * classSum Cj) Cs.out : ℂ) • classSum Cs) w
        = if Cs = ConjClasses.mk w then (classSum Ci * classSum Cj) Cs.out else 0 := by
    intro Cs
    rw [MonoidAlgebra.smul_apply, classSum_apply, smul_eq_mul]
    by_cases hCs : ConjClasses.mk w = Cs
    · rw [if_pos hCs, if_pos hCs.symm, mul_one]
    · rw [if_neg hCs, if_neg (fun h => hCs h.symm), mul_zero]
  rw [Finset.sum_congr rfl (fun Cs _ => hterm Cs),
    Finset.sum_ite_eq' Finset.univ (ConjClasses.mk w)
      (fun Cs => (classSum Ci * classSum Cj) Cs.out)]
  rw [if_pos (Finset.mem_univ _)]
  exact classSum_mul_apply_out Ci Cj w

end StructureCoeff

section CentralCharacter

variable {V : Type*} [AddCommGroup V] [Module ℂ V] [FiniteDimensional ℂ V]

/-- **Schur's lemma for central elements of `ℂ[G]`.** A central element `x` of the group algebra
acts on a finite-dimensional irreducible complex representation `ρ` as a scalar: there is `c : ℂ`
with `ρ.asAlgebraHom x = c • LinearMap.id`.  (Isaacs (1.5)/§3.) -/
theorem exists_central_scalar_asAlgebraHom (ρ : Representation ℂ G V) [IsIrreducible ρ]
    {x : ℂ[G]} (hx : x ∈ Subalgebra.center ℂ (ℂ[G])) :
    ∃ c : ℂ, ρ.asAlgebraHom x = c • LinearMap.id := by
  -- `asAlgebraHom ρ x` is an intertwiner: it commutes with every `ρ g`.
  have hcomm : ∀ (g : G) (v : V), ρ.asAlgebraHom x (ρ g v) = ρ g (ρ.asAlgebraHom x v) := by
    intro g v
    have hgx : MonoidAlgebra.of ℂ G g * x = x * MonoidAlgebra.of ℂ G g :=
      (Subalgebra.mem_center_iff (R := ℂ)).mp hx _
    have h1 : ρ.asAlgebraHom (MonoidAlgebra.of ℂ G g * x)
        = ρ.asAlgebraHom (x * MonoidAlgebra.of ℂ G g) := by rw [hgx]
    simp only [map_mul, asAlgebraHom_of] at h1
    have := LinearMap.congr_fun h1 v
    simpa only [Module.End.mul_apply] using this.symm
  let f : IntertwiningMap ρ ρ :=
    (ρ.asAlgebraHom x).intertwiningMap_of_isIntertwiningMap ρ ρ hcomm
  obtain ⟨c, hc⟩ :=
    (IsIrreducible.algebraMap_intertwiningMap_bijective_of_isAlgClosed (ρ := ρ)).surjective f
  refine ⟨c, ?_⟩
  have hlin := congrArg IntertwiningMap.toLinearMap hc
  rw [IntertwiningMap.algebraMap_apply, IntertwiningMap.toLinearMap_smul,
    show (1 : IntertwiningMap ρ ρ).toLinearMap = LinearMap.id from rfl] at hlin
  exact hlin.symm

omit [FiniteDimensional ℂ V] in
/-- `V` is nontrivial when `ρ` is irreducible (used so that `finrank ℂ V > 0`). -/
theorem nontrivial_of_isIrreducible (ρ : Representation ℂ G V) [IsIrreducible ρ] :
    Nontrivial V := by
  haveI h1 : Nontrivial (Subrepresentation ρ) := IsSimpleOrder.toNontrivial
  have h2 : Nontrivial (Submodule ℂ V) :=
    (Subrepresentation.toSubmodule_injective (ρ := ρ)).nontrivial
  exact (Submodule.nontrivial_iff ℂ).mp h2

/-- The unique scalar `c` with `ρ.asAlgebraHom x = c • id` is the normalized trace
`trace(ρ.asAlgebraHom x) / finrank ℂ V`. -/
theorem centralScalar_eq (ρ : Representation ℂ G V) [IsIrreducible ρ]
    {x : ℂ[G]} {c : ℂ} (hc : ρ.asAlgebraHom x = c • LinearMap.id) :
    c = LinearMap.trace ℂ V (ρ.asAlgebraHom x) / (finrank ℂ V : ℂ) := by
  haveI := nontrivial_of_isIrreducible ρ
  have hfr : (finrank ℂ V : ℂ) ≠ 0 := Nat.cast_ne_zero.mpr Module.finrank_pos.ne'
  rw [hc, map_smul, LinearMap.trace_id, smul_eq_mul, mul_div_assoc, div_self hfr, mul_one]

/-- **The central character `ω_ρ : Z(ℂ[G]) →ₐ[ℂ] ℂ`** attached to a finite-dimensional irreducible
complex representation `ρ` of `G`.  A central element `x` acts on `V` as the scalar `ω_ρ(x)`, and
`x ↦ ω_ρ(x)` is a `ℂ`-algebra homomorphism.  This is the homomorphism `ω` of Isaacs §3 (p. 35),
invoked in Peterfalvi (6.7.2).

The value `ω_ρ(x)` is `trace(ρ.asAlgebraHom x) / finrank ℂ V`; the algebra-hom axioms hold because
`ρ.asAlgebraHom` is multiplicative and each `ρ.asAlgebraHom x` (for central `x`) is a scalar matrix,
whose normalized trace is exactly its scalar. -/
noncomputable def centralCharacterOfRep (ρ : Representation ℂ G V) [IsIrreducible ρ] :
    Subalgebra.center ℂ (ℂ[G]) →ₐ[ℂ] ℂ where
  toFun x := LinearMap.trace ℂ V (ρ.asAlgebraHom x.val) / (finrank ℂ V : ℂ)
  map_one' := by
    have hfr : (finrank ℂ V : ℂ) ≠ 0 := by
      haveI := nontrivial_of_isIrreducible ρ
      exact Nat.cast_ne_zero.mpr Module.finrank_pos.ne'
    change LinearMap.trace ℂ V (ρ.asAlgebraHom (1 : ℂ[G])) / (finrank ℂ V : ℂ) = 1
    rw [map_one, LinearMap.trace_one, div_self hfr]
  map_mul' x y := by
    have hfr : (finrank ℂ V : ℂ) ≠ 0 := by
      haveI := nontrivial_of_isIrreducible ρ
      exact Nat.cast_ne_zero.mpr Module.finrank_pos.ne'
    obtain ⟨cx, hcx⟩ := exists_central_scalar_asAlgebraHom ρ x.property
    obtain ⟨cy, hcy⟩ := exists_central_scalar_asAlgebraHom ρ y.property
    have hxy : (x * y : Subalgebra.center ℂ (ℂ[G])).val = x.val * y.val := rfl
    change LinearMap.trace ℂ V (ρ.asAlgebraHom (x * y).val) / (finrank ℂ V : ℂ)
        = (LinearMap.trace ℂ V (ρ.asAlgebraHom x.val) / (finrank ℂ V : ℂ))
          * (LinearMap.trace ℂ V (ρ.asAlgebraHom y.val) / (finrank ℂ V : ℂ))
    -- RHS: each normalized trace is the corresponding scalar.
    rw [← centralScalar_eq ρ hcx, ← centralScalar_eq ρ hcy]
    -- LHS: `asAlgebraHom (x*y) = (cx•id)*(cy•id) = (cx*cy)•id`, normalized trace is `cx*cy`.
    rw [hxy, map_mul, hcx, hcy, smul_mul_smul_comm, Module.End.mul_eq_comp, LinearMap.id_comp,
      map_smul, LinearMap.trace_id, smul_eq_mul, mul_div_assoc, div_self hfr, mul_one]
  map_zero' := by
    change LinearMap.trace ℂ V (ρ.asAlgebraHom (0 : ℂ[G])) / (finrank ℂ V : ℂ) = 0
    rw [map_zero, map_zero, zero_div]
  map_add' x y := by
    change LinearMap.trace ℂ V (ρ.asAlgebraHom (x + y).val) / (finrank ℂ V : ℂ)
        = LinearMap.trace ℂ V (ρ.asAlgebraHom x.val) / (finrank ℂ V : ℂ)
          + LinearMap.trace ℂ V (ρ.asAlgebraHom y.val) / (finrank ℂ V : ℂ)
    have hadd : (x + y : Subalgebra.center ℂ (ℂ[G])).val = x.val + y.val := rfl
    rw [hadd, map_add, map_add, add_div]
  commutes' r := by
    have hfr : (finrank ℂ V : ℂ) ≠ 0 := by
      haveI := nontrivial_of_isIrreducible ρ
      exact Nat.cast_ne_zero.mpr Module.finrank_pos.ne'
    change LinearMap.trace ℂ V (ρ.asAlgebraHom ((algebraMap ℂ (Subalgebra.center ℂ (ℂ[G])) r)).val)
        / (finrank ℂ V : ℂ) = r
    rw [Subalgebra.coe_algebraMap, AlgHom.commutes, Module.algebraMap_end_eq_smul_id,
      map_smul, LinearMap.trace_id, smul_eq_mul, mul_div_assoc, div_self hfr, mul_one]

@[simp] theorem centralCharacterOfRep_apply (ρ : Representation ℂ G V) [IsIrreducible ρ]
    (x : Subalgebra.center ℂ (ℂ[G])) :
    centralCharacterOfRep ρ x = LinearMap.trace ℂ V (ρ.asAlgebraHom x.val) / (finrank ℂ V : ℂ) :=
  rfl

end CentralCharacter

section Evaluation

variable {V : Type*} [AddCommGroup V] [Module ℂ V] [FiniteDimensional ℂ V]
variable [Fintype G] [DecidableEq (ConjClasses G)]

omit [FiniteDimensional ℂ V] in
/-- The image of a class sum under the representation algebra map is `∑_{g ∈ C} ρ g`. -/
theorem asAlgebraHom_classSum (ρ : Representation ℂ G V) (C : ConjClasses G) :
    ρ.asAlgebraHom (classSum C) =
      ∑ g : G, if ConjClasses.mk g = C then ρ g else 0 := by
  rw [classSum, map_sum]
  refine Finset.sum_congr rfl fun g _ => ?_
  by_cases h : ConjClasses.mk g = C
  · simp only [h, if_true, asAlgebraHom_of]
  · simp [h]

omit [FiniteDimensional ℂ V] in
/-- The trace of `ρ.asAlgebraHom (classSum C)` is `∑_{g ∈ C} χ_ρ(g)`, i.e. `|C| · χ_ρ(g)` for any
`g ∈ C` (since `χ_ρ` is a class function). -/
theorem trace_asAlgebraHom_classSum (ρ : Representation ℂ G V) (C : ConjClasses G) :
    LinearMap.trace ℂ V (ρ.asAlgebraHom (classSum C)) =
      ∑ g : G, if ConjClasses.mk g = C then ρ.character g else 0 := by
  rw [asAlgebraHom_classSum, map_sum]
  refine Finset.sum_congr rfl fun g _ => ?_
  by_cases h : ConjClasses.mk g = C
  · simp only [h, if_true]; rfl
  · simp [h]

/-- **Evaluation of the central character on a class sum** (Isaacs (3.6); Peterfalvi (6.7.2)):
`ω_ρ(C) = (∑_{g ∈ C} χ_ρ(g)) / χ_ρ(1)`.  Since `χ_ρ` is constant on `C`, the numerator equals
`|C| · χ_ρ(g)` for any representative `g ∈ C`. -/
theorem centralCharacterOfRep_classSum (ρ : Representation ℂ G V) [IsIrreducible ρ]
    (C : ConjClasses G) :
    centralCharacterOfRep ρ ⟨classSum C, classSum_mem_center C⟩ =
      (∑ g : G, if ConjClasses.mk g = C then ρ.character g else 0) / (finrank ℂ V : ℂ) := by
  rw [centralCharacterOfRep_apply, trace_asAlgebraHom_classSum]

omit [FiniteDimensional ℂ V] in
/-- The numerator `∑_{g ∈ C} χ_ρ(g)` equals `|C| · χ_ρ(g)` for any `g ∈ C`: the character is
constant on the class, and `|C|` is the number of group elements lying in `C`. -/
theorem sum_character_eq_card_mul (ρ : Representation ℂ G V) (C : ConjClasses G) {g : G}
    (hg : ConjClasses.mk g = C) :
    (∑ g : G, if ConjClasses.mk g = C then ρ.character g else 0)
      = (Nat.card { x : G // ConjClasses.mk x = C } : ℂ) * ρ.character g := by
  classical
  -- The character is constant on the class: replace `χ g'` by `χ g` under the guard.
  have hbody : ∀ g' : G, (if ConjClasses.mk g' = C then ρ.character g' else 0)
      = (if ConjClasses.mk g' = C then ρ.character g else 0) := by
    intro g'
    by_cases hg' : ConjClasses.mk g' = C
    · have hconj : IsConj g g' := ConjClasses.mk_eq_mk_iff_isConj.mp (hg.trans hg'.symm)
      obtain ⟨u, rfl⟩ := isConj_iff.mp hconj
      rw [char_conj]
    · simp [hg']
  rw [Finset.sum_congr rfl (fun g' _ => hbody g')]
  -- Now sum a constant over the class: `∑ g', (if mk g' = C then χ g else 0) = |C| · χ g`.
  rw [← Finset.sum_filter, Finset.sum_const, nsmul_eq_mul]
  congr 2
  rw [Nat.card_eq_fintype_card, Fintype.card_subtype]

end Evaluation

section Integrality

variable {V : Type*} [AddCommGroup V] [Module ℂ V] [FiniteDimensional ℂ V]
variable [Fintype G] [DecidableEq (ConjClasses G)] [Fintype (ConjClasses G)]

/-- Shorthand for the central-character value `ω_ρ(C_s)` on a class sum. -/
local notation3 "ω" ρ:max C:max => centralCharacterOfRep ρ ⟨classSum C, classSum_mem_center C⟩

/-- **The product rule for central-character values.** Because `ω_ρ` is a `ℂ`-algebra hom and
`C_i · C_j = ∑_s m_s · C_s` (`classSum_mul`), the value `ω_ρ(C_i) · ω_ρ(C_j)` is a linear
combination of the values `ω_ρ(C_s)` whose coefficients `(classSum Ci * classSum Cj) C_s.out` are
*natural numbers* (factorization counts), the key fact making the generated `ℤ`-subalgebra closed
under multiplication. -/
theorem centralCharacterOfRep_classSum_mul (ρ : Representation ℂ G V) [IsIrreducible ρ]
    (Ci Cj : ConjClasses G) :
    (ω ρ Ci) * (ω ρ Cj) =
      ∑ Cs : ConjClasses G, ((classSum Ci * classSum Cj) Cs.out) • (ω ρ Cs) := by
  classical
  -- `ω` is multiplicative, and the product of the two class sums is the stated combination.
  have hcenter : (⟨classSum Ci, classSum_mem_center Ci⟩ : Subalgebra.center ℂ (ℂ[G]))
        * ⟨classSum Cj, classSum_mem_center Cj⟩
      = ∑ Cs : ConjClasses G,
          ((classSum Ci * classSum Cj) Cs.out) •
            (⟨classSum Cs, classSum_mem_center Cs⟩ : Subalgebra.center ℂ (ℂ[G])) := by
    apply Subtype.ext
    rw [Subalgebra.coe_mul, AddSubmonoidClass.coe_finset_sum]
    simp only [SetLike.val_smul]
    exact classSum_mul Ci Cj
  calc (ω ρ Ci) * (ω ρ Cj)
      = centralCharacterOfRep ρ
          (⟨classSum Ci, classSum_mem_center Ci⟩ * ⟨classSum Cj, classSum_mem_center Cj⟩) := by
        rw [map_mul]
    _ = centralCharacterOfRep ρ
          (∑ Cs : ConjClasses G, ((classSum Ci * classSum Cj) Cs.out) •
            (⟨classSum Cs, classSum_mem_center Cs⟩ : Subalgebra.center ℂ (ℂ[G]))) := by
        rw [hcenter]
    _ = ∑ Cs : ConjClasses G,
          ((classSum Ci * classSum Cj) Cs.out) • (ω ρ Cs) := by
        rw [map_sum]; exact Finset.sum_congr rfl fun Cs _ => map_smul _ _ _

omit [Fintype (ConjClasses G)] in
/-- **Algebraic integrality of the central-character value `ω_ρ(C)`** (Isaacs (3.7); the
structure-constant integrality used in Peterfalvi (6.7.3)).  For an irreducible representation `ρ`
of a finite group `G` and a conjugacy class `C`, the value `ω_ρ(C) = |C| · χ_ρ(g) / χ_ρ(1)` is an
**algebraic integer**.

The proof realizes the standard structure-constant argument inside `ℂ` directly: the `ℤ`-submodule
`N ⊆ ℂ` spanned by `{1} ∪ {ω_ρ(C_s) : C_s}` is finitely generated (the spanning set is finite, as
`ConjClasses G` is finite) and closed under multiplication — the latter because `ω_ρ` is a
`ℂ`-algebra hom and `classSum_mul` expresses `C_i · C_j` with integer structure coefficients, so
`ω_ρ(C_i) · ω_ρ(C_j) = ∑_s m_s · ω_ρ(C_s) ∈ N` (`centralCharacterOfRep_classSum_mul`).  Thus `N` is
a `ℤ`-subalgebra of `ℂ` that is module-finite, and every element of a module-finite subalgebra is
integral (`IsIntegral.of_mem_of_fg`). -/
theorem centralCharacterOfRep_classSum_isIntegral (ρ : Representation ℂ G V) [IsIrreducible ρ]
    (C : ConjClasses G) :
    IsIntegral ℤ (ω ρ C) := by
  classical
  haveI : Finite (ConjClasses G) := Finite.of_surjective _ ConjClasses.mk_surjective
  haveI : Fintype (ConjClasses G) := Fintype.ofFinite _
  -- The finite spanning set: `{1}` together with all central-character values.
  set s : Set ℂ := insert 1 (Set.range (fun Cs : ConjClasses G => ω ρ Cs)) with hs
  have hsfin : s.Finite := (Set.finite_range _).insert 1
  -- The `ℤ`-submodule generated by `s`.
  set N : Submodule ℤ ℂ := Submodule.span ℤ s with hN
  -- Membership of `1` and every generator.
  have h1_mem : (1 : ℂ) ∈ N := Submodule.subset_span (Set.mem_insert _ _)
  have hgen_mem : ∀ Cs : ConjClasses G, (ω ρ Cs) ∈ N := fun Cs =>
    Submodule.subset_span (Set.mem_insert_of_mem _ ⟨Cs, rfl⟩)
  -- A factorization-count coefficient times a generator lands in `N` (`ℕ`-smul of a member).
  have hcoeff_smul : ∀ (Ci Cj Cs : ConjClasses G),
      ((classSum Ci * classSum Cj) Cs.out) • (ω ρ Cs) ∈ N := by
    intro Ci Cj Cs
    rw [classSum_mul_apply, Nat.cast_smul_eq_nsmul]
    exact nsmul_mem (hgen_mem Cs) _
  -- Closure under multiplication: it suffices to check products of generators.
  have hmul : ∀ x y : ℂ, x ∈ N → y ∈ N → x * y ∈ N := by
    have hgen : ∀ a ∈ s, ∀ b ∈ s, a * b ∈ N := by
      intro a ha b hb
      rcases ha with rfl | ⟨Ci, rfl⟩
      · rw [one_mul]; exact Submodule.subset_span hb
      · rcases hb with rfl | ⟨Cj, rfl⟩
        · rw [mul_one]; exact hgen_mem Ci
        · rw [centralCharacterOfRep_classSum_mul]
          exact Submodule.sum_mem _ fun Cs _ => hcoeff_smul Ci Cj Cs
    -- Lift generator-closure to all of `N` by span induction (bilinearly).
    intro x y hx hy
    refine Submodule.span_induction ?_ ?_ ?_ ?_ hx
    · intro a ha
      refine Submodule.span_induction ?_ ?_ ?_ ?_ hy
      · intro b hb; exact hgen a ha b hb
      · rw [mul_zero]; exact N.zero_mem
      · intro b c _ _ hb hc; rw [mul_add]; exact N.add_mem hb hc
      · intro r b _ hb; rw [mul_smul_comm]; exact N.smul_mem r hb
    · rw [zero_mul]; exact N.zero_mem
    · intro a c _ _ ha hc; rw [add_mul]; exact N.add_mem ha hc
    · intro r a _ ha; rw [smul_mul_assoc]; exact N.smul_mem r ha
  -- Package `N` as a `ℤ`-subalgebra of `ℂ`.
  let S : Subalgebra ℤ ℂ := N.toSubalgebra h1_mem hmul
  have hSfg : S.toSubmodule.FG := by
    rw [Submodule.toSubalgebra_toSubmodule]; exact Submodule.fg_span hsfin
  -- `ω ρ C ∈ S`, and every element of a module-finite subalgebra is integral.
  exact IsIntegral.of_mem_of_fg S hSfg _ (hgen_mem C)

end Integrality

section CharacterIntegrality

variable {V : Type*} [AddCommGroup V] [Module ℂ V] [FiniteDimensional ℂ V] [Finite G]

/-- **`|C| · χ_ρ(g) / χ_ρ(1)` is an algebraic integer** (Isaacs (3.7); the integrality input to
Peterfalvi (6.7.3)).  For an irreducible representation `ρ` of a finite group `G`, a conjugacy class
`C`, and any representative `g ∈ C`, the value `|C| · χ_ρ(g) / χ_ρ(1)` is an algebraic integer over
`ℤ`.

This is the explicit character-value form of `centralCharacterOfRep_classSum_isIntegral`: that
theorem states `ω_ρ(C)` is integral, and `centralCharacterOfRep_classSum` together with
`sum_character_eq_card_mul` identify `ω_ρ(C)` with `|C| · χ_ρ(g) / χ_ρ(1)` (using `char_one` for
`χ_ρ(1) = finrank ℂ V`).  This is the form most arguments consume (e.g. the `mod |P|` congruence of
(6.7.3), and the classical proof that `χ_ρ(1) ∣ |G|`). -/
theorem isIntegral_card_mul_character_div (ρ : Representation ℂ G V) [IsIrreducible ρ]
    (C : ConjClasses G) {g : G} (hg : ConjClasses.mk g = C) :
    IsIntegral ℤ
      ((Nat.card { x : G // ConjClasses.mk x = C } : ℂ) * ρ.character g / ρ.character 1) := by
  classical
  haveI : Fintype G := Fintype.ofFinite G
  have hval :
      (Nat.card { x : G // ConjClasses.mk x = C } : ℂ) * ρ.character g / ρ.character 1 =
        centralCharacterOfRep ρ ⟨classSum C, classSum_mem_center C⟩ := by
    rw [centralCharacterOfRep_classSum, sum_character_eq_card_mul ρ C hg, ρ.char_one]
  rw [hval]
  exact centralCharacterOfRep_classSum_isIntegral ρ C

end CharacterIntegrality

section CharacterValuesIntegral

/-- **A root of unity is an algebraic integer.** If `x : ℂ` satisfies `x ^ n = 1` with `n ≠ 0`,
then `x` is integral over `ℤ` — it is a root of the monic polynomial `X ^ n - 1`. -/
theorem isIntegral_of_pow_eq_one {x : ℂ} {n : ℕ} (hn : n ≠ 0) (hx : x ^ n = 1) :
    IsIntegral ℤ x := by
  refine ⟨Polynomial.X ^ n - Polynomial.C 1, ?_, ?_⟩
  · exact Polynomial.monic_X_pow_sub_C 1 hn
  · simp [hx]

variable {V : Type*} [AddCommGroup V] [Module ℂ V] [FiniteDimensional ℂ V]

/-- **Eigenvalues of a finite-order endomorphism are roots of unity.** If `f : End ℂ V` satisfies
`f ^ n = 1` and `μ` is a root of the characteristic polynomial of `f` (equivalently an eigenvalue),
then `μ ^ n = 1`. -/
theorem pow_eq_one_of_isRoot_charpoly_of_pow_eq_one {f : Module.End ℂ V} {n : ℕ}
    (hf : f ^ n = 1) {μ : ℂ} (hμ : f.charpoly.IsRoot μ) : μ ^ n = 1 := by
  -- `μ` is a root of the charpoly, hence an eigenvalue, so it has a nonzero eigenvector.
  have hev : f.HasEigenvalue μ := (Module.End.hasEigenvalue_iff_isRoot_charpoly f μ).mpr hμ
  obtain ⟨v, hv⟩ := hev.exists_hasEigenvector
  -- Acting by `f ^ n` scales `v` by `μ ^ n`; but `f ^ n = 1`, so `μ ^ n • v = v`.
  have hpow : (f ^ n) v = μ ^ n • v := hv.pow_apply n
  rw [hf, Module.End.one_apply] at hpow
  -- `hpow : v = μ ^ n • v`; hence `(μ ^ n - 1) • v = 0` with `v ≠ 0` over `ℂ` forces `μ ^ n = 1`.
  have hsub : (μ ^ n - 1) • v = 0 := by rw [sub_smul, one_smul, ← hpow, sub_self]
  rcases smul_eq_zero.mp hsub with h | h
  · exact sub_eq_zero.mp h
  · exact absurd h hv.2

/-- **Character values are algebraic integers** (Isaacs (3.7) preamble / standard).  For any
finite-dimensional complex representation `ρ` of a finite group `G` and any `g : G`, the character
value `χ_ρ(g) = trace(ρ g)` is an algebraic integer over `ℤ`.

Standard proof: `ρ g` has finite order `n = |G|` (since `g ^ |G| = 1` and `ρ` is a homomorphism),
so `(ρ g) ^ n = 1`.  Over `ℂ` the characteristic polynomial of `ρ g` splits, so the trace is the
sum of its roots (eigenvalues); each eigenvalue `μ` satisfies `μ ^ n = 1`, hence is a root of unity
and so integral over `ℤ` (`isIntegral_of_pow_eq_one`).  A sum of algebraic integers is an algebraic
integer. -/
theorem character_isIntegral (ρ : Representation ℂ G V) [Finite G] (g : G) :
    IsIntegral ℤ (ρ.character g) := by
  classical
  haveI : Fintype G := Fintype.ofFinite G
  set n : ℕ := Nat.card G with hn_def
  have hn : n ≠ 0 := Nat.card_pos.ne'
  -- `(ρ g) ^ n = ρ (g ^ n) = ρ 1 = 1`, using `g ^ |G| = 1`.
  have hgn : g ^ n = 1 := pow_card_eq_one'
  have hfn : (ρ g) ^ n = 1 := by
    rw [← map_pow, hgn, map_one]
  -- The trace is the sum of the roots of the (splitting) characteristic polynomial.
  have hsplits : (ρ g).charpoly.Splits := IsAlgClosed.splits _
  have htrace : ρ.character g = (ρ g).charpoly.roots.sum := by
    rw [Representation.character]
    exact Module.End.trace_eq_sum_roots_charpoly_of_splits hsplits
  rw [htrace]
  -- A finite sum (over a multiset) of algebraic integers is an algebraic integer; each root is one.
  refine IsIntegral.multiset_sum ?_
  intro μ hμ
  have hroot : (ρ g).charpoly.IsRoot μ :=
    (Polynomial.mem_roots ((ρ g).charpoly_monic).ne_zero).mp hμ
  exact isIntegral_of_pow_eq_one hn (pow_eq_one_of_isRoot_charpoly_of_pow_eq_one hfn hroot)

/-- **A rational algebraic integer is an integer.** If `q : ℚ` is integral over `ℤ` when viewed
inside `ℂ`, then `q` is the image of an integer: there is `n : ℤ` with `(q : ℂ) = n`.

`ℤ` is integrally closed (it is a `UniqueFactorizationMonoid`, hence integrally closed in its
fraction field `ℚ`).  Transferring `IsIntegral ℤ (q : ℂ)` down the injective `ℚ`-algebra map
`ℚ ↪ ℂ` gives `IsIntegral ℤ q`, and integral closure then yields the integer. -/
theorem isIntegral_rat_imp_int {q : ℚ} (h : IsIntegral ℤ (q : ℂ)) :
    ∃ n : ℤ, (q : ℂ) = n := by
  -- `(q : ℂ) = algebraMap ℚ ℂ q`; transfer integrality down the injection `ℚ ↪ ℂ`.
  have hqℂ : (q : ℂ) = algebraMap ℚ ℂ q := (eq_ratCast (algebraMap ℚ ℂ) q).symm
  rw [hqℂ] at h
  have hQ : IsIntegral ℤ q :=
    (isIntegral_algebraMap_iff (FaithfulSMul.algebraMap_injective ℚ ℂ)).mp h
  -- `ℤ` is integrally closed in `ℚ` (it is a UFD), so `q = (n : ℚ)` for some `n : ℤ`.
  obtain ⟨n, hn⟩ := IsIntegrallyClosed.isIntegral_iff.mp hQ
  refine ⟨n, ?_⟩
  -- `hn : algebraMap ℤ ℚ n = q`, i.e. `(n : ℚ) = q`; cast up to `ℂ`.
  rw [algebraMap_int_eq, Int.coe_castRingHom] at hn
  rw [← hn]
  push_cast
  ring

end CharacterValuesIntegral

section CharacterDegreeDvd

variable {V : Type*} [AddCommGroup V] [Module ℂ V] [FiniteDimensional ℂ V]
variable [Fintype G] [DecidableEq (ConjClasses G)] [Fintype (ConjClasses G)]

omit [DecidableEq (ConjClasses G)] in
/-- **Regrouping a class function by conjugacy class.** For `F : G → ℂ` constant on conjugacy
classes, the sum over `G` regroups as a sum over classes, each contributing `|C| · F(C.out)`. -/
theorem sum_eq_sum_conjClasses_of_isClassFun {F : G → ℂ}
    (hF : ∀ g h : G, F (h * g * h⁻¹) = F g) :
    ∑ g : G, F g
      = ∑ C : ConjClasses G, (Nat.card { x : G // ConjClasses.mk x = C } : ℂ) * F C.out := by
  classical
  -- Fiberwise over the conjugacy-class map `mk : G → ConjClasses G`.
  rw [← Finset.sum_fiberwise Finset.univ (fun g : G => ConjClasses.mk g) F]
  refine Finset.sum_congr rfl fun C _ => ?_
  -- On the fiber `{g | mk g = C}`, `F` is constant equal to `F C.out`.
  have hbody : ∀ g ∈ Finset.univ.filter (fun g : G => ConjClasses.mk g = C),
      F g = F C.out := by
    intro g hg
    rw [Finset.mem_filter] at hg
    -- `g` and `C.out` are conjugate (both have class `C`), so `F g = F C.out`.
    have hmkout : ConjClasses.mk C.out = C := by
      rw [← ConjClasses.quotient_mk_eq_mk, Quotient.out_eq]
    have hconj : IsConj C.out g := ConjClasses.mk_eq_mk_iff_isConj.mp (hmkout.trans hg.2.symm)
    obtain ⟨u, rfl⟩ := isConj_iff.mp hconj
    exact hF C.out u
  rw [Finset.sum_congr rfl hbody, Finset.sum_const, nsmul_eq_mul]
  congr 2
  rw [Nat.card_eq_fintype_card, Fintype.card_subtype]

/-- **First orthogonality in class-sum form.** For an irreducible representation `ρ`, summing the
class-sum central-character values weighted by `χ_ρ((C.out)⁻¹)` and rescaling by `χ_ρ(1)` recovers
`|G|`:
`(∑_C ω_ρ(C) · χ_ρ((C.out)⁻¹)) · χ_ρ(1) = |G|`.
This is the first orthogonality relation `∑_g χ_ρ(g) χ_ρ(g⁻¹) = |G|` (`char_orthonormal` with
`ρ ≅ ρ`) regrouped over conjugacy classes. -/
theorem sum_centralCharacter_mul_character_inv_mul_character_one (ρ : Representation ℂ G V)
    [IsIrreducible ρ] :
    (∑ C : ConjClasses G,
        centralCharacterOfRep ρ ⟨classSum C, classSum_mem_center C⟩ * ρ.character (C.out)⁻¹)
        * ρ.character 1 = (Nat.card G : ℂ) := by
  classical
  haveI := nontrivial_of_isIrreducible ρ
  have hd : ρ.character 1 ≠ 0 := by
    rw [ρ.char_one]; exact Nat.cast_ne_zero.mpr Module.finrank_pos.ne'
  -- First orthogonality `∑_g χ(g) χ(g⁻¹) = |G|` from `char_orthonormal` with `ρ ≅ ρ`.
  haveI : Invertible (Nat.card G : ℂ) :=
    invertibleOfNonzero (Nat.cast_ne_zero.mpr Nat.card_pos.ne')
  have hNℂ : (Nat.card G : ℂ) ≠ 0 := Nat.cast_ne_zero.mpr Nat.card_pos.ne'
  have horth := Representation.char_orthonormal ρ ρ
  rw [if_pos ⟨Representation.Equiv.refl ρ⟩] at horth
  -- Clear the `(Nat.card G)⁻¹` factor: `∑_g χ(g) χ(g⁻¹) = |G|`.
  have hsumG : ∑ g : G, ρ.character g * ρ.character g⁻¹ = (Nat.card G : ℂ) := by
    field_simp at horth
    simpa [mul_comm] using horth
  -- Distribute `· χ(1)` over the sum and identify each term with `|C| χ(g_C) χ(g_C⁻¹)`.
  rw [Finset.sum_mul]
  have hterm : ∀ C : ConjClasses G,
      (centralCharacterOfRep ρ ⟨classSum C, classSum_mem_center C⟩ * ρ.character (C.out)⁻¹)
          * ρ.character 1
        = (Nat.card { x : G // ConjClasses.mk x = C } : ℂ)
            * (ρ.character C.out * ρ.character (C.out)⁻¹) := by
    intro C
    -- `ω_ρ(C) = (|C| χ(g_C)) / χ(1)` via `centralCharacterOfRep_classSum` + class-constancy.
    have hmkout : ConjClasses.mk C.out = C := by
      rw [← ConjClasses.quotient_mk_eq_mk, Quotient.out_eq]
    have homega : centralCharacterOfRep ρ ⟨classSum C, classSum_mem_center C⟩
        = ((Nat.card { x : G // ConjClasses.mk x = C } : ℂ) * ρ.character C.out)
            / ρ.character 1 := by
      rw [centralCharacterOfRep_classSum, sum_character_eq_card_mul ρ C hmkout, ρ.char_one]
    rw [homega, div_mul_eq_mul_div, div_mul_eq_mul_div, mul_div_assoc, div_self hd, mul_one]
    ring
  rw [Finset.sum_congr rfl (fun C _ => hterm C),
    ← sum_eq_sum_conjClasses_of_isClassFun
      (F := fun g => ρ.character g * ρ.character g⁻¹) ?_]
  · exact hsumG
  · intro g h
    simp only
    rw [ρ.char_conj, show (h * g * h⁻¹)⁻¹ = h * g⁻¹ * h⁻¹ by group, ρ.char_conj]

end CharacterDegreeDvd

section CharacterDegreeDvdMain

variable {V : Type*} [AddCommGroup V] [Module ℂ V] [FiniteDimensional ℂ V] [Finite G]

/-- **`χ_ρ(1) ∣ |G|`** (Isaacs, *Character Theory of Finite Groups*, Thm 3.11; the classical
divisibility of the degree).  For an irreducible complex representation `ρ` of a finite group `G`,
the degree `χ_ρ(1) = dim V` divides the order of the group.

Proof (the standard algebraic-integer argument): the rational number `|G| / χ_ρ(1)` equals
`∑_C ω_ρ(C) · χ_ρ((g_C)⁻¹)` (first orthogonality regrouped over classes,
`sum_centralCharacter_mul_character_inv_mul_character_one`), a sum of products of algebraic integers
(`isIntegral_card_mul_character_div` for `ω_ρ(C)`, `character_isIntegral` for the conjugate factor),
hence itself an algebraic integer.  Being a rational algebraic integer it is an integer
(`isIntegral_rat_imp_int`), so `χ_ρ(1) ∣ |G|`. -/
theorem finrank_dvd_card (ρ : Representation ℂ G V) [IsIrreducible ρ] :
    finrank ℂ V ∣ Nat.card G := by
  classical
  haveI : Fintype G := Fintype.ofFinite G
  haveI : Finite (ConjClasses G) := Finite.of_surjective _ ConjClasses.mk_surjective
  haveI : Fintype (ConjClasses G) := Fintype.ofFinite _
  haveI := nontrivial_of_isIrreducible ρ
  set d : ℕ := finrank ℂ V with hd_def
  have hdpos : 0 < d := Module.finrank_pos
  have hdℂ : (d : ℂ) ≠ 0 := Nat.cast_ne_zero.mpr hdpos.ne'
  -- The summed quantity `S := ∑_C ω_ρ(C) · χ((g_C)⁻¹)`.
  set S : ℂ := ∑ C : ConjClasses G,
      centralCharacterOfRep ρ ⟨classSum C, classSum_mem_center C⟩ * ρ.character (C.out)⁻¹ with hS
  -- `S · χ(1) = |G|`, and `χ(1) = d`, so `S · d = |G|`.
  have hSd : S * (d : ℂ) = (Nat.card G : ℂ) := by
    have := sum_centralCharacter_mul_character_inv_mul_character_one ρ
    rwa [ρ.char_one] at this
  -- `S` is an algebraic integer: a sum of products of algebraic integers.
  have hSint : IsIntegral ℤ S := by
    refine IsIntegral.sum _ fun C _ => ?_
    refine IsIntegral.mul ?_ ?_
    · -- `ω_ρ(C) = |C| χ(g_C)/χ(1)` is an algebraic integer.
      have hmkout : ConjClasses.mk C.out = C := by
        rw [← ConjClasses.quotient_mk_eq_mk, Quotient.out_eq]
      have hval := isIntegral_card_mul_character_div ρ C hmkout
      have heq : centralCharacterOfRep ρ ⟨classSum C, classSum_mem_center C⟩
          = (Nat.card { x : G // ConjClasses.mk x = C } : ℂ) * ρ.character C.out
              / ρ.character 1 := by
        rw [centralCharacterOfRep_classSum, sum_character_eq_card_mul ρ C hmkout, ρ.char_one]
      rw [heq]; exact hval
    · exact character_isIntegral ρ (C.out)⁻¹
  -- `S = (|G| / d : ℚ)` cast to `ℂ`, so `S` is a rational algebraic integer, hence an integer.
  have hSrat : S = (((Nat.card G : ℚ) / (d : ℚ) : ℚ) : ℂ) := by
    rw [eq_div_of_mul_eq hdℂ hSd]
    push_cast
    ring
  obtain ⟨n, hn⟩ := isIntegral_rat_imp_int (q := (Nat.card G : ℚ) / (d : ℚ)) (hSrat ▸ hSint)
  -- From `S = n` and `S · d = |G|`: `(n : ℂ) · d = |G|`, descend to `ℤ` then to `ℕ`.
  rw [hSrat, hn] at hSd
  -- `(n : ℂ) * d = |G|` over `ℂ` ⇒ `n * d = |G|` over `ℤ`.
  have hZ : n * (d : ℤ) = (Nat.card G : ℤ) := by
    have hcast : ((n * (d : ℤ) : ℤ) : ℂ) = ((Nat.card G : ℤ) : ℂ) := by
      push_cast
      linear_combination hSd
    exact_mod_cast hcast
  -- `d ∣ |G|` in `ℤ`, hence in `ℕ`.
  have hdvdZ : (d : ℤ) ∣ (Nat.card G : ℤ) := ⟨n, by rw [← hZ]; ring⟩
  exact_mod_cast hdvdZ

/-- **The degree of an irreducible representation of a `p`-group is a power of `p`** (Isaacs,
*Character Theory of Finite Groups*, Cor. 3.12 / standard).  If `G` is a finite `p`-group and `ρ`
is an irreducible complex representation of `G`, then `dim V = χ_ρ(1)` is a power of the prime `p`.

This is the immediate divisibility corollary of `finrank_dvd_card`: writing `|G| = p ^ n`
(`IsPGroup.iff_card`), the degree divides `p ^ n`, and a divisor of a prime power is itself a
power of that prime (`Nat.dvd_prime_pow`). -/
theorem exists_finrank_eq_prime_pow_of_isPGroup {p : ℕ} [Fact p.Prime] (hG : IsPGroup p G)
    (ρ : Representation ℂ G V) [IsIrreducible ρ] :
    ∃ k : ℕ, finrank ℂ V = p ^ k := by
  obtain ⟨n, hn⟩ := (IsPGroup.iff_card (p := p)).mp hG
  have hdvd : finrank ℂ V ∣ p ^ n := hn ▸ finrank_dvd_card ρ
  obtain ⟨k, _, hk⟩ := (Nat.dvd_prime_pow (p := p) (Fact.out (p := p.Prime))).mp hdvd
  exact ⟨k, hk⟩

end CharacterDegreeDvdMain

end OddOrder.RepresentationTheory
