/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.GroupTheory.RepresentationTheory.Modular.BrauerInductionDescent

/-!
# Induction carries `ℤ[ω]·ch(H)` into `ℤ[ω]·v(G)`

`v(G) = ∑_{E ∈ 𝒳} ch(E)^*` is by definition generated by the inductions of virtual characters;
Gorenstein's argument needs the same with `ℤ[ω]` coefficients, because the class function of
Lemma 7.6 lies in `ch_R(H)` rather than `ch(H)` (issue 9508, 段 F).

Since `Ind_H^G` is `K`-linear (`induceFun_add`, `induceFun_smul`), the statement is a one-step
closure induction.

## Main results

* `OddOrder.RepresentationTheory.induceFun_mem_adjoinSpan_inducedVirtualCharacters`

## References

* D. Gorenstein, *Finite Groups*, §4.7 (`references/gorenstein/pages/`).
-/

namespace OddOrder.RepresentationTheory

variable {K G : Type*} [Field K] [Group G] [Fintype G] {ω : K} {𝒳 : Set (Subgroup G)}

/-- **`Ind_H^G (ch_R(H)) ⊆ v_R(G)`** for `H` in the family. -/
theorem induceFun_mem_adjoinSpan_inducedVirtualCharacters {H : Subgroup G} (hH : H ∈ 𝒳)
    {ψ : ↥H → K} (hψ : ψ ∈ adjoinSpan ω (virtualCharacters K ↥H)) :
    induceFun H ψ ∈ adjoinSpan ω (inducedVirtualCharacters K 𝒳) := by
  induction hψ using AddSubgroup.closure_induction with
  | mem f hf =>
      obtain ⟨j, w, hw, rfl⟩ := hf
      rw [induceFun_smul]
      exact pow_smul_mem_adjoinSpan j (induceFun_mem_inducedVirtualCharacters hH hw)
  | zero => simpa only [induceFun_zero] using (adjoinSpan ω (inducedVirtualCharacters K 𝒳)).zero_mem
  | add a b _ _ ha hb =>
      simpa only [induceFun_add] using
        (adjoinSpan ω (inducedVirtualCharacters K 𝒳)).add_mem ha hb
  | neg a _ ha =>
      simpa only [induceFun_neg] using (adjoinSpan ω (inducedVirtualCharacters K 𝒳)).neg_mem ha

end OddOrder.RepresentationTheory
