/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.Algebra.Ring.Equiv
import Mathlib.Algebra.Ring.Aut
import Mathlib.Algebra.Group.End
import Mathlib.Algebra.Group.Subgroup.Basic

/-!
# Semilinear extension: additive automorphisms multiplicative on a generating scalar set

Abstract layer for **Peterfalvi (9.7.b)** (LMS LNS 272, p. 52; issue 1043): the map `η(w)`
transported from the `W₁`-action on the chief factor `H̄ ≅ F = GF(p^q)` is a priori only an
*additive* automorphism of `F`; the book upgrades it to a **field automorphism** from two facts:

* the twist identity `η(w)(t·ψ(x)) = η(w)(t)·η(w)(ψ(x))` — multiplicativity against the scalar
  image `U* = ψ(Ū)` (derived from the `W₂`-base-point normalization `s^w = s`);
* `U*` generates `F` **additively** ("the additive subgroup of `F` generated by `U*` is `F`",
  from the irreducibility of the `U`-action).

This file proves the abstract upgrade: an additive automorphism `α : F ≃+ F` of a ring that is
multiplicative against every element of an additively-generating set `S` is fully multiplicative
(`addEquiv_mul_of_mul_scalars` — for fixed `t`, the set `{t' | α (t·t') = α t · α t'}` is an
additive subgroup containing `S`), hence a ring automorphism (`ringEquivOfAddEquivOfMulScalars`;
`map_one` is automatic for a `RingEquiv`).  A pointwise family version packages a group's worth
of such automorphisms into `W →* RingAut F` (`ringAutHomOfAddAutHom`), preserving injectivity.

The concrete (9.7.b) wiring — the base-point normalization of the Galois-field model
`caseB_exists_galoisField_repr`, the twist identity from `W̄₂ = C_{H̄}(W₁)`, and the additive
generation from irreducibility — lives on the S11 side (issue 1043).
-/

namespace OddOrder.RepresentationTheory

variable {F : Type*} [Ring F]

/-- **Multiplicativity from a generating scalar set**: an additive automorphism `α` that is
multiplicative against every element of `S` (`α (t·s) = α t · α s`) is multiplicative against
every element of the additive closure of `S`; if `S` generates `F` additively, against
everything.  For fixed `t`, the set `{t' | α (t·t') = α t · α t'}` is an additive subgroup
(distributivity + additivity of `α`) containing `S`. -/
theorem addEquiv_mul_of_mul_scalars (α : F ≃+ F) {S : Set F}
    (hgen : AddSubgroup.closure S = ⊤)
    (hmul : ∀ s ∈ S, ∀ t : F, α (t * s) = α t * α s) (t t' : F) :
    α (t * t') = α t * α t' := by
  have hmem : t' ∈ AddSubgroup.closure S := hgen ▸ AddSubgroup.mem_top t'
  induction hmem using AddSubgroup.closure_induction with
  | mem s hs => exact hmul s hs t
  | zero => simp
  | add x y _ _ hpx hpy => rw [mul_add, map_add, hpx, hpy, map_add, mul_add]
  | neg x _ hpx => rw [mul_neg, map_neg, hpx, map_neg, mul_neg]

/-- **The semilinear-extension ring automorphism** (Peterfalvi (9.7.b), abstract form): an
additive automorphism multiplicative against an additively-generating scalar set is a ring
automorphism.  (`map_one` needs no hypothesis: a multiplicative-and-additive equiv of a ring
preserves `1` automatically.) -/
def ringEquivOfAddEquivOfMulScalars (α : F ≃+ F) {S : Set F}
    (hgen : AddSubgroup.closure S = ⊤)
    (hmul : ∀ s ∈ S, ∀ t : F, α (t * s) = α t * α s) : F ≃+* F :=
  { α with
    map_mul' := addEquiv_mul_of_mul_scalars α hgen hmul }

@[simp] theorem ringEquivOfAddEquivOfMulScalars_apply (α : F ≃+ F) {S : Set F}
    (hgen : AddSubgroup.closure S = ⊤)
    (hmul : ∀ s ∈ S, ∀ t : F, α (t * s) = α t * α s) (x : F) :
    ringEquivOfAddEquivOfMulScalars α hgen hmul x = α x := rfl

/-- **Group-level packaging** (the `η : W₁ →* Aut F` of Peterfalvi (9.7.b)): a homomorphism into
the additive automorphisms whose every value is multiplicative against a common
additively-generating scalar set upgrades to a homomorphism into the **ring** automorphisms,
with the same underlying functions.

`AddAut F` is an *additive* group in mathlib, so the source is its multiplicative incarnation
`Multiplicative (AddAut F)` (the same idiom as `AddAut.toZModLinearEquiv` in
`OddOrder/GroupTheory/PRank.lean` and `AddAut.mulLeft` in `OddOrder/BG/AppC_NormSet.lean`).
Both group laws are function composition, so the two `rfl`s below are the real content. -/
def ringAutHomOfAddAutHom {W : Type*} [Group W] (η : W →* Multiplicative (AddAut F))
    {S : Set F} (hgen : AddSubgroup.closure S = ⊤)
    (hmul : ∀ w : W, ∀ s ∈ S, ∀ t : F, Multiplicative.toAdd (η w) (t * s)
      = Multiplicative.toAdd (η w) t * Multiplicative.toAdd (η w) s) :
    W →* RingAut F where
  toFun w := ringEquivOfAddEquivOfMulScalars (Multiplicative.toAdd (η w)) hgen (hmul w)
  map_one' := by
    refine RingEquiv.ext fun x => ?_
    rw [ringEquivOfAddEquivOfMulScalars_apply, map_one η]
    rfl
  map_mul' w w' := by
    refine RingEquiv.ext fun x => ?_
    rw [ringEquivOfAddEquivOfMulScalars_apply, map_mul η]
    rfl

@[simp] theorem ringAutHomOfAddAutHom_apply {W : Type*} [Group W]
    (η : W →* Multiplicative (AddAut F))
    {S : Set F} (hgen : AddSubgroup.closure S = ⊤)
    (hmul : ∀ w : W, ∀ s ∈ S, ∀ t : F, Multiplicative.toAdd (η w) (t * s)
      = Multiplicative.toAdd (η w) t * Multiplicative.toAdd (η w) s) (w : W) (x : F) :
    ringAutHomOfAddAutHom η hgen hmul w x = Multiplicative.toAdd (η w) x := rfl

/-- The ring-automorphism packaging preserves injectivity: distinct `W`-elements with distinct
additive actions stay distinct as ring automorphisms (same underlying functions). -/
theorem ringAutHomOfAddAutHom_injective {W : Type*} [Group W]
    (η : W →* Multiplicative (AddAut F))
    {S : Set F} (hgen : AddSubgroup.closure S = ⊤)
    (hmul : ∀ w : W, ∀ s ∈ S, ∀ t : F, Multiplicative.toAdd (η w) (t * s)
      = Multiplicative.toAdd (η w) t * Multiplicative.toAdd (η w) s)
    (hinj : Function.Injective η) :
    Function.Injective (ringAutHomOfAddAutHom η hgen hmul) := by
  intro w w' h
  apply hinj
  refine Multiplicative.toAdd.injective (AddEquiv.ext fun x => ?_)
  have := congrArg (fun f : RingAut F => f x) h
  simpa using this

end OddOrder.RepresentationTheory
