/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.Data.Complex.Basic
import Mathlib.LinearAlgebra.Span.Basic
import Mathlib.RepresentationTheory.Character
import Mathlib.RepresentationTheory.Irreducible
import OddOrder.GroupTheory.RepresentationTheory.ClassFunction

/-!
# The virtual character lattice `ℤ[Irr G]`

For a group `G`, Peterfalvi's `ℤ[Irr G]` (T. Peterfalvi, *Character Theory for the Odd
Order Theorem*, LMS LNS 272, 2000, §2 line 19) is the `ℤ`-submodule of complex-valued
class functions on `G` generated by the irreducible characters.  Its elements are the
**virtual characters** of `G`.

## Main definitions

* `OddOrder.RepresentationTheory.IsIrreducibleCharacter φ` — predicate: `φ` is the character
  of some finite-dimensional irreducible `ℂ`-representation of `G` (on a vector space in the
  base universe `Type 0`; this covers every isomorphism class of such representations).
* `OddOrder.RepresentationTheory.irreducibleCharacters G` — the set of irreducible
  characters on `G`. Peterfalvi notation: `Irr(G)`.
* `OddOrder.RepresentationTheory.ZIrr G` — `Submodule ℤ (ClassFunction G ℂ)`, Peterfalvi's
  `ℤ[Irr G]`.
* `OddOrder.RepresentationTheory.repCharacterClassFunction` — the canonical
  `ClassFunction G ℂ` attached to a finite-dimensional `ℂ`-representation `ρ` of `G`.

## mathlib v4.29.1 状況

`Representation.character`, `Representation.IsIrreducible`, `FDRep.character`, and
`char_orthonormal` are available, but neither `Irr(G)` as a set of class functions nor
`ℤ[Irr G]` as a `Submodule ℤ` exist in mathlib. This module provides them.

## TODO (本 commit 範囲外)

* Cardinality `Fintype.card (irreducibleCharacters G) = #conj-classes` — needs the Wave 1a
  `BrauerPermutation` module + a finite indexing API for `Irr(G)`.
* Coercion / constructor from `FDRep ℂ G` (categorical irreducibility ⇔
  `Representation.IsIrreducible`); will need `G : Type 0` to align FDRep's universe
  parameter with `ℂ`.
* `Submodule.span` characterization in terms of finite `ℤ`-linear combinations of
  irreducibles (for §4 (2.6.b) and §7 Coherence).

## References

* Peterfalvi §2 line 19 (`ℤ[Irr G]`); §3 (1.4) (`τ : ℤ[X, H^#] → ℤ[Irr G]`); §4 (2.6.b)
  (Dade isometry sends virtual characters to virtual characters).
* mathlib `Mathlib.RepresentationTheory.Character`,
  `Mathlib.RepresentationTheory.Irreducible`.
-/

namespace OddOrder.RepresentationTheory

open scoped MonoidAlgebra

variable {G : Type*} [Group G]

/-- The trivial complex character, as a class function: it is constantly `1`. -/
def trivialClassFunction (G : Type*) [Group G] : ClassFunction G ℂ :=
  ⟨fun _ => 1, fun _ _ => rfl⟩

@[simp] theorem trivialClassFunction_apply (g : G) :
    trivialClassFunction G g = 1 :=
  rfl

section RepToClassFunction

variable {V : Type} [AddCommGroup V] [Module ℂ V] [FiniteDimensional ℂ V]

/-- The `ClassFunction G ℂ` attached to a finite-dimensional `ℂ`-representation `ρ` of `G`:
its value at `g` is the trace of `ρ g`. Conjugation invariance follows from
`Representation.char_conj`.

`V` is restricted to `Type 0`; this is sufficient for the irreducible character predicate
because every finite-dimensional `ℂ`-representation has a representative on a vector space
in `Type 0` (e.g. `Fin n → ℂ`). -/
noncomputable def repCharacterClassFunction (ρ : Representation ℂ G V) :
    ClassFunction G ℂ :=
  ⟨ρ.character, fun g h => ρ.char_conj g h⟩

omit [FiniteDimensional ℂ V] in
@[simp] theorem repCharacterClassFunction_apply (ρ : Representation ℂ G V) (g : G) :
    (repCharacterClassFunction ρ : G → ℂ) g = ρ.character g := rfl

end RepToClassFunction

/-- A class function `φ : ClassFunction G ℂ` is an **irreducible character** if there is a
finite-dimensional irreducible `ℂ`-representation `ρ` of `G` (on a vector space in `Type 0`)
whose character is `φ`. -/
def IsIrreducibleCharacter (φ : ClassFunction G ℂ) : Prop :=
  ∃ (V : Type) (_ : AddCommGroup V) (_ : Module ℂ V) (_ : FiniteDimensional ℂ V)
      (ρ : Representation ℂ G V), Representation.IsIrreducible ρ ∧
        (φ : G → ℂ) = ρ.character

/-- The trivial class function is an irreducible character. -/
theorem trivialClassFunction_isIrreducible :
    IsIrreducibleCharacter (trivialClassFunction G) := by
  let ρ : Representation ℂ G ℂ := Representation.trivial ℂ G ℂ
  refine ⟨ℂ, inferInstance, inferInstance, inferInstance, ρ, ?_, ?_⟩
  · change IsSimpleOrder (Subrepresentation ρ)
    refine { toNontrivial := ?_, eq_bot_or_eq_top := ?_ }
    · refine ⟨⟨⊥, ⊤, ?_⟩⟩
      intro h
      have hmem : (1 : ℂ) ∈ (⊥ : Subrepresentation ρ) := by
        rw [h]
        trivial
      have hone : (1 : ℂ) = 0 := by
        change (1 : ℂ) ∈ (⊥ : Submodule ℂ ℂ) at hmem
        simpa only [Submodule.mem_bot] using hmem
      exact one_ne_zero hone
    · intro S
      by_cases hS : S = ⊥
      · exact Or.inl hS
      · right
        apply le_antisymm le_top
        intro z _
        have hnonzero : ∃ y : ℂ, y ∈ S ∧ y ≠ 0 := by
          by_contra h
          apply hS
          apply le_antisymm
          · intro y hy
            have hy0 : y = 0 := by
              by_contra hy0
              exact h ⟨y, hy, hy0⟩
            subst hy0
            change (0 : ℂ) ∈ (⊥ : Submodule ℂ ℂ)
            simp
          · exact bot_le
        obtain ⟨y, hyS, hy0⟩ := hnonzero
        have hz : z = (z / y) • y := by
          calc
            z = (z / y) * y := by field_simp [hy0]
            _ = (z / y) • y := rfl
        rw [hz]
        exact S.toSubmodule.smul_mem (z / y) hyS
  · funext g
    simp [Representation.character]

/-- The set of irreducible characters of `G` (Peterfalvi `Irr(G)`). -/
def irreducibleCharacters (G : Type*) [Group G] : Set (ClassFunction G ℂ) :=
  { φ | IsIrreducibleCharacter φ }

@[simp] theorem mem_irreducibleCharacters {φ : ClassFunction G ℂ} :
    φ ∈ irreducibleCharacters G ↔ IsIrreducibleCharacter φ := Iff.rfl

/-- Peterfalvi's `ℤ[Irr G]`: the `ℤ`-submodule of `ClassFunction G ℂ` spanned by the
irreducible characters. Members are **virtual characters**. -/
def ZIrr (G : Type*) [Group G] : Submodule ℤ (ClassFunction G ℂ) :=
  Submodule.span ℤ (irreducibleCharacters G)

theorem ZIrr_eq_span :
    ZIrr G = Submodule.span ℤ (irreducibleCharacters G) := rfl

/-- Every irreducible character is a virtual character. -/
theorem IsIrreducibleCharacter.mem_ZIrr {φ : ClassFunction G ℂ}
    (hφ : IsIrreducibleCharacter φ) : φ ∈ ZIrr G :=
  Submodule.subset_span hφ

/-- The character of a finite-dimensional irreducible `ℂ`-representation (on `Type 0`) is a
virtual character. -/
theorem repCharacterClassFunction_mem_ZIrr
    {V : Type} [AddCommGroup V] [Module ℂ V] [FiniteDimensional ℂ V]
    {ρ : Representation ℂ G V} (hρ : Representation.IsIrreducible ρ) :
    repCharacterClassFunction ρ ∈ ZIrr G := by
  refine IsIrreducibleCharacter.mem_ZIrr ?_
  exact ⟨V, inferInstance, inferInstance, inferInstance, ρ, hρ, rfl⟩

/-- The irreducible characters of `G`, viewed as a subset of `ZIrr G`. -/
theorem irreducibleCharacters_subset_ZIrr :
    irreducibleCharacters G ⊆ (ZIrr G : Set (ClassFunction G ℂ)) :=
  fun _ hφ => IsIrreducibleCharacter.mem_ZIrr hφ

end OddOrder.RepresentationTheory
