/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.FieldTheory.Minpoly.IsIntegrallyClosed
import OddOrder.GroupTheory.RepresentationTheory.Modular.VirtualCharacterSplitting

/-!
# Gorenstein Lemma 7.4: descending from `ℤ[ω]`-coefficients to `ℤ`-coefficients

The Brauer–Tate argument runs inside `v_R(G) = ℤ[ω] · v(G)`, where `ω` is a root of unity: the
class function of Lemma 7.6 is `∑_i \overline{ψ_i(u)} ψ_i`, whose coefficients are roots of unity
and *not* integers.  Only at the very end (Lemma 7.9) does one need to come back to `ℤ`, and
Lemma 7.4 is what allows it:

`ch(G) ∩ v_R(G) = v(G)`.

The proof here extracts coefficients through the pairing rather than through linear independence
of `Irr(G)`.  If `θ = ∑_{j<n} ω^j • u_j` with `u_j ∈ v(G)`, then for each block character `χ_i`

`(θ, χ_i) = ∑_{j<n} ω^j (u_j, χ_i)`,

and both `(θ, χ_i)` and every `(u_j, χ_i)` are rational integers (`charPairing_mem_intRange`, using
`v(G) ⊆ ch(G)`).  Since `1, ω, …, ω^{n-1}` are `ℤ`-linearly independent — they are a `ℤ`-basis of
`ℤ[ω]`, `Algebra.adjoin.powerBasis'` — the coefficient of `ω^0` must be `(θ, χ_i)` and all the
others must vanish.  So `u_0` and `θ` have the same pairings against every `χ_i`, hence are equal
(`eq_of_charPairing_eq`), and `θ = u_0 ∈ v(G)`.

## Main definitions

* `OddOrder.RepresentationTheory.adjoinSpan` — `ℤ[ω] · M`

## Main results

* `OddOrder.RepresentationTheory.exists_intCast_sum_pow` — `ℤ[ω]` is `ℤ`-spanned by
  `1, ω, …, ω^{n-1}`
* `OddOrder.RepresentationTheory.eq_zero_of_sum_intCast_pow_eq_zero` — and they are independent
* `OddOrder.RepresentationTheory.exists_sum_pow_smul_of_mem_adjoinSpan` — normal form in `ℤ[ω]·M`
* `OddOrder.RepresentationTheory.Modular.mem_inducedVirtualCharacters_of_mem_adjoinSpan` —
  **Lemma 7.4**

## References

* D. Gorenstein, *Finite Groups*, §4.7, Lemma 7.4 (`references/gorenstein/pages/`).
-/

namespace OddOrder.RepresentationTheory

/-! ### `ℤ[ω]` is free on `1, ω, …, ω ^ (n-1)` -/

section Adjoin

variable {K : Type*} [Field K] [CharZero K] {ω : K} (hω : IsIntegral ℤ ω)

omit [CharZero K] in
include hω in
/-- The minimal polynomial of an integral element is not a constant. -/
theorem natDegree_minpoly_int_pos : 0 < (minpoly ℤ ω).natDegree :=
  minpoly.natDegree_pos hω

include hω in
/-- The `i`-th element of the power basis of `ℤ[ω]` is `ω ^ i`. -/
theorem coe_adjoin_powerBasis_basis (i : Fin (Algebra.adjoin.powerBasis' hω).dim) :
    (Subalgebra.val (Algebra.adjoin ℤ ({ω} : Set K))) ((Algebra.adjoin.powerBasis' hω).basis i)
      = ω ^ (i : ℕ) := by
  rw [PowerBasis.coe_basis, map_pow, Algebra.adjoin.powerBasis'_gen]
  rfl

include hω in
/-- **`ℤ[ω]` is `ℤ`-spanned by `1, ω, …, ω ^ (n-1)`**, `n` the degree of the minimal polynomial:
the power basis of `Algebra.adjoin ℤ {ω}`, pushed into `K`. -/
theorem exists_intCast_sum_pow {x : K} (hx : x ∈ Algebra.adjoin ℤ ({ω} : Set K)) :
    ∃ c : Fin (minpoly ℤ ω).natDegree → ℤ, x = ∑ i, (c i : K) * ω ^ (i : ℕ) := by
  classical
  refine ⟨fun i => (Algebra.adjoin.powerBasis' hω).basis.equivFun ⟨x, hx⟩ i, ?_⟩
  have hs := congrArg (Subalgebra.val (Algebra.adjoin ℤ ({ω} : Set K)))
    ((Algebra.adjoin.powerBasis' hω).basis.sum_equivFun
      (⟨x, hx⟩ : ↥(Algebra.adjoin ℤ ({ω} : Set K))))
  rw [map_sum] at hs
  refine hs.symm.trans (Finset.sum_congr rfl fun i _ => ?_)
  rw [map_zsmul, zsmul_eq_mul, coe_adjoin_powerBasis_basis hω]

include hω in
set_option backward.isDefEq.respectTransparency false in
/-- **`1, ω, …, ω ^ (n-1)` are `ℤ`-linearly independent.** -/
theorem eq_zero_of_sum_intCast_pow_eq_zero {c : Fin (minpoly ℤ ω).natDegree → ℤ}
    (h : ∑ i, (c i : K) * ω ^ (i : ℕ) = 0) (i : Fin (minpoly ℤ ω).natDegree) : c i = 0 := by
  classical
  refine Fintype.linearIndependent_iff.mp
    (Algebra.adjoin.powerBasis' hω).basis.linearIndependent c ?_ i
  refine Subtype.ext ?_
  have hval : (Subalgebra.val (Algebra.adjoin ℤ ({ω} : Set K)))
      (∑ i, c i • (Algebra.adjoin.powerBasis' hω).basis i)
      = ∑ i, (c i : K) * ω ^ (i : ℕ) := by
    rw [map_sum]
    exact Finset.sum_congr rfl fun i _ => by
      rw [map_zsmul, zsmul_eq_mul, coe_adjoin_powerBasis_basis hω]
  exact hval.trans h

end Adjoin

/-! ### The `ℤ[ω]`-span of an additive subgroup -/

section AdjoinSpan

variable {K V : Type*} [Field K] [AddCommGroup V] [Module K V]

/-- **`ℤ[ω] · M`**, as the additive group generated by the `ω ^ j • w` with `w ∈ M`. -/
def adjoinSpan (ω : K) (M : AddSubgroup V) : AddSubgroup V :=
  AddSubgroup.closure { f | ∃ (j : ℕ) (w : V), w ∈ M ∧ f = ω ^ j • w }

variable {ω : K} {M : AddSubgroup V}

theorem pow_smul_mem_adjoinSpan (j : ℕ) {w : V} (hw : w ∈ M) : ω ^ j • w ∈ adjoinSpan ω M :=
  AddSubgroup.subset_closure ⟨j, w, hw, rfl⟩

theorem le_adjoinSpan : M ≤ adjoinSpan ω M := fun w hw => by
  simpa using pow_smul_mem_adjoinSpan (ω := ω) 0 hw

theorem adjoinSpan_mono {M' : AddSubgroup V} (h : M ≤ M') : adjoinSpan ω M ≤ adjoinSpan ω M' :=
  AddSubgroup.closure_mono <| by rintro f ⟨j, w, hw, rfl⟩; exact ⟨j, w, h hw, rfl⟩

variable [CharZero K] (hω : IsIntegral ℤ ω)

include hω in
/-- **Multiplying by a cyclotomic integer stays inside `ℤ[ω] · M`.** -/
theorem smul_mem_adjoinSpan_of_mem_adjoin {r : K} (hr : r ∈ Algebra.adjoin ℤ ({ω} : Set K))
    {w : V} (hw : w ∈ M) : r • w ∈ adjoinSpan ω M := by
  classical
  obtain ⟨c, hc⟩ := exists_intCast_sum_pow hω hr
  rw [hc, Finset.sum_smul]
  refine sum_mem fun i _ => ?_
  rw [mul_smul]
  rw [show ((c i : ℤ) : K) • (ω ^ (i : ℕ) • w) = (c i) • (ω ^ (i : ℕ) • w) from
    Int.cast_smul_eq_zsmul K (c i) (ω ^ (i : ℕ) • w)]
  exact zsmul_mem (pow_smul_mem_adjoinSpan _ hw) _

include hω in
/-- **Normal form in `ℤ[ω] · M`**: every element is `∑_{j < n} ω^j • u j` with `u j ∈ M`. -/
theorem exists_sum_pow_smul_of_mem_adjoinSpan {x : V} (hx : x ∈ adjoinSpan ω M) :
    ∃ u : Fin (minpoly ℤ ω).natDegree → V, (∀ j, u j ∈ M) ∧
      x = ∑ j : Fin (minpoly ℤ ω).natDegree, ω ^ (j : ℕ) • u j := by
  classical
  -- the set of elements in normal form is an additive subgroup containing the generators
  let W : AddSubgroup V :=
    { carrier := { x | ∃ u : Fin (minpoly ℤ ω).natDegree → V, (∀ j, u j ∈ M) ∧
        x = ∑ j : Fin (minpoly ℤ ω).natDegree, ω ^ (j : ℕ) • u j }
      zero_mem' := ⟨0, fun _ => M.zero_mem, by simp⟩
      add_mem' := by
        rintro a b ⟨u, hu, rfl⟩ ⟨v, hv, rfl⟩
        refine ⟨u + v, fun j => M.add_mem (hu j) (hv j), ?_⟩
        rw [← Finset.sum_add_distrib]
        exact Finset.sum_congr rfl fun j _ => by rw [Pi.add_apply, smul_add]
      neg_mem' := by
        rintro a ⟨u, hu, rfl⟩
        refine ⟨-u, fun j => M.neg_mem (hu j), ?_⟩
        rw [← Finset.sum_neg_distrib]
        exact Finset.sum_congr rfl fun j _ => by rw [Pi.neg_apply, smul_neg] }
  have hgen : { f : V | ∃ (j : ℕ) (w : V), w ∈ M ∧ f = ω ^ j • w } ⊆ (W : Set V) := by
    rintro f ⟨j, w, hw, rfl⟩
    obtain ⟨c, hc⟩ := exists_intCast_sum_pow hω
      (x := ω ^ j) (Subalgebra.pow_mem _ (Algebra.self_mem_adjoin_singleton ℤ ω) j)
    refine ⟨fun i => (c i) • w, fun i => M.zsmul_mem hw _, ?_⟩
    rw [hc, Finset.sum_smul]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [mul_smul, Int.cast_smul_eq_zsmul K (c i) (ω ^ (i : ℕ) • w), smul_comm]
  exact (AddSubgroup.closure_le W).mpr hgen hx

end AdjoinSpan

/-! ### Lemma 7.4 -/

namespace Modular

variable {K G : Type*} [Field K] [CharZero K] [Group G] [Fintype G] {ι' : Type*} {m : ι' → Type*}
  [∀ i, Fintype (m i)] [∀ i, DecidableEq (m i)] [∀ i, Nonempty (m i)]
  (e : MonoidAlgebra K G ≃ₐ[K] ∀ j, Matrix (m j) (m j) K)
  [Finite ι'] [Invertible (Nat.card G : K)]
  {ω : K} (hω : IsIntegral ℤ ω) {𝒳 : Set (Subgroup G)}

include e hω in
/-- **Gorenstein Lemma 7.4**: a virtual character lying in `ℤ[ω] · v(G)` already lies in `v(G)`. -/
theorem mem_inducedVirtualCharacters_of_mem_adjoinSpan {θ : G → K}
    (hchθ : θ ∈ virtualCharacters K G)
    (hθ : θ ∈ adjoinSpan ω (inducedVirtualCharacters K 𝒳)) :
    θ ∈ inducedVirtualCharacters K 𝒳 := by
  classical
  obtain ⟨u, hu, rfl⟩ := exists_sum_pow_smul_of_mem_adjoinSpan hω hθ
  obtain ⟨j₀, hj₀⟩ : ∃ j₀ : Fin (minpoly ℤ ω).natDegree, (j₀ : ℕ) = 0 :=
    ⟨⟨0, natDegree_minpoly_int_pos hω⟩, rfl⟩
  -- every `u j` is a virtual character
  have huch : ∀ j, u j ∈ virtualCharacters K G := fun j =>
    inducedVirtualCharacters_le_virtualCharacters e 𝒳 (hu j)
  -- pairing the normal form against a block character
  have hpair : ∀ i : ι', charPairing K (∑ j : Fin (minpoly ℤ ω).natDegree, ω ^ (j : ℕ) • u j)
      (wedderburnRepresentation e i).character
      = ∑ j : Fin (minpoly ℤ ω).natDegree, ω ^ (j : ℕ)
        * charPairing K (u j) (wedderburnRepresentation e i).character := by
    intro i
    simp only [charPairing]
    rw [Finset.sum_congr rfl fun g (_ : g ∈ Finset.univ) =>
      show (∑ j : Fin (minpoly ℤ ω).natDegree, ω ^ (j : ℕ) • u j) g⁻¹
            * (wedderburnRepresentation e i).character g
          = ∑ j : Fin (minpoly ℤ ω).natDegree, ω ^ (j : ℕ)
            * (u j g⁻¹ * (wedderburnRepresentation e i).character g) from by
        rw [Finset.sum_apply, Finset.sum_mul]
        exact Finset.sum_congr rfl fun j _ => by rw [Pi.smul_apply, smul_eq_mul]; ring,
      Finset.sum_comm, Finset.mul_sum]
    exact Finset.sum_congr rfl fun j _ => by rw [← Finset.mul_sum]; ring
  -- the coefficients are integers
  choose b hb using fun (j : Fin (minpoly ℤ ω).natDegree) (i : ι') =>
    charPairing_mem_intRange (huch j) (mem_virtualCharacters_wedderburnRepresentation e i)
  choose a ha using fun (i : ι') =>
    charPairing_mem_intRange hchθ (mem_virtualCharacters_wedderburnRepresentation e i)
  -- `ℤ`-independence of the powers of `ω` forces the `ω^0`-coefficient
  have hzero : ∀ i : ι', ∀ j : Fin (minpoly ℤ ω).natDegree,
      (if j = j₀ then b j i - a i else b j i) = 0 := by
    intro i
    refine fun j => eq_zero_of_sum_intCast_pow_eq_zero
      (c := fun j => if j = j₀ then b j i - a i else b j i) hω ?_ j
    have hsum : ∑ j : Fin (minpoly ℤ ω).natDegree, ((b j i : ℤ) : K) * ω ^ (j : ℕ)
        = (a i : K) := by
      rw [show ((a i : ℤ) : K)
          = charPairing K (∑ j : Fin (minpoly ℤ ω).natDegree, ω ^ (j : ℕ) • u j)
            (wedderburnRepresentation e i).character from ha i, hpair i]
      exact Finset.sum_congr rfl fun j _ => by
        rw [show ((b j i : ℤ) : K)
          = charPairing K (u j) (wedderburnRepresentation e i).character from hb j i]; ring
    have hexp : ∀ j : Fin (minpoly ℤ ω).natDegree,
        ((if j = j₀ then b j i - a i else b j i : ℤ) : K) * ω ^ (j : ℕ)
          = ((b j i : ℤ) : K) * ω ^ (j : ℕ) - (if j = j₀ then ((a i : ℤ) : K) else 0) := by
      intro j
      by_cases hjj : j = j₀
      · subst hjj
        rw [if_pos rfl, if_pos rfl, Int.cast_sub, sub_mul, hj₀]
        norm_num
      · rw [if_neg hjj, if_neg hjj, sub_zero]
    rw [Finset.sum_congr rfl fun j (_ : j ∈ Finset.univ) => hexp j, Finset.sum_sub_distrib, hsum]
    simp
  -- so `u j₀` and `θ` pair identically against every block character
  have hEq : (∑ j : Fin (minpoly ℤ ω).natDegree, ω ^ (j : ℕ) • u j) = u j₀ := by
    refine eq_of_charPairing_eq e (fun g h => virtualCharacters_conj hchθ g h)
      (fun g h => virtualCharacters_conj (huch j₀) g h) fun i => ?_
    have h0 := hzero i j₀
    rw [if_pos rfl, sub_eq_zero] at h0
    rw [← ha i, ← hb j₀ i, h0]
  rw [hEq]
  exact hu j₀

end Modular

end OddOrder.RepresentationTheory
