/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.RingTheory.WittVector.Complete
import Mathlib.RingTheory.WittVector.DiscreteValuationRing
import Mathlib.Algebra.CharP.Algebra
import Mathlib.FieldTheory.IsAlgClosed.Basic
import OddOrder.GroupTheory.RepresentationTheory.Modular.PModularSystem

/-!
# Witt vectors of a perfect field of characteristic `p` form a `p`-modular system

Let `k` be a perfect field of characteristic `p`.  The ring of Witt vectors `𝕎 k` is the
*unramified* coefficient ring of modular representation theory over `k`: it is a complete
discrete valuation ring of characteristic `0` whose residue field is `k` itself.  This file
records that data as an `IsPModularSystem p (𝕎 k)` instance.

Together with `PModularSystem.lean` (which only exhibits `ℤ_[p]`, whose residue field is the
prime field `ZMod p`) this is what makes *splitting* systems available: choosing `k` to be a
large enough finite field puts all the `p'`-roots of unity one needs into the residue field,
and `RootsOfUnityLift` then lifts them to `𝕎 k`.  See `SplittingSystem.lean`.

Everything rests on two mathlib results about a perfect `k` of characteristic `p`:
`WittVector.quotientPEquiv` (`𝕎 k ⧸ (p) ≃+* k`) and `WittVector.isAdicCompleteIdealSpanP`
(`𝕎 k` is `p`-adically complete); `WittVector.isDiscreteValuationRing` supplies `IsLocalRing`.

## Main results

* `OddOrder.RepresentationTheory.Modular.maximalIdeal_wittVector` — `𝔪(𝕎 k) = (p)`
* `OddOrder.RepresentationTheory.Modular.wittVectorResidueFieldEquiv` — `ResidueField (𝕎 k) ≃+* k`
* `OddOrder.RepresentationTheory.Modular.instIsAlgClosedResidueFieldWittVector`
* `OddOrder.RepresentationTheory.Modular.instIsPModularSystemWittVector` — the system itself
-/

namespace OddOrder.RepresentationTheory.Modular

open IsLocalRing

section WittVector

variable {p : ℕ} [hp : Fact p.Prime] (k : Type*) [Field k] [CharP k p] [PerfectRing k p]

/-- `p` is nonzero in `𝕎 k`.

`WittVector.eq_zero_of_p_mul_eq_zero` says that `𝕎 k` is `p`-torsion free; applied to `1` it
turns `(p : 𝕎 k) = 0` into `1 = 0`. -/
theorem wittVector_natCast_p_ne_zero : ((p : ℕ) : WittVector p k) ≠ 0 := fun h => by
  have h1 : (1 : WittVector p k) * ((p : ℕ) : WittVector p k) = 0 := by rw [h, mul_zero]
  exact one_ne_zero (WittVector.eq_zero_of_p_mul_eq_zero (k := k) 1 h1)

/-- The ideal `(p)` of `𝕎 k` is maximal, because the quotient by it is the field `k`
(`WittVector.quotientPEquiv`). -/
theorem isMaximal_span_natCast_p : (Ideal.span {((p : ℕ) : WittVector p k)}).IsMaximal := by
  rw [Ideal.Quotient.maximal_ideal_iff_isField_quotient]
  exact (WittVector.quotientPEquiv (p := p) (k := k)).toMulEquiv.isField (Field.toIsField k)

/-- **The maximal ideal of `𝕎 k` is generated by `p`.**  (`𝕎 k` is local because it is a
discrete valuation ring, `WittVector.isDiscreteValuationRing`.) -/
theorem maximalIdeal_wittVector :
    maximalIdeal (WittVector p k) = Ideal.span {((p : ℕ) : WittVector p k)} :=
  (IsLocalRing.eq_maximalIdeal (isMaximal_span_natCast_p k)).symm

instance instIsAdicCompleteMaximalIdealWittVector :
    IsAdicComplete (maximalIdeal (WittVector p k)) (WittVector p k) := by
  rw [maximalIdeal_wittVector]
  infer_instance

instance instHenselianLocalRingWittVector : HenselianLocalRing (WittVector p k) :=
  henselianLocalRing_of_isAdicComplete _

/-- **The residue field of `𝕎 k` is `k`.** -/
noncomputable def wittVectorResidueFieldEquiv : ResidueField (WittVector p k) ≃+* k :=
  (Ideal.quotEquivOfEq (maximalIdeal_wittVector k)).trans WittVector.quotientPEquiv

instance instCharPResidueFieldWittVector : CharP (ResidueField (WittVector p k)) p :=
  charP_of_injective_ringHom (wittVectorResidueFieldEquiv k).symm.toRingHom.injective p

/-- **The residue field inherits algebraic closedness.**  Taking `k` algebraically closed makes
`𝕎 k` a `p`-modular system whose residue field splits every group algebra, which is the setting
of Brauer's count. -/
instance instIsAlgClosedResidueFieldWittVector [IsAlgClosed k] :
    IsAlgClosed (ResidueField (WittVector p k)) :=
  IsAlgClosed.of_ringEquiv k _ (wittVectorResidueFieldEquiv k).symm

/-- A nonzero natural number stays nonzero in `𝕎 k`.

Split `n = p ^ a * m` with `p ∤ m` (`Nat.ordProj_mul_ordCompl_eq_self`).  The factor `m` has
nonzero constant coefficient, hence is nonzero, `p` is nonzero by
`wittVector_natCast_p_ne_zero`, and `𝕎 k` is a domain. -/
theorem wittVector_natCast_ne_zero {n : ℕ} (hn : n ≠ 0) : ((n : ℕ) : WittVector p k) ≠ 0 := by
  have hsplit : ((n : ℕ) : WittVector p k)
      = ((p : ℕ) : WittVector p k) ^ n.factorization p
        * ((ordCompl[p] n : ℕ) : WittVector p k) := by
    rw [← Nat.cast_pow, ← Nat.cast_mul, Nat.ordProj_mul_ordCompl_eq_self n p]
  have hcompl : ((ordCompl[p] n : ℕ) : WittVector p k) ≠ 0 := by
    intro h0
    have hk : ((ordCompl[p] n : ℕ) : k) = 0 := by
      simpa using congrArg (WittVector.constantCoeff (p := p) (R := k)) h0
    exact Nat.not_dvd_ordCompl hp.out hn ((CharP.cast_eq_zero_iff k p _).mp hk)
  rw [hsplit]
  exact mul_ne_zero (pow_ne_zero _ (wittVector_natCast_p_ne_zero k)) hcompl

instance instCharZeroWittVector : CharZero (WittVector p k) :=
  charZero_of_inj_zero fun _ hn => by
    by_contra hne
    exact wittVector_natCast_ne_zero k hne hn

/-- **Witt vectors of a perfect field of characteristic `p` form a `p`-modular system.** -/
instance instIsPModularSystemWittVector : IsPModularSystem p (WittVector p k) where

end WittVector

end OddOrder.RepresentationTheory.Modular
