/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Isaacs.Ch04_Commutators.Main

/-! # Isaacs §4B: Mann's theorem on small conjugacy classes (pp. 125-128)

Isaacs, *Finite Group Theory* (AMS GSM 92, 2008), §4B, pp. 125-128: the subgroup
`M(G)` generated by the conjugacy classes of the two smallest sizes, and Mann's
theorems bounding its nilpotence class.

* **M(G)** (p. 125): `mannSubgroup` — generated by all elements `x` whose class size
  `classCard x` is a lower bound for every nontrivial class size (equivalently: the
  classes of size `n₁ = 1` together with the classes of the smallest nontrivial size
  `n₂`; this encoding avoids mentioning `n₂` and degenerates gracefully for abelian
  `G`, where `M(G) = G`).
* **Lemma 4.17** (p. 127): `card_centralizer_lt_card_centralizer_commutator` —
  `K ⊴ G` abelian, `x ∉ Z(G)`, `k ∈ K` ⟹ `|C_G(x)| < |C_G(⁅k,x⁆)|`.
* **Corollary 4.18** (p. 127): `commutator_mannSubgroup_le_center` —
  `K ⊴ G` abelian ⟹ `⁅K, M(G)⁆ ≤ Z(G)`.
* **Theorem 4.15** (p. 128): `commutator_mannSubgroup_four_eq_bot_of_centralizer_eq_self`
  (γ₄-form), with `Group.IsNilpotent` / `Group.nilpotencyClass ≤ 3` corollaries.
* **Lemma 4.16** (p. 126), generalized from the `p`-group case
  (`OddOrder.GroupTheory.CriticalSubgroup.centralizer_eq_self_of_maximal_abelian_normal`)
  to nilpotent groups: `centralizer_eq_self_of_maximal_abelian_normal_of_isNilpotent`
  (finiteness is not needed), plus the existence corollary
  `exists_normal_abelian_centralizer_eq_self` for finite nilpotent groups.
* **Theorem 4.14** (Mann, p. 126): `lowerCentralSeries_mannSubgroup_eq_bot_of_isNilpotent`
  — `G` finite nilpotent ⟹ `M(G)` has class at most `3`.
* **Theorem 4.19** (Mann, p. 128): `lowerCentralSeries_map_fitting_mannSubgroup_eq_bot`
  — for arbitrary finite `G`, the Fitting subgroup `F(M(G))` has class at most `4`.

Nilpotence class `≤ c` is encoded ambiently as `S.lowerCentralSeries c = ⊥` (mathlib
indexing: `Subgroup.lowerCentralSeries S c` is `γ_{c+1}(S)` computed in the ambient
group), with `Group.nilpotencyClass ↥S ≤ c` versions derived via
`Subgroup.top_subtype_lowerCentralSeries`.
-/

namespace OddOrder.Isaacs.Ch04

open scoped commutatorElement Pointwise

variable {G : Type*} [Group G]

section /- 4B: conjugacy class sizes and the Mann subgroup M(G) (p. 125) -/

/-- The size of the conjugacy class of `x`, encoded as the index of its centralizer
(orbit–stabilizer). Takes the junk value `0` when the index is infinite. -/
noncomputable def classCard (x : G) : ℕ :=
  (Subgroup.centralizer {x}).index

theorem classCard_def (x : G) : classCard x = (Subgroup.centralizer {x}).index := rfl

/-- The centralizer of a single element is everything iff the element is central. -/
theorem centralizer_singleton_eq_top_iff {x : G} :
    Subgroup.centralizer ({x} : Set G) = ⊤ ↔ x ∈ Subgroup.center G := by
  constructor
  · intro h
    rw [Subgroup.mem_center_iff]
    intro g
    exact Subgroup.mem_centralizer_singleton_iff.mp (h ▸ Subgroup.mem_top g)
  · intro hx
    rw [eq_top_iff]
    intro g _
    exact Subgroup.mem_centralizer_singleton_iff.mpr (Subgroup.mem_center_iff.mp hx g)

/-- `classCard x = 1` iff `x` is central. -/
theorem classCard_eq_one_iff {x : G} : classCard x = 1 ↔ x ∈ Subgroup.center G := by
  rw [classCard_def, Subgroup.index_eq_one, centralizer_singleton_eq_top_iff]

theorem classCard_pos [Finite G] (x : G) : 0 < classCard x :=
  Nat.pos_of_ne_zero Subgroup.index_ne_zero_of_finite

theorem one_lt_classCard_iff [Finite G] {x : G} :
    1 < classCard x ↔ x ∉ Subgroup.center G := by
  rw [← classCard_eq_one_iff]
  have := classCard_pos x
  omega

/-- Conjugation permutes centralizers: `C_G(gxg⁻¹) = (C_G(x))^g`. -/
theorem centralizer_singleton_conj (g x : G) :
    Subgroup.centralizer ({g * x * g⁻¹} : Set G) =
      (Subgroup.centralizer ({x} : Set G)).map (MulAut.conj g : G →* G) := by
  ext t
  rw [Subgroup.mem_centralizer_singleton_iff, Subgroup.mem_map]
  constructor
  · intro h
    refine ⟨g⁻¹ * t * g, ?_, ?_⟩
    · rw [Subgroup.mem_centralizer_singleton_iff]
      calc g⁻¹ * t * g * x = g⁻¹ * (t * (g * x * g⁻¹)) * g := by group
        _ = g⁻¹ * (g * x * g⁻¹ * t) * g := by rw [h]
        _ = x * (g⁻¹ * t * g) := by group
    · show (MulAut.conj g : G →* G) (g⁻¹ * t * g) = t
      simp only [MonoidHom.coe_coe, MulAut.conj_apply]
      group
  · rintro ⟨s, hs, rfl⟩
    rw [Subgroup.mem_centralizer_singleton_iff] at hs
    simp only [MonoidHom.coe_coe, MulAut.conj_apply]
    calc g * s * g⁻¹ * (g * x * g⁻¹) = g * (s * x) * g⁻¹ := by group
      _ = g * (x * s) * g⁻¹ := by rw [hs]
      _ = g * x * g⁻¹ * (g * s * g⁻¹) := by group

/-- Class sizes are constant on conjugacy classes. -/
theorem classCard_conj (g x : G) : classCard (g * x * g⁻¹) = classCard x := by
  rw [classCard_def, classCard_def, centralizer_singleton_conj]
  exact Subgroup.index_map_equiv _ (MulAut.conj g)

/-- **Isaacs p. 125.** The generating set of `M(G)`: elements whose class size is a lower
bound for all nontrivial class sizes. Central elements (class size `1`) always qualify;
noncentral ones qualify exactly when their class has the smallest nontrivial size `n₂`. -/
def mannGenerators (G : Type*) [Group G] : Set G :=
  {x : G | ∀ z : G, 1 < classCard z → classCard x ≤ classCard z}

/-- **Isaacs p. 125, `M(G)`.** The subgroup generated by the elements lying in the
conjugacy classes of the two smallest sizes `n₁ = 1 < n₂` (encoded without mentioning
`n₂`: generators are the elements whose class size is `1` or a lower bound for all
nontrivial class sizes). For abelian `G` this gives `M(G) = G`. -/
def mannSubgroup (G : Type*) [Group G] : Subgroup G :=
  Subgroup.closure (mannGenerators G)

theorem mannSubgroup_eq_closure (G : Type*) [Group G] :
    mannSubgroup G = Subgroup.closure (mannGenerators G) := rfl

theorem mem_mannGenerators_iff {x : G} :
    x ∈ mannGenerators G ↔ ∀ z : G, 1 < classCard z → classCard x ≤ classCard z :=
  Iff.rfl

/-- Membership criterion for the generators of `M(G)`. -/
theorem mem_mannSubgroup_of_forall_classCard_le {x : G}
    (hx : ∀ z : G, 1 < classCard z → classCard x ≤ classCard z) :
    x ∈ mannSubgroup G :=
  Subgroup.subset_closure hx

/-- Central elements generate: `Z(G) ≤ M(G)`. -/
theorem center_le_mannSubgroup (G : Type*) [Group G] :
    Subgroup.center G ≤ mannSubgroup G := by
  intro x hx
  refine mem_mannSubgroup_of_forall_classCard_le fun z hz => ?_
  have h1 : classCard x = 1 := classCard_eq_one_iff.mpr hx
  omega

/-- The Mann generating set is closed under conjugation (class sizes are conjugation
invariant). -/
theorem mannGenerators_conj_mem {x : G} (hx : x ∈ mannGenerators G) (g : G) :
    g * x * g⁻¹ ∈ mannGenerators G := fun z hz => by
  rw [classCard_conj]
  exact hx z hz

/-- `M(G) ⊴ G`: the generating set of `M(G)` is a union of conjugacy classes. -/
instance mannSubgroup_normal : (mannSubgroup G).Normal := by
  constructor
  intro n hn g
  have hmap : (mannSubgroup G).map (MulAut.conj g : G →* G) = mannSubgroup G := by
    change (Subgroup.closure (mannGenerators G)).map _ = Subgroup.closure (mannGenerators G)
    rw [MonoidHom.map_closure]
    congr 1
    apply Set.Subset.antisymm
    · rintro _ ⟨x, hx, rfl⟩
      show (MulAut.conj g : G →* G) x ∈ mannGenerators G
      simp only [MonoidHom.coe_coe, MulAut.conj_apply]
      exact mannGenerators_conj_mem hx g
    · intro x hx
      refine ⟨g⁻¹ * x * g, by simpa using mannGenerators_conj_mem hx g⁻¹, ?_⟩
      show (MulAut.conj g : G →* G) (g⁻¹ * x * g) = x
      simp only [MonoidHom.coe_coe, MulAut.conj_apply]
      group
  rw [← hmap]
  exact Subgroup.mem_map.mpr
    ⟨n, hn, by simp only [MonoidHom.coe_coe, MulAut.conj_apply]⟩

end

section /- 4B: Lemma 4.17 — commutation shrinks centralizers (p. 127) -/

/-- Orbit–stabilizer for the conjugation action, in `Nat.card` form:
`|x^G| ⬝ |C_G(x)| = |G|`. -/
theorem card_conjOrbit_mul_card_centralizer [Finite G] (x : G) :
    Nat.card (MulAction.orbit (ConjAct G) x) *
      Nat.card (Subgroup.centralizer ({x} : Set G)) = Nat.card G := by
  have e1 : Nat.card (MulAction.orbit (ConjAct G) x) =
      (MulAction.stabilizer (ConjAct G) x).index := by
    rw [Subgroup.index_eq_card]
    exact Nat.card_congr (MulAction.orbitEquivQuotientStabilizer (ConjAct G) x)
  have e2 : Nat.card (Subgroup.centralizer ({x} : Set G)) =
      Nat.card (MulAction.stabilizer (ConjAct G) x) := by
    apply Nat.card_congr
    refine (Equiv.subtypeEquiv ConjAct.ofConjAct.toEquiv fun g => ?_).symm
    simp only [MulAction.mem_stabilizer_iff, Subgroup.mem_centralizer_singleton_iff,
      ConjAct.smul_def, mul_inv_eq_iff_eq_mul]
    exact Iff.rfl
  rw [e1, e2, Subgroup.index_mul_card]
  exact Nat.card_congr ConjAct.ofConjAct.toEquiv

/-- The centralizer of an element of `H`, computed inside `H`, is the restriction
(`subgroupOf`) of the ambient centralizer. -/
theorem centralizer_singleton_subgroupOf (H : Subgroup G) (w : ↥H) :
    Subgroup.centralizer ({w} : Set ↥H) =
      (Subgroup.centralizer ({(w : G)} : Set G)).subgroupOf H := by
  ext t
  rw [Subgroup.mem_centralizer_singleton_iff, Subgroup.mem_subgroupOf,
    Subgroup.mem_centralizer_singleton_iff]
  constructor
  · intro h
    simpa using congrArg Subtype.val h
  · intro h
    exact Subtype.ext (by simpa using h)

/-- **Isaacs Lemma 4.17, core case.** Let `K ⊴ G` be abelian with `G = K C_G(x)`, and let
`k ∈ K` with `y := ⁅k, x⁆ ≠ 1`. Then `|C_G(x)| < |C_G(y)|`.

Book's counting, orbit-style: with `T := {⁅t, x⁆ | t ∈ K}` (the image of the
homomorphism `θ : t ↦ ⁅t, x⁆` of the book), the conjugacy class of `x` is exactly
`T·x` (conjugating by `g = a·c`, `a ∈ K`, `c ∈ C_G(x)`, gives `gxg⁻¹ = ⁅a,x⁆x`),
while the class of `y` lands inside `T \ {1}`. Hence `|y^G| < |T| = |x^G|`, and
orbit–stabilizer flips the inequality to the centralizers. -/
theorem card_centralizer_lt_of_commutator_ne_one_of_sup_eq_top [Finite G]
    {K : Subgroup G} [K.Normal] (hK : ∀ a ∈ K, ∀ b ∈ K, a * b = b * a)
    {x k : G} (hk : k ∈ K)
    (htop : K ⊔ Subgroup.centralizer ({x} : Set G) = ⊤) (hy : ⁅k, x⁆ ≠ 1) :
    Nat.card (Subgroup.centralizer ({x} : Set G)) <
      Nat.card (Subgroup.centralizer ({⁅k, x⁆} : Set G)) := by
  classical
  set T : Set G := (fun t => ⁅t, x⁆) '' (K : Set G) with hT
  -- every element of `G` factors as (element of `K`) * (element of `C_G(x)`)
  have hdecomp : ∀ g : G, ∃ a ∈ K, ∃ c ∈ Subgroup.centralizer ({x} : Set G), g = a * c := by
    intro g
    have hg : g ∈ (↑(K ⊔ Subgroup.centralizer ({x} : Set G)) : Set G) := by
      rw [htop, Subgroup.coe_top]
      exact Set.mem_univ g
    rw [Subgroup.normal_mul, Set.mem_mul] at hg
    obtain ⟨a, ha, c, hc, hac⟩ := hg
    exact ⟨a, ha, c, hc, hac.symm⟩
  -- `T ⊆ K` (using normality of `K`)
  have hTK : T ⊆ (K : Set G) := by
    rintro w ⟨t, ht, rfl⟩
    change ⁅t, x⁆ ∈ (K : Set G)
    have heq : ⁅t, x⁆ = t * (x * t⁻¹ * x⁻¹) := by group
    rw [heq]
    exact K.mul_mem ht ((‹K.Normal›).conj_mem t⁻¹ (K.inv_mem ht) x)
  have h1T : (1 : G) ∈ T := ⟨1, K.one_mem, commutatorElement_one_left x⟩
  -- the conjugacy class of `x` is `T * x`
  have horbx : MulAction.orbit (ConjAct G) x = (fun w => w * x) '' T := by
    ext w
    constructor
    · rintro ⟨g, rfl⟩
      obtain ⟨a, ha, c, hc, hg⟩ := hdecomp (ConjAct.ofConjAct g)
      have hcx : c * x * c⁻¹ = x := by
        rw [mul_inv_eq_iff_eq_mul]
        exact Subgroup.mem_centralizer_singleton_iff.mp hc
      refine ⟨⁅a, x⁆, ⟨a, ha, rfl⟩, ?_⟩
      change ⁅a, x⁆ * x = g • x
      rw [ConjAct.smul_def, hg]
      calc ⁅a, x⁆ * x = a * x * a⁻¹ := by group
        _ = a * (c * x * c⁻¹) * a⁻¹ := by rw [hcx]
        _ = a * c * x * (a * c)⁻¹ := by group
    · rintro ⟨_, ⟨t, _, rfl⟩, rfl⟩
      refine ⟨ConjAct.toConjAct t, ?_⟩
      change ConjAct.toConjAct t • x = ⁅t, x⁆ * x
      rw [ConjAct.smul_def, ConjAct.ofConjAct_toConjAct]
      group
  -- the conjugacy class of `y = ⁅k, x⁆` lands in `T \ {1}`
  have horby : MulAction.orbit (ConjAct G) ⁅k, x⁆ ⊆ T \ {1} := by
    rintro w ⟨g, rfl⟩
    obtain ⟨a, ha, c, hc, hg⟩ := hdecomp (ConjAct.ofConjAct g)
    have hcx : c * x * c⁻¹ = x := by
      rw [mul_inv_eq_iff_eq_mul]
      exact Subgroup.mem_centralizer_singleton_iff.mp hc
    have hconj : c * ⁅k, x⁆ * c⁻¹ = ⁅c * k * c⁻¹, x⁆ := by
      have hfree : c * ⁅k, x⁆ * c⁻¹ = ⁅c * k * c⁻¹, c * x * c⁻¹⁆ := by group
      rw [hfree, hcx]
    have hckc : c * k * c⁻¹ ∈ K := (‹K.Normal›).conj_mem k hk c
    have hmemK : c * ⁅k, x⁆ * c⁻¹ ∈ K := by
      rw [hconj]
      exact hTK ⟨_, hckc, rfl⟩
    constructor
    · refine ⟨c * k * c⁻¹, hckc, ?_⟩
      change ⁅c * k * c⁻¹, x⁆ = g • ⁅k, x⁆
      rw [ConjAct.smul_def, hg]
      have hcomm : a * (c * ⁅k, x⁆ * c⁻¹) = c * ⁅k, x⁆ * c⁻¹ * a := hK a ha _ hmemK
      calc ⁅c * k * c⁻¹, x⁆ = c * ⁅k, x⁆ * c⁻¹ := hconj.symm
        _ = a * (c * ⁅k, x⁆ * c⁻¹) * a⁻¹ := by rw [hcomm]; group
        _ = a * c * ⁅k, x⁆ * (a * c)⁻¹ := by group
    · intro hmem1
      apply hy
      simp only [Set.mem_singleton_iff, ConjAct.smul_def] at hmem1
      calc ⁅k, x⁆ = (ConjAct.ofConjAct g)⁻¹ *
            (ConjAct.ofConjAct g * ⁅k, x⁆ * (ConjAct.ofConjAct g)⁻¹) *
            ConjAct.ofConjAct g := by group
        _ = 1 := by rw [hmem1]; group
  -- counting: `|y^G| < |T| = |x^G|`
  have hcard_x : Nat.card (MulAction.orbit (ConjAct G) x) = Nat.card T := by
    rw [horbx]
    exact Nat.card_image_of_injective (mul_left_injective x) T
  have hT1 : (T \ {1}).ncard < T.ncard := by
    have hpos : 0 < T.ncard := (Set.ncard_pos (Set.toFinite T)).mpr ⟨1, h1T⟩
    rw [Set.ncard_sdiff_singleton_of_mem h1T]
    omega
  have hcard_y_lt : Nat.card (MulAction.orbit (ConjAct G) ⁅k, x⁆) < Nat.card T := by
    calc Nat.card (MulAction.orbit (ConjAct G) ⁅k, x⁆)
        = (MulAction.orbit (ConjAct G) ⁅k, x⁆).ncard := Nat.card_coe_set_eq _
      _ ≤ (T \ {1}).ncard := Set.ncard_le_ncard horby (Set.toFinite _)
      _ < T.ncard := hT1
      _ = Nat.card T := (Nat.card_coe_set_eq T).symm
  -- flip via orbit-stabilizer
  have hox := card_conjOrbit_mul_card_centralizer x
  have hoy := card_conjOrbit_mul_card_centralizer ⁅k, x⁆
  by_contra hcon
  have hcon' : Nat.card (Subgroup.centralizer ({⁅k, x⁆} : Set G)) ≤
      Nat.card (Subgroup.centralizer ({x} : Set G)) := Nat.le_of_not_lt hcon
  have hpos : 0 < Nat.card (Subgroup.centralizer ({x} : Set G)) := Nat.card_pos
  have hlt : Nat.card G < Nat.card G := by
    calc Nat.card G = Nat.card (MulAction.orbit (ConjAct G) ⁅k, x⁆) *
          Nat.card (Subgroup.centralizer ({⁅k, x⁆} : Set G)) := hoy.symm
      _ ≤ Nat.card (MulAction.orbit (ConjAct G) ⁅k, x⁆) *
          Nat.card (Subgroup.centralizer ({x} : Set G)) := Nat.mul_le_mul le_rfl hcon'
      _ < Nat.card (MulAction.orbit (ConjAct G) x) *
          Nat.card (Subgroup.centralizer ({x} : Set G)) := by
          apply mul_lt_mul_of_pos_right _ hpos
          rw [hcard_x]
          exact hcard_y_lt
      _ = Nat.card G := hox
  exact lt_irrefl _ hlt

/-- **Isaacs Lemma 4.17.** Let `K ⊴ G` be abelian (`G` finite), `x ∉ Z(G)` and `k ∈ K`.
Then `|C_G(x)| < |C_G(⁅k, x⁆)|`: commutating with a noncentral element strictly grows
the centralizer.

If `⁅k, x⁆ = 1` this is `|C_G(x)| < |G|`. Otherwise everything happens inside
`H := K C_G(x)` (where the core case `card_centralizer_lt_of_commutator_ne_one_of_sup_eq_top`
applies): `C_H(x) = C_G(x)` since `C_G(x) ≤ H`, while `C_H(⁅k,x⁆) ≤ C_G(⁅k,x⁆)`. -/
theorem card_centralizer_lt_card_centralizer_commutator [Finite G]
    {K : Subgroup G} [K.Normal] (hK : ∀ a ∈ K, ∀ b ∈ K, a * b = b * a)
    {x : G} (hx : x ∉ Subgroup.center G) {k : G} (hk : k ∈ K) :
    Nat.card (Subgroup.centralizer ({x} : Set G)) <
      Nat.card (Subgroup.centralizer ({⁅k, x⁆} : Set G)) := by
  by_cases hy : ⁅k, x⁆ = 1
  · -- `C_G(1) = G`, and `C_G(x) < G` since `x` is not central
    rw [hy]
    have h1 : Subgroup.centralizer ({(1 : G)} : Set G) = ⊤ := by
      rw [eq_top_iff]
      intro g _
      rw [Subgroup.mem_centralizer_singleton_iff, mul_one, one_mul]
    rw [h1, Subgroup.card_top]
    have hne : Subgroup.centralizer ({x} : Set G) ≠ ⊤ := fun h =>
      hx (centralizer_singleton_eq_top_iff.mp h)
    have hidx1 : (Subgroup.centralizer ({x} : Set G)).index ≠ 1 := fun h =>
      hne (Subgroup.index_eq_one.mp h)
    have hidx0 : (Subgroup.centralizer ({x} : Set G)).index ≠ 0 :=
      Subgroup.index_ne_zero_of_finite
    have hpos : 0 < Nat.card (Subgroup.centralizer ({x} : Set G)) := Nat.card_pos
    calc Nat.card (Subgroup.centralizer ({x} : Set G))
        = Nat.card (Subgroup.centralizer ({x} : Set G)) * 1 := (mul_one _).symm
      _ < Nat.card (Subgroup.centralizer ({x} : Set G)) *
          (Subgroup.centralizer ({x} : Set G)).index :=
            mul_lt_mul_of_pos_left (by omega) hpos
      _ = Nat.card G := Subgroup.card_mul_index (Subgroup.centralizer ({x} : Set G))
  · -- localize at `H := K ⊔ C_G(x)` and apply the core case
    have hxC : x ∈ Subgroup.centralizer ({x} : Set G) :=
      Subgroup.mem_centralizer_singleton_iff.mpr rfl
    set H := K ⊔ Subgroup.centralizer ({x} : Set G) with hHdef
    have hKH : K ≤ H := le_sup_left
    have hCH : Subgroup.centralizer ({x} : Set G) ≤ H := le_sup_right
    have hxH : x ∈ H := hCH hxC
    have hkH : k ∈ H := hKH hk
    set x' : ↥H := ⟨x, hxH⟩ with hx'def
    set k' : ↥H := ⟨k, hkH⟩ with hk'def
    have hx'coe : ((x' : ↥H) : G) = x := by rw [hx'def]
    have hcoe_y : ((⁅k', x'⁆ : ↥H) : G) = ⁅k, x⁆ := by
      rw [hk'def, hx'def]
      simp [commutatorElement_def]
    -- centralizers restrict along `subgroupOf`
    have h1 : Subgroup.centralizer ({x'} : Set ↥H) =
        (Subgroup.centralizer ({x} : Set G)).subgroupOf H := by
      have := centralizer_singleton_subgroupOf H x'
      rwa [hx'coe] at this
    have h2 : Subgroup.centralizer ({⁅k', x'⁆} : Set ↥H) =
        (Subgroup.centralizer ({⁅k, x⁆} : Set G)).subgroupOf H := by
      have := centralizer_singleton_subgroupOf H ⁅k', x'⁆
      rwa [hcoe_y] at this
    -- hypotheses of the core case, inside `↥H`
    have hK' : ∀ a ∈ K.subgroupOf H, ∀ b ∈ K.subgroupOf H, a * b = b * a := by
      intro a ha b hb
      rw [Subgroup.mem_subgroupOf] at ha hb
      exact Subtype.ext (hK _ ha _ hb)
    have hk'K : k' ∈ K.subgroupOf H := by
      rw [hk'def, Subgroup.mem_subgroupOf]
      exact hk
    have hy' : ⁅k', x'⁆ ≠ 1 := by
      intro h
      apply hy
      rw [← hcoe_y, h, OneMemClass.coe_one]
    have htop' : K.subgroupOf H ⊔
        (Subgroup.centralizer ({x} : Set G)).subgroupOf H = ⊤ := by
      rw [← Subgroup.map_subtype_inj (H := H), Subgroup.map_sup,
        Subgroup.subgroupOf_map_subtype, Subgroup.subgroupOf_map_subtype,
        inf_eq_left.mpr hKH, inf_eq_left.mpr hCH, ← MonoidHom.range_eq_map,
        Subgroup.range_subtype]
    rw [← h1] at htop'
    have hcore := card_centralizer_lt_of_commutator_ne_one_of_sup_eq_top
      hK' hk'K htop' hy'
    rw [h1, h2] at hcore
    -- transfer the cardinalities back to `G`
    have hcx : Nat.card ((Subgroup.centralizer ({x} : Set G)).subgroupOf H) =
        Nat.card (Subgroup.centralizer ({x} : Set G)) :=
      Nat.card_congr (Subgroup.subgroupOfEquivOfLe hCH).toEquiv
    have hDle : Nat.card ((Subgroup.centralizer ({⁅k, x⁆} : Set G)).subgroupOf H) ≤
        Nat.card (Subgroup.centralizer ({⁅k, x⁆} : Set G)) := by
      have heq : (Subgroup.centralizer ({⁅k, x⁆} : Set G)).subgroupOf H =
          (Subgroup.centralizer ({⁅k, x⁆} : Set G) ⊓ H).subgroupOf H := by
        ext t
        simp only [Subgroup.mem_subgroupOf, Subgroup.mem_inf]
        exact ⟨fun h => ⟨h, t.2⟩, fun h => h.1⟩
      rw [heq, Nat.card_congr (Subgroup.subgroupOfEquivOfLe
        (inf_le_right (a := Subgroup.centralizer ({⁅k, x⁆} : Set G)) (b := H))).toEquiv]
      exact Subgroup.card_le_of_le inf_le_left
    omega

end

section /- 4B: Corollary 4.18 — ⁅K, M(G)⁆ ≤ Z(G) (p. 127) -/

/-- Strictly larger centralizer means strictly smaller conjugacy class. -/
theorem classCard_lt_classCard_of_card_centralizer_lt [Finite G] {a b : G}
    (h : Nat.card (Subgroup.centralizer ({a} : Set G)) <
      Nat.card (Subgroup.centralizer ({b} : Set G))) :
    classCard b < classCard a := by
  by_contra hcon
  have hcon' : classCard a ≤ classCard b := Nat.le_of_not_lt hcon
  have hpos : 0 < classCard a := classCard_pos a
  have hlt : Nat.card (Subgroup.centralizer ({a} : Set G)) * classCard a <
      Nat.card (Subgroup.centralizer ({b} : Set G)) * classCard b :=
    lt_of_lt_of_le (mul_lt_mul_of_pos_right h hpos) (Nat.mul_le_mul le_rfl hcon')
  rw [classCard_def, classCard_def, Subgroup.card_mul_index, Subgroup.card_mul_index] at hlt
  exact lt_irrefl _ hlt

/-- **Isaacs Corollary 4.18.** If `K ⊴ G` is abelian (`G` finite), then
`⁅K, M(G)⁆ ≤ Z(G)`.

For a generator `x` of `M(G)` and `k ∈ K`: if `x` is central then `⁅k, x⁆ = 1`;
otherwise Lemma 4.17 gives `classCard ⁅k,x⁆ < classCard x`, and since `classCard x`
is a lower bound for all nontrivial class sizes, `classCard ⁅k,x⁆ = 1`, i.e.
`⁅k, x⁆ ∈ Z(G)`. This extends from generators to all of `M(G)` by pushing to
`G/Z(G)`, where the condition "commutes with `K` mod `Z(G)`" defines a subgroup
(the preimage of a centralizer). -/
theorem commutator_mannSubgroup_le_center [Finite G] {K : Subgroup G} [K.Normal]
    (hK : ∀ a ∈ K, ∀ b ∈ K, a * b = b * a) :
    ⁅K, mannSubgroup G⁆ ≤ Subgroup.center G := by
  classical
  -- generators of M(G) commute with K modulo the center
  have hgen : ∀ x ∈ mannGenerators G, ∀ k ∈ K, ⁅k, x⁆ ∈ Subgroup.center G := by
    intro x hx k hk
    by_cases hxZ : x ∈ Subgroup.center G
    · have h1 : ⁅k, x⁆ = 1 :=
        commutatorElement_eq_one_iff_commute.mpr (Subgroup.mem_center_iff.mp hxZ k)
      rw [h1]
      exact (Subgroup.center G).one_mem
    · have h17 := card_centralizer_lt_card_centralizer_commutator hK hxZ hk
      have hlt : classCard ⁅k, x⁆ < classCard x :=
        classCard_lt_classCard_of_card_centralizer_lt h17
      by_contra hyZ
      have hy1 : 1 < classCard ⁅k, x⁆ := one_lt_classCard_iff.mpr hyZ
      have hle := hx ⁅k, x⁆ hy1
      omega
  -- push to G/Z(G): M(G) lands in the centralizer of the image of K
  have hM : mannSubgroup G ≤
      (Subgroup.centralizer ((K.map (QuotientGroup.mk' (Subgroup.center G)) :
        Subgroup (G ⧸ Subgroup.center G)) : Set (G ⧸ Subgroup.center G))).comap
        (QuotientGroup.mk' (Subgroup.center G)) := by
    change Subgroup.closure (mannGenerators G) ≤ _
    rw [Subgroup.closure_le]
    intro x hx
    rw [SetLike.mem_coe, Subgroup.mem_comap, Subgroup.mem_centralizer_iff]
    intro h hh
    rw [SetLike.mem_coe, Subgroup.mem_map] at hh
    obtain ⟨kk, hkk, rfl⟩ := hh
    have hcz := hgen x hx kk hkk
    have hπy : QuotientGroup.mk' (Subgroup.center G) ⁅kk, x⁆ = 1 := by
      rw [QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]
      exact hcz
    rw [map_commutatorElement] at hπy
    exact commutatorElement_eq_one_iff_commute.mp hπy
  -- conclude on elements
  rw [Subgroup.commutator_le]
  intro g₁ h₁ g₂ h₂
  have hg₂ := hM h₂
  rw [Subgroup.mem_comap, Subgroup.mem_centralizer_iff] at hg₂
  have hcomm : QuotientGroup.mk' (Subgroup.center G) g₁ *
        QuotientGroup.mk' (Subgroup.center G) g₂ =
      QuotientGroup.mk' (Subgroup.center G) g₂ *
        QuotientGroup.mk' (Subgroup.center G) g₁ :=
    hg₂ _ (Subgroup.mem_map_of_mem _ h₁)
  have h1 : QuotientGroup.mk' (Subgroup.center G) ⁅g₁, g₂⁆ = 1 := by
    rw [map_commutatorElement]
    exact commutatorElement_eq_one_iff_commute.mpr hcomm
  rwa [QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff] at h1

end

section /- 4B: Theorem 4.15 — self-centralizing normal K forces class(M(G)) ≤ 3 (p. 128) -/

/-- From ambient `S.lowerCentralSeries n = ⊥`, the subgroup `S` is nilpotent of class at
most `n` as a group in its own right. -/
theorem nilpotencyClass_le_of_lowerCentralSeries_eq_bot {S : Subgroup G} {n : ℕ}
    (h : S.lowerCentralSeries n = ⊥) : Group.nilpotencyClass ↥S ≤ n := by
  haveI : Group.IsNilpotent ↥S := Subgroup.isNilpotent_of_lowerCentralSeries_eq_bot h
  rw [← Subgroup.lowerCentralSeries_eq_bot_iff_nilpotencyClass_le,
    ← Subgroup.map_subtype_inj (H := S), Subgroup.map_bot,
    Subgroup.top_subtype_lowerCentralSeries]
  exact h

/-- **Isaacs Theorem 4.15** (γ₄-form). If `K ⊴ G` is self-centralizing (`C_G(K) = K`,
`G` finite), then `⁅⁅⁅M, M⁆, M⁆, M⁆ = 1` for `M := M(G)`, i.e. `M(G)` is nilpotent of
class at most `3`.

Note `C_G(K) = K` forces `K` abelian. By Corollary 4.18, `⁅K, M⁆ ≤ Z(G)`, hence
`⁅⁅K, M⁆, M⁆ = 1 = ⁅⁅M, K⁆, M⁆`; the three subgroups lemma gives `⁅⁅M, M⁆, K⁆ = 1`,
i.e. `M' ≤ C_G(K) = K`, and then `γ₄(M) = ⁅⁅M', M⁆, M⁆ ≤ ⁅⁅K, M⁆, M⁆ = 1`. -/
theorem commutator_mannSubgroup_four_eq_bot_of_centralizer_eq_self [Finite G]
    {K : Subgroup G} [K.Normal] (hself : Subgroup.centralizer (K : Set G) = K) :
    ⁅⁅⁅mannSubgroup G, mannSubgroup G⁆, mannSubgroup G⁆, mannSubgroup G⁆ = ⊥ := by
  -- `K` is abelian
  have hK : ∀ a ∈ K, ∀ b ∈ K, a * b = b * a := by
    intro a ha b hb
    rw [← hself] at hb
    exact Subgroup.mem_centralizer_iff.mp hb a ha
  have h18 : ⁅K, mannSubgroup G⁆ ≤ Subgroup.center G :=
    commutator_mannSubgroup_le_center hK
  have hKMM : ⁅⁅K, mannSubgroup G⁆, mannSubgroup G⁆ = ⊥ := by
    rw [Subgroup.commutator_eq_bot_iff_le_centralizer]
    exact h18.trans (Subgroup.center_le_centralizer _)
  have hMKM : ⁅⁅mannSubgroup G, K⁆, mannSubgroup G⁆ = ⊥ := by
    rw [Subgroup.commutator_comm (mannSubgroup G) K]
    exact hKMM
  have h3 : ⁅⁅mannSubgroup G, mannSubgroup G⁆, K⁆ = ⊥ :=
    Subgroup.commutator_commutator_eq_bot_of_rotate hMKM hKMM
  have hMM_le : ⁅mannSubgroup G, mannSubgroup G⁆ ≤ K := by
    rw [← hself]
    exact Subgroup.commutator_eq_bot_iff_le_centralizer.mp h3
  rw [← le_bot_iff, ← hKMM]
  exact Subgroup.commutator_mono (Subgroup.commutator_mono hMM_le le_rfl) le_rfl

/-- **Isaacs Theorem 4.15** (lower-central-series form): `γ₄(M(G)) = 1` as
`(mannSubgroup G).lowerCentralSeries 3 = ⊥`. -/
theorem lowerCentralSeries_mannSubgroup_eq_bot_of_centralizer_eq_self [Finite G]
    {K : Subgroup G} [K.Normal] (hself : Subgroup.centralizer (K : Set G) = K) :
    (mannSubgroup G).lowerCentralSeries 3 = ⊥ :=
  commutator_mannSubgroup_four_eq_bot_of_centralizer_eq_self hself

/-- **Isaacs Theorem 4.15** (nilpotency form): `M(G)` is nilpotent. -/
theorem isNilpotent_mannSubgroup_of_centralizer_eq_self [Finite G]
    {K : Subgroup G} [K.Normal] (hself : Subgroup.centralizer (K : Set G) = K) :
    Group.IsNilpotent ↥(mannSubgroup G) :=
  Subgroup.isNilpotent_of_lowerCentralSeries_eq_bot
    (lowerCentralSeries_mannSubgroup_eq_bot_of_centralizer_eq_self hself)

/-- **Isaacs Theorem 4.15** (nilpotency class form): `class(M(G)) ≤ 3`. -/
theorem nilpotencyClass_mannSubgroup_le_of_centralizer_eq_self [Finite G]
    {K : Subgroup G} [K.Normal] (hself : Subgroup.centralizer (K : Set G) = K) :
    Group.nilpotencyClass ↥(mannSubgroup G) ≤ 3 :=
  nilpotencyClass_le_of_lowerCentralSeries_eq_bot
    (lowerCentralSeries_mannSubgroup_eq_bot_of_centralizer_eq_self hself)

end

section /- 4B: Lemma 4.16 — maximal abelian normal subgroups of nilpotent groups (p. 126) -/

/-- A nontrivial normal subgroup of a nilpotent group meets the center nontrivially.
Nilpotent analogue of the `p`-group fact
`OddOrder.GroupTheory.CriticalSubgroup.exists_mem_center_of_normal_ne_bot`;
no finiteness is required.

Proof: the iterated commutators `⁅…⁅N, G⁆, …, G⁆` descend inside the lower central
series of `G`, hence eventually vanish; the last nonvanishing term `W` satisfies
`⁅W, G⁆ = 1`, so `⊥ ≠ W ≤ N ∩ Z(G)`. -/
theorem exists_mem_center_of_normal_ne_bot_of_isNilpotent [Group.IsNilpotent G]
    {N : Subgroup G} [N.Normal] (hN : N ≠ ⊥) :
    ∃ x : G, x ∈ N ∧ x ∈ Subgroup.center G ∧ x ≠ 1 := by
  classical
  obtain ⟨m, hm⟩ := Subgroup.nilpotent_iff_lowerCentralSeries.mp ‹_›
  have hbot : iterCommutator N ⊤ m = ⊥ := by
    rw [← le_bot_iff, ← hm]
    exact iterCommutator_le_lowerCentralSeries N ⊤ m
  have hex : ∃ n, iterCommutator N ⊤ n = ⊥ := ⟨m, hbot⟩
  have hn_bot : iterCommutator N ⊤ (Nat.find hex) = ⊥ := Nat.find_spec hex
  have hn_pos : 0 < Nat.find hex := by
    rcases Nat.eq_zero_or_pos (Nat.find hex) with h0 | hpos
    · exfalso
      apply hN
      rw [h0, iterCommutator_zero] at hn_bot
      exact hn_bot
    · exact hpos
  have hW_ne : iterCommutator N ⊤ (Nat.find hex - 1) ≠ ⊥ :=
    Nat.find_min hex (by omega)
  have hW_comm : ⁅iterCommutator N ⊤ (Nat.find hex - 1), (⊤ : Subgroup G)⁆ = ⊥ := by
    rw [← iterCommutator_succ, show Nat.find hex - 1 + 1 = Nat.find hex from by omega]
    exact hn_bot
  have hW_center : iterCommutator N ⊤ (Nat.find hex - 1) ≤ Subgroup.center G := by
    have h := Subgroup.commutator_eq_bot_iff_le_centralizer.mp hW_comm
    rwa [Subgroup.coe_top, Subgroup.centralizer_univ] at h
  have hW_le_N : iterCommutator N ⊤ (Nat.find hex - 1) ≤ N := by
    have hall : ∀ i, iterCommutator N ⊤ i ≤ N := by
      intro i
      induction i with
      | zero => rw [iterCommutator_zero]
      | succ j ih =>
        rw [iterCommutator_succ]
        calc ⁅iterCommutator N ⊤ j, (⊤ : Subgroup G)⁆ ≤ ⁅N, (⊤ : Subgroup G)⁆ :=
            Subgroup.commutator_mono ih le_rfl
          _ ≤ N := Subgroup.commutator_le_left N ⊤
    exact hall _
  obtain ⟨w, hwW, hw1⟩ : ∃ w ∈ iterCommutator N ⊤ (Nat.find hex - 1), w ≠ (1 : G) := by
    by_contra hcon
    push Not at hcon
    apply hW_ne
    rw [eq_bot_iff]
    intro w hw
    rw [Subgroup.mem_bot]
    exact hcon w hw
  exact ⟨w, hW_le_N hwW, hW_center hwW, hw1⟩

/-- **Isaacs Lemma 4.16** (nilpotent generalization). In a nilpotent group `G`
(finiteness not needed), a normal subgroup `A` maximal among abelian normal subgroups
is self-centralizing: `C_G(A) = A`.

Generalizes the `p`-group case
`OddOrder.GroupTheory.CriticalSubgroup.centralizer_eq_self_of_maximal_abelian_normal`
(Gorenstein 5.3.12), whose proof is mirrored: if `A < C := C_G(A)`, pick a nonidentity
central element `x̄` of the nontrivial normal subgroup `C/A ⊴ G/A` (using
`exists_mem_center_of_normal_ne_bot_of_isNilpotent` on the nilpotent quotient `G/A`);
the preimage `X` of `⟨x̄⟩` is normal in `G`, abelian (cyclic over the central kernel
`A ≤ Z(X)`), and strictly contains `A` — contradicting maximality. -/
theorem centralizer_eq_self_of_maximal_abelian_normal_of_isNilpotent
    [Group.IsNilpotent G] {A : Subgroup G} [A.Normal]
    (hA_comm : ∀ x ∈ A, ∀ y ∈ A, x * y = y * x)
    (hA_max : ∀ B : Subgroup G, B.Normal → (∀ x ∈ B, ∀ y ∈ B, x * y = y * x) →
      A ≤ B → B = A) :
    Subgroup.centralizer (A : Set G) = A := by
  have hA_le : A ≤ Subgroup.centralizer (A : Set G) := by
    intro m hm
    rw [Subgroup.mem_centralizer_iff]
    intro h hh
    exact hA_comm h hh m hm
  refine le_antisymm ?_ hA_le
  by_contra hnot
  set H := Subgroup.centralizer (A : Set G) with hH_def
  have hAH : A < H := lt_of_le_of_ne hA_le fun h => hnot (h ▸ le_refl _)
  haveI : H.Normal := inferInstance
  set q := QuotientGroup.mk' A with hq_def
  set Hbar := H.map q with hHbar_def
  haveI : Hbar.Normal := Subgroup.Normal.map inferInstance q (QuotientGroup.mk'_surjective A)
  -- `H̄ ≠ ⊥`: pick `h ∈ H \ A`
  have hHbar_ne : Hbar ≠ ⊥ := by
    obtain ⟨h, hhH, hhA⟩ := SetLike.exists_of_lt hAH
    intro hbot
    apply hhA
    have hmem : q h ∈ Hbar := Subgroup.mem_map_of_mem q hhH
    rw [hbot, Subgroup.mem_bot] at hmem
    exact (QuotientGroup.eq_one_iff h).mp hmem
  -- a nonidentity central element of the nilpotent quotient `G/A`
  obtain ⟨xbar, hxbar_H, hxbar_center, hxbar_ne⟩ :=
    exists_mem_center_of_normal_ne_bot_of_isNilpotent hHbar_ne
  -- the preimage `X` of `⟨x̄⟩` is normal in `G` and contains `A`
  have hzp_le_center : Subgroup.zpowers xbar ≤ Subgroup.center (G ⧸ A) :=
    Subgroup.zpowers_le.mpr hxbar_center
  haveI hzp_normal : (Subgroup.zpowers xbar).Normal :=
    { conj_mem := fun n hn g => by
        rw [Subgroup.mem_center_iff.mp (hzp_le_center hn) g, mul_assoc,
          mul_inv_cancel, mul_one]
        exact hn }
  set X := (Subgroup.zpowers xbar).comap q with hX_def
  haveI : X.Normal := inferInstance
  have hAX : A ≤ X := by
    intro m hm
    rw [hX_def, Subgroup.mem_comap, hq_def, QuotientGroup.mk'_apply,
      (QuotientGroup.eq_one_iff m).mpr hm]
    exact one_mem _
  -- `X ≤ H = C_G(A)`
  have hXH : X ≤ H := by
    have h1 : X ≤ Hbar.comap q :=
      Subgroup.comap_mono (Subgroup.zpowers_le.mpr hxbar_H)
    have h2 : Hbar.comap q = A ⊔ H := by
      rw [hHbar_def, hq_def, QuotientGroup.comap_map_mk']
    rw [h2, sup_eq_right.mpr hAH.le] at h1
    exact h1
  -- `f : ↥X →* ⟨x̄⟩`, the quotient map restricted to `X`
  have hf_mem : ∀ g : X, q (g : G) ∈ Subgroup.zpowers xbar := fun g => g.2
  set f : X →* Subgroup.zpowers xbar :=
    (q.comp X.subtype).codRestrict (Subgroup.zpowers xbar) hf_mem with hf_def
  -- `ker f ≤ Z(X)`: `f g = 1 ⟹ g ∈ A`, and `X ≤ H` centralizes `A`
  have hker : f.ker ≤ Subgroup.center X := by
    intro g hg
    rw [MonoidHom.mem_ker, hf_def] at hg
    have hgA : (g : G) ∈ A := by
      have hq1 : q (g : G) = 1 := by
        have := congrArg Subtype.val hg
        simpa [MonoidHom.codRestrict_apply] using this
      exact (QuotientGroup.eq_one_iff (g : G)).mp hq1
    rw [Subgroup.mem_center_iff]
    intro h
    apply Subtype.ext
    have hhH : (h : G) ∈ Subgroup.centralizer (A : Set G) := hXH h.2
    have hcomm := Subgroup.mem_centralizer_iff.mp hhH (g : G) hgA
    simpa using hcomm.symm
  -- `X` is abelian (cyclic quotient over a central kernel)
  have hX_comm : ∀ x ∈ X, ∀ y ∈ X, x * y = y * x := by
    intro x hx y hy
    have := (f.isMulCommutative_of_isCyclic_of_ker_le_center hker).is_comm.comm ⟨x, hx⟩ ⟨y, hy⟩
    exact congrArg Subtype.val this
  -- maximality is contradicted: `X = A` but `x ∈ X \ A`
  obtain ⟨x, hx_eq⟩ := QuotientGroup.mk'_surjective A xbar
  have hxX : x ∈ X := by
    rw [hX_def, Subgroup.mem_comap, hq_def, hx_eq]
    exact Subgroup.mem_zpowers xbar
  have hxA : x ∉ A := by
    intro hmem
    apply hxbar_ne
    rw [← hx_eq, QuotientGroup.mk'_apply]
    exact (QuotientGroup.eq_one_iff x).mpr hmem
  have hXeqA : X = A := hA_max X inferInstance hX_comm hAX
  exact hxA (hXeqA ▸ hxX)

/-- **Isaacs Lemma 4.16, existence form.** A finite nilpotent group has an abelian
normal subgroup that is self-centralizing (any maximal abelian normal subgroup works). -/
theorem exists_normal_abelian_centralizer_eq_self (G : Type*) [Group G] [Finite G]
    [Group.IsNilpotent G] :
    ∃ K : Subgroup G, K.Normal ∧ (∀ x ∈ K, ∀ y ∈ K, x * y = y * x) ∧
      Subgroup.centralizer (K : Set G) = K := by
  classical
  haveI : Finite (Subgroup G) :=
    Finite.of_injective (fun H : Subgroup G => (H : Set G)) SetLike.coe_injective
  have hfin : {B : Subgroup G | B.Normal ∧ ∀ x ∈ B, ∀ y ∈ B, x * y = y * x}.Finite :=
    Set.toFinite _
  obtain ⟨A, hAs, hAmax⟩ := hfin.exists_maximalFor (fun B : Subgroup G => Nat.card B) _
    ⟨⊥, inferInstance, by simp⟩
  obtain ⟨hAnormal, hAcomm⟩ := hAs
  haveI := hAnormal
  refine ⟨A, hAnormal, hAcomm, ?_⟩
  apply centralizer_eq_self_of_maximal_abelian_normal_of_isNilpotent hAcomm
  intro B hBn hBcomm hAB
  have hcard : Nat.card B ≤ Nat.card A :=
    hAmax ⟨hBn, hBcomm⟩ (Subgroup.card_le_of_le hAB)
  have hsub : (A : Set G) = (B : Set G) := by
    apply Set.eq_of_subset_of_ncard_le (SetLike.coe_subset_coe.mpr hAB) ?_ (Set.toFinite _)
    rw [← Nat.card_coe_set_eq, ← Nat.card_coe_set_eq]
    exact hcard
  exact SetLike.coe_injective hsub.symm

end

section /- 4B: Theorem 4.14 — Mann: class(M(G)) ≤ 3 for nilpotent G (p. 126) -/

/-- **Isaacs Theorem 4.14 (Mann)**, lower-central-series form. If `G` is finite and
nilpotent then `M(G)` has nilpotence class at most `3`: `γ₄(M(G)) = 1`.

Combine Lemma 4.16 (a maximal abelian normal subgroup `K` is self-centralizing) with
Theorem 4.15. -/
theorem lowerCentralSeries_mannSubgroup_eq_bot_of_isNilpotent (G : Type*) [Group G]
    [Finite G] [Group.IsNilpotent G] :
    (mannSubgroup G).lowerCentralSeries 3 = ⊥ := by
  obtain ⟨K, hKn, _, hself⟩ := exists_normal_abelian_centralizer_eq_self G
  haveI := hKn
  exact lowerCentralSeries_mannSubgroup_eq_bot_of_centralizer_eq_self hself

/-- **Isaacs Theorem 4.14 (Mann)**, nilpotency form: for finite nilpotent `G`,
`M(G)` is nilpotent (indeed of class ≤ 3, see
`nilpotencyClass_mannSubgroup_le_of_isNilpotent`). -/
theorem isNilpotent_mannSubgroup (G : Type*) [Group G] [Finite G] [Group.IsNilpotent G] :
    Group.IsNilpotent ↥(mannSubgroup G) :=
  Subgroup.isNilpotent_of_lowerCentralSeries_eq_bot
    (lowerCentralSeries_mannSubgroup_eq_bot_of_isNilpotent G)

/-- **Isaacs Theorem 4.14 (Mann)**, nilpotency class form: `class(M(G)) ≤ 3` for finite
nilpotent `G`. -/
theorem nilpotencyClass_mannSubgroup_le_of_isNilpotent (G : Type*) [Group G] [Finite G]
    [Group.IsNilpotent G] :
    Group.nilpotencyClass ↥(mannSubgroup G) ≤ 3 :=
  nilpotencyClass_le_of_lowerCentralSeries_eq_bot
    (lowerCentralSeries_mannSubgroup_eq_bot_of_isNilpotent G)

end

section /- 4B: Theorem 4.19 — Mann: class(F(M(G))) ≤ 4 for arbitrary finite G (p. 128) -/

/-- **Isaacs Theorem 4.11** for the lower central series of a subgroup `S ≤ G`, computed
in the ambient group: `⁅γᵢ(S), γⱼ(S)⁆ ≤ γ_{i+j}(S)` (in mathlib indexing
`S.lowerCentralSeries n = γ_{n+1}(S)`, so the exponent is `i + j + 1`). Generalizes
`commutator_lowerCentralSeries_le` (the case `S = ⊤`) by transporting along
`S.subtype`. -/
theorem commutator_lowerCentralSeries_le_subgroup (S : Subgroup G) (i j : ℕ) :
    ⁅S.lowerCentralSeries i, S.lowerCentralSeries j⁆ ≤
      S.lowerCentralSeries (i + j + 1) := by
  have h := commutator_lowerCentralSeries_le (G := ↥S) i j
  have h2 := Subgroup.map_mono (f := S.subtype) h
  rwa [Subgroup.map_commutator, Subgroup.top_subtype_lowerCentralSeries,
    Subgroup.top_subtype_lowerCentralSeries, Subgroup.top_subtype_lowerCentralSeries] at h2

/-- **Isaacs Theorem 4.19 (Mann)**, lower-central-series form. For an arbitrary finite
group `G`, the Fitting subgroup `F := F(M(G))` of the Mann subgroup (viewed in `G` via
`Subgroup.map (mannSubgroup G).subtype`) has nilpotence class at most `4`:
`γ₅(F) = 1`.

Proof (p. 128): let `n` be least with `γ_{n+1}(F) = 1` and suppose `n ≥ 5`. By
Theorem 4.11, `⁅γ_{n-2}(F), γ_{n-2}(F)⁆ ≤ γ_{2n-4}(F) = 1` (as `2n - 4 > n`), so
`K := γ_{n-2}(F)` is abelian; it is normal in `G` since `F ⊴ G` (`F` is characteristic
in `M(G) ⊴ G`). Corollary 4.18 gives `⁅K, M(G)⁆ ≤ Z(G)`, hence
`γ_{n-1}(F) = ⁅K, F⁆ ≤ Z(G)` and `γ_n(F) = ⁅γ_{n-1}(F), F⁆ = 1`, contradicting
minimality. -/
theorem lowerCentralSeries_map_fitting_mannSubgroup_eq_bot (G : Type*) [Group G]
    [Finite G] :
    ((OddOrder.Isaacs.Ch01.fitting ↥(mannSubgroup G)).map
      (mannSubgroup G).subtype).lowerCentralSeries 4 = ⊥ := by
  classical
  -- `F ⊴ G`: characteristic in `M(G) ⊴ G`
  haveI hFnormal : ((OddOrder.Isaacs.Ch01.fitting ↥(mannSubgroup G)).map
      (mannSubgroup G).subtype).Normal := inferInstance
  haveI : Group.IsNilpotent ↥(OddOrder.Isaacs.Ch01.fitting ↥(mannSubgroup G)) :=
    OddOrder.Isaacs.Ch01.fitting.isNilpotent
  haveI hFnilp : Group.IsNilpotent ↥((OddOrder.Isaacs.Ch01.fitting ↥(mannSubgroup G)).map
      (mannSubgroup G).subtype) :=
    Group.nilpotent_of_mulEquiv (Subgroup.equivMapOfInjective _ _
      (mannSubgroup G).subtype_injective)
  set F := (OddOrder.Isaacs.Ch01.fitting ↥(mannSubgroup G)).map
    (mannSubgroup G).subtype with hFdef
  have hFM : F ≤ mannSubgroup G := Subgroup.map_subtype_le _
  obtain ⟨n0, hn0⟩ := (Subgroup.isNilpotent_iff_lowerCentralSeries F).mp hFnilp
  have hex : ∃ n, F.lowerCentralSeries n = ⊥ := ⟨n0, hn0⟩
  have hn_bot : F.lowerCentralSeries (Nat.find hex) = ⊥ := Nat.find_spec hex
  rcases Nat.lt_or_ge 4 (Nat.find hex) with hgt | hle
  swap
  · exact le_bot_iff.mp (hn_bot ▸ F.lowerCentralSeries_antitone hle)
  · exfalso
    obtain ⟨m, hm5⟩ : ∃ m, Nat.find hex = m + 5 := ⟨Nat.find hex - 5, by omega⟩
    rw [hm5] at hn_bot
    -- `K := γ_{m+3}(F) = F.lowerCentralSeries (m+2)` is abelian by Thm 4.11
    have hKcomm : ∀ a ∈ F.lowerCentralSeries (m + 2), ∀ b ∈ F.lowerCentralSeries (m + 2),
        a * b = b * a := by
      have hcomm_le : ⁅F.lowerCentralSeries (m + 2), F.lowerCentralSeries (m + 2)⁆ ≤
          F.lowerCentralSeries (m + 5) :=
        (commutator_lowerCentralSeries_le_subgroup F (m + 2) (m + 2)).trans
          (F.lowerCentralSeries_antitone (by omega))
      have hbot : ⁅F.lowerCentralSeries (m + 2), F.lowerCentralSeries (m + 2)⁆ = ⊥ :=
        le_bot_iff.mp (hcomm_le.trans hn_bot.le)
      intro a ha b hb
      have hmem := Subgroup.commutator_eq_bot_iff_le_centralizer.mp hbot ha
      exact (Subgroup.mem_centralizer_iff.mp hmem b hb).symm
    -- `K ⊴ G`, so Corollary 4.18 applies
    haveI : (F.lowerCentralSeries (m + 2)).Normal := inferInstance
    have h18 : ⁅F.lowerCentralSeries (m + 2), mannSubgroup G⁆ ≤ Subgroup.center G :=
      commutator_mannSubgroup_le_center hKcomm
    -- `γ_{n-1}(F) ≤ Z(G)`, hence `γ_n(F) = 1`: contradiction with minimality of `n`
    have h33 : F.lowerCentralSeries (m + 3) ≤ Subgroup.center G := by
      have heq : F.lowerCentralSeries (m + 3) =
          ⁅F.lowerCentralSeries (m + 2), F⁆ :=
        F.lowerCentralSeries_succ (m + 2)
      rw [heq]
      exact (Subgroup.commutator_mono le_rfl hFM).trans h18
    have h44 : F.lowerCentralSeries (m + 4) = ⊥ :=
      F.lowerCentralSeries_succ_eq_bot h33
    exact Nat.find_min hex (by omega) h44

/-- **Isaacs Theorem 4.19 (Mann)**, nilpotency class form: for arbitrary finite `G`,
`class(F(M(G))) ≤ 4`. -/
theorem nilpotencyClass_map_fitting_mannSubgroup_le (G : Type*) [Group G] [Finite G] :
    Group.nilpotencyClass
      ↥((OddOrder.Isaacs.Ch01.fitting ↥(mannSubgroup G)).map
        (mannSubgroup G).subtype) ≤ 4 :=
  nilpotencyClass_le_of_lowerCentralSeries_eq_bot
    (lowerCentralSeries_map_fitting_mannSubgroup_eq_bot G)

end

end OddOrder.Isaacs.Ch04
