/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.Algebra.Algebra.Subalgebra.Basic
import Mathlib.RingTheory.Artinian.Ring
import OddOrder.Algebra.DefectGroupConjugacy
import OddOrder.Algebra.GroupAlgebraConjugation
import OddOrder.Algebra.Rosenberg

/-!
# Defect groups in the group algebra

The relative-trace theory of `RelativeTrace`, `DefectGroup` and `DefectGroupConjugacy` is stated
for an arbitrary `G`-algebra.  Here it is specialised to the case it was built for: `A = k[G]`
with `G` acting by conjugation, where `A^G = Z(k[G])` and the `G`-fixed idempotents are the block
idempotents.

Three hypotheses of the general theory are discharged:

* `A^G` is commutative — the `G`-fixed points are central (`forall_smul_eq_iff_mem_center`);
* the indices prime to `p` are invertible by a `G`-fixed element when `k` has characteristic `p`
  — take the scalar `(n : k)⁻¹`;
* the corner of a *primitive* central idempotent is local — `Z(k[G])` is a finite-dimensional
  commutative algebra, hence Artinian, so Fitting's dichotomy `isNilpotent_or_exists_mul_eq`
  applies inside it.

What comes out is Brauer's theorem in its usual form: the defect groups of a block are
`p`-groups and form a single `G`-conjugacy class.

## Main results

* `OddOrder.GroupAlgebra.commute_of_forall_smul_eq`
* `OddOrder.GroupAlgebra.exists_fixed_nsmul_one_inv`
* `OddOrder.GroupAlgebra.isPGroup_of_isDefectGroup`
* `OddOrder.GroupAlgebra.isNilpotent_or_exists_fixed_mul_eq` — Fitting's dichotomy in `Z(k[G])`.
* `OddOrder.GroupAlgebra.exists_conj_eq_of_isDefectGroup` — the defect groups of a primitive
  central idempotent form one conjugacy class.
-/

namespace OddOrder.GroupAlgebra

open MonoidAlgebra OddOrder.GAlgebra

open scoped OddOrder.Conjugation Pointwise

section CommRing

variable {k : Type*} [CommRing k] {G : Type*} [Group G]

/-- **Two `G`-fixed elements of `k[G]` commute**, because a `G`-fixed element is central.  This
is the commutativity of `A^G = Z(k[G])`. -/
theorem commute_of_forall_smul_eq {x y : MonoidAlgebra k G} (hx : ∀ g : G, g • x = x) :
    Commute x y := forall_smul_eq_iff_mem_center.mp hx y

/-- The `G`-fixed points of `k[G]` are exactly the centre, as a subalgebra. -/
theorem mem_center_iff_forall_smul_eq {x : MonoidAlgebra k G} :
    x ∈ Subalgebra.center k (MonoidAlgebra k G) ↔ ∀ g : G, g • x = x := by
  rw [Subalgebra.mem_center_iff]
  exact ⟨fun h => forall_smul_eq_iff_mem_center.mpr fun y => (h y).symm,
    fun h y => (forall_smul_eq_iff_mem_center.mp h y).symm⟩

end CommRing

section Field

variable {k : Type*} [Field k] {G : Type*} [Group G]

/-- **The invertible-index hypothesis for `k[G]`.**  If `k` has characteristic `p` and `p ∤ n`
then `n • 1` has a `G`-fixed inverse, namely the scalar `(n : k)⁻¹`.  This is what lets a defect
group be shrunk into a Sylow `p`-subgroup. -/
theorem exists_fixed_nsmul_one_inv {p : ℕ} [CharP k p] {n : ℕ} (hn : ¬ p ∣ n) :
    ∃ v : MonoidAlgebra k G, (∀ g : G, g • v = v) ∧
      (n • (1 : MonoidAlgebra k G)) * v = 1 := by
  have hne : (n : k) ≠ 0 := fun h => hn ((CharP.cast_eq_zero_iff k p n).mp h)
  refine ⟨single 1 ((n : k)⁻¹), fun g => by simp, ?_⟩
  have hone : (n • (1 : MonoidAlgebra k G)) = single 1 (n : k) := by
    rw [← Nat.cast_smul_eq_nsmul k n (1 : MonoidAlgebra k G), MonoidAlgebra.one_def,
      MonoidAlgebra.smul_single, smul_eq_mul, mul_one]
  rw [hone, single_mul_single, mul_one, mul_inv_cancel₀ hne, ← MonoidAlgebra.one_def]

variable [Finite G]

/-- **The defect groups of a central element of `k[G]` are `p`-groups** when `k` has
characteristic `p`.  This is `GAlgebra.isPGroup_of_isDefectGroup` with the index inverses
supplied by `exists_fixed_nsmul_one_inv`. -/
theorem isPGroup_of_isDefectGroup {p : ℕ} [CharP k p] (hp : p.Prime)
    {b : MonoidAlgebra k G} {D : Subgroup G} (hD : IsDefectGroup b D) : IsPGroup p ↥D :=
  GAlgebra.isPGroup_of_isDefectGroup hp (fun _ hn => exists_fixed_nsmul_one_inv hn) hD

/-- **Fitting's dichotomy in `Z(k[G])`.**  Let `b` be a *primitive* idempotent of the centre: the
only central idempotents `u` with `b u = u` are `0` and `b`.  Then for every central `x` the
element `b x` is nilpotent or invertible in the corner `b Z(k[G])`.

The point is that `Z(k[G])` is a finite-dimensional commutative `k`-algebra, hence Artinian, so
the chain of principal ideals generated by the powers of `b x` stabilises and
`isNilpotent_or_exists_mul_eq_of_isArtinian` applies. -/
theorem isNilpotent_or_exists_fixed_mul_eq {b : MonoidAlgebra k G} (hbfix : ∀ g : G, g • b = b)
    (hb : IsIdempotentElem b)
    (hprim : ∀ u : MonoidAlgebra k G, (∀ g : G, g • u = u) → IsIdempotentElem u → b * u = u →
      u = 0 ∨ u = b)
    {x : MonoidAlgebra k G} (hx : ∀ g : G, g • x = x) :
    IsNilpotent (b * x) ∨
      ∃ u : MonoidAlgebra k G, (∀ g : G, g • u = u) ∧ u * (b * x) = b := by
  set Z := Subalgebra.center k (MonoidAlgebra k G) with hZ
  haveI : Module.Finite k ↥Z :=
    Module.Finite.of_injective Z.toSubmodule.subtype Subtype.val_injective
  haveI : IsArtinianRing ↥Z := IsArtinianRing.of_finite k _
  set b' : ↥Z := ⟨b, mem_center_iff_forall_smul_eq.mpr hbfix⟩ with hb'def
  set x' : ↥Z := ⟨x, mem_center_iff_forall_smul_eq.mpr hx⟩ with hx'def
  have hb' : IsIdempotentElem b' := Subtype.ext hb
  have hprim' : ∀ u : ↥Z, IsIdempotentElem u → b' * u = u → u = 0 ∨ u = b' := by
    intro u hu hbu
    rcases hprim u (mem_center_iff_forall_smul_eq.mp u.2) (Subtype.ext_iff.mp hu)
      (Subtype.ext_iff.mp hbu) with h | h
    · exact Or.inl (Subtype.ext h)
    · exact Or.inr (Subtype.ext h)
  rcases isNilpotent_or_exists_mul_eq_of_isArtinian hb' hprim' x' with h | ⟨u, hu⟩
  · exact Or.inl (by simpa using h.map Z.val)
  · exact Or.inr ⟨(u : MonoidAlgebra k G), mem_center_iff_forall_smul_eq.mp u.2,
      by simpa using congrArg (Z.val ·) hu⟩

/-- **Brauer's theorem on defect groups.**  The defect groups of a nonzero primitive idempotent
of `Z(k[G])` — in particular of a block idempotent — form a single `G`-conjugacy class. -/
theorem exists_conj_eq_of_isDefectGroup {b : MonoidAlgebra k G} (hbfix : ∀ g : G, g • b = b)
    (hb : IsIdempotentElem b) (hb0 : b ≠ 0)
    (hprim : ∀ u : MonoidAlgebra k G, (∀ g : G, g • u = u) → IsIdempotentElem u → b * u = u →
      u = 0 ∨ u = b)
    {D D' : Subgroup G} (hD : IsDefectGroup b D) (hD' : IsDefectGroup b D') :
    ∃ g : G, D = MulAut.conj g • D' :=
  GAlgebra.exists_conj_eq_of_isDefectGroup_of_commute hbfix hb hb0
    (fun _ _ hx _ => commute_of_forall_smul_eq hx)
    (fun _ hx => isNilpotent_or_exists_fixed_mul_eq hbfix hb hprim hx) hD hD'

end Field

end OddOrder.GroupAlgebra
