/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.Analysis.Complex.Polynomial.Basic
import Mathlib.FieldTheory.IsAlgClosed.Basic
import OddOrder.Algebra.AlgInt

/-!
# Roots of unity summing to their count, over an arbitrary field

Over `ℂ` the statement "`n` numbers of modulus `1` summing to `n` are all `1`" is the equality
case of the triangle inequality
(`OddOrder.RepresentationTheory.all_eq_one_of_norm_eq_one_of_sum_eq_card`).  Modular
representation theory needs it over the abstract coefficient field of a `p`-modular system, where
there is no absolute value: Navarro (6.11) says that a Brauer character with `φ(g) = φ(1)` at a
`p`-regular `g` has `g` in its kernel, and the eigenvalue lifts `ε_i` live in `𝒪`, not in `ℂ`.

The transfer is purely algebraic.  The `ε_i` are roots of `X^m - 1`, hence integral over `ℚ`, so
they generate a subalgebra `A ⊆ K` that is integral over `ℚ`; a domain integral over a field is a
field, and an algebraic extension of `ℚ` embeds into the algebraically closed `ℂ`
(`IsAlgClosed.lift`).  Transporting the hypothesis along that embedding puts us back over `ℂ`,
and the conclusion comes back because a ring homomorphism out of a field is injective.

No archimedean property of `K` is used or needed — only that `ℂ` is an algebraically closed field
of characteristic zero in which the statement is already known.

## Main results

* `OddOrder.Algebra.eq_one_of_pow_eq_one_of_sum_eq_card`
-/

namespace OddOrder.Algebra

open Polynomial

variable {K : Type*} [Field K] [CharZero K]

/-- **Roots of unity summing to their count are all `1`**, over any field of characteristic zero.

This is the equality case of the triangle inequality, transported from `ℂ` along an embedding of
the (algebraic) subalgebra generated by the roots. -/
theorem eq_one_of_pow_eq_one_of_sum_eq_card {ι : Type*} [Fintype ι] {m : ℕ} (hm : m ≠ 0)
    {ε : ι → K} (hε : ∀ i, ε i ^ m = 1) (hsum : ∑ i, ε i = (Fintype.card ι : K)) (i : ι) :
    ε i = 1 := by
  classical
  set A := _root_.Algebra.adjoin ℚ (Set.range ε) with hA
  -- the subalgebra generated by the roots is integral over `ℚ`, hence a field
  have hint : ∀ x ∈ Set.range ε, IsIntegral ℚ x := by
    rintro _ ⟨j, rfl⟩
    exact ⟨X ^ m - C 1, monic_X_pow_sub_C 1 hm, by simp [hε j]⟩
  haveI : _root_.Algebra.IsIntegral ℚ ↥A := _root_.Algebra.IsIntegral.adjoin hint
  haveI : _root_.Algebra.IsAlgebraic ℚ ↥A := inferInstance
  -- an embedding into `ℂ`
  let f : ↥A →ₐ[ℚ] ℂ := IsAlgClosed.lift
  let e : ι → ↥A := fun j => ⟨ε j, _root_.Algebra.subset_adjoin ⟨j, rfl⟩⟩
  have hepow : ∀ j, e j ^ m = 1 := fun j => Subtype.ext (by
    have : ((e j ^ m : ↥A) : K) = (e j : K) ^ m := by push_cast; ring
    rw [this]
    simpa using hε j)
  -- the images are roots of unity in `ℂ` summing to their count
  have hnorm : ∀ j, ‖f (e j)‖ = 1 := by
    intro j
    refine Complex.norm_eq_one_of_pow_eq_one ?_ hm
    rw [← map_pow, hepow j, map_one]
  have hsumA : ∑ j, e j = (Fintype.card ι : ↥A) := by
    refine Subtype.ext ?_
    have h1 : ((∑ j, e j : ↥A) : K) = ∑ j, ε j := map_sum A.val e Finset.univ
    have h2 : (((Fintype.card ι : ↥A)) : K) = (Fintype.card ι : K) := map_natCast A.val _
    rw [h1, h2, hsum]
  have hsum' : ∑ j, f (e j) = (Fintype.card ι : ℂ) := by
    rw [← map_sum, hsumA, map_natCast]
  -- back to `ℂ`, where the statement is the equality case of the triangle inequality
  have hall := OddOrder.RepresentationTheory.all_eq_one_of_norm_eq_one_of_sum_eq_card
    (s := Finset.univ.val.map fun j => f (e j))
    (by
      intro z hz
      obtain ⟨j, -, rfl⟩ := Multiset.mem_map.mp hz
      exact hnorm j)
    (by
      have hcard : Multiset.card (Finset.univ.val.map fun j => f (e j)) = Fintype.card ι := by
        rw [Multiset.card_map]; rfl
      rw [hcard]
      exact hsum')
  have hone : f (e i) = 1 := hall _ (Multiset.mem_map_of_mem _ (Finset.mem_univ_val i))
  -- `x^m = 1` factors as `(x - 1) · (1 + x + ⋯ + x^{m-1}) = 0` in the domain `A`
  have hfac : (e i - 1) * (∑ k ∈ Finset.range m, e i ^ k) = 0 := by
    rw [mul_comm, geom_sum_mul, hepow i, sub_self]
  rcases mul_eq_zero.mp hfac with h | h
  · exact congrArg Subtype.val (sub_eq_zero.mp h)
  · -- the second factor maps to `m ≠ 0` in `ℂ`, so it is not zero
    exfalso
    have hm0 : ((m : ℕ) : ℂ) = 0 := by
      have himg := congrArg f h
      rw [map_sum, map_zero] at himg
      simp only [map_pow, hone, one_pow, Finset.sum_const, Finset.card_range, nsmul_eq_mul,
        mul_one] at himg
      exact himg
    exact hm (by exact_mod_cast hm0)

end OddOrder.Algebra
