/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.RingTheory.Artinian.Ring
import Mathlib.RingTheory.Idempotents
import Mathlib.RingTheory.Nilpotent.Basic

/-!
# Rosenberg's lemma

Let `e` be an idempotent of a ring `R` whose corner `eRe` is a *local* ring.  If `e` lies in a
finite sum of two-sided ideals then it already lies in one of them.

The proof is two lines of algebra: cutting the relation `e = ∑ c i` down by `e` on both sides
gives `e = ∑ e (c i) e` with `e (c i) e` in the corner and still in the `i`-th ideal.  In a local
ring the non-units are closed under addition and do not contain the identity, so some
`e (c i) e` is invertible in the corner — and then `e` itself is in the `i`-th ideal.

Locality is fed in abstractly, as a predicate `N` marking the non-units of the corner, because
the ring one really wants to apply this to is a *fixed subring* `A^G` sitting inside a bigger
ring `A`, and bundling that as a type only to unbundle it again is pure friction.  The
coefficients allowed to multiply the ideals are likewise given as a set `U ⊆ R`.

For a commutative ring the non-units of the corner are exactly its nilpotents, and the
dichotomy "nilpotent or invertible" is Fitting's lemma; it is available as soon as the chain of
principal ideals generated by the powers of an element stabilises, so in particular over any
Artinian ring.  This is how the hypothesis is discharged for the block idempotents of `Z(kG)`.

## Main results

* `OddOrder.exists_mem_of_sum_eq_of_local` — Rosenberg's lemma.
* `OddOrder.exists_mem_of_sum_eq_of_isNilpotent` — its commutative form.
* `OddOrder.isNilpotent_or_exists_mul_eq` — Fitting's dichotomy in the corner of a primitive
  idempotent.
* `OddOrder.exists_pow_eq_pow_mul` — the stabilisation input, over an Artinian ring.
-/

namespace OddOrder

section Local

variable {R : Type*} [Ring R] {ι : Type*}

/-- An idempotent `≠ 0` is not nilpotent. -/
theorem not_isNilpotent_of_isIdempotentElem {e : R} (he : IsIdempotentElem e) (he0 : e ≠ 0) :
    ¬ IsNilpotent e := fun h =>
  he0 (eq_of_isNilpotent_sub_of_isIdempotentElem_of_commute he .zero (by simpa using h)
    (Commute.zero_right e))

/-- **Rosenberg's lemma.**

`e` is a nonzero idempotent of `R`, and `N` marks the elements of the corner `eRe` that fail to
be invertible there: `N` is closed under addition and avoids `e` — which together say precisely
that the corner is a local ring — while `hdich` says an element of the corner outside `N` has a
left inverse there, taken from the coefficient set `U`.

If `e` is a finite sum of elements `c i` drawn from additive subgroups `I i` that are stable
under multiplication by `U` on both sides, then `e` lies in one of the `I i`. -/
theorem exists_mem_of_sum_eq_of_local {e : R} (he : IsIdempotentElem e) (he0 : e ≠ 0)
    {N : R → Prop} (hNadd : ∀ x y, N x → N y → N (x + y)) (hNe : ¬ N e)
    {U : Set R} (heU : e ∈ U)
    {s : Finset ι} {I : ι → AddSubgroup R} {c : ι → R}
    (hIl : ∀ i, ∀ u ∈ U, ∀ x ∈ I i, u * x ∈ I i)
    (hIr : ∀ i, ∀ u ∈ U, ∀ x ∈ I i, x * u ∈ I i)
    (hc : ∀ i ∈ s, c i ∈ I i)
    (hdich : ∀ i ∈ s, N (e * c i * e) ∨ ∃ u ∈ U, u * (e * c i * e) = e)
    (hsum : ∑ i ∈ s, c i = e) :
    ∃ i ∈ s, e ∈ I i := by
  by_contra hcon
  push Not at hcon
  -- The corner components stay inside their ideals.
  have hmem : ∀ i ∈ s, e * c i * e ∈ I i := fun i hi =>
    hIr i e heU _ (hIl i e heU _ (hc i hi))
  -- None of them can be invertible in the corner, else `e` would be in that ideal.
  have hN : ∀ i ∈ s, N (e * c i * e) := by
    intro i hi
    rcases hdich i hi with h | ⟨u, hu, huc⟩
    · exact h
    · exact absurd (huc ▸ hIl i u hu _ (hmem i hi)) (hcon i hi)
  rcases s.eq_empty_or_nonempty with rfl | hs
  · rw [Finset.sum_empty] at hsum
    exact he0 hsum.symm
  · -- But the corner components add up to `e`, which is not a non-unit.
    refine hNe ?_
    have hsum' : ∑ i ∈ s, e * c i * e = e := by
      rw [← Finset.sum_mul, ← Finset.mul_sum, hsum, he.eq, he.eq]
    rw [← hsum']
    exact Finset.sum_induction_nonempty _ N hNadd hs hN

end Local

section CommRing

variable {R : Type*} [CommRing R] {ι : Type*}

/-- **Rosenberg's lemma in a commutative ring.**  The corner of `e` is `eR`, its non-units are the
nilpotents, and the locality hypothesis becomes the dichotomy "`e * x` is nilpotent or invertible
in `eR`". -/
theorem exists_mem_of_sum_eq_of_isNilpotent {e : R} (he : IsIdempotentElem e) (he0 : e ≠ 0)
    (hdich : ∀ x : R, IsNilpotent (e * x) ∨ ∃ u : R, u * (e * x) = e)
    {s : Finset ι} {I : ι → Ideal R} {c : ι → R}
    (hc : ∀ i ∈ s, c i ∈ I i) (hsum : ∑ i ∈ s, c i = e) :
    ∃ i ∈ s, e ∈ I i := by
  have hcorner : ∀ x : R, e * x * e = e * x := fun x => by rw [mul_right_comm, he.eq]
  obtain ⟨i, hi, hmem⟩ := exists_mem_of_sum_eq_of_local (I := fun i => (I i).toAddSubgroup)
    he he0 (N := IsNilpotent) (fun x y hx hy => Commute.isNilpotent_add (Commute.all x y) hx hy)
    (not_isNilpotent_of_isIdempotentElem he he0) (U := Set.univ) (Set.mem_univ e)
    (fun i u _ x hx => (I i).mul_mem_left u hx) (fun i u _ x hx => (I i).mul_mem_right u hx)
    hc (fun i _ => by
      rw [hcorner]
      rcases hdich (c i) with h | ⟨u, hu⟩
      · exact Or.inl h
      · exact Or.inr ⟨u, Set.mem_univ u, hu⟩)
    hsum
  exact ⟨i, hi, hmem⟩

/-- **Fitting's dichotomy.**  Let `e` be a *primitive* idempotent — the only idempotents of the
corner `eR` are `0` and `e` — and let the powers of `e * x` generate a chain of principal ideals
that stabilises.  Then `e * x` is either nilpotent or invertible in `eR`.

Indeed `u = (e x)^n b` is an idempotent of `eR` for a stabilising `n`; `u = 0` forces
`(e x)^n = 0` and `u = e` exhibits `(e x)^{n-1} b` as an inverse. -/
theorem isNilpotent_or_exists_mul_eq {e : R} (he : IsIdempotentElem e)
    (hprim : ∀ u : R, IsIdempotentElem u → e * u = u → u = 0 ∨ u = e) {x : R}
    (hx : ∃ n : ℕ, 0 < n ∧ ∃ b : R, (e * x) ^ n = (e * x) ^ (2 * n) * b) :
    IsNilpotent (e * x) ∨ ∃ u : R, u * (e * x) = e := by
  obtain ⟨n, hn, b, hb⟩ := hx
  obtain ⟨m, rfl⟩ : ∃ m, n = m + 1 := ⟨n - 1, by omega⟩
  set y := e * x with hy
  have hey : e * y = y := by rw [hy, ← mul_assoc, he.eq]
  have heyn : e * y ^ (m + 1) = y ^ (m + 1) := by
    rw [pow_succ', ← mul_assoc, hey]
  have hsq : y ^ (m + 1) * y ^ (m + 1) = y ^ (2 * (m + 1)) := by
    rw [← pow_add]; ring_nf
  have hidem : IsIdempotentElem (y ^ (m + 1) * b) := by
    change y ^ (m + 1) * b * (y ^ (m + 1) * b) = y ^ (m + 1) * b
    calc y ^ (m + 1) * b * (y ^ (m + 1) * b)
        = y ^ (2 * (m + 1)) * b * b := by rw [← hsq]; ring
      _ = y ^ (m + 1) * b := by rw [← hb]
  have hfix : e * (y ^ (m + 1) * b) = y ^ (m + 1) * b := by rw [← mul_assoc, heyn]
  rcases hprim _ hidem hfix with h0 | h1
  · refine Or.inl ⟨m + 1, ?_⟩
    calc y ^ (m + 1) = y ^ (2 * (m + 1)) * b := hb
      _ = y ^ (m + 1) * (y ^ (m + 1) * b) := by rw [← hsq]; ring
      _ = 0 := by rw [h0, mul_zero]
  · exact Or.inr ⟨y ^ m * b, by rw [mul_comm (y ^ m) b, mul_assoc, ← pow_succ, mul_comm b, h1]⟩

set_option backward.isDefEq.respectTransparency false in
/-- **The powers of an element of an Artinian ring stabilise**: `y ^ n = y ^ (2 n) * b` for some
`n ≥ 1` and some `b`.  This is the input Fitting's dichotomy needs. -/
theorem exists_pow_eq_pow_mul [IsArtinianRing R] (y : R) :
    ∃ n : ℕ, 0 < n ∧ ∃ b : R, y ^ n = y ^ (2 * n) * b := by
  set f : ℕ →o (Submodule R R)ᵒᵈ :=
    ⟨fun m => OrderDual.toDual (Ideal.span {y ^ (m + 1)}), by
      intro m₁ m₂ hm
      exact (Ideal.span_singleton_le_span_singleton).mpr (pow_dvd_pow y (by omega))⟩ with hf
  obtain ⟨n, hn⟩ := IsArtinian.monotone_stabilizes f
  have hstab : Ideal.span {y ^ (n + 1)} = Ideal.span {y ^ (2 * (n + 1))} := by
    have := hn (2 * n + 1) (by omega)
    simpa only [hf, OrderHom.coe_mk, OrderDual.toDual_inj, show 2 * n + 1 + 1 = 2 * (n + 1) by ring]
      using this
  have hmem : y ^ (n + 1) ∈ Ideal.span ({y ^ (2 * (n + 1))} : Set R) := by
    rw [← hstab]
    exact Ideal.mem_span_singleton_self _
  obtain ⟨b, hb⟩ := Ideal.mem_span_singleton.mp hmem
  exact ⟨n + 1, Nat.succ_pos n, b, hb⟩

/-- Fitting's dichotomy over an Artinian ring: no stabilisation hypothesis needed. -/
theorem isNilpotent_or_exists_mul_eq_of_isArtinian [IsArtinianRing R] {e : R}
    (he : IsIdempotentElem e)
    (hprim : ∀ u : R, IsIdempotentElem u → e * u = u → u = 0 ∨ u = e) (x : R) :
    IsNilpotent (e * x) ∨ ∃ u : R, u * (e * x) = e :=
  isNilpotent_or_exists_mul_eq he hprim (exists_pow_eq_pow_mul (e * x))

/-- **Rosenberg's lemma for a primitive idempotent of a commutative Artinian ring.**  This is the
form used for block idempotents: `Z(kG)` is a finite-dimensional commutative algebra, hence
Artinian, and a block idempotent is primitive in it. -/
theorem exists_mem_of_sum_eq_of_isArtinian [IsArtinianRing R] {e : R} (he : IsIdempotentElem e)
    (he0 : e ≠ 0) (hprim : ∀ u : R, IsIdempotentElem u → e * u = u → u = 0 ∨ u = e)
    {s : Finset ι} {I : ι → Ideal R} {c : ι → R}
    (hc : ∀ i ∈ s, c i ∈ I i) (hsum : ∑ i ∈ s, c i = e) :
    ∃ i ∈ s, e ∈ I i :=
  exists_mem_of_sum_eq_of_isNilpotent he he0
    (isNilpotent_or_exists_mul_eq_of_isArtinian he hprim) hc hsum

end CommRing

end OddOrder
