/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.FieldTheory.Finite.Basic
import Mathlib.Algebra.Algebra.ZMod
import OddOrder.Algebra.FixedPointsGalois

/-!
# Automorphisms of a finite field are Frobenius powers

Every `σ : RingAut F` of a finite field is `x ↦ x ^ s` for `s` a power of the
characteristic.  This is the concrete handle needed to analyse *semilinear*
maps `v ↦ c · σ v`, which is how a group of odd order acts on a homogeneous
component of an `𝔽₂[K]`-module when it normalizes the cyclic group `K`.

Peterfalvi Part II, Ch. III §1 (p. 117) needs exactly that analysis: the book
routes the step through "`[K, P] ⋊ P` is a Frobenius group", which is only
valid when `p ∤ |C_{Q₀}(P)| − 1` (automatic in Ch. II, where `|Q₀| = 2^p`, but
not in Ch. III).  The semilinear route replaces it and needs no coprimality.

## Main results

* `OddOrder.RingAut.exists_pow_eq` — `σ x = x ^ s` for some `s`.
-/

namespace OddOrder.RingAut

variable {F : Type*} [Field F] [Finite F]

/-- **Every automorphism of a finite field is a power of the Frobenius.**

Over the prime field every ring automorphism is automatically an algebra
automorphism, and `Gal(F / 𝔽_p)` is generated by the Frobenius
(`FiniteField.bijective_frobeniusAlgEquivOfAlgebraic_pow`), whose `n`-th power
is `x ↦ x ^ (p ^ n)`. -/
theorem exists_pow_eq (σ : _root_.RingAut F) :
    ∃ s : ℕ, 0 < s ∧ ∀ x : F, σ x = x ^ s := by
  classical
  haveI : Fintype F := Fintype.ofFinite F
  obtain ⟨p, hp⟩ := CharP.exists F
  haveI : Fact (Nat.Prime p) := ⟨CharP.char_is_prime F p⟩
  haveI : CharP F p := hp
  haveI : Fintype (ZMod p) := ZMod.fintype p
  letI : Algebra (ZMod p) F := ZMod.algebra F p
  haveI : Algebra.IsAlgebraic (ZMod p) F := Algebra.IsIntegral.isAlgebraic
  -- `σ` fixes the prime field, hence is an algebra automorphism
  let σA : F ≃ₐ[ZMod p] F :=
    AlgEquiv.ofRingEquiv (f := σ) fun r => by
      have h := RingHom.ext_zmod (σ.toRingHom.comp (algebraMap (ZMod p) F))
        (algebraMap (ZMod p) F)
      exact congrFun (congrArg (fun f : ZMod p →+* F => (f : ZMod p → F)) h) r
  obtain ⟨n, hn⟩ :=
    (FiniteField.bijective_frobeniusAlgEquivOfAlgebraic_pow (ZMod p) F).2 σA
  refine ⟨Fintype.card (ZMod p) ^ (n : ℕ), pow_pos Fintype.card_pos _, fun x => ?_⟩
  have hx : σA x = (FiniteField.frobeniusAlgEquivOfAlgebraic (ZMod p) F ^ (n : ℕ)) x := by
    simp only [← hn]
  rw [show σ x = σA x from rfl, hx, AlgEquiv.coe_pow,
    FiniteField.coe_frobeniusAlgEquivOfAlgebraic_iterate]

end OddOrder.RingAut
