/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.FieldTheory.Finite.Basic
import Mathlib.Algebra.Algebra.ZMod
import OddOrder.Algebra.FixedPointsGalois

/-!
# Automorphisms of a finite field are Frobenius powers

Every `σ : RingAut F` of a finite field is `x ↦ x ^ s` for `s` a power of the
characteristic.  This is the concrete handle needed to analyse *semilinear*
maps `v ↦ c · σ v`, which is how a group of odd order acts on a homogeneous
component of an `𝔽₂[K]`-module when it normalizes the cyclic group `K`.

Peterfalvi Part II, Ch. III §1 (p. 117) needs exactly that analysis: the book
routes the step through "`[K, P] ⋊ P` is a Frobenius group", which is only
valid when `p ∤ |C_{Q₀}(P)| − 1` (automatic in Ch. II, where `|Q₀| = 2^p`, but
not in Ch. III).  The semilinear route replaces it and needs no coprimality.

## Main results

* `OddOrder.RingAut.exists_pow_eq` — `σ x = x ^ s` for some `s`.
* `OddOrder.exists_pow_eq_of_pow_natCard_div_eq_one` — in a finite cyclic group,
  `x ^ (N / d) = 1` makes `x` a `d`-th power.
* `OddOrder.RingAut.exists_ne_zero_mul_pow_eq` — **Hilbert 90**, semilinear form:
  if `|F| = s ^ n` and `c ^ ((|F| - 1) / (s - 1)) = 1` then `c * v ^ s = v` for
  some `v ≠ 0`.
* `OddOrder.RingAut.exists_generator_pow_natCard_fixedSet` — a prime-order
  subgroup of `RingAut F` is generated by the `|F^B|`-power map.  This is what
  lets the previous lemma be applied: an arbitrary element of `B` is `a ↦ a ^ s`
  for some `s`, but only the distinguished generator has `|F| = s ^ |B|`.
-/

namespace OddOrder.RingAut

variable {F : Type*} [Field F] [Finite F]

/-- **Every automorphism of a finite field is a power of the Frobenius.**

Over the prime field every ring automorphism is automatically an algebra
automorphism, and `Gal(F / 𝔽_p)` is generated by the Frobenius
(`FiniteField.bijective_frobeniusAlgEquivOfAlgebraic_pow`), whose `n`-th power
is `x ↦ x ^ (p ^ n)`. -/
theorem exists_pow_eq (σ : _root_.RingAut F) :
    ∃ s : ℕ, 0 < s ∧ ∀ x : F, σ x = x ^ s := by
  classical
  haveI : Fintype F := Fintype.ofFinite F
  obtain ⟨p, hp⟩ := CharP.exists F
  haveI : Fact (Nat.Prime p) := ⟨CharP.char_is_prime F p⟩
  haveI : CharP F p := hp
  haveI : Fintype (ZMod p) := ZMod.fintype p
  letI : Algebra (ZMod p) F := ZMod.algebra F p
  haveI : Algebra.IsAlgebraic (ZMod p) F := Algebra.IsIntegral.isAlgebraic
  -- `σ` fixes the prime field, hence is an algebra automorphism
  let σA : F ≃ₐ[ZMod p] F :=
    AlgEquiv.ofRingEquiv (f := σ) fun r => by
      have h := RingHom.ext_zmod (σ.toRingHom.comp (algebraMap (ZMod p) F))
        (algebraMap (ZMod p) F)
      exact congrFun (congrArg (fun f : ZMod p →+* F => (f : ZMod p → F)) h) r
  obtain ⟨n, hn⟩ :=
    (FiniteField.bijective_frobeniusAlgEquivOfAlgebraic_pow (ZMod p) F).2 σA
  refine ⟨Fintype.card (ZMod p) ^ (n : ℕ), pow_pos Fintype.card_pos _, fun x => ?_⟩
  have hx : σA x = (FiniteField.frobeniusAlgEquivOfAlgebraic (ZMod p) F ^ (n : ℕ)) x := by
    simp only [← hn]
  rw [show σ x = σA x from rfl, hx, AlgEquiv.coe_pow,
    FiniteField.coe_frobeniusAlgEquivOfAlgebraic_iterate]

/-- In a finite cyclic group of order `N`, an element killed by `N / d` (for `d ∣ N`)
is a `d`-th power.

Writing `x = g ^ a` for a generator `g`, the hypothesis says `N ∣ a * (N / d)`, i.e.
`d ∣ a`. -/
theorem _root_.OddOrder.exists_pow_eq_of_pow_natCard_div_eq_one {C : Type*} [CommGroup C]
    [Finite C] [IsCyclic C] {d : ℕ} (hd : d ∣ Nat.card C) {x : C}
    (hx : x ^ (Nat.card C / d) = 1) : ∃ b : C, b ^ d = x := by
  classical
  obtain ⟨m, hm⟩ := hd
  have hNpos : 0 < Nat.card C := Nat.card_pos
  have hdpos : 0 < d := by
    rcases Nat.eq_zero_or_pos d with rfl | h
    · rw [zero_mul] at hm; omega
    · exact h
  have hmpos : 0 < m := by
    rcases Nat.eq_zero_or_pos m with rfl | h
    · rw [mul_zero] at hm; omega
    · exact h
  have hdiv : Nat.card C / d = m := by rw [hm]; exact Nat.mul_div_cancel_left m hdpos
  obtain ⟨g, hg⟩ := IsCyclic.exists_generator (α := C)
  have hgord : orderOf g = Nat.card C := orderOf_eq_card_of_forall_mem_zpowers hg
  obtain ⟨a, ha⟩ := mem_powers_iff_mem_zpowers.mpr (hg x)
  have ha' : g ^ a = x := ha
  rw [← ha', ← pow_mul, hdiv] at hx
  have hdvd : orderOf g ∣ a * m := orderOf_dvd_of_pow_eq_one hx
  rw [hgord, hm] at hdvd
  obtain ⟨t, ht⟩ := hdvd
  have hda : a = d * t := by
    have h2 : (d * t) * m = a * m := by
      calc (d * t) * m = (d * m) * t := by ring
        _ = a * m := ht.symm
    exact (Nat.eq_of_mul_eq_mul_right hmpos h2).symm
  refine ⟨g ^ t, ?_⟩
  rw [← pow_mul, mul_comm t d, ← hda, ha']

/-- **Hilbert's Theorem 90 for a finite field, semilinear form.**

If `|F| = s ^ n` and `c ≠ 0` has trivial `s`-norm — i.e. `c ^ ((|F| - 1)/(s - 1)) = 1`,
which is `∏_{i < n} c^{s^i} = 1` — then the semilinear map `v ↦ c * v ^ s` has a
non-trivial fixed point.

`v ↦ c * v ^ s` fixes `v ≠ 0` exactly when `v ^ (s - 1) = c⁻¹`, so this says `c⁻¹`
is an `(s-1)`-st power in the cyclic group `Fˣ`, which is
`OddOrder.exists_pow_eq_of_pow_natCard_div_eq_one` once one knows
`(s - 1) ∣ (|F| - 1)`. -/
theorem exists_ne_zero_mul_pow_eq {s n : ℕ} (hs : 1 < s)
    (hcard : Nat.card F = s ^ n) {c : F} (hc : c ≠ 0)
    (hnorm : c ^ ((Nat.card F - 1) / (s - 1)) = 1) :
    ∃ v : F, v ≠ 0 ∧ c * v ^ s = v := by
  classical
  haveI : Fintype F := Fintype.ofFinite F
  have hunits : Nat.card Fˣ = Nat.card F - 1 := Nat.card_units F
  have hdvd : (s - 1) ∣ Nat.card F - 1 := by
    rw [hcard]
    exact Nat.sub_one_dvd_pow_sub_one s n
  have hdvd' : (s - 1) ∣ Nat.card Fˣ := by rw [hunits]; exact hdvd
  set cu : Fˣ := Units.mk0 c hc with hcu
  have hnorm' : cu ^ (Nat.card Fˣ / (s - 1)) = 1 := by
    apply Units.ext
    rw [hunits]
    simpa [hcu] using hnorm
  obtain ⟨b, hb⟩ := OddOrder.exists_pow_eq_of_pow_natCard_div_eq_one hdvd' hnorm'
  have hval : ((b : Fˣ) : F) ^ (s - 1) = c := by
    simpa [hcu] using congrArg (Units.val (α := F)) hb
  have hb0 : ((b : Fˣ) : F) ≠ 0 := b.ne_zero
  refine ⟨(((b : Fˣ) : F))⁻¹, inv_ne_zero hb0, ?_⟩
  have hs1 : s = (s - 1) + 1 := by omega
  rw [← hval, inv_pow, hs1, pow_succ]
  field_simp
  congr 1

/-! ## The distinguished generator of a prime-order automorphism group -/

/-- **A prime-order subgroup of `RingAut F` is generated by the `|F^B|`-power map.**

Let `B ≤ RingAut F` have prime order `p` and put `s = |F^B|`.  Then `a ↦ a ^ s`
is an automorphism of `F` lying in `B` (it fixes `F^B` pointwise, and `B` is
*all* of the automorphisms doing that, by `fixer_fixedSet`), it is non-trivial,
and hence generates `B`.  Moreover `|F| = s ^ p` by Artin.

This matters because `exists_ne_zero_mul_pow_eq` needs `|F| = s ^ n`: an
arbitrary generator of `B` is `a ↦ a ^ (s ^ j)` for some `j` prime to `p`, and
then `|F| ≠ (s ^ j) ^ p`.  Picking *this* generator repairs that. -/
theorem exists_generator_pow_natCard_fixedSet {B : Subgroup (_root_.RingAut F)}
    {p : ℕ} (hp : p.Prime) (hB : Nat.card B = p) :
    ∃ σ : _root_.RingAut F, σ ∈ B ∧ Subgroup.zpowers σ = B ∧
      (∀ a : F, σ a = a ^ Nat.card (fixedSet B)) ∧
      Nat.card F = Nat.card (fixedSet B) ^ p := by
  classical
  haveI : Fintype F := Fintype.ofFinite F
  obtain ⟨p₀, hp₀⟩ := CharP.exists F
  haveI : Fact (Nat.Prime p₀) := ⟨CharP.char_is_prime F p₀⟩
  haveI : CharP F p₀ := hp₀
  haveI : Fintype (ZMod p₀) := ZMod.fintype p₀
  letI : Algebra (ZMod p₀) F := ZMod.algebra F p₀
  haveI : Algebra.IsAlgebraic (ZMod p₀) F := Algebra.IsIntegral.isAlgebraic
  set K₀ : Subfield F := FixedPoints.subfield (↥B) F with hK₀
  set s : ℕ := Nat.card (fixedSet B) with hs
  have hscard : s = Nat.card ↥K₀ := by
    rw [hs, fixedSet_eq_subfield]; rfl
  -- Artin: `|F| = s ^ p`
  have hArtin : Module.finrank (↥K₀) F = p := by
    rw [hK₀, finrank_fixedSet B, hB]
  have hcard : Nat.card F = s ^ p := by
    haveI : Fintype ↥K₀ := Fintype.ofFinite _
    rw [hscard, ← hArtin]
    simpa [Nat.card_eq_fintype_card] using
      (Module.card_eq_pow_finrank (K := ↥K₀) (V := F))
  -- `s` is a power of the characteristic
  have hFcard : Nat.card F = p₀ ^ Module.finrank (ZMod p₀) F := by
    haveI : Fintype (ZMod p₀) := inferInstance
    simpa [Nat.card_eq_fintype_card, ZMod.card] using
      (Module.card_eq_pow_finrank (K := ZMod p₀) (V := F))
  have hsdvd : s ∣ p₀ ^ Module.finrank (ZMod p₀) F := by
    rw [← hFcard, hcard]
    exact dvd_pow_self s hp.pos.ne'
  obtain ⟨j, _hj, hsj⟩ := (Nat.dvd_prime_pow (Fact.out : p₀.Prime)).mp hsdvd
  -- the `s`-power map as a ring automorphism
  set τ : _root_.RingAut F :=
    ((FiniteField.frobeniusAlgEquivOfAlgebraic (ZMod p₀) F) ^ j).toRingEquiv with hτ
  have hτapp : ∀ a : F, τ a = a ^ s := by
    intro a
    have : τ a = ((FiniteField.frobeniusAlgEquivOfAlgebraic (ZMod p₀) F) ^ j) a := rfl
    rw [this, AlgEquiv.coe_pow, FiniteField.coe_frobeniusAlgEquivOfAlgebraic_iterate,
      hsj, ZMod.card]
  -- `τ` fixes `F^B` pointwise, hence lies in `B`
  have hτB : τ ∈ B := by
    rw [← fixer_fixedSet B]
    intro a ha
    rw [hτapp a]
    have haK : a ∈ K₀ := by
      have := (fixedSet_eq_subfield B) ▸ ha
      exact this
    haveI : Fintype ↥K₀ := Fintype.ofFinite _
    have hpow : (⟨a, haK⟩ : ↥K₀) ^ Nat.card ↥K₀ = ⟨a, haK⟩ := by
      simpa [Nat.card_eq_fintype_card] using FiniteField.pow_card (⟨a, haK⟩ : ↥K₀)
    rw [hscard]
    exact congrArg (Subtype.val (p := fun z => z ∈ K₀)) hpow
  -- `τ ≠ 1`
  have hs2 : 2 ≤ s := by
    rw [hscard]
    haveI : Fintype ↥K₀ := Fintype.ofFinite _
    have : 1 < Nat.card ↥K₀ := Finite.one_lt_card_iff_nontrivial.mpr inferInstance
    omega
  have hτne : τ ≠ 1 := by
    intro h
    have hall : ∀ a : F, a ^ s = a := by
      intro a
      rw [← hτapp a, h]; rfl
    -- every unit would satisfy `a ^ (s - 1) = 1`, bounding the order of `Fˣ`
    haveI : Fintype F := Fintype.ofFinite F
    obtain ⟨g, hg⟩ := IsCyclic.exists_generator (α := Fˣ)
    have hgord : orderOf g = Nat.card Fˣ := orderOf_eq_card_of_forall_mem_zpowers hg
    have hunits : Nat.card Fˣ = Nat.card F - 1 := Nat.card_units F
    have hgs : g ^ (s - 1) = 1 := by
      apply Units.ext
      have h1 : ((g : F)) ^ s = (g : F) := hall _
      have h2 : (g : F) ≠ 0 := g.ne_zero
      have hs1 : s = (s - 1) + 1 := by omega
      rw [hs1, pow_succ] at h1
      simpa using mul_right_cancel₀ h2 (by simpa using h1)
    have hdvd : orderOf g ∣ s - 1 := orderOf_dvd_of_pow_eq_one hgs
    rw [hgord, hunits, hcard] at hdvd
    have hpos : 0 < s - 1 := by omega
    have hle : s ^ p - 1 ≤ s - 1 := Nat.le_of_dvd hpos hdvd
    have hbig : s * s ≤ s ^ p := by
      calc s * s = s ^ 2 := by ring
        _ ≤ s ^ p := Nat.pow_le_pow_right (by omega) hp.two_le
    have h4 : s * 2 ≤ s * s := Nat.mul_le_mul_left s hs2
    have h5 : 2 ≤ s := hs2
    omega
  refine ⟨τ, hτB, ?_, hτapp, hcard⟩
  -- prime order: any non-trivial element generates
  have hle : Subgroup.zpowers τ ≤ B := (Subgroup.zpowers_le).mpr hτB
  refine (Subgroup.eq_of_le_of_card_ge hle ?_)
  rw [hB]
  have : orderOf τ ≠ 1 := fun h => hτne (orderOf_eq_one_iff.mp h)
  have hdvd : orderOf τ ∣ p := by
    rw [← hB]
    have h1 := orderOf_dvd_natCard (⟨τ, hτB⟩ : ↥B)
    have h2 : orderOf τ = orderOf (⟨τ, hτB⟩ : ↥B) :=
      Subgroup.orderOf_coe (⟨τ, hτB⟩ : ↥B)
    rwa [← h2] at h1
  have : orderOf τ = p := (hp.eq_one_or_self_of_dvd _ hdvd).resolve_left this
  rw [Nat.card_zpowers, this]

end OddOrder.RingAut
