/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.BG.Ch1_Preliminary.PLengthTransfer
import OddOrder.Isaacs.Ch05_Transfer.Basic

/-!
# BG Lemma 1.21(d) — `p`-length one via the subgroup generated by `p`-elements

Bender–Glauberman, *Local Analysis for the Odd Order Theorem* (LMS LNS 188, 1994), §1
(mmd `references/bg/local-analysis.mmd` L569, issue 3010):

> (d) `G` has `p`-length one **iff** the subgroup `U` of `G` generated by all `p`-elements
> has a normal `p`-complement.

This is the last numbered result of BG §1; parts (a)(b)(c)(e) live in `PLengthTransfer.lean`.

## Statement and proof outline

`U := pElementsSubgroup p G := closure {g | IsPGroup p (zpowers g)}` is the subgroup generated
by all elements of `p`-power order (`O^{p'}(G)`, the `p'`-residual — note the repo's `OPrime`
is `O^p`, a different object). It is normal because conjugation preserves `p`-power order.

Writing `Opp := O_{p',p}(G) = oPiPrimePiCore {p} G` and `Op' := O_{p'}(G) = oPiCore {p}ᶜ G`,
the biconditional splits as

* **Step 1** (`hasPLengthOne_iff_pElementsSubgroup_le`): `G` has `p`-length one `↔ U ≤ Opp`.
  `hasPLengthOne p G` unfolds to `p ∤ |G / Opp|`, i.e. `G/Opp` is a `p'`-group. Forward: every
  `p`-element maps to a `p`-power-order element of the `p'`-group `G/Opp`, hence to `1`, so lies
  in `Opp`; `closure_le` gives `U ≤ Opp`. Backward: a Sylow `p`-subgroup `P` is generated by
  `p`-elements so `P ≤ U ≤ Opp`, forcing `p ∤ [G : Opp]`.

* **Step 2** (`pElementsSubgroup_le_iff_hasNormalPComplement`): `U ≤ Opp ↔ U` has a normal
  `p`-complement. Both directions run through the image of `U` in `G/Op'`:
  `↥U ⧸ (Op'.subgroupOf U) ≅ U.map (mk' Op')`, whose order is `(Op'.subgroupOf U).index`.
  - `U ≤ Opp ⟹` `U.map (mk' Op') ≤ Opp.map (mk' Op') = O_p(G/Op')` is a `p`-group, so
    `N := Op'.subgroupOf U` is a normal Hall `p'`-subgroup of `↥U`, giving a normal `p`-complement.
  - A normal `p`-complement `K ◁ ↥U` forces `O_{p'}(↥U) ≤ N`, and `[↥U : N] ∣ [↥U : O_{p'}(↥U)]
    ∣ [↥U : K]` is a `p`-power; so `U.map (mk' Op')` is a `p`-group and `U ≤ Opp`.

The `HasNormalPComplement ⟸ normal Hall p'-subgroup` bridge is
`hasNormalPComplement_of_normal_pPrime_index`.
-/

namespace OddOrder.BG.Ch1

open OddOrder.Isaacs

variable {p : ℕ}

/-- The subgroup generated by all `p`-elements of `G` (elements of `p`-power order). This is the
`p'`-residual `O^{p'}(G)` appearing in BG Lemma 1.21(d). -/
def pElementsSubgroup (p : ℕ) (G : Type*) [Group G] : Subgroup G :=
  Subgroup.closure {g : G | IsPGroup p (Subgroup.zpowers g)}

/-- **`pElementsSubgroup p G` is normal.** The generating set `{g | IsPGroup p (zpowers g)}` is
stable under conjugation (`SemiconjBy g x (g*x*g⁻¹)` gives `orderOf x = orderOf (g*x*g⁻¹)`), so
`closure` of it is normal. -/
theorem pElementsSubgroup_normal (p : ℕ) (G : Type*) [Group G] [Finite G] [Fact p.Prime] :
    (pElementsSubgroup p G).Normal := by
  refine ⟨fun n hn g => ?_⟩
  change g * n * g⁻¹ ∈ Subgroup.closure {y : G | IsPGroup p (Subgroup.zpowers y)}
  have hn' : n ∈ Subgroup.closure {y : G | IsPGroup p (Subgroup.zpowers y)} := hn
  clear hn
  induction hn' using Subgroup.closure_induction with
  | mem x hx =>
      refine Subgroup.subset_closure ?_
      change IsPGroup p (Subgroup.zpowers (g * x * g⁻¹))
      have hx' : IsPGroup p (Subgroup.zpowers x) := hx
      have hsemi : SemiconjBy g x (g * x * g⁻¹) := by unfold SemiconjBy; group
      have horder : orderOf x = orderOf (g * x * g⁻¹) := hsemi.orderOf_eq g
      rw [IsPGroup.iff_card] at hx' ⊢
      rw [Nat.card_zpowers, ← horder, ← Nat.card_zpowers]
      exact hx'
  | one => simp
  | mul a b _ _ iha ihb =>
      have hrw : g * (a * b) * g⁻¹ = (g * a * g⁻¹) * (g * b * g⁻¹) := by group
      rw [hrw]; exact Subgroup.mul_mem _ iha ihb
  | inv a _ iha =>
      have hrw : g * a⁻¹ * g⁻¹ = (g * a * g⁻¹)⁻¹ := by group
      rw [hrw]; exact Subgroup.inv_mem _ iha

/-- `O_{p'}(G) = oPiCore {p}ᶜ G` has order prime to `p` (it is a `{p}ᶜ`-group). -/
private theorem oPiCore_compl_not_dvd [Fact p.Prime] {G : Type*} [Group G] [Finite G] :
    ¬ p ∣ Nat.card ↥(Ch03.oPiCore (({p} : Set ℕ)ᶜ) G) := fun hd =>
  (Ch03.oPiCore.isPiGroup (({p} : Set ℕ)ᶜ) p
    (Nat.mem_primeFactors.mpr ⟨Fact.out, hd, Nat.card_pos.ne'⟩)) (Set.mem_singleton p)

/-- **char in normal ⇒ normal** (local copy of the standard fact, also in
`Ch09_MoreSubnormality.Semisimple` / `Ch10_MoreTransfer.TransferIndexPrime`): if `L` is
characteristic in the normal subgroup `N ⊴ W`, then `L.map N.subtype ⊴ W`. -/
private theorem normal_map_subtype_of_char {W : Type*} [Group W] {N : Subgroup W}
    [N.Normal] {L : Subgroup ↥N} (hL : L.Characteristic) :
    (L.map N.subtype).Normal := by
  refine ⟨fun a ha w => ?_⟩
  obtain ⟨⟨a', ha'N⟩, ha'L, rfl⟩ := ha
  have hmap : L.map (MulAut.conjNormal w).toMonoidHom = L :=
    (Subgroup.characteristic_iff_map_eq.mp hL) (MulAut.conjNormal w)
  have hmem : (MulAut.conjNormal w) ⟨a', ha'N⟩ ∈ L := by
    rw [← hmap]; exact Subgroup.mem_map_of_mem _ ha'L
  exact ⟨(MulAut.conjNormal w) ⟨a', ha'N⟩, hmem, MulAut.conjNormal_apply w ⟨a', ha'N⟩⟩

/-- **Second-isomorphism bookkeeping**: for `M ⊴ G` and any `U ≤ G`, the index of `M ⊓ U` inside
`U` equals the order of the image of `U` in `G/M`. (`(mk' M) ∘ U.subtype` has kernel
`M.subgroupOf U` and range `U.map (mk' M)`.) -/
private theorem index_subgroupOf_eq_card_map {G : Type*} [Group G] (U M : Subgroup G) [M.Normal] :
    (M.subgroupOf U).index = Nat.card ↥(U.map (QuotientGroup.mk' M)) := by
  have hψrange : ((QuotientGroup.mk' M).comp U.subtype).range = U.map (QuotientGroup.mk' M) := by
    rw [MonoidHom.range_comp, Subgroup.range_subtype]
  have hψker : ((QuotientGroup.mk' M).comp U.subtype).ker = M.subgroupOf U := by
    ext x
    simp only [MonoidHom.mem_ker, MonoidHom.comp_apply, Subgroup.coe_subtype,
      QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff, Subgroup.mem_subgroupOf]
  rw [← hψker, ← hψrange, Subgroup.index_eq_card]
  exact Nat.card_congr (QuotientGroup.quotientKerEquivRange _).toEquiv

/-- **Bridge: a normal Hall `p'`-subgroup is a normal `p`-complement.** If `N ⊴ H` has order
prime to `p` and index a power of `p`, then any Sylow `p`-subgroup complements `N`, so `H` has a
normal `p`-complement. Mirrors the cardinality argument of Isaacs Thm 5.25 / Lem 5.27. -/
theorem hasNormalPComplement_of_normal_pPrime_index {H : Type*} [Group H] [Finite H]
    [Fact p.Prime] (N : Subgroup H) [N.Normal]
    (hNp' : ¬ p ∣ Nat.card ↥N) (hidx : ∃ k, N.index = p ^ k) :
    Ch05.HasNormalPComplement p H := by
  refine ⟨N, inferInstance, fun P => ?_⟩
  obtain ⟨k, hk⟩ := hidx
  have hP_card : Nat.card ↥(P : Subgroup H) = p ^ (Nat.card H).factorization p :=
    P.card_eq_multiplicity
  have hv : (Nat.card H).factorization p = k := by
    have hL : Nat.card ↥N * N.index = Nat.card H := Subgroup.card_mul_index N
    have htot : Nat.card H = Nat.card ↥N * p ^ k := by rw [← hL, hk]
    rw [htot, Nat.factorization_mul Nat.card_pos.ne' (pow_ne_zero k (Fact.out : p.Prime).pos.ne'),
        Finsupp.add_apply, Nat.factorization_eq_zero_of_not_dvd hNp',
        Nat.factorization_pow_self Fact.out, zero_add]
  have hP_card' : Nat.card ↥(P : Subgroup H) = p ^ k := by rw [hP_card, hv]
  have hmul : Nat.card ↥N * Nat.card ↥(P : Subgroup H) = Nat.card H := by
    rw [hP_card', ← hk]; exact Subgroup.card_mul_index N
  have hcop : Nat.Coprime (Nat.card ↥N) (Nat.card ↥(P : Subgroup H)) := by
    rw [hP_card']
    exact (((Nat.Prime.coprime_iff_not_dvd Fact.out).mpr hNp').symm).pow_right k
  exact Subgroup.isComplement'_of_coprime hmul hcop

section /- BG Lemma 1.21(d) (mmd L569) -/

variable [Fact p.Prime] {G : Type*} [Group G] [Finite G]

/-- **Step 1**: `G` has `p`-length one iff `U := ⟨p-elements⟩ ≤ O_{p',p}(G)`. -/
theorem hasPLengthOne_iff_pElementsSubgroup_le :
    hasPLengthOne p G ↔ pElementsSubgroup p G ≤ Ch03.oPiPrimePiCore ({p} : Set ℕ) G := by
  constructor
  · -- `G/Opp` a `p'`-group ⟹ every `p`-element lies in `Opp`.
    intro hpl
    rw [pElementsSubgroup, Subgroup.closure_le]
    intro g hg
    have hg' : IsPGroup p (Subgroup.zpowers g) := hg
    change g ∈ Ch03.oPiPrimePiCore ({p} : Set ℕ) G
    obtain ⟨k, hk⟩ := (IsPGroup.iff_card).mp hg'
    rw [Nat.card_zpowers] at hk
    have hg1 : g ^ (p ^ k) = 1 := by rw [← hk]; exact pow_orderOf_eq_one g
    have hx1 : QuotientGroup.mk' (Ch03.oPiPrimePiCore ({p} : Set ℕ) G) g = 1 := by
      set x := QuotientGroup.mk' (Ch03.oPiPrimePiCore ({p} : Set ℕ) G) g with hx
      have hgpow : x ^ (p ^ k) = 1 := by rw [hx, ← map_pow, hg1, map_one]
      have hord_dvd_pk : orderOf x ∣ p ^ k := orderOf_dvd_of_pow_eq_one hgpow
      have hord_dvd_card : orderOf x ∣ Nat.card (G ⧸ Ch03.oPiPrimePiCore ({p} : Set ℕ) G) :=
        orderOf_dvd_natCard x
      obtain ⟨j, _, hj⟩ := (Nat.dvd_prime_pow Fact.out).mp hord_dvd_pk
      rcases Nat.eq_zero_or_pos j with hj0 | hjpos
      · rw [hj0, pow_zero] at hj; exact orderOf_eq_one_iff.mp hj
      · exact absurd
          ((show p ∣ orderOf x by rw [hj]; exact dvd_pow_self p hjpos.ne').trans hord_dvd_card) hpl
    rwa [QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff] at hx1
  · -- a Sylow `p`-subgroup lies in `U ≤ Opp`, so `p ∤ [G : Opp]`.
    intro hle hdvd
    obtain ⟨P⟩ := (inferInstance : Nonempty (Sylow p G))
    have hP_le_U : (P : Subgroup G) ≤ pElementsSubgroup p G := by
      intro x hxP
      exact Subgroup.subset_closure (P.isPGroup'.to_le (Subgroup.zpowers_le.mpr hxP))
    have hP_le_Opp : (P : Subgroup G) ≤ Ch03.oPiPrimePiCore ({p} : Set ℕ) G := hP_le_U.trans hle
    have hidx_dvd : (Ch03.oPiPrimePiCore ({p} : Set ℕ) G).index ∣ (P : Subgroup G).index :=
      Subgroup.index_dvd_of_le hP_le_Opp
    rw [← Subgroup.index_eq_card] at hdvd
    exact P.not_dvd_index (hdvd.trans hidx_dvd)

/-- **Step 2**: `U ≤ O_{p',p}(G)` iff `U := ⟨p-elements⟩` has a normal `p`-complement. -/
theorem pElementsSubgroup_le_iff_hasNormalPComplement :
    pElementsSubgroup p G ≤ Ch03.oPiPrimePiCore ({p} : Set ℕ) G ↔
      Ch05.HasNormalPComplement p ↥(pElementsSubgroup p G) := by
  haveI hU_normal : (pElementsSubgroup p G).Normal := pElementsSubgroup_normal p G
  constructor
  · -- `N := O_{p'}(G) ⊓ U` is a normal Hall `p'`-subgroup of `↥U`.
    intro hU_le
    haveI hN_normal :
        ((Ch03.oPiCore (({p} : Set ℕ)ᶜ) G).subgroupOf (pElementsSubgroup p G)).Normal :=
      Subgroup.Normal.comap inferInstance (pElementsSubgroup p G).subtype
    refine hasNormalPComplement_of_normal_pPrime_index
      ((Ch03.oPiCore (({p} : Set ℕ)ᶜ) G).subgroupOf (pElementsSubgroup p G)) ?_ ?_
    · -- `p ∤ |N|` since `N ↪ O_{p'}(G)`.
      have hcard :
          Nat.card ↥((Ch03.oPiCore (({p} : Set ℕ)ᶜ) G).subgroupOf (pElementsSubgroup p G))
            = Nat.card ↥(((Ch03.oPiCore (({p} : Set ℕ)ᶜ) G).subgroupOf
                (pElementsSubgroup p G)).map (pElementsSubgroup p G).subtype) :=
        Nat.card_congr (Subgroup.equivMapOfInjective _ _
          (pElementsSubgroup p G).subtype_injective).toEquiv
      rw [hcard, Subgroup.subgroupOf_map_subtype]
      exact fun hd => oPiCore_compl_not_dvd (hd.trans (Subgroup.card_dvd_of_le inf_le_left))
    · -- `[↥U : N] = |U.map (mk' Op')|`, a `p`-power.
      have hUmap_pg : IsPGroup p ↥((pElementsSubgroup p G).map
          (QuotientGroup.mk' (Ch03.oPiCore (({p} : Set ℕ)ᶜ) G))) := by
        have hle : (pElementsSubgroup p G).map
              (QuotientGroup.mk' (Ch03.oPiCore (({p} : Set ℕ)ᶜ) G))
            ≤ (Ch03.oPiPrimePiCore ({p} : Set ℕ) G).map
              (QuotientGroup.mk' (Ch03.oPiCore (({p} : Set ℕ)ᶜ) G)) :=
          Subgroup.map_mono hU_le
        exact isPGroup_map_oPiPrimePiCore.of_injective (Subgroup.inclusion hle)
          (Subgroup.inclusion_injective hle)
      obtain ⟨k, hk⟩ := (IsPGroup.iff_card).mp hUmap_pg
      exact ⟨k, by
        rw [index_subgroupOf_eq_card_map (pElementsSubgroup p G)
          (Ch03.oPiCore (({p} : Set ℕ)ᶜ) G), hk]⟩
  · -- A normal `p`-complement forces `O_{p'}(↥U) ≤ N`, so `[↥U : N]` is a `p`-power.
    intro hNPC
    obtain ⟨K, hKn, hKcompl⟩ := hNPC
    haveI : K.Normal := hKn
    obtain ⟨P⟩ := (inferInstance : Nonempty (Sylow p ↥(pElementsSubgroup p G)))
    have hKp' : ¬ p ∣ Nat.card ↥K := by
      rw [← (hKcompl P).index_eq_card]; exact P.not_dvd_index
    have hKpi : Ch03.Subgroup.IsPiGroup (({p} : Set ℕ)ᶜ) K := by
      intro r hr
      have hrp : r ≠ p := by
        intro h
        rw [h] at hr
        exact hKp' (Nat.dvd_of_mem_primeFactors hr)
      simpa using hrp
    have hK_le_W : K ≤ Ch03.oPiCore (({p} : Set ℕ)ᶜ) ↥(pElementsSubgroup p G) :=
      Ch03.Subgroup.IsPiGroup.le_oPiCore hKpi
    have hK_idx_pow : ∃ m, K.index = p ^ m :=
      ⟨_, by rw [((hKcompl P).symm).index_eq_card]; exact P.card_eq_multiplicity⟩
    -- `W := O_{p'}(↥U)` is characteristic, so `W.map U.subtype ⊴ G`, `p'`, hence `≤ O_{p'}(G)`.
    haveI hWchar : (Ch03.oPiCore (({p} : Set ℕ)ᶜ) ↥(pElementsSubgroup p G)).Characteristic :=
      Ch03.oPiCore.characteristic _ _
    haveI hWG_normal : ((Ch03.oPiCore (({p} : Set ℕ)ᶜ) ↥(pElementsSubgroup p G)).map
        (pElementsSubgroup p G).subtype).Normal := normal_map_subtype_of_char hWchar
    have hWG_pi : Ch03.Subgroup.IsPiGroup (({p} : Set ℕ)ᶜ)
        ((Ch03.oPiCore (({p} : Set ℕ)ᶜ) ↥(pElementsSubgroup p G)).map
          (pElementsSubgroup p G).subtype) := by
      intro r hr
      rw [Subgroup.card_map_of_injective (pElementsSubgroup p G).subtype_injective] at hr
      exact Ch03.oPiCore.isPiGroup _ r hr
    have hWG_le : (Ch03.oPiCore (({p} : Set ℕ)ᶜ) ↥(pElementsSubgroup p G)).map
        (pElementsSubgroup p G).subtype ≤ Ch03.oPiCore (({p} : Set ℕ)ᶜ) G :=
      Ch03.Subgroup.IsPiGroup.le_oPiCore hWG_pi
    have hW_le_N : Ch03.oPiCore (({p} : Set ℕ)ᶜ) ↥(pElementsSubgroup p G)
        ≤ (Ch03.oPiCore (({p} : Set ℕ)ᶜ) G).subgroupOf (pElementsSubgroup p G) :=
      Subgroup.map_le_iff_le_comap.mp hWG_le
    -- `[↥U : N] ∣ [↥U : W] ∣ [↥U : K] = p^m`.
    have hN_idx_pow : ∃ j,
        ((Ch03.oPiCore (({p} : Set ℕ)ᶜ) G).subgroupOf (pElementsSubgroup p G)).index = p ^ j := by
      obtain ⟨m, hm⟩ := hK_idx_pow
      have hdvd :
          ((Ch03.oPiCore (({p} : Set ℕ)ᶜ) G).subgroupOf (pElementsSubgroup p G)).index ∣ p ^ m :=
        calc ((Ch03.oPiCore (({p} : Set ℕ)ᶜ) G).subgroupOf (pElementsSubgroup p G)).index
            ∣ (Ch03.oPiCore (({p} : Set ℕ)ᶜ) ↥(pElementsSubgroup p G)).index :=
              Subgroup.index_dvd_of_le hW_le_N
          _ ∣ K.index := Subgroup.index_dvd_of_le hK_le_W
          _ = p ^ m := hm
      obtain ⟨j, _, hj⟩ := (Nat.dvd_prime_pow Fact.out).mp hdvd
      exact ⟨j, hj⟩
    -- `U.map (mk' Op')` is a `p`-group, hence `U ≤ O_{p',p}(G)`.
    have hUmap_pg : IsPGroup p ↥((pElementsSubgroup p G).map
        (QuotientGroup.mk' (Ch03.oPiCore (({p} : Set ℕ)ᶜ) G))) := by
      obtain ⟨j, hj⟩ := hN_idx_pow
      refine IsPGroup.of_card (n := j) ?_
      rw [← index_subgroupOf_eq_card_map (pElementsSubgroup p G)
        (Ch03.oPiCore (({p} : Set ℕ)ᶜ) G)]
      exact hj
    exact le_oPiPrimePiCore_of_quotient_isPGroup hUmap_pg

/-- **BG Lemma 1.21(d)** (mmd L569): `G` has `p`-length one iff the subgroup generated by all
`p`-elements has a normal `p`-complement. -/
theorem hasPLengthOne_iff_hasNormalPComplement_pElementsSubgroup :
    hasPLengthOne p G ↔ Ch05.HasNormalPComplement p ↥(pElementsSubgroup p G) :=
  hasPLengthOne_iff_pElementsSubgroup_le.trans pElementsSubgroup_le_iff_hasNormalPComplement

end

end OddOrder.BG.Ch1
