/-
Copyright (c) 2026 Yawara ISHIDA. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import OddOrder.BG.Ch1_Preliminary.S04_PGroupsSmallRank

/-!
# BG §4 — Proposition 4.11 (Huppert)

> **本** Bender–Glauberman, *Local Analysis for the Odd Order Theorem* §4,
> Proposition 4.11 (Huppert, *Endliche Gruppen I*, Satz III.11.6).

**Prop 4.11**: `p` 素数, `p > 3`, `R` 有限 `p`-群, `|Ω₁(R)| ≤ p²` ⇒ `R` は metacyclic。

`|R|` 帰納 + 前補題 (Lem 4.9 `card_omega1_quotient_le_prime_sq`, Lem 4.5(b)
`isElementaryAbelian_omega1_of_isCyclic_index_prime`, Lem 4.2, Lem 4.1, agemo `Agemo`)。

S04 本体 (`S04_PGroupsSmallRank.lean`) が肥大しているため、Prop 4.11 とその補助補題は
本 leaf に分離 (S04 を凍結し再ビルドを軽く保つ)。namespace は §4 共通の
`OddOrder.BG.Ch1.S04`。
-/

open scoped commutatorElement

namespace OddOrder.BG.Ch1.S04

open OddOrder.GroupTheory

variable {R : Type*} [Group R] [Finite R] {p : ℕ} [Fact p.Prime]

/-- **In a finite `p`-group, a normal subgroup of order `p` is central.**

A nontrivial normal subgroup of a finite `p`-group meets the centre
(`IsPGroup.normal_inf_center_nontrivial`); since `|N| = p` is prime, the nontrivial
subgroup `N ⊓ Z(R)` of `N` must be all of `N`, so `N ≤ Z(R)`.

(BG §4 Prop 4.11 の step 6 で `⟨a,z⟩/⟨aᵖ,z⟩` (位数 `p` の normal) が中心に入ることに使う。) -/
theorem le_center_of_card_eq_prime_of_normal (hR : IsPGroup p R)
    {N : Subgroup R} [N.Normal] (hN : Nat.card N = p) : N ≤ Subgroup.center R := by
  have hp : p.Prime := Fact.out
  haveI hNnt : Nontrivial N :=
    Finite.one_lt_card_iff_nontrivial.mp (by rw [hN]; exact hp.one_lt)
  have hmeet : Nontrivial ((N ⊓ Subgroup.center R : Subgroup R)) :=
    OddOrder.Isaacs.Ch01.IsPGroup.normal_inf_center_nontrivial hR hNnt
  have hle : (N ⊓ Subgroup.center R : Subgroup R) ≤ N := inf_le_left
  have hcard_dvd : Nat.card (N ⊓ Subgroup.center R : Subgroup R) ∣ Nat.card N :=
    Subgroup.card_dvd_of_le hle
  have hcard_ne_one : Nat.card (N ⊓ Subgroup.center R : Subgroup R) ≠ 1 :=
    (Finite.one_lt_card_iff_nontrivial.mpr hmeet).ne'
  have hcard_eq : Nat.card (N ⊓ Subgroup.center R : Subgroup R) = p := by
    rcases (Nat.dvd_prime hp).mp (hN ▸ hcard_dvd) with h1 | hp'
    · exact absurd h1 hcard_ne_one
    · exact hp'
  have heq : (N ⊓ Subgroup.center R : Subgroup R) = N :=
    Subgroup.eq_of_le_of_card_ge hle (by rw [hcard_eq, hN])
  calc N = (N ⊓ Subgroup.center R : Subgroup R) := heq.symm
    _ ≤ Subgroup.center R := inf_le_right

/-- For an abelian finite `p`-group `R`, `|R / Φ(R)| ≤ |Ω₁(R)|`.

The `p`-th power map `φ : x ↦ xᵖ` is a homomorphism (abelian) with `ker φ = Ω₁(R)` (the
`p`-torsion) and `range φ ≤ Φ(R)` (each `xᵖ ∈ Φ(R)`). The first isomorphism theorem gives
`(range φ).index = |ker φ| = |Ω₁(R)|`, and `range φ ≤ Φ(R)` gives `|R/Φ(R)| ≤ (range φ).index`.

(BG §4 Prop 4.11 abelian base case で `|Ω₁(R)| ≤ p²` から `|R/Φ(R)| ≤ p²`、ゆえ rank ≤ 2 を出すのに使う。) -/
theorem card_quotient_frattini_le_card_omega1_of_comm (hR : IsPGroup p R)
    (hcomm : ∀ x y : R, x * y = y * x) :
    Nat.card (R ⧸ frattini R) ≤ Nat.card (Omega R p 1) := by
  letI : CommGroup R := { (inferInstance : Group R) with mul_comm := hcomm }
  -- `φ : x ↦ xᵖ`, a homomorphism since `R` is abelian.
  let φ : R →* R :=
    { toFun := fun x => x ^ p
      map_one' := one_pow p
      map_mul' := fun a b => mul_pow a b p }
  -- `ker φ = Ω₁(R)`.
  have hker : φ.ker = Omega R p 1 := by
    apply le_antisymm
    · intro x hx
      exact Omega.mem_of_pow_eq_one (by rw [pow_one]; exact hx)
    · rw [Omega, Subgroup.closure_le]
      rintro x hx
      rw [SetLike.mem_coe, MonoidHom.mem_ker]
      show x ^ p = 1
      simpa using hx
  -- `range φ ≤ Φ(R)`: each `xᵖ ∈ Φ(R)`.
  have hrange_le : φ.range ≤ frattini R := by
    rintro _ ⟨x, rfl⟩
    exact OddOrder.GroupTheory.IsPGroup.pow_mem_frattini hR x
  -- `(range φ).index = |ker φ|` (first isomorphism + `index_mul_card`).
  have hidx : (φ.range).index = Nat.card φ.ker := by
    have hcong : Nat.card (R ⧸ φ.ker) = Nat.card φ.range :=
      Nat.card_congr (QuotientGroup.quotientKerEquivRange φ).toEquiv
    have hre : Nat.card φ.range = φ.ker.index := hcong.symm
    have e1 : (φ.range).index * Nat.card φ.range = Nat.card R := φ.range.index_mul_card
    have e2 : φ.ker.index * Nat.card φ.ker = Nat.card R := φ.ker.index_mul_card
    have hkpos : 0 < φ.ker.index := Nat.card_pos
    rw [hre] at e1
    have hcancel : φ.ker.index * (φ.range).index = φ.ker.index * Nat.card φ.ker := by
      rw [mul_comm φ.ker.index (φ.range).index, e1, ← e2]
    exact Nat.eq_of_mul_eq_mul_left hkpos hcancel
  -- `|R/Φ| = Φ.index ∣ (range φ).index`, and both positive ⇒ `≤`.
  have hdvd : (frattini R).index ∣ (φ.range).index := Subgroup.index_dvd_of_le hrange_le
  have hrpos : 0 < (φ.range).index := Nat.card_pos
  calc Nat.card (R ⧸ frattini R) = (frattini R).index := rfl
    _ ≤ (φ.range).index := Nat.le_of_dvd hrpos hdvd
    _ = Nat.card φ.ker := hidx
    _ = Nat.card (Omega R p 1) := by rw [hker]

/-- **A finite `p`-group of order `≤ p²` is generated by at most two elements.**

If `Q` is cyclic, one generator suffices. Otherwise `|Q| = p²` (a `p`-group of order `≤ p²`
that is not cyclic cannot have order `1` or `p`); picking `g₁ ≠ 1` and `g₂ ∉ ⟨g₁⟩` gives
`⟨g₁, g₂⟩ ⊋ ⟨g₁⟩`, forcing `|⟨g₁, g₂⟩| = p² = |Q|`, so `⟨g₁, g₂⟩ = Q`. -/
theorem exists_generators_le_two_of_isPGroup_of_card_le_prime_sq {Q : Type*} [Group Q] [Finite Q]
    (hQpg : IsPGroup p Q) (hQ : Nat.card Q ≤ p ^ 2) :
    ∃ T : Finset Q, T.card ≤ 2 ∧ Subgroup.closure (↑T : Set Q) = ⊤ := by
  classical
  have hp : p.Prime := Fact.out
  by_cases hcyc : IsCyclic Q
  · -- cyclic: a single generator.
    obtain ⟨g, hg⟩ := hcyc.exists_generator
    refine ⟨{g}, by simp, ?_⟩
    rw [Finset.coe_singleton, ← Subgroup.zpowers_eq_closure]
    exact top_unique fun x _ => hg x
  · -- not cyclic ⇒ `|Q| = p²`.
    obtain ⟨k, hk⟩ := hQpg.exists_card_eq
    have hk2 : k = 2 := by
      have hkle : k ≤ 2 := by
        have h := hQ; rw [hk] at h; exact (Nat.pow_le_pow_iff_right hp.one_lt).mp h
      interval_cases k
      · refine absurd ?_ hcyc
        have h1 : Nat.card Q = 1 := by rw [hk]; simp
        haveI : Subsingleton Q := (Nat.card_eq_one_iff_unique.mp h1).1
        exact ⟨⟨1, fun x => Subgroup.mem_zpowers_iff.mpr ⟨0, Subsingleton.elim _ _⟩⟩⟩
      · exact absurd (isCyclic_of_prime_card (p := p) (by rw [hk, pow_one])) hcyc
      · rfl
    rw [hk2] at hk
    haveI : Nontrivial Q := by
      rw [← Finite.one_lt_card_iff_nontrivial, hk]
      exact Nat.one_lt_pow (by norm_num) hp.one_lt
    obtain ⟨g₁, hg₁⟩ := exists_ne (1 : Q)
    have hcardz : Nat.card (Subgroup.zpowers g₁) = orderOf g₁ := Nat.card_zpowers g₁
    have hord_dvd : orderOf g₁ ∣ p ^ 2 := by
      rw [← hcardz, ← hk]; exact Subgroup.card_subgroup_dvd_card _
    have hord_ne1 : orderOf g₁ ≠ 1 := by simpa [orderOf_eq_one_iff] using hg₁
    -- `⟨g₁⟩ = ⊤` would make `Q` cyclic; so `⟨g₁⟩ ≠ ⊤`.
    have hz_ne_top : Subgroup.zpowers g₁ ≠ ⊤ := by
      intro htop
      apply hcyc
      refine ⟨⟨g₁, fun x => ?_⟩⟩
      have hx : x ∈ (⊤ : Subgroup Q) := Subgroup.mem_top x
      rwa [← htop] at hx
    -- hence `orderOf g₁ = p` (divides `p²`, `≠ 1`, `≠ p²`).
    have hordp : orderOf g₁ = p := by
      rcases (Nat.dvd_prime_pow hp).mp hord_dvd with ⟨j, hj_le, hje⟩
      interval_cases j
      · simp only [pow_zero] at hje; exact absurd hje hord_ne1
      · rw [hje, pow_one]
      · have hcardeq : Nat.card (Subgroup.zpowers g₁) = Nat.card Q := by rw [hcardz, hje, hk]
        exact absurd (Subgroup.eq_top_of_card_eq (H := Subgroup.zpowers g₁) hcardeq) hz_ne_top
    obtain ⟨g₂, hg₂⟩ : ∃ x, x ∉ Subgroup.zpowers g₁ := by
      by_contra h; push_neg at h
      exact hz_ne_top (top_unique fun x _ => h x)
    refine ⟨{g₁, g₂}, le_trans (Finset.card_insert_le _ _) (by simp), ?_⟩
    -- `K := ⟨g₁,g₂⟩` contains `⟨g₁⟩` (order `p`) and `g₂ ∉ ⟨g₁⟩`, so `|K| ≠ p`; `|K| ∣ p²` and
    -- `p ∣ |K|` then force `|K| = p² = |Q|`, hence `K = ⊤`.
    have hg₁K : g₁ ∈ Subgroup.closure (↑({g₁, g₂} : Finset Q) : Set Q) :=
      Subgroup.subset_closure (by simp)
    have hg₂K : g₂ ∈ Subgroup.closure (↑({g₁, g₂} : Finset Q) : Set Q) :=
      Subgroup.subset_closure (by simp)
    set K : Subgroup Q := Subgroup.closure (↑({g₁, g₂} : Finset Q) : Set Q) with hK
    have hzle : Subgroup.zpowers g₁ ≤ K := by rw [Subgroup.zpowers_le]; exact hg₁K
    have hKdvd : Nat.card K ∣ p ^ 2 := by rw [← hk]; exact Subgroup.card_subgroup_dvd_card _
    have hp_dvd_K : p ∣ Nat.card K := by
      have h := Subgroup.card_dvd_of_le hzle; rwa [hcardz, hordp] at h
    have hKne_p : Nat.card K ≠ p := by
      intro hKp
      have hcard_le : Nat.card K ≤ Nat.card (Subgroup.zpowers g₁) :=
        le_of_eq (by rw [hKp, hcardz, hordp])
      have heq : Subgroup.zpowers g₁ = K := Subgroup.eq_of_le_of_card_ge hzle hcard_le
      exact hg₂ (by rw [heq]; exact hg₂K)
    have hKeq : Nat.card K = p ^ 2 := by
      rcases (Nat.dvd_prime_pow hp).mp hKdvd with ⟨j, hj_le, hje⟩
      interval_cases j
      · rw [hje, pow_zero] at hp_dvd_K; exact absurd (Nat.dvd_one.mp hp_dvd_K) hp.ne_one
      · rw [pow_one] at hje; exact absurd hje hKne_p
      · exact hje
    have hKcardeq : Nat.card K = Nat.card Q := by rw [hKeq, hk]
    exact Subgroup.eq_top_of_card_eq (H := K) hKcardeq

/-- **Burnside basis (rank ≤ 2 form)**: a finite `p`-group `R` with `|R/Φ(R)| ≤ p²` is
generated by at most two elements.

Apply `exists_generators_le_two_of_isPGroup_of_card_le_prime_sq` to the (elementary abelian)
quotient `R/Φ(R)` to get `≤2` generators of `R/Φ(R)`, lift them to `R`, and use that `Φ(R)` is
non-generating (`frattini_nongenerating`). -/
theorem exists_generators_le_two_of_card_quotient_frattini_le_prime_sq
    (hR : IsPGroup p R) (hQ : Nat.card (R ⧸ frattini R) ≤ p ^ 2) :
    ∃ T : Finset R, T.card ≤ 2 ∧ Subgroup.closure (↑T : Set R) = ⊤ := by
  classical
  obtain ⟨U, hUcard, hUgen⟩ :=
    exists_generators_le_two_of_isPGroup_of_card_le_prime_sq (hR.to_quotient (frattini R)) hQ
  -- preimage section `f` of `mk'`.
  let f : (R ⧸ frattini R) → R := fun u => (QuotientGroup.mk'_surjective (frattini R) u).choose
  have hfspec : ∀ u, QuotientGroup.mk' (frattini R) (f u) = u :=
    fun u => (QuotientGroup.mk'_surjective (frattini R) u).choose_spec
  refine ⟨U.image f, le_trans Finset.card_image_le hUcard, ?_⟩
  -- the image of `closure (U.image f)` in `R/Φ` is `closure U = ⊤`.
  have hmap : (Subgroup.closure (↑(U.image f) : Set R)).map (QuotientGroup.mk' (frattini R)) = ⊤ := by
    rw [MonoidHom.map_closure]
    have himg : (QuotientGroup.mk' (frattini R)) '' (↑(U.image f) : Set R) = (↑U : Set _) := by
      rw [Finset.coe_image, Set.image_image]
      ext u
      simp only [Set.mem_image, Finset.mem_coe]
      exact ⟨fun ⟨v, hv, hvu⟩ => by rw [← hvu, hfspec]; exact hv,
             fun hu => ⟨u, hu, hfspec u⟩⟩
    rw [himg]; exact hUgen
  -- hence `closure (U.image f) ⊔ Φ(R) = ⊤`, so by `frattini_nongenerating`, `= ⊤`.
  have hsup : Subgroup.closure (↑(U.image f) : Set R) ⊔ frattini R = ⊤ := by
    have hcm := Subgroup.comap_map_eq (f := QuotientGroup.mk' (frattini R))
      (Subgroup.closure (↑(U.image f) : Set R))
    rw [hmap, Subgroup.comap_top, QuotientGroup.ker_mk'] at hcm
    exact hcm.symm
  exact frattini_nongenerating hsup

/-- **BG Prop 4.11, abelian base case**: an abelian finite `p`-group with `|Ω₁(R)| ≤ p²` is
metacyclic.

`|R/Φ(R)| ≤ |Ω₁(R)| ≤ p²` (`card_quotient_frattini_le_card_omega1_of_comm`), so `R` is generated
by `≤ 2` elements (`exists_generators_le_two_of_card_quotient_frattini_le_prime_sq`). If `R` is
cyclic it is metacyclic; otherwise `R = ⟨a, b⟩` and `⟨a⟩` is a cyclic normal subgroup (abelian)
with `R/⟨a⟩ = ⟨b̄⟩` cyclic. -/
theorem isMetacyclic_of_omega1_card_le_prime_sq_of_comm (hR : IsPGroup p R)
    (hcomm : ∀ x y : R, x * y = y * x) (hΩ : Nat.card (Omega R p 1) ≤ p ^ 2) :
    OddOrder.GroupTheory.IsMetacyclic R := by
  classical
  letI : CommGroup R := { (inferInstance : Group R) with mul_comm := hcomm }
  have hQ : Nat.card (R ⧸ frattini R) ≤ p ^ 2 :=
    le_trans (card_quotient_frattini_le_card_omega1_of_comm hR hcomm) hΩ
  obtain ⟨T, hTcard, hTgen⟩ := exists_generators_le_two_of_card_quotient_frattini_le_prime_sq hR hQ
  by_cases hcyc : IsCyclic R
  · exact OddOrder.GroupTheory.IsMetacyclic.of_isCyclic
  · -- not cyclic ⇒ `T.card = 2` (`≤ 1` generators would make `R` cyclic).
    have hT2 : T.card = 2 := by
      by_contra hne
      apply hcyc
      have hcard1 : T.card ≤ 1 := by omega
      obtain ⟨a, ha⟩ := Finset.card_le_one_iff_subset_singleton.mp hcard1
      have hle : Subgroup.closure (↑T : Set R) ≤ Subgroup.zpowers a := by
        rw [Subgroup.closure_le]
        intro x hx
        have hx' : x ∈ ({a} : Finset R) := ha (Finset.mem_coe.mp hx)
        rw [Finset.mem_singleton] at hx'; subst hx'
        exact Subgroup.mem_zpowers _
      rw [hTgen] at hle
      have htop : Subgroup.zpowers a = ⊤ := top_le_iff.mp hle
      refine ⟨⟨a, fun x => ?_⟩⟩
      have hx : x ∈ (⊤ : Subgroup R) := Subgroup.mem_top x
      rwa [← htop] at hx
    obtain ⟨a, b, hab, hTab⟩ := Finset.card_eq_two.mp hT2
    rw [hTab, Finset.coe_pair] at hTgen
    refine ⟨Subgroup.zpowers a, inferInstance, inferInstance, ?_⟩
    -- `R/⟨a⟩` is cyclic, generated by `mk b`.
    have hmkb_top :
        Subgroup.zpowers (QuotientGroup.mk' (Subgroup.zpowers a) b) = ⊤ := by
      have h1 : (Subgroup.closure ({a, b} : Set R)).map
          (QuotientGroup.mk' (Subgroup.zpowers a)) = ⊤ := by
        rw [hTgen, Subgroup.map_top_of_surjective _ (QuotientGroup.mk'_surjective _)]
      rw [MonoidHom.map_closure, Set.image_pair] at h1
      have hmka : QuotientGroup.mk' (Subgroup.zpowers a) a = 1 := by
        rw [QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]; exact Subgroup.mem_zpowers a
      rw [hmka] at h1
      have hle : Subgroup.closure
            ({1, QuotientGroup.mk' (Subgroup.zpowers a) b} : Set (R ⧸ Subgroup.zpowers a))
          ≤ Subgroup.zpowers (QuotientGroup.mk' (Subgroup.zpowers a) b) := by
        rw [Subgroup.closure_le]
        intro y hy
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hy
        rcases hy with rfl | rfl
        · exact one_mem _
        · exact Subgroup.mem_zpowers _
      rw [h1] at hle
      exact top_le_iff.mp hle
    refine ⟨⟨QuotientGroup.mk' (Subgroup.zpowers a) b, fun x => ?_⟩⟩
    have hx : x ∈ (⊤ : Subgroup (R ⧸ Subgroup.zpowers a)) := Subgroup.mem_top x
    rwa [← hmkb_top] at hx

/-- **BG Prop 4.11, equation (4.7)**: lift a metacyclic quotient `R/⟨z⟩` back to `R`.

Let `R` be a finite `p`-group, `z ∈ Z(R)` of order `p` (so `T := ⟨z⟩` is normal), and suppose
`R ⧸ T` is metacyclic. Then there exist `a, b ∈ R` with, writing `K := ⟨a, z⟩`:

* `(i)`  `K ◁ R`               (`⟨a, z⟩` is normal);
* `(ii)` `R' ⊆ K`              (the commutator subgroup lies in `⟨a, z⟩`);
* `(iii)` `R = ⟨a, b, z⟩`;
* `(iv)` `K / T` is cyclic      (`⟨a, z⟩/⟨z⟩` is cyclic; used by step 6 of Prop 4.11);
* `(v)`  `R / K` is cyclic      (used by step 8 of Prop 4.11).

Unpacking `IsMetacyclic (R ⧸ T)` gives a cyclic normal `N ◁ R/T` with `(R/T)/N` cyclic. Lifting
a generator of `N` along `mk' T` gives `a` with `N = ⟨mk a⟩`; set `K := comap (mk' T) N`. Then
`K ◁ R` (`Normal.comap`), `T ≤ K` (`le_comap_mk'`), `K.map (mk' T) = N`
(`map_comap_eq_self_of_surjective`); and `(ii)` follows from `(R/T)/N` abelian, `(iv)` from
the first isomorphism theorem `K/(T.subgroupOf K) ≃ K.map (mk' T) = N`, `(v)` from Noether's
third isomorphism theorem `(R/T)/N ≃ R/K`. Lifting a generator of `(R/T)/N` twice gives `b`,
whence `R = ⟨a, b, z⟩`. Finally `K = ⟨a, z⟩` is verified by `ext`.

The conclusion is packaged with `K := ⟨a, z⟩` bound existentially together with its `Normal`
instance, so that the cyclic quotients `K/T` and `R/K` are well-formed group quotients; the
defining equation `K = ⟨a, z⟩` is part of the conclusion, so no content of `(4.7)` is lost.

The hypothesis `(Subgroup.zpowers z).Normal` is the typeclass prerequisite for the quotient
`R ⧸ ⟨z⟩` to be a group; it is a direct consequence of `z ∈ Z(R)` (which the caller, the
induction body of Prop 4.11, has at hand) and is *not* hoisted hard content.

This is the `(4.7)` step of the non-abelian induction of Prop 4.11 (mmd L1560-1564). -/
theorem exists_metacyclic_lift_of_isMetacyclic_quotient_center_prime (hR : IsPGroup p R)
    {z : R} [(Subgroup.zpowers z).Normal] (hz : z ∈ Subgroup.center R) (hzp : orderOf z = p)
    (hmeta : OddOrder.GroupTheory.IsMetacyclic (R ⧸ Subgroup.zpowers z)) :
    ∃ (a b : R) (K : Subgroup R), ∃ _ : K.Normal,
      K = Subgroup.closure ({a, z} : Set R) ∧
      _root_.commutator R ≤ K ∧
      Subgroup.closure ({a, b, z} : Set R) = ⊤ ∧
      IsCyclic (K ⧸ (Subgroup.zpowers z).subgroupOf K) ∧
      IsCyclic (R ⧸ K) := by
  classical
  set T : Subgroup R := Subgroup.zpowers z with hT
  -- ⟨STEP 1⟩ Unpack `IsMetacyclic (R ⧸ T)`.
  obtain ⟨N, hNnorm, hNcyc, hQcyc⟩ := hmeta
  haveI := hNnorm; haveI := hNcyc; haveI := hQcyc
  -- ⟨STEP 2⟩ A generator `ngen` of `N`, lifted to `a ∈ R`; so `N = ⟨mk' T a⟩`.
  obtain ⟨ngen, hngen⟩ := hNcyc.exists_generator
  obtain ⟨a, ha⟩ := QuotientGroup.mk'_surjective T ngen
  have haN : QuotientGroup.mk' T a ∈ N := ha ▸ ngen.2
  have hNeq : N = Subgroup.zpowers (QuotientGroup.mk' T a) := by
    apply le_antisymm
    · -- every `x ∈ N` is a power of the generator `ngen`, hence of `mk' T a = ↑ngen`.
      intro x hx
      obtain ⟨k, hk⟩ := (Subgroup.mem_zpowers_iff).mp (hngen ⟨x, hx⟩)
      rw [Subgroup.mem_zpowers_iff]
      refine ⟨k, ?_⟩
      -- `(mk' T a)^k = (N.subtype ngen)^k = N.subtype (ngen^k) = N.subtype ⟨x,hx⟩ = x`.
      have hsub : N.subtype (ngen ^ k) = x := by rw [hk]; rfl
      rwa [map_zpow, Subgroup.coe_subtype, ← ha] at hsub
    · rw [Subgroup.zpowers_le]; exact haN
  -- ⟨STEP 3⟩ `K := comap (mk' T) N`; normal, contains `T`, and maps onto `N`.
  set K : Subgroup R := N.comap (QuotientGroup.mk' T) with hK
  haveI hKnorm : K.Normal := hNnorm.comap _
  have hTleK : T ≤ K := QuotientGroup.le_comap_mk' T N
  have hKmap : K.map (QuotientGroup.mk' T) = N :=
    Subgroup.map_comap_eq_self_of_surjective (QuotientGroup.mk'_surjective T) N
  -- ⟨STEP 4 = (ii)⟩ `commutator R ≤ K`.
  have hcommQ : _root_.commutator (R ⧸ T) ≤ N :=
    Subgroup.Normal.quotient_commutative_iff_commutator_le.mp inferInstance
  have hcommR : _root_.commutator R ≤ K := by
    rw [hK, ← Subgroup.map_le_iff_le_comap]
    calc (_root_.commutator R).map (QuotientGroup.mk' T)
        = _root_.commutator (R ⧸ T) := by
          rw [_root_.commutator_def, _root_.commutator_def, Subgroup.map_commutator,
              Subgroup.map_top_of_surjective _ (QuotientGroup.mk'_surjective T)]
      _ ≤ N := hcommQ
  -- ⟨STEP 5 = (iii)⟩ `R = ⟨a, b, z⟩`, with `b` a two-step lift of a generator of `(R/T)/N`.
  obtain ⟨qgen, hqgen⟩ := hQcyc.exists_generator
  obtain ⟨bq, hbq⟩ := QuotientGroup.mk'_surjective N qgen
  obtain ⟨b, hb⟩ := QuotientGroup.mk'_surjective T bq
  -- (a) `closure {mk' T a, mk' T b} = ⊤` in `R ⧸ T`.
  have hmkclosure :
      Subgroup.closure ({QuotientGroup.mk' T a, QuotientGroup.mk' T b} : Set (R ⧸ T)) = ⊤ := by
    set C : Subgroup (R ⧸ T) :=
      Subgroup.closure ({QuotientGroup.mk' T a, QuotientGroup.mk' T b} : Set (R ⧸ T)) with hC
    -- `mk' T a ∈ N`, so `N = ⟨mk' T a⟩ ≤ C`.
    have hNleC : N ≤ C := by
      rw [hNeq, Subgroup.zpowers_le, hC]
      exact Subgroup.subset_closure (by simp)
    -- The image of `C` under `mk' N` is `⊤` (it contains the generator `qgen` of `(R/T)/N`).
    have hmapN : C.map (QuotientGroup.mk' N) = ⊤ := by
      rw [hC, MonoidHom.map_closure, Set.image_pair]
      -- `mk' N (mk' T a) = 1` (since `mk' T a ∈ N`), `mk' N (mk' T b) = qgen`.
      have hmka1 : QuotientGroup.mk' N (QuotientGroup.mk' T a) = 1 := by
        rw [QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]; exact haN
      have hmkbq : QuotientGroup.mk' N (QuotientGroup.mk' T b) = qgen := by
        rw [hb, hbq]
      rw [hmka1, hmkbq]
      -- `closure {1, qgen} ⊇ zpowers qgen = ⊤`.
      refine top_le_iff.mp (le_trans (fun y _ => hqgen y) ?_)
      rw [Subgroup.zpowers_le]
      exact Subgroup.subset_closure (Set.mem_insert_of_mem _ rfl)
    -- `C ⊔ N = comap (mk' N) (map (mk' N) C) = comap ⊤ = ⊤`, and `N ≤ C`, so `C = ⊤`.
    have hsupN : C ⊔ N = ⊤ := by
      have hcm := Subgroup.comap_map_eq (f := QuotientGroup.mk' N) C
      rw [hmapN, Subgroup.comap_top, QuotientGroup.ker_mk'] at hcm
      exact hcm.symm
    rw [sup_eq_left.mpr hNleC] at hsupN
    rw [hC] at hsupN; exact hsupN
  -- (b) Lift to `R`: `closure {a, b, z} = ⊤`.
  have hiii : Subgroup.closure ({a, b, z} : Set R) = ⊤ := by
    have hmap3 : (Subgroup.closure ({a, b, z} : Set R)).map (QuotientGroup.mk' T) = ⊤ := by
      rw [MonoidHom.map_closure, Set.image_insert_eq, Set.image_insert_eq, Set.image_singleton]
      have hmkz : QuotientGroup.mk' T z = 1 := by
        rw [QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff, hT]; exact Subgroup.mem_zpowers z
      rw [hmkz]
      refine top_le_iff.mp ?_
      rw [← hmkclosure]
      apply Subgroup.closure_mono
      intro x hx
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx ⊢
      tauto
    have hsup : Subgroup.closure ({a, b, z} : Set R) ⊔ T = ⊤ := by
      have hcm := Subgroup.comap_map_eq (f := QuotientGroup.mk' T)
        (Subgroup.closure ({a, b, z} : Set R))
      rw [hmap3, Subgroup.comap_top, QuotientGroup.ker_mk'] at hcm; exact hcm.symm
    have hzin : z ∈ Subgroup.closure ({a, b, z} : Set R) := Subgroup.subset_closure (by simp)
    have hTin : T ≤ Subgroup.closure ({a, b, z} : Set R) := by
      rw [hT, Subgroup.zpowers_le]; exact hzin
    rw [sup_eq_left.mpr hTin] at hsup; exact hsup
  -- ⟨STEP 6 = (iv)⟩ `K / (T.subgroupOf K)` is cyclic (`≅ K.map (mk' T) = N`).
  haveI hiv : IsCyclic (K ⧸ (T.subgroupOf K)) := by
    -- `φ := mk' T ∘ K.subtype : K →* R/T`, with `range φ = K.map (mk' T) = N` and
    -- `ker φ = T.subgroupOf K`.
    set φ : K →* (R ⧸ T) := (QuotientGroup.mk' T).comp K.subtype with hφ
    have hrange : φ.range = N := by
      rw [hφ, MonoidHom.range_comp, Subgroup.range_subtype]; exact hKmap
    have hkereq : φ.ker = T.subgroupOf K := by
      rw [hφ, ← MonoidHom.comap_ker, QuotientGroup.ker_mk']; rfl
    haveI : IsCyclic ↥φ.range := by rw [hrange]; exact hNcyc
    haveI : IsCyclic (K ⧸ φ.ker) :=
      isCyclic_of_surjective (QuotientGroup.quotientKerEquivRange φ).symm.toMonoidHom
        (QuotientGroup.quotientKerEquivRange φ).symm.surjective
    haveI : (T.subgroupOf K).Normal := (inferInstance : T.Normal).subgroupOf K
    -- transport `IsCyclic (K ⧸ φ.ker)` along the equality `φ.ker = T.subgroupOf K`.
    exact isCyclic_of_surjective (QuotientGroup.quotientMulEquivOfEq hkereq).toMonoidHom
      (QuotientGroup.quotientMulEquivOfEq hkereq).surjective
  -- ⟨STEP 7 = (v)⟩ `R / K` is cyclic (`≅ (R/T)/N`).
  haveI hv : IsCyclic (R ⧸ K) := by
    -- `(R/T)/N ≃ (R/T)/(K.map (mk' T)) ≃ R/K`, and the first is cyclic.
    have e : ((R ⧸ T) ⧸ N) ≃* (R ⧸ K) :=
      (QuotientGroup.quotientMulEquivOfEq hKmap.symm).trans
        (QuotientGroup.quotientQuotientEquivQuotient T K hTleK)
    exact isCyclic_of_surjective e e.surjective
  -- ⟨STEP 8⟩ Identify `K = closure {a, z}` by `ext`.
  have hKeq : K = Subgroup.closure ({a, z} : Set R) := by
    apply le_antisymm
    · -- `x ∈ K = comap (mk' T) N ⟹ mk' T x ∈ N = ⟨mk' T a⟩ ⟹ x ∈ ⟨a, z⟩`.
      intro x hx
      rw [hK, Subgroup.mem_comap, hNeq, Subgroup.mem_zpowers_iff] at hx
      obtain ⟨k, hk⟩ := hx
      -- `mk' T x = (mk' T a)^k = mk' T (a^k)`, so `x * (a^k)⁻¹ ∈ ker (mk' T) = T = ⟨z⟩`.
      have hxa : QuotientGroup.mk' T (x * (a ^ k)⁻¹) = 1 := by
        rw [map_mul, map_inv, map_zpow, hk, mul_inv_cancel]
      rw [QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff, hT,
        Subgroup.mem_zpowers_iff] at hxa
      obtain ⟨m, hm⟩ := hxa
      -- `x = z^m * a^k ∈ ⟨a, z⟩`.
      have hzmem : z ∈ Subgroup.closure ({a, z} : Set R) :=
        Subgroup.subset_closure (by simp)
      have hamem : a ∈ Subgroup.closure ({a, z} : Set R) :=
        Subgroup.subset_closure (by simp)
      have hxeq : x = z ^ m * a ^ k := by
        rw [hm]; group
      rw [hxeq]
      exact mul_mem ((Subgroup.closure ({a, z} : Set R)).zpow_mem hzmem m)
        ((Subgroup.closure ({a, z} : Set R)).zpow_mem hamem k)
    · -- `a, z ∈ K`.
      rw [Subgroup.closure_le]
      intro x hx
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
      rcases hx with rfl | rfl
      · rw [SetLike.mem_coe, hK, Subgroup.mem_comap]; exact haN
      · rw [SetLike.mem_coe]; exact hTleK (by rw [hT]; exact Subgroup.mem_zpowers _)
  exact ⟨a, b, K, hKnorm, hKeq, hcommR, hiii, hiv, hv⟩

/-- **BG Prop 4.11, step 8** (mmd L1584-1586): a finite `p`-group `R` (`p` odd) with
`|Ω₁(R)| ≤ p²` whose commutator subgroup `R'` is cyclic is metacyclic.

This is the closing step of the non-abelian induction of Prop 4.11, stated as a clean
stand-alone lemma (the `a, b, z` setup of the induction is not needed). The general form
subsumes the abelian case (`R' = ⊥` is cyclic), so it faithfully captures the BG argument
without weakening the conclusion.

Proof (following BG): if `R` is cyclic it is metacyclic. Otherwise let `S` be a cyclic
subgroup maximal subject to `R' ⊆ S` (exists by finiteness, with witness `R'` itself,
which is cyclic by hypothesis). Since `R' ⊆ S`, `S ⊴ R`, and `S ≠ R` as `R` is not cyclic.
For *any* `S₁` with `S ≤ S₁` and `|S₁/S| = p` (i.e. `S₁ = comap (mk' S) P̄` for an order-`p`
subgroup `P̄ ≤ R/S`): `S₁` is not cyclic (else `S = S₁` by maximality, contradicting
`S.relIndex S₁ = p ≠ 1`), so by Lemma 4.5(b) `|Ω₁(S₁)| = p²`. Pushing `Ω₁(↥S₁)` into `R` and
squeezing against `|Ω₁(R)| ≤ p²` gives `Ω₁(S₁) = Ω₁(R)` (so `|Ω₁(R)| = p²`), hence
`Ω₁(R) ≤ S₁` and `S₁ = S ⊔ Ω₁(R)` (a tower-`relIndex` computation, using `Ω₁(R) ⊄ S`). As
`S ⊔ Ω₁(R)` does not depend on `P̄`, every order-`p` subgroup of `R/S` is
`(S ⊔ Ω₁(R)).map (mk' S)`, so `R/S` has a unique subgroup of order `p` and is cyclic
(`isCyclic_of_subgroups_card_prime_unique_of_odd`). Then `⟨S, R/S⟩` witnesses metacyclicity. -/
theorem isMetacyclic_of_isCyclic_commutator_of_card_omega1_le
    (hR : IsPGroup p R) (hp_odd : Odd p)
    (hΩ : Nat.card (Omega R p 1) ≤ p ^ 2)
    (hcyc : IsCyclic (_root_.commutator R)) :
    OddOrder.GroupTheory.IsMetacyclic R := by
  classical
  have hp : p.Prime := Fact.out
  -- ⟨STEP 0⟩ If `R` is cyclic, it is metacyclic; otherwise work with `hRcyc : ¬ IsCyclic R`.
  by_cases hRcyc : IsCyclic R
  · haveI := hRcyc
    exact OddOrder.GroupTheory.IsMetacyclic.of_isCyclic
  -- ⟨STEP 1⟩ Maximal cyclic `S` subject to `R' ⊆ S`, from finiteness (witness = `R'`).
  obtain ⟨S, hSsub, hSmax⟩ :=
    Finite.exists_le_maximal
      (p := fun H : Subgroup R => IsCyclic ↥H ∧ _root_.commutator R ≤ H) ⟨hcyc, le_refl _⟩
  have hScyc : IsCyclic ↥S := hSmax.1.1
  have hRprime_le : _root_.commutator R ≤ S := hSmax.1.2
  haveI := hScyc
  -- ⟨STEP 2⟩ `S ⊴ R` (since `R' ⊆ S`) and `S ≠ ⊤` (since `R` is not cyclic).
  have hSnorm : S.Normal := OddOrder.Isaacs.Ch06.normal_of_commutator_le hRprime_le
  haveI := hSnorm
  -- `R/S` is a `p`-group.
  haveI hQpg : IsPGroup p (R ⧸ S) := hR.to_quotient S
  -- ⟨STEP 5⟩ Uniqueness of order-`p` subgroups of `R/S` ⇒ `R/S` cyclic.
  have hRScyc : IsCyclic (R ⧸ S) := by
    refine OddOrder.Isaacs.Ch06.isCyclic_of_subgroups_card_prime_unique_of_odd hQpg hp_odd ?_
    -- For each order-`p` subgroup `P̄ ≤ R/S`, its preimage `S₁ = comap (mk' S) P̄` equals
    -- the fixed subgroup `S ⊔ Ω₁(R)`; hence `P̄ = (S ⊔ Ω₁(R)).map (mk' S)` for every `P̄`.
    have key : ∀ P : Subgroup (R ⧸ S), Nat.card P = p →
        Subgroup.comap (QuotientGroup.mk' S) P = S ⊔ Omega R p 1 := by
      intro P hP
      set S₁ : Subgroup R := Subgroup.comap (QuotientGroup.mk' S) P with hS₁_def
      have hS_le_S₁ : S ≤ S₁ := QuotientGroup.le_comap_mk' S P
      have hS₁pg : IsPGroup p S₁ := hR.to_subgroup S₁
      -- (5b) `S.relIndex S₁ = p`.
      have hSrel : S.relIndex S₁ = p := by
        have hker : S = (QuotientGroup.mk' S).ker := (QuotientGroup.ker_mk' S).symm
        rw [hker, Subgroup.relIndex_ker, hS₁_def,
          Subgroup.map_comap_eq_self_of_surjective (QuotientGroup.mk'_surjective S)]
        exact hP
      -- (5c) `S₁` is not cyclic: else maximality forces `S = S₁`, but `relIndex = p ≠ 1`.
      have hS₁nc : ¬ IsCyclic ↥S₁ := by
        intro hS₁cyc
        have hle : S₁ ≤ S := hSmax.2 ⟨hS₁cyc, hRprime_le.trans hS_le_S₁⟩ hS_le_S₁
        have hSeqS₁ : S = S₁ := le_antisymm hS_le_S₁ hle
        rw [← hSeqS₁, Subgroup.relIndex_self] at hSrel
        exact hp.one_lt.ne' hSrel.symm
      -- (5d) `S.subgroupOf S₁` is cyclic (`≅ ↥S`) of index `p`; apply Lemma 4.5(b) to `↥S₁`.
      have hSsub_cyc : IsCyclic ↥(S.subgroupOf S₁) :=
        isCyclic_of_surjective (Subgroup.subgroupOfEquivOfLe hS_le_S₁).symm.toMonoidHom
          (Subgroup.subgroupOfEquivOfLe hS_le_S₁).symm.surjective
      have hSsub_idx : (S.subgroupOf S₁).index = p := hSrel
      obtain ⟨_hΩS₁_ea, hΩS₁_card⟩ :=
        isElementaryAbelian_omega1_of_isCyclic_index_prime hS₁pg hp_odd hS₁nc hSsub_cyc hSsub_idx
      -- (5e) `(Ω₁ ↥S₁).map S₁.subtype ≤ Ω₁(R)` and has order `p²`; squeeze with `hΩ` ⇒ equal.
      have hΩmap_le : (Omega (↥S₁) p 1).map S₁.subtype ≤ Omega R p 1 := by
        rw [Subgroup.map_le_iff_le_comap, Omega, Subgroup.closure_le]
        rintro ⟨g, hgS₁⟩ (hg : (⟨g, hgS₁⟩ : ↥S₁) ^ (p ^ 1) = 1)
        change (⟨g, hgS₁⟩ : ↥S₁) ∈ Subgroup.comap S₁.subtype (Omega R p 1)
        rw [Subgroup.mem_comap]
        refine Omega.mem_of_pow_eq_one ?_
        rw [pow_one]
        have hval := congrArg (Subgroup.subtype S₁) hg
        rw [map_pow, pow_one, map_one] at hval
        simpa using hval
      have hΩmap_card : Nat.card ((Omega (↥S₁) p 1).map S₁.subtype) = p ^ 2 := by
        rw [Subgroup.card_map_of_injective S₁.subtype_injective, hΩS₁_card]
      have hΩeq : (Omega (↥S₁) p 1).map S₁.subtype = Omega R p 1 :=
        Subgroup.eq_of_le_of_card_ge hΩmap_le (by rw [hΩmap_card]; exact hΩ)
      -- `|Ω₁(R)| = p²` (consequence of the squeeze) and `Ω₁(R) ≤ S₁`.
      have hΩR_card : Nat.card (Omega R p 1) = p ^ 2 := by rw [← hΩeq, hΩmap_card]
      have hΩR_le_S₁ : Omega R p 1 ≤ S₁ := by rw [← hΩeq]; exact Subgroup.map_subtype_le _
      -- `Ω₁(R)` is elementary abelian (image of the e.a. `Ω₁ ↥S₁`), so every element is
      -- `p`-torsion.
      have hΩR_ea : (Omega R p 1).IsElementaryAbelian p :=
        hΩeq ▸ _hΩS₁_ea.map S₁.subtype_injective
      have hΩR_pow : ∀ g : R, g ∈ Omega R p 1 → g ^ p = 1 := by
        intro g hg
        have := hΩR_ea.pow_eq_one ⟨g, hg⟩
        simpa using congrArg (Subtype.val) this
      -- `Ω₁(R) ⊄ S`: else `Ω₁(R) ≤ (Ω₁ ↥S).map subtype`, forcing `p² = |Ω₁(R)| ≤ |Ω₁ ↥S| = p`.
      have hΩR_not_le_S : ¬ Omega R p 1 ≤ S := by
        intro hle
        -- `S` is nontrivial (it contains the nontrivial `Ω₁(R)`, of order `p²`).
        haveI hS_nt : Nontrivial ↥S := by
          rw [← Finite.one_lt_card_iff_nontrivial]
          have h1 : Nat.card (Omega R p 1) ≤ Nat.card ↥S := Subgroup.card_le_of_le hle
          have h2 : 1 < Nat.card (Omega R p 1) := by
            rw [hΩR_card]; exact Nat.one_lt_pow (by norm_num) hp.one_lt
          omega
        -- each generator of `Ω₁(R)` lies in `(Ω₁ ↥S).map S.subtype`.
        have hΩR_le_ΩS : Omega R p 1 ≤ (Omega (↥S) p 1).map S.subtype := by
          intro x hx
          have hxS : x ∈ S := hle hx
          rw [Subgroup.mem_map]
          refine ⟨⟨x, hxS⟩, ?_, rfl⟩
          refine Omega.mem_of_pow_eq_one ?_
          rw [pow_one]
          ext
          rw [SubmonoidClass.coe_pow, Subgroup.coe_mk, OneMemClass.coe_one]
          exact hΩR_pow x hx
        have hΩS_card : Nat.card (Omega ↥S p 1) = p :=
          card_omega1_eq_prime_of_isCyclic (hR.to_subgroup S)
        have hΩSmap_card : Nat.card ((Omega ↥S p 1).map S.subtype) = p := by
          rw [Subgroup.card_map_of_injective S.subtype_injective, hΩS_card]
        have hle_card : Nat.card (Omega R p 1) ≤ p := by
          calc Nat.card (Omega R p 1)
              ≤ Nat.card ((Omega ↥S p 1).map S.subtype) := Subgroup.card_le_of_le hΩR_le_ΩS
            _ = p := hΩSmap_card
        rw [hΩR_card] at hle_card
        -- `p² ≤ p` is false for `p ≥ 2`.
        nlinarith [hp.two_le]
      -- (5f) `S₁ = S ⊔ Ω₁(R)` via a tower `relIndex` computation.
      have hSup_le : S ⊔ Omega R p 1 ≤ S₁ := sup_le hS_le_S₁ hΩR_le_S₁
      have hS_le_sup : S ≤ S ⊔ Omega R p 1 := le_sup_left
      have htower : S.relIndex (S ⊔ Omega R p 1) * (S ⊔ Omega R p 1).relIndex S₁ = p := by
        rw [Subgroup.relIndex_mul_relIndex S (S ⊔ Omega R p 1) S₁ hS_le_sup hSup_le]; exact hSrel
      have hfirst_ne_one : S.relIndex (S ⊔ Omega R p 1) ≠ 1 := by
        rw [Ne, Subgroup.relIndex_eq_one]
        intro hle
        exact hΩR_not_le_S (le_trans le_sup_right hle)
      have hsecond_eq_one : (S ⊔ Omega R p 1).relIndex S₁ = 1 := by
        -- `a * b = p` prime with `a ≠ 1` forces `a = p`, hence `b = 1`.
        set a := S.relIndex (S ⊔ Omega R p 1)
        set b := (S ⊔ Omega R p 1).relIndex S₁
        have hadvd : a ∣ p := Dvd.intro_left b (by rw [mul_comm]; exact htower)
        have ha_eq_p : a = p := (hp.eq_one_or_self_of_dvd a hadvd).resolve_left hfirst_ne_one
        rw [ha_eq_p] at htower
        have hp_pos : 0 < p := hp.pos
        have : p * b = p * 1 := by rw [mul_one]; exact htower
        exact Nat.eq_of_mul_eq_mul_left hp_pos this
      have hge : S₁ ≤ S ⊔ Omega R p 1 := Subgroup.relIndex_eq_one.mp hsecond_eq_one
      exact le_antisymm hge hSup_le
    -- Close uniqueness: both order-`p` subgroups map back to the same `comap`.
    intro P Q hP hQ
    have hPc := key P hP
    have hQc := key Q hQ
    have hPm : (Subgroup.comap (QuotientGroup.mk' S) P).map (QuotientGroup.mk' S) = P :=
      Subgroup.map_comap_eq_self_of_surjective (QuotientGroup.mk'_surjective S) P
    have hQm : (Subgroup.comap (QuotientGroup.mk' S) Q).map (QuotientGroup.mk' S) = Q :=
      Subgroup.map_comap_eq_self_of_surjective (QuotientGroup.mk'_surjective S) Q
    rw [← hPm, ← hQm, hPc, hQc]
  -- ⟨STEP 7⟩ `⟨S, R/S⟩` witnesses metacyclicity.
  exact ⟨S, hSnorm, hScyc, hRScyc⟩

end OddOrder.BG.Ch1.S04
