/-
Copyright (c) 2026 Yawara ISHIDA. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.BG.Ch1_Preliminary.S04f_Omega1

/-!
# BG §4F — Blackburn: the noncentral-Ω₁ opening layer

Split from the parent file (issue 0149, the longFile-1500 campaign); the parent
imports this leaf, so downstream imports are unchanged.
-/

open scoped Pointwise commutatorElement

namespace OddOrder.BG.Ch1.S04
open OddOrder.GroupTheory
open OddOrder.Isaacs.Ch03 (IsAInvariant)
open OddOrder.Isaacs.Ch03.IsAInvariant
  (quotientMulAutHom quotientMulAutHom_apply)
open OddOrder.BG.Ch1_Preliminary (isAInvariant_map_subtype_of_restrict
  isAInvariant_subgroupOf_restrict)

section BlackburnClassification

/-- Blackburn 4.16 Case B-2: after lifting the Maschke complement, the ambient
group is generated by `S = Ω₁(R)` and the image of `X ≤ C_R(T)`. -/
theorem blackburn_noncentral_omega1_sup_centralizer_complement_eq_top
    {R : Type*} [Group R] [Finite R] {p : ℕ} [Fact p.Prime]
    (hR : IsPGroup p R)
    (hT_facts :
      let S : Subgroup R := Omega R p 1
      let T : Subgroup R := ⁅S, (⊤ : Subgroup R)⁆
      (Subgroup.center S).map S.subtype < T ∧ T < S ∧ Nat.card T = p ^ 2)
    (hT_elem :
      let S : Subgroup R := Omega R p 1
      let T : Subgroup R := ⁅S, (⊤ : Subgroup R)⁆
      T.IsElementaryAbelian p)
    {X : Subgroup (Subgroup.centralizer ((⁅Omega R p 1, (⊤ : Subgroup R)⁆ : Subgroup R) : Set R))}
    (hC_le_X :
      let S : Subgroup R := Omega R p 1
      let T : Subgroup R := ⁅S, (⊤ : Subgroup R)⁆
      let C : Subgroup R := Subgroup.centralizer (S : Set R)
      let D : Subgroup R := Subgroup.centralizer (T : Set R)
      C.subgroupOf D ≤ X)
    (hX_sup_T :
      let S : Subgroup R := Omega R p 1
      let T : Subgroup R := ⁅S, (⊤ : Subgroup R)⁆
      let C : Subgroup R := Subgroup.centralizer (S : Set R)
      let D : Subgroup R := Subgroup.centralizer (T : Set R)
      let hCD_normal : (C.subgroupOf D).Normal :=
        (blackburn_noncentral_centralizer_normalities (R := R) (p := p)).2.2
      letI : (C.subgroupOf D).Normal := hCD_normal
      X.map (QuotientGroup.mk' (C.subgroupOf D)) ⊔
          (T.subgroupOf D).map (QuotientGroup.mk' (C.subgroupOf D)) =
        Omega (D ⧸ C.subgroupOf D) p 1) :
    let S : Subgroup R := Omega R p 1
    let T : Subgroup R := ⁅S, (⊤ : Subgroup R)⁆
    let D : Subgroup R := Subgroup.centralizer (T : Set R)
    S ⊔ X.map D.subtype = ⊤ := by
  dsimp at hT_facts hT_elem hC_le_X hX_sup_T ⊢
  let S : Subgroup R := Omega R p 1
  let T : Subgroup R := ⁅S, (⊤ : Subgroup R)⁆
  let D : Subgroup R := Subgroup.centralizer (T : Set R)
  have hrelations := blackburn_noncentral_centralizer_relations hT_facts hT_elem
  have hT_le_D : T ≤ D := hrelations.2.1
  have hT_le_S : T ≤ S := hT_facts.2.1.le
  have hSD_top := blackburn_noncentral_omega1_sup_centralizer_eq_top hR hT_facts hT_elem
  have hXT_top :=
    blackburn_noncentral_centralizer_complement_sup_commutator_eq_top
      hT_facts hT_elem hC_le_X hX_sup_T
  have hXRT_eq_D : X.map D.subtype ⊔ T = D := by
    have hmap : (X ⊔ T.subgroupOf D).map D.subtype = D := by
      rw [hXT_top, ← MonoidHom.range_eq_map, D.range_subtype]
    rwa [Subgroup.map_sup, Subgroup.map_subgroupOf_eq_of_le hT_le_D] at hmap
  have hD_le_SX : D ≤ S ⊔ X.map D.subtype := by
    intro r hrD
    have hrXRT : r ∈ X.map D.subtype ⊔ T := by
      rwa [hXRT_eq_D]
    exact (sup_le le_sup_right (hT_le_S.trans le_sup_left)) hrXRT
  apply eq_top_iff.mpr
  intro r _
  have hrSD : r ∈ S ⊔ D := by
    rw [hSD_top]
    exact Subgroup.mem_top r
  exact (sup_le le_sup_left hD_le_SX) hrSD

/-- Blackburn 4.16 Case B-2 Maschke step for `D/C`.

This packages the application of `exists_aInvariant_complement_in_omega1_quotient` to
`D = C_R(T)` and `C = C_R(S)`.  The only substantial BG input left as an assumption is that
`D/C` is abelian; the divisibility, coprimality, invariance, and `Ω₁` image hypotheses are
assembled from the earlier B-2 support lemmas. -/
theorem blackburn_noncentral_exists_centralizer_quotient_complement
    {R : Type*} [Group R] [Finite R] {p : ℕ} [Fact p.Prime]
    {A : Type*} [Group A] [Finite A] {φ : A →* MulAut R}
    (hcop : Nat.Coprime (Nat.card A) (Nat.card R))
    (hT_facts :
      let S : Subgroup R := Omega R p 1
      let T : Subgroup R := ⁅S, (⊤ : Subgroup R)⁆
      (Subgroup.center S).map S.subtype < T ∧ T < S ∧ Nat.card T = p ^ 2)
    (hT_elem :
      let S : Subgroup R := Omega R p 1
      let T : Subgroup R := ⁅S, (⊤ : Subgroup R)⁆
      T.IsElementaryAbelian p)
    (hD_quot_ab :
      let S : Subgroup R := Omega R p 1
      let T : Subgroup R := ⁅S, (⊤ : Subgroup R)⁆
      let C : Subgroup R := Subgroup.centralizer (S : Set R)
      let D : Subgroup R := Subgroup.centralizer (T : Set R)
      let hCD_normal : (C.subgroupOf D).Normal :=
        (blackburn_noncentral_centralizer_normalities (R := R) (p := p)).2.2
      letI : (C.subgroupOf D).Normal := hCD_normal
      ∀ x y : D ⧸ C.subgroupOf D, x * y = y * x) :
    let S : Subgroup R := Omega R p 1
    let T : Subgroup R := ⁅S, (⊤ : Subgroup R)⁆
    let C : Subgroup R := Subgroup.centralizer (S : Set R)
    let D : Subgroup R := Subgroup.centralizer (T : Set R)
    let hInv := blackburn_noncentral_operator_invariances (p := p) (φ := φ)
    let hD_inv : IsAInvariant φ D := hInv.2.2.2
    let hCD_normal : (C.subgroupOf D).Normal :=
      (blackburn_noncentral_centralizer_normalities (R := R) (p := p)).2.2
    letI : (C.subgroupOf D).Normal := hCD_normal
    ∃ X : Subgroup D,
      C.subgroupOf D ≤ X ∧ IsAInvariant hD_inv.restrict X ∧
      X.map (QuotientGroup.mk' (C.subgroupOf D)) ≤ Omega (D ⧸ C.subgroupOf D) p 1 ∧
      X.map (QuotientGroup.mk' (C.subgroupOf D)) ⊓
          (T.subgroupOf D).map (QuotientGroup.mk' (C.subgroupOf D)) = ⊥ ∧
      X.map (QuotientGroup.mk' (C.subgroupOf D)) ⊔
          (T.subgroupOf D).map (QuotientGroup.mk' (C.subgroupOf D)) =
        Omega (D ⧸ C.subgroupOf D) p 1 := by
  dsimp at hT_facts hT_elem hD_quot_ab ⊢
  let S : Subgroup R := Omega R p 1
  let T : Subgroup R := ⁅S, (⊤ : Subgroup R)⁆
  let C : Subgroup R := Subgroup.centralizer (S : Set R)
  let D : Subgroup R := Subgroup.centralizer (T : Set R)
  have hCD_norms := blackburn_noncentral_centralizer_normalities (R := R) (p := p)
  have hCD_normal : (C.subgroupOf D).Normal := hCD_norms.2.2
  have hInv := blackburn_noncentral_operator_invariances (p := p) (φ := φ)
  have hT_inv : IsAInvariant φ T := hInv.2.1
  have hC_inv : IsAInvariant φ C := hInv.2.2.1
  have hD_inv : IsAInvariant φ D := hInv.2.2.2
  have hpD : p ∣ Nat.card D :=
    blackburn_noncentral_prime_dvd_centralizer_card hT_facts hT_elem
  have hcopD : Nat.Coprime (Nat.card A) (Nat.card D) :=
    hcop.coprime_dvd_right (Subgroup.card_subgroup_dvd_card D)
  have hCsub_inv : IsAInvariant hD_inv.restrict (C.subgroupOf D) :=
    isAInvariant_subgroupOf_restrict hD_inv hC_inv
  have hTsub_inv : IsAInvariant hD_inv.restrict (T.subgroupOf D) :=
    isAInvariant_subgroupOf_restrict hD_inv hT_inv
  have hTΩ : (T.subgroupOf D).map (QuotientGroup.mk' (C.subgroupOf D)) ≤
      Omega (D ⧸ C.subgroupOf D) p 1 :=
    subgroupOf_image_le_omega_quotient_of_isElementaryAbelian (C := C) (D := D) hT_elem
  exact OddOrder.BG.Ch1_Preliminary.exists_aInvariant_complement_in_omega1_quotient
    hpD hcopD hCsub_inv hD_quot_ab hTsub_inv hTΩ

/-- Blackburn 4.16 Case B-2: the image `TC/C` in `R/C`, where
`C = C_R(S)`, has order `p` and lies in `Ω₁(R/C)`. -/
private theorem blackburn_noncentral_commutator_map_centralizer_card_and_omega
    {R : Type*} [Group R] [Finite R] {p : ℕ} [Fact p.Prime]
    (hT_facts :
      let S : Subgroup R := Omega R p 1
      let T : Subgroup R := ⁅S, (⊤ : Subgroup R)⁆
      (Subgroup.center S).map S.subtype < T ∧ T < S ∧ Nat.card T = p ^ 2)
    (hT_elem :
      let S : Subgroup R := Omega R p 1
      let T : Subgroup R := ⁅S, (⊤ : Subgroup R)⁆
      T.IsElementaryAbelian p)
    (hT_quot_cards :
      let S : Subgroup R := Omega R p 1
      let T : Subgroup R := ⁅S, (⊤ : Subgroup R)⁆
      let Z : Subgroup R := (Subgroup.center S).map S.subtype
      Nat.card (S ⧸ T.subgroupOf S) = p ∧ Nat.card (T ⧸ Z.subgroupOf T) = p) :
    let S : Subgroup R := Omega R p 1
    let T : Subgroup R := ⁅S, (⊤ : Subgroup R)⁆
    let C : Subgroup R := Subgroup.centralizer (S : Set R)
    Nat.card (T.map (QuotientGroup.mk' C)) = p ∧
      T.map (QuotientGroup.mk' C) ≤ Omega (R ⧸ C) p 1 := by
  dsimp at hT_facts hT_elem hT_quot_cards ⊢
  let S : Subgroup R := Omega R p 1
  let T : Subgroup R := ⁅S, (⊤ : Subgroup R)⁆
  let C : Subgroup R := Subgroup.centralizer (S : Set R)
  let Z : Subgroup R := (Subgroup.center S).map S.subtype
  have hS_normal : S.Normal := by dsimp [S]; infer_instance
  have hrelations := blackburn_noncentral_centralizer_relations hT_facts hT_elem
  have hTC_eq_Z : T ⊓ C = Z := hrelations.2.2
  have hCsubT_eq_ZsubT : C.subgroupOf T = Z.subgroupOf T := by
    rw [← Subgroup.inf_subgroupOf_right C T, inf_comm, hTC_eq_Z]
  have hTmap_card : Nat.card (T.map (QuotientGroup.mk' C)) = p := by
    rw [← Subgroup.nat_card_quotient_subgroupOf_eq_card_map C T,
      hCsubT_eq_ZsubT, hT_quot_cards.2]
  have hTmap_omega : T.map (QuotientGroup.mk' C) ≤ Omega (R ⧸ C) p 1 := by
    rintro q ⟨t, htT, rfl⟩
    refine Omega.mem_of_pow_eq_one ?_
    rw [pow_one]
    rw [← map_pow]
    have ht_pow : t ^ p = 1 := congrArg Subtype.val (hT_elem.pow_eq_one ⟨t, htT⟩)
    rw [ht_pow, map_one]
  exact ⟨hTmap_card, hTmap_omega⟩

/-- Blackburn 4.16 Case B-2: the image `TC/C` lies inside the image
`D/C`, where `D = C_R(T)`, and keeps its order-`p`/`Ω₁` facts. -/
theorem blackburn_noncentral_commutator_image_relations
    {R : Type*} [Group R] [Finite R] {p : ℕ} [Fact p.Prime]
    (hT_facts :
      let S : Subgroup R := Omega R p 1
      let T : Subgroup R := ⁅S, (⊤ : Subgroup R)⁆
      (Subgroup.center S).map S.subtype < T ∧ T < S ∧ Nat.card T = p ^ 2)
    (hT_elem :
      let S : Subgroup R := Omega R p 1
      let T : Subgroup R := ⁅S, (⊤ : Subgroup R)⁆
      T.IsElementaryAbelian p)
    (hT_quot_cards :
      let S : Subgroup R := Omega R p 1
      let T : Subgroup R := ⁅S, (⊤ : Subgroup R)⁆
      let Z : Subgroup R := (Subgroup.center S).map S.subtype
      Nat.card (S ⧸ T.subgroupOf S) = p ∧ Nat.card (T ⧸ Z.subgroupOf T) = p) :
    let S : Subgroup R := Omega R p 1
    let T : Subgroup R := ⁅S, (⊤ : Subgroup R)⁆
    let C : Subgroup R := Subgroup.centralizer (S : Set R)
    let D : Subgroup R := Subgroup.centralizer (T : Set R)
    T.map (QuotientGroup.mk' C) ≤ D.map (QuotientGroup.mk' C) ∧
      Nat.card (T.map (QuotientGroup.mk' C)) = p ∧
      T.map (QuotientGroup.mk' C) ≤ Omega (R ⧸ C) p 1 := by
  dsimp at hT_facts hT_elem hT_quot_cards ⊢
  let S : Subgroup R := Omega R p 1
  let T : Subgroup R := ⁅S, (⊤ : Subgroup R)⁆
  let C : Subgroup R := Subgroup.centralizer (S : Set R)
  let D : Subgroup R := Subgroup.centralizer (T : Set R)
  have hrelations := blackburn_noncentral_centralizer_relations hT_facts hT_elem
  have hT_le_D : T ≤ D := hrelations.2.1
  have hTC := blackburn_noncentral_commutator_map_centralizer_card_and_omega
    hT_facts hT_elem hT_quot_cards
  exact ⟨Subgroup.map_mono hT_le_D, hTC.1, hTC.2⟩

end BlackburnClassification

end OddOrder.BG.Ch1.S04
