/-
Copyright (c) 2026 Yawara ISHIDA. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.GroupTheory.Perm.Cycle.Type
import OddOrder.BG.Ch1_Preliminary.S04c_Prop411
import OddOrder.BG.Ch1_Preliminary.S04d_GorThm415
import OddOrder.BG.Ch1_Preliminary.S04e_GorThm37
import OddOrder.GroupTheory.CentralProduct

/-!
# BG §4F — Blackburn rank-two classification

This downstream leaf hosts the BG §4 endpoint declarations that must see both
`S04_PGroupsSmallRank` and the later Gorenstein precursor files:

* `S04d_GorThm415`: `SCN₃(R)=∅ ⇒ pRank R p ≤ 2`.
* `S04e_GorThm37`: the minimal `p′`-operator subgroup is special of exponent `p`.
* `S04c_Prop411`: Huppert's metacyclic criterion.

Keeping the Blackburn apex here avoids an import cycle: `S04e_GorThm37` imports
`S04_PGroupsSmallRank`, so the final Theorem 4.16 proof cannot live in S04 itself.
-/

open scoped Pointwise commutatorElement

namespace OddOrder.BG.Ch1.S04

open OddOrder.GroupTheory
open OddOrder.Isaacs.Ch03 (IsAInvariant)
open OddOrder.BG.Ch1_Preliminary (isAInvariant_map_subtype_of_restrict)

section AutOrderConstraints

/-! ## §4E: automorphism-order constraints (Lemmas 4.13 and 4.14) -/

/-- Arithmetic half of BG Lemma 4.14.  For odd `p`, every prime divisor `q` of
`p^2 - 1` divides one of the half-factors `(p + 1) / 2` or `(p - 1) / 2`.

The only small wrinkle is `q = 2`: since `p` is odd, exactly one of
`(p - 1) / 2`, `(p + 1) / 2` is even.  For odd `q`, remove the factor `4` from
`p^2 - 1 = 4 * ((p - 1) / 2) * ((p + 1) / 2)`. -/
private theorem prime_dvd_half_factor_of_odd_dvd_sq_sub_one {p q : ℕ}
    (hp_odd : Odd p) (hq : q.Prime) (hq_dvd : q ∣ p ^ 2 - 1) :
    q ∣ (p + 1) / 2 ∨ q ∣ (p - 1) / 2 := by
  classical
  by_cases hq2 : q = 2
  · subst q
    have hp_repr : 2 * (p / 2) + 1 = p := Nat.two_mul_div_two_add_one_of_odd hp_odd
    have hsub : (p - 1) / 2 = p / 2 := by omega
    have hadd : (p + 1) / 2 = p / 2 + 1 := by omega
    rcases Nat.even_or_odd (p / 2) with h_even | h_odd
    · right
      rw [hsub]
      exact Even.two_dvd h_even
    · left
      rw [hadd]
      exact Even.two_dvd h_odd.add_one
  · set a := (p - 1) / 2 with ha
    set b := (p + 1) / 2 with hb
    have hsub_even : Even (p - 1) := by
      rcases hp_odd with ⟨k, rfl⟩
      rw [Nat.add_sub_cancel]
      exact even_two_mul k
    have hadd_even : Even (p + 1) := hp_odd.add_one
    have hsub : p - 1 = 2 * a := by
      rw [ha]
      exact (Nat.two_mul_div_two_of_even hsub_even).symm
    have hadd : p + 1 = 2 * b := by
      rw [hb]
      exact (Nat.two_mul_div_two_of_even hadd_even).symm
    have hsq : p ^ 2 - 1 = (p - 1) * (p + 1) := by
      rcases p with _ | n
      · simp
      · rw [Nat.succ_sub_one,
          show (n + 1) ^ 2 = n * (n + 2) + 1 from by ring, Nat.add_sub_cancel]
    have hfac : p ^ 2 - 1 = 4 * (a * b) := by
      calc
        p ^ 2 - 1 = (p - 1) * (p + 1) := hsq
        _ = (2 * a) * (2 * b) := by rw [hsub, hadd]
        _ = 4 * (a * b) := by ring
    have hq_dvd_four_mul : q ∣ 4 * (a * b) := by rwa [hfac] at hq_dvd
    have hq_not_dvd_four : ¬ q ∣ 4 := by
      intro hq4
      have hq_le4 : q ≤ 4 := Nat.le_of_dvd (by norm_num) hq4
      have hq_ge2 : 2 ≤ q := hq.two_le
      interval_cases q
      · exact hq2 rfl
      · exact (by decide : ¬ 3 ∣ 4) hq4
      · exact (by decide : ¬ Nat.Prime 4) hq
    have hq_coprime_four : Nat.Coprime q 4 :=
      hq.coprime_iff_not_dvd.mpr hq_not_dvd_four
    have hq_dvd_ab : q ∣ a * b :=
      (Nat.Coprime.dvd_mul_left hq_coprime_four).mp hq_dvd_four_mul
    rcases hq.dvd_mul.mp hq_dvd_ab with hqa | hqb
    · right
      rwa [ha]
    · left
      rwa [hb]

/-- Cauchy extraction for BG Lemma 4.13: a prime divisor of `|Aut R|` is realized
by an automorphism of order exactly that prime. -/
private theorem exists_mulAut_orderOf_eq_prime_of_prime_dvd_card
    {R : Type*} [Group R] [Finite R] {q : ℕ}
    (hq : q.Prime) (hq_dvd : q ∣ Nat.card (MulAut R)) :
    ∃ ψ : MulAut R, orderOf ψ = q := by
  letI : Fact q.Prime := ⟨hq⟩
  exact exists_prime_orderOf_dvd_card' q hq_dvd

/-- The cyclic automorphism group generated by a `q`-element acts with order
coprime to a finite `p`-group when `q ≠ p`. -/
private theorem coprime_card_zpowers_mulAut_of_prime_order_ne
    {R : Type*} [Group R] [Finite R] {p q : ℕ} [Fact p.Prime]
    (hR : IsPGroup p R) (hq : q.Prime) (hqp : q ≠ p)
    {ψ : MulAut R} (hψ_order : orderOf ψ = q) :
    Nat.Coprime (Nat.card (Subgroup.zpowers ψ)) (Nat.card R) := by
  obtain ⟨n, hn⟩ := hR.exists_card_eq
  rw [Nat.card_zpowers, hψ_order, hn]
  exact ((Nat.coprime_primes hq Fact.out).mpr hqp).pow_right n

/-- Subgroups inherit the BG Lemma 4.7 rank bound from the ambient `SCN₃`-empty
`p`-group. -/
private theorem pRank_subgroup_le_two_of_scn3_empty
    {R : Type*} [Group R] [Finite R] {p : ℕ} [Fact p.Prime]
    (hp_odd : Odd p) (hR : IsPGroup p R)
    (hSCN : ∀ A : Subgroup R, ¬ IsSCN₃ p A) (Q : Subgroup R) :
    pRank Q p ≤ 2 :=
  (pRank_mono_of_le Q).trans (pRank_le_two_of_scn3_empty hp_odd hR hSCN)

/-- Abelian branch support for BG Lemma 4.13: an elementary abelian subgroup of an
`SCN₃`-empty finite `p`-group has order at most `p²`. -/
private theorem card_le_prime_sq_of_scn3_empty_elementaryAbelian_subgroup
    {R : Type*} [Group R] [Finite R] {p : ℕ} [Fact p.Prime]
    (hp_odd : Odd p) (hR : IsPGroup p R)
    (hSCN : ∀ A : Subgroup R, ¬ IsSCN₃ p A) {Q : Subgroup R}
    (hQ : IsElementaryAbelian p Q) :
    Nat.card Q ≤ p ^ 2 := by
  have hQ_rank : pRank Q p ≤ 2 :=
    pRank_subgroup_le_two_of_scn3_empty hp_odd hR hSCN Q
  have hlog_le : Nat.log p (Nat.card Q) ≤ 2 := hQ.log_card_le_pRank.trans hQ_rank
  have hcard : Nat.card Q = p ^ Nat.log p (Nat.card Q) := by
    letI : IsMulCommutative Q := IsMulCommutative.of_comm hQ.comm
    letI := hQ.zmodModule
    rw [hQ.log_card_eq_finrank]
    exact hQ.card_eq_pow_finrank
  rw [hcard]
  exact Nat.pow_le_pow_right (Fact.out : p.Prime).pos hlog_le

/-- Exponent-`p` support for BG Lemma 4.13: a subgroup of an `SCN₃`-empty finite
`p`-group with exponent `p` has order at most `p³`. -/
private theorem card_le_prime_cube_of_scn3_empty_exp_prime_subgroup
    {R : Type*} [Group R] [Finite R] {p : ℕ} [Fact p.Prime]
    (hp_odd : Odd p) (hR : IsPGroup p R)
    (hSCN : ∀ A : Subgroup R, ¬ IsSCN₃ p A) {Q : Subgroup R}
    (hQ_exp : Monoid.exponent Q = p) :
    Nat.card Q ≤ p ^ 3 := by
  have hQ_rank : pRank Q p ≤ 2 :=
    pRank_subgroup_le_two_of_scn3_empty hp_odd hR hSCN Q
  have hQ_pow : ∀ x : Q, x ^ p = 1 := by
    intro x
    simpa [hQ_exp] using (Monoid.pow_exponent_eq_one x)
  exact card_le_prime_cube_of_pRank_le_two_of_exponent_prime
    (hR.to_subgroup Q) hQ_rank hQ_pow

/-- If an operator has prime-power-one relation and acts nontrivially on an
invariant subgroup, then its restricted automorphism has that prime order. -/
private theorem orderOf_restrict_eq_prime_of_pow_eq_one_and_nontrivial
    {A R : Type*} [Group A] [Group R] {φ : A →* MulAut R}
    {Q : Subgroup R} (hQ_inv : IsAInvariant φ Q) {ψ : A} {q : ℕ}
    (hq : q.Prime) (hψ_pow : ψ ^ q = 1)
    (hψ_nt : ∃ g ∈ Q, (φ ψ) g ≠ g) :
    orderOf (hQ_inv.restrict ψ) = q := by
  have hres_ne_one : hQ_inv.restrict ψ ≠ 1 := by
    intro hres
    obtain ⟨g, hgQ, hg⟩ := hψ_nt
    apply hg
    have hfix : (hQ_inv.restrict ψ) ⟨g, hgQ⟩ = ⟨g, hgQ⟩ := by
      rw [hres]
      rfl
    exact congrArg Subtype.val hfix
  have hres_pow : (hQ_inv.restrict ψ) ^ q = 1 := by
    rw [← map_pow, hψ_pow, map_one]
  have hdvd : orderOf (hQ_inv.restrict ψ) ∣ q := orderOf_dvd_of_pow_eq_one hres_pow
  rcases hq.eq_one_or_self_of_dvd _ hdvd with h1 | hqeq
  · exact (hres_ne_one (orderOf_eq_one_iff.mp h1)).elim
  · exact hqeq

/-- Minimality support for BG Lemma 4.13: if `Q` is minimal among `φ`-invariant
subgroups on which `ψ` acts nontrivially, then `ψ` fixes every proper
`φ`-invariant subgroup of `Q` pointwise. -/
private theorem acts_trivially_on_proper_of_minimal_nontrivial
    {A R : Type*} [Group A] [Group R] {φ : A →* MulAut R}
    {Q : Subgroup R} {ψ : A}
    (hmin : ∀ N : Subgroup R, IsAInvariant φ N → N ≤ Q →
      (∃ g ∈ N, (φ ψ) g ≠ g) → N = Q)
    {N : Subgroup R} (hN_inv : IsAInvariant φ N) (hN_le : N ≤ Q)
    (hN_ne : N ≠ Q) :
    ∀ n ∈ N, (φ ψ) n = n := by
  intro n hn
  by_contra hn_ne
  exact hN_ne (hmin N hN_inv hN_le ⟨n, hn, hn_ne⟩)

/-- Restricted form of `acts_trivially_on_proper_of_minimal_nontrivial`, for
proper invariant subgroups of the selected subgroup `Q`. -/
private theorem restrict_acts_trivially_on_proper_of_minimal_nontrivial
    {A R : Type*} [Group A] [Group R] {φ : A →* MulAut R}
    {Q : Subgroup R} (hQ_inv : IsAInvariant φ Q) {ψ : A}
    (hmin : ∀ N : Subgroup R, IsAInvariant φ N → N ≤ Q →
      (∃ g ∈ N, (φ ψ) g ≠ g) → N = Q)
    {K : Subgroup Q} (hK_inv : IsAInvariant hQ_inv.restrict K)
    (hK_ne : K ≠ ⊤) :
    ∀ z ∈ K, (hQ_inv.restrict ψ) z = z := by
  intro z hz
  let N : Subgroup R := K.map Q.subtype
  have hN_inv : IsAInvariant φ N := isAInvariant_map_subtype_of_restrict hQ_inv hK_inv
  have hN_le : N ≤ Q := Subgroup.map_subtype_le K
  have hN_ne : N ≠ Q := by
    intro hNQ
    apply hK_ne
    have hQtop : Q = (⊤ : Subgroup Q).map Q.subtype := by
      rw [← MonoidHom.range_eq_map, Q.range_subtype]
    exact Subgroup.map_injective Q.subtype_injective (hNQ.trans hQtop)
  apply Subtype.ext
  rw [IsAInvariant.restrict_apply_val]
  exact acts_trivially_on_proper_of_minimal_nontrivial hmin hN_inv hN_le hN_ne
    (z : R) (Subgroup.mem_map_of_mem _ hz)

/-- **BG Lemma 4.13** (via Gorenstein Theorem 4.15(ii)). Suppose `p` is an odd
prime, `R` is a finite `p`-group, and `q` is a prime divisor of `|Aut R|`. If
`SCN₃(R)` is empty and `q ≠ p`, then `q ∣ p^2 - 1` and `q < p`.

The proof is the remaining assembly of `pRank_le_two_of_scn3_empty`,
`exists_minimal_aInvariant_isExpPSpecial_of_pprimeAction`, and the existing
rank-`≤ 2` linear automorphism bounds in `PRank.lean`. -/
theorem dvd_prime_sq_sub_one_and_lt_of_prime_dvd_aut_of_scn3_empty
    {R : Type*} [Group R] [Finite R] {p q : ℕ} [Fact p.Prime]
    (hp_odd : Odd p) (hR : IsPGroup p R)
    (hSCN : ∀ A : Subgroup R, ¬ IsSCN₃ p A)
    (hq : q.Prime) (hqp : q ≠ p) (hq_dvd : q ∣ Nat.card (MulAut R)) :
    q ∣ p ^ 2 - 1 ∧ q < p := by
  obtain ⟨ψ, hψ_order⟩ := exists_mulAut_orderOf_eq_prime_of_prime_dvd_card hq hq_dvd
  have hψ_ne_one : ψ ≠ 1 := by
    intro hψ
    have hq_one : q = 1 := by rw [← hψ_order, hψ, orderOf_one]
    exact hq.ne_one hq_one
  let A : Subgroup (MulAut R) := Subgroup.zpowers ψ
  let φ : A →* MulAut R := A.subtype
  let ψA : A := ⟨ψ, Subgroup.mem_zpowers ψ⟩
  have hA_cop : Nat.Coprime (Nat.card A) (Nat.card R) := by
    dsimp [A]
    exact coprime_card_zpowers_mulAut_of_prime_order_ne hR hq hqp hψ_order
  have hψA_ntriv : ¬ ∀ g : R, (φ ψA) g = g := by
    intro hfix
    apply hψ_ne_one
    ext g
    exact hfix g
  obtain ⟨Q, hQ_inv, hψ_nt_Q, hQ_special, hQ_exp, hQ_min⟩ :=
    exists_minimal_aInvariant_isExpPSpecial_of_pprimeAction_with_minimality
      hp_odd φ hR hA_cop hψA_ntriv
  have hQ_rank : pRank Q p ≤ 2 :=
    pRank_subgroup_le_two_of_scn3_empty hp_odd hR hSCN Q
  have hQ_card_cube : Nat.card Q ≤ p ^ 3 :=
    card_le_prime_cube_of_scn3_empty_exp_prime_subgroup hp_odd hR hSCN hQ_exp
  have hQ_elem_card_le : IsElementaryAbelian p Q → Nat.card Q ≤ p ^ 2 :=
    card_le_prime_sq_of_scn3_empty_elementaryAbelian_subgroup hp_odd hR hSCN
  have hψA_pow : ψA ^ q = 1 := by
    apply Subtype.ext
    change ψ ^ q = 1
    rw [← hψ_order]
    exact pow_orderOf_eq_one ψ
  have hψQ_order : orderOf (hQ_inv.restrict ψA) = q :=
    orderOf_restrict_eq_prime_of_pow_eq_one_and_nontrivial hQ_inv hq hψA_pow hψ_nt_Q
  have hQ_min_fix : ∀ K : Subgroup Q, IsAInvariant hQ_inv.restrict K → K ≠ ⊤ →
      ∀ z ∈ K, (hQ_inv.restrict ψA) z = z :=
    fun K hK_inv hK_ne =>
      restrict_acts_trivially_on_proper_of_minimal_nontrivial hQ_inv hQ_min hK_inv hK_ne
  have hQ_elem_dvd : IsElementaryAbelian p Q → q ∣ p ^ 2 - 1 := by
    intro hQ_elem
    exact prime_dvd_prime_sq_sub_one_of_orderOf_mulAut hq hqp hQ_elem
      (hQ_elem_card_le hQ_elem) hψQ_order
  have hQ_elem_lt : IsElementaryAbelian p Q → q < p := by
    intro hQ_elem
    exact lt_of_prime_dvd_prime_sq_sub_one Fact.out hp_odd hq hqp (hQ_elem_dvd hQ_elem)
  sorry

/-- **BG Lemma 4.14.** Under the hypotheses of Lemma 4.13, `q` divides one of the
half-factors `(p + 1) / 2` or `(p - 1) / 2`.

BG derives this from Lemma 4.13 and the factorization
`p^2 - 1 = 4 * ((p - 1) / 2) * ((p + 1) / 2)` for odd `p`; the `q = 2` case is
absorbed by the same parity split. -/
theorem dvd_half_prime_add_or_sub_of_prime_dvd_aut_of_scn3_empty
    {R : Type*} [Group R] [Finite R] {p q : ℕ} [Fact p.Prime]
    (hp_odd : Odd p) (hR : IsPGroup p R)
    (hSCN : ∀ A : Subgroup R, ¬ IsSCN₃ p A)
    (hq : q.Prime) (hqp : q ≠ p) (hq_dvd : q ∣ Nat.card (MulAut R)) :
    q ∣ (p + 1) / 2 ∨ q ∣ (p - 1) / 2 := by
  exact prime_dvd_half_factor_of_odd_dvd_sq_sub_one hp_odd hq
    (dvd_prime_sq_sub_one_and_lt_of_prime_dvd_aut_of_scn3_empty hp_odd hR hSCN hq hqp
      hq_dvd).1

end AutOrderConstraints

section BlackburnClassification

/-! ## §4F: Blackburn rank-two classification (Theorem 4.16)

The current declaration makes the BG Theorem 4.16 endpoint visible in Lean.
Its proof is the remaining Blackburn apex of issue 0051; the statement is kept
close to the printed theorem:

* `A` is represented by an operator action `φ : A →* MulAut R`.
* "`A` is a `p'`-group of automorphisms" is represented in the repo's standard
  coprime-action form `Nat.Coprime (Nat.card A) (Nat.card R)`.
* `[R,A]=R` is `OddOrder.Isaacs.Ch04.actionCommutator φ = ⊤`.
* `R = R₁ ∘ R₂` is the internal central product
  `IsCentralProduct (⊤ : Subgroup R) R₁ R₂`.
-/

/-- **BG Theorem 4.16, case (2)** (Blackburn): `R` is the central product
`R₁ ∘ R₂`, where `R₁` is nonabelian of order `p^3` and exponent `p`, `R₂` is
cyclic, and `Ω₁(R₂) = R₁'`.

The equality `Ω₁(R₂) = R₁'` is stated after mapping both subgroups into the
ambient group `R`: `Ω₁(R₂)` is `(Omega R₂ p 1).map R₂.subtype`, and `R₁'` is
`(commutator R₁).map R₁.subtype`. -/
def BlackburnCentralProductCase (p : ℕ) (R : Type*) [Group R] : Prop :=
  ∃ R₁ R₂ : Subgroup R,
    IsCentralProduct (⊤ : Subgroup R) R₁ R₂ ∧
      ¬ IsMulCommutative ↥R₁ ∧
      Nat.card ↥R₁ = p ^ 3 ∧
      Monoid.exponent ↥R₁ = p ∧
      IsCyclic ↥R₂ ∧
      (Omega ↥R₂ p 1).map R₂.subtype =
        (_root_.commutator ↥R₁).map R₁.subtype

/-- **BG Theorem 4.16** (Blackburn rank-two classification).

Let `p` be an odd prime, `R` a nonidentity finite `p`-group, and `A` a
`p'`-group of automorphisms of `R`.  If `r(R) ≤ 2`, `[R,A]=R`, and `|A|` is odd,
then `p > 3` and either `R` is abelian, or `R` is a central product
`R₁ ∘ R₂` where `R₁` is nonabelian of order `p^3` and exponent `p`, `R₂` is
cyclic, and `Ω₁(R₂)=R₁'`.

In Lean, because `R` is a `p`-group, BG's rank hypothesis `r(R) ≤ 2` is represented
as `pRank R p ≤ 2`; see the §4C comments above `scn3_empty_of_pRank_le_two`.
The proof is intentionally still `sorry`: this declaration makes the missing
Blackburn apex visible to the mainline `sorry` census and downstream dependencies. -/
theorem blackburnRankTwoClassification
    {R : Type*} [Group R] [Finite R] [Nontrivial R]
    {p : ℕ} [Fact p.Prime] (hp_odd : Odd p) (hR : IsPGroup p R)
    {A : Type*} [Group A] [Finite A] {φ : A →* MulAut R}
    (hcop : Nat.Coprime (Nat.card A) (Nat.card R))
    (hrank : pRank R p ≤ 2)
    (hRA : OddOrder.Isaacs.Ch04.actionCommutator φ = ⊤)
    (hAodd : Odd (Nat.card A)) :
    3 < p ∧ (IsMulCommutative R ∨ BlackburnCentralProductCase p R) := by
  sorry

end BlackburnClassification

end OddOrder.BG.Ch1.S04
