/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.BG.Ch2_Uniqueness.S08_CenterFittingOpcore

/-!
# BG §8 — `O_{π'}`-core and centralizer comparisons for `cFittingInG`

The `opiCoreInG` comparison layer: `Z(F(M))·O`-invariance, coprimality, the
`O_{σ(F)'}`-vanishing chain and the centralizer inclusions feeding the `SCN`-Fitting
transitivity argument.

Split from `OddOrder.BG.Ch2_Uniqueness.S08_SCNFitting` (issue 0149); that file
imports this leaf, so downstream imports are unchanged.
-/

namespace OddOrder.BG.Ch2.S08
open OddOrder.GroupTheory
open OddOrder.Isaacs
open scoped Pointwise

variable {G : Type*} [Group G]


/-- For `q ∈ π(F(M))`, the central q-core `O_q(Z(F(M)))` is a
`π(C_F(M)(A0))`-subgroup. -/
theorem centerFittingOpCoreInG_isPiSubgroup_primesOf_cFittingInG [Finite G]
    {p q : ℕ} [Fact q.Prime] {M A0 : Subgroup G}
    (hA0 : isMaxElemAbelianIn p A0 (fittingInG M))
    (hq : q ∈ (Nat.card ↥(fittingInG M)).primeFactors) :
    Subgroup.IsPiSubgroup (OddOrder.BG.Ch2.S07.primesOf (cFittingInG M A0))
      (centerFittingOpCoreInG q M) := by
  have hA0F : A0 ≤ fittingInG M := isMaxElemAbelianIn_le hA0
  have hPrimes :
      OddOrder.BG.Ch2.S07.primesOf (cFittingInG M A0) =
        OddOrder.BG.Ch2.S07.primesOf (fittingInG M) := by
    dsimp [cFittingInG]
    exact primesOf_cFitting_eq_primesOf_fittingInG hA0F
  have hBq : Subgroup.IsPiSubgroup ({q} : Set ℕ) (centerFittingOpCoreInG q M) := by
    dsimp [centerFittingOpCoreInG]
    exact isPiSubgroup_opiCoreInG ({q} : Set ℕ) (centerFittingInG M)
  intro r hr
  have hrq : r ∈ ({q} : Set ℕ) := hBq r hr
  rw [Set.mem_singleton_iff] at hrq
  rw [hrq, hPrimes]
  simpa [OddOrder.BG.Ch2.S07.primesOf] using hq

/-- The action of `O_q(Z(F(M)))` on an `ℋ`-member for the complementary prime set is
coprime. -/
theorem coprime_card_centerFittingOpCoreInG_hInvariant [Finite G]
    {p q : ℕ} [Fact q.Prime] {M A0 X Y : Subgroup G}
    (hA0 : isMaxElemAbelianIn p A0 (fittingInG M))
    (hq : q ∈ (Nat.card ↥(fittingInG M)).primeFactors)
    (hY : Y ∈ hInvariant X (cFittingInG M A0)
      (OddOrder.BG.Ch2.S07.primesOf (cFittingInG M A0))ᶜ) :
    Nat.Coprime (Nat.card ↥(centerFittingOpCoreInG q M)) (Nat.card ↥Y) :=
  coprime_card_of_isPiSubgroup_of_isPiSubgroup_compl
    (centerFittingOpCoreInG_isPiSubgroup_primesOf_cFittingInG hA0 hq)
    (hInvariant_isPiSubgroup hY)

/-- BG (8.4), commutator form: in the non-p-group case, every
`π(C_F(M)(A0))`-complement `ℋ`-member is generated by its commutators with
`O_q(Z(F(M)))`, for each `q ∈ π(F(M))`. -/
theorem hInvariant_le_commutator_centerFittingOpCoreInG_of_not_pGroup
    [Finite G] (hG : IsMinimalSimpleOdd G) {p q : ℕ} [Fact p.Prime] [Fact q.Prime]
    {M A0 X Y : Subgroup G} (hM : M ∈ maximalSubgroups G)
    (hA0 : isMaxElemAbelianIn p A0 (fittingInG M))
    (hFnp : ¬ IsPGroup p ↥(fittingInG M))
    (hq : q ∈ (Nat.card ↥(fittingInG M)).primeFactors)
    (hY : Y ∈ hInvariant X (cFittingInG M A0)
      (OddOrder.BG.Ch2.S07.primesOf (cFittingInG M A0))ᶜ) :
    Y ≤ ⁅centerFittingOpCoreInG q M, Y⁆ := by
  have hfixed : Y ⊓
      Subgroup.centralizer (centerFittingOpCoreInG q M : Set G) = ⊥ := by
    simpa [inf_comm] using
      centralizer_centerFittingOpCoreInG_inf_hInvariant_eq_bot_of_not_pGroup
        hG hM hA0 hFnp hq hY
  haveI : IsSolvable ↥(centerFittingOpCoreInG q M) :=
    centerFittingOpCoreInG_isSolvable q M
  exact le_commutator_of_coprime_inf_centralizer_eq_bot
    (centerFittingOpCoreInG_le_normalizer_of_hInvariant (q := q) hA0 hY)
    (coprime_card_centerFittingOpCoreInG_hInvariant hA0 hq hY) hfixed

/-- If `R` is a q-subgroup of `X`, then the q'-core of `N_X(R)` lies in the q'-core
of `C_X(R)`. The point is that `K = O_{q'}(N_X(R))` normalizes `R`, while `R`
normalizes `K`; hence `[K,R]` lies in both the q'-group `K` and the q-group `R`. -/
theorem opiCoreInG_singleton_compl_normalizer_inf_le_centralizer_inf
    [Finite G] {q : ℕ} [Fact q.Prime] {R X : Subgroup G}
    (hRX : R ≤ X) (hRpi : Subgroup.IsPiSubgroup ({q} : Set ℕ) R) :
    opiCoreInG ({q} : Set ℕ)ᶜ (Subgroup.normalizer (R : Set G) ⊓ X) ≤
      opiCoreInG ({q} : Set ℕ)ᶜ (Subgroup.centralizer (R : Set G) ⊓ X) := by
  let N : Subgroup G := Subgroup.normalizer (R : Set G) ⊓ X
  let C : Subgroup G := Subgroup.centralizer (R : Set G) ⊓ X
  let K : Subgroup G := opiCoreInG ({q} : Set ℕ)ᶜ N
  have hKN : K ≤ N := opiCoreInG_le ({q} : Set ℕ)ᶜ N
  have hKX : K ≤ X := hKN.trans inf_le_right
  have hK_norm_R : K ≤ Subgroup.normalizer (R : Set G) := hKN.trans inf_le_left
  have hRN : R ≤ N := by
    intro r hr
    exact ⟨Subgroup.le_normalizer hr, hRX hr⟩
  have hN_norm_K : N ≤ Subgroup.normalizer (K : Set G) := by
    dsimp [K]
    exact le_normalizer_opiCoreInG ({q} : Set ℕ)ᶜ N
  have hR_norm_K : R ≤ Subgroup.normalizer (K : Set G) := hRN.trans hN_norm_K
  have hcomm_le_K : ⁅K, R⁆ ≤ K :=
    OddOrder.Isaacs.Ch04.commutator_le_of_le_normalizer hR_norm_K
  have hcomm_le_R : ⁅K, R⁆ ≤ R := by
    rw [Subgroup.commutator_comm K R]
    exact OddOrder.Isaacs.Ch04.commutator_le_of_le_normalizer hK_norm_R
  have hKpi : Subgroup.IsPiSubgroup ({q} : Set ℕ)ᶜ K := by
    dsimp [K]
    exact isPiSubgroup_opiCoreInG ({q} : Set ℕ)ᶜ N
  have hcomm_pi : Subgroup.IsPiSubgroup ({q} : Set ℕ)ᶜ ⁅K, R⁆ := by
    intro s hs
    exact hKpi s
      (Nat.primeFactors_mono (Subgroup.card_dvd_of_le hcomm_le_K) Nat.card_pos.ne' hs)
  have hcomm_bot : ⁅K, R⁆ = ⊥ :=
    eq_bot_of_le_of_isPiSubgroup_of_isPiSubgroup_compl hcomm_le_R hRpi hcomm_pi
  have hK_cent : K ≤ Subgroup.centralizer (R : Set G) := by
    rw [← Subgroup.commutator_eq_bot_iff_le_centralizer]
    exact hcomm_bot
  have hKC : K ≤ C := by
    intro x hx
    exact ⟨hK_cent hx, hKX hx⟩
  have hC_le_N : C ≤ N := by
    intro x hx
    exact ⟨Subgroup.centralizer_le_normalizer (R : Set G) hx.1, hx.2⟩
  have hKnormC : (K.subgroupOf C).Normal := by
    rw [Subgroup.normal_subgroupOf_iff_le_normalizer hKC]
    exact hC_le_N.trans hN_norm_K
  exact le_opiCoreInG_of_normal_of_isPiSubgroup hKC hKnormC hKpi

/-- BG (8.5), central-core form: for distinct primes `q,r ∈ π(F(M))`, the central
r-core `O_r(Z(F(M)))` lies in `O_{q'}(X)` whenever `X` is solvable and contains
`C_F(M)(A0)`. -/
theorem centerFittingOpCoreInG_le_opiCoreInG_singleton_compl_of_ne
    [Finite G] (hG : IsMinimalSimpleOdd G) {p q r : ℕ}
    [Fact p.Prime] [Fact q.Prime] [Fact r.Prime] {M A0 X : Subgroup G}
    (hM : M ∈ maximalSubgroups G)
    (hA0 : isMaxElemAbelianIn p A0 (fittingInG M))
    (hXsolv : IsSolvable ↥X)
    (hAX : cFittingInG M A0 ≤ X)
    (hq : q ∈ (Nat.card ↥(fittingInG M)).primeFactors)
    (hr : r ∈ (Nat.card ↥(fittingInG M)).primeFactors)
    (hqr : q ≠ r) :
    centerFittingOpCoreInG r M ≤ opiCoreInG ({q} : Set ℕ)ᶜ X := by
  let Rq : Subgroup G := centerFittingOpCoreInG q M
  let Br : Subgroup G := centerFittingOpCoreInG r M
  let Nq : Subgroup G := Subgroup.normalizer (Rq : Set G) ⊓ X
  have hRqX : Rq ≤ X :=
    (centerFittingOpCoreInG_le_cFittingInG (q := q) hA0).trans hAX
  have hBrX : Br ≤ X :=
    (centerFittingOpCoreInG_le_cFittingInG (q := r) hA0).trans hAX
  have hRqpi : Subgroup.IsPiSubgroup ({q} : Set ℕ) Rq := by
    dsimp [Rq, centerFittingOpCoreInG]
    exact isPiSubgroup_opiCoreInG ({q} : Set ℕ) (centerFittingInG M)
  have hBrpi_r : Subgroup.IsPiSubgroup ({r} : Set ℕ) Br := by
    dsimp [Br, centerFittingOpCoreInG]
    exact isPiSubgroup_opiCoreInG ({r} : Set ℕ) (centerFittingInG M)
  have hBrpi_qcompl : Subgroup.IsPiSubgroup ({q} : Set ℕ)ᶜ Br := by
    refine hBrpi_r.mono ?_
    intro s hs hsq
    rw [Set.mem_singleton_iff] at hs hsq
    exact hqr (hsq.symm.trans hs)
  have hNq_eq_M : Subgroup.normalizer (Rq : Set G) = M := by
    dsimp [Rq]
    exact normalizer_centerFittingOpCoreInG_eq_of_ne_bot hG hM
      (centerFittingOpCoreInG_ne_bot_of_mem_primeFactors_fittingInG hq)
  have hBrNq : Br ≤ Nq := by
    refine le_inf ?_ hBrX
    intro x hx
    simpa [hNq_eq_M] using centerFittingOpCoreInG_le r M hx
  have hBrnormNq : (Br.subgroupOf Nq).Normal := by
    rw [Subgroup.normal_subgroupOf_iff_le_normalizer hBrNq]
    have hNq_le_M : Nq ≤ M := by
      intro x hx
      simpa [hNq_eq_M] using hx.1
    have hBr_norm_eq_M : Subgroup.normalizer (Br : Set G) = M := by
      dsimp [Br]
      exact normalizer_centerFittingOpCoreInG_eq_of_ne_bot hG hM
        (centerFittingOpCoreInG_ne_bot_of_mem_primeFactors_fittingInG hr)
    have hM_norm_Br : M ≤ Subgroup.normalizer (Br : Set G) := by
      rw [hBr_norm_eq_M]
    exact hNq_le_M.trans hM_norm_Br
  have hBr_le_core_Nq : Br ≤ opiCoreInG ({q} : Set ℕ)ᶜ Nq :=
    le_opiCoreInG_of_normal_of_isPiSubgroup hBrNq hBrnormNq hBrpi_qcompl
  have hcore_Nq_le_core_CX :
      opiCoreInG ({q} : Set ℕ)ᶜ Nq ≤
        opiCoreInG ({q} : Set ℕ)ᶜ (Subgroup.centralizer (Rq : Set G) ⊓ X) := by
    dsimp [Nq]
    exact opiCoreInG_singleton_compl_normalizer_inf_le_centralizer_inf hRqX hRqpi
  have hRqP : IsPGroup q ↥Rq :=
    OddOrder.GroupTheory.isPGroup_of_isPiSubgroup_singleton hRqpi
  have hcore_CX_le_core_X :
      opiCoreInG ({q} : Set ℕ)ᶜ (Subgroup.centralizer (Rq : Set G) ⊓ X) ≤
        opiCoreInG ({q} : Set ℕ)ᶜ X :=
    OddOrder.BG.Ch2.S07.opiCoreInG_centralizer_inf_le_opiCoreInG hXsolv hRqX hRqP
  exact hBr_le_core_Nq.trans (hcore_Nq_le_core_CX.trans hcore_CX_le_core_X)

/-- BG (8.5), full cFitting-core form: for distinct primes `q,r`, the r-core
of `A = C_F(M)(A0)` lies in `O_{q'}(X)` whenever `X` is solvable and contains `A`. -/
theorem opiCoreInG_singleton_cFittingInG_le_opiCoreInG_singleton_compl_of_ne
    [Finite G] (hG : IsMinimalSimpleOdd G) {p q r : ℕ}
    [Fact p.Prime] [Fact q.Prime] [Fact r.Prime] {M A0 X : Subgroup G}
    (hM : M ∈ maximalSubgroups G)
    (hA0 : isMaxElemAbelianIn p A0 (fittingInG M))
    (hXsolv : IsSolvable ↥X)
    (hAX : cFittingInG M A0 ≤ X)
    (hq : q ∈ (Nat.card ↥(fittingInG M)).primeFactors)
    (hqr : q ≠ r) :
    opiCoreInG ({r} : Set ℕ) (cFittingInG M A0) ≤ opiCoreInG ({q} : Set ℕ)ᶜ X := by
  let Rq : Subgroup G := centerFittingOpCoreInG q M
  let Ar : Subgroup G := opiCoreInG ({r} : Set ℕ) (cFittingInG M A0)
  let Nq : Subgroup G := Subgroup.normalizer (Rq : Set G) ⊓ X
  have hRqX : Rq ≤ X :=
    (centerFittingOpCoreInG_le_cFittingInG (q := q) hA0).trans hAX
  have hRqpi : Subgroup.IsPiSubgroup ({q} : Set ℕ) Rq := by
    dsimp [Rq, centerFittingOpCoreInG]
    exact isPiSubgroup_opiCoreInG ({q} : Set ℕ) (centerFittingInG M)
  have hNq_eq_M : Subgroup.normalizer (Rq : Set G) = M := by
    dsimp [Rq]
    exact normalizer_centerFittingOpCoreInG_eq_of_ne_bot hG hM
      (centerFittingOpCoreInG_ne_bot_of_mem_primeFactors_fittingInG hq)
  have hNq_le_M : Nq ≤ M := by
    intro x hx
    simpa [hNq_eq_M] using hx.1
  have hArX : Ar ≤ X :=
    (opiCoreInG_le ({r} : Set ℕ) (cFittingInG M A0)).trans hAX
  have hArF : Ar ≤ fittingInG M := by
    dsimp [Ar]
    exact opiCoreInG_singleton_cFittingInG_le_opiCoreInG_fittingInG.trans
      (opiCoreInG_le ({r} : Set ℕ) (fittingInG M))
  have hAr_cent_Rq : Ar ≤ Subgroup.centralizer (Rq : Set G) := by
    intro x hx
    have hxF : x ∈ fittingInG M := hArF hx
    have hxC := fittingInG_le_centralizer_centerFittingInG M hxF
    rw [Subgroup.mem_centralizer_iff]
    intro y hy
    exact Subgroup.mem_centralizer_iff.mp hxC y
      (centerFittingOpCoreInG_le_centerFittingInG q M hy)
  have hArNq : Ar ≤ Nq := by
    refine le_inf ?_ hArX
    exact hAr_cent_Rq.trans (Subgroup.centralizer_le_normalizer (Rq : Set G))
  let L : Subgroup G := opiCoreInG ({q} : Set ℕ)ᶜ M ⊓ Nq
  have hArOqM : Ar ≤ opiCoreInG ({q} : Set ℕ)ᶜ M := by
    dsimp [Ar]
    exact opiCoreInG_singleton_cFittingInG_le_opiCoreInG_singleton_compl_maximal_of_ne
      hqr
  have hArL : Ar ≤ L := le_inf hArOqM hArNq
  have hLNq : L ≤ Nq := inf_le_right
  have hLnorm : (L.subgroupOf Nq).Normal := by
    rw [Subgroup.normal_subgroupOf_iff_le_normalizer hLNq]
    intro x hx
    rw [Subgroup.mem_normalizer_iff]
    intro y
    constructor
    · intro hy
      have hyInf : y ∈ opiCoreInG ({q} : Set ℕ)ᶜ M ⊓ Nq := by simpa [L] using hy
      have hxM : x ∈ M := hNq_le_M hx
      have hnormO :=
        Subgroup.mem_normalizer_iff.mp
          (le_normalizer_opiCoreInG ({q} : Set ℕ)ᶜ M hxM) y
      have hnormN := Subgroup.mem_normalizer_iff.mp (Subgroup.le_normalizer hx) y
      simpa [L] using Subgroup.mem_inf.mpr ⟨hnormO.mp hyInf.1, hnormN.mp hyInf.2⟩
    · intro hy
      have hyInf : x * y * x⁻¹ ∈ opiCoreInG ({q} : Set ℕ)ᶜ M ⊓ Nq := by
        simpa [L] using hy
      have hxM : x ∈ M := hNq_le_M hx
      have hnormO :=
        Subgroup.mem_normalizer_iff.mp
          (le_normalizer_opiCoreInG ({q} : Set ℕ)ᶜ M hxM) y
      have hnormN := Subgroup.mem_normalizer_iff.mp (Subgroup.le_normalizer hx) y
      simpa [L] using Subgroup.mem_inf.mpr ⟨hnormO.mpr hyInf.1, hnormN.mpr hyInf.2⟩
  have hLpi : Subgroup.IsPiSubgroup ({q} : Set ℕ)ᶜ L := by
    intro s hs
    exact isPiSubgroup_opiCoreInG ({q} : Set ℕ)ᶜ M s
      (Nat.primeFactors_mono (Subgroup.card_dvd_of_le (inf_le_left : L ≤ _))
        Nat.card_pos.ne' hs)
  have hL_core_Nq : L ≤ opiCoreInG ({q} : Set ℕ)ᶜ Nq :=
    le_opiCoreInG_of_normal_of_isPiSubgroup hLNq hLnorm hLpi
  have hAr_core_Nq : Ar ≤ opiCoreInG ({q} : Set ℕ)ᶜ Nq := hArL.trans hL_core_Nq
  have hcore_Nq_le_core_CX :
      opiCoreInG ({q} : Set ℕ)ᶜ Nq ≤
        opiCoreInG ({q} : Set ℕ)ᶜ (Subgroup.centralizer (Rq : Set G) ⊓ X) := by
    dsimp [Nq]
    exact opiCoreInG_singleton_compl_normalizer_inf_le_centralizer_inf hRqX hRqpi
  have hRqP : IsPGroup q ↥Rq :=
    OddOrder.GroupTheory.isPGroup_of_isPiSubgroup_singleton hRqpi
  have hcore_CX_le_core_X :
      opiCoreInG ({q} : Set ℕ)ᶜ (Subgroup.centralizer (Rq : Set G) ⊓ X) ≤
        opiCoreInG ({q} : Set ℕ)ᶜ X :=
    OddOrder.BG.Ch2.S07.opiCoreInG_centralizer_inf_le_opiCoreInG hXsolv hRqX hRqP
  exact hAr_core_Nq.trans (hcore_Nq_le_core_CX.trans hcore_CX_le_core_X)

/-- BG (8.7) input: `O_{q'}(C_F(M)(A0))` is absorbed by `O_{q'}(H)`
whenever `H` is solvable and contains `C_F(M)(A0)`. -/
theorem opiCoreInG_cFittingInG_singleton_compl_le_opiCoreInG_singleton_compl
    [Finite G] (hG : IsMinimalSimpleOdd G) {p q : ℕ} [Fact p.Prime] [Fact q.Prime]
    {M A0 H : Subgroup G} (hM : M ∈ maximalSubgroups G)
    (hA0 : isMaxElemAbelianIn p A0 (fittingInG M))
    (hHsolv : IsSolvable ↥H)
    (hAH : cFittingInG M A0 ≤ H)
    (hq : q ∈ (Nat.card ↥(fittingInG M)).primeFactors) :
    opiCoreInG ({q} : Set ℕ)ᶜ (cFittingInG M A0) ≤ opiCoreInG ({q} : Set ℕ)ᶜ H := by
  let A : Subgroup G := cFittingInG M A0
  let K : Subgroup G := opiCoreInG ({q} : Set ℕ)ᶜ A
  have hA_le_F : A ≤ fittingInG M := by
    dsimp [A, cFittingInG]
    exact inf_le_right
  have hA_nilp : Group.IsNilpotent ↥A := by
    haveI : Group.IsNilpotent ↥(fittingInG M) := fittingInG_isNilpotent M
    exact Group.nilpotent_of_mulEquiv (Subgroup.subgroupOfEquivOfLe hA_le_F)
  have hK_nilp : Group.IsNilpotent ↥K := by
    have hK_A : K ≤ A := by
      dsimp [K]
      exact opiCoreInG_le ({q} : Set ℕ)ᶜ A
    haveI : Group.IsNilpotent ↥A := hA_nilp
    exact Group.nilpotent_of_mulEquiv (Subgroup.subgroupOfEquivOfLe hK_A)
  refine le_of_sylow_le_of_nilpotent hK_nilp ?_
  intro r
  haveI : Fact (r : ℕ).Prime := ⟨Nat.prime_of_mem_primeFactors r.2⟩
  let S : Subgroup G := ((default : Sylow (r : ℕ) ↥K) : Subgroup ↥K).map K.subtype
  have hS_le_K : S ≤ K := by
    dsimp [S]
    exact Subgroup.map_subtype_le _
  have hS_le_A : S ≤ A := hS_le_K.trans (by
    dsimp [K]
    exact opiCoreInG_le ({q} : Set ℕ)ᶜ A)
  have hS_p : IsPGroup (r : ℕ) ↥S := by
    dsimp [S]
    exact (default : Sylow (r : ℕ) ↥K).isPGroup'.map K.subtype
  have hS_le_OrA : S ≤ opiCoreInG ({(r : ℕ)} : Set ℕ) A :=
    le_opiCoreInG_singleton_of_isPGroup_of_le_nilpotent hA_nilp hS_le_A hS_p
  have hr_not_q : q ≠ (r : ℕ) := by
    have hKpi : Subgroup.IsPiSubgroup ({q} : Set ℕ)ᶜ K := by
      dsimp [K]
      exact isPiSubgroup_opiCoreInG ({q} : Set ℕ)ᶜ A
    have hrcomp : (r : ℕ) ∈ ({q} : Set ℕ)ᶜ := hKpi (r : ℕ) r.2
    intro hqr
    exact hrcomp (by simp [hqr])
  exact hS_le_OrA.trans (by
    dsimp [A]
    exact opiCoreInG_singleton_cFittingInG_le_opiCoreInG_singleton_compl_of_ne
      hG hM hA0 hHsolv hAH hq hr_not_q)

/-- BG (8.7), complement-centralizer form: after `π(F(H)) = π(F(M))`, the
`p`-core of `C_F(M)(A0)` centralizes `O_{p'}(F(H))`. -/
theorem opiCoreInG_singleton_cFittingInG_le_centralizer_opiCoreInG_singleton_compl_fittingInG
    [Finite G] (hG : IsMinimalSimpleOdd G) {p : ℕ} [Fact p.Prime]
    {M A0 H : Subgroup G} (hM : M ∈ maximalSubgroups G)
    (hA0 : isMaxElemAbelianIn p A0 (fittingInG M))
    (hHsolv : IsSolvable ↥H)
    (hAH : cFittingInG M A0 ≤ H)
    (hPrimes : OddOrder.BG.Ch2.S07.primesOf (fittingInG H) =
      OddOrder.BG.Ch2.S07.primesOf (fittingInG M)) :
    opiCoreInG ({p} : Set ℕ) (cFittingInG M A0) ≤
      Subgroup.centralizer (opiCoreInG ({p} : Set ℕ)ᶜ (fittingInG H) : Set G) := by
  let Ap : Subgroup G := opiCoreInG ({p} : Set ℕ) (cFittingInG M A0)
  let K : Subgroup G := opiCoreInG ({p} : Set ℕ)ᶜ (fittingInG H)
  have hK_le_cent_Ap : K ≤ Subgroup.centralizer (Ap : Set G) := by
    have hK_le_FH : K ≤ fittingInG H := by
      dsimp [K]
      exact opiCoreInG_le ({p} : Set ℕ)ᶜ (fittingInG H)
    have hK_nilp : Group.IsNilpotent ↥K := by
      haveI : Group.IsNilpotent ↥(fittingInG H) := fittingInG_isNilpotent H
      exact Group.nilpotent_of_mulEquiv (Subgroup.subgroupOfEquivOfLe hK_le_FH)
    refine le_of_sylow_le_of_nilpotent hK_nilp ?_
    intro r
    haveI : Fact (r : ℕ).Prime := ⟨Nat.prime_of_mem_primeFactors r.2⟩
    let S : Subgroup G := ((default : Sylow (r : ℕ) ↥K) : Subgroup ↥K).map K.subtype
    have hS_le_K : S ≤ K := by
      dsimp [S]
      exact Subgroup.map_subtype_le _
    have hS_le_FH : S ≤ fittingInG H := hS_le_K.trans hK_le_FH
    have hS_p : IsPGroup (r : ℕ) ↥S := by
      dsimp [S]
      exact (default : Sylow (r : ℕ) ↥K).isPGroup'.map K.subtype
    have hS_le_OrFH : S ≤ opiCoreInG ({(r : ℕ)} : Set ℕ) (fittingInG H) :=
      le_opiCoreInG_singleton_of_isPGroup_of_le_nilpotent
        (fittingInG_isNilpotent H) hS_le_FH hS_p
    have hrFH : (r : ℕ) ∈ (Nat.card ↥(fittingInG H)).primeFactors :=
      Nat.primeFactors_mono (Subgroup.card_dvd_of_le hK_le_FH) Nat.card_pos.ne' r.2
    have hrFM_primes : (r : ℕ) ∈ OddOrder.BG.Ch2.S07.primesOf (fittingInG M) := by
      rw [← hPrimes]
      exact hrFH
    have hKpi : Subgroup.IsPiSubgroup ({p} : Set ℕ)ᶜ K := by
      dsimp [K]
      exact isPiSubgroup_opiCoreInG ({p} : Set ℕ)ᶜ (fittingInG H)
    have hr_not_p : (r : ℕ) ≠ p := by
      have hrcomp : (r : ℕ) ∈ ({p} : Set ℕ)ᶜ := hKpi (r : ℕ) r.2
      intro hrp
      exact hrcomp (by simp [hrp])
    have hAp_le_OrH_compl : Ap ≤ opiCoreInG ({(r : ℕ)} : Set ℕ)ᶜ H := by
      dsimp [Ap]
      exact opiCoreInG_singleton_cFittingInG_le_opiCoreInG_singleton_compl_of_ne
        (p := p) (q := (r : ℕ)) (r := p) hG hM hA0 hHsolv hAH hrFM_primes hr_not_p
    have hOrFH_cent_Ap :
        opiCoreInG ({(r : ℕ)} : Set ℕ) (fittingInG H) ≤
          Subgroup.centralizer (Ap : Set G) :=
      opiCoreInG_fittingInG_le_centralizer_of_le_opiCoreInG_compl
        ({(r : ℕ)} : Set ℕ) hAp_le_OrH_compl
    exact hS_le_OrFH.trans hOrFH_cent_Ap
  change Ap ≤ Subgroup.centralizer (K : Set G)
  intro x hx
  refine Subgroup.mem_centralizer_iff.mpr ?_
  intro y hy
  exact (Subgroup.mem_centralizer_iff.mp (hK_le_cent_Ap hy) x hx).symm

/-- BG (8.7) plus Proposition 1.4: after `π(F(H)) = π(F(M))`, the `p`-core of
`C_F(M)(A0)` centralizes `O_{p'}(H)`. -/
theorem opiCoreInG_singleton_cFittingInG_le_centralizer_opiCoreInG_singleton_compl
    [Finite G] (hG : IsMinimalSimpleOdd G) {p : ℕ} [Fact p.Prime]
    {M A0 H : Subgroup G} (hM : M ∈ maximalSubgroups G)
    (hA0 : isMaxElemAbelianIn p A0 (fittingInG M))
    (hHsolv : IsSolvable ↥H)
    (hAH : cFittingInG M A0 ≤ H)
    (hPrimes : OddOrder.BG.Ch2.S07.primesOf (fittingInG H) =
      OddOrder.BG.Ch2.S07.primesOf (fittingInG M)) :
    opiCoreInG ({p} : Set ℕ) (cFittingInG M A0) ≤
      Subgroup.centralizer (opiCoreInG ({p} : Set ℕ)ᶜ H : Set G) := by
  let Ap : Subgroup G := opiCoreInG ({p} : Set ℕ) (cFittingInG M A0)
  let N : Subgroup G := opiCoreInG ({p} : Set ℕ)ᶜ H
  change Ap ≤ Subgroup.centralizer (N : Set G)
  have hN_H : N ≤ H := by
    dsimp [N]
    exact opiCoreInG_le ({p} : Set ℕ)ᶜ H
  have hH_norm_N : H ≤ Subgroup.normalizer (N : Set G) := by
    dsimp [N]
    exact le_normalizer_opiCoreInG ({p} : Set ℕ)ᶜ H
  have hAp_cent_FN : Ap ≤ Subgroup.centralizer (fittingInG N : Set G) := by
    have hAp_cent_OFH : Ap ≤
        Subgroup.centralizer (opiCoreInG ({p} : Set ℕ)ᶜ (fittingInG H) : Set G) := by
      dsimp [Ap]
      exact
        opiCoreInG_singleton_cFittingInG_le_centralizer_opiCoreInG_singleton_compl_fittingInG
          hG hM hA0 hHsolv hAH hPrimes
    have hFN_le_OFH : fittingInG N ≤ opiCoreInG ({p} : Set ℕ)ᶜ (fittingInG H) := by
      dsimp [N]
      exact fittingInG_opiCoreInG_singleton_compl_le_opiCoreInG_singleton_compl_fittingInG H
    intro a ha
    rw [Subgroup.mem_centralizer_iff]
    intro y hy
    exact Subgroup.mem_centralizer_iff.mp (hAp_cent_OFH ha) y (hFN_le_OFH hy)
  have hAp_H : Ap ≤ H := by
    dsimp [Ap]
    exact (opiCoreInG_le ({p} : Set ℕ) (cFittingInG M A0)).trans hAH
  have hAp_norm_N : Ap ≤ Subgroup.normalizer (N : Set G) := hAp_H.trans hH_norm_N
  have hAp_pi : Subgroup.IsPiSubgroup ({p} : Set ℕ) Ap := by
    dsimp [Ap]
    exact isPiSubgroup_opiCoreInG ({p} : Set ℕ) (cFittingInG M A0)
  have hN_pi : Subgroup.IsPiSubgroup ({p} : Set ℕ)ᶜ N := by
    dsimp [N]
    exact isPiSubgroup_opiCoreInG ({p} : Set ℕ)ᶜ H
  have hCop : Nat.Coprime (Nat.card ↥Ap) (Nat.card ↥N) :=
    coprime_card_of_isPiSubgroup_of_isPiSubgroup_compl hAp_pi hN_pi
  haveI : IsSolvable ↥H := hHsolv
  haveI hNsolv : IsSolvable ↥N :=
    solvable_of_solvable_injective (f := Subgroup.inclusion hN_H)
      (Subgroup.inclusion_injective hN_H)
  exact le_centralizer_of_coprime_normalizes_of_le_centralizer_fittingInG
    hAp_norm_N hCop hAp_cent_FN


end OddOrder.BG.Ch2.S08
