/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.Data.Finite.Perm
import Mathlib.Data.Nat.Choose.Lucas
import Mathlib.GroupTheory.Complement
import Mathlib.GroupTheory.GroupAction.ConjAct
import Mathlib.GroupTheory.GroupAction.Quotient
import Mathlib.GroupTheory.Nilpotent
import Mathlib.GroupTheory.Perm.Cycle.Type
import Mathlib.GroupTheory.Subgroup.Simple
import Mathlib.GroupTheory.Sylow
import OddOrder.GroupTheory.ChermakDelgado

/-!
# Basic

Prefix-split from `OddOrder.Isaacs.Ch01_Sylow.Main` (2000-line limit, issue 0103 第 2 パス).
-/

/-!
# OddOrder.Isaacs.Ch01 — Sylow Theory

Isaacs, *Finite Group Theory* (AMS GSM 92, 2008), Chapter 1
"Sylow Theory" (pp. 1-44) の Lean 化。

## 章のセクション分割

| § | 内容 | Isaacs 番号 | 状態 |
|---|---|---|---|
| 1A | 群作用と Fundamental Counting Principle | 1.1 – 1.6 | 着手中 |
| 1B | Sylow の存在定理 (Sylow E), Cauchy | 1.7 – 1.10 | TODO |
| 1C | Sylow の共役 (Sylow C / D), Frattini argument | 1.11 – 1.18 | TODO |
| 1D | 冪零群, Fitting 部分群 `F(G)` | 1.19 – 1.29 | TODO |
| 1E | 位数 \|G\|=2n (n 奇) の指数 2 正規部分群 など | 1.30 – 1.36 | TODO |
| 1F | Brodkey の定理 (Sylow が abelian の場合) | 1.37 – 1.40 | 完了 |
| 1G | Chermak–Delgado | 1.41 – 1.46 | TODO |

## 方針

mathlib 既存資産 (`Sylow`, `MulAction.orbitEquivQuotientStabilizer`,
`Subgroup.normalCore`, `Subgroup.normalCore_eq_ker`) を最大限再利用し、
Isaacs の流儀で主張を再述する薄いラッパーを与える。

主要な新規実装ターゲット (mathlib 未収載):

* **§1D Thm 1.28**: Fitting 部分群 `Fit(G)` の定義 + 「最大冪零正規部分群である」
  ことの証明 (Phase 1 の最初の本格的な新規実装)

ノート: [notes/isaacs/ch01_sylow.md](../../notes/isaacs/ch01_sylow.md)
-/

namespace OddOrder.Isaacs.Ch01

open scoped IsMulCommutative

section /- 1A: Group actions and the Fundamental Counting Principle (pp. 1-10) -/

open scoped Pointwise

variable {G : Type*} [Group G]

/-! **Isaacs Thm 1.1** (`H.normalCore = (MulAction.toPermHom G (G ⧸ H)).ker`) と
**Thm 1.4** (`MulAction.orbit G α ≃ G ⧸ MulAction.stabilizer G α`) は mathlib
`Subgroup.normalCore_eq_ker` / `MulAction.orbitEquivQuotientStabilizer` を直接
呼び出す (本ファイルではラッパーを書かない). -/

/-- **Isaacs Cor 1.2**.  `H ≤ G` で `[G:H] = n` なら，`N := core_G(H) = H.normalCore` は
`N ◁ G`, `N ≤ H` であり，`[G:N] ∣ n!`.

証明: Thm 1.1 より `G/N ↪ Sym(G/H) ≅ S_n`，よって `|G/N| ∣ |S_n| = n!`．
mathlib では `H.normalCore_eq_ker` → `index_ker` → `card_subgroup_dvd_card` + `Nat.card_perm`
を組み合わせる. -/
theorem normalCore_index_dvd_factorial (H : Subgroup G) [Finite (G ⧸ H)] :
    H.normalCore.Normal ∧ H.normalCore ≤ H ∧
      H.normalCore.index ∣ Nat.factorial H.index := by
  refine ⟨inferInstance, H.normalCore_le, ?_⟩
  rw [H.normalCore_eq_ker, Subgroup.index_ker]
  calc Nat.card (MulAction.toPermHom G (G ⧸ H)).range
      ∣ Nat.card (Equiv.Perm (G ⧸ H)) := Subgroup.card_subgroup_dvd_card _
    _ = Nat.factorial (Nat.card (G ⧸ H)) := Nat.card_perm
    _ = Nat.factorial H.index := by rw [← Subgroup.index_eq_card]

/-- **Isaacs Cor 1.3**.  `G` が単純群で `∃ H ≤ G` with `[G:H] = n > 1` なら `|G| ∣ n!`.

証明: Cor 1.2 の `N := core_G(H)` は `G` で正規．`G` 単純なので `N = ⊥` か `N = ⊤`．
`n > 1` より `H ⊊ G`，よって `N ≤ H ⊊ G`，つまり `N ≠ ⊤`．
ゆえに `N = ⊥`，`[G:⊥] = |G|`，`|G| ∣ n!`. -/
theorem card_dvd_factorial_of_simple_subgroup_index [IsSimpleGroup G] [Finite G]
    (H : Subgroup G) (hn1 : 1 < H.index) :
    Nat.card G ∣ Nat.factorial H.index := by
  have hn : H.index ≠ 0 := by omega
  haveI : Finite (G ⧸ H) := Subgroup.index_ne_zero_iff_finite.mp hn
  obtain ⟨_, hNH, hdvd⟩ := normalCore_index_dvd_factorial H
  rcases Subgroup.Normal.eq_bot_or_eq_top (inferInstance : H.normalCore.Normal)
      with hN | hN
  · rw [hN, Subgroup.index_bot] at hdvd
    exact hdvd
  · -- N = ⊤ なら H = ⊤ つまり [G:H] = 1, hn1 と矛盾
    exfalso
    have hHtop : H = ⊤ := le_antisymm le_top (hN ▸ hNH)
    rw [hHtop, Subgroup.index_top] at hn1
    exact Nat.lt_irrefl 1 hn1

/-! **Isaacs Cor 1.5** (`|conjClass x| = [G : C_G(x)]`) と **Cor 1.6**
(`|conj(H)| = [G : N_G(H)]`) は mathlib の `ConjAct.orbit_eq_carrier_conjClasses` +
`MulAction.index_stabilizer` + `Subgroup.centralizer_eq_comap_stabilizer` を
直接組合せる. -/

end -- 1A

section /- 1B: Sylow's existence theorem and Cauchy (pp. 10-17) -/

variable {G : Type*} [Group G]

/-! **Isaacs Thm 1.7** (Sylow E) は mathlib `Sylow.nonempty` を直接呼ぶ.
**Lemma 1.8** (`C(p^a m, p^a) ≡ m mod p`) は
`Choose.choose_pow_mul_pow_mul_modEq_choose_nat (b := 1)` を直接呼ぶ. -/

/-- **Isaacs Cor 1.9** (Cauchy).  有限群 `G` で素数 `p ∣ |G|` ⇒ `G` は位数 `p`
の元を持つ.

mathlib `exists_prime_orderOf_dvd_card'` の再述. -/
theorem cauchy [Finite G] {p : ℕ} [Fact p.Prime] (hdvd : p ∣ Nat.card G) :
    ∃ x : G, orderOf x = p :=
  exists_prime_orderOf_dvd_card' p hdvd

/-- A finite group is generated by any choice of one Sylow `p`-subgroup for each prime
divisor of its order. -/
theorem sylow_choice_iSup_eq_top [Finite G]
    (P : ∀ p : (Nat.card G).primeFactors, Sylow p.val G) :
    (⨆ p, (P p : Subgroup G)) = ⊤ := by
  classical
  set sup := ⨆ p, (P p : Subgroup G) with hsup_def
  have h_sup_dvd : Nat.card sup ∣ Nat.card G := Subgroup.card_subgroup_dvd_card sup
  have h_pow_dvd : ∀ p ∈ (Nat.card G).primeFactors,
      p ^ (Nat.card G).factorization p ∣ Nat.card sup := by
    intro p hp
    haveI : Fact p.Prime := ⟨Nat.prime_of_mem_primeFactors hp⟩
    have hP_le : ((P ⟨p, hp⟩ : Subgroup G)) ≤ sup :=
      le_iSup (fun q : (Nat.card G).primeFactors => (P q : Subgroup G)) ⟨p, hp⟩
    have h_dvd := Subgroup.card_dvd_of_le hP_le
    rwa [Sylow.card_eq_multiplicity] at h_dvd
  have h_le : ∀ p, (Nat.card G).factorization p ≤ (Nat.card sup).factorization p := by
    intro p
    rcases Nat.eq_zero_or_pos ((Nat.card G).factorization p) with h0 | hpos
    · rw [h0]
      exact Nat.zero_le _
    · have hp_in : p ∈ (Nat.card G).primeFactors := by
        rw [← Nat.support_factorization]
        exact Finsupp.mem_support_iff.mpr (by omega)
      exact ((Nat.prime_of_mem_primeFactors hp_in).pow_dvd_iff_le_factorization
        (Nat.ne_of_gt Nat.card_pos)).mp (h_pow_dvd p hp_in)
  have h_le_prime : ∀ p, (Nat.card sup).factorization p ≤ (Nat.card G).factorization p :=
    fun p => (Nat.factorization_le_iff_dvd (Nat.ne_of_gt Nat.card_pos)
      (Nat.ne_of_gt Nat.card_pos)).mpr h_sup_dvd p
  exact Subgroup.eq_top_of_card_eq sup
    (Nat.eq_of_factorization_eq (Nat.ne_of_gt Nat.card_pos) (Nat.ne_of_gt Nat.card_pos)
      (fun p => le_antisymm (h_le_prime p) (h_le p)))

/-- A finite group is generated by all of its Sylow subgroups. -/
theorem iSup_sylow_eq_top [Finite G] :
    (⨆ p : (Nat.card G).primeFactors, ⨆ P : Sylow p.val G, (P : Subgroup G)) = ⊤ := by
  classical
  apply le_antisymm le_top
  rw [← sylow_choice_iSup_eq_top (G := G) (fun p => default)]
  exact iSup_le fun p =>
    (le_iSup (fun P : Sylow p.val G => (P : Subgroup G)) default).trans
      (le_iSup (fun q : (Nat.card G).primeFactors =>
        ⨆ P : Sylow q.val G, (P : Subgroup G)) p)

/-! **Isaacs Lemma 1.10** (特性 in 正規 ⇒ 正規) は mathlib
`Subgroup.normal_of_characteristic_of_normal` がインスタンスとして提供している
ので typeclass で自動推論される. 呼び出し側では `inferInstance` で取得. -/

end -- 1B

section /- 1C: Sylow C / D, Frattini argument (pp. 13-17) -/

open Pointwise Subgroup MulAction

variable {G : Type*} [Group G] {p : ℕ} [Fact p.Prime]

/-! **Isaacs Thm 1.11** (任意 `p`-部分群は Sylow の共役に含まれる),
**Thm 1.12 Sylow C** (任意 2 Sylow が共役),
**Lemma 1.13 Frattini argument**,
**Thm 1.14 Sylow D** (任意 `p`-部分群は Sylow に含まれる),
**Cor 1.15** (`n_p(G) = [G : N_G(S)]`) はすべて mathlib に直接対応がある:

* Thm 1.11: `IsPGroup.exists_le_sylow` + `Sylow.orbit_eq_top` を組合せる
* Thm 1.12: `MulAction.exists_smul_eq` (`Sylow.isPretransitive_of_finite`)
* Lemma 1.13: `Sylow.normalizer_sup_eq_top'`
* Thm 1.14: `IsPGroup.exists_le_sylow`
* Cor 1.15: `Sylow.card_eq_index_normalizer`

呼び出し側で直接 mathlib 名を使う. -/

/-- **Isaacs Thm 1.16**.  `n_p(G) > 1` のとき, distinct `S, T ∈ Syl_p(G)` で
`|S ∩ T|` が最大となるペアを取ると `n_p(G) ≡ 1 (mod |S : S ∩ T|)`.

証明の方針 (Isaacs p. 15): `S` を `p`-部分群とみて `Sylow p G` に共役作用. 軌道分解は次の構造:
* `{S}` 自身は固定点 1 個 (`IsPGroup.sylow_mem_fixedPoints_iff` で唯一固定点と判明).
* 他の任意の Sylow `Q` の軌道サイズは `(S ⊓ Q).relIndex S` (`IsPGroup.inf_normalizer_sylow`).
* 最大性 `|S ⊓ Q| ≤ |D|` より `(S ⊓ Q).relIndex S ≥ D.relIndex S =: d`.
* `S` は `p`-群 ⇒ 各軌道サイズは `p` 冪. したがって `d ∣ (S ⊓ Q).relIndex S`.
* クラス公式で合計 ≡ 1 (mod d). -/
theorem card_sylow_modEq_one_of_max_inter
    [Finite G] {p : ℕ} [Fact p.Prime] [Finite (Sylow p G)]
    (_hgt : 1 < Nat.card (Sylow p G))
    (S T : Sylow p G) (_hST : S ≠ T)
    (hmax : ∀ S' T' : Sylow p G, S' ≠ T' →
      Nat.card ((S' : Subgroup G) ⊓ (T' : Subgroup G) : Subgroup G) ≤
      Nat.card ((S : Subgroup G) ⊓ (T : Subgroup G) : Subgroup G)) :
    Nat.card (Sylow p G) ≡ 1
      [MOD ((S : Subgroup G) ⊓ (T : Subgroup G) : Subgroup G).relIndex S] := by
  classical
  -- 表記: Ssub := ↑S, Tsub := ↑T, D := S ⊓ T (sub of G), d := |S : D|
  set Ssub : Subgroup G := (S : Subgroup G) with hSsubDef
  set Tsub : Subgroup G := (T : Subgroup G) with hTsubDef
  set D : Subgroup G := Ssub ⊓ Tsub with hDdef
  set d : ℕ := D.relIndex Ssub with hd_def
  -- 各 Q : Sylow p G について Ssub-軌道のサイズ = (Ssub ⊓ Q).relIndex Ssub.
  have orbit_card : ∀ Q : Sylow p G,
      Nat.card (MulAction.orbit Ssub Q) = (Ssub ⊓ (Q : Subgroup G)).relIndex Ssub := by
    intro Q
    -- stabilizer ↥Ssub Q を (N_G(Q)).subgroupOf Ssub と同定する.
    have hstab_eq : MulAction.stabilizer Ssub Q
        = (Subgroup.normalizer (Q : Set G)).subgroupOf Ssub := by
      ext ⟨g, hg⟩
      have hsmul : (⟨g, hg⟩ : Ssub) • Q = g • Q := rfl
      rw [MulAction.mem_stabilizer_iff, Subgroup.mem_subgroupOf, hsmul,
          Sylow.smul_eq_iff_mem_normalizer]
    -- index も従って書き換え可能.
    have hstab : (MulAction.stabilizer Ssub Q).index =
        (Ssub ⊓ (Q : Subgroup G)).relIndex Ssub := by
      rw [hstab_eq]
      -- ((N_G Q).subgroupOf Ssub).index = (N_G Q).relIndex Ssub  (定義).
      -- = (Ssub ⊓ N_G Q).relIndex Ssub (`inf_relIndex_right`).
      -- = (Ssub ⊓ Q).relIndex Ssub (`IsPGroup.inf_normalizer_sylow`).
      change (Subgroup.normalizer (Q : Set G)).relIndex Ssub
        = (Ssub ⊓ (Q : Subgroup G)).relIndex Ssub
      rw [← Subgroup.inf_relIndex_right (Subgroup.normalizer (Q : Set G)) Ssub, inf_comm,
          S.2.inf_normalizer_sylow Q]
    rw [Nat.card_coe_set_eq, ← MulAction.index_stabilizer, hstab]
  -- d は p 冪. (S は p-群なので Ssub の任意の部分群の index も p 冪.)
  have hd_pow : ∃ k : ℕ, d = p ^ k := by
    have : (D.subgroupOf Ssub).FiniteIndex := ⟨Nat.card_pos.ne'⟩
    obtain ⟨k, hk⟩ := S.2.index (D.subgroupOf Ssub)
    exact ⟨k, hk⟩
  -- 各 Q について軌道サイズも p 冪.
  have orbit_card_pow : ∀ Q : Sylow p G, ∃ k, Nat.card (MulAction.orbit Ssub Q) = p ^ k :=
    fun Q => S.2.card_orbit Q
  -- 補題: H ≤ K ⇒ Nat.card K = Nat.card H * H.relIndex K.
  have card_eq_mul_relIndex : ∀ H K : Subgroup G, H ≤ K →
      Nat.card K = Nat.card H * H.relIndex K := by
    intro H K hHK
    have heq : Nat.card (H.subgroupOf K) * (H.subgroupOf K).index = Nat.card K :=
      Subgroup.card_mul_index _
    rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe hHK).toEquiv] at heq
    exact heq.symm
  have card_eq_D_mul_d : Nat.card Ssub = Nat.card (D : Subgroup G) * d :=
    card_eq_mul_relIndex D Ssub inf_le_left
  -- 同様に |Ssub| = |Ssub ⊓ Q| * (Ssub ⊓ Q).relIndex Ssub.
  have card_eq_inf_mul_relIndex : ∀ Q : Sylow p G,
      Nat.card Ssub = Nat.card ((Ssub ⊓ (Q : Subgroup G)) : Subgroup G) *
        (Ssub ⊓ (Q : Subgroup G)).relIndex Ssub := fun Q =>
    card_eq_mul_relIndex (Ssub ⊓ (Q : Subgroup G)) Ssub inf_le_left
  -- 各 Q ≠ S について軌道サイズは d で割り切れる.
  have d_dvd_orbit_ne : ∀ Q : Sylow p G, Q ≠ S →
      d ∣ Nat.card (MulAction.orbit Ssub Q) := by
    intro Q hQ
    obtain ⟨kd, hkd⟩ := hd_pow
    obtain ⟨kq, hkq⟩ := orbit_card_pow Q
    -- |Ssub ⊓ Q| ≤ |D| からの不等式.  hmax Q S は |Q ⊓ S| ≤ |D| をくれるので inf_comm.
    have hcardLE :
        Nat.card ((Ssub ⊓ (Q : Subgroup G)) : Subgroup G) ≤ Nat.card (D : Subgroup G) := by
      have := hmax Q S hQ
      rwa [inf_comm] at this
    have hSsub_eq1 := card_eq_D_mul_d
    have hSsub_eq2 := card_eq_inf_mul_relIndex Q
    -- |D| * d = |Ssub ⊓ Q| * (Ssub ⊓ Q).relIndex Ssub = |Ssub|
    have hmul : Nat.card (D : Subgroup G) * d = Nat.card ((Ssub ⊓ (Q : Subgroup G)) : Subgroup G) *
        (Ssub ⊓ (Q : Subgroup G)).relIndex Ssub := hSsub_eq1.symm.trans hSsub_eq2
    have hD_pos : 0 < Nat.card (D : Subgroup G) := Nat.card_pos
    -- d ≤ Nat.card (orbit Ssub Q)
    have hd_le_orbit : d ≤ Nat.card (MulAction.orbit Ssub Q) := by
      rw [orbit_card Q]
      have h := Nat.mul_le_mul_right ((Ssub ⊓ (Q : Subgroup G)).relIndex Ssub) hcardLE
      -- h : |Ssub ⊓ Q| * relIndex ≤ |D| * relIndex
      -- but |D| * d = |Ssub ⊓ Q| * relIndex, so |D| * d ≤ |D| * relIndex.
      have h2 : Nat.card (D : Subgroup G) * d ≤ Nat.card (D : Subgroup G) *
          (Ssub ⊓ (Q : Subgroup G)).relIndex Ssub := hmul ▸ h
      exact Nat.le_of_mul_le_mul_left h2 hD_pos
    -- 比較を p 冪に持ち込む.
    rw [hkq, hkd]
    have hp1 : 1 < p := (Fact.out : p.Prime).one_lt
    -- d = p^kd ≤ p^kq = orbit. ⇒ kd ≤ kq ⇒ p^kd ∣ p^kq.
    have hd_le_pow : p ^ kd ≤ p ^ kq := by rw [← hkd, ← hkq]; exact hd_le_orbit
    have hkle : kd ≤ kq := (Nat.pow_le_pow_iff_right hp1).mp hd_le_pow
    exact pow_dvd_pow p hkle
  -- 軌道 |orbit S| = 1.
  have orbit_S_eq_one : Nat.card (MulAction.orbit Ssub S) = 1 := by
    rw [orbit_card, inf_idem, Subgroup.relIndex_self]
  -- クラス公式: |Sylow p G| = Σ_{ω : Quot orbitRel} |orbit(ω.out)|.
  -- これを Sylow p G の有限和として扱い, S の軌道のみ 1 で他は d の倍数,
  -- よって全体は 1 mod d.
  -- 実装: orbitRel.Quotient 上の和に分割.
  -- 軌道 Quotient ⟦Q⟧ をパラメータとして, 各 ω 毎に Q := ω.out をとり
  -- Nat.card (MulAction.orbit Ssub Q) を加算.
  letI : Fintype (Sylow p G) := Fintype.ofFinite _
  letI : Fintype (MulAction.orbitRel.Quotient Ssub (Sylow p G)) := Fintype.ofFinite _
  -- 各点 P に対し  Fintype (orbit Ssub P)
  haveI : ∀ P : Sylow p G, Fintype (MulAction.orbit Ssub P) := fun P => Fintype.ofFinite _
  -- 全体 |Sylow p G| = Σ orbit
  have hsum : Nat.card (Sylow p G) =
      ∑ ω : MulAction.orbitRel.Quotient Ssub (Sylow p G),
        Nat.card (MulAction.orbit Ssub ω.out) := by
    rw [Nat.card_congr (MulAction.selfEquivSigmaOrbits Ssub (Sylow p G)), Nat.card_sigma]
  -- 軌道の代表は本質的に固定点 (= S) かそれ以外.
  -- ⟦S⟧ に対応する軌道のサイズは 1, 他は d の倍数.
  -- ω.out は同じ軌道の他の元 Q かもしれないが,
  --   orbit Ssub Q = orbit Ssub S が成り立つので Nat.card は同じ.
  --   さらに Q ∈ orbit Ssub S なので Q = S とは限らないが,
  --   "軌道に S を含む" ⇔ ω.out ∈ orbit Ssub S ⇔ ω = ⟦S⟧.
  -- d ∣ (Nat.card (Sylow p G) - 1) を示す.
  rw [Nat.ModEq]
  rw [hsum]
  -- 和を ⟦S⟧ の軌道と他に分割.
  -- ⟦S⟧ : MulAction.orbitRel.Quotient Ssub (Sylow p G)
  -- ⟦S⟧.out ∈ orbit Ssub S, よって Nat.card (orbit ⟦S⟧.out) = 1
  --   (∵ orbit ⟦S⟧.out = orbit S, both contain S which is fixed)
  -- Set s := ⟦S⟧ : the orbit class
  set Squot : MulAction.orbitRel.Quotient Ssub (Sylow p G) := ⟦S⟧ with hSquot
  have hSquot_card_eq : Nat.card (MulAction.orbit Ssub Squot.out) = 1 := by
    -- Squot.out ∈ orbit Ssub S なので orbit Squot.out = orbit S
    have horbit_eq : MulAction.orbit Ssub Squot.out = MulAction.orbit Ssub S := by
      apply MulAction.orbit_eq_iff.mpr
      -- need: Squot.out ∈ MulAction.orbit Ssub S
      -- ⟦Squot.out⟧ = Squot = ⟦S⟧, so Squot.out ≈ S
      have heq : (⟦Squot.out⟧ : MulAction.orbitRel.Quotient Ssub (Sylow p G)) = ⟦S⟧ := by
        rw [Quotient.out_eq, hSquot]
      have hrel : MulAction.orbitRel Ssub (Sylow p G) Squot.out S := Quotient.exact heq
      exact hrel
    rw [horbit_eq, orbit_S_eq_one]
  -- 残りの軌道のサイズは d で割り切れる.
  have hd_dvd_rest : ∀ ω : MulAction.orbitRel.Quotient Ssub (Sylow p G), ω ≠ Squot →
      d ∣ Nat.card (MulAction.orbit Ssub ω.out) := by
    intro ω hω
    -- ω.out ≠ S(と同じ軌道)
    have hne : ω.out ≠ S := by
      intro h
      apply hω
      rw [hSquot]
      rw [← Quotient.out_eq' ω, h]
    -- ω.out が S と同じ軌道なら ω = ⟦S⟧ となり矛盾.
    -- d ∣ (orbit Ssub ω.out).card は ω.out ≠ S だけでは出ない…
    -- 鍵: d_dvd_orbit_ne は Q ≠ S を要求. しかし注意: S と "同じ軌道" にいる
    --   別の Sylow Q (S ≠ Q)も dotodes... 実は orbit Ssub S = {S}, なので
    --   Q ∈ orbit Ssub S ⇔ Q = S.  したがって S と同じ軌道は S 自身のみ.
    --   ω ≠ ⟦S⟧ なら ω.out ∉ orbit Ssub S, 特に ω.out ≠ S.
    -- d ∣ (orbit ω.out).card は d_dvd_orbit_ne ω.out (h : ω.out ≠ S) で OK.
    exact d_dvd_orbit_ne ω.out hne
  -- 和を分割: ∑ω = orbit(Squot.out) + ∑_{ω ∈ univ.erase Squot} orbit(ω.out)
  rw [← Finset.add_sum_erase (Finset.univ : Finset _)
      (fun ω : MulAction.orbitRel.Quotient Ssub (Sylow p G) =>
        Nat.card (MulAction.orbit Ssub ω.out))
      (Finset.mem_univ Squot)]
  rw [hSquot_card_eq]
  -- 残部 d.
  have hd_dvd_sum : d ∣ ∑ x ∈ (Finset.univ.erase Squot),
      Nat.card (MulAction.orbit Ssub x.out) := by
    apply Finset.dvd_sum
    intro x hx
    rw [Finset.mem_erase] at hx
    exact hd_dvd_rest x hx.1
  rcases hd_dvd_sum with ⟨q, hq⟩
  -- target: (1 + ∑ rest) % d = 1 % d
  -- We have ∑ rest = d * q, so (1 + d*q) % d = 1 % d.
  rw [hq]
  -- want: (1 + d * q) % d = 1 % d
  exact Nat.add_mul_mod_self_left 1 d q

/-! **Isaacs Cor 1.17** (`n_p ≡ 1 mod p`) は mathlib `card_sylow_modEq_one` を,
**Lemma 1.18** (`N_G(P)` 内の `p`-部分群は `P` に含まれる) は
`IsPGroup.inf_normalizer_sylow` を直接呼ぶ. -/

end -- 1C

section /- 1D: Nilpotent groups, Fitting subgroup F(G) (pp. 21-29) -/

open scoped Pointwise

variable {G : Type*} [Group G]

/-! ### Isaacs Thm 1.19–1.25: 冪零群と p-群の基本構造 -/

/-- **Isaacs Thm 1.19**.  `P` を有限 `p`-群, `N` をその非自明な正規部分群とすると,
`N ∩ Z(P)` は非自明.

証明骨子: `ConjAct P` の作用を `N` (正規部分群) に制限して考える
(`Subgroup.conjMulDistribMulAction`).  `IsPGroup p P` から `IsPGroup p (ConjAct P)`,
`IsPGroup.card_modEq_card_fixedPoints` で `|N| ≡ |fixedPoints| (mod p)`.
`N` 非自明 p-群より `p ∣ |N|`, ゆえ `p ∣ |fixedPoints|`. `1 ∈ fixedPoints` なので
`|fixedPoints| ≥ 1`, よって `≥ p ≥ 2`, 非自明. fixed point は `N ∩ Z(P)` の元. -/
theorem IsPGroup.normal_inf_center_nontrivial {P : Type*} [Group P] [Finite P]
    {p : ℕ} [Fact p.Prime] (hP : IsPGroup p P)
    {N : Subgroup P} [N.Normal] (hN : Nontrivial N) :
    Nontrivial ((N ⊓ Subgroup.center P : Subgroup P)) := by
  -- ConjAct P acts on N (since N is normal), IsPGroup p (ConjAct P).
  haveI hCA : IsPGroup p (ConjAct P) := hP.of_equiv ConjAct.toConjAct
  -- p divides |N| since N is a nontrivial p-group.
  have hpN : p ∣ Nat.card N := by
    obtain ⟨n, hn0, hn⟩ := (hP.to_subgroup N).nontrivial_iff_card.mp hN
    exact hn.symm ▸ dvd_pow_self _ hn0.ne'
  -- 1 is fixed under the ConjAct P action on N.
  have h1 : (1 : N) ∈ MulAction.fixedPoints (ConjAct P) N := by
    intro g
    apply Subtype.ext
    change (g : ConjAct P) • ((1 : N) : P) = ((1 : N) : P)
    rw [ConjAct.smul_def]
    simp
  -- p ∣ |N| and ∃ fixed point ⇒ ∃ another fixed point ≠ 1.
  obtain ⟨g, hgFix, hg1⟩ :=
    hCA.exists_fixed_point_of_prime_dvd_card_of_fixed_point (α := N) hpN h1
  -- (g : P) is central, and g ∈ N, hence ≠ 1 gives nontriviality of N ⊓ center P.
  have hg_center : (g : P) ∈ Subgroup.center P := by
    rw [Subgroup.mem_center_iff]
    intro h
    have heq : ConjAct.toConjAct h • g = g := hgFix _
    have hcoe : (((ConjAct.toConjAct h) • g : N) : P) = (g : P) := by rw [heq]
    rw [ConjAct.Subgroup.val_conj_smul, ConjAct.toConjAct_smul_eq_mulAut_conj,
      MulAut.conj_apply] at hcoe
    -- hcoe : h * (g : P) * h⁻¹ = (g : P)
    rw [mul_inv_eq_iff_eq_mul] at hcoe
    exact hcoe
  refine ⟨⟨1, ⟨((g : N) : P), Subgroup.mem_inf.mpr ⟨g.2, hg_center⟩⟩, ?_⟩⟩
  intro heq
  apply hg1
  -- heq : (1 : (N ⊓ center P)) = ⟨(g : P), ...⟩ at the inf level
  -- goal: 1 = g at the N level
  apply Subtype.ext  -- to P level
  have := congrArg (fun x : (N ⊓ Subgroup.center P : Subgroup P) => (x : P)) heq
  simpa using this

/-! **Isaacs Lemma 1.20** は冪零性のいくつかの特性化を主張するが, (1)-(2) は
`IsNilpotent` の定義そのもの, (3) 「全 Sylow 正規」は mathlib
`Group.isNilpotent_of_finite_tfae` 全体に対応する (Thm 1.26 慣用名
`isNilpotent_iff_forall_sylow_normal` で扱う).

**Thm 1.20** (冪零 ⇔ NormalizerCondition) は `Group.isNilpotent_of_finite_tfae.out 0 1`,
**Thm 1.21** (`upperCentralSeries G (nilpotencyClass G) = ⊤`) は
`upperCentralSeries_nilpotencyClass` を直接呼ぶ. -/

/-- **Isaacs Thm 1.22** (Normalizer Condition).  有限冪零群 `G` で真部分群 `H < G` ならば
`H < N_G(H)`.

mathlib `Group.normalizerCondition_of_isNilpotent` の再述. -/
theorem lt_normalizer_of_isNilpotent_of_lt_top [Group.IsNilpotent G]
    {H : Subgroup G} (hH : H < ⊤) :
    H < Subgroup.normalizer H :=
  Group.normalizerCondition_of_isNilpotent H hH

/-- **Isaacs Lemma 1.23**.  `P` を有限 `p`-群, `N, M ⊴ P` で `N < M` ならば,
ある `L ⊴ P` が存在して `N < L`, `L ≤ M`, かつ `N.relIndex L = p`.

証明: `M.map (mk' N) ⊴ P/N` は非自明 (`N < M`).  `P/N` は finite p-群なので
Thm 1.19 で `M.map (mk' N) ⊓ Z(P/N)` も非自明. Cauchy で位数 `p` の元 `y` を取り,
`zpowers y ≤ Z(P/N)` ゆえ `P/N` で正規.  `L := (zpowers y).comap (mk' N)` が
条件 (`N < L ≤ M`, `relIndex = p`) を満たす. -/
theorem IsPGroup.exists_normal_index_eq_prime {P : Type*} [Group P] [Finite P]
    {p : ℕ} [Fact p.Prime] (hP : IsPGroup p P)
    {N M : Subgroup P} [N.Normal] [M.Normal] (hNM : N < M) :
    ∃ L : Subgroup P, L.Normal ∧ N < L ∧ L ≤ M ∧ N.relIndex L = p := by
  -- P/N も p-群
  haveI hQuot_pgroup : IsPGroup p (P ⧸ N) := hP.to_quotient N
  -- M.map (mk' N) ⊴ P/N
  let M' : Subgroup (P ⧸ N) := M.map (QuotientGroup.mk' N)
  haveI : M'.Normal := inferInstance
  -- M' は非自明 (N < M)
  have hM'_nontriv : Nontrivial M' := by
    rw [Subgroup.nontrivial_iff_ne_bot]
    intro hbot
    obtain ⟨m, hmM, hmN⟩ := SetLike.exists_of_lt hNM
    apply hmN
    have hm_in : QuotientGroup.mk' N m ∈ M' := Subgroup.mem_map.mpr ⟨m, hmM, rfl⟩
    rw [hbot, Subgroup.mem_bot] at hm_in
    exact (QuotientGroup.eq_one_iff m).mp hm_in
  -- Thm 1.19 で M' ⊓ Z(P/N) も非自明.  Quotient is finite.
  haveI : Finite (P ⧸ N) := Quotient.finite _
  have hinf_nontriv : Nontrivial ((M' ⊓ Subgroup.center (P ⧸ N) : Subgroup (P ⧸ N))) :=
    IsPGroup.normal_inf_center_nontrivial hQuot_pgroup hM'_nontriv
  -- Cauchy: 位数 p の元を取る
  have h_subgroup_pgroup : IsPGroup p (↥(M' ⊓ Subgroup.center (P ⧸ N))) :=
    hQuot_pgroup.to_subgroup _
  obtain ⟨k, hk0, hk_card⟩ := h_subgroup_pgroup.nontrivial_iff_card.mp hinf_nontriv
  have hp_dvd_inf : p ∣ Nat.card (↥(M' ⊓ Subgroup.center (P ⧸ N))) := by
    rw [hk_card]; exact dvd_pow_self _ hk0.ne'
  obtain ⟨ysub, hy_ord⟩ := exists_prime_orderOf_dvd_card' p hp_dvd_inf
  set y : P ⧸ N := (ysub : P ⧸ N)
  have hy_M : y ∈ M' := (Subgroup.mem_inf.mp ysub.2).1
  have hy_Z : y ∈ Subgroup.center (P ⧸ N) := (Subgroup.mem_inf.mp ysub.2).2
  have hy_order : orderOf y = p := by
    rw [show y = ((ysub : ↥(M' ⊓ Subgroup.center (P ⧸ N))) : P ⧸ N) from rfl]
    exact (orderOf_injective ((M' ⊓ Subgroup.center (P ⧸ N)).subtype)
      Subtype.coe_injective ysub).trans hy_ord
  -- ⟨y⟩ ≤ Z(P/N), 正規
  have hzpowers_le_center : Subgroup.zpowers y ≤ Subgroup.center (P ⧸ N) :=
    Subgroup.zpowers_le.mpr hy_Z
  haveI hzpowers_normal : (Subgroup.zpowers y).Normal := by
    refine ⟨fun n hn g => ?_⟩
    have hn_center := hzpowers_le_center hn
    rw [Subgroup.mem_center_iff] at hn_center
    have hgn : g * n = n * g := hn_center g
    have : g * n * g⁻¹ = n := by rw [hgn, mul_inv_cancel_right]
    rw [this]; exact hn
  have hzpowers_le_M' : Subgroup.zpowers y ≤ M' := Subgroup.zpowers_le.mpr hy_M
  set L : Subgroup P := (Subgroup.zpowers y).comap (QuotientGroup.mk' N) with hL_def
  refine ⟨L, inferInstance, ?_, ?_, ?_⟩
  · -- N < L
    refine lt_of_le_of_ne ?_ ?_
    · intro x hx
      rw [hL_def, Subgroup.mem_comap, QuotientGroup.mk'_apply,
        (QuotientGroup.eq_one_iff x).mpr hx]
      exact (Subgroup.zpowers y).one_mem
    · intro heq
      have hy_eq_one : y = 1 := by
        obtain ⟨pbar, hpbar⟩ := QuotientGroup.mk'_surjective N y
        have hpbar_L : pbar ∈ L := by
          rw [hL_def, Subgroup.mem_comap, hpbar]; exact Subgroup.mem_zpowers y
        rw [← heq] at hpbar_L
        rw [← hpbar]; exact (QuotientGroup.eq_one_iff pbar).mpr hpbar_L
      have hOrder1 : orderOf (1 : P ⧸ N) = p := hy_eq_one ▸ hy_order
      rw [orderOf_one] at hOrder1
      exact (Fact.out (p := p.Prime)).one_lt.ne hOrder1
  · -- L ≤ M
    intro x hx
    simp only [hL_def, Subgroup.mem_comap, QuotientGroup.mk'_apply] at hx
    have hx_M' : QuotientGroup.mk x ∈ M' := hzpowers_le_M' hx
    obtain ⟨m, hmM, hmEq⟩ := Subgroup.mem_map.mp hx_M'
    have hmx : (QuotientGroup.mk m : P ⧸ N) = QuotientGroup.mk x := by
      have := hmEq; simp only [QuotientGroup.mk'_apply] at this; exact this
    have hinN : m⁻¹ * x ∈ N := QuotientGroup.eq.mp hmx
    have hmix_M : m⁻¹ * x ∈ M := hNM.le hinN
    have hxeq : x = m * (m⁻¹ * x) := by group
    rw [hxeq]; exact M.mul_mem hmM hmix_M
  · -- N.relIndex L = p
    have hN_le_L : N ≤ L := by
      intro x hx
      rw [hL_def, Subgroup.mem_comap, QuotientGroup.mk'_apply,
        (QuotientGroup.eq_one_iff x).mpr hx]
      exact (Subgroup.zpowers y).one_mem
    have hLidx : L.index = (Subgroup.zpowers y).index :=
      Subgroup.index_comap_of_surjective (Subgroup.zpowers y) (QuotientGroup.mk'_surjective N)
    have hLag1 : Nat.card (Subgroup.zpowers y) * (Subgroup.zpowers y).index = Nat.card (P ⧸ N) :=
      (Subgroup.zpowers y).card_mul_index
    have hzy_card : Nat.card (Subgroup.zpowers y) = p := by rw [Nat.card_zpowers, hy_order]
    have hLag2 : N.relIndex L * L.index = N.index := Subgroup.relIndex_mul_index hN_le_L
    have hN_index : N.index = Nat.card (P ⧸ N) := rfl
    have h_N_eq : N.index = p * L.index := by rw [hN_index, ← hLag1, hzy_card, hLidx]
    have h_eq : N.relIndex L * L.index = p * L.index := by rw [hLag2, h_N_eq]
    haveI : Finite (P ⧸ L) := Quotient.finite _
    have hL_index_ne_zero : L.index ≠ 0 := Nat.card_pos.ne'
    exact Nat.eq_of_mul_eq_mul_right (Nat.pos_of_ne_zero hL_index_ne_zero) h_eq

/-! **Isaacs Cor 1.24** (弱形, `p`-群が各 `m ≤ n` で位数 `p^m` 部分群を持つ) は
mathlib `Sylow.exists_subgroup_card_pow_prime_of_le_card` を, **Cor 1.25** (Sylow E
の一般化 `p^m ∣ |G| ⇒ 位数 `p^m` 部分群存在) は `Sylow.exists_subgroup_card_pow_prime`
を直接呼ぶ. -/

/-! ### O_p(G) と Fitting 部分群 F(G)

Isaacs §1D 後半の主要新規実装。詳細設計は
[notes/isaacs/ch01_sylow_d_fitting.md](../../notes/isaacs/ch01_sylow_d_fitting.md)。

`opCore p G` (= `O_p(G)`) は全 Sylow `p`-部分群の共通部分として定義し,
最大の正規 `p`-部分群であることを示す (Isaacs Problem 1B.2). この上に
`fitting G` (= `F(G)`) を `⨆_{p prime} opCore p G` として乗せる. -/

/-- `O_p(G)`: `G` の全 Sylow `p`-部分群の共通部分.  Isaacs Problem 1B.2 で示される
ように, これは `G` の最大の正規 `p`-部分群と一致する.

mathlib 未収載のため新規定義 (将来 mathlib に `Subgroup.opCore` として PR したい形). -/
def opCore (p : ℕ) (G : Type*) [Group G] : Subgroup G :=
  ⨅ P : Sylow p G, (P : Subgroup G)

@[simp]
theorem mem_opCore {p : ℕ} {x : G} :
    x ∈ opCore p G ↔ ∀ P : Sylow p G, x ∈ (P : Subgroup G) := by
  simp [opCore, Subgroup.mem_iInf]

theorem opCore_le {p : ℕ} (P : Sylow p G) : opCore p G ≤ (P : Subgroup G) :=
  iInf_le _ P

/-- `O_p(G)` は `p`-部分群 (Sylow に含まれるから).

`[Fact p.Prime]` 必須 (`Sylow.nonempty` から少なくとも 1 つの Sylow を取るため). -/
theorem opCore_isPGroup (p : ℕ) [Fact p.Prime] (G : Type*) [Group G] :
    IsPGroup p (opCore p G) := by
  obtain ⟨P⟩ := Sylow.nonempty (p := p) (G := G)
  exact P.2.of_injective (Subgroup.inclusion (opCore_le P))
    (Subgroup.inclusion_injective _)

/-- `O_p(G)` は `G` で正規.
証明: `Subgroup.Normal.of_conjugate_fixed` を使い,
`∀ g : G, MulAut.conj g • opCore p G = opCore p G` を示す.
各 `g` について `MulAut.conj g` は Sylow 部分群を Sylow 部分群に写す (`g • P ∈ Sylow p G`)
ので, 全 Sylow の共通部分 `opCore p G` も共役不変. -/
instance opCore.normal (p : ℕ) (G : Type*) [Group G] : (opCore p G).Normal := by
  apply Subgroup.Normal.of_conjugate_fixed
  intro g
  ext x
  simp only [mem_opCore, Subgroup.mem_pointwise_smul_iff_inv_smul_mem, MulAut.smul_def]
  -- After simp: ∀ P, (MulAut.conj g)⁻¹ x ∈ ↑P  ↔  ∀ P, x ∈ ↑P
  -- Here ↑P is the Subgroup G coercion via CoeOut (Sylow p G) (Subgroup G)
  constructor
  · intro h P
    -- Apply h to (g⁻¹ • P : Sylow p G); then unfold the smul at Subgroup level
    have hQ : (MulAut.conj g)⁻¹ x ∈ (↑(g⁻¹ • P) : Subgroup G) := h (g⁻¹ • P)
    rw [Sylow.coe_subgroup_smul, ← map_inv,
        Subgroup.mem_pointwise_smul_iff_inv_smul_mem] at hQ
    simp only [map_inv, inv_inv, MulAut.smul_def] at hQ
    rwa [MulAut.apply_inv_self] at hQ
  · intro h P
    -- Apply h to (g • P : Sylow p G); then unfold the smul at Subgroup level
    have hQ : x ∈ (↑(g • P) : Subgroup G) := h (g • P)
    rw [Sylow.coe_subgroup_smul,
        Subgroup.mem_pointwise_smul_iff_inv_smul_mem] at hQ
    exact hQ

/-- `O_p(G)` は `G` で特性的 (任意の自己同型 `φ : G ≃* G` で不変).

証明: `characteristic_iff_le_comap` 経由. 任意の `φ` と `x ∈ opCore p G` について,
全 Sylow `Q` に対し `Q.comapOfInjective φ.toMonoidHom` も Sylow `p` で,
`x ∈ Q.comapOfInjective ...` ⇔ `φ x ∈ Q`. -/
instance opCore.characteristic (p : ℕ) (G : Type*) [Group G] :
    (opCore p G).Characteristic := by
  rw [Subgroup.characteristic_iff_le_comap]
  intro φ x hx
  rw [Subgroup.mem_comap, mem_opCore]
  rw [mem_opCore] at hx
  intro Q
  have hinj : Function.Injective (φ.toMonoidHom : G →* G) := φ.injective
  have hrange : (Q : Subgroup G) ≤ (φ.toMonoidHom : G →* G).range := by
    rw [MonoidHom.range_eq_top.mpr φ.surjective]; exact le_top
  -- `Q.comapOfInjective φ.toMonoidHom hinj hrange : Sylow p G` and its coercion is `Q.comap φ`.
  have hxQ' := hx (Q.comapOfInjective (φ.toMonoidHom : G →* G) hinj hrange)
  rwa [Sylow.coe_comapOfInjective, Subgroup.mem_comap] at hxQ'

/-- **Isaacs Problem 1B.2**. 任意の正規 `p`-部分群 `N` は `opCore p G` に含まれる.
これにより `opCore p G` は `G` の最大正規 `p`-部分群である.

証明: Sylow D (`IsPGroup.exists_le_sylow`) で `N ≤ Q` となる Sylow `Q` を取り,
任意の Sylow `P` に対して Sylow C (`[Finite (Sylow p G)]`) で `∃ g, P = g • Q` を取る.
`N` の正規性から `N = MulAut.conj g • N ≤ MulAut.conj g • Q = ↑(g • Q) = ↑P`. -/
theorem normal_pgroup_le_opCore {p : ℕ} [Fact p.Prime] {G : Type*} [Group G]
    [Finite (Sylow p G)]
    {N : Subgroup G} [N.Normal] (hN : IsPGroup p N) :
    N ≤ opCore p G := by
  rw [opCore, le_iInf_iff]
  intro P
  obtain ⟨Q, hNQ⟩ := hN.exists_le_sylow
  obtain ⟨g, hgQ⟩ := MulAction.exists_smul_eq G Q P
  calc (N : Subgroup G)
      = MulAut.conj g • N := (Subgroup.Normal.conj_smul_eq_self g N).symm
    _ ≤ MulAut.conj g • (Q : Subgroup G) :=
        Subgroup.pointwise_smul_le_pointwise_smul_iff.mpr hNQ
    _ = ↑(g • Q) := Sylow.coe_subgroup_smul.symm
    _ = ↑P := by rw [hgQ]

/-- A normal Sylow `p`-subgroup is the `p`-core. -/
theorem Sylow.eq_opCore_of_normal {p : ℕ} [Fact p.Prime] [Finite (Sylow p G)]
    (P : Sylow p G) (hP : (P : Subgroup G).Normal) :
    (P : Subgroup G) = opCore p G := by
  haveI : (P : Subgroup G).Normal := hP
  exact le_antisymm (normal_pgroup_le_opCore P.isPGroup') (opCore_le P)

/-- A characteristic subgroup with the order of a Sylow `p`-subgroup supplies a normal
Sylow `p`-subgroup. -/
theorem exists_normal_sylow_of_characteristic_card_eq [Finite G]
    {p : ℕ} [Fact p.Prime] {K : Subgroup G} (hKchar : K.Characteristic)
    (hKcard : Nat.card K = p ^ (Nat.card G).factorization p) :
    ∃ P : Sylow p G, (P : Subgroup G).Normal := by
  classical
  haveI : K.Characteristic := hKchar
  let P : Sylow p G := Sylow.ofCard K hKcard
  refine ⟨P, ?_⟩
  have hP : (P : Subgroup G) = K := by
    simp [P]
  rw [hP]
  infer_instance

/-- A characteristic subgroup whose order matches a Sylow `p`-subgroup is itself a normal
Sylow `p`-subgroup. -/
theorem exists_normal_sylow_of_characteristic_card_eq_sylow [Finite G]
    {p : ℕ} [Fact p.Prime] {K : Subgroup G} (hKchar : K.Characteristic)
    (P₀ : Sylow p G) (hKcard : Nat.card K = Nat.card (P₀ : Subgroup G)) :
    ∃ P : Sylow p G, (P : Subgroup G).Normal :=
  exists_normal_sylow_of_characteristic_card_eq hKchar
    (hKcard.trans P₀.card_eq_multiplicity)

/-! ### Isaacs Thm 1.26 (冪零 ⇔ Sylow 全正規) -/

/-- **Isaacs Thm 1.26 (1) ⇔ (4)**.  有限群 `G` について「`G` が冪零」と
「`G` の任意の Sylow 部分群が正規」は同値.

mathlib `Group.isNilpotent_of_finite_tfae` の (0) ⇔ (3) の抽出ラッパー.  Isaacs 流 5 条件
((1)冪零, (2)`H<G ⇒ N_G(H)>H`, (3) 全極大正規, (4) 全 Sylow 正規, (5) Sylow 内部直積)
は TFAE 全体 (`Group.isNilpotent_of_finite_tfae`) で確保される. -/
theorem isNilpotent_iff_forall_sylow_normal [Finite G] :
    Group.IsNilpotent G ↔
      ∀ (p : ℕ) [Fact p.Prime] (P : Sylow p G), (↑P : Subgroup G).Normal :=
  Group.isNilpotent_of_finite_tfae.out 0 3

/-! **Isaacs Thm 1.26 (4) ⇒ (1)** (全 Sylow 正規 ⇒ 冪零) は呼出側で
`isNilpotent_iff_forall_sylow_normal.mpr` を直接呼ぶ. -/

/-- **Isaacs Thm 1.26 (1) ⇒ (4)** (片向き取り出し).
冪零ならば任意の Sylow は正規. -/
theorem Sylow.normal_of_isNilpotent [Finite G] [Group.IsNilpotent G]
    {p : ℕ} [Fact p.Prime] (P : Sylow p G) : (↑P : Subgroup G).Normal :=
  isNilpotent_iff_forall_sylow_normal.mp ‹_› p P

/-- **Isaacs Lemma 1.27**.  `H i : ι → Subgroup G` が有限族で各 `H i` が正規部分群,
かつ位数 (`Nat.card`) が対ごとに互いに素ならば, 族 `H` は `iSupIndep` (内部直積構造).

証明: 互いに素 ⇒ `Subgroup.disjoint_of_coprime_natCard` で `Disjoint`,
正規 + Disjoint ⇒ `commute_of_normal_of_disjoint` で `Pairwise Commute`,
最後に mathlib `Subgroup.independent_of_coprime_order` を適用. -/
theorem iSupIndep_of_coprime_card_of_normal {ι : Type*} [Finite ι]
    (H : ι → Subgroup G) [∀ i, (H i).Normal] [∀ i, Finite (H i)]
    (hcoprime : Pairwise fun i j => Nat.Coprime (Nat.card (H i)) (Nat.card (H j))) :
    iSupIndep H := by
  -- Step 1: Disjoint from coprime cards.
  have hdisj : ∀ i j, i ≠ j → Disjoint (H i) (H j) := fun i j hij =>
    Subgroup.disjoint_of_coprime_natCard (hcoprime hij)
  -- Step 2: Pairwise commute from disjoint + normal.
  have hcomm : Pairwise fun i j : ι =>
      ∀ x y : G, x ∈ H i → y ∈ H j → Commute x y := by
    intro i j hij x y hx hy
    exact Subgroup.commute_of_normal_of_disjoint (H i) (H j)
      inferInstance inferInstance (hdisj i j hij) x y hx hy
  -- Step 3: Apply mathlib's independent_of_coprime_order.
  classical
  haveI : ∀ i, Fintype (H i) := fun i => Fintype.ofFinite _
  have hcoprime' : Pairwise fun i j =>
      Nat.Coprime (Fintype.card (H i)) (Fintype.card (H j)) := by
    intro i j hij
    have := hcoprime hij
    simpa [Nat.card_eq_fintype_card] using this
  exact Subgroup.independent_of_coprime_order hcomm hcoprime'

/-! ### Fitting 部分群 F(G) -/

/-- **Fitting subgroup** `F(G)`: 全ての素数 `p` についての `opCore p G` (= `O_p(G)`)
の supremum.  これは `G` の最大の正規冪零部分群となる (Isaacs Cor 1.28).

mathlib 未収載のため新規定義. `Subgroup.fitting` として将来 mathlib に PR したい形.

Isaacs 流の定義「`|G|` の各素因子 `p` について `O_p(G)` の積」と等価. 非素数 `p` や
`|G|` に分割しない素数 `p` に対しては `opCore p G ⊆` 既存の sup なので, 範囲を
広げても結果は変わらない (実際 `opCore p G = ⊥` for primes p ∤ |G|, 有限 G で). -/
def fitting (G : Type*) [Group G] : Subgroup G :=
  ⨆ p : Nat.Primes, opCore (p : ℕ) G

theorem opCore_le_fitting (p : Nat.Primes) (G : Type*) [Group G] :
    opCore (p : ℕ) G ≤ fitting G :=
  le_iSup (fun q : Nat.Primes => opCore (q : ℕ) G) p

/-- If `F(G)` is not contained in `S`, then some prime core `O_p(G)` is not
contained in `S`. -/
theorem exists_opCore_not_le_of_fitting_not_le {G : Type*} [Group G] {S : Subgroup G}
    (hS : ¬ fitting G ≤ S) :
    ∃ p : Nat.Primes, ¬ opCore (p : ℕ) G ≤ S := by
  by_contra h
  push Not at h
  exact hS (iSup_le h)

/-- `F(G)` は `G` で特性的. 各 `opCore p G` が特性的 (`opCore.characteristic`) で,
特性的部分群の sup は特性的 (`Subgroup.map_iSup` + `iSup_congr`). -/
instance fitting.characteristic (G : Type*) [Group G] : (fitting G).Characteristic := by
  rw [Subgroup.characteristic_iff_map_eq]
  intro φ
  change (⨆ p : Nat.Primes, opCore (p : ℕ) G).map φ.toMonoidHom
    = ⨆ p : Nat.Primes, opCore (p : ℕ) G
  rw [Subgroup.map_iSup]
  exact iSup_congr fun _ =>
    Subgroup.characteristic_iff_map_eq.mp (opCore.characteristic _ _) φ

/-- `F(G)` は `G` の正規部分群. 各 `opCore p G` の正規性を `iSup_induction` で全体に持ち上げる. -/
instance fitting.normal (G : Type*) [Group G] : (fitting G).Normal := by
  refine ⟨fun n hn g => ?_⟩
  refine Subgroup.iSup_induction _ (C := fun x => g * x * g⁻¹ ∈ fitting G) hn
    ?mem ?one ?mul
  case mem =>
    intro p x hx
    -- x ∈ opCore p G が正規だから g * x * g⁻¹ ∈ opCore p G ≤ fitting
    exact (opCore_le_fitting p G) ((opCore.normal (p : ℕ) G).conj_mem x hx g)
  case one =>
    simp
  case mul =>
    intro x y hx hy
    -- g * (x * y) * g⁻¹ = (g * x * g⁻¹) * (g * y * g⁻¹)
    have heq : g * (x * y) * g⁻¹ = (g * x * g⁻¹) * (g * y * g⁻¹) := by group
    rw [heq]
    exact (fitting G).mul_mem hx hy

/-- 補助補題: 有限冪零群 `N` では, 各素因数 `p` に対する代表 Sylow 部分群
`default : Sylow p N` の supremum は `⊤_N` に等しい.

証明骨子: Thm 1.26 で全 Sylow が正規, よって `unique_of_normal` で各素因数につき
Sylow が 1 つ. `noncommPiCoprod` 経由で `(∀ p ∈ pf(|N|), Sylow p N) →* N` を作り,
互いに素な p-群より単射 (`independent_of_coprime_order`), 濃度比較で全射 ⇒ range = ⊤.
range = `⨆ p, ↑(default Sylow)` (by `noncommPiCoprod_range`). -/
theorem iSup_default_sylow_eq_top_of_nilpotent
    (N : Type*) [Group N] [Finite N] [Group.IsNilpotent N] :
    ⨆ p : (Nat.card N).primeFactors,
        ((default : Sylow (p : ℕ) N) : Subgroup N) = ⊤ := by
  classical
  have hnormal : ∀ {p : ℕ} [Fact p.Prime] (P : Sylow p N), P.Normal := fun P =>
    Sylow.normal_of_isNilpotent P
  have _ := Fintype.ofFinite N
  set ps := (Nat.card N).primeFactors with hps
  let P : ∀ p, Sylow p N := default
  have hPfin : ∀ p, Fintype (P p) := fun p ↦ Fintype.ofFinite (P p)
  have hcomm : Pairwise fun p₁ p₂ : ps =>
      ∀ x y : N, x ∈ (P p₁ : Subgroup N) → y ∈ (P p₂ : Subgroup N) → Commute x y := by
    rintro ⟨p₁, hp₁⟩ ⟨p₂, hp₂⟩ hne
    haveI hp₁' := Fact.mk (Nat.prime_of_mem_primeFactors hp₁)
    haveI hp₂' := Fact.mk (Nat.prime_of_mem_primeFactors hp₂)
    have hne' : p₁ ≠ p₂ := by simpa using hne
    apply Subgroup.commute_of_normal_of_disjoint _ _ (hnormal (P p₁)) (hnormal (P p₂))
    exact IsPGroup.disjoint_of_ne p₁ p₂ hne' _ _ (P p₁).isPGroup' (P p₂).isPGroup'
  -- noncommPiCoprod : (∀ p : ps, P p) →* N
  set f := Subgroup.noncommPiCoprod (G := N) (H := fun p : ps => (P p : Subgroup N)) hcomm
    with hf
  -- f is injective by independent_of_coprime_order
  have hinj : Function.Injective f := by
    apply Subgroup.injective_noncommPiCoprod_of_iSupIndep
    apply Subgroup.independent_of_coprime_order hcomm
    rintro ⟨p₁, hp₁⟩ ⟨p₂, hp₂⟩ hne
    haveI hp₁' := Fact.mk (Nat.prime_of_mem_primeFactors hp₁)
    haveI hp₂' := Fact.mk (Nat.prime_of_mem_primeFactors hp₂)
    have hne' : p₁ ≠ p₂ := by simpa using hne
    simp only [← Nat.card_eq_fintype_card]
    exact IsPGroup.coprime_card_of_ne p₁ p₂ hne' _ _ (P p₁).isPGroup' (P p₂).isPGroup'
  -- |∀ p : ps, P p| = |N|
  have hcard : Fintype.card (∀ p : ps, P p) = Fintype.card N := by
    simp only [← Nat.card_eq_fintype_card]
    calc Nat.card (∀ p : ps, P p)
        = ∏ p : ps, Nat.card (P p) := Nat.card_pi
      _ = ∏ p : ps, p.1 ^ (Nat.card N).factorization p.1 := by
          refine Finset.prod_congr rfl ?_
          rintro ⟨p, hp⟩ _
          exact @Sylow.card_eq_multiplicity _ _ _ p
            ⟨Nat.prime_of_mem_primeFactors hp⟩ (P p)
      _ = ∏ p ∈ ps, p ^ (Nat.card N).factorization p :=
          Finset.prod_finset_coe (fun p => p ^ (Nat.card N).factorization p) _
      _ = (Nat.card N).factorization.prod (· ^ ·) := rfl
      _ = Nat.card N := Nat.prod_factorization_pow_eq_self Nat.card_pos.ne'
  -- bijective
  have hbij : Function.Bijective f :=
    (Fintype.bijective_iff_injective_and_card f).mpr ⟨hinj, hcard⟩
  -- range = ⊤
  have hrange : f.range = (⊤ : Subgroup N) :=
    MonoidHom.range_eq_top.mpr hbij.surjective
  -- but noncommPiCoprod_range says range = ⨆ i, H i
  have hrange' : f.range = ⨆ p : ps, (P p : Subgroup N) :=
    Subgroup.noncommPiCoprod_range
  rw [hrange'] at hrange
  exact hrange

/-- In a finite nilpotent group, the center of any Sylow subgroup lies in the center of the
whole group. -/
theorem center_sylow_le_center_of_isNilpotent [Finite G] [Group.IsNilpotent G]
    {p : ℕ} [Fact p.Prime] (P : Sylow p G) :
    (Subgroup.center ↥(P : Subgroup G)).map (P : Subgroup G).subtype ≤ Subgroup.center G := by
  classical
  intro z hz
  obtain ⟨zp, hzp_center, hzp_eq⟩ := hz
  have hzp_eqG : (zp : G) = z := hzp_eq
  have hzP : z ∈ (P : Subgroup G) := by
    rw [← hzp_eqG]
    exact zp.2
  rw [Subgroup.mem_center_iff]
  intro g
  have hg_sup :
      g ∈ ⨆ r : (Nat.card G).primeFactors,
          ((default : Sylow (r : ℕ) G) : Subgroup G) := by
    rw [iSup_default_sylow_eq_top_of_nilpotent G]
    exact trivial
  refine Subgroup.iSup_induction _ (C := fun x => x * z = z * x) hg_sup ?mem ?one ?mul
  · rintro ⟨r, hr⟩ x hx
    haveI hrprime : Fact r.Prime := ⟨Nat.prime_of_mem_primeFactors hr⟩
    by_cases hrp : r = p
    · subst p
      have hP_normal : P.Normal := Sylow.normal_of_isNilpotent P
      haveI : Unique (Sylow r G) := Sylow.unique_of_normal P hP_normal
      have hxP : x ∈ (P : Subgroup G) := by
        simpa [Subsingleton.elim (default : Sylow r G) P] using hx
      have hcomm := congrArg Subtype.val
        (Subgroup.mem_center_iff.mp hzp_center ⟨x, hxP⟩)
      simpa [hzp_eqG] using hcomm
    · have hD_normal : ((default : Sylow r G) : Subgroup G).Normal :=
        Sylow.normal_of_isNilpotent _
      have hP_normal : (P : Subgroup G).Normal := Sylow.normal_of_isNilpotent P
      have hdisjoint : Disjoint ((default : Sylow r G) : Subgroup G) (P : Subgroup G) :=
        IsPGroup.disjoint_of_ne r p hrp _ _ (default : Sylow r G).isPGroup' P.isPGroup'
      exact (Subgroup.commute_of_normal_of_disjoint _ _ hD_normal hP_normal hdisjoint _ _
        hx hzP).eq
  · simp
  · intro x y hx hy
    calc
      (x * y) * z = x * (y * z) := by group
      _ = x * (z * y) := by rw [hy]
      _ = (x * z) * y := by group
      _ = (z * x) * y := by rw [hx]
      _ = z * (x * y) := by group

/-- In a finite nilpotent group, every prime divisor of the group order divides the center. -/
theorem mem_primeFactors_center_of_isNilpotent [Finite G] [Group.IsNilpotent G]
    {p : ℕ} [Fact p.Prime] (hp : p ∈ (Nat.card G).primeFactors) :
    p ∈ (Nat.card ↥(Subgroup.center G)).primeFactors := by
  let P : Sylow p G := default
  let ZP : Subgroup G := (Subgroup.center ↥(P : Subgroup G)).map (P : Subgroup G).subtype
  have hp_dvd : p ∣ Nat.card G := (Nat.mem_primeFactors.mp hp).2.1
  have hP_ne : (P : Subgroup G) ≠ ⊥ := P.ne_bot_of_dvd_card hp_dvd
  have hZP_ne : ZP ≠ ⊥ := by
    dsimp [ZP]
    intro hbot
    have hcenter_bot : Subgroup.center ↥(P : Subgroup G) = ⊥ :=
      (Subgroup.map_eq_bot_iff_of_injective _ (P : Subgroup G).subtype_injective).mp hbot
    haveI : Nontrivial ↥(P : Subgroup G) := (P : Subgroup G).nontrivial_iff_ne_bot.mpr hP_ne
    exact (Subgroup.center _).nontrivial_iff_ne_bot.mp P.isPGroup'.center_nontrivial hcenter_bot
  have hZP_le_center : ZP ≤ Subgroup.center G := by
    dsimp [ZP]
    exact center_sylow_le_center_of_isNilpotent P
  have hZP_pgroup : IsPGroup p ZP := by
    dsimp [ZP]
    exact (P.isPGroup'.to_subgroup (Subgroup.center ↥(P : Subgroup G))).map
      (P : Subgroup G).subtype
  have hp_dvd_ZP : p ∣ Nat.card ↥ZP := by
    obtain ⟨n, hn⟩ := hZP_pgroup.exists_card_eq
    have hn0 : n ≠ 0 := by
      intro hn0
      apply hZP_ne
      apply Subgroup.card_eq_one.mp
      rw [hn, hn0, pow_zero]
    rw [hn]
    exact dvd_pow_self p hn0
  exact Nat.mem_primeFactors.mpr ⟨Fact.out, hp_dvd_ZP.trans
    (Subgroup.card_dvd_of_le hZP_le_center), Nat.card_pos.ne'⟩

/-- **Isaacs Cor 1.28(b)** (Fitting subgroup の最大性).
任意の正規冪零部分群 `N` は `fitting G` に含まれる.

証明骨子: `N` が冪零 ⇒ `N` の各 Sylow `Q` は `N` で正規 (Thm 1.26) ⇒ `Q` は `N` で
特性的 (`Sylow.characteristic_of_normal`) ⇒ `N ◁ G` で `Q.map N.subtype ◁ G` (Lemma 1.10).
これが `p`-部分群なので Problem 1B.2 で `Q.map N.subtype ≤ opCore p G ≤ fitting G`.
`N` 全体が unique Sylow 達の sup に等しい (`iSup_default_sylow_eq_top_of_nilpotent`) ことから
`N ≤ fitting G`. -/
theorem nilpotent_normal_le_fitting [Finite G] {N : Subgroup G} [N.Normal]
    [Group.IsNilpotent N] : N ≤ fitting G := by
  -- N 全体 (= ⊤ within Subgroup N, mapped through N.subtype = N) ≤ fitting G
  have hsup : (⊤ : Subgroup N).map N.subtype = N := by
    rw [← MonoidHom.range_eq_map, Subgroup.range_subtype]
  rw [← hsup, ← iSup_default_sylow_eq_top_of_nilpotent N, Subgroup.map_iSup]
  refine iSup_le ?_
  rintro ⟨p, hp⟩
  haveI hp' : Fact p.Prime := ⟨Nat.prime_of_mem_primeFactors hp⟩
  -- default : Sylow p N is normal in N
  have hPN : (default : Sylow p N).Normal := Sylow.normal_of_isNilpotent _
  -- default Sylow is characteristic in N (unique Sylow ⇒ characteristic)
  haveI : ((default : Sylow p N) : Subgroup N).Characteristic :=
    Sylow.characteristic_of_normal _ hPN
  -- so its image in G is normal (mathlib instance: characteristic in normal ⇒ normal)
  haveI : (((default : Sylow p N) : Subgroup N).map N.subtype).Normal :=
    inferInstance
  -- it's a p-subgroup of G
  have hpGroup : IsPGroup p (((default : Sylow p N) : Subgroup N).map N.subtype) :=
    (default : Sylow p N).2.map N.subtype
  -- Problem 1B.2 + opCore ≤ fitting
  calc ((default : Sylow p N) : Subgroup N).map N.subtype
      ≤ opCore p G := normal_pgroup_le_opCore hpGroup
    _ ≤ fitting G := opCore_le_fitting ⟨p, hp'.out⟩ G

/-- A nontrivial finite solvable group has nontrivial Fitting subgroup.

Take the last nontrivial derived-series term. It is abelian, hence nilpotent, and normal;
therefore it lies in the Fitting subgroup by maximality. -/
theorem fitting_ne_bot_of_solvable_nontrivial
    (M : Type*) [Group M] [Finite M] [Nontrivial M] [IsSolvable M] :
    fitting M ≠ ⊥ := by
  classical
  obtain ⟨N, hN⟩ := (isSolvable_def M).mp inferInstance
  have hex : ∃ n, derivedSeries M n = ⊥ := ⟨N, hN⟩
  set n := Nat.find hex with hn_def
  have hn_bot : derivedSeries M n = ⊥ := Nat.find_spec hex
  have hn_pos : 0 < n := by
    rcases Nat.eq_zero_or_pos n with h0 | hpos
    · exfalso
      have : derivedSeries M 0 = ⊥ := h0 ▸ hn_bot
      rw [derivedSeries_zero] at this
      exact (bot_ne_top (α := Subgroup M)) this.symm
    · exact hpos
  set m := n - 1 with hm_def
  have hm_succ : m + 1 = n := by omega
  set L := derivedSeries M m with hL_def
  have hL_ne_bot : L ≠ ⊥ := by
    rw [hL_def]
    exact Nat.find_min hex (by omega)
  have hLL_bot : ⁅L, L⁆ = ⊥ := by
    rw [hL_def, ← derivedSeries_succ, hm_succ, hn_bot]
  haveI hL_comm : IsMulCommutative L := by
    rw [Subgroup.commutator_eq_bot_iff_le_centralizer] at hLL_bot
    refine ⟨⟨fun a b => ?_⟩⟩
    have ha_cent : (a : M) ∈ Subgroup.centralizer (L : Set M) := hLL_bot a.property
    rw [Subgroup.mem_centralizer_iff] at ha_cent
    apply Subtype.ext
    exact (ha_cent b.val b.property).symm
  haveI hL_normal : L.Normal := by
    rw [hL_def]
    exact derivedSeries_normal M m
  haveI hL_nilp : Group.IsNilpotent ↥L := inferInstance
  have hL_le_fitting : L ≤ fitting M := nilpotent_normal_le_fitting
  intro hF_bot
  rw [hF_bot, le_bot_iff] at hL_le_fitting
  exact hL_ne_bot hL_le_fitting

/-- A natural number greater than `1` has a largest prime factor.  The conclusion is
packaged in the exact form used in BG when choosing "the largest prime divisor of `|G|`". -/
theorem exists_max_primeFactor_of_one_lt {n : ℕ} (hn : 1 < n) :
    ∃ p : ℕ, p ∈ n.primeFactors ∧ ∀ q ∈ n.primeFactors, q ≤ p := by
  classical
  obtain ⟨p, hp_prime, hp_dvd⟩ := Nat.exists_prime_and_dvd hn.ne'
  have hn_ne_zero : n ≠ 0 := by omega
  have hp_mem : p ∈ n.primeFactors := hp_prime.mem_primeFactors hp_dvd hn_ne_zero
  refine ⟨n.primeFactors.max' ⟨p, hp_mem⟩, ?_, ?_⟩
  · exact Finset.max'_mem _ _
  · intro q hq
    exact Finset.le_max' _ q hq

/-- A nontrivial finite type has a largest prime factor in its cardinality. -/
theorem exists_max_primeFactor_card_of_nontrivial (G : Type*) [Finite G] [Nontrivial G] :
    ∃ p : ℕ, p ∈ (Nat.card G).primeFactors ∧ p.Prime ∧
      ∀ q ∈ (Nat.card G).primeFactors, q ≤ p := by
  obtain ⟨p, hp_mem, hp_max⟩ :=
    exists_max_primeFactor_of_one_lt (n := Nat.card G) (Finite.one_lt_card (α := G))
  exact ⟨p, hp_mem, Nat.prime_of_mem_primeFactors hp_mem, hp_max⟩

/-- 有限 `G` で `p ∤ |G|` (より一般に `p` が `|G|` の素因子でない) なら, 任意の
Sylow `p`-部分群は自明 `⊥`, 従って `opCore p G = ⊥`.

`Sylow.card_eq_multiplicity` で各 Sylow の濃度は `p ^ v_p(|G|)`. `p ∉ pf(|G|)` なら
`v_p(|G|) = 0` で濃度 1, ゆえ `⊥`. -/
theorem opCore_eq_bot_of_not_mem_primeFactors [Finite G]
    {p : ℕ} [Fact p.Prime] (hp : p ∉ (Nat.card G).primeFactors) :
    opCore p G = ⊥ := by
  -- Pick any Sylow P; it's ⊥ since its card is p^0 = 1.
  obtain ⟨P⟩ := Sylow.nonempty (p := p) (G := G)
  have hcard : Nat.card (P : Subgroup G) = 1 := by
    rw [Sylow.card_eq_multiplicity P]
    have hfact : (Nat.card G).factorization p = 0 := by
      by_cases hdvd : p ∣ Nat.card G
      · -- p divides but is not in primeFactors → contradiction since Nat.card G ≠ 0
        exfalso
        exact hp (Nat.mem_primeFactors.mpr
          ⟨(Fact.out : p.Prime), hdvd, Nat.card_pos.ne'⟩)
      · exact Nat.factorization_eq_zero_of_not_dvd hdvd
    rw [hfact, pow_zero]
  have hPbot : (P : Subgroup G) = ⊥ := Subgroup.eq_bot_of_card_eq _ hcard
  exact le_bot_iff.mp (le_of_le_of_eq (opCore_le P) hPbot)

/-- 有限 `G` について `fitting G` は `|G|` の素因子だけに渡る `opCore` の sup と等しい.
非素因子 `p` に対しては `opCore p G = ⊥` で寄与しないため. -/
theorem fitting_eq_iSup_primeFactors [Finite G] :
    fitting G = ⨆ p : (Nat.card G).primeFactors, opCore (p : ℕ) G := by
  apply le_antisymm
  · -- fitting = ⨆ p : Primes ≤ ⨆ p : pf
    refine iSup_le (fun p => ?_)
    haveI : Fact (p : ℕ).Prime := ⟨p.2⟩
    by_cases hmem : (p : ℕ) ∈ (Nat.card G).primeFactors
    · -- p is in primeFactors, contribute via the indexed sup
      exact le_iSup (fun q : (Nat.card G).primeFactors => opCore (q : ℕ) G) ⟨p, hmem⟩
    · -- p not in primeFactors: opCore p G = ⊥
      rw [opCore_eq_bot_of_not_mem_primeFactors hmem]
      exact bot_le
  · -- ⨆ p : pf ≤ ⨆ p : Primes (= fitting)
    refine iSup_le (fun p => ?_)
    have hp : (p : ℕ).Prime := Nat.prime_of_mem_primeFactors p.2
    exact opCore_le_fitting ⟨(p : ℕ), hp⟩ G

/-- **Isaacs Cor 1.28(a)** (Fitting subgroup の冪零性).
有限群 `G` について `fitting G` は冪零.

証明骨子: `(Nat.card G).primeFactors` 上の積 `∀ p, opCore p G` から `G` への
`noncommPiCoprod` を考える. (i) 異なる素数 `p ≠ q` で `opCore p G, opCore q G` は
互いに素な p-群 (`IsPGroup.disjoint_of_ne`) ゆえ可換 (`commute_of_normal_of_disjoint`,
両者は正規), (ii) `independent_of_coprime_order` で `iSupIndep`, よって
`noncommPiCoprod` は単射 (`injective_noncommPiCoprod_of_iSupIndep`).
range は `⨆ p, opCore p G = fitting G` (`fitting_eq_iSup_primeFactors`).
従って `(∀ p, opCore p G) ≃* fitting G` (`MulEquiv.ofInjective` + `subgroupCongr`).
各 `opCore p G` は有限 p-群ゆえ冪零 (`IsPGroup.isNilpotent`), 有限積も冪零
(`Group.isNilpotent_pi`), `MulEquiv` で `fitting G` も冪零.

`instance` 指定で `[Group.IsNilpotent (fitting G)]` が下流で自動推論される. -/
instance fitting.isNilpotent [Finite G] : Group.IsNilpotent (fitting G) := by
  classical
  have _ := Fintype.ofFinite G
  set ps := (Nat.card G).primeFactors with hps
  -- For each p ∈ pf, opCore p G is a p-group and normal in G
  have hcomm : Pairwise fun p₁ p₂ : ps =>
      ∀ x y : G, x ∈ opCore (p₁ : ℕ) G → y ∈ opCore (p₂ : ℕ) G → Commute x y := by
    rintro ⟨p₁, hp₁⟩ ⟨p₂, hp₂⟩ hne
    haveI hp₁' : Fact (p₁ : ℕ).Prime := ⟨Nat.prime_of_mem_primeFactors hp₁⟩
    haveI hp₂' : Fact (p₂ : ℕ).Prime := ⟨Nat.prime_of_mem_primeFactors hp₂⟩
    have hne' : p₁ ≠ p₂ := by simpa using hne
    apply Subgroup.commute_of_normal_of_disjoint _ _ (opCore.normal p₁ G)
      (opCore.normal p₂ G)
    exact IsPGroup.disjoint_of_ne p₁ p₂ hne' _ _
      (opCore_isPGroup p₁ G) (opCore_isPGroup p₂ G)
  set f := Subgroup.noncommPiCoprod (G := G)
    (H := fun p : ps => opCore (p : ℕ) G) hcomm with hf
  -- f is injective by iSupIndep (coprime orders)
  have hinj : Function.Injective f := by
    apply Subgroup.injective_noncommPiCoprod_of_iSupIndep
    apply Subgroup.independent_of_coprime_order hcomm
    rintro ⟨p₁, hp₁⟩ ⟨p₂, hp₂⟩ hne
    haveI hp₁' : Fact (p₁ : ℕ).Prime := ⟨Nat.prime_of_mem_primeFactors hp₁⟩
    haveI hp₂' : Fact (p₂ : ℕ).Prime := ⟨Nat.prime_of_mem_primeFactors hp₂⟩
    have hne' : p₁ ≠ p₂ := by simpa using hne
    simp only [← Nat.card_eq_fintype_card]
    exact IsPGroup.coprime_card_of_ne p₁ p₂ hne' _ _
      (opCore_isPGroup p₁ G) (opCore_isPGroup p₂ G)
  -- range f = ⨆ p, opCore p G = fitting G
  have hrange : f.range = fitting G := by
    rw [hf, Subgroup.noncommPiCoprod_range, ← fitting_eq_iSup_primeFactors]
  -- Build MulEquiv (∀ p, opCore p G) ≃* fitting G
  let e : (∀ p : ps, opCore (p : ℕ) G) ≃* fitting G :=
    (MonoidHom.ofInjective hinj).trans (MulEquiv.subgroupCongr hrange)
  -- Each opCore p G (as a group) is finite + p-group ⇒ nilpotent
  have hnilp : ∀ p : ps, Group.IsNilpotent (opCore (p : ℕ) G) := by
    rintro ⟨p, hp⟩
    haveI : Fact p.Prime := ⟨Nat.prime_of_mem_primeFactors hp⟩
    exact (opCore_isPGroup p G).isNilpotent
  -- Finite product of nilpotent is nilpotent
  haveI : ∀ p : ps, Group.IsNilpotent (opCore (p : ℕ) G) := hnilp
  haveI : Group.IsNilpotent (∀ p : ps, opCore (p : ℕ) G) := Group.isNilpotent_pi
  -- Transport across the MulEquiv
  exact Group.nilpotent_of_mulEquiv e

/-- **Isaacs Cor 1.29** (冪零正規部分群の積も冪零).
`K, L` が `G` の正規冪零部分群ならば `K ⊔ L` (= `KL`) も冪零.

証明: Cor 1.28(b) で `K, L ≤ fitting G` ⇒ `K ⊔ L ≤ fitting G`.
`(K ⊔ L).subgroupOf (fitting G)` は冪零 (Cor 1.28(a) + `Subgroup.isNilpotent` instance),
`subgroupOfEquivOfLe` の同型で `K ⊔ L` も冪零. -/
instance sup_isNilpotent_of_normal_nilpotent [Finite G]
    (K L : Subgroup G) [K.Normal] [L.Normal]
    [Group.IsNilpotent K] [Group.IsNilpotent L] :
    Group.IsNilpotent (↥(K ⊔ L)) := by
  have hKLfit : K ⊔ L ≤ fitting G :=
    sup_le nilpotent_normal_le_fitting nilpotent_normal_le_fitting
  exact Group.nilpotent_of_mulEquiv (Subgroup.subgroupOfEquivOfLe hKLfit)

/-- **Isaacs Lucchini 2.20 prereq**: `M ⊴ G` ⇒ `F(M) ⊆ F(G)` (`F(M)` を `M.subtype`
で `G` 部分群として見て).

形式的には `(fitting ↥M).map M.subtype ≤ fitting G`. Lucchini Thm 2.20 (K=⊥ case)
の M non-abelian 場面で利用.

**証明**: `fitting ↥M` は `↥M` で characteristic (`fitting.characteristic`).
`M ⊴ G` ゆえ mathlib `Subgroup.normal_of_characteristic_of_normal` instance で
`(fitting ↥M).map M.subtype ⊴ G`. `fitting ↥M` は冪零 (`fitting.isNilpotent`),
`equivMapOfInjective` + `Group.nilpotent_of_mulEquiv` で image も冪零.
`nilpotent_normal_le_fitting` を適用して結論. -/
theorem fitting_map_subtype_le_fitting [Finite G] {M : Subgroup G} [M.Normal] :
    (fitting ↥M).map M.subtype ≤ fitting G := by
  haveI : Finite ↥M := inferInstance
  haveI : Group.IsNilpotent ↥(fitting (↥M : Type _)) := fitting.isNilpotent
  haveI hNilp : Group.IsNilpotent ↥((fitting ↥M).map M.subtype) :=
    Group.nilpotent_of_mulEquiv (Subgroup.equivMapOfInjective (fitting ↥M) M.subtype
      M.subtype_injective)
  exact nilpotent_normal_le_fitting

/-- If a normal subgroup contains `F(G)`, then its Fitting subgroup maps onto
`F(G)`. -/
theorem fitting_map_eq_of_normal_of_fitting_le [Finite G] {M : Subgroup G} [M.Normal]
    (hFM : fitting G ≤ M) :
    (fitting ↥M).map M.subtype = fitting G := by
  refine le_antisymm fitting_map_subtype_le_fitting ?_
  haveI : Group.IsNilpotent ↥(fitting G) := fitting.isNilpotent
  haveI : Group.IsNilpotent ↥((fitting G).subgroupOf M) :=
    Group.nilpotent_of_mulEquiv (Subgroup.subgroupOfEquivOfLe hFM).symm
  have hle : (fitting G).subgroupOf M ≤ fitting ↥M :=
    nilpotent_normal_le_fitting
  calc fitting G
      = fitting G ⊓ M := (inf_eq_left.mpr hFM).symm
    _ = ((fitting G).subgroupOf M).map M.subtype :=
        (Subgroup.subgroupOf_map_subtype _ M).symm
    _ ≤ (fitting ↥M).map M.subtype := Subgroup.map_mono hle

/-- The image of the Fitting subgroup under a group isomorphism is contained in the Fitting
subgroup of the codomain. -/
theorem fitting_map_mulEquiv_le {A B : Type*} [Group A] [Group B] [Finite A] [Finite B]
    (e : A ≃* B) :
    (fitting A).map e.toMonoidHom ≤ fitting B := by
  haveI : Group.IsNilpotent (fitting A) := fitting.isNilpotent
  haveI : Group.IsNilpotent ↥((fitting A).map e.toMonoidHom) :=
    Group.nilpotent_of_mulEquiv (Subgroup.equivMapOfInjective _ e.toMonoidHom e.injective)
  haveI : ((fitting A).map e.toMonoidHom).Normal :=
    (fitting.normal A).map e.toMonoidHom e.surjective
  exact nilpotent_normal_le_fitting

/-- The Fitting subgroup is preserved by group isomorphisms. -/
theorem fitting_map_mulEquiv {A B : Type*} [Group A] [Group B] [Finite A] (e : A ≃* B) :
    (fitting A).map e.toMonoidHom = fitting B := by
  haveI : Finite B := Finite.of_equiv A e.toEquiv
  refine le_antisymm (fitting_map_mulEquiv_le e) (fun y hy => ?_)
  have hpre : e.symm y ∈ fitting A :=
    fitting_map_mulEquiv_le e.symm (by simpa using Subgroup.mem_map_of_mem e.symm.toMonoidHom hy)
  simpa using Subgroup.mem_map_of_mem e.toMonoidHom hpre

/-- The Fitting subgroup of `A.subgroupOf S`, pushed into `S`, is the restriction
of the Fitting subgroup of `A`, pushed into the ambient group. -/
theorem fitting_subgroupOf_map_subtype_eq [Finite G] {A S : Subgroup G} (hAS : A ≤ S) :
    (fitting ↥(A.subgroupOf S)).map (A.subgroupOf S).subtype =
      ((fitting ↥A).map A.subtype).subgroupOf S := by
  apply Subgroup.map_injective S.subtype_injective
  have hLS : (fitting ↥A).map A.subtype ≤ S :=
    (Subgroup.map_subtype_le _).trans hAS
  have hcomp : S.subtype.comp (A.subgroupOf S).subtype =
      A.subtype.comp (Subgroup.subgroupOfEquivOfLe hAS).toMonoidHom := by
    ext a'
    rfl
  rw [Subgroup.subgroupOf_map_subtype, inf_eq_left.mpr hLS, Subgroup.map_map, hcomp,
    ← Subgroup.map_map, fitting_map_mulEquiv]

/-- The Fitting subgroup of the image of a subgroup under `K.subtype` is the image
of the Fitting subgroup under the composed subtype map. -/
theorem fitting_map_map_subtype [Finite G] {K : Subgroup G} {P : Subgroup K} :
    (fitting ↥(P.map K.subtype)).map (P.map K.subtype).subtype =
      ((fitting ↥P).map P.subtype).map K.subtype := by
  have hcomp : (P.map K.subtype).subtype.comp
      (Subgroup.equivMapOfInjective P K.subtype K.subtype_injective).toMonoidHom =
      K.subtype.comp P.subtype := by
    ext a
    rfl
  rw [← fitting_map_mulEquiv (Subgroup.equivMapOfInjective P K.subtype K.subtype_injective),
    Subgroup.map_map, hcomp, ← Subgroup.map_map]

end -- 1D

section /- 1E: Small-order groups, normal subgroup of index 2 (pp. 31-34) -/

open scoped Pointwise

variable {G : Type*} [Group G]

/-- **Isaacs Thm 1.30** (前半, uniqueness form).  `|G| = p · q` で `q < p` が
ともに素数ならば, `G` の Sylow `p`-部分群は一意. -/
theorem sylow_p_subsingleton_of_card_eq_mul_prime_lt
    [Finite G] {p q : ℕ} [Fact p.Prime] [Fact q.Prime]
    (hqp : q < p) (hcard : Nat.card G = p * q) :
    Subsingleton (Sylow p G) := by
  haveI : Finite (Sylow p G) := inferInstance
  obtain ⟨P⟩ := Sylow.nonempty (p := p) (G := G)
  have hPcard : Nat.card P = p := by
    have hmul := P.card_eq_multiplicity (G := G)
    rw [hcard, Nat.factorization_mul (Fact.out (p := p.Prime)).ne_zero
        (Fact.out (p := q.Prime)).ne_zero] at hmul
    simp only [Finsupp.coe_add, Pi.add_apply,
               Nat.Prime.factorization_self (Fact.out (p := p.Prime)),
               (Fact.out (p := q.Prime)).factorization,
               Finsupp.single_apply, if_neg hqp.ne] at hmul
    simpa using hmul
  have hPindex : (P : Subgroup G).index = q := by
    have h1 : Nat.card (P : Subgroup G) * (P : Subgroup G).index = Nat.card G :=
      Subgroup.card_mul_index _
    rw [hcard, hPcard] at h1
    exact Nat.eq_of_mul_eq_mul_left (Fact.out (p := p.Prime)).pos h1
  have hdvd : Nat.card (Sylow p G) ∣ q := hPindex ▸ P.card_dvd_index
  have hmod : Nat.card (Sylow p G) ≡ 1 [MOD p] := card_sylow_modEq_one p G
  rcases (Nat.dvd_prime (Fact.out (p := q.Prime))).mp hdvd with hn1 | hnq
  · exact (Nat.card_eq_one_iff_unique.mp hn1).1
  · exfalso
    rw [hnq] at hmod
    have hge : 1 ≤ q := (Fact.out (p := q.Prime)).pos
    have hdvd' : p ∣ q - 1 := (Nat.modEq_iff_dvd' hge).mp hmod.symm
    have hlt : q - 1 < p := by omega
    have hq1 : q - 1 = 0 := Nat.eq_zero_of_dvd_of_lt hdvd' hlt
    have hq_eq : q = 1 := by omega
    exact (Fact.out (p := q.Prime)).one_lt.ne' hq_eq

/-- **Isaacs Thm 1.30** (前半).  `|G| = p·q` で `q < p` がともに素数なら,
`G` の Sylow `p`-部分群は正規 (一意). -/
theorem sylow_normal_of_card_eq_mul_prime_lt
    [Finite G] {p q : ℕ} [Fact p.Prime] [Fact q.Prime]
    (hqp : q < p) (hcard : Nat.card G = p * q) (P : Sylow p G) :
    (P : Subgroup G).Normal := by
  haveI : Subsingleton (Sylow p G) :=
    sylow_p_subsingleton_of_card_eq_mul_prime_lt hqp hcard
  exact Sylow.normal_of_subsingleton P

/-- **Isaacs Thm 1.30** (後半).  `|G| = p·q` (`q < p` 素), `q ∤ (p − 1)` ⇒ `G` 巡回.

証明 (Isaacs p.31): 前半で Sylow `p` は正規 (一意).  Sylow `q` についても
`n_q ∣ p` (`Sylow.card_dvd_index`), `n_q ≡ 1 (mod q)` (`card_sylow_modEq_one`).
`q` 素数なので `n_q ∈ {1, p}`; `n_q = p` ならば `q ∣ p − 1` で仮定矛盾.
ゆえに Sylow `q` も正規.  Cauchy で位数 `p` の `s ∈ Sylow p`, 位数 `q` の
`t ∈ Sylow q` を取り, 正規 + 互いに素位数 (disjoint) ⇒ 可換
(`commute_of_normal_of_disjoint`).  `orderOf (s * t) = pq = |G|`
(`Commute.orderOf_mul_eq_mul_orderOf_of_coprime`) ⇒ `G` 巡回. -/
theorem isCyclic_of_card_eq_mul_prime_lt_of_not_dvd
    [Finite G] {p q : ℕ} [hp : Fact p.Prime] [hq : Fact q.Prime]
    (hqp : q < p) (hcard : Nat.card G = p * q) (hndvd : ¬ q ∣ p - 1) :
    IsCyclic G := by
  classical
  haveI : Finite (Sylow p G) := inferInstance
  haveI : Finite (Sylow q G) := inferInstance
  have hpq_ne : p ≠ q := fun h => (Nat.lt_irrefl _ (h ▸ hqp))
  obtain ⟨Q⟩ := Sylow.nonempty (p := q) (G := G)
  obtain ⟨P⟩ := Sylow.nonempty (p := p) (G := G)
  -- 位数情報
  have hcop_qp : Nat.Coprime q p := (Nat.coprime_primes hq.out hp.out).mpr hpq_ne.symm
  have hcop_pq : Nat.Coprime p q := hcop_qp.symm
  have hcard' : Nat.card G = q * p := by rw [hcard, mul_comm]
  have hfact_p : (Nat.card G).factorization p = 1 := by
    rw [hcard, Nat.factorization_mul_apply_of_coprime hcop_pq,
        hp.out.factorization_self,
        Nat.factorization_eq_zero_of_not_dvd
          (fun hd => hpq_ne ((Nat.prime_dvd_prime_iff_eq hp.out hq.out).mp hd))]
  have hfact_q : (Nat.card G).factorization q = 1 := by
    rw [hcard', Nat.factorization_mul_apply_of_coprime hcop_qp,
        hq.out.factorization_self,
        Nat.factorization_eq_zero_of_not_dvd
          (fun hd => hpq_ne.symm ((Nat.prime_dvd_prime_iff_eq hq.out hp.out).mp hd))]
  have hPcard : Nat.card P = p := by rw [P.card_eq_multiplicity, hfact_p, pow_one]
  have hQcard : Nat.card Q = q := by rw [Q.card_eq_multiplicity, hfact_q, pow_one]
  have hQindex : (Q : Subgroup G).index = p := by
    have := (Q : Subgroup G).card_mul_index
    rw [hQcard, hcard'] at this
    exact Nat.eq_of_mul_eq_mul_left hq.out.pos this
  -- Sylow q が一意 (q ∤ p-1 を使う)
  have hnq_dvd : Nat.card (Sylow q G) ∣ p := hQindex ▸ Sylow.card_dvd_index Q
  have hnq_mod : Nat.card (Sylow q G) ≡ 1 [MOD q] := card_sylow_modEq_one q G
  have hnq_pos : 0 < Nat.card (Sylow q G) := Nat.card_pos
  have hnq_eq : Nat.card (Sylow q G) = 1 := by
    rcases (Nat.dvd_prime hp.out).mp hnq_dvd with h1 | hp_eq
    · exact h1
    · exfalso
      apply hndvd
      have : p ≡ 1 [MOD q] := hp_eq ▸ hnq_mod
      have hp_ge : 1 ≤ p := hp.out.one_lt.le
      exact (Nat.modEq_iff_dvd' hp_ge).mp this.symm
  haveI hQsub : Subsingleton (Sylow q G) := by
    rw [Nat.card_eq_one_iff_unique] at hnq_eq
    exact hnq_eq.1
  haveI hPnormal : (↑P : Subgroup G).Normal :=
    sylow_normal_of_card_eq_mul_prime_lt hqp hcard P
  haveI hQnormal : (↑Q : Subgroup G).Normal := Sylow.normal_of_subsingleton Q
  -- Cauchy で各 Sylow から位数 p / q の元
  have hPdvd : p ∣ Nat.card (↑P : Subgroup G) := by rw [hPcard]
  have hQdvd : q ∣ Nat.card (↑Q : Subgroup G) := by rw [hQcard]
  obtain ⟨s, hs_order⟩ := exists_prime_orderOf_dvd_card' (G := (↑P : Subgroup G)) p hPdvd
  obtain ⟨t, ht_order⟩ := exists_prime_orderOf_dvd_card' (G := (↑Q : Subgroup G)) q hQdvd
  set sG : G := (s : G)
  set tG : G := (t : G)
  have hsG_orderG : orderOf sG = p := (Subgroup.orderOf_coe s).trans hs_order
  have htG_orderG : orderOf tG = q := (Subgroup.orderOf_coe t).trans ht_order
  have hsG_mem : sG ∈ (↑P : Subgroup G) := s.2
  have htG_mem : tG ∈ (↑Q : Subgroup G) := t.2
  have hdisjoint : Disjoint (↑P : Subgroup G) (↑Q : Subgroup G) :=
    IsPGroup.disjoint_of_ne p q hpq_ne _ _ P.isPGroup' Q.isPGroup'
  have hcomm : Commute sG tG :=
    Subgroup.commute_of_normal_of_disjoint _ _ hPnormal hQnormal hdisjoint _ _ hsG_mem htG_mem
  have hcop_orders : Nat.Coprime (orderOf sG) (orderOf tG) := by
    rw [hsG_orderG, htG_orderG]; exact hcop_pq
  have horder : orderOf (sG * tG) = p * q := by
    rw [hcomm.orderOf_mul_eq_mul_orderOf_of_coprime hcop_orders, hsG_orderG, htG_orderG]
  have horder_eq : orderOf (sG * tG) = Nat.card G := by rw [horder, hcard]
  exact isCyclic_of_orderOf_eq_card (sG * tG) horder_eq

end
end OddOrder.Isaacs.Ch01
