/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Peterfalvi.Appendices.Suzuki2Groups.AgemoLayers
import OddOrder.GroupTheory.RepresentationTheory.ElementaryAbelianRepresentation

/-!
# Higman's elementary lower-central layers

G. Higman, *Suzuki 2-groups*, Illinois J. Math. 7 (1963), section 4,
pp. 84--85; used in Peterfalvi, Appendix III.

For the lower central series `H = H₁, H₂, ...`, Higman writes

`Lᵢ = Hᵢ / (Hᵢ² Hᵢ₊₁)`.

Mathlib numbers the same series from zero, so `lowerCentralTerm H 0` is
Higman's `H₁`, and `lowerCentralLayer H 0` is his `L₁`.  The denominator is
constructed, not postulated: it is generated by the squares in the current
term together with the next lower-central term.  This file supplies the
common carrier and automorphism-action infrastructure for Higman's Lemmas
4--9, together with the actual commutator pairing, its alternating
linearization, and its full-span theorem for the spectral argument.
-/

set_option autoImplicit false

namespace OddOrder.Peterfalvi.Appendices.Suzuki2Groups

open OddOrder.GroupTheory
open OddOrder.Isaacs.Ch03
open scoped commutatorElement IsMulCommutative

universe uH uX uL1 uL2

/-- The `i`-th lower-central term in mathlib's zero-based numbering.
It is Higman's `H_(i+1)`. -/
def lowerCentralTerm (H : Type uH) [Group H] (i : ℕ) : Subgroup H :=
  (⊤ : Subgroup H).lowerCentralSeries i

/-- The denominator `Hᵢ² Hᵢ₊₁`, viewed inside `Hᵢ`.

`Agemo _ 2 1` is the subgroup generated by squares.  The supremum is the
subgroup product because both factors are normal in the current term. -/
def lowerCentralLayerKernel (H : Type uH) [Group H] (i : ℕ) :
    Subgroup ↥(lowerCentralTerm H i) :=
  Agemo (↥(lowerCentralTerm H i)) 2 1 ⊔
    (lowerCentralTerm H (i + 1)).subgroupOf (lowerCentralTerm H i)

/-- The next lower-central term is normal inside the current term. -/
theorem lowerCentralNext_subgroupOf_normal (H : Type uH) [Group H] (i : ℕ) :
    ((lowerCentralTerm H (i + 1)).subgroupOf
      (lowerCentralTerm H i)).Normal := by
  have hnormal : (lowerCentralTerm H (i + 1)).Normal := by
    dsimp [lowerCentralTerm]
    infer_instance
  exact hnormal.subgroupOf _

/-- The denominator `Hᵢ² Hᵢ₊₁` is normal in `Hᵢ`. -/
instance lowerCentralLayerKernel_normal (H : Type uH) [Group H] (i : ℕ) :
    (lowerCentralLayerKernel H i).Normal := by
  dsimp [lowerCentralLayerKernel]
  letI : ((lowerCentralTerm H (i + 1)).subgroupOf
      (lowerCentralTerm H i)).Normal :=
    lowerCentralNext_subgroupOf_normal H i
  infer_instance

/-- The next lower-central term lies in the current one. -/
theorem lowerCentralTerm_succ_le (H : Type uH) [Group H] (i : ℕ) :
    lowerCentralTerm H (i + 1) ≤ lowerCentralTerm H i := by
  exact (⊤ : Subgroup H).lowerCentralSeries_antitone (Nat.le_succ i)

/-- The same denominator, embedded back into the ambient group `H`.

Keeping this ambient form records literally the source expression
`Hᵢ² Hᵢ₊₁`; the quotient carrier itself uses the corresponding subgroup of
`Hᵢ`. -/
def lowerCentralLayerKernelInAmbient (H : Type uH) [Group H] (i : ℕ) :
    Subgroup H :=
  (lowerCentralLayerKernel H i).map (lowerCentralTerm H i).subtype

/-- The ambient denominator is exactly the product of the subgroup generated
by squares in `Hᵢ` and `Hᵢ₊₁`. -/
theorem lowerCentralLayerKernelInAmbient_eq
    (H : Type uH) [Group H] (i : ℕ) :
    lowerCentralLayerKernelInAmbient H i =
      (Agemo (↥(lowerCentralTerm H i)) 2 1).map
          (lowerCentralTerm H i).subtype ⊔
        lowerCentralTerm H (i + 1) := by
  rw [lowerCentralLayerKernelInAmbient, lowerCentralLayerKernel,
    Subgroup.map_sup,
    Subgroup.map_subgroupOf_eq_of_le (lowerCentralTerm_succ_le H i)]

/-- The ambient denominator lies in `Hᵢ`, as required for the quotient. -/
theorem lowerCentralLayerKernelInAmbient_le
    (H : Type uH) [Group H] (i : ℕ) :
    lowerCentralLayerKernelInAmbient H i ≤ lowerCentralTerm H i :=
  Subgroup.map_subtype_le _

/-- The subgroup form of the ambient denominator recovers the kernel used by
the quotient definition. -/
theorem lowerCentralLayerKernelInAmbient_subgroupOf
    (H : Type uH) [Group H] (i : ℕ) :
    (lowerCentralLayerKernelInAmbient H i).subgroupOf
        (lowerCentralTerm H i) =
      lowerCentralLayerKernel H i := by
  rw [← Subgroup.map_subtype_inj,
    Subgroup.map_subgroupOf_eq_of_le
      (lowerCentralLayerKernelInAmbient_le H i)]
  rfl

/-- The ambient denominator is normal in `H`.  This follows from normality of
`Hᵢ`, characteristicity of its square subgroup, and normality of `Hᵢ₊₁`. -/
theorem lowerCentralLayerKernelInAmbient_normal
    (H : Type uH) [Group H] (i : ℕ) :
    (lowerCentralLayerKernelInAmbient H i).Normal := by
  rw [lowerCentralLayerKernelInAmbient_eq]
  haveI : (lowerCentralTerm H i).Normal := by
    dsimp [lowerCentralTerm]
    infer_instance
  haveI : ((Agemo (↥(lowerCentralTerm H i)) 2 1).map
      (lowerCentralTerm H i).subtype).Normal := inferInstance
  haveI : (lowerCentralTerm H (i + 1)).Normal := by
    dsimp [lowerCentralTerm]
    infer_instance
  infer_instance

/-- Higman's elementary lower-central layer
`L_(i+1) = H_(i+1) / (H_(i+1)^2 H_(i+2))`. -/
abbrev lowerCentralLayer (H : Type uH) [Group H] (i : ℕ) :=
  ↥(lowerCentralTerm H i) ⧸ lowerCentralLayerKernel H i

/-- Every square in the current lower-central term belongs to the layer
kernel. -/
theorem sq_mem_lowerCentralLayerKernel
    (H : Type uH) [Group H] (i : ℕ) (x : ↥(lowerCentralTerm H i)) :
    x ^ 2 ∈ lowerCentralLayerKernel H i := by
  change x ^ 2 ∈
    Agemo (↥(lowerCentralTerm H i)) 2 1 ⊔
      (lowerCentralTerm H (i + 1)).subgroupOf (lowerCentralTerm H i)
  apply (show Agemo (↥(lowerCentralTerm H i)) 2 1 ≤ _ from le_sup_left)
  simpa using
    (Agemo.mem_of_eq_pow (G := ↥(lowerCentralTerm H i))
      (p := 2) (n := 1) x)

/-- Commutators of two elements in the current lower-central term belong to
the next term, hence to the layer kernel. -/
theorem commutatorElement_mem_lowerCentralLayerKernel
    (H : Type uH) [Group H] (i : ℕ)
    (x y : ↥(lowerCentralTerm H i)) :
    ⁅x, y⁆ ∈ lowerCentralLayerKernel H i := by
  change ⁅x, y⁆ ∈
    Agemo (↥(lowerCentralTerm H i)) 2 1 ⊔
      (lowerCentralTerm H (i + 1)).subgroupOf (lowerCentralTerm H i)
  apply (show (lowerCentralTerm H (i + 1)).subgroupOf
      (lowerCentralTerm H i) ≤ _ from le_sup_right)
  change ⁅(x : H), (y : H)⁆ ∈ lowerCentralTerm H (i + 1)
  have hxy : ⁅(x : H), (y : H)⁆ ∈
      ⁅lowerCentralTerm H i, lowerCentralTerm H i⁆ :=
    Subgroup.commutator_mem_commutator x.2 y.2
  apply (show ⁅lowerCentralTerm H i, lowerCentralTerm H i⁆ ≤
      lowerCentralTerm H (i + 1) by
    dsimp [lowerCentralTerm]
    exact Subgroup.commutator_mono le_rfl le_top)
  exact hxy

/-- Each lower-central layer is elementary abelian of exponent two. -/
theorem lowerCentralLayer_isElementaryAbelian
    (H : Type uH) [Group H] (i : ℕ) :
    IsElementaryAbelian 2 (lowerCentralLayer H i) := by
  refine ⟨?_, ?_⟩
  · intro a b
    obtain ⟨x, rfl⟩ :=
      QuotientGroup.mk'_surjective (lowerCentralLayerKernel H i) a
    obtain ⟨y, rfl⟩ :=
      QuotientGroup.mk'_surjective (lowerCentralLayerKernel H i) b
    apply commutatorElement_eq_one_iff_mul_comm.mp
    rw [← map_commutatorElement]
    exact (QuotientGroup.eq_one_iff _).mpr
      (commutatorElement_mem_lowerCentralLayerKernel H i x y)
  · intro a
    obtain ⟨x, rfl⟩ :=
      QuotientGroup.mk'_surjective (lowerCentralLayerKernel H i) a
    rw [← map_pow]
    exact (QuotientGroup.eq_one_iff _).mpr
      (sq_mem_lowerCentralLayerKernel H i x)

/-- The ambient automorphism action restricted to the `i`-th lower-central
term. -/
def lowerCentralTermAction
    {H : Type uH} {X : Type uX} [Group H] [Group X]
    (phi : X →* MulAut H) (i : ℕ) :
    X →* MulAut ↥(lowerCentralTerm H i) :=
  (IsAInvariant.lowerCentralSeries phi i).restrict

/-- The denominator `Hᵢ² Hᵢ₊₁` is invariant under every ambient
automorphism action restricted to `Hᵢ`.

This deliberately does not claim that `Hᵢ₊₁` is characteristic under every
abstract automorphism of `Hᵢ`; invariance under restrictions of ambient
automorphisms is exactly what Higman's induced action requires. -/
theorem lowerCentralLayerKernel_isInvariant
    {H : Type uH} {X : Type uX} [Group H] [Group X]
    (phi : X →* MulAut H) (i : ℕ) :
    IsAInvariant (lowerCentralTermAction phi i)
      (lowerCentralLayerKernel H i) := by
  apply IsAInvariant.sup
  · exact IsAInvariant.of_characteristic _
  · exact (IsAInvariant.lowerCentralSeries phi i).subgroupOf
      (IsAInvariant.lowerCentralSeries phi (i + 1))

/-- The action induced on Higman's layer `L_(i+1)`. -/
noncomputable def lowerCentralLayerAction
    {H : Type uH} {X : Type uX} [Group H] [Group X]
    (phi : X →* MulAut H) (i : ℕ) :
    X →* MulAut (lowerCentralLayer H i) :=
  (lowerCentralLayerKernel_isInvariant phi i).quotientMulAutHom

/-- The induced layer action agrees with the ambient action on
representatives. -/
@[simp]
theorem lowerCentralLayerAction_apply_mk
    {H : Type uH} {X : Type uX} [Group H] [Group X]
    (phi : X →* MulAut H) (i : ℕ) (g : X)
    (x : ↥(lowerCentralTerm H i)) :
    lowerCentralLayerAction phi i g
        (QuotientGroup.mk' (lowerCentralLayerKernel H i) x) =
      QuotientGroup.mk' (lowerCentralLayerKernel H i)
        (lowerCentralTermAction phi i g x) := rfl

/-! ## The canonical `F_2` representation -/

/-- Commutativity of a lower-central layer, packaged without changing its
canonical quotient-group operations. -/
abbrev lowerCentralLayerIsMulCommutative
    (H : Type uH) [Group H] (i : ℕ) :
    IsMulCommutative (lowerCentralLayer H i) :=
  IsMulCommutative.of_comm (lowerCentralLayer_isElementaryAbelian H i).comm

/-- The canonical `F_2`-module structure on an elementary lower-central
layer.  It is derived from the exponent-two theorem, not supplied as data. -/
noncomputable abbrev lowerCentralLayerZmodModule
    (H : Type uH) [Group H] (i : ℕ) :
    letI : IsMulCommutative (lowerCentralLayer H i) :=
      lowerCentralLayerIsMulCommutative H i
    Module (ZMod 2) (Additive (lowerCentralLayer H i)) :=
  (lowerCentralLayer_isElementaryAbelian H i).zmodModule

/-- Higman’s induced action on `L_(i+1)`, viewed as its canonical linear
representation over `F_2`. -/
noncomputable def lowerCentralLayerRepresentation
    {H : Type uH} {X : Type uX} [Group H] [Group X]
    (phi : X →* MulAut H) (i : ℕ) :
    letI : IsMulCommutative (lowerCentralLayer H i) :=
      lowerCentralLayerIsMulCommutative H i
    letI : Module (ZMod 2) (Additive (lowerCentralLayer H i)) :=
      lowerCentralLayerZmodModule H i
    Representation (ZMod 2) X (Additive (lowerCentralLayer H i)) := by
  letI : IsMulCommutative (lowerCentralLayer H i) :=
    lowerCentralLayerIsMulCommutative H i
  letI : Module (ZMod 2) (Additive (lowerCentralLayer H i)) :=
    lowerCentralLayerZmodModule H i
  letI : MulDistribMulAction X (lowerCentralLayer H i) :=
    MulDistribMulAction.compHom _ (lowerCentralLayerAction phi i)
  exact Representation.ofDistribMulAction
    (ZMod 2) X (Additive (lowerCentralLayer H i))

/-- The layer representation is exactly the induced quotient action on
underlying group elements. -/
theorem lowerCentralLayerRepresentation_apply
    {H : Type uH} {X : Type uX} [Group H] [Group X]
    (phi : X →* MulAut H) (i : ℕ) (g : X)
    (q : lowerCentralLayer H i) :
    letI : IsMulCommutative (lowerCentralLayer H i) :=
      lowerCentralLayerIsMulCommutative H i
    letI : Module (ZMod 2) (Additive (lowerCentralLayer H i)) :=
      lowerCentralLayerZmodModule H i
    lowerCentralLayerRepresentation phi i g (Additive.ofMul q) =
      Additive.ofMul (lowerCentralLayerAction phi i g q) := by
  letI : IsMulCommutative (lowerCentralLayer H i) :=
    lowerCentralLayerIsMulCommutative H i
  letI : Module (ZMod 2) (Additive (lowerCentralLayer H i)) :=
    lowerCentralLayerZmodModule H i
  rfl

/-- The cardinality of a finite lower-central layer is `2` to its canonical
`F_2`-dimension.  This is the source of Higman’s notation `|L_i| = 2^n`. -/
theorem lowerCentralLayer_card_eq_pow_finrank
    (H : Type uH) [Group H] [Finite H] (i : ℕ) :
    letI : IsMulCommutative (lowerCentralLayer H i) :=
      lowerCentralLayerIsMulCommutative H i
    letI : Module (ZMod 2) (Additive (lowerCentralLayer H i)) :=
      lowerCentralLayerZmodModule H i
    Nat.card (lowerCentralLayer H i) =
      2 ^ Module.finrank (ZMod 2) (Additive (lowerCentralLayer H i)) := by
  letI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  exact (lowerCentralLayer_isElementaryAbelian H i).card_eq_pow_finrank


local instance instLowerCentralLayerKernelInAmbientNormal
    (H : Type uH) [Group H] (i : ℕ) :
    (lowerCentralLayerKernelInAmbient H i).Normal :=
  lowerCentralLayerKernelInAmbient_normal H i

/-- The next lower-central term is one of the two factors of the ambient
layer kernel. -/
theorem lowerCentralTerm_succ_le_layerKernelInAmbient
    (H : Type uH) [Group H] (i : ℕ) :
    lowerCentralTerm H (i + 1) ≤
      lowerCentralLayerKernelInAmbient H i := by
  rw [lowerCentralLayerKernelInAmbient_eq]
  exact le_sup_right

/-- Quotienting by the second-layer kernel kills the third lower-central
term. -/
theorem lowerCentralSeries_two_map_layerKernel_one_eq_bot
    (H : Type uH) [Group H] :
    (lowerCentralTerm H 2).map
        (QuotientGroup.mk' (lowerCentralLayerKernelInAmbient H 1)) = ⊥ := by
  rw [Subgroup.map_eq_bot_iff, QuotientGroup.ker_mk']
  simpa using lowerCentralTerm_succ_le_layerKernelInAmbient H 1

/-- The quotient `H / (H₂² H₃)` has nilpotency class at most two. -/
theorem quotient_layerKernel_one_lowerCentralSeries_two_eq_bot
    (H : Type uH) [Group H] :
    (⊤ : Subgroup (H ⧸ lowerCentralLayerKernelInAmbient H 1)).lowerCentralSeries 2 = ⊥ := by
  rw [← Subgroup.map_top_of_surjective
      (QuotientGroup.mk' (lowerCentralLayerKernelInAmbient H 1))
      (QuotientGroup.mk'_surjective _),
    ← Subgroup.map_lowerCentralSeries]
  exact lowerCentralSeries_two_map_layerKernel_one_eq_bot H

/-- In the same quotient, the commutator subgroup is central. -/
theorem quotient_layerKernel_one_commutator_le_center
    (H : Type uH) [Group H] :
    _root_.commutator (H ⧸ lowerCentralLayerKernelInAmbient H 1) ≤
      Subgroup.center (H ⧸ lowerCentralLayerKernelInAmbient H 1) := by
  have hthree := quotient_layerKernel_one_lowerCentralSeries_two_eq_bot H
  rw [Subgroup.lowerCentralSeries_succ,
    Subgroup.top_lowerCentralSeries_one] at hthree
  have hcentralizer :
      _root_.commutator (H ⧸ lowerCentralLayerKernelInAmbient H 1) ≤
        Subgroup.centralizer
          (⊤ : Subgroup (H ⧸ lowerCentralLayerKernelInAmbient H 1)) :=
    (Subgroup.commutator_eq_bot_iff_le_centralizer.mp hthree)
  simpa only [Subgroup.coe_top, Subgroup.centralizer_univ] using hcentralizer

/-- The natural embedding of the second layer into the ambient class-two
quotient. -/
noncomputable def lowerCentralLayerOneToAmbientQuotient
    (H : Type uH) [Group H] :
    lowerCentralLayer H 1 →*
      H ⧸ lowerCentralLayerKernelInAmbient H 1 :=
  QuotientGroup.map
    (lowerCentralLayerKernel H 1)
    (lowerCentralLayerKernelInAmbient H 1)
    (lowerCentralTerm H 1).subtype (by
      rw [← Subgroup.map_le_iff_le_comap]
      exact le_rfl)

/-- The natural map of the second layer is injective. -/
theorem lowerCentralLayerOneToAmbientQuotient_injective
    (H : Type uH) [Group H] :
    Function.Injective (lowerCentralLayerOneToAmbientQuotient H) := by
  rw [lowerCentralLayerOneToAmbientQuotient,
    ← MonoidHom.ker_eq_bot_iff, QuotientGroup.ker_map,
    Subgroup.map_eq_bot_iff, QuotientGroup.ker_mk']
  rw [← lowerCentralLayerKernelInAmbient_subgroupOf H 1]
  exact le_rfl

/-- A commutator of first-term representatives, as an element of the second
lower-central term. -/
def lowerCentralCommutator
    (H : Type uH) [Group H]
    (x y : ↥(lowerCentralTerm H 0)) :
    ↥(lowerCentralTerm H 1) :=
  ⟨⁅(x : H), (y : H)⁆, by
    rw [lowerCentralTerm, Subgroup.top_lowerCentralSeries_one]
    exact Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _)⟩

/-- The raw commutator value in `L₂`. -/
def lowerCentralCommutatorValue
    (H : Type uH) [Group H]
    (x y : ↥(lowerCentralTerm H 0)) :
    lowerCentralLayer H 1 :=
  QuotientGroup.mk' (lowerCentralLayerKernel H 1)
    (lowerCentralCommutator H x y)

/-- Mapping a raw commutator value into the ambient quotient gives the
ambient commutator of the mapped representatives. -/
@[simp]
theorem lowerCentralLayerOneToAmbientQuotient_commutatorValue
    (H : Type uH) [Group H]
    (x y : ↥(lowerCentralTerm H 0)) :
    lowerCentralLayerOneToAmbientQuotient H
        (lowerCentralCommutatorValue H x y) =
      ⁅QuotientGroup.mk' (lowerCentralLayerKernelInAmbient H 1) (x : H),
        QuotientGroup.mk' (lowerCentralLayerKernelInAmbient H 1) (y : H)⁆ := by
  simp [lowerCentralLayerOneToAmbientQuotient,
    lowerCentralCommutatorValue, lowerCentralCommutator]
  rfl


/-- In a class-two group, the commutator is multiplicative in the right slot.
This is derived from the left-slot identity and commutator inversion. -/
private theorem lowerCentral_commutatorElement_mul_right_of_class_le_two
    {G : Type*} [Group G]
    (hC : _root_.commutator G ≤ Subgroup.center G)
    (z a b : G) :
    ⁅z, a * b⁆ = ⁅z, a⁆ * ⁅z, b⁆ := by
  have hswap : ⁅z, a⁆ * ⁅z, b⁆ = ⁅z, b⁆ * ⁅z, a⁆ := by
    have hca : ⁅z, a⁆ ∈ Subgroup.center G :=
      hC (OddOrder.Isaacs.Ch04.commutatorElement_mem_commutator_top z a)
    exact (Subgroup.mem_center_iff.mp hca _).symm
  have hinv : ⁅a * b, z⁆⁻¹ = ⁅z, a * b⁆ :=
    commutatorElement_inv (a * b) z
  have hleft : ⁅a * b, z⁆ = ⁅a, z⁆ * ⁅b, z⁆ :=
    OddOrder.Isaacs.Ch04.commutatorElement_mul_left_of_class_le_two
      hC a b z
  rw [← hinv, hleft, mul_inv_rev, commutatorElement_inv,
    commutatorElement_inv, hswap]

/-- The raw commutator value is multiplicative in the right variable. -/
theorem lowerCentralCommutatorValue_mul_right
    (H : Type uH) [Group H]
    (x y z : ↥(lowerCentralTerm H 0)) :
    lowerCentralCommutatorValue H x (y * z) =
      lowerCentralCommutatorValue H x y *
        lowerCentralCommutatorValue H x z := by
  apply lowerCentralLayerOneToAmbientQuotient_injective H
  rw [map_mul]
  simp only [lowerCentralLayerOneToAmbientQuotient_commutatorValue,
    Subgroup.coe_mul, map_mul]
  exact lowerCentral_commutatorElement_mul_right_of_class_le_two
    (quotient_layerKernel_one_commutator_le_center H) _ _ _

/-- The raw commutator value is multiplicative in the left variable. -/
theorem lowerCentralCommutatorValue_mul_left
    (H : Type uH) [Group H]
    (x y z : ↥(lowerCentralTerm H 0)) :
    lowerCentralCommutatorValue H (x * y) z =
      lowerCentralCommutatorValue H x z *
        lowerCentralCommutatorValue H y z := by
  apply lowerCentralLayerOneToAmbientQuotient_injective H
  rw [map_mul]
  simp only [lowerCentralLayerOneToAmbientQuotient_commutatorValue,
    Subgroup.coe_mul, map_mul]
  exact OddOrder.Isaacs.Ch04.commutatorElement_mul_left_of_class_le_two
    (quotient_layerKernel_one_commutator_le_center H) _ _ _

local instance instLowerCentralLayerIsMulCommutative
    (H : Type uH) [Group H] (i : ℕ) :
    IsMulCommutative (lowerCentralLayer H i) :=
  ⟨⟨(lowerCentralLayer_isElementaryAbelian H i).1⟩⟩

noncomputable local instance instLowerCentralLayerZModTwoModule
    (H : Type uH) [Group H] (i : ℕ) :
    Module (ZMod 2) (Additive (lowerCentralLayer H i)) :=
  lowerCentralLayerZmodModule H i

/-- The raw commutator, as a homomorphism in both variables before quotienting L1. -/
noncomputable def lowerCentralCommutatorBihomRaw
    (H : Type uH) [Group H] :
    ↥(lowerCentralTerm H 0) →*
      ↥(lowerCentralTerm H 0) →*
        lowerCentralLayer H 1 where
  toFun x :=
    { toFun := lowerCentralCommutatorValue H x
      map_one' := by
        apply (QuotientGroup.eq_one_iff _).mpr
        rw [show lowerCentralCommutator H x 1 = 1 from
          Subtype.ext (commutatorElement_one_right (x : H))]
        exact Subgroup.one_mem _
      map_mul' := lowerCentralCommutatorValue_mul_right H x }
  map_one' := by
    ext y
    apply (QuotientGroup.eq_one_iff _).mpr
    rw [show lowerCentralCommutator H 1 y = 1 from
      Subtype.ext (commutatorElement_one_left (y : H))]
    exact Subgroup.one_mem _
  map_mul' x x' := by
    ext y
    exact lowerCentralCommutatorValue_mul_left H x x' y

/-- The raw bihomomorphism kills the first-layer kernel in the right slot. -/
theorem lowerCentralCommutatorBihomRaw_ker_right
    (H : Type uH) [Group H]
    (x : ↥(lowerCentralTerm H 0))
    {k : ↥(lowerCentralTerm H 0)}
    (hk : k ∈ lowerCentralLayerKernel H 0) :
    lowerCentralCommutatorBihomRaw H x k = 1 := by
  apply (show lowerCentralLayerKernel H 0 ≤
      (lowerCentralCommutatorBihomRaw H x).ker by
    rw [lowerCentralLayerKernel]
    apply sup_le
    · rw [Agemo, Subgroup.closure_le]
      rintro _ ⟨a, rfl⟩
      change lowerCentralCommutatorBihomRaw H x (a ^ (2 ^ 1)) = 1
      rw [map_pow]
      simpa using
        (lowerCentralLayer_isElementaryAbelian H 1).2
          (lowerCentralCommutatorBihomRaw H x a)
    · intro z hz
      rw [MonoidHom.mem_ker]
      apply (QuotientGroup.eq_one_iff _).mpr
      change lowerCentralCommutator H x z ∈
        Agemo (↥(lowerCentralTerm H 1)) 2 1 ⊔
          (lowerCentralTerm H 2).subgroupOf (lowerCentralTerm H 1)
      apply (show (lowerCentralTerm H 2).subgroupOf
          (lowerCentralTerm H 1) ≤ _ from le_sup_right)
      change ⁅(x : H), (z : H)⁆ ∈ lowerCentralTerm H 2
      rw [← commutatorElement_inv]
      apply Subgroup.inv_mem
      rw [lowerCentralTerm, Subgroup.lowerCentralSeries_succ]
      exact Subgroup.commutator_mem_commutator hz (Subgroup.mem_top _))
  exact hk

/-- The raw bihomomorphism kills the first-layer kernel in the left slot. -/
theorem lowerCentralCommutatorBihomRaw_ker_left
    (H : Type uH) [Group H]
    {k : ↥(lowerCentralTerm H 0)}
    (hk : k ∈ lowerCentralLayerKernel H 0)
    (y : ↥(lowerCentralTerm H 0)) :
    lowerCentralCommutatorBihomRaw H k y = 1 := by
  apply (show lowerCentralLayerKernel H 0 ≤
      ((MonoidHom.eval y).comp
        (lowerCentralCommutatorBihomRaw H)).ker by
    rw [lowerCentralLayerKernel]
    apply sup_le
    · rw [Agemo, Subgroup.closure_le]
      rintro _ ⟨a, rfl⟩
      change lowerCentralCommutatorBihomRaw H (a ^ (2 ^ 1)) y = 1
      rw [map_pow]
      simpa using
        (lowerCentralLayer_isElementaryAbelian H 1).2
          (lowerCentralCommutatorBihomRaw H a y)
    · intro z hz
      rw [MonoidHom.mem_ker]
      apply (QuotientGroup.eq_one_iff _).mpr
      change lowerCentralCommutator H z y ∈
        Agemo (↥(lowerCentralTerm H 1)) 2 1 ⊔
          (lowerCentralTerm H 2).subgroupOf (lowerCentralTerm H 1)
      apply (show (lowerCentralTerm H 2).subgroupOf
          (lowerCentralTerm H 1) ≤ _ from le_sup_right)
      change ⁅(z : H), (y : H)⁆ ∈ lowerCentralTerm H 2
      rw [lowerCentralTerm, Subgroup.lowerCentralSeries_succ]
      exact Subgroup.commutator_mem_commutator hz (Subgroup.mem_top _))
  exact hk

/-- The commutator bihomomorphism after descending the right argument to L1. -/
noncomputable def lowerCentralCommutatorBihomRight
    (H : Type uH) [Group H] :
    ↥(lowerCentralTerm H 0) →*
      lowerCentralLayer H 0 →*
        lowerCentralLayer H 1 where
  toFun x :=
    QuotientGroup.lift
      (lowerCentralLayerKernel H 0)
      (lowerCentralCommutatorBihomRaw H x)
      (fun k hk =>
        MonoidHom.mem_ker.mpr
          (lowerCentralCommutatorBihomRaw_ker_right H x hk))
  map_one' := by
    ext q
    simp only [MonoidHom.comp_apply, QuotientGroup.mk'_apply,
      QuotientGroup.lift_mk', MonoidHom.one_apply, map_one]
  map_mul' x x' := by
    ext q
    simp only [MonoidHom.comp_apply, MonoidHom.mul_apply,
      QuotientGroup.mk'_apply, QuotientGroup.lift_mk', map_mul]

/-- The fully descended commutator pairing L1 →* L1 →* L2. -/
noncomputable def lowerCentralCommutatorBihom
    (H : Type uH) [Group H] :
    lowerCentralLayer H 0 →*
      lowerCentralLayer H 0 →*
        lowerCentralLayer H 1 :=
  QuotientGroup.lift
    (lowerCentralLayerKernel H 0)
    (lowerCentralCommutatorBihomRight H)
    (fun k hk =>
      MonoidHom.mem_ker.mpr (by
        ext q
        simp only [lowerCentralCommutatorBihomRight,
          MonoidHom.coe_mk, OneHom.coe_mk]
        exact lowerCentralCommutatorBihomRaw_ker_left H hk q))

/-- The descended pairing evaluates to the raw commutator class on representatives. -/
@[simp]
theorem lowerCentralCommutatorBihom_mk
    (H : Type uH) [Group H]
    (x y : ↥(lowerCentralTerm H 0)) :
    lowerCentralCommutatorBihom H
        (QuotientGroup.mk' (lowerCentralLayerKernel H 0) x)
        (QuotientGroup.mk' (lowerCentralLayerKernel H 0) y) =
      lowerCentralCommutatorValue H x y := by
  rfl

/-- The descended commutator pairing is alternating. -/
@[simp]
theorem lowerCentralCommutatorBihom_self
    (H : Type uH) [Group H]
    (v : lowerCentralLayer H 0) :
    lowerCentralCommutatorBihom H v v = 1 := by
  obtain ⟨x, rfl⟩ :=
    QuotientGroup.mk'_surjective (lowerCentralLayerKernel H 0) v
  rw [lowerCentralCommutatorBihom_mk]
  apply (QuotientGroup.eq_one_iff _).mpr
  rw [show lowerCentralCommutator H x x = 1 from
    Subtype.ext (commutatorElement_self (x : H))]
  exact Subgroup.one_mem _


/-! ## Generic conversion of a multiplicative bihomomorphism -/

/-- A multiplicative bihomomorphism, written additively in both inputs and
the output. -/
def bihomToAdditive
    {L1 : Type uL1} {L2 : Type uL2}
    [Group L1] [Group L2] [IsMulCommutative L1] [IsMulCommutative L2]
    (b : L1 →* L1 →* L2) :
    Additive L1 →+ Additive L1 →+ Additive L2 :=
  AddMonoidHom.mk'
    (fun x => (b (Additive.toMul x)).toAdditive)
    (fun x x' => by
      ext y
      change Additive.ofMul
          (b (Additive.toMul x * Additive.toMul x') (Additive.toMul y)) = _
      rw [map_mul, MonoidHom.mul_apply]
      rfl)

@[simp]
theorem bihomToAdditive_apply
    {L1 : Type uL1} {L2 : Type uL2}
    [Group L1] [Group L2] [IsMulCommutative L1] [IsMulCommutative L2]
    (b : L1 →* L1 →* L2) (x y : Additive L1) :
    bihomToAdditive b x y =
      Additive.ofMul (b (Additive.toMul x) (Additive.toMul y)) := rfl

/-- Every bi-additive map between `ZMod 2`-modules is canonically bilinear.

The inner additive hom is converted by `AddMonoidHom.toZModLinearMap`; the
outer additive hom into the resulting linear-map space is converted in the
same way. -/
noncomputable def bihomToZModTwoBilinear
    {L1 : Type uL1} {L2 : Type uL2}
    [Group L1] [Group L2] [IsMulCommutative L1] [IsMulCommutative L2]
    [Module (ZMod 2) (Additive L1)] [Module (ZMod 2) (Additive L2)]
    (b : L1 →* L1 →* L2) :
    Additive L1 →ₗ[ZMod 2] Additive L1 →ₗ[ZMod 2] Additive L2 :=
  (AddMonoidHom.mk'
    (fun x => (bihomToAdditive b x).toZModLinearMap 2)
    (fun x x' => by
      ext y
      simp [map_add])).toZModLinearMap 2

@[simp]
theorem bihomToZModTwoBilinear_apply
    {L1 : Type uL1} {L2 : Type uL2}
    [Group L1] [Group L2] [IsMulCommutative L1] [IsMulCommutative L2]
    [Module (ZMod 2) (Additive L1)] [Module (ZMod 2) (Additive L2)]
    (b : L1 →* L1 →* L2) (x y : Additive L1) :
    bihomToZModTwoBilinear b x y =
      Additive.ofMul (b (Additive.toMul x) (Additive.toMul y)) := rfl

/-- A multiplicatively alternating bihomomorphism becomes a bilinear map
whose diagonal is zero. -/
theorem bihomToZModTwoBilinear_self
    {L1 : Type uL1} {L2 : Type uL2}
    [Group L1] [Group L2] [IsMulCommutative L1] [IsMulCommutative L2]
    [Module (ZMod 2) (Additive L1)] [Module (ZMod 2) (Additive L2)]
    (b : L1 →* L1 →* L2) (hself : ∀ x : L1, b x x = 1)
    (x : Additive L1) :
    bihomToZModTwoBilinear b x x = 0 := by
  change Additive.ofMul
      (b (Additive.toMul x) (Additive.toMul x)) = Additive.ofMul 1
  rw [hself]

/-- Package a bilinear map with zero diagonal as a degree-two alternating
map, allowing an arbitrary module as codomain. -/
def bilinToAltModule
    {R M N : Type*} [CommRing R]
    [AddCommGroup M] [Module R M] [AddCommGroup N] [Module R N]
    (β : M →ₗ[R] M →ₗ[R] N) (halt : ∀ x : M, β x x = 0) :
    M [⋀^Fin 2]→ₗ[R] N where
  toFun v := β (v 0) (v 1)
  map_update_add' m i x y := by
    fin_cases i <;>
      simp only [Function.update, Fin.isValue, dite_eq_ite] <;>
      norm_num
  map_update_smul' m i c x := by
    fin_cases i <;>
      simp only [Function.update, Fin.isValue, dite_eq_ite] <;>
      norm_num
  map_eq_zero_of_eq' v i j hvij hij := by
    have h01 : v 0 = v 1 := by
      fin_cases i <;> fin_cases j <;>
        first | exact absurd rfl hij | simp_all
    simp only [h01, halt]

@[simp]
theorem bilinToAltModule_apply
    {R M N : Type*} [CommRing R]
    [AddCommGroup M] [Module R M] [AddCommGroup N] [Module R N]
    (β : M →ₗ[R] M →ₗ[R] N) (halt : ∀ x : M, β x x = 0)
    (v : Fin 2 → M) :
    bilinToAltModule β halt v = β (v 0) (v 1) := rfl


/-! ## The actual lower-central commutator maps -/

/-- The descended commutator pairing as a `ZMod 2`-bilinear map. -/
noncomputable def lowerCentralCommutatorBilinear
    (H : Type uH) [Group H] :
    Additive (lowerCentralLayer H 0) →ₗ[ZMod 2]
      Additive (lowerCentralLayer H 0) →ₗ[ZMod 2]
        Additive (lowerCentralLayer H 1) :=
  bihomToZModTwoBilinear (lowerCentralCommutatorBihom H)

@[simp]
theorem lowerCentralCommutatorBilinear_apply
    (H : Type uH) [Group H]
    (x y : Additive (lowerCentralLayer H 0)) :
    lowerCentralCommutatorBilinear H x y =
      Additive.ofMul
        (lowerCentralCommutatorBihom H
          (Additive.toMul x) (Additive.toMul y)) := rfl

@[simp]
theorem lowerCentralCommutatorBilinear_mk
    (H : Type uH) [Group H]
    (x y : ↥(lowerCentralTerm H 0)) :
    lowerCentralCommutatorBilinear H
        (Additive.ofMul
          (QuotientGroup.mk' (lowerCentralLayerKernel H 0) x))
        (Additive.ofMul
          (QuotientGroup.mk' (lowerCentralLayerKernel H 0) y)) =
      Additive.ofMul (lowerCentralCommutatorValue H x y) := by
  change Additive.ofMul
      (lowerCentralCommutatorBihom H
        (QuotientGroup.mk' (lowerCentralLayerKernel H 0) x)
        (QuotientGroup.mk' (lowerCentralLayerKernel H 0) y)) = _
  rw [lowerCentralCommutatorBihom_mk]

/-- Alternation of the group commutator becomes diagonal vanishing. -/
@[simp]
theorem lowerCentralCommutatorBilinear_self
    (H : Type uH) [Group H]
    (x : Additive (lowerCentralLayer H 0)) :
    lowerCentralCommutatorBilinear H x x = 0 :=
  bihomToZModTwoBilinear_self
    (lowerCentralCommutatorBihom H)
    (lowerCentralCommutatorBihom_self H) x

/-- The descended commutator pairing as a degree-two alternating map. -/
noncomputable def lowerCentralCommutatorAlternating
    (H : Type uH) [Group H] :
    Additive (lowerCentralLayer H 0) [⋀^Fin 2]→ₗ[ZMod 2]
      Additive (lowerCentralLayer H 1) :=
  bilinToAltModule (lowerCentralCommutatorBilinear H)
    (lowerCentralCommutatorBilinear_self H)

@[simp]
theorem lowerCentralCommutatorAlternating_apply
    (H : Type uH) [Group H]
    (v : Fin 2 → Additive (lowerCentralLayer H 0)) :
    lowerCentralCommutatorAlternating H v =
      lowerCentralCommutatorBilinear H (v 0) (v 1) := rfl

/-- The image in `L₂` of an ambient commutator. -/
def lowerCentralRawBracket
    (H : Type uH) [Group H] (x y : H) : lowerCentralLayer H 1 :=
  QuotientGroup.mk' (lowerCentralLayerKernel H 1)
    ⟨⁅x, y⁆, by
      change ⁅x, y⁆ ∈ ⁅(⊤ : Subgroup H), ⊤⁆
      exact Subgroup.commutator_mem_commutator (Subgroup.mem_top x) (Subgroup.mem_top y)⟩

theorem lowerCentralRawBracket_span_eq_top
    (H : Type uH) [Group H] :
    letI : IsMulCommutative (lowerCentralLayer H 1) :=
      lowerCentralLayerIsMulCommutative H 1
    letI : Module (ZMod 2) (Additive (lowerCentralLayer H 1)) :=
      lowerCentralLayerZmodModule H 1
    Submodule.span (ZMod 2)
        (Set.range fun z : H × H => Additive.ofMul (lowerCentralRawBracket H z.1 z.2)) = ⊤ := by
  letI : IsMulCommutative (lowerCentralLayer H 1) :=
    lowerCentralLayerIsMulCommutative H 1
  letI : Module (ZMod 2) (Additive (lowerCentralLayer H 1)) :=
    lowerCentralLayerZmodModule H 1
  let S : Set H :=
    {c | ∃ x ∈ (⊤ : Subgroup H), ∃ y ∈ (⊤ : Subgroup H), ⁅x, y⁆ = c}
  have hterm : lowerCentralTerm H 1 = Subgroup.closure S := by
    rfl
  let P : ∀ z : H, z ∈ Subgroup.closure S → Prop :=
    fun z hz =>
      Additive.ofMul
          (QuotientGroup.mk' (lowerCentralLayerKernel H 1)
            (⟨z, hterm.symm ▸ hz⟩ : lowerCentralTerm H 1)) ∈
        Submodule.span (ZMod 2)
          (Set.range fun w : H × H =>
            Additive.ofMul (lowerCentralRawBracket H w.1 w.2))
  have hclosure : ∀ z (hz : z ∈ Subgroup.closure S), P z hz := by
    intro z hz
    refine Subgroup.closure_induction (p := P) ?_ ?_ ?_ ?_ hz
    · intro c hc
      rcases hc with ⟨x, _hx, y, _hy, rfl⟩
      exact Submodule.subset_span ⟨(x, y), rfl⟩
    · dsimp only [P]
      change (0 : Additive (lowerCentralLayer H 1)) ∈
        Submodule.span (ZMod 2)
          (Set.range fun w : H × H =>
            Additive.ofMul (lowerCentralRawBracket H w.1 w.2))
      exact Submodule.zero_mem _
    · intro a b ha hb iha ihb
      dsimp only [P] at iha ihb ⊢
      have hab :
          (⟨a * b, hterm.symm ▸ Subgroup.mul_mem _ ha hb⟩ : lowerCentralTerm H 1) =
            (⟨a, hterm.symm ▸ ha⟩ : lowerCentralTerm H 1) *
              (⟨b, hterm.symm ▸ hb⟩ : lowerCentralTerm H 1) := by
        rfl
      rw [hab, map_mul]
      exact Submodule.add_mem _ iha ihb
    · intro a ha iha
      dsimp only [P] at iha ⊢
      have hainv :
          (⟨a⁻¹, hterm.symm ▸ Subgroup.inv_mem _ ha⟩ : lowerCentralTerm H 1) =
            (⟨a, hterm.symm ▸ ha⟩ : lowerCentralTerm H 1)⁻¹ := by
        rfl
      rw [hainv, map_inv]
      exact Submodule.neg_mem _ iha
  refine Submodule.eq_top_iff'.mpr fun q => ?_
  change Additive.ofMul q.toMul ∈ Submodule.span (ZMod 2)
    (Set.range fun z : H × H => Additive.ofMul (lowerCentralRawBracket H z.1 z.2))
  obtain ⟨z, hzq⟩ :=
    QuotientGroup.mk'_surjective (lowerCentralLayerKernel H 1) q.toMul
  rw [← hzq]
  rcases z with ⟨z, hz⟩
  have hz' : z ∈ Subgroup.closure S := hterm ▸ hz
  simpa [P] using hclosure z hz'

/-- Any descended pairing agreeing with the raw commutator on representatives
has spanning range; no surjectivity hypothesis on the pairing is used. -/
theorem lowerCentralPairing_span_eq_top_of_apply_mk
    (H : Type uH) [Group H]
    (b : lowerCentralLayer H 0 → lowerCentralLayer H 0 →
      Additive (lowerCentralLayer H 1))
    (hb : ∀ x y : H,
      b (QuotientGroup.mk' (lowerCentralLayerKernel H 0)
          (⟨x, Subgroup.mem_top x⟩ : lowerCentralTerm H 0))
        (QuotientGroup.mk' (lowerCentralLayerKernel H 0)
          (⟨y, Subgroup.mem_top y⟩ : lowerCentralTerm H 0)) =
        Additive.ofMul (lowerCentralRawBracket H x y)) :
    letI : IsMulCommutative (lowerCentralLayer H 1) :=
      lowerCentralLayerIsMulCommutative H 1
    letI : Module (ZMod 2) (Additive (lowerCentralLayer H 1)) :=
      lowerCentralLayerZmodModule H 1
    Submodule.span (ZMod 2)
        (Set.range fun z : lowerCentralLayer H 0 × lowerCentralLayer H 0 =>
          b z.1 z.2) = ⊤ := by
  letI : IsMulCommutative (lowerCentralLayer H 1) :=
    lowerCentralLayerIsMulCommutative H 1
  letI : Module (ZMod 2) (Additive (lowerCentralLayer H 1)) :=
    lowerCentralLayerZmodModule H 1
  apply top_unique
  rw [← lowerCentralRawBracket_span_eq_top H]
  apply Submodule.span_mono
  rintro _ ⟨⟨x, y⟩, rfl⟩
  refine ⟨(
    QuotientGroup.mk' (lowerCentralLayerKernel H 0)
      (⟨x, Subgroup.mem_top x⟩ : lowerCentralTerm H 0),
    QuotientGroup.mk' (lowerCentralLayerKernel H 0)
      (⟨y, Subgroup.mem_top y⟩ : lowerCentralTerm H 0)), ?_⟩
  exact hb x y

theorem lowerCentralLayerAction_rawBracket
    {H : Type uH} {X : Type uX} [Group H] [Group X]
    (phi : X →* MulAut H) (g : X) (x y : H) :
    lowerCentralLayerAction phi 1 g (lowerCentralRawBracket H x y) =
      lowerCentralRawBracket H (phi g x) (phi g y) := by
  rw [lowerCentralRawBracket, lowerCentralLayerAction_apply_mk]
  apply congrArg (QuotientGroup.mk' (lowerCentralLayerKernel H 1))
  ext
  exact map_commutatorElement (phi g) x y

theorem lowerCentralPairing_equivariant_of_apply_mk
    {H : Type uH} {X : Type uX} [Group H] [Group X]
    (phi : X →* MulAut H)
    (b : lowerCentralLayer H 0 → lowerCentralLayer H 0 →
      Additive (lowerCentralLayer H 1))
    (hb : ∀ x y : H,
      b (QuotientGroup.mk' (lowerCentralLayerKernel H 0)
          (⟨x, Subgroup.mem_top x⟩ : lowerCentralTerm H 0))
        (QuotientGroup.mk' (lowerCentralLayerKernel H 0)
          (⟨y, Subgroup.mem_top y⟩ : lowerCentralTerm H 0)) =
        Additive.ofMul (lowerCentralRawBracket H x y))
    (g : X) (u v : lowerCentralLayer H 0) :
    letI : IsMulCommutative (lowerCentralLayer H 1) :=
      lowerCentralLayerIsMulCommutative H 1
    letI : Module (ZMod 2) (Additive (lowerCentralLayer H 1)) :=
      lowerCentralLayerZmodModule H 1
    lowerCentralLayerRepresentation phi 1 g (b u v) =
      b (lowerCentralLayerAction phi 0 g u)
        (lowerCentralLayerAction phi 0 g v) := by
  letI : IsMulCommutative (lowerCentralLayer H 1) :=
    lowerCentralLayerIsMulCommutative H 1
  letI : Module (ZMod 2) (Additive (lowerCentralLayer H 1)) :=
    lowerCentralLayerZmodModule H 1
  obtain ⟨x, rfl⟩ :=
    QuotientGroup.mk'_surjective (lowerCentralLayerKernel H 0) u
  obtain ⟨y, rfl⟩ :=
    QuotientGroup.mk'_surjective (lowerCentralLayerKernel H 0) v
  have hx : lowerCentralTermAction phi 0 g x =
      (⟨phi g x.1, Subgroup.mem_top _⟩ : lowerCentralTerm H 0) := by
    ext
    rfl
  have hy : lowerCentralTermAction phi 0 g y =
      (⟨phi g y.1, Subgroup.mem_top _⟩ : lowerCentralTerm H 0) := by
    ext
    rfl
  rw [hb x.1 y.1, lowerCentralLayerRepresentation_apply]
  change Additive.ofMul
      (lowerCentralLayerAction phi 1 g (lowerCentralRawBracket H x.1 y.1)) = _
  rw [lowerCentralLayerAction_rawBracket,
    lowerCentralLayerAction_apply_mk, lowerCentralLayerAction_apply_mk,
    hx, hy, hb]



/-- The actual commutator bilinear map has full spanning range in `L₂`. -/
theorem lowerCentralCommutatorBilinear_span_eq_top
    (H : Type uH) [Group H] :
    Submodule.span (ZMod 2)
        (Set.range fun z :
          Additive (lowerCentralLayer H 0) ×
            Additive (lowerCentralLayer H 0) =>
          lowerCentralCommutatorBilinear H z.1 z.2) = ⊤ := by
  change Submodule.span (ZMod 2)
      (Set.range fun z :
        lowerCentralLayer H 0 × lowerCentralLayer H 0 =>
        lowerCentralCommutatorBilinear H
          (Additive.ofMul z.1) (Additive.ofMul z.2)) = ⊤
  exact lowerCentralPairing_span_eq_top_of_apply_mk H
    (fun u v => lowerCentralCommutatorBilinear H
      (Additive.ofMul u) (Additive.ofMul v))
    (fun x y => by
      rw [lowerCentralCommutatorBilinear_mk]
      rfl)

/-- The actual commutator bilinear map intertwines every induced group action. -/
theorem lowerCentralCommutatorBilinear_equivariant
    {H : Type uH} {X : Type uX} [Group H] [Group X]
    (phi : X →* MulAut H) (g : X)
    (u v : Additive (lowerCentralLayer H 0)) :
    lowerCentralLayerRepresentation phi 1 g
        (lowerCentralCommutatorBilinear H u v) =
      lowerCentralCommutatorBilinear H
        (Additive.ofMul
          (lowerCentralLayerAction phi 0 g (Additive.toMul u)))
        (Additive.ofMul
          (lowerCentralLayerAction phi 0 g (Additive.toMul v))) := by
  let b : lowerCentralLayer H 0 → lowerCentralLayer H 0 →
      Additive (lowerCentralLayer H 1) :=
    fun x y => lowerCentralCommutatorBilinear H
      (Additive.ofMul x) (Additive.ofMul y)
  have hb : ∀ x y : H,
      b (QuotientGroup.mk' (lowerCentralLayerKernel H 0)
          (⟨x, Subgroup.mem_top x⟩ : lowerCentralTerm H 0))
        (QuotientGroup.mk' (lowerCentralLayerKernel H 0)
          (⟨y, Subgroup.mem_top y⟩ : lowerCentralTerm H 0)) =
        Additive.ofMul (lowerCentralRawBracket H x y) := by
    intro x y
    dsimp only [b]
    rw [lowerCentralCommutatorBilinear_mk]
    rfl
  simpa only [b, ofMul_toMul] using
    (lowerCentralPairing_equivariant_of_apply_mk phi b hb g
      (Additive.toMul u) (Additive.toMul v))


end OddOrder.Peterfalvi.Appendices.Suzuki2Groups
