/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Peterfalvi.Appendices.Suzuki2Groups.AgemoLayers
import OddOrder.GroupTheory.RepresentationTheory.ElementaryAbelianRepresentation

/-!
# Higman's elementary lower-central layers

G. Higman, *Suzuki 2-groups*, Illinois J. Math. 7 (1963), section 4,
pp. 84--85; used in Peterfalvi, Appendix III.

For the lower central series `H = H₁, H₂, ...`, Higman writes

`Lᵢ = Hᵢ / (Hᵢ² Hᵢ₊₁)`.

Mathlib numbers the same series from zero, so `lowerCentralTerm H 0` is
Higman's `H₁`, and `lowerCentralLayer H 0` is his `L₁`.  The denominator is
constructed, not postulated: it is generated by the squares in the current
term together with the next lower-central term.  This file supplies the
common carrier and automorphism-action infrastructure for Higman's Lemmas
4--9; the commutator pairing and the spectral argument will be added here as
that coherent cluster develops.
-/

set_option autoImplicit false

namespace OddOrder.Peterfalvi.Appendices.Suzuki2Groups

open OddOrder.GroupTheory
open OddOrder.Isaacs.Ch03
open scoped commutatorElement IsMulCommutative

universe uH uX

/-- The `i`-th lower-central term in mathlib's zero-based numbering.
It is Higman's `H_(i+1)`. -/
def lowerCentralTerm (H : Type uH) [Group H] (i : ℕ) : Subgroup H :=
  (⊤ : Subgroup H).lowerCentralSeries i

/-- The denominator `Hᵢ² Hᵢ₊₁`, viewed inside `Hᵢ`.

`Agemo _ 2 1` is the subgroup generated by squares.  The supremum is the
subgroup product because both factors are normal in the current term. -/
def lowerCentralLayerKernel (H : Type uH) [Group H] (i : ℕ) :
    Subgroup ↥(lowerCentralTerm H i) :=
  Agemo (↥(lowerCentralTerm H i)) 2 1 ⊔
    (lowerCentralTerm H (i + 1)).subgroupOf (lowerCentralTerm H i)

/-- The next lower-central term is normal inside the current term. -/
theorem lowerCentralNext_subgroupOf_normal (H : Type uH) [Group H] (i : ℕ) :
    ((lowerCentralTerm H (i + 1)).subgroupOf
      (lowerCentralTerm H i)).Normal := by
  have hnormal : (lowerCentralTerm H (i + 1)).Normal := by
    dsimp [lowerCentralTerm]
    infer_instance
  exact hnormal.subgroupOf _

/-- The denominator `Hᵢ² Hᵢ₊₁` is normal in `Hᵢ`. -/
instance lowerCentralLayerKernel_normal (H : Type uH) [Group H] (i : ℕ) :
    (lowerCentralLayerKernel H i).Normal := by
  dsimp [lowerCentralLayerKernel]
  letI : ((lowerCentralTerm H (i + 1)).subgroupOf
      (lowerCentralTerm H i)).Normal :=
    lowerCentralNext_subgroupOf_normal H i
  infer_instance

/-- The next lower-central term lies in the current one. -/
theorem lowerCentralTerm_succ_le (H : Type uH) [Group H] (i : ℕ) :
    lowerCentralTerm H (i + 1) ≤ lowerCentralTerm H i := by
  exact (⊤ : Subgroup H).lowerCentralSeries_antitone (Nat.le_succ i)

/-- The same denominator, embedded back into the ambient group `H`.

Keeping this ambient form records literally the source expression
`Hᵢ² Hᵢ₊₁`; the quotient carrier itself uses the corresponding subgroup of
`Hᵢ`. -/
def lowerCentralLayerKernelInAmbient (H : Type uH) [Group H] (i : ℕ) :
    Subgroup H :=
  (lowerCentralLayerKernel H i).map (lowerCentralTerm H i).subtype

/-- The ambient denominator is exactly the product of the subgroup generated
by squares in `Hᵢ` and `Hᵢ₊₁`. -/
theorem lowerCentralLayerKernelInAmbient_eq
    (H : Type uH) [Group H] (i : ℕ) :
    lowerCentralLayerKernelInAmbient H i =
      (Agemo (↥(lowerCentralTerm H i)) 2 1).map
          (lowerCentralTerm H i).subtype ⊔
        lowerCentralTerm H (i + 1) := by
  rw [lowerCentralLayerKernelInAmbient, lowerCentralLayerKernel,
    Subgroup.map_sup,
    Subgroup.map_subgroupOf_eq_of_le (lowerCentralTerm_succ_le H i)]

/-- The ambient denominator lies in `Hᵢ`, as required for the quotient. -/
theorem lowerCentralLayerKernelInAmbient_le
    (H : Type uH) [Group H] (i : ℕ) :
    lowerCentralLayerKernelInAmbient H i ≤ lowerCentralTerm H i :=
  Subgroup.map_subtype_le _

/-- The subgroup form of the ambient denominator recovers the kernel used by
the quotient definition. -/
theorem lowerCentralLayerKernelInAmbient_subgroupOf
    (H : Type uH) [Group H] (i : ℕ) :
    (lowerCentralLayerKernelInAmbient H i).subgroupOf
        (lowerCentralTerm H i) =
      lowerCentralLayerKernel H i := by
  rw [← Subgroup.map_subtype_inj,
    Subgroup.map_subgroupOf_eq_of_le
      (lowerCentralLayerKernelInAmbient_le H i)]
  rfl

/-- The ambient denominator is normal in `H`.  This follows from normality of
`Hᵢ`, characteristicity of its square subgroup, and normality of `Hᵢ₊₁`. -/
theorem lowerCentralLayerKernelInAmbient_normal
    (H : Type uH) [Group H] (i : ℕ) :
    (lowerCentralLayerKernelInAmbient H i).Normal := by
  rw [lowerCentralLayerKernelInAmbient_eq]
  haveI : (lowerCentralTerm H i).Normal := by
    dsimp [lowerCentralTerm]
    infer_instance
  haveI : ((Agemo (↥(lowerCentralTerm H i)) 2 1).map
      (lowerCentralTerm H i).subtype).Normal := inferInstance
  haveI : (lowerCentralTerm H (i + 1)).Normal := by
    dsimp [lowerCentralTerm]
    infer_instance
  infer_instance

/-- Higman's elementary lower-central layer
`L_(i+1) = H_(i+1) / (H_(i+1)^2 H_(i+2))`. -/
abbrev lowerCentralLayer (H : Type uH) [Group H] (i : ℕ) :=
  ↥(lowerCentralTerm H i) ⧸ lowerCentralLayerKernel H i

/-- Every square in the current lower-central term belongs to the layer
kernel. -/
theorem sq_mem_lowerCentralLayerKernel
    (H : Type uH) [Group H] (i : ℕ) (x : ↥(lowerCentralTerm H i)) :
    x ^ 2 ∈ lowerCentralLayerKernel H i := by
  change x ^ 2 ∈
    Agemo (↥(lowerCentralTerm H i)) 2 1 ⊔
      (lowerCentralTerm H (i + 1)).subgroupOf (lowerCentralTerm H i)
  apply (show Agemo (↥(lowerCentralTerm H i)) 2 1 ≤ _ from le_sup_left)
  simpa using
    (Agemo.mem_of_eq_pow (G := ↥(lowerCentralTerm H i))
      (p := 2) (n := 1) x)

/-- Commutators of two elements in the current lower-central term belong to
the next term, hence to the layer kernel. -/
theorem commutatorElement_mem_lowerCentralLayerKernel
    (H : Type uH) [Group H] (i : ℕ)
    (x y : ↥(lowerCentralTerm H i)) :
    ⁅x, y⁆ ∈ lowerCentralLayerKernel H i := by
  change ⁅x, y⁆ ∈
    Agemo (↥(lowerCentralTerm H i)) 2 1 ⊔
      (lowerCentralTerm H (i + 1)).subgroupOf (lowerCentralTerm H i)
  apply (show (lowerCentralTerm H (i + 1)).subgroupOf
      (lowerCentralTerm H i) ≤ _ from le_sup_right)
  change ⁅(x : H), (y : H)⁆ ∈ lowerCentralTerm H (i + 1)
  have hxy : ⁅(x : H), (y : H)⁆ ∈
      ⁅lowerCentralTerm H i, lowerCentralTerm H i⁆ :=
    Subgroup.commutator_mem_commutator x.2 y.2
  apply (show ⁅lowerCentralTerm H i, lowerCentralTerm H i⁆ ≤
      lowerCentralTerm H (i + 1) by
    dsimp [lowerCentralTerm]
    exact Subgroup.commutator_mono le_rfl le_top)
  exact hxy

/-- Each lower-central layer is elementary abelian of exponent two. -/
theorem lowerCentralLayer_isElementaryAbelian
    (H : Type uH) [Group H] (i : ℕ) :
    IsElementaryAbelian 2 (lowerCentralLayer H i) := by
  refine ⟨?_, ?_⟩
  · intro a b
    obtain ⟨x, rfl⟩ :=
      QuotientGroup.mk'_surjective (lowerCentralLayerKernel H i) a
    obtain ⟨y, rfl⟩ :=
      QuotientGroup.mk'_surjective (lowerCentralLayerKernel H i) b
    apply commutatorElement_eq_one_iff_mul_comm.mp
    rw [← map_commutatorElement]
    exact (QuotientGroup.eq_one_iff _).mpr
      (commutatorElement_mem_lowerCentralLayerKernel H i x y)
  · intro a
    obtain ⟨x, rfl⟩ :=
      QuotientGroup.mk'_surjective (lowerCentralLayerKernel H i) a
    rw [← map_pow]
    exact (QuotientGroup.eq_one_iff _).mpr
      (sq_mem_lowerCentralLayerKernel H i x)

/-- The ambient automorphism action restricted to the `i`-th lower-central
term. -/
def lowerCentralTermAction
    {H : Type uH} {X : Type uX} [Group H] [Group X]
    (phi : X →* MulAut H) (i : ℕ) :
    X →* MulAut ↥(lowerCentralTerm H i) :=
  (IsAInvariant.lowerCentralSeries phi i).restrict

/-- The denominator `Hᵢ² Hᵢ₊₁` is invariant under every ambient
automorphism action restricted to `Hᵢ`.

This deliberately does not claim that `Hᵢ₊₁` is characteristic under every
abstract automorphism of `Hᵢ`; invariance under restrictions of ambient
automorphisms is exactly what Higman's induced action requires. -/
theorem lowerCentralLayerKernel_isInvariant
    {H : Type uH} {X : Type uX} [Group H] [Group X]
    (phi : X →* MulAut H) (i : ℕ) :
    IsAInvariant (lowerCentralTermAction phi i)
      (lowerCentralLayerKernel H i) := by
  apply IsAInvariant.sup
  · exact IsAInvariant.of_characteristic _
  · exact (IsAInvariant.lowerCentralSeries phi i).subgroupOf
      (IsAInvariant.lowerCentralSeries phi (i + 1))

/-- The action induced on Higman's layer `L_(i+1)`. -/
noncomputable def lowerCentralLayerAction
    {H : Type uH} {X : Type uX} [Group H] [Group X]
    (phi : X →* MulAut H) (i : ℕ) :
    X →* MulAut (lowerCentralLayer H i) :=
  (lowerCentralLayerKernel_isInvariant phi i).quotientMulAutHom

/-- The induced layer action agrees with the ambient action on
representatives. -/
@[simp]
theorem lowerCentralLayerAction_apply_mk
    {H : Type uH} {X : Type uX} [Group H] [Group X]
    (phi : X →* MulAut H) (i : ℕ) (g : X)
    (x : ↥(lowerCentralTerm H i)) :
    lowerCentralLayerAction phi i g
        (QuotientGroup.mk' (lowerCentralLayerKernel H i) x) =
      QuotientGroup.mk' (lowerCentralLayerKernel H i)
        (lowerCentralTermAction phi i g x) := rfl

/-! ## The canonical `F_2` representation -/

/-- Commutativity of a lower-central layer, packaged without changing its
canonical quotient-group operations. -/
abbrev lowerCentralLayerIsMulCommutative
    (H : Type uH) [Group H] (i : ℕ) :
    IsMulCommutative (lowerCentralLayer H i) :=
  IsMulCommutative.of_comm (lowerCentralLayer_isElementaryAbelian H i).comm

/-- The canonical `F_2`-module structure on an elementary lower-central
layer.  It is derived from the exponent-two theorem, not supplied as data. -/
noncomputable abbrev lowerCentralLayerZmodModule
    (H : Type uH) [Group H] (i : ℕ) :
    letI : IsMulCommutative (lowerCentralLayer H i) :=
      lowerCentralLayerIsMulCommutative H i
    Module (ZMod 2) (Additive (lowerCentralLayer H i)) :=
  (lowerCentralLayer_isElementaryAbelian H i).zmodModule

/-- Higman’s induced action on `L_(i+1)`, viewed as its canonical linear
representation over `F_2`. -/
noncomputable def lowerCentralLayerRepresentation
    {H : Type uH} {X : Type uX} [Group H] [Group X]
    (phi : X →* MulAut H) (i : ℕ) :
    letI : IsMulCommutative (lowerCentralLayer H i) :=
      lowerCentralLayerIsMulCommutative H i
    letI : Module (ZMod 2) (Additive (lowerCentralLayer H i)) :=
      lowerCentralLayerZmodModule H i
    Representation (ZMod 2) X (Additive (lowerCentralLayer H i)) := by
  letI : IsMulCommutative (lowerCentralLayer H i) :=
    lowerCentralLayerIsMulCommutative H i
  letI : Module (ZMod 2) (Additive (lowerCentralLayer H i)) :=
    lowerCentralLayerZmodModule H i
  letI : MulDistribMulAction X (lowerCentralLayer H i) :=
    MulDistribMulAction.compHom _ (lowerCentralLayerAction phi i)
  exact Representation.ofDistribMulAction
    (ZMod 2) X (Additive (lowerCentralLayer H i))

/-- The layer representation is exactly the induced quotient action on
underlying group elements. -/
theorem lowerCentralLayerRepresentation_apply
    {H : Type uH} {X : Type uX} [Group H] [Group X]
    (phi : X →* MulAut H) (i : ℕ) (g : X)
    (q : lowerCentralLayer H i) :
    letI : IsMulCommutative (lowerCentralLayer H i) :=
      lowerCentralLayerIsMulCommutative H i
    letI : Module (ZMod 2) (Additive (lowerCentralLayer H i)) :=
      lowerCentralLayerZmodModule H i
    lowerCentralLayerRepresentation phi i g (Additive.ofMul q) =
      Additive.ofMul (lowerCentralLayerAction phi i g q) := by
  letI : IsMulCommutative (lowerCentralLayer H i) :=
    lowerCentralLayerIsMulCommutative H i
  letI : Module (ZMod 2) (Additive (lowerCentralLayer H i)) :=
    lowerCentralLayerZmodModule H i
  rfl

/-- The cardinality of a finite lower-central layer is `2` to its canonical
`F_2`-dimension.  This is the source of Higman’s notation `|L_i| = 2^n`. -/
theorem lowerCentralLayer_card_eq_pow_finrank
    (H : Type uH) [Group H] [Finite H] (i : ℕ) :
    letI : IsMulCommutative (lowerCentralLayer H i) :=
      lowerCentralLayerIsMulCommutative H i
    letI : Module (ZMod 2) (Additive (lowerCentralLayer H i)) :=
      lowerCentralLayerZmodModule H i
    Nat.card (lowerCentralLayer H i) =
      2 ^ Module.finrank (ZMod 2) (Additive (lowerCentralLayer H i)) := by
  letI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  exact (lowerCentralLayer_isElementaryAbelian H i).card_eq_pow_finrank

end OddOrder.Peterfalvi.Appendices.Suzuki2Groups
