/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Peterfalvi.Appendices.Suzuki2Groups.HigmanIdempotentCovariance
import OddOrder.Peterfalvi.Appendices.Suzuki2Groups.HigmanNormalAbelian

/-!
# Higman Lemma 3: the kernel of the quotient endomorphism family

G. Higman, *Suzuki 2-groups*, Illinois J. Math. 7 (1963), Lemmas 2--3,
pp. 83--84.

For the chosen endomorphisms `nu(u)` satisfying
`conj(u^-1) = 1 - 2 * nu(u)`, this file identifies the kernel of the induced
homomorphism on `A / A^2` with `A` itself.  The forward inclusion uses
Higman's Lemma 2: a zero quotient endomorphism gives `[<u>, A] <= A^4`, while
`Phi(C) = Phi(A)` gives `u^2 in A^2`; hence `u` belongs to `A`.  The reverse
inclusion is the direct calculation that conjugation by an element of the
abelian subgroup `A` is trivial.

No order calculation for `C / A` and no exponent bound for `A` are claimed
here.
-/

set_option autoImplicit false

namespace OddOrder.Peterfalvi.Appendices.Suzuki2Groups

open OddOrder.GroupTheory
open OddOrder.Isaacs.Ch03
open scoped commutatorElement

/-- If an element of the ambient subgroup `C` already belongs to the abelian
normal subgroup `A`, its chosen Higman endomorphism vanishes on `A / A^2`. -/
theorem HigmanEndomorphismFamily.modTwo_eq_zero_of_coe_mem
    {P ι : Type*} [Group P]
    {A C : Subgroup P} [A.Normal]
    [Finite ι] {e : ℕ}
    (hAcomm : IsMulCommutative A)
    (ε : A ≃* (ι → Multiplicative (ZMod (2 ^ e))))
    (he : 3 ≤ e) :
    letI : CommGroup A :=
      { (inferInstance : Group A) with
        mul_comm := hAcomm.is_comm.comm }
    ∀ (F : HigmanEndomorphismFamily
        (fun u : C ↦ MulAut.conjNormal (H := A) (u : P)⁻¹))
      (u : C), (u : P) ∈ A → F.modTwo u = 0 := by
  letI : CommGroup A :=
    { (inferInstance : Group A) with
      mul_comm := hAcomm.is_comm.comm }
  intro F u hu
  have hconj :
      MulAut.conjNormal (H := A) (u : P)⁻¹ = 1 := by
    ext a
    rw [MulAut.conjNormal_apply, MulAut.one_apply]
    have hcomm : (u : P) * (a : P) = (a : P) * (u : P) :=
      congrArg A.subtype
        (mul_comm (⟨(u : P), hu⟩ : A) a)
    rw [inv_inv, mul_assoc, ← hcomm]
    simp
  have hadd :
      (MulAut.conjNormal (H := A) (u : P)⁻¹).toMonoidHom.toAdditive =
        (1 : AddMonoid.End (Additive A)) := by
    rw [hconj]
    rfl
  have hrel := F.conj_eq_one_sub_two u
  rw [hadd] at hrel
  have htwo : 2 • F.ν u = 0 := by
    calc
      2 • F.ν u =
          (1 : AddMonoid.End (Additive A)) - (1 - 2 • F.ν u) := by
        abel
      _ = (1 : AddMonoid.End (Additive A)) - 1 :=
        (congrArg
          (fun k : AddMonoid.End (Additive A) ↦
            (1 : AddMonoid.End (Additive A)) - k) hrel).symm
      _ = 0 := sub_self _
  exact actualModTwoEnd_eq_zero_of_two_nsmul_eq_zero ε he (F.ν u) htwo

/-- The zero set of the additive quotient family contains the cyclic subgroup
generated by each one of its elements. -/
theorem HigmanEndomorphismFamily.modTwo_eq_zero_of_mem_zpowers
    {A C ι : Type*} [CommGroup A] [Group C] [Finite ι]
    {conjInv : C → MulAut A} {e : ℕ}
    (F : HigmanEndomorphismFamily conjInv)
    (ε : A ≃* (ι → Multiplicative (ZMod (2 ^ e))))
    (he : 3 ≤ e)
    (hconjMul : ∀ u v : C, conjInv (u * v) = conjInv v * conjInv u)
    {u v : C} (hu : F.modTwo u = 0)
    (hv : v ∈ Subgroup.zpowers u) :
    F.modTwo v = 0 := by
  obtain ⟨n, rfl⟩ := Subgroup.mem_zpowers_iff.mp hv
  let Φ := F.modTwoHom ε he hconjMul
  have hΦu : Φ u = 1 := by
    apply Multiplicative.toAdd.injective
    change F.modTwo u = 0
    exact hu
  have hΦpow : Φ (u ^ n) = 1 := by
    rw [map_zpow, hΦu, one_zpow]
  have h := congrArg Multiplicative.toAdd hΦpow
  change F.modTwo (u ^ n) = 0 at h
  exact h

/-- If the actual quotient endomorphism at `u` is zero, the commutator of
`u^-1` with each element of `A` belongs to `A^4`. -/
theorem actualHigmanFamily_commutator_inv_mem_agemo_two_of_modTwo_eq_zero
    {P : Type*} [Group P] {A C : Subgroup P} [A.Normal]
    (hAcomm : IsMulCommutative A) (u : C) :
    letI : CommGroup A :=
      { (inferInstance : Group A) with
        mul_comm := hAcomm.is_comm.comm }
    ∀ F : HigmanEndomorphismFamily
        (fun v : C ↦ MulAut.conjNormal (H := A) (v : P)⁻¹),
      F.modTwo u = 0 →
        ∀ a : A, ⁅(u : P)⁻¹, (a : P)⁆ ∈
          (Agemo A 2 2).map A.subtype := by
  letI : CommGroup A :=
    { (inferInstance : Group A) with
      mul_comm := hAcomm.is_comm.comm }
  intro F hzero a
  let νm : A →* A := addEndToMonoidEnd (F.ν u)
  have hνq := DFunLike.congr_fun hzero
    (Additive.ofMul (QuotientGroup.mk a))
  have hνmem : νm a ∈ Agemo A 2 1 := by
    rw [← QuotientGroup.eq_one_iff]
    have hνq' := congrArg Additive.toMul hνq
    simpa [νm, HigmanEndomorphismFamily.modTwo] using hνq'
  have hνsqA : (νm a) ^ 2 ∈ Agemo A 2 2 :=
    mem_agemo_succ_iff.mpr ⟨νm a, hνmem, rfl⟩
  have hνsqP : ((νm a : A) : P) ^ 2 ∈
      (Agemo A 2 2).map A.subtype := by
    simpa using Subgroup.mem_map_of_mem A.subtype hνsqA
  have hpoint := DFunLike.congr_fun (F.conj_eq_one_sub_two u)
    (Additive.ofMul a)
  have hconj :
      ((MulAut.conjNormal (H := A) (u : P)⁻¹) a : A) =
        a * (νm a) ^ (-2 : ℤ) := by
    have hpoint' := congrArg Additive.toMul hpoint
    change ((MulAut.conjNormal (H := A) (u : P)⁻¹) a : A) =
      Additive.toMul
        (Additive.ofMul a - 2 • F.ν u (Additive.ofMul a)) at hpoint'
    calc
      _ = Additive.toMul
          (Additive.ofMul a - 2 • F.ν u (Additive.ofMul a)) := hpoint'
      _ = a * (νm a) ^ (-2 : ℤ) := by
        have hz : (νm a) ^ (-2 : ℤ) = ((νm a) ^ 2)⁻¹ := by
          simp only [zpow_neg, zpow_ofNat]
        rw [hz]
        simp only [νm, addEndToMonoidEnd_apply, sub_eq_add_neg, two_nsmul,
          pow_two, toMul_add, toMul_neg, toMul_ofMul]
  have heq : ⁅(u : P)⁻¹, (a : P)⁆ = ((νm a : A) : P) ^ (-2 : ℤ) := by
    have hθ : (((MulAut.conjNormal (H := A) (u : P)⁻¹) a : A) : P) =
        (u : P)⁻¹ * (a : P) * (u : P) := by
      dsimp
      simp
    have hconjP := congrArg A.subtype hconj
    change (((MulAut.conjNormal (H := A) (u : P)⁻¹) a : A) : P) =
      (((a * (νm a) ^ (-2 : ℤ)) : A) : P) at hconjP
    have hcancelA : (a * (νm a) ^ (-2 : ℤ)) * a⁻¹ =
        (νm a) ^ (-2 : ℤ) := by
      rw [mul_comm a]
      group
    have hcancelP := congrArg A.subtype hcancelA
    change ((((a * (νm a) ^ (-2 : ℤ)) * a⁻¹) : A) : P) =
      (((νm a) ^ (-2 : ℤ) : A) : P) at hcancelP
    rw [commutatorElement_def, inv_inv, ← hθ]
    calc
      _ = (((a * (νm a) ^ (-2 : ℤ) : A) : P) * (a : P)⁻¹) := by
        rw [hconjP]
      _ = _ := hcancelP
  rw [heq]
  have hz : ((νm a : A) : P) ^ (-2 : ℤ) =
      (((νm a : A) : P) ^ 2)⁻¹ := by
    simp only [zpow_neg, zpow_ofNat]
  rw [hz]
  exact (Agemo A 2 2).map A.subtype |>.inv_mem hνsqP

/-- If the actual quotient value at `u` is zero, all commutators between
`A` and the cyclic subgroup generated by `u` lie in `A^4`. -/
theorem actualHigmanFamily_commutator_zpowers_le_agemo_two_of_modTwo_eq_zero
    {P ι : Type*} [Group P] [Finite ι]
    {A C : Subgroup P} [A.Normal]
    (hAcomm : IsMulCommutative A) {e : ℕ}
    (ε : letI : CommGroup A :=
      { (inferInstance : Group A) with
        mul_comm := hAcomm.is_comm.comm }
      A ≃* (ι → Multiplicative (ZMod (2 ^ e))))
    (he : 3 ≤ e) (u : C) :
    letI : CommGroup A :=
      { (inferInstance : Group A) with
        mul_comm := hAcomm.is_comm.comm }
    ∀ F : HigmanEndomorphismFamily
        (fun v : C ↦ MulAut.conjNormal (H := A) (v : P)⁻¹),
      F.modTwo u = 0 →
        ⁅Subgroup.zpowers (u : P), A⁆ ≤
          (Agemo A 2 2).map A.subtype := by
  letI : CommGroup A :=
    { (inferInstance : Group A) with
      mul_comm := hAcomm.is_comm.comm }
  intro F hzero
  rw [Subgroup.commutator_le]
  intro x hx a ha
  have hxC : x ∈ C :=
    (Subgroup.zpowers_le.mpr u.2) hx
  let xC : C := ⟨x, hxC⟩
  have hxCzp : xC ∈ Subgroup.zpowers u := by
    obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp hx
    apply Subgroup.mem_zpowers_iff.mpr
    refine ⟨n, Subtype.ext ?_⟩
    exact hn
  have hxCinvzp : xC⁻¹ ∈ Subgroup.zpowers u :=
    (Subgroup.zpowers u).inv_mem hxCzp
  have hzeroInv : F.modTwo xC⁻¹ = 0 :=
    F.modTwo_eq_zero_of_mem_zpowers ε he subgroupConjInv_mul
      hzero hxCinvzp
  have hpoint :=
    actualHigmanFamily_commutator_inv_mem_agemo_two_of_modTwo_eq_zero
      hAcomm xC⁻¹ F hzeroInv ⟨a, ha⟩
  simpa only [xC, Subgroup.coe_inv, inv_inv, Subtype.coe_mk] using hpoint

/-- **Higman, Suzuki 2-groups, Lemmas 2--3** (pp. 83--84), kernel
inclusion.  If the chosen quotient endomorphism at `u` vanishes, then `u`
belongs to `A`. -/
theorem actualHigmanFamily_mem_of_modTwo_eq_zero
    {P ι : Type*} [Group P] [Finite P] [Finite ι]
    (hP : IsPGroup 2 P)
    (X : Subgroup (MulAut P))
    (htrans : ∀ x ∈ involutions P, ∀ y ∈ involutions P,
      ∃ g : X, (g : MulAut P) x = y)
    {A C : Subgroup P} [A.Normal]
    (hAC : A ≤ C) (hAcomm : IsMulCommutative A)
    (hAinv : IsAInvariant X.subtype A) (hAne : A ≠ ⊥)
    (hΦ : (frattini C).map C.subtype = (frattini A).map A.subtype)
    {e : ℕ}
    (ε : letI : CommGroup A :=
      { (inferInstance : Group A) with
        mul_comm := hAcomm.is_comm.comm }
      A ≃* (ι → Multiplicative (ZMod (2 ^ e))))
    (he : 3 ≤ e) (u : C) :
    letI : CommGroup A :=
      { (inferInstance : Group A) with
        mul_comm := hAcomm.is_comm.comm }
    ∀ F : HigmanEndomorphismFamily
        (fun v : C ↦ MulAut.conjNormal (H := A) (v : P)⁻¹),
      F.modTwo u = 0 → (u : P) ∈ A := by
  letI : CommGroup A :=
    { (inferInstance : Group A) with
      mul_comm := hAcomm.is_comm.comm }
  intro F hzero
  by_contra huA
  apply no_sq_mem_agemo_one_and_commutator_le_agemo_two
    hP X htrans A hAcomm hAinv hAne huA
  refine ⟨square_mem_agemo_one_of_frattini_map_eq
    hP hAC hAcomm hΦ u.2, ?_⟩
  exact
    actualHigmanFamily_commutator_zpowers_le_agemo_two_of_modTwo_eq_zero
      hAcomm ε he u F hzero

/-- **Higman, Suzuki 2-groups, Lemma 3** (p. 84): exact pointwise kernel
criterion for the induced quotient endomorphism family. -/
theorem actualHigmanFamily_modTwo_eq_zero_iff_mem
    {P ι : Type*} [Group P] [Finite P] [Finite ι]
    (hP : IsPGroup 2 P)
    (X : Subgroup (MulAut P))
    (htrans : ∀ x ∈ involutions P, ∀ y ∈ involutions P,
      ∃ g : X, (g : MulAut P) x = y)
    {A C : Subgroup P} [A.Normal]
    (hAC : A ≤ C) (hAcomm : IsMulCommutative A)
    (hAinv : IsAInvariant X.subtype A) (hAne : A ≠ ⊥)
    (hΦ : (frattini C).map C.subtype = (frattini A).map A.subtype)
    {e : ℕ}
    (ε : letI : CommGroup A :=
      { (inferInstance : Group A) with
        mul_comm := hAcomm.is_comm.comm }
      A ≃* (ι → Multiplicative (ZMod (2 ^ e))))
    (he : 3 ≤ e) (u : C) :
    letI : CommGroup A :=
      { (inferInstance : Group A) with
        mul_comm := hAcomm.is_comm.comm }
    ∀ F : HigmanEndomorphismFamily
        (fun v : C ↦ MulAut.conjNormal (H := A) (v : P)⁻¹),
      F.modTwo u = 0 ↔ (u : P) ∈ A := by
  letI : CommGroup A :=
    { (inferInstance : Group A) with
      mul_comm := hAcomm.is_comm.comm }
  intro F
  constructor
  · exact actualHigmanFamily_mem_of_modTwo_eq_zero
      hP X htrans hAC hAcomm hAinv hAne hΦ ε he u F
  · exact HigmanEndomorphismFamily.modTwo_eq_zero_of_coe_mem
      hAcomm ε he F u

/-- **Higman, Suzuki 2-groups, Lemma 3** (p. 84): the kernel of the
multiplicative form of the chosen quotient endomorphism family is precisely
the copy of `A` inside `C`. -/
theorem actualHigmanFamily_modTwoHom_ker_eq
    {P ι : Type*} [Group P] [Finite P] [Finite ι]
    (hP : IsPGroup 2 P)
    (X : Subgroup (MulAut P))
    (htrans : ∀ x ∈ involutions P, ∀ y ∈ involutions P,
      ∃ g : X, (g : MulAut P) x = y)
    {A C : Subgroup P} [A.Normal]
    (hAC : A ≤ C) (hAcomm : IsMulCommutative A)
    (hAinv : IsAInvariant X.subtype A) (hAne : A ≠ ⊥)
    (hΦ : (frattini C).map C.subtype = (frattini A).map A.subtype)
    {e : ℕ}
    (ε : letI : CommGroup A :=
      { (inferInstance : Group A) with
        mul_comm := hAcomm.is_comm.comm }
      A ≃* (ι → Multiplicative (ZMod (2 ^ e))))
    (he : 3 ≤ e) :
    letI : CommGroup A :=
      { (inferInstance : Group A) with
        mul_comm := hAcomm.is_comm.comm }
    ∀ F : HigmanEndomorphismFamily
        (fun v : C ↦ MulAut.conjNormal (H := A) (v : P)⁻¹),
      (F.modTwoHom ε he subgroupConjInv_mul).ker = A.subgroupOf C := by
  letI : CommGroup A :=
    { (inferInstance : Group A) with
      mul_comm := hAcomm.is_comm.comm }
  intro F
  ext u
  rw [MonoidHom.mem_ker, Subgroup.mem_subgroupOf]
  constructor
  · intro hu
    have hzero := congrArg Multiplicative.toAdd hu
    change F.modTwo u = 0 at hzero
    exact (actualHigmanFamily_modTwo_eq_zero_iff_mem
      hP X htrans hAC hAcomm hAinv hAne hΦ ε he u F).mp hzero
  · intro hu
    apply Multiplicative.toAdd.injective
    change F.modTwo u = 0
    exact (actualHigmanFamily_modTwo_eq_zero_iff_mem
      hP X htrans hAC hAcomm hAinv hAne hΦ ε he u F).mpr hu

end OddOrder.Peterfalvi.Appendices.Suzuki2Groups
