/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Isaacs.Ch04_Commutators.ForwardFromCh03
import OddOrder.Isaacs.Ch04_Commutators.Main.ThreeSubgroups
import OddOrder.Peterfalvi.Appendices.Huppert.TransitiveInvariant

/-!
# Peterfalvi Appendix III: invariant summands under a Frobenius action

T. Peterfalvi, *Character Theory for the Odd Order Theorem* (LMS LNS 272,
2000), Appendix III, Higman theorem, p. 141, as used in Part II, Ch. I §3,
Lemma 5, p. 107.

This file isolates the honest bridge from the fixed-point-free action of `K`
on a Suzuki `2`-group to the simplicity and complementarity of the invariant
summands in its central quotient.

* coprime fixed-point lifting makes the induced quotient action fixed-point-free;
* an action of order `|U| - 1` which is fixed-point-free is transitive on `U#`;
* Peterfalvi Appendix B, Proposition 1 then makes `U` simple as a `K`-group;
* two distinct invariant summands of the correct cardinalities are complementary.

No elementary-abelian hypothesis is needed for these implications; that
hypothesis belongs to Higman's construction of the summands themselves.
-/

set_option autoImplicit false

namespace OddOrder.Peterfalvi.Appendices.Suzuki2Groups

open OddOrder.Isaacs.Ch03
open OddOrder.Isaacs.Ch03.IsAInvariant (quotientMulAutHom)

universe uK uP uE

section QuotientFixedPoints

variable {K : Type uK} {P : Type uP}
  [Group K] [Finite K] [Group P] [Finite P]

/-- Fixed points in an invariant normal subgroup are exactly the obstruction
to a fixed-point-free action on the quotient.

More precisely, if every fixed point in `P` of a nonidentity element of `K`
lies in `Z`, and `(|K|, |Z|) = 1`, then the induced action on `P / Z` is
fixed-point-free.  The proof restricts to the cyclic subgroup generated by
the operator and uses Isaacs Corollary 3.28 to lift a fixed coset to a fixed
representative. -/
theorem quotient_fixedPointFree_of_fixedPoints_le
    (act : K →* MulAut P) (Z : Subgroup P) [Z.Normal]
    (hZinv : IsAInvariant act Z)
    (hcop : Nat.Coprime (Nat.card K) (Nat.card ↑Z))
    (hfixed : ∀ k : K, k ≠ 1 → ∀ x : P, act k x = x → x ∈ Z) :
    ∀ k : K, k ≠ 1 → ∀ q : (P ⧸ Z),
      quotientMulAutHom hZinv k q = q → q = 1 := by
  intro k hk q hq
  obtain ⟨g, rfl⟩ := QuotientGroup.mk'_surjective Z q
  let C : Subgroup K := Subgroup.zpowers k
  let psi : C →* MulAut P := act.comp C.subtype
  have hCcop : Nat.Coprime (Nat.card C) (Nat.card ↑Z) :=
    hcop.coprime_dvd_left (Subgroup.card_subgroup_dvd_card C)
  have hZpsi : IsAInvariant psi Z := fun c => hZinv c
  letI : MulAction K (P ⧸ Z) :=
    MulAction.compHom (P ⧸ Z) (quotientMulAutHom hZinv)
  have hkStabilizer : k ∈ MulAction.stabilizer K (QuotientGroup.mk' Z g) := by
    rw [MulAction.mem_stabilizer_iff]
    exact hq
  have hCStabilizer : C ≤ MulAction.stabilizer K (QuotientGroup.mk' Z g) := by
    rw [show C = Subgroup.zpowers k from rfl, Subgroup.zpowers_le]
    exact hkStabilizer
  have hcoset : ∀ c : C, ∃ z ∈ Z, psi c g = g * z := by
    intro c
    have hcfix : (c : K) • QuotientGroup.mk' Z g = QuotientGroup.mk' Z g := by
      rw [← MulAction.mem_stabilizer_iff]
      exact hCStabilizer c.2
    change quotientMulAutHom hZinv (c : K) (QuotientGroup.mk' Z g) =
      QuotientGroup.mk' Z g at hcfix
    rw [OddOrder.Isaacs.Ch03.IsAInvariant.quotientMulAutHom_apply_mk' hZinv,
      QuotientGroup.mk'_eq_mk'] at hcfix
    obtain ⟨z, hz, hzeq⟩ := hcfix
    exact ⟨z⁻¹, Z.inv_mem hz, by
      rw [MonoidHom.comp_apply, eq_mul_inv_iff_mul_eq]
      exact hzeq⟩
  haveI : IsSolvable C :=
    isSolvable_of_comm fun c d => mul_comm' c d
  obtain ⟨c, hcfix, z, hz, hc⟩ :=
    OddOrder.Isaacs.Ch04.coprime_fixedPoints_quotient_of_coprime_normal
      (φ := psi) hCcop (Or.inl (inferInstance : IsSolvable C)) hZpsi hcoset
  let kC : C := ⟨k, Subgroup.mem_zpowers k⟩
  have hck : act k c = c := by
    simpa only [psi, kC, MonoidHom.comp_apply, Subgroup.coe_subtype] using hcfix kC
  have hcZ : c ∈ Z := hfixed k hk c hck
  apply (QuotientGroup.eq_one_iff g).mpr
  have hg : g = c * z⁻¹ := by
    rw [hc]
    group
  rw [hg]
  exact Z.mul_mem hcZ (Z.inv_mem hz)

omit [Group K] [Finite K] in
/-- Consecutive finite cardinalities are coprime.  This is the arithmetic
form used when Higman's complement has `|K| = |Z| - 1`. -/
theorem card_coprime_of_card_eq_sub_one
    (Z : Subgroup P) (hKcard : Nat.card K = Nat.card ↑Z - 1) :
    Nat.Coprime (Nat.card K) (Nat.card ↑Z) := by
  rw [hKcard]
  exact (Nat.coprime_self_sub_left
    (show 1 ≤ Nat.card ↑Z from Nat.card_pos)).mpr (Nat.coprime_one_left _)

end QuotientFixedPoints

section TransitiveSummands

variable {K : Type uK} {E : Type uE}
  [Group K] [Group E] [Finite E]

/-- A fixed-point-free action whose operator group has order `|U| - 1` is
transitive on the nonidentity elements of an invariant subgroup `U`.

The orbit map from `K` to `U#` is injective by fixed-point-freeness, and the
cardinality hypothesis makes it bijective. -/
theorem restrict_transitive_of_fixedPointFree_card
    (rho : K →* MulAut E)
    (hfree : ∀ k : K, k ≠ 1 → ∀ x : E, rho k x = x → x = 1)
    {U : Subgroup E} (hUinv : IsAInvariant rho U)
    (hcard : Nat.card K = Nat.card ↑U - 1) :
    ∀ a b : U, a ≠ 1 → b ≠ 1 →
      ∃ k : K, hUinv.restrict k a = b := by
  classical
  letI : Fintype U := Fintype.ofFinite U
  intro a b ha hb
  let orbitMap : K → {u : U // u ≠ 1} := fun k =>
    ⟨hUinv.restrict k a, by
      intro hka
      apply ha
      apply (hUinv.restrict k).injective
      simpa using hka⟩
  have horbitMap_injective : Function.Injective orbitMap := by
    intro k l hkl
    have hval : rho k (a : E) = rho l (a : E) := by
      exact congrArg (fun u : {u : U // u ≠ 1} => ((u : U) : E)) hkl
    have hfix : rho (l⁻¹ * k) (a : E) = (a : E) := by
      rw [map_mul, map_inv]
      change (rho l)⁻¹ (rho k (a : E)) = (a : E)
      rw [hval, MulAut.inv_apply_self]
    have hlk : l⁻¹ * k = 1 := by
      by_contra hne
      have haone : (a : E) = 1 := hfree (l⁻¹ * k) hne (a : E) hfix
      exact ha (Subtype.ext haone)
    exact (inv_mul_eq_one.mp hlk).symm
  have htargetCard : Nat.card {u : U // u ≠ 1} = Nat.card ↑U - 1 := by
    rw [Nat.card_eq_fintype_card, Nat.card_eq_fintype_card,
      Fintype.card_subtype_compl, Fintype.card_subtype_eq]
  have horbitMap_bijective : Function.Bijective orbitMap :=
    (Nat.bijective_iff_injective_and_card orbitMap).mpr
      ⟨horbitMap_injective, hcard.trans htargetCard.symm⟩
  obtain ⟨k, hk⟩ := horbitMap_bijective.surjective ⟨b, hb⟩
  exact ⟨k, congrArg Subtype.val hk⟩

/-- Under the same hypotheses, every subgroup of `U` invariant under the
restricted action is either trivial or all of `U`. -/
theorem invariant_eq_bot_or_top_of_fixedPointFree_card
    (rho : K →* MulAut E)
    (hfree : ∀ k : K, k ≠ 1 → ∀ x : E, rho k x = x → x = 1)
    {U : Subgroup E} (hUinv : IsAInvariant rho U)
    (hcard : Nat.card K = Nat.card ↑U - 1)
    {V : Subgroup U} (hVinv : IsAInvariant hUinv.restrict V) :
    V = ⊥ ∨ V = ⊤ := by
  apply OddOrder.Peterfalvi.Appendices.Huppert.isAInvariant_eq_bot_or_top_of_transitive
    hUinv.restrict
  · exact restrict_transitive_of_fixedPointFree_card rho hfree hUinv hcard
  · exact hVinv

/-- Distinct invariant subgroups are complementary once transitivity on the
first subgroup, equality of their orders, and the ambient product formula are
known.

Transitivity makes the intersection either trivial or all of the first
subgroup.  The latter contradicts distinctness and equal cardinality; the
cardinality product then upgrades disjointness to complementarity. -/
theorem isCompl_of_distinct_invariant_of_transitive_card
    (rho : K →* MulAut E)
    {U V : Subgroup E} (hUinv : IsAInvariant rho U)
    (hVinv : IsAInvariant rho V)
    (htrans : ∀ a b : U, a ≠ 1 → b ≠ 1 →
      ∃ k : K, hUinv.restrict k a = b)
    (hne : U ≠ V) (hcard : Nat.card ↑U = Nat.card ↑V)
    (hmul : Nat.card ↑U * Nat.card ↑V = Nat.card E) :
    IsCompl U V := by
  have hVinU : IsAInvariant hUinv.restrict (V.subgroupOf U) :=
    hUinv.subgroupOf hVinv
  have hsimple : V.subgroupOf U = ⊥ ∨ V.subgroupOf U = ⊤ :=
    OddOrder.Peterfalvi.Appendices.Huppert.isAInvariant_eq_bot_or_top_of_transitive
      hUinv.restrict htrans hVinU
  have hdisjoint : Disjoint U V := by
    rcases hsimple with hbot | htop
    · exact (Subgroup.subgroupOf_eq_bot.mp hbot).symm
    · have hUV : U ≤ V := Subgroup.subgroupOf_eq_top.mp htop
      exact (hne (Subgroup.eq_of_le_of_card_ge hUV hcard.symm.le)).elim
  exact (Subgroup.isComplement'_of_card_mul_and_disjoint hmul hdisjoint).isCompl

end TransitiveSummands

end OddOrder.Peterfalvi.Appendices.Suzuki2Groups
