/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.GroupTheory.FixedPointFree
import Mathlib.GroupTheory.Nilpotent
import OddOrder.GroupTheory.GroupAction.PerfectQuasiprimitive
import OddOrder.GroupTheory.SpecificGroups.Suzuki.Bruhat

/-!
# Simplicity of the standard Suzuki group

This file proves the Suzuki-group target used in Peterfalvi, Part II, Chapter I,
Section 3, Lemma 1 (pp. 100--107).  For the nondegenerate parameters `0 < m`,
the concrete doubly transitive group generated by the root, torus, and Weyl
permutations is perfect, its point stabilizer is solvable, and hence it is simple.

Peterfalvi cites Huppert--Blackburn, Chapter XI, Theorem 3.6 for this fact.  The
proof here instead verifies the standard perfect/primitive/solvable-stabilizer
criterion directly from the explicit generator relations.
-/

set_option autoImplicit false

namespace OddOrder.GroupTheory.SpecificGroups.Suzuki

open scoped commutatorElement

variable {m : ℕ}

section /- §3 Lemma 1: perfectness and the solvable point stabilizer (pp. 100--107) -/

private theorem torusWeight_ne_one_of_ne_one (c : TorusParameter m) (hc : c ≠ 1) :
    torusWeight c ≠ 1 := by
  intro hw
  have hs : (c : Field m) ≠ 0 := Units.ne_zero c
  have htw := congrArg (titsTwist m) hw
  change (c : Field m) * titsTwist m (c : Field m) = 1 at hw
  simp only [torusWeight, map_mul, titsTwist_twice, map_one] at htw
  have hsq : (c : Field m) = (c : Field m) ^ 2 := by
    calc
      (c : Field m) = (c : Field m) * 1 := by rw [mul_one]
      _ = (c : Field m) *
          (titsTwist m (c : Field m) * (c : Field m) ^ 2) := by rw [htw]
      _ = ((c : Field m) * titsTwist m (c : Field m)) *
          (c : Field m) ^ 2 := by ring
      _ = (c : Field m) ^ 2 := by rw [hw, one_mul]
  apply hc
  apply Units.ext
  apply mul_left_cancel₀ hs
  simpa only [pow_two, Units.val_one, mul_one] using hsq.symm

/-- **Peterfalvi Part II, Ch. I, §3 Lemma 1 (Suzuki target).**
The torus weight is one exactly at the identity parameter. -/
@[simp] theorem torusWeight_eq_one_iff (c : TorusParameter m) :
    torusWeight c = 1 ↔ c = 1 := by
  constructor
  · intro h
    by_contra hc
    exact torusWeight_ne_one_of_ne_one c hc h
  · rintro rfl
    simp [torusWeight]

/-- **Peterfalvi Part II, Ch. I, §3 Lemma 1 (Suzuki target).**
Every nonidentity torus parameter acts fixed-point-freely on the root group. -/
theorem torusScale_fixedPointFree
    (c : TorusParameter m) (hc : c ≠ 1) :
    MonoidHom.FixedPointFree (torusScale c) := by
  intro u hu
  have hs : (c : Field m) ≠ 0 := Units.ne_zero c
  have hw : torusWeight c ≠ 0 := torusWeight_ne_zero c
  have hfst : u.fst = 0 := by
    by_contra hne
    apply hc
    apply Units.ext
    apply mul_left_cancel₀ hne
    simp only [Units.val_one, mul_one]
    exact ((div_eq_iff hs).mp (congrArg RootGroup.fst hu)).symm
  have hsnd : u.snd = 0 := by
    by_contra hne
    have hweight : torusWeight c = 1 := by
      apply mul_left_cancel₀ hne
      rw [mul_one]
      exact ((div_eq_iff hw).mp (congrArg RootGroup.snd hu)).symm
    exact hc ((torusWeight_eq_one_iff c).mp hweight)
  ext
  · simpa only [RootGroup.fst_one] using hfst
  · simpa only [RootGroup.snd_one] using hsnd

/-- **Peterfalvi Part II, Ch. I, §3 Lemma 1 (Suzuki target).**
For every nonidentity torus parameter, the root displacement map is surjective. -/
theorem torusScale_mul_inv_surjective
    (c : TorusParameter m) (hc : c ≠ 1) :
    Function.Surjective (fun v : RootGroup m ↦ torusScale c v * v⁻¹) := by
  intro u
  obtain ⟨v, hv⟩ :=
    (torusScale_fixedPointFree c hc).commutatorMap_surjective u⁻¹
  refine ⟨v, ?_⟩
  simpa only [MonoidHom.commutatorMap_apply, div_eq_mul_inv, mul_inv_rev,
    inv_inv] using congrArg Inv.inv hv

private theorem exists_torusParameter_ne_one (hm : 0 < m) :
    ∃ c : TorusParameter m, c ≠ 1 := by
  have hcard : 1 < Nat.card (TorusParameter m) := by
    rw [Nat.card_units, natCard_field]
    have hpow : 2 ^ 3 ≤ 2 ^ (2 * m + 1) :=
      Nat.pow_le_pow_right (by omega) (by omega)
    norm_num at hpow ⊢
    omega
  letI : Nontrivial (TorusParameter m) :=
    Finite.one_lt_card_iff_nontrivial.mp hcard
  exact exists_ne 1

/-- **Peterfalvi Part II, Ch. I, §3 Lemma 1 (Suzuki target).**
The torus--root commutator is the corresponding root displacement. -/
theorem commutator_torusHom_rootHom
    (c : TorusParameter m) (u : RootGroup m) :
    ⁅torusHom m c, rootHom m u⁆ =
      rootHom m (torusScale c u * u⁻¹) := by
  rw [commutatorElement_def, torusHom_mul_rootHom_mul_inv,
    ← map_inv, ← map_mul]

/-- **Peterfalvi Part II, Ch. I, §3 Lemma 1 (Suzuki target).**
The Weyl--torus commutator realizes the inverse-square torus parameter. -/
theorem commutator_weylElement_torusHom (c : TorusParameter m) :
    ⁅weylElement m, torusHom m c⁆ =
      torusHom m (c⁻¹ * c⁻¹) := by
  have hwinv : (weylElement m)⁻¹ = weylElement m := by
    apply inv_eq_iff_mul_eq_one.mpr
    simpa only [pow_two] using weylElement_sq_eq_one m
  rw [commutatorElement_def, hwinv,
    weylElement_mul_torusHom_mul_weylElement, ← map_inv, ← map_mul]

/-- **Peterfalvi Part II, Ch. I, §3 Lemma 1 (Suzuki target).**
Every standard torus generator belongs to the derived subgroup. -/
theorem torusHom_mem_commutator (c : TorusParameter m) :
    torusHom m c ∈ commutator (standardPermGroup m) := by
  obtain ⟨d, hd⟩ := isSquare_of_charTwo' ((c⁻¹ : TorusParameter m) : Field m)
  have hd0 : d ≠ 0 := by
    intro hd0
    have hc0 : ((c⁻¹ : TorusParameter m) : Field m) ≠ 0 := Units.ne_zero c⁻¹
    apply hc0
    rw [hd, hd0, zero_mul]
  let e : TorusParameter m := Units.mk0 d hd0
  have he : e * e = c⁻¹ := by
    apply Units.ext
    exact hd.symm
  have heinv : e⁻¹ * e⁻¹ = c := by
    calc
      e⁻¹ * e⁻¹ = (e * e)⁻¹ := (mul_inv_rev e e).symm
      _ = (c⁻¹)⁻¹ := congrArg Inv.inv he
      _ = c := inv_inv c
  rw [← heinv, ← commutator_weylElement_torusHom]
  exact Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _)

/-- **Peterfalvi Part II, Ch. I, §3 Lemma 1 (Suzuki target).**
For `0 < m`, every standard root generator belongs to the derived subgroup. -/
theorem rootHom_mem_commutator (hm : 0 < m) (u : RootGroup m) :
    rootHom m u ∈ commutator (standardPermGroup m) := by
  obtain ⟨c, hc⟩ := exists_torusParameter_ne_one hm
  obtain ⟨v, hv⟩ := torusScale_mul_inv_surjective c hc u
  rw [← hv, ← commutator_torusHom_rootHom]
  exact Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _)

/-- **Peterfalvi Part II, Ch. I, §3 Lemma 1 (Suzuki target).**
For `0 < m`, the standard Weyl involution belongs to the derived subgroup. -/
theorem weylElement_mem_commutator (hm : 0 < m) :
    weylElement m ∈ commutator (standardPermGroup m) := by
  let u : RootGroup m := RootGroup.mk 1 0
  have hu : u ≠ 1 := by
    intro h
    have hfst := congrArg RootGroup.fst h
    exact one_ne_zero (by simpa only [u, RootGroup.fst_one] using hfst)
  have hwinv : (weylElement m)⁻¹ = weylElement m := by
    apply inv_eq_iff_mul_eq_one.mpr
    simpa only [pow_two] using weylElement_sq_eq_one m
  let C := commutator (standardPermGroup m)
  have hroot (v : RootGroup m) : rootHom m v ∈ C :=
    rootHom_mem_commutator hm v
  have htorus (c : TorusParameter m) : torusHom m c ∈ C :=
    torusHom_mem_commutator c
  have hleft : weylElement m * rootHom m u * weylElement m ∈ C := by
    rw [← hwinv]
    exact (inferInstance : C.Normal).conj_mem (rootHom m u) (hroot u) (weylElement m)
  have hright :
      rootHom m (Ovoid.weylAffine u) *
          torusHom m (bruhatTorus u hu) * weylElement m *
            rootHom m (bruhatRightRoot u) ∈ C := by
    rw [← weylElement_mul_rootHom_mul_weylElement u hu]
    exact hleft
  have hprefix :
      rootHom m (Ovoid.weylAffine u) * torusHom m (bruhatTorus u hu) ∈ C :=
    C.mul_mem (hroot _) (htorus _)
  have hisolate := C.mul_mem
    (C.mul_mem (C.inv_mem hprefix) hright)
    (C.inv_mem (hroot (bruhatRightRoot u)))
  convert hisolate using 1; group

/-- **Peterfalvi Part II, Ch. I, §3 Lemma 1 (Suzuki target).**
The standard root group is solvable because it is a finite `2`-group. -/
private theorem rootGroup_isSolvable (m : ℕ) : IsSolvable (RootGroup m) := by
  letI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  letI : Group.IsNilpotent (RootGroup m) :=
    IsPGroup.isNilpotent (p := 2) (RootGroup.isPGroup m)
  infer_instance

/-- **Peterfalvi Part II, Ch. I, §3 Lemma 1 (Suzuki target).**
The root--torus semidirect-product model is solvable. -/
private theorem borelModel_isSolvable (m : ℕ) : IsSolvable (BorelModel m) := by
  letI : IsSolvable (RootGroup m) := rootGroup_isSolvable m
  exact solvable_of_ker_le_range
    (SemidirectProduct.inl : RootGroup m →* BorelModel m)
    (SemidirectProduct.rightHom : BorelModel m →* TorusParameter m)
    (by rw [← SemidirectProduct.range_inl_eq_ker_rightHom])

/-- **Peterfalvi Part II, Ch. I, §3 Lemma 1 (Suzuki target).**
The standard Borel subgroup is solvable. -/
theorem standardBorel_isSolvable (m : ℕ) : IsSolvable (standardBorel m) := by
  letI : IsSolvable (BorelModel m) := borelModel_isSolvable m
  change IsSolvable (borelHom m).range
  exact solvable_of_surjective (borelHom m).rangeRestrict_surjective

/-- **Peterfalvi Part II, Ch. I, §3 Lemma 1 (Suzuki target).**
For `0 < m`, the standard Suzuki permutation group is perfect. -/
theorem commutator_standardPermGroup_eq_top (hm : 0 < m) :
    commutator (standardPermGroup m) = ⊤ := by
  let C := commutator (standardPermGroup m)
  let H : Subgroup (Equiv.Perm (Ovoid m)) :=
    C.map (standardPermGroup m).subtype
  have hle : standardPermGroup m ≤ H := by
    apply standardPermGroup_le
    · intro u
      change ((rootHom m u : standardPermGroup m) : Equiv.Perm (Ovoid m)) ∈ H
      exact Subgroup.mem_map_of_mem (standardPermGroup m).subtype
        (rootHom_mem_commutator hm u)
    · intro c
      change ((torusHom m c : standardPermGroup m) : Equiv.Perm (Ovoid m)) ∈ H
      exact Subgroup.mem_map_of_mem (standardPermGroup m).subtype
        (torusHom_mem_commutator c)
    · change ((weylElement m : standardPermGroup m) : Equiv.Perm (Ovoid m)) ∈ H
      exact Subgroup.mem_map_of_mem (standardPermGroup m).subtype
        (weylElement_mem_commutator hm)
  apply top_unique
  intro g _
  have hg : (g : Equiv.Perm (Ovoid m)) ∈ H := hle g.property
  rcases hg with ⟨x, hx, hxeq⟩
  have hxg : x = g := Subtype.ext hxeq
  exact hxg ▸ hx

end

section /- §3 Lemma 1: simplicity of the Suzuki target (pp. 100--107) -/

private lemma standardPermGroup_nontrivial (m : ℕ) :
    Nontrivial (standardPermGroup m) := by
  refine ⟨⟨weylElement m, 1, ?_⟩⟩
  intro h
  have hp := congrArg
    (fun g : standardPermGroup m ↦ g • Ovoid.infinity m) h
  rw [weylElement_smul_infinity, one_smul] at hp
  change (some (1 : RootGroup m) : Option (RootGroup m)) = none at hp
  exact Option.some_ne_none _ hp

/-- **Peterfalvi Part II, Ch. I, §3 Lemma 1 (Suzuki target).**
For every positive `m`, the concrete standard Suzuki permutation group is simple.
The hypothesis excludes the degenerate `m = 0` group of order `20`. -/
theorem standardPermGroup_isSimpleGroup (hm : 0 < m) :
    IsSimpleGroup (standardPermGroup m) := by
  letI : Nontrivial (standardPermGroup m) :=
    standardPermGroup_nontrivial m
  letI : MulAction.IsPreprimitive (standardPermGroup m) (Ovoid m) :=
    MulAction.isPreprimitive_of_is_two_pretransitive
      (standardPermGroup_isMultiplyPretransitive m)
  letI : Group.IsPerfect (standardPermGroup m) :=
    ⟨commutator_standardPermGroup_eq_top hm⟩
  letI : IsSolvable
      (MulAction.stabilizer (standardPermGroup m) (Ovoid.infinity m)) := by
    rw [← standardBorel_eq_infinityStabilizer]
    exact standardBorel_isSolvable m
  exact isSimpleGroup_of_isPerfect_of_isQuasiPreprimitive_of_isSolvable_stabilizer
      (Ovoid.infinity m)

end

end OddOrder.GroupTheory.SpecificGroups.Suzuki
