/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.GroupTheory.SpecificGroups.Suzuki.Ovoid
import Mathlib.GroupTheory.Perm.Option

/-!
# Standard root, torus, and Weyl permutations of the Suzuki ovoid

The standard Suzuki action is generated by root-group translations, diagonal
torus scalings, and a Weyl involution.  This file constructs those permutations
directly on the infinity-plus-affine ovoid carrier, proves the root and torus
homomorphism laws and conjugation relation, and derives Weyl involutivity from
the reciprocal Suzuki-norm identity.

This is shared infrastructure for the Suzuki target in **Peterfalvi, Part II,
Chapter I, Theorem A** (pp. 97-98).
-/

set_option autoImplicit false

namespace OddOrder.GroupTheory.SpecificGroups.Suzuki

variable {m : ℕ}

noncomputable local instance (m : ℕ) : DecidableEq (RootGroup m) :=
  Classical.decEq _

namespace Ovoid

/-- The permutation induced by one root-group element: it fixes infinity and
acts by left multiplication on affine coordinates. -/
noncomputable def rootPerm (u : RootGroup m) : Equiv.Perm (Ovoid m) :=
  Equiv.optionCongr (Equiv.mulLeft u)

@[simp] theorem rootPerm_infinity (u : RootGroup m) :
    rootPerm u (infinity m) = infinity m :=
  rfl

@[simp] theorem rootPerm_affine (u v : RootGroup m) :
    rootPerm u (affine v) = affine (u * v) :=
  rfl

/-- The root-group permutations form a group homomorphism. -/
noncomputable def rootPermHom (m : ℕ) : RootGroup m →* Equiv.Perm (Ovoid m) where
  toFun := rootPerm
  map_one' := by
    apply Equiv.ext
    intro p
    cases p with
    | none => rfl
    | some v =>
        change affine (1 * v) = affine v
        rw [one_mul]
  map_mul' u v := by
    apply Equiv.ext
    intro p
    cases p with
    | none => rfl
    | some w =>
        change affine ((u * v) * w) = affine (u * (v * w))
        rw [mul_assoc]

@[simp] theorem rootPermHom_apply_infinity (u : RootGroup m) :
    rootPermHom m u (infinity m) = infinity m :=
  rootPerm_infinity u

@[simp] theorem rootPermHom_apply_affine (u v : RootGroup m) :
    rootPermHom m u (affine v) = affine (u * v) :=
  rootPerm_affine u v

/-- The root-group permutation representation is faithful. -/
theorem rootPermHom_injective (m : ℕ) : Function.Injective (rootPermHom m) := by
  intro u v huv
  have hpoint := congrArg (fun σ : Equiv.Perm (Ovoid m) => σ (affine 1)) huv
  simpa only [rootPermHom_apply_affine, mul_one, affine_inj] using hpoint

/-- There is a unique root-group element carrying one affine point to another. -/
theorem existsUnique_rootPerm_affine (u v : RootGroup m) :
    ∃! g : RootGroup m, rootPermHom m g (affine u) = affine v := by
  refine ⟨v * u⁻¹, ?_, ?_⟩
  · change affine ((v * u⁻¹) * u) = affine v
    rw [mul_assoc, inv_mul_cancel, mul_one]
  · intro g hg
    have hgu : g * u = v := by
      exact affine_inj.mp (by simpa only [rootPermHom_apply_affine] using hg)
    calc
      g = (g * u) * u⁻¹ := by simp
      _ = v * u⁻¹ := by rw [hgu]



end Ovoid

/-- The parameter group of the standard Suzuki torus. -/
abbrev TorusParameter (m : ℕ) := (Field m)ˣ

/-- The second-coordinate weight `c * theta(c)` of a torus parameter. -/
noncomputable def torusWeight {m : ℕ} (c : TorusParameter m) : Field m :=
  (c : Field m) * titsTwist m (c : Field m)

theorem torusWeight_ne_zero {m : ℕ} (c : TorusParameter m) : torusWeight c ≠ 0 :=
  mul_ne_zero (Units.ne_zero c) ((map_ne_zero (titsTwist m)).2 (Units.ne_zero c))

@[simp] theorem torusWeight_one (m : ℕ) : torusWeight (1 : TorusParameter m) = 1 := by
  simp [torusWeight]

@[simp] theorem torusWeight_mul {m : ℕ} (c d : TorusParameter m) :
    torusWeight (c * d) = torusWeight c * torusWeight d := by
  simp only [torusWeight, Units.val_mul, map_mul]
  ring

/-- Root-group scaling induced by a torus parameter.  Its inverse multiplies
the two coordinates by `c` and `c * theta(c)`, respectively. -/
noncomputable def torusScale {m : ℕ} (c : TorusParameter m) : RootGroup m ≃* RootGroup m where
  toFun u := ⟨u.fst / (c : Field m), u.snd / torusWeight c⟩
  invFun u := ⟨u.fst * (c : Field m), u.snd * torusWeight c⟩
  left_inv u := by
    ext
    · exact div_mul_cancel₀ u.fst (Units.ne_zero c)
    · exact div_mul_cancel₀ u.snd (torusWeight_ne_zero c)
  right_inv u := by
    ext
    · exact mul_div_cancel_right₀ u.fst (Units.ne_zero c)
    · exact mul_div_cancel_right₀ u.snd (torusWeight_ne_zero c)
  map_mul' u v := by
    ext
    · simp only [RootGroup.fst_mul]
      exact add_div u.fst v.fst (c : Field m)
    · simp only [RootGroup.snd_mul]
      rw [map_div₀]
      change (u.snd + v.snd + v.fst * titsTwist m u.fst) /
          ((c : Field m) * titsTwist m (c : Field m)) =
        u.snd / ((c : Field m) * titsTwist m (c : Field m)) +
          v.snd / ((c : Field m) * titsTwist m (c : Field m)) +
          (v.fst / (c : Field m)) *
            (titsTwist m u.fst / titsTwist m (c : Field m))
      field_simp [Units.ne_zero c,
        (map_ne_zero (titsTwist m)).2 (Units.ne_zero c)]

@[simp] theorem torusScale_fst {m : ℕ} (c : TorusParameter m) (u : RootGroup m) :
    (torusScale c u).fst = u.fst / (c : Field m) :=
  rfl

@[simp] theorem torusScale_snd {m : ℕ} (c : TorusParameter m) (u : RootGroup m) :
    (torusScale c u).snd = u.snd / torusWeight c :=
  rfl

@[simp] theorem torusScale_symm_fst {m : ℕ} (c : TorusParameter m) (u : RootGroup m) :
    ((torusScale c).symm u).fst = u.fst * (c : Field m) :=
  rfl

@[simp] theorem torusScale_symm_snd {m : ℕ} (c : TorusParameter m) (u : RootGroup m) :
    ((torusScale c).symm u).snd = u.snd * torusWeight c :=
  rfl

/-- The root-group scalings form a multiplicative action of the torus
parameters. -/
noncomputable def torusScaleHom (m : ℕ) : TorusParameter m →* MulAut (RootGroup m) where
  toFun := torusScale
  map_one' := by
    ext u <;> simp
  map_mul' c d := by
    ext u
    · simp [div_eq_mul_inv]
      ring
    · simp only [MulAut.mul_apply, torusScale_snd, torusWeight_mul]
      field_simp [torusWeight_ne_zero c, torusWeight_ne_zero d]

@[simp] theorem torusScaleHom_apply {m : ℕ} (c : TorusParameter m) (u : RootGroup m) :
    torusScaleHom m c u = torusScale c u :=
  rfl


namespace Ovoid

/-- Extend a permutation by fixing the extra `none` point. -/
private def optionPermHom (α : Type*) : Equiv.Perm α →* Equiv.Perm (Option α) where
  toFun := Equiv.optionCongr
  map_one' := Equiv.optionCongr_one
  map_mul' e f := by
    ext p
    cases p <;> rfl

/-- The standard diagonal torus as a permutation representation on the ovoid
carrier.  It fixes infinity and divides affine coordinates by `c` and
`c * theta(c)`. -/
noncomputable def torusPerm (m : ℕ) : TorusParameter m →* Equiv.Perm (Ovoid m) :=
  (optionPermHom (RootGroup m)).comp
    ((MulAut.toPerm (RootGroup m)).comp (torusScaleHom m))

@[simp] theorem torusPerm_infinity {m : ℕ} (c : TorusParameter m) :
    torusPerm m c (infinity m) = infinity m :=
  rfl

@[simp] theorem torusPerm_affine {m : ℕ} (c : TorusParameter m) (u : RootGroup m) :
    torusPerm m c (affine u) = affine (torusScale c u) :=
  rfl

@[simp] theorem torusPerm_affineMk {m : ℕ} (c : TorusParameter m) (x y : Field m) :
    torusPerm m c (affineMk x y) =
      affineMk (x / (c : Field m)) (y / torusWeight c) :=
  rfl

/-- Distinct nonzero field parameters induce distinct torus permutations. -/
theorem torusPerm_injective (m : ℕ) : Function.Injective (torusPerm m) := by
  intro c d hcd
  have hp := congrArg (fun e : Equiv.Perm (Ovoid m) =>
    e (affineMk (1 : Field m) 0)) hcd
  rw [torusPerm_affineMk, torusPerm_affineMk] at hp
  have hroot :
      (RootGroup.mk (1 / (c : Field m)) (0 / torusWeight c)) =
        RootGroup.mk (1 / (d : Field m)) (0 / torusWeight d) :=
    Option.some_injective _ hp
  have hfst := congrArg RootGroup.fst hroot
  apply Units.ext
  apply inv_injective
  simpa only [one_div] using hfst

/-- Conjugating a root translation by a torus permutation scales the root
parameter by `(x,y) |-> (x/c, y/(c*theta(c)))`. -/
theorem torusPerm_mul_rootPerm_mul_inv {m : ℕ}
    (c : TorusParameter m) (u : RootGroup m) :
    torusPerm m c * rootPermHom m u * (torusPerm m c)⁻¹ =
      rootPermHom m (torusScale c u) := by
  apply Equiv.Perm.ext
  intro p
  cases p with
  | none => rfl
  | some v =>
      change affine (torusScale c (u * (torusScale c).symm v)) =
        affine (torusScale c u * v)
      rw [map_mul, MulEquiv.apply_symm_apply]

/-- The affine origin of the Suzuki ovoid. -/
noncomputable def origin (m : ℕ) : Ovoid m := affine (1 : RootGroup m)

@[simp] theorem origin_eq_affineMk_zero_zero (m : ℕ) :
    origin m = affineMk 0 0 := by
  rfl

/-- The reciprocal affine coordinates used by the Weyl permutation. -/
noncomputable def weylAffine (u : RootGroup m) : RootGroup m :=
  ⟨u.snd / u.suzukiNorm, u.fst / u.suzukiNorm⟩

@[simp] theorem weylAffine_fst (u : RootGroup m) :
    (weylAffine u).fst = u.snd / u.suzukiNorm :=
  rfl

@[simp] theorem weylAffine_snd (u : RootGroup m) :
    (weylAffine u).snd = u.fst / u.suzukiNorm :=
  rfl

/-- The reciprocal affine point has inverse Suzuki norm. -/
theorem weylAffine_suzukiNorm (u : RootGroup m) :
    (weylAffine u).suzukiNorm = u.suzukiNorm⁻¹ := by
  exact suzukiNorm_reciprocal m u.fst u.snd

/-- A non-origin affine coordinate pair has nonzero Suzuki norm. -/
theorem suzukiNorm_ne_zero_of_ne_one {u : RootGroup m} (hu : u ≠ 1) :
    u.suzukiNorm ≠ 0 := by
  intro hN
  exact hu ((RootGroup.suzukiNorm_eq_zero_iff_eq_one u).mp hN)

/-- Reciprocal affine coordinates preserve non-origins. -/
theorem weylAffine_ne_one {u : RootGroup m} (hu : u ≠ 1) : weylAffine u ≠ 1 := by
  intro hw
  have hzero : (weylAffine u).suzukiNorm = 0 :=
    (RootGroup.suzukiNorm_eq_zero_iff_eq_one (weylAffine u)).2 hw
  rw [weylAffine_suzukiNorm] at hzero
  exact inv_ne_zero (suzukiNorm_ne_zero_of_ne_one hu) hzero

/-- Applying reciprocal affine coordinates twice recovers every non-origin pair. -/
theorem weylAffine_weylAffine {u : RootGroup m} (hu : u ≠ 1) :
    weylAffine (weylAffine u) = u := by
  have hn : u.suzukiNorm ≠ 0 := suzukiNorm_ne_zero_of_ne_one hu
  ext
  · change (u.fst / u.suzukiNorm) / (weylAffine u).suzukiNorm = u.fst
    rw [weylAffine_suzukiNorm, div_inv_eq_mul, div_mul_cancel₀ _ hn]
  · change (u.snd / u.suzukiNorm) / (weylAffine u).suzukiNorm = u.snd
    rw [weylAffine_suzukiNorm, div_inv_eq_mul, div_mul_cancel₀ _ hn]

/-- The Weyl transformation as an endofunction of the ovoid carrier. -/
noncomputable def weylFun (m : ℕ) : Ovoid m → Ovoid m
  | none => origin m
  | some u => if u = 1 then infinity m else affine (weylAffine u)

@[simp] theorem weylFun_infinity (m : ℕ) :
    weylFun m (infinity m) = origin m := by
  rfl

@[simp] theorem weylFun_origin (m : ℕ) :
    weylFun m (origin m) = infinity m := by
  simp [weylFun, origin, affine, infinity]

/-- Evaluation of the Weyl transformation at a non-origin affine point. -/
theorem weylFun_affine_of_ne_one (u : RootGroup m) (hu : u ≠ 1) :
    weylFun m (affine u) = affine (weylAffine u) := by
  simp [weylFun, affine, hu]

/-- Coordinate evaluation of the Weyl transformation away from the origin. -/
theorem weylFun_affineMk_of_ne_zero {x y : Field m} (hxy : ¬(x = 0 ∧ y = 0)) :
    weylFun m (affineMk x y) =
      affineMk (y / suzukiNorm m x y) (x / suzukiNorm m x y) := by
  have hu : RootGroup.mk x y ≠ 1 := by
    intro h
    apply hxy
    constructor
    · simpa using congrArg RootGroup.fst h
    · simpa using congrArg RootGroup.snd h
  exact weylFun_affine_of_ne_one _ hu

/-- The norm occurring in every non-origin Weyl branch is nonzero. -/
theorem suzukiNorm_ne_zero_of_ne_zero {x y : Field m} (hxy : ¬(x = 0 ∧ y = 0)) :
    suzukiNorm m x y ≠ 0 :=
  (suzukiNorm_eq_zero_iff m x y).not.mpr hxy

/-- The Weyl transformation is involutive on the ovoid carrier. -/
theorem weylFun_involutive (m : ℕ) : Function.Involutive (weylFun m) := by
  intro p
  cases p with
  | none =>
      change weylFun m (origin m) = infinity m
      exact weylFun_origin m
  | some u =>
      change weylFun m (weylFun m (affine u)) = affine u
      by_cases hu : u = 1
      · subst u
        rw [show affine (1 : RootGroup m) = origin m by rfl, weylFun_origin,
          weylFun_infinity]
      · rw [weylFun_affine_of_ne_one u hu,
          weylFun_affine_of_ne_one (weylAffine u) (weylAffine_ne_one hu),
          weylAffine_weylAffine hu]

/-- The Weyl involution as a permutation of the Suzuki ovoid. -/
noncomputable def weylPerm (m : ℕ) : Equiv.Perm (Ovoid m) where
  toFun := weylFun m
  invFun := weylFun m
  left_inv := weylFun_involutive m
  right_inv := weylFun_involutive m

@[simp] theorem weylPerm_apply (m : ℕ) (p : Ovoid m) :
    weylPerm m p = weylFun m p :=
  rfl

@[simp] theorem weylPerm_infinity (m : ℕ) :
    weylPerm m (infinity m) = origin m :=
  weylFun_infinity m

@[simp] theorem weylPerm_origin (m : ℕ) :
    weylPerm m (origin m) = infinity m :=
  weylFun_origin m

theorem weylPerm_affine_of_ne_one (u : RootGroup m) (hu : u ≠ 1) :
    weylPerm m (affine u) = affine (weylAffine u) :=
  weylFun_affine_of_ne_one u hu

theorem weylPerm_affineMk_of_ne_zero {x y : Field m} (hxy : ¬(x = 0 ∧ y = 0)) :
    weylPerm m (affineMk x y) =
      affineMk (y / suzukiNorm m x y) (x / suzukiNorm m x y) :=
  weylFun_affineMk_of_ne_zero hxy

@[simp] theorem weylPerm_apply_apply (m : ℕ) (p : Ovoid m) :
    weylPerm m (weylPerm m p) = p :=
  weylFun_involutive m p

@[simp] theorem weylPerm_symm (m : ℕ) : (weylPerm m).symm = weylPerm m := by
  rfl


end Ovoid

end OddOrder.GroupTheory.SpecificGroups.Suzuki
