/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Peterfalvi.Appendices.Suzuki.FirstCase.StepFourteen

/-!
# Peterfalvi Part II, Ch. II, step (14): the action of `N_G(RΣ)` on `𝒜₂`

T. Peterfalvi, *Character Theory for the Odd Order Theorem* (LMS LNS 272,
2000), Part II, Ch. II, (14), p. 113.

Step (14) states that `N_G(RΣ)/RΣ ≅ S₃`.  The isomorphism is realised by the
action of `N_G(RΣ)` on the three-element set `𝒜₂` of order-`3` subgroups of
`Z₁P` other than `Z₁` (`lineSetTwo`, whose cardinality was computed in
`ncard_lineSetTwo`).  This file builds that permutation representation:

* `normalizerRSigma` — the subgroup `N_G(RΣ)`;
* `smul_mem_lineSetTwo_iff` — conjugation by an element of `N_G(RΣ)` preserves
  `𝒜₂` (it preserves `Z₁P = Z(RΣ)` and `Z₁ = ⁅RΣ, RΣ⁆`, and subgroup orders);
* `lineSetTwoPermHom` — the resulting homomorphism `N_G(RΣ) →* Sym(𝒜₂)`.

Conjugation is written with the pointwise action of `MulAut G` on `Subgroup G`,
which is the mathlib idiom; `smul_eq_map_conj` bridges it to the `Subgroup.map`
form used in `StepFourteen`.
-/

set_option autoImplicit false

open scoped Pointwise

namespace OddOrder.Peterfalvi.Appendices.Suzuki

section ConjSmul

variable {G' : Type*} [Group G']

/-- The pointwise action of `MulAut G'` on subgroups, written as a `Subgroup.map`. -/
theorem smul_eq_map_conj (g : G') (A : Subgroup G') :
    (MulAut.conj g) • A = A.map (MulAut.conj g).toMonoidHom := rfl

/-- Membership in a conjugated subgroup. -/
theorem mem_conj_smul_iff {g x : G'} {A : Subgroup G'} :
    x ∈ (MulAut.conj g) • A ↔ g⁻¹ * x * g ∈ A := by
  rw [smul_eq_map_conj, Subgroup.mem_map]
  constructor
  · rintro ⟨y, hy, rfl⟩
    have h : g⁻¹ * (g * y * g⁻¹) * g = y := by group
    rw [show (MulAut.conj g).toMonoidHom y = g * y * g⁻¹ from rfl, h]
    exact hy
  · intro h
    refine ⟨g⁻¹ * x * g, h, ?_⟩
    change g * (g⁻¹ * x * g) * g⁻¹ = x
    group

/-- Conjugation transports membership along a fixed subgroup. -/
theorem conj_mem_of_conj_smul_eq {g x : G'} {A : Subgroup G'}
    (h : (MulAut.conj g) • A = A) (hx : x ∈ A) : g * x * g⁻¹ ∈ A := by
  rw [← h, mem_conj_smul_iff]
  have h1 : g⁻¹ * (g * x * g⁻¹) * g = x := by group
  rw [h1]
  exact hx

/-- An element centralizing a subgroup elementwise fixes it under conjugation. -/
theorem conj_smul_eq_of_forall_comm {g : G'} {A : Subgroup G'}
    (h : ∀ x ∈ A, g * x = x * g) : (MulAut.conj g) • A = A := by
  ext x
  rw [mem_conj_smul_iff]
  constructor
  · intro hx
    have h1 : g * (g⁻¹ * x * g) = (g⁻¹ * x * g) * g := h _ hx
    have h2 : x = g⁻¹ * x * g := by
      calc x = g * (g⁻¹ * x * g) * g⁻¹ := by group
        _ = ((g⁻¹ * x * g) * g) * g⁻¹ := by rw [h1]
        _ = g⁻¹ * x * g := by group
    rw [h2]
    exact hx
  · intro hx
    have h1 : g⁻¹ * x * g = x := by
      calc g⁻¹ * x * g = g⁻¹ * (x * g) := by group
        _ = g⁻¹ * (g * x) := by rw [← h x hx]
        _ = x := by group
    rw [h1]
    exact hx

/-- **An odd-order element normalizing a subgroup of order `3` centralizes it.**
Conjugation permutes the two nonidentity elements of `⟨z⟩`, so conjugation by `g²` is
trivial on `⟨z⟩`; and an element of odd order lies in the group generated by its
square. -/
theorem commute_of_odd_orderOf_of_conj_mem_zpowers {g z : G'}
    (hodd : Odd (orderOf g)) (hz : orderOf z = 3)
    (hconj : g * z * g⁻¹ ∈ Subgroup.zpowers z) : g * z = z * g := by
  have hz3 : z * z * z = 1 := by
    have h := pow_orderOf_eq_one z
    rw [hz] at h
    calc z * z * z = z ^ 3 := by rw [pow_succ, pow_two]
      _ = 1 := h
  have hzne : z ≠ 1 := fun h => by rw [h, orderOf_one] at hz; omega
  -- `⟨z⟩ = {1, z, z²}`
  have hmem : ∀ c ∈ Subgroup.zpowers z, c = 1 ∨ c = z ∨ c = z * z := by
    intro c hc
    rw [Subgroup.mem_zpowers_iff] at hc
    obtain ⟨k, rfl⟩ := hc
    have hred : z ^ k = z ^ (k % 3) := by
      conv_lhs => rw [← zpow_mod_orderOf, hz]
      norm_num
    rw [hred]
    have h3 : k % 3 = 0 ∨ k % 3 = 1 ∨ k % 3 = 2 := by omega
    rcases h3 with h | h | h
    · exact Or.inl (by rw [h, zpow_zero])
    · exact Or.inr (Or.inl (by rw [h, zpow_one]))
    · exact Or.inr (Or.inr
        (by rw [h, show (2 : ℤ) = 1 + 1 from rfl, zpow_add, zpow_one]))
  have hcases : g * z * g⁻¹ = z ∨ g * z * g⁻¹ = z * z := by
    rcases hmem _ hconj with h | h | h
    · refine absurd ?_ hzne
      calc z = g⁻¹ * (g * z * g⁻¹) * g := by group
        _ = 1 := by rw [h]; group
    · exact Or.inl h
    · exact Or.inr h
  -- conjugation by `g²` fixes `z`
  have hg2 : g ^ 2 * z * (g ^ 2)⁻¹ = z := by
    have hexp : g ^ 2 * z * (g ^ 2)⁻¹ = g * (g * z * g⁻¹) * g⁻¹ := by
      rw [pow_two]; group
    rcases hcases with h | h
    · rw [hexp, h, h]
    · rw [hexp, h]
      have h4 : g * (z * z) * g⁻¹ = (g * z * g⁻¹) * (g * z * g⁻¹) := by group
      rw [h4, h]
      calc z * z * (z * z) = (z * z * z) * z := by group
        _ = z := by rw [hz3, one_mul]
  have hc2 : Commute (g ^ 2) z := by
    have h1 : g ^ 2 * z = (g ^ 2 * z * (g ^ 2)⁻¹) * g ^ 2 := by
      rw [pow_two]; group
    rw [show Commute (g ^ 2) z ↔ g ^ 2 * z = z * g ^ 2 from Iff.rfl, h1, hg2]
  -- an odd-order element is a power of its square
  obtain ⟨r, hr⟩ := hodd
  have hm : (g ^ 2) ^ (r + 1) = g := by
    rw [← pow_mul]
    have h1 : 2 * (r + 1) = orderOf g + 1 := by omega
    rw [h1, pow_succ, pow_orderOf_eq_one, one_mul]
  calc g * z = (g ^ 2) ^ (r + 1) * z := by rw [hm]
    _ = z * (g ^ 2) ^ (r + 1) := hc2.pow_left (r + 1)
    _ = z * g := by rw [hm]

end ConjSmul

namespace FirstCaseHypothesis

universe uG uΩ

variable {G : Type uG} {Ω : Type uΩ} [Group G] [MulAction G Ω] [Finite G]
  (fc : FirstCaseHypothesis G Ω)
  {F : Type uG} [NearFields.NearField F]
  (model : letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
    NearFields.AffineNearFieldModel fc.rankOneQuotient F)

/-- **`N_G(RΣ)`** ((14), p. 113), with `RΣ = R ⊔ Σ` in the notation of (11). -/
noncomputable def normalizerRSigma : Subgroup G :=
  Subgroup.normalizer ((fc.invImageF model
    ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) : Subgroup G) : Set G)

include model in
theorem mem_normalizerRSigma_iff {g : G} :
    g ∈ fc.normalizerRSigma model ↔ ∀ y : G,
      y ∈ (fc.invImageF model
          ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) : Subgroup G)
        ↔ g * y * g⁻¹ ∈ (fc.invImageF model
          ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) : Subgroup G) :=
  Subgroup.mem_set_normalizer_iff

include model in
/-- **`N_G(RΣ)` fixes `Z₁`** ((14), p. 113): `Z₁ = ⁅RΣ, RΣ⁆` is a characteristic
subgroup of `RΣ`, so conjugation by a normalizing element maps it onto itself. -/
theorem conj_smul_zpowers_eq
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) {g : G}
    (hg : g ∈ fc.normalizerRSigma model) :
    (MulAut.conj g) • Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      = Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) := by
  classical
  set Z₁ : Subgroup G := Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
    * fc.toHypothesis.t) with hZ₁_def
  have hle : (MulAut.conj g) • Z₁ ≤ Z₁ := by
    intro x hx
    rw [mem_conj_smul_iff] at hx
    have h := fc.conj_mem_zpowers_of_mem_normalizer_sup model ind hB2 hg hx
    have h1 : g * (g⁻¹ * x * g) * g⁻¹ = x := by group
    rwa [h1] at h
  refine Subgroup.eq_of_le_of_card_ge hle (le_of_eq ?_)
  rw [smul_eq_map_conj,
    Subgroup.card_map_of_injective (f := (MulAut.conj g).toMonoidHom)
      (MulAut.conj g).injective]

include model in
/-- **Conjugation by `N_G(RΣ)` preserves `𝒜₂`** ((14), p. 113): it preserves
`Z₁P = Z(RΣ)` and `Z₁ = ⁅RΣ, RΣ⁆`, and it preserves the order of a subgroup. -/
theorem smul_mem_lineSetTwo
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) {g : G}
    (hg : g ∈ fc.normalizerRSigma model) {A : Subgroup G} (hA : A ∈ fc.lineSetTwo) :
    (MulAut.conj g) • A ∈ fc.lineSetTwo := by
  classical
  obtain ⟨hle, hcard, hne⟩ := hA
  refine ⟨?_, ?_, ?_⟩
  · intro x hx
    rw [mem_conj_smul_iff] at hx
    have h := fc.conj_mem_zpowers_sup_P_of_mem_normalizer_sup model ind hB2 hg
      (hle hx)
    have h1 : g * (g⁻¹ * x * g) * g⁻¹ = x := by group
    rwa [h1] at h
  · rw [smul_eq_map_conj,
      Subgroup.card_map_of_injective (f := (MulAut.conj g).toMonoidHom)
        (MulAut.conj g).injective]
    exact hcard
  · intro hEq
    refine hne ?_
    have hZ := fc.conj_smul_zpowers_eq model ind hB2 hg
    rw [smul_eq_map_conj] at hEq hZ
    exact Subgroup.map_injective (MulAut.conj g).injective (hEq.trans hZ.symm)

include model in
/-- Conjugation by an element of `N_G(RΣ)` restricts to a bijection of `𝒜₂`. -/
theorem smul_mem_lineSetTwo_iff
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) {g : G}
    (hg : g ∈ fc.normalizerRSigma model) (A : Subgroup G) :
    (MulAut.conj g) • A ∈ fc.lineSetTwo ↔ A ∈ fc.lineSetTwo := by
  refine ⟨fun h => ?_, fun h => fc.smul_mem_lineSetTwo model ind hB2 hg h⟩
  have h' := fc.smul_mem_lineSetTwo model ind hB2 (inv_mem hg) h
  rwa [← mul_smul, ← map_mul, inv_mul_cancel, map_one, one_smul] at h'

include model in
/-- **`|RΣ| = 3⁴`** in case (10.2): `|R| = |F|·|P| = 27` and `|Σ| = 3`. -/
theorem card_sup_invImageF_centralizer_W_eq
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    Nat.card ↥(fc.invImageF model
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) = 3 ^ 4 := by
  let := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  obtain ⟨hpSig, hp3, hF9, -, -, -⟩ := fc.step_twelve model ind hB2
  obtain ⟨-, -, -, hSig3, -⟩ :=
    fc.card_field_eq_nine_of_p_dvd_card_centralizer_W ind model hB2 hpSig
  have hPcard : Nat.card ↥fc.P = 3 := by rw [fc.card_P, hp3]
  rw [fc.card_sup_invImageF_centralizer_W model ind, fc.card_invImageF model ind,
    hF9, hPcard, hSig3]
  norm_num

include model in
/-- **`s` normalizes `RΣ`**: it centralizes `P` (Ch. I Prop 5: `P ≤ V = C_D(s)`), hence
normalizes `R` (step (11)), and it centralizes `Σ ≤ W ≤ V`. -/
theorem distinguishedInvolution_mem_normalizerRSigma :
    fc.toHypothesis.distinguishedInvolution ∈ fc.normalizerRSigma model := by
  let := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  set s : G := fc.toHypothesis.distinguishedInvolution with hs_def
  have hs2 : s * s = 1 := by
    have h := fc.toHypothesis.distinguishedInvolution_sq
    rwa [pow_two] at h
  have hsinv : s⁻¹ = s := by
    rw [← mul_one s⁻¹, ← hs2, ← mul_assoc, inv_mul_cancel, one_mul]
  have hsP : s ∈ Subgroup.centralizer (fc.P : Set G) := by
    rw [Subgroup.mem_centralizer_iff]
    intro y hy
    exact Subgroup.mem_centralizer_singleton_iff.mp
      (fc.toHypothesis.V_le_centralizer_distinguishedInvolution (fc.P_le_V hy)).2
  have hconj : ∀ y ∈ (fc.invImageF model
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) : Subgroup G),
      s * y * s⁻¹ ∈ (fc.invImageF model
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) : Subgroup G) := by
    intro y hy
    have hy' : y ∈ ((fc.invImageF model : Set G)
        * ((fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G) : Subgroup G)
          : Set G)) := by
      rw [← fc.coe_sup_invImageF_centralizer_W model]
      exact hy
    obtain ⟨r, hr, w, hw, rfl⟩ := hy'
    have h1 : s * (r * w) * s⁻¹ = (s * r * s⁻¹) * (s * w * s⁻¹) := by group
    rw [h1]
    refine Subgroup.mul_mem _
      (Subgroup.mem_sup_left (fc.conj_mem_invImageF model hsP hr)) ?_
    have hws : w * s = s * w := Subgroup.mem_centralizer_singleton_iff.mp
      (fc.centralizer_W_le_centralizer_distinguishedInvolution hw)
    have h2 : s * w * s⁻¹ = w := by rw [← hws]; group
    rw [h2]
    exact Subgroup.mem_sup_right hw
  have hsinv2 : s⁻¹ * s⁻¹ = 1 := by rw [hsinv]; exact hs2
  rw [fc.mem_normalizerRSigma_iff model]
  intro h
  refine ⟨fun hh => hconj h hh, fun hh => ?_⟩
  have h3 : s * (s * h * s⁻¹) * s⁻¹ = h := by
    calc s * (s * h * s⁻¹) * s⁻¹ = (s * s) * h * (s⁻¹ * s⁻¹) := by group
      _ = h := by rw [hs2, hsinv2, one_mul, mul_one]
  rw [← h3]
  exact hconj _ hh

include model in
/-- **`|C_G(P)| = 3⁴·8`** in case (10.2): the order accounting of (11)
(`|C_G(P)| = |P|·|F|·|Q̄|·|D̄|`) with `|P| = 3`, `|F| = 9`, `|Q̄| = |F*| = 8` and
`|D̄| = |Σ| = 3`. -/
theorem card_centralizer_P_eq
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    Nat.card ↥(Subgroup.centralizer (fc.P : Set G)) = 81 * 8 := by
  let := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  obtain ⟨hpSig, hp3, hF9, -, -, -⟩ := fc.step_twelve model ind hB2
  obtain ⟨-, -, -, hSig3, -⟩ :=
    fc.card_field_eq_nine_of_p_dvd_card_centralizer_W ind model hB2 hpSig
  obtain ⟨e⟩ := fc.sigma_mulEquiv_centralizer_W ind
  have hPcard : Nat.card ↥fc.P = 3 := by rw [fc.card_P, hp3]
  have : Finite F := Nat.finite_of_card_ne_zero (by rw [hF9]; norm_num)
  have hQ8 : Nat.card ↥(fc.rankOneQuotient).Q = 8 := by
    have := Fintype.ofFinite F
    have := Classical.decEq F
    rw [Nat.card_congr model.qEquiv.toEquiv, Nat.card_eq_fintype_card,
      Fintype.card_units, ← Nat.card_eq_fintype_card, hF9]
  have hD3 : Nat.card ↥(fc.rankOneQuotient).D = 3 := by
    rw [Nat.card_congr e.toEquiv, hSig3]
  rw [fc.card_centralizer_P model ind, hPcard, hF9, hQ8, hD3]

include model in
/-- **`C_G(Z₁P) = C_G(P) ⊓ C_G(st) = RΣ`** (quoted in (15), p. 113).

`RΣ` centralizes `Z₁P`: `R` is abelian and contains both `st` and `P`, while
`Σ = C_W(P)` centralizes `P` by definition and `st` because `Σ ≤ V = C_D(s) = C_D(t)`.
Conversely `|C_G(P)| = 3⁴·8` by the order accounting of (11) in case (10.2), and `st`
lies in `T`, so it is a strongly real element of order `3` and `|C_G(st)|` is odd
(Ch. I §3, Lemma 3).  Hence `|C_G(P) ⊓ C_G(st)|` is an odd divisor of `3⁴·8`, so it
divides `3⁴ = 81 = |RΣ|`. -/
theorem centralizer_P_inf_centralizer_mul_t_eq_sup
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    Subgroup.centralizer (fc.P : Set G)
        ⊓ Subgroup.centralizer ({fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t} : Set G)
      = fc.invImageF model
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) := by
  let := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  obtain ⟨hpSig, hp3, hF9, -, -, -⟩ := fc.step_twelve model ind hB2
  obtain ⟨-, -, -, hSig3, -⟩ :=
    fc.card_field_eq_nine_of_p_dvd_card_centralizer_W ind model hB2 hpSig
  have hm : Nat.card F = fc.p ^ 2 := by rw [hF9, hp3]; norm_num
  have hPcard : Nat.card ↥fc.P = 3 := by rw [fc.card_P, hp3]
  have hCPcard := fc.card_centralizer_P_eq model ind hB2
  set R : Subgroup G := fc.invImageF model with hR_def
  set Sg : Subgroup G :=
    fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G) with hSg_def
  have hRcard : Nat.card ↥R = 27 := by
    rw [hR_def, fc.card_invImageF model ind, hF9, hPcard]
  have hRScard : Nat.card ↥(R ⊔ Sg) = 81 := by
    rw [hR_def, hSg_def, fc.card_sup_invImageF_centralizer_W model ind]
    rw [← hR_def, ← hSg_def, hRcard, hSig3]
  -- `RΣ` centralizes both `P` and `st`
  have habR := fc.invImageF_mul_comm model ind hB2 hm
  have hPR : fc.P ≤ R := fc.P_le_invImageF model
  have hstR : fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t ∈ R :=
    fc.distinguishedInvolution_mul_t_mem_invImageF model
  have hle : R ⊔ Sg ≤ Subgroup.centralizer (fc.P : Set G)
      ⊓ Subgroup.centralizer ({fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t} : Set G) := by
    refine sup_le (le_inf ?_ ?_)
      (le_inf inf_le_right
        fc.centralizer_W_le_centralizer_distinguishedInvolution_mul_t)
    · intro r hr
      rw [Subgroup.mem_centralizer_iff]
      intro y hy
      exact (habR r hr y (hPR hy)).symm
    · intro r hr
      exact Subgroup.mem_centralizer_singleton_iff.mpr (habR r hr _ hstR)
  -- `|C_G(st)|` is odd: `st ∈ T` is strongly real of order `3`
  have hstord : orderOf (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) = 3 := by
    rw [fc.orderOf_st_eq_char model, fc.char_eq_p model hB2, hp3]
  have hst2 : (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) ^ 2 ≠ 1 := by
    intro h
    have h1 := orderOf_dvd_of_pow_eq_one h
    rw [hstord] at h1
    omega
  have hoddC := fc.toHypothesis.centralizer_natCard_odd_of_stronglyReal
    (fc.isStronglyReal_of_mem_sInvertedT model ind hB2 hm
      (fc.distinguishedInvolution_mul_t_mem_sInvertedT model ind hB2 hm)) hst2
  -- an odd divisor of `3⁴·8` divides `3⁴`
  have hodd' : Odd (Nat.card ↥(Subgroup.centralizer (fc.P : Set G)
      ⊓ Subgroup.centralizer ({fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t} : Set G))) :=
    hoddC.of_dvd_nat (Subgroup.card_dvd_of_le inf_le_right)
  have hdvd648 : Nat.card ↥(Subgroup.centralizer (fc.P : Set G)
      ⊓ Subgroup.centralizer ({fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t} : Set G)) ∣ 81 * 8 := by
    rw [← hCPcard]
    exact Subgroup.card_dvd_of_le inf_le_left
  have hdvd81 := (hodd'.coprime_two_right.pow_right 3).dvd_of_dvd_mul_right hdvd648
  have hge : 81 ∣ Nat.card ↥(Subgroup.centralizer (fc.P : Set G)
      ⊓ Subgroup.centralizer ({fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t} : Set G)) := by
    rw [← hRScard]
    exact Subgroup.card_dvd_of_le hle
  exact (Subgroup.eq_of_le_of_card_ge hle
    (le_of_eq (by rw [Nat.dvd_antisymm hdvd81 hge, hRScard]))).symm

include model in
/-- **The permutation representation of `N_G(RΣ)` on `𝒜₂`** ((14), p. 113).
Step (14) asserts that this map is onto `Sym(𝒜₂) ≅ S₃` with kernel `RΣ`. -/
noncomputable def lineSetTwoPermHom
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    ↥(fc.normalizerRSigma model) →* Equiv.Perm ↥fc.lineSetTwo where
  toFun g := (MulAction.toPerm (MulAut.conj (g : G))).subtypePerm
    (fun A => fc.smul_mem_lineSetTwo_iff model ind hB2 g.2 A)
  map_one' := by
    refine Equiv.ext fun A => Subtype.ext ?_
    change (MulAut.conj ((1 : ↥(fc.normalizerRSigma model)) : G)) • (A : Subgroup G)
      = (A : Subgroup G)
    rw [Subgroup.coe_one, map_one, one_smul]
  map_mul' g h := by
    refine Equiv.ext fun A => Subtype.ext ?_
    change (MulAut.conj ((g * h : ↥(fc.normalizerRSigma model)) : G)) • (A : Subgroup G)
      = (MulAut.conj ((g : G))) • ((MulAut.conj ((h : G))) • (A : Subgroup G))
    rw [Subgroup.coe_mul, map_mul, mul_smul]

include model in
/-- `Z₁ ⊓ P = 1`: `Z₁ ≤ T` by the "`Z₁ ⊂ T`" remark of (14), and `T ⊓ P = 1` by (11). -/
theorem zpowers_inf_P_eq_bot
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) {m : ℕ}
    (hm : Nat.card F = fc.p ^ m) :
    Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t)
      ⊓ fc.P = ⊥ := by
  rw [eq_bot_iff]
  intro x hx
  have hx' : x ∈ fc.sInvertedT model ⊓ fc.P :=
    ⟨fc.zpowers_distinguishedInvolution_mul_t_le_sInvertedT model ind hB2 hm hx.1,
      hx.2⟩
  rwa [(fc.sInvertedT_spec model ind hB2 hm).2.2.2] at hx'

include model in
/-- `P ∈ 𝒜₂` (it has order `3` and meets `Z₁` trivially). -/
theorem P_mem_lineSetTwo
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) : fc.P ∈ fc.lineSetTwo := by
  obtain ⟨-, hp3, hF9, -, -, -⟩ := fc.step_twelve model ind hB2
  have hm : Nat.card F = fc.p ^ 2 := by rw [hF9, hp3]; norm_num
  have hPcard : Nat.card ↥fc.P = 3 := by rw [fc.card_P, hp3]
  refine ⟨le_sup_right, hPcard, fun hEq => ?_⟩
  have hbot := fc.zpowers_inf_P_eq_bot model ind hB2 hm
  rw [← hEq, inf_idem] at hbot
  rw [hbot, Subgroup.card_bot] at hPcard
  omega

include model in
/-- `⟨(st)·y⟩ ∈ 𝒜₂` for a nonidentity `y ∈ P`: the two commuting order-`3` elements
`st` and `y` generate distinct lines of `Z₁P`. -/
theorem zpowers_mul_mem_lineSetTwo
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) {y : G} (hyP : y ∈ fc.P)
    (hy1 : y ≠ 1) :
    Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t * y) ∈ fc.lineSetTwo := by
  let := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  obtain ⟨-, hp3, hF9, -, -, -⟩ := fc.step_twelve model ind hB2
  have hm : Nat.card F = fc.p ^ 2 := by rw [hF9, hp3]; norm_num
  set z : G := fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t with hz_def
  have hbot := fc.zpowers_inf_P_eq_bot model ind hB2 hm
  have hzZ : z ∈ Subgroup.zpowers z := Subgroup.mem_zpowers z
  have hstord : orderOf z = 3 := by
    rw [hz_def, fc.orderOf_st_eq_char model, fc.char_eq_p model hB2, hp3]
  -- `z` and `y` commute inside the abelian `R`
  have habR := fc.invImageF_mul_comm model ind hB2 hm
  have hcomm : Commute z y :=
    habR z (fc.distinguishedInvolution_mul_t_mem_invImageF model) y
      (fc.P_le_invImageF model hyP)
  have hy3 : y ^ 3 = 1 := by
    have h := fc.P.orderOf_dvd_natCard hyP
    rw [fc.card_P, hp3] at h
    exact orderOf_dvd_iff_pow_eq_one.mp h
  have hz3 : z ^ 3 = 1 := by rw [← hstord]; exact pow_orderOf_eq_one z
  -- `z·y ≠ 1`
  have hzy1 : z * y ≠ 1 := by
    intro h
    have hz' : z ∈ Subgroup.zpowers z ⊓ fc.P := by
      refine ⟨hzZ, ?_⟩
      have : z = y⁻¹ := by rw [← mul_one z, ← mul_inv_cancel y, ← mul_assoc, h, one_mul]
      rw [this]
      exact fc.P.inv_mem hyP
    rw [hbot, Subgroup.mem_bot] at hz'
    rw [hz'] at hstord
    simp at hstord
  refine ⟨Subgroup.zpowers_le.mpr (Subgroup.mul_mem_sup hzZ hyP), ?_, ?_⟩
  · rw [Nat.card_zpowers]
    have hdvd : orderOf (z * y) ∣ 3 :=
      orderOf_dvd_iff_pow_eq_one.mpr (by rw [hcomm.mul_pow, hy3, hz3, one_mul])
    rcases (Nat.dvd_prime (by norm_num)).mp hdvd with h1 | h3
    · exact absurd (orderOf_eq_one_iff.mp h1) hzy1
    · exact h3
  · intro hEq
    have hyZ : y ∈ Subgroup.zpowers z ⊓ fc.P := by
      refine ⟨?_, hyP⟩
      have h1 : y = z⁻¹ * (z * y) := by group
      rw [h1]
      exact Subgroup.mul_mem _ (Subgroup.inv_mem _ hzZ)
        (hEq ▸ Subgroup.mem_zpowers (z * y))
    rw [hbot, Subgroup.mem_bot] at hyZ
    exact hy1 hyZ

@[simp]
theorem lineSetTwoPermHom_apply
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G))
    (g : ↥(fc.normalizerRSigma model)) (A : ↥fc.lineSetTwo) :
    (fc.lineSetTwoPermHom model ind hB2 g A : Subgroup G)
      = (MulAut.conj ((g : G))) • (A : Subgroup G) := rfl

include model in
/-- **The kernel of the action of `N_G(RΣ)` on `𝒜₂` is `RΣ`** ((14), p. 113).

`RΣ` acts trivially because `Z₁P = Z(RΣ)`, so it centralizes every member of `𝒜₂`
elementwise.  Conversely an element `g` of the kernel fixes `P ∈ 𝒜₂`, hence
centralizes `P` (step (1): `N_G(P) = C_G(P)`); it also fixes `Z₁` and the line
`⟨(st)·y⟩` for a generator `y` of `P`, and matching the unique `Z₁ × P`
decomposition of `g·(st·y)·g⁻¹ = (g·st·g⁻¹)·y` pins the exponent to `k ≡ 1 (mod 3)`,
so `g` centralizes `st` as well.  Thus `g ∈ C_G(P) ⊓ C_G(st) = RΣ`.

Peterfalvi instead argues that the kernel lies in `N_G(P) = R·C_Q(P)·Σ` and that
`C_Q(P)^#` is fixed-point-free on `𝒜 − {P}`; the route taken here replaces the
structure of `N_G(P)` by the order of `C_G(P)` together with the oddness of
`|C_G(st)|` (`centralizer_P_inf_centralizer_mul_t_eq_sup`). -/
theorem mem_ker_lineSetTwoPermHom_iff
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G))
    {g : ↥(fc.normalizerRSigma model)} :
    g ∈ (fc.lineSetTwoPermHom model ind hB2).ker ↔
      (g : G) ∈ fc.invImageF model
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) := by
  let := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  obtain ⟨-, hp3, hF9, -, -, -⟩ := fc.step_twelve model ind hB2
  have hm : Nat.card F = fc.p ^ 2 := by rw [hF9, hp3]; norm_num
  set z : G := fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t with hz_def
  have hstord : orderOf z = 3 := by
    rw [hz_def, fc.orderOf_st_eq_char model, fc.char_eq_p model hB2, hp3]
  have hcentre := fc.inf_centralizer_sup_eq_zpowers_sup_P model ind hB2
  constructor
  · intro hker
    have hfix : ∀ A ∈ fc.lineSetTwo, (MulAut.conj (g : G)) • A = A := by
      intro A hA
      have h1 : fc.lineSetTwoPermHom model ind hB2 g ⟨A, hA⟩ = ⟨A, hA⟩ := by
        rw [MonoidHom.mem_ker.mp hker]; rfl
      simpa using congrArg Subtype.val h1
    -- `g` fixes `P`, hence centralizes it (step (1): `N_G(P) = C_G(P)`)
    have hgC : (g : G) ∈ Subgroup.centralizer (fc.P : Set G) := by
      rw [← fc.normalizer_P_eq_centralizer]
      exact conj_smul_eq_iff_mem_normalizer.mp
        (hfix fc.P (fc.P_mem_lineSetTwo model ind hB2))
    obtain ⟨y, hyP, hy1⟩ : ∃ y ∈ fc.P, y ≠ (1 : G) := by
      by_contra hcon
      push Not at hcon
      have hbot : fc.P = ⊥ := by
        rw [eq_bot_iff]
        intro x hx
        rw [Subgroup.mem_bot]
        exact hcon x hx
      have h2 := fc.card_P
      rw [hbot, Subgroup.card_bot, hp3] at h2
      omega
    have hyord : orderOf y = 3 := by
      have h := fc.P.orderOf_dvd_natCard hyP
      rw [fc.card_P, hp3] at h
      rcases (Nat.dvd_prime (by norm_num)).mp h with h1 | h3
      · exact absurd (orderOf_eq_one_iff.mp h1) hy1
      · exact h3
    have hgy : (g : G) * y * (g : G)⁻¹ = y := by
      have h1 := Subgroup.mem_centralizer_iff.mp hgC y hyP
      calc (g : G) * y * (g : G)⁻¹ = (y * (g : G)) * (g : G)⁻¹ := by rw [← h1]
        _ = y := by group
    -- `g` fixes the line `⟨z·y⟩`
    have hcomm : Commute z y :=
      fc.invImageF_mul_comm model ind hB2 hm z
        (fc.distinguishedInvolution_mul_t_mem_invImageF model) y
        (fc.P_le_invImageF model hyP)
    have hmem := conj_mem_of_conj_smul_eq
      (hfix _ (fc.zpowers_mul_mem_lineSetTwo model ind hB2 hyP hy1))
      (Subgroup.mem_zpowers (z * y))
    rw [Subgroup.mem_zpowers_iff] at hmem
    obtain ⟨k, hk⟩ := hmem
    have hu : (g : G) * z * (g : G)⁻¹ ∈ Subgroup.zpowers z :=
      conj_mem_of_conj_smul_eq (fc.conj_smul_zpowers_eq model ind hB2 g.2)
        (Subgroup.mem_zpowers z)
    have hsplit : (g : G) * (z * y) * (g : G)⁻¹
        = ((g : G) * z * (g : G)⁻¹) * y := by
      calc (g : G) * (z * y) * (g : G)⁻¹
          = ((g : G) * z * (g : G)⁻¹) * ((g : G) * y * (g : G)⁻¹) := by group
        _ = ((g : G) * z * (g : G)⁻¹) * y := by rw [hgy]
    have heq : z ^ k * y ^ k = ((g : G) * z * (g : G)⁻¹) * y := by
      rw [← hcomm.mul_zpow, hk, hsplit]
    -- unique `Z₁ × P` decomposition
    have hab : (z ^ k)⁻¹ * ((g : G) * z * (g : G)⁻¹) = y ^ k * y⁻¹ := by
      have h1 : y ^ k = (z ^ k)⁻¹ * (((g : G) * z * (g : G)⁻¹) * y) := by
        rw [← heq]; group
      calc (z ^ k)⁻¹ * ((g : G) * z * (g : G)⁻¹)
          = ((z ^ k)⁻¹ * (((g : G) * z * (g : G)⁻¹) * y)) * y⁻¹ := by group
        _ = y ^ k * y⁻¹ := by rw [← h1]
    have hone : (z ^ k)⁻¹ * ((g : G) * z * (g : G)⁻¹) = 1 := by
      have hmemboth : (z ^ k)⁻¹ * ((g : G) * z * (g : G)⁻¹)
          ∈ Subgroup.zpowers z ⊓ fc.P := by
        refine ⟨Subgroup.mul_mem _ (Subgroup.inv_mem _
          (Subgroup.zpow_mem _ (Subgroup.mem_zpowers z) k)) hu, ?_⟩
        rw [hab]
        exact Subgroup.mul_mem _ (Subgroup.zpow_mem _ hyP k)
          (Subgroup.inv_mem _ hyP)
      rwa [fc.zpowers_inf_P_eq_bot model ind hB2 hm, Subgroup.mem_bot] at hmemboth
    have hyk : y ^ k = y := by
      have h1 : y ^ k * y⁻¹ = 1 := by rw [← hab, hone]
      calc y ^ k = (y ^ k * y⁻¹) * y := by group
        _ = y := by rw [h1, one_mul]
    -- `k ≡ 1 (mod 3)`, so `g` centralizes `z` too
    have hzk : z ^ k = z := by
      have hk1 : y ^ (k - 1) = 1 := by
        rw [zpow_sub, zpow_one, hyk, mul_inv_cancel]
      have hdvd : ((3 : ℕ) : ℤ) ∣ k - 1 := by
        rw [← hyord]
        exact orderOf_dvd_iff_zpow_eq_one.mpr hk1
      have hz1 : z ^ (k - 1) = 1 :=
        orderOf_dvd_iff_zpow_eq_one.mp (by rw [hstord]; exact hdvd)
      rw [zpow_sub, zpow_one] at hz1
      calc z ^ k = (z ^ k * z⁻¹) * z := by group
        _ = z := by rw [hz1, one_mul]
    have hgz : (g : G) * z = z * (g : G) := by
      have h1 : (g : G) * z * (g : G)⁻¹ = z := by
        calc (g : G) * z * (g : G)⁻¹
            = z ^ k * ((z ^ k)⁻¹ * ((g : G) * z * (g : G)⁻¹)) := by group
          _ = z ^ k := by rw [hone, mul_one]
          _ = z := hzk
      calc (g : G) * z = ((g : G) * z * (g : G)⁻¹) * (g : G) := by group
        _ = z * (g : G) := by rw [h1]
    rw [← fc.centralizer_P_inf_centralizer_mul_t_eq_sup model ind hB2]
    exact ⟨hgC, Subgroup.mem_centralizer_singleton_iff.mpr hgz⟩
  · intro hg
    rw [MonoidHom.mem_ker]
    refine Equiv.ext fun A => Subtype.ext ?_
    change (MulAut.conj ((g : G))) • (A : Subgroup G) = (A : Subgroup G)
    refine conj_smul_eq_of_forall_comm fun x hx => ?_
    have hxZ : x ∈ Subgroup.zpowers z ⊔ fc.P := (fc.mem_lineSetTwo.mp A.2).1 hx
    rw [← hcentre] at hxZ
    exact Subgroup.mem_centralizer_iff.mp hxZ.2 (g : G) hg

include model in
/-- **`RΣ` is not a Sylow `3`-subgroup of `G`** (by (10.2), `|G|₃ = 3⁴·|W|` with
`|W| ∈ {3, 9}`, while `|RΣ| = 3⁴`), so normalizer growth inside a Sylow `3`-subgroup
containing `RΣ` produces a `3`-element of `N_G(RΣ)` outside `RΣ`. -/
theorem exists_orderOf_pow_three_mem_normalizerRSigma_notMem_sup
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    ∃ x ∈ fc.normalizerRSigma model,
      x ∉ (fc.invImageF model
          ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) : Subgroup G)
        ∧ ∃ j : ℕ, orderOf x = 3 ^ j := by
  let := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  have : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  obtain ⟨-, -, -, -, hW, hGp⟩ := fc.step_twelve model ind hB2
  have hRScard := fc.card_sup_invImageF_centralizer_W_eq model ind hB2
  have hRp : IsPGroup 3 ↥(fc.invImageF model
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) : Subgroup G) :=
    IsPGroup.of_card hRScard
  obtain ⟨X, hRX⟩ := hRp.exists_le_sylow
  have hXcard : Nat.card ↥(X : Subgroup G)
      = 3 ^ 4 * Nat.card ↥fc.toHypothesis.W := by
    rw [Sylow.card_eq_multiplicity]
    exact hGp
  have hWge : 3 ≤ Nat.card ↥fc.toHypothesis.W := by rcases hW with h | h <;> omega
  have hRltX : (fc.invImageF model
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) : Subgroup G)
      < (X : Subgroup G) := by
    refine lt_of_le_of_ne hRX fun h => ?_
    rw [← h, hRScard] at hXcard
    have hcon : (3 : ℕ) ^ 4 * 3 ≤ 3 ^ 4 * Nat.card ↥fc.toHypothesis.W := by gcongr
    rw [← hXcard] at hcon
    norm_num at hcon
  have hgrow := OddOrder.BG.Ch2.S08.lt_inf_normalizer_of_isPGroup_lt
    (p := 3) X.isPGroup' hRltX
  obtain ⟨x, hxY, hxR⟩ := SetLike.exists_of_lt hgrow
  refine ⟨x, hxY.2, hxR, ?_⟩
  obtain ⟨j, hj⟩ := (IsPGroup.iff_orderOf).mp X.isPGroup' ⟨x, hxY.1⟩
  exact ⟨j, by rwa [Subgroup.orderOf_mk] at hj⟩

include model in
/-- **`N_G(RΣ)` induces the full symmetric group on `𝒜₂`** ((14), p. 113): the image
of the action is all of `Sym(𝒜₂) ≅ S₃`.

`|Sym(𝒜₂)| = 3! = 6`.  The distinguished involution `s` normalizes `RΣ` and lies
outside it (`|RΣ| = 3⁴` is odd), so its image has order `2`; and `RΣ` is not a Sylow
`3`-subgroup of `G` by (10.2), so `N_G(RΣ)` also contains a `3`-element outside `RΣ`,
whose image has order `3`.  Hence `6 ∣ |image|` and `|image| ∣ 6`. -/
theorem lineSetTwoPermHom_surjective
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    Function.Surjective (fc.lineSetTwoPermHom model ind hB2) := by
  classical
  have : Finite (Subgroup G) :=
    Finite.of_injective (fun H : Subgroup G => (H : Set G)) SetLike.coe_injective
  have : Finite ↥fc.lineSetTwo := Subtype.finite
  have := Fintype.ofFinite ↥fc.lineSetTwo
  have := Classical.decEq ↥fc.lineSetTwo
  have : Fact (Nat.Prime 2) := ⟨by norm_num⟩
  set φ := fc.lineSetTwoPermHom model ind hB2 with hφ_def
  -- `|Sym(𝒜₂)| = 3! = 6`
  have hA3 : Fintype.card ↥fc.lineSetTwo = 3 := by
    rw [← Nat.card_eq_fintype_card, Nat.card_coe_set_eq,
      fc.ncard_lineSetTwo model ind hB2]
  have hcard6 : Nat.card (Equiv.Perm ↥fc.lineSetTwo) = 6 := by
    rw [Nat.card_eq_fintype_card, Fintype.card_perm, hA3]
    decide
  have hRScard := fc.card_sup_invImageF_centralizer_W_eq model ind hB2
  -- the image of `s` has order `2`
  have hsN := fc.distinguishedInvolution_mem_normalizerRSigma model
  have hsnotR : fc.toHypothesis.distinguishedInvolution
      ∉ (fc.invImageF model
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) : Subgroup G) := by
    intro hmem
    have hord : orderOf fc.toHypothesis.distinguishedInvolution = 2 :=
      orderOf_eq_prime fc.toHypothesis.distinguishedInvolution_sq
        fc.toHypothesis.distinguishedInvolution_ne_one
    have hdvd := Subgroup.orderOf_dvd_natCard _ hmem
    rw [hord, hRScard] at hdvd
    norm_num at hdvd
  have hφs2 : orderOf (φ ⟨_, hsN⟩) = 2 := by
    refine orderOf_eq_prime ?_ fun h => ?_
    · have hx2 : (⟨_, hsN⟩ : ↥(fc.normalizerRSigma model)) ^ 2 = 1 := by
        refine Subtype.ext ?_
        rw [Subgroup.coe_pow, Subgroup.coe_one]
        exact fc.toHypothesis.distinguishedInvolution_sq
      rw [← map_pow, hx2, map_one]
    · exact hsnotR ((fc.mem_ker_lineSetTwoPermHom_iff model ind hB2).mp
        (MonoidHom.mem_ker.mpr h))
  have h2dvd : 2 ∣ Nat.card ↥φ.range := by
    have hd := Subgroup.orderOf_dvd_natCard φ.range
      (⟨⟨_, hsN⟩, rfl⟩ : φ ⟨_, hsN⟩ ∈ φ.range)
    rwa [hφs2] at hd
  -- the image of a `3`-element outside `RΣ` has order `3`
  obtain ⟨x, hxN, hxR, j, hxord⟩ :=
    fc.exists_orderOf_pow_three_mem_normalizerRSigma_notMem_sup model ind hB2
  have hφx1 : φ (⟨x, hxN⟩ : ↥(fc.normalizerRSigma model)) ≠ 1 := fun h =>
    hxR ((fc.mem_ker_lineSetTwoPermHom_iff model ind hB2).mp
      (MonoidHom.mem_ker.mpr h))
  have hdvd3 : orderOf (φ (⟨x, hxN⟩ : ↥(fc.normalizerRSigma model))) ∣ 3 ^ j := by
    have h1 := orderOf_map_dvd φ (⟨x, hxN⟩ : ↥(fc.normalizerRSigma model))
    rwa [Subgroup.orderOf_mk, hxord] at h1
  obtain ⟨i, -, hie⟩ := (Nat.dvd_prime_pow (by norm_num)).mp hdvd3
  have h3dvd : 3 ∣ Nat.card ↥φ.range := by
    refine dvd_trans ?_ (Subgroup.orderOf_dvd_natCard φ.range
      (⟨⟨x, hxN⟩, rfl⟩ : φ (⟨x, hxN⟩ : ↥(fc.normalizerRSigma model)) ∈ φ.range))
    rw [hie]
    refine dvd_pow_self 3 fun h => ?_
    rw [h, pow_zero] at hie
    exact hφx1 (orderOf_eq_one_iff.mp hie)
  -- `6 ∣ |image| ∣ 6`
  have h6 : 6 ∣ Nat.card ↥φ.range := by
    exact Nat.Coprime.mul_dvd_of_dvd_of_dvd
      (show Nat.Coprime 2 3 by norm_num) h2dvd h3dvd
  rw [← MonoidHom.range_eq_top]
  refine Subgroup.eq_top_of_card_eq _ ?_
  rw [hcard6]
  exact Nat.dvd_antisymm (by rw [← hcard6]; exact Subgroup.card_subgroup_dvd_card _) h6

include model in
/-- **`|N_G(RΣ)| = 2·3⁵`** ((14), p. 113): the action on `𝒜₂` has kernel `RΣ`
(order `3⁴`) and image all of `Sym(𝒜₂)` (order `3! = 6`). -/
theorem card_normalizerRSigma
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    Nat.card ↥(fc.normalizerRSigma model) = 2 * 3 ^ 5 := by
  classical
  have : Finite (Subgroup G) :=
    Finite.of_injective (fun H : Subgroup G => (H : Set G)) SetLike.coe_injective
  have : Finite ↥fc.lineSetTwo := Subtype.finite
  have := Fintype.ofFinite ↥fc.lineSetTwo
  have := Classical.decEq ↥fc.lineSetTwo
  set φ := fc.lineSetTwoPermHom model ind hB2 with hφ_def
  have hRle : (fc.invImageF model
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) : Subgroup G)
      ≤ fc.normalizerRSigma model := Subgroup.le_normalizer
  have hker : φ.ker = (fc.invImageF model
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))).subgroupOf
        (fc.normalizerRSigma model) := by
    ext g
    rw [Subgroup.mem_subgroupOf]
    exact fc.mem_ker_lineSetTwoPermHom_iff model ind hB2
  have hkercard : Nat.card ↥φ.ker = 3 ^ 4 := by
    rw [hker, Nat.card_congr (Subgroup.subgroupOfEquivOfLe hRle).toEquiv]
    exact fc.card_sup_invImageF_centralizer_W_eq model ind hB2
  have hA3 : Fintype.card ↥fc.lineSetTwo = 3 := by
    rw [← Nat.card_eq_fintype_card, Nat.card_coe_set_eq,
      fc.ncard_lineSetTwo model ind hB2]
  have hrange : Nat.card ↥φ.range = 6 := by
    rw [MonoidHom.range_eq_top.mpr (fc.lineSetTwoPermHom_surjective model ind hB2),
      Subgroup.card_top, Nat.card_eq_fintype_card, Fintype.card_perm, hA3]
    decide
  have hq := Subgroup.card_eq_card_quotient_mul_card_subgroup φ.ker
  rw [Nat.card_congr (QuotientGroup.quotientKerEquivRange φ).toEquiv, hrange,
    hkercard] at hq
  rw [hq]
  norm_num

end FirstCaseHypothesis

end OddOrder.Peterfalvi.Appendices.Suzuki
