/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Peterfalvi.Appendices.Suzuki.FirstCase.StepSixteen

/-!
# Peterfalvi Part II, Ch. II, step (17): weak closure of `Z₁PΣ`

T. Peterfalvi, *Character Theory for the Odd Order Theorem* (LMS LNS 272,
2000), Part II, Ch. II, (17), p. 114.

This file proves the first half of (17): the abelian subgroup `Z₁PΣ` is weakly closed
in the Sylow `3`-subgroup `R₂` (`map_conj_eq_of_le_sylow`), which is the hypothesis of
the Hall–Wielandt theorem, together with `N_G(R₂) = R₂⟨s⟩ = N_G(Z₁PΣ)`.  The final
contradiction built on it is in `StepSeventeen.lean`.
-/

set_option autoImplicit false

open scoped Pointwise commutatorElement

namespace OddOrder.Peterfalvi.Appendices.Suzuki

section GenericStronglyReal

variable {G' : Type*} [Group G']

/-- The inverse of a strongly real element is strongly real. -/
theorem isStronglyReal_inv {x : G'} (hx : IsStronglyReal x) : IsStronglyReal x⁻¹ := by
  obtain ⟨u, ⟨hu2, hu1⟩, v, ⟨hv2, hv1⟩, rfl⟩ := hx
  have huinv : u⁻¹ = u := inv_eq_of_mul_eq_one_right (by rw [← pow_two]; exact hu2)
  have hvinv : v⁻¹ = v := inv_eq_of_mul_eq_one_right (by rw [← pow_two]; exact hv2)
  exact ⟨v, ⟨hv2, hv1⟩, u, ⟨hu2, hu1⟩, by rw [mul_inv_rev, huinv, hvinv]⟩

/-- A normal subgroup of prime index `p` forces `p ∣ |G^{ab}|`. -/
theorem dvd_card_abelianization_of_index_eq_prime [Finite G'] {H : Subgroup G'}
    [H.Normal] {p : ℕ} (hp : p.Prime) (hidx : H.index = p) :
    p ∣ Nat.card (Abelianization G') := by
  classical
  haveI : Fact p.Prime := ⟨hp⟩
  haveI hcyc : IsCyclic (G' ⧸ H) :=
    isCyclic_of_prime_card (α := G' ⧸ H) (p := p)
      (by rw [← Subgroup.index_eq_card, hidx])
  haveI : IsMulCommutative (G' ⧸ H) := IsCyclic.isMulCommutative
  have hcomm : commutator G' ≤ H := by
    rw [commutator_def]
    refine Subgroup.commutator_le.mpr fun a _ b _ => ?_
    rw [← QuotientGroup.eq_one_iff]
    have h := ‹IsMulCommutative (G' ⧸ H)›.is_comm.comm
      (QuotientGroup.mk (s := H) a) (QuotientGroup.mk (s := H) b)
    calc QuotientGroup.mk (s := H) ⁅a, b⁆
        = ⁅QuotientGroup.mk (s := H) a, QuotientGroup.mk (s := H) b⁆ := by
          simp [commutatorElement_def, QuotientGroup.mk_mul, QuotientGroup.mk_inv]
      _ = 1 := commutatorElement_eq_one_iff_commute.mpr h
  let f : Abelianization G' →* G' ⧸ H :=
    QuotientGroup.map (commutator G') H (MonoidHom.id G') (by simpa using hcomm)
  have hsurj : Function.Surjective f := by
    intro y
    obtain ⟨g, rfl⟩ := QuotientGroup.mk_surjective (s := H) y
    exact ⟨Abelianization.of g, rfl⟩
  have hcard : Nat.card (G' ⧸ H) ∣ Nat.card (Abelianization G') := by
    obtain ⟨e⟩ : Nonempty ((Abelianization G' ⧸ f.ker) ≃* (G' ⧸ H)) :=
      ⟨QuotientGroup.quotientKerEquivOfSurjective f hsurj⟩
    rw [← Nat.card_congr e.toEquiv, ← Subgroup.index_eq_card]
    exact Subgroup.index_dvd_card _
  rwa [← Subgroup.index_eq_card, hidx] at hcard

/-- **Class-`2` commutator bound.**  Let `Z ≤ N ≤ X` with `Z` centralizing `X`,
`⁅N, X⁆ ≤ Z` and `⁅X, X⁆ ≤ N`, and suppose `X` is generated by `N` together with two
elements `u, v`.  Then `⁅X, X⁆ ≤ Z⟨⁅u,v⁆⟩`.

This is the group-theoretic content of "the commutator induces an alternating form on
the two-dimensional space `X/N`, so its image is at most one-dimensional". -/
theorem commutator_le_of_two_generators [Finite G'] {X N Z : Subgroup G'} {u v : G'}
    (hZcen : ∀ z ∈ Z, ∀ x ∈ X, z * x = x * z)
    (hNX : ⁅N, X⁆ ≤ Z) (hXX : ⁅X, X⁆ ≤ N) (huX : u ∈ X) (hvX : v ∈ X)
    (hgen : Subgroup.closure ((N : Set G') ∪ {u, v}) = X) :
    ⁅X, X⁆ ≤ Z ⊔ Subgroup.zpowers ⁅u, v⁆ := by
  classical
  set c : G' := ⁅u, v⁆ with hc_def
  set M : Subgroup G' := Z ⊔ Subgroup.zpowers c with hM_def
  have hcN : c ∈ N := hXX (Subgroup.commutator_mem_commutator huX hvX)
  -- `M` is normalized by every element of `X`
  have hMconj : ∀ x ∈ X, ∀ m ∈ M, x * m * x⁻¹ ∈ M := by
    intro x hx m hm
    have hsub : M ≤ Subgroup.comap (MulAut.conj x).toMonoidHom M := by
      refine sup_le (fun z hz => ?_) (Subgroup.zpowers_le.mpr ?_)
      · have : x * z * x⁻¹ = z := by rw [← hZcen z hz x hx]; group
        exact Subgroup.mem_sup_left (by change x * z * x⁻¹ ∈ Z; rw [this]; exact hz)
      · -- `x c x⁻¹ = ⁅x, c⁆ · c` with `⁅x, c⁆ ∈ Z`
        have hxc : ⁅x, c⁆ ∈ Z := by
          have h := Subgroup.commutator_mem_commutator hcN hx
          have h2 : ⁅c, x⁆ ∈ Z := hNX h
          have h3 : ⁅x, c⁆ = ⁅c, x⁆⁻¹ := by
            rw [commutatorElement_def, commutatorElement_def]; group
          rw [h3]
          exact Subgroup.inv_mem _ h2
        have heq : x * c * x⁻¹ = ⁅x, c⁆ * c := by
          rw [commutatorElement_def]; group
        change x * c * x⁻¹ ∈ M
        rw [heq]
        exact Subgroup.mul_mem _ (Subgroup.mem_sup_left hxc)
          (Subgroup.mem_sup_right (Subgroup.mem_zpowers _))
    exact hsub hm
  -- for fixed `a ∈ X`, the property `⁅a, ·⁆ ∈ M` passes from generators to all of `X`
  have hright : ∀ a ∈ X, (∀ b ∈ (N : Set G') ∪ {u, v}, ⁅a, b⁆ ∈ M) →
      ∀ b ∈ X, ⁅a, b⁆ ∈ M := by
    intro a _ hbase b hb
    rw [← hgen] at hb
    induction hb using Subgroup.closure_induction with
    | mem y hy => exact hbase y hy
    | one =>
        rw [show ⁅a, (1 : G')⁆ = 1 by rw [commutatorElement_def]; group]
        exact M.one_mem
    | mul x y hx hy ihx ihy =>
        have hxX : x ∈ X := by rw [← hgen]; exact hx
        have heq : ⁅a, x * y⁆ = ⁅a, x⁆ * (x * ⁅a, y⁆ * x⁻¹) := by
          rw [commutatorElement_def, commutatorElement_def, commutatorElement_def]
          group
        rw [heq]
        exact M.mul_mem ihx (hMconj x hxX _ ihy)
    | inv x hx ihx =>
        have hxX : x ∈ X := by rw [← hgen]; exact hx
        have heq : ⁅a, x⁻¹⁆ = x⁻¹ * ⁅a, x⁆⁻¹ * (x⁻¹)⁻¹ := by
          rw [commutatorElement_def, commutatorElement_def]; group
        rw [heq]
        exact hMconj x⁻¹ (X.inv_mem hxX) _ (M.inv_mem ihx)
  -- the generators satisfy the property in the first variable as well
  have hbase : ∀ a ∈ (N : Set G') ∪ {u, v}, ∀ b ∈ X, ⁅a, b⁆ ∈ M := by
    rintro a (haN | ha) b hbX
    · exact Subgroup.mem_sup_left (hNX (Subgroup.commutator_mem_commutator haN hbX))
    · have haX : a ∈ X := by rcases ha with rfl | rfl; exacts [huX, hvX]
      refine hright a haX ?_ b hbX
      rintro y (hyN | hy)
      · have h1 : ⁅y, a⁆ ∈ Z :=
          hNX (Subgroup.commutator_mem_commutator hyN haX)
        have h2 : ⁅a, y⁆ = ⁅y, a⁆⁻¹ := by
          rw [commutatorElement_def, commutatorElement_def]; group
        rw [h2]
        exact Subgroup.mem_sup_left (Subgroup.inv_mem _ h1)
      · have hself : ∀ w : G', ⁅w, w⁆ ∈ M := by
          intro w
          rw [show ⁅w, w⁆ = 1 by rw [commutatorElement_def]; group]
          exact M.one_mem
        have hcomm_uv : ⁅u, v⁆ ∈ M :=
          Subgroup.mem_sup_right (Subgroup.mem_zpowers _)
        have hcomm_vu : ⁅v, u⁆ ∈ M := by
          have h2 : ⁅v, u⁆ = c⁻¹ := by
            rw [hc_def, commutatorElement_def, commutatorElement_def]; group
          rw [h2]
          exact Subgroup.mem_sup_right (Subgroup.inv_mem _ (Subgroup.mem_zpowers _))
        rcases ha with rfl | rfl <;> rcases hy with rfl | rfl
        · exact hself _
        · exact hcomm_uv
        · exact hcomm_vu
        · exact hself _
  -- and then to all of `X` in the first variable
  refine Subgroup.commutator_le.mpr fun a ha b hb => ?_
  have hall : ∀ a ∈ X, ∀ b ∈ X, ⁅a, b⁆ ∈ M := by
    intro a haX
    rw [← hgen] at haX
    induction haX using Subgroup.closure_induction with
    | mem y hy => exact hbase y hy
    | one =>
        intro b _
        rw [show ⁅(1 : G'), b⁆ = 1 by rw [commutatorElement_def]; group]
        exact M.one_mem
    | mul x y hx hy ihx ihy =>
        intro b hbX
        have hxX : x ∈ X := by rw [← hgen]; exact hx
        have heq : ⁅x * y, b⁆ = (x * ⁅y, b⁆ * x⁻¹) * ⁅x, b⁆ := by
          rw [commutatorElement_def, commutatorElement_def, commutatorElement_def]
          group
        rw [heq]
        exact M.mul_mem (hMconj x hxX _ (ihy b hbX)) (ihx b hbX)
    | inv x hx ihx =>
        intro b hbX
        have hxX : x ∈ X := by rw [← hgen]; exact hx
        have heq : ⁅x⁻¹, b⁆ = x⁻¹ * ⁅x, b⁆⁻¹ * (x⁻¹)⁻¹ := by
          rw [commutatorElement_def, commutatorElement_def]; group
        rw [heq]
        exact hMconj x⁻¹ (X.inv_mem hxX) _ (M.inv_mem (ihx b hbX))
  exact hall a ha b hb

/-- For an endomorphism of a finite group, the index of the range equals the size of the
kernel. -/
theorem index_range_eq_card_ker {A : Type*} [Group A] [Finite A] (φ : A →* A) :
    φ.range.index = Nat.card ↥φ.ker := by
  have h1 := φ.range.card_mul_index
  have h2 := φ.ker.card_mul_index
  rw [Subgroup.index_ker] at h2
  have hpos : 0 < Nat.card ↥φ.range := Nat.card_pos
  have h3 : Nat.card ↥φ.range * φ.range.index
      = Nat.card ↥φ.range * Nat.card ↥φ.ker := by
    rw [h1, ← h2]; ring
  exact Nat.eq_of_mul_eq_mul_left hpos h3

/-- If `F` is normalized by `X` and contains all commutators of a generating set of `X`,
then `⁅X, X⁆ ≤ F`. -/
theorem commutator_le_of_generators {X F : Subgroup G'} {T : Set G'}
    (hgen : Subgroup.closure T = X)
    (hFconj : ∀ x ∈ X, ∀ f ∈ F, x * f * x⁻¹ ∈ F)
    (hbase : ∀ a ∈ T, ∀ b ∈ T, ⁅a, b⁆ ∈ F) :
    ⁅X, X⁆ ≤ F := by
  classical
  have hright : ∀ a : G', (∀ b ∈ T, ⁅a, b⁆ ∈ F) → ∀ b ∈ X, ⁅a, b⁆ ∈ F := by
    intro a hb b hbX
    rw [← hgen] at hbX
    induction hbX using Subgroup.closure_induction with
    | mem y hy => exact hb y hy
    | one =>
        rw [show ⁅a, (1 : G')⁆ = 1 by rw [commutatorElement_def]; group]
        exact F.one_mem
    | mul x y hx _ ihx ihy =>
        have hxX : x ∈ X := by rw [← hgen]; exact hx
        have heq : ⁅a, x * y⁆ = ⁅a, x⁆ * (x * ⁅a, y⁆ * x⁻¹) := by
          rw [commutatorElement_def, commutatorElement_def, commutatorElement_def]
          group
        rw [heq]
        exact F.mul_mem ihx (hFconj x hxX _ ihy)
    | inv x hx ihx =>
        have hxX : x ∈ X := by rw [← hgen]; exact hx
        have heq : ⁅a, x⁻¹⁆ = x⁻¹ * ⁅a, x⁆⁻¹ * (x⁻¹)⁻¹ := by
          rw [commutatorElement_def, commutatorElement_def]; group
        rw [heq]
        exact hFconj x⁻¹ (X.inv_mem hxX) _ (F.inv_mem ihx)
  refine Subgroup.commutator_le.mpr fun a ha b hb => ?_
  have hall : ∀ a ∈ X, ∀ b ∈ X, ⁅a, b⁆ ∈ F := by
    intro a haX
    rw [← hgen] at haX
    induction haX using Subgroup.closure_induction with
    | mem y hy => exact hright y (fun b hbT => hbase y hy b hbT)
    | one =>
        intro b _
        rw [show ⁅(1 : G'), b⁆ = 1 by rw [commutatorElement_def]; group]
        exact F.one_mem
    | mul x y hx _ ihx ihy =>
        intro b hbX
        have hxX : x ∈ X := by rw [← hgen]; exact hx
        have heq : ⁅x * y, b⁆ = (x * ⁅y, b⁆ * x⁻¹) * ⁅x, b⁆ := by
          rw [commutatorElement_def, commutatorElement_def, commutatorElement_def]
          group
        rw [heq]
        exact F.mul_mem (hFconj x hxX _ (ihy b hbX)) (ihx b hbX)
    | inv x hx ihx =>
        intro b hbX
        have hxX : x ∈ X := by rw [← hgen]; exact hx
        have heq : ⁅x⁻¹, b⁆ = x⁻¹ * ⁅x, b⁆⁻¹ * (x⁻¹)⁻¹ := by
          rw [commutatorElement_def, commutatorElement_def]; group
        rw [heq]
        exact hFconj x⁻¹ (X.inv_mem hxX) _ (F.inv_mem (ihx b hbX))
  exact hall a ha b hb

end GenericStronglyReal

namespace FirstCaseHypothesis

universe uG uΩ

variable {G : Type uG} {Ω : Type uΩ} [Group G] [MulAction G Ω] [Finite G]
  (fc : FirstCaseHypothesis G Ω)
  {F : Type uG} [NearFields.NearField F]
  (model : letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
    NearFields.AffineNearFieldModel fc.rankOneQuotient F)

include model in
/-- **The strongly real elements of `Z₁PΣ` are exactly those of `Z₁`** ((16), p. 114):
a strongly real `y ∈ Z₁PΣ` generates a subgroup of order `3` all of whose elements are
strongly real (the inverse of a strongly real element is strongly real), so that
subgroup is `Z₁`. -/
theorem mem_zpowers_of_isStronglyReal_of_mem
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) {y : G}
    (hy : y ∈ (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
    (hsr : IsStronglyReal y) :
    y ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  rcases eq_or_ne y 1 with rfl | hy1
  · exact Subgroup.one_mem _
  -- `y` has order `3`
  have hZSP_LV : ((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
      ≤ fc.nonsplitTorus ⊔ fc.toHypothesis.V :=
    sup_le (sup_le (fc.zpowers_le_nonsplitTorus.trans le_sup_left)
      ((inf_le_left.trans fc.toHypothesis.W_le_V).trans le_sup_right))
      (fc.P_le_V.trans le_sup_right)
  have hy3 : y ^ 3 = 1 :=
    (fc.pow_three_eq_one_iff_mem_zpowers_sup_sigma_sup_P model ind hB2
      (hZSP_LV hy)).mpr hy
  have hyord : orderOf y = 3 := by
    have h := orderOf_dvd_of_pow_eq_one hy3
    rcases (Nat.dvd_prime (by norm_num)).mp h with h1 | h3
    · exact absurd (orderOf_eq_one_iff.mp h1) hy1
    · exact h3
  have hXeq := fc.eq_zpowers_of_card_three_of_forall_isStronglyReal model ind hB2
    (X := Subgroup.zpowers y) (Subgroup.zpowers_le.mpr hy)
    (by rw [Nat.card_zpowers, hyord])
    (by
      intro z hz hz1
      rcases eq_one_or_eq_or_eq_inv_of_mem_zpowers_of_orderOf_eq_three hyord hz
        with h | h | h
      · exact absurd h hz1
      · rw [h]; exact hsr
      · rw [h]; exact isStronglyReal_inv hsr)
  rw [← hXeq]
  exact Subgroup.mem_zpowers _

include model in
/-- **`Z₁PΣ` is weakly closed in `R₂`, once `Z₁^x ≤ LV`** ((17), p. 114): then
`Z₁^x ≤ Ω₁(LV) = Z₁PΣ` consists of strongly real elements, so `Z₁^x = Z₁` by (16) and
`x ∈ N_G(Z₁) = N_G(Z₁PΣ)`. -/
theorem map_conj_eq_of_map_conj_zpowers_le
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) (S : Sylow 3 G)
    (hR₁S : fc.sylowThreeNormalizerRSigma model ≤ (S : Subgroup G)) {x : G}
    (hxLV : (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)).map (MulAut.conj x).toMonoidHom
      ≤ fc.nonsplitTorus ⊔ fc.toHypothesis.V) :
    (((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
          : Subgroup G).map (MulAut.conj x).toMonoidHom
      = (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  obtain ⟨-, hp3, -, -, -, -⟩ := fc.step_twelve model ind hB2
  have hstord : orderOf (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) = 3 := by
    rw [fc.orderOf_st_eq_char model, fc.char_eq_p model hB2, hp3]
  -- `Z₁^x` lies in `Ω₁(LV) = Z₁PΣ`
  have hle : (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)).map (MulAut.conj x).toMonoidHom
      ≤ (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P := by
    intro y hy
    refine (fc.pow_three_eq_one_iff_mem_zpowers_sup_sigma_sup_P model ind hB2
      (hxLV hy)).mp ?_
    obtain ⟨z, hz, rfl⟩ := hy
    have hz3 : z ^ 3 = 1 := by
      have h := Subgroup.orderOf_dvd_natCard _ hz
      rw [Nat.card_zpowers, hstord] at h
      exact orderOf_dvd_iff_pow_eq_one.mp h
    change (x * z * x⁻¹) ^ 3 = 1
    rw [conj_pow, hz3]
    group
  -- `Z₁^x = Z₁` by the uniqueness of the strongly real line
  have hZeq : (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)).map (MulAut.conj x).toMonoidHom
      = Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) := by
    refine fc.eq_zpowers_of_card_three_of_forall_isStronglyReal model ind hB2 hle ?_ ?_
    · rw [Subgroup.card_map_of_injective, Nat.card_zpowers, hstord]
      exact fun a b h => by
        simpa using congrArg (fun y => (MulAut.conj x).symm y) h
    · rintro y ⟨z, hz, rfl⟩ -
      exact isStronglyReal_conj
        (fc.forall_isStronglyReal_mem_zpowers_st model ind hB2 hz) x
  -- hence `x` normalizes `Z₁`, so also `Z₁PΣ`
  have hxN : x ∈ Subgroup.normalizer ((Subgroup.zpowers
      (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t) : Subgroup G)
        : Set G) := Subgroup.mem_normalizer_iff_map_conj_eq.mpr hZeq
  rw [fc.normalizer_zpowers_eq_normalizer_zpowers_sup_sigma_sup_P model ind hB2
    S hR₁S] at hxN
  exact Subgroup.mem_normalizer_iff_map_conj_eq.mp hxN

include model in
/-- **`Z₁^x ≤ LV`** ((17), p. 114, first paragraph), for `x` with `(Z₁PΣ)^x ≤ R₂`.

Otherwise `R₂ = LV·Z₁^x`, and `A = (Z₁PΣ)^x ⊓ LV` has order `9` and lies in
`Ω₁(LV) = Z₁PΣ`.  Its nonidentity elements are not strongly real: the strongly real
elements of `(Z₁PΣ)^x` are those of `Z₁^x`, which meets `LV` trivially in this case.
Hence `A ⊓ Z₁ = 1` and `Z₁A = Z₁PΣ`, so `Z₁^x` — which centralizes the abelian
`(Z₁PΣ)^x ⊇ A` and the central `Z₁ = Z(R₂)` — centralizes `Z₁PΣ`.  Then `Z₁Σ = Z(LV)`
is centralized by `LV` and by `Z₁^x`, i.e. `Z₁Σ ≤ Z(R₂) = Z₁`, contradicting
`|Z₁Σ| = 9`. -/
theorem map_conj_zpowers_le_sup_nonsplitTorus_V
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) (S : Sylow 3 G)
    (hR₁S : fc.sylowThreeNormalizerRSigma model ≤ (S : Subgroup G)) {x : G}
    (hx : (((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
            * fc.toHypothesis.t)
          ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
            : Subgroup G).map (MulAut.conj x).toMonoidHom ≤ (S : Subgroup G)) :
    (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)).map (MulAut.conj x).toMonoidHom
      ≤ fc.nonsplitTorus ⊔ fc.toHypothesis.V := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  obtain ⟨-, hp3, -, -, -, -⟩ := fc.step_twelve model ind hB2
  have hstord : orderOf (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) = 3 := by
    rw [fc.orderOf_st_eq_char model, fc.char_eq_p model hB2, hp3]
  have hZ₁card : Nat.card ↥(Subgroup.zpowers
      (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t)) = 3 := by
    rw [Nat.card_zpowers, hstord]
  have hconjInj : Function.Injective (MulAut.conj x).toMonoidHom := fun a b h => by
    simpa using congrArg (fun y => (MulAut.conj x).symm y) h
  set B : Subgroup G := (((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
        : Subgroup G).map (MulAut.conj x).toMonoidHom with hB_def
  set Zx : Subgroup G := (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t)).map (MulAut.conj x).toMonoidHom with hZx_def
  have hZxB : Zx ≤ B := Subgroup.map_mono (le_sup_left.trans le_sup_left)
  have hBcard : Nat.card ↥B = 27 := by
    rw [hB_def, Subgroup.card_map_of_injective hconjInj]
    exact fc.card_zpowers_sup_sigma_sup_P model ind hB2
  have hZxcard : Nat.card ↥Zx = 3 := by
    rw [hZx_def, Subgroup.card_map_of_injective hconjInj, hZ₁card]
  by_contra hcon
  have hBnotLV : ¬ B ≤ fc.nonsplitTorus ⊔ fc.toHypothesis.V :=
    fun h => hcon (hZxB.trans h)
  -- `A = B ⊓ LV` has order `9`
  have hBS : B ≤ (S : Subgroup G) := hx
  have hLVS := fc.sup_nonsplitTorus_V_le_sylow model ind hB2 S hR₁S
  have hidx := fc.index_subgroupOf_sup_nonsplitTorus_V_eq_three model ind hB2 S hR₁S
  have hminFac : (Nat.card ↥(S : Subgroup G)).minFac = 3 := by
    rcases fc.card_sylow_eq model ind hB2 S with h | h <;> rw [h] <;> norm_num
  haveI hLVnorm : ((fc.nonsplitTorus ⊔ fc.toHypothesis.V).subgroupOf
      (S : Subgroup G)).Normal :=
    Subgroup.normal_of_index_eq_minFac_card (by rw [hidx, hminFac])
  have hrel : (fc.nonsplitTorus ⊔ fc.toHypothesis.V).relIndex B ∣ 3 := by
    have h := Subgroup.relIndex_dvd_index_of_normal
      (H := (fc.nonsplitTorus ⊔ fc.toHypothesis.V).subgroupOf (S : Subgroup G))
      (K := B.subgroupOf (S : Subgroup G))
    rw [Subgroup.relIndex_subgroupOf hBS, hidx] at h
    exact h
  have hmul : Nat.card ↥((fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊓ B)
      * (fc.nonsplitTorus ⊔ fc.toHypothesis.V).relIndex B = Nat.card ↥B := by
    have hcard1 : Nat.card ↥(((fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊓ B).subgroupOf B)
        = Nat.card ↥((fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊓ B) :=
      Nat.card_congr (Subgroup.subgroupOfEquivOfLe inf_le_right).toEquiv
    have h := (((fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊓ B).subgroupOf B).card_mul_index
    rwa [hcard1, Subgroup.inf_subgroupOf_right] at h
  have hAcard : Nat.card ↥((fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊓ B) = 9 := by
    rw [hBcard] at hmul
    rcases (Nat.dvd_prime (by norm_num)).mp hrel with h1 | h3
    · exfalso
      rw [h1, mul_one] at hmul
      exact hBnotLV (le_trans (le_of_eq (Subgroup.eq_of_le_of_card_ge inf_le_right
        (by rw [hmul, hBcard])).symm) inf_le_left)
    · rw [h3] at hmul; omega
  -- `A ≤ Z₁ΣP`
  have hAZSP : (fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊓ B
      ≤ (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P := by
    intro y hy
    refine (fc.pow_three_eq_one_iff_mem_zpowers_sup_sigma_sup_P model ind hB2
      hy.1).mp ?_
    obtain ⟨z, hz, hzy⟩ := hy.2
    have hz3 : z ^ 3 = 1 :=
      (fc.pow_three_eq_one_iff_mem_zpowers_sup_sigma_sup_P model ind hB2
        (by
          refine sup_le (sup_le (fc.zpowers_le_nonsplitTorus.trans le_sup_left)
            ((inf_le_left.trans fc.toHypothesis.W_le_V).trans le_sup_right))
            (fc.P_le_V.trans le_sup_right) hz)).mpr hz
    have hyz : y = x * z * x⁻¹ := hzy.symm
    rw [hyz, conj_pow, hz3]
    group
  -- `A ⊓ Z₁ = 1`
  have hAZ₁ : ((fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊓ B)
      ⊓ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) = ⊥ := by
    rw [eq_bot_iff]
    intro y hy
    rw [Subgroup.mem_bot]
    by_contra hy1
    -- `y ∈ Z₁^#` is strongly real and lies in `B`, hence in `Z₁^x`
    refine hcon ?_
    have hyB : y ∈ B := hy.1.2
    have hysr : IsStronglyReal y :=
      fc.forall_isStronglyReal_mem_zpowers_st model ind hB2 hy.2
    have hyZx : y ∈ Zx := by
      obtain ⟨w, hwB, hwy⟩ : ∃ w ∈ ((Subgroup.zpowers
          (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t)
          ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P),
          x * w * x⁻¹ = y := by
        obtain ⟨w, hw, hwy⟩ := hyB
        exact ⟨w, hw, hwy⟩
      have hwsr : IsStronglyReal w := by
        have h := isStronglyReal_conj hysr x⁻¹
        rwa [show x⁻¹ * y * x⁻¹⁻¹ = w by rw [← hwy]; group] at h
      have hwZ := fc.mem_zpowers_of_isStronglyReal_of_mem model ind hB2 hwB hwsr
      exact ⟨w, hwZ, hwy⟩
    -- so `Z₁^x = ⟨y⟩ = Z₁ ≤ LV`
    have hyord : orderOf y = 3 := by
      have h := Subgroup.orderOf_dvd_natCard _ hy.2
      rw [hZ₁card] at h
      rcases (Nat.dvd_prime (by norm_num)).mp h with h1 | h3
      · exact absurd (orderOf_eq_one_iff.mp h1) hy1
      · exact h3
    have h1 : Subgroup.zpowers y = Zx :=
      Subgroup.eq_of_le_of_card_ge (Subgroup.zpowers_le.mpr hyZx)
        (by rw [hZxcard, Nat.card_zpowers, hyord])
    rw [← h1]
    exact Subgroup.zpowers_le.mpr
      (Subgroup.mem_sup_left (fc.zpowers_le_nonsplitTorus hy.2))
  -- `Z₁A = Z₁ΣP`
  have hprod : Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ ((fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊓ B)
      = (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P := by
    refine Subgroup.eq_of_le_of_card_ge
      (sup_le (le_sup_left.trans le_sup_left) hAZSP) ?_
    rw [card_sup_eq_mul_of_commute
        (fun a ha b hb => fc.mul_comm_of_mem_zpowers_sup_sigma_sup_P model ind hB2
          (Subgroup.mem_sup_left (Subgroup.mem_sup_left ha)) (hAZSP hb))
        (by rw [← hAZ₁]; exact inf_comm _ _),
      hZ₁card, hAcard, fc.card_zpowers_sup_sigma_sup_P model ind hB2]
  -- `B` is abelian, being a conjugate of `Z₁ΣP`
  have hBcomm : ∀ a ∈ B, ∀ b ∈ B, a * b = b * a := by
    rintro a ⟨c, hc, rfl⟩ b ⟨d, hd, rfl⟩
    have hcd := fc.mul_comm_of_mem_zpowers_sup_sigma_sup_P model ind hB2 hc hd
    change (x * c * x⁻¹) * (x * d * x⁻¹) = (x * d * x⁻¹) * (x * c * x⁻¹)
    calc (x * c * x⁻¹) * (x * d * x⁻¹) = x * (c * d) * x⁻¹ := by group
      _ = x * (d * c) * x⁻¹ := by rw [hcd]
      _ = (x * d * x⁻¹) * (x * c * x⁻¹) := by group
  -- `Z₁ = Z(R₂)` is central in `R₂`
  have hZ₁cen : ∀ z ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t), ∀ u ∈ (S : Subgroup G), z * u = u * z := by
    intro z hz u hu
    have hmem : z ∈ (S : Subgroup G) ⊓ Subgroup.centralizer
        (((S : Subgroup G)) : Set G) := by
      rw [fc.inf_centralizer_sylow_eq_zpowers model ind hB2 S hR₁S]
      exact hz
    exact (Subgroup.mem_centralizer_iff.mp hmem.2 u hu).symm
  -- `Z₁^x` centralizes `Z₁ΣP = Z₁A`
  have hZxcen : ∀ u ∈ Zx, ∀ v ∈ ((Subgroup.zpowers
        (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P),
      u * v = v * u := by
    intro u hu v hv
    rw [← hprod] at hv
    have hcoe := coe_sup_eq_mul_of_commute
      (fun _ (ha : _ ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)) _
        (hb : _ ∈ (fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊓ B) =>
        fc.mul_comm_of_mem_zpowers_sup_sigma_sup_P model ind hB2
          (Subgroup.mem_sup_left (Subgroup.mem_sup_left ha)) (hAZSP hb))
    have hv' : v ∈ ((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) : Subgroup G) : Set G)
        * (((fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊓ B : Subgroup G) : Set G) := by
      rw [← hcoe]; exact hv
    obtain ⟨z, hz, a, ha, hza⟩ := hv'
    have hzav : z * a = v := hza
    have h1 : u * z = z * u := (hZ₁cen z hz u (hBS (hZxB hu))).symm
    have h2 : u * a = a * u := hBcomm u (hZxB hu) a ha.2
    calc u * v = u * (z * a) := by rw [hzav]
      _ = z * (u * a) := by rw [← mul_assoc, h1, mul_assoc]
      _ = z * (a * u) := by rw [h2]
      _ = v * u := by rw [← mul_assoc, hzav]
  -- `R₂ = LV·Z₁^x`
  have hLVcardS : Nat.card ↥(fc.nonsplitTorus ⊔ fc.toHypothesis.V) * 3
      = Nat.card ↥(S : Subgroup G) := by
    have h := ((fc.nonsplitTorus ⊔ fc.toHypothesis.V).subgroupOf
      (S : Subgroup G)).card_mul_index
    rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe hLVS).toEquiv, hidx] at h
    exact h
  have hR₂eq : (fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊔ Zx = (S : Subgroup G) := by
    refine Subgroup.eq_of_le_of_card_ge (sup_le hLVS (hZxB.trans hBS)) ?_
    obtain ⟨m, hm⟩ := Subgroup.card_dvd_of_le
      (le_sup_left : fc.nonsplitTorus ⊔ fc.toHypothesis.V ≤ _ ⊔ Zx)
    have hdvd : Nat.card ↥((fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊔ Zx)
        ∣ Nat.card ↥(S : Subgroup G) :=
      Subgroup.card_dvd_of_le (sup_le hLVS (hZxB.trans hBS))
    have hpos : 0 < Nat.card ↥(fc.nonsplitTorus ⊔ fc.toHypothesis.V) := Nat.card_pos
    have hm3 : m ∣ 3 := by
      rw [hm, ← hLVcardS] at hdvd
      exact (Nat.mul_dvd_mul_iff_left hpos).mp hdvd
    rcases (Nat.dvd_prime (by norm_num)).mp hm3 with h1 | h3
    · exfalso
      refine hcon (le_trans ?_ (le_refl _))
      have heq : (fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊔ Zx
          = fc.nonsplitTorus ⊔ fc.toHypothesis.V :=
        (Subgroup.eq_of_le_of_card_ge le_sup_left (by rw [hm, h1, mul_one])).symm
      rw [← heq]
      exact le_sup_right
    · rw [hm, h3, hLVcardS]
  -- `Z₁Σ ≤ Z(R₂) = Z₁`, contradicting `|Z₁Σ| = 9`
  have hm : Nat.card F = fc.p ^ 2 := by
    obtain ⟨-, -, hF9, -, -, -⟩ := fc.step_twelve model ind hB2
    rw [hF9, hp3]; norm_num
  have hZ₁R : Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) ≤ fc.invImageF model :=
    (fc.zpowers_distinguishedInvolution_mul_t_le_sInvertedT model ind hB2 hm).trans
      (fc.sInvertedT_spec model ind hB2 hm).1
  have hZSP_S : ((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
      ≤ (S : Subgroup G) := by
    refine le_trans (le_trans ?_ (fc.sup_le_sylowThreeNormalizerRSigma model ind hB2))
      hR₁S
    exact sup_le (sup_le (hZ₁R.trans le_sup_left) le_sup_right)
      ((fc.P_le_invImageF model).trans le_sup_left)
  have hZSle' : (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)))
      ≤ (S : Subgroup G)
        ⊓ Subgroup.centralizer (((S : Subgroup G)) : Set G) := by
    intro y hy
    refine ⟨hZSP_S (Subgroup.mem_sup_left hy), ?_⟩
    rw [← hR₂eq, centralizer_sup]
    refine ⟨?_, ?_⟩
    · have heq := fc.inf_centralizer_sup_nonsplitTorus_V_eq model ind hB2
      rw [← heq] at hy
      exact hy.2
    · refine Subgroup.mem_centralizer_iff.mpr fun u hu => ?_
      exact hZxcen u hu y (Subgroup.mem_sup_left hy)
  have hZSle : (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)))
      ≤ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) :=
    le_trans hZSle'
      (le_of_eq (fc.inf_centralizer_sylow_eq_zpowers model ind hB2 S hR₁S))
  have hcard9 := fc.card_zpowers_sup_sigma model ind hB2
  have hdvd := Subgroup.card_dvd_of_le hZSle
  rw [hcard9, hZ₁card] at hdvd
  exact absurd (Nat.le_of_dvd (by norm_num) hdvd) (by norm_num)

include model in
/-- **`Z₁PΣ` is weakly closed in `R₂`** ((17), p. 114): every `G`-conjugate of `Z₁PΣ`
that is contained in the Sylow `3`-subgroup `R₂` equals `Z₁PΣ`.

This is the hypothesis of the Hall–Wielandt theorem, which then yields
`G/O³(G) ≅ N_G(Z₁PΣ)/O³(N_G(Z₁PΣ)) = R₂⟨s⟩/O³(R₂⟨s⟩)` (`Z₁PΣ` is abelian and
`p = 3 > 2`). -/
theorem map_conj_eq_of_le_sylow
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) (S : Sylow 3 G)
    (hR₁S : fc.sylowThreeNormalizerRSigma model ≤ (S : Subgroup G)) {x : G}
    (hx : (((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
            * fc.toHypothesis.t)
          ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
            : Subgroup G).map (MulAut.conj x).toMonoidHom ≤ (S : Subgroup G)) :
    (((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
          : Subgroup G).map (MulAut.conj x).toMonoidHom
      = (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P :=
  fc.map_conj_eq_of_map_conj_zpowers_le model ind hB2 S hR₁S
    (fc.map_conj_zpowers_le_sup_nonsplitTorus_V model ind hB2 S hR₁S hx)

include model in
/-- **`N_G(R₂) = R₂⟨s⟩ = N_G(Z₁PΣ)`** ((17), p. 114): `R₂ = C_G(Z₁)` and `Z(R₂) = Z₁`
by (14), so normalizing `R₂` is the same as normalizing `Z₁`. -/
theorem normalizer_sylow_eq
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) (S : Sylow 3 G)
    (hR₁S : fc.sylowThreeNormalizerRSigma model ≤ (S : Subgroup G)) :
    Subgroup.normalizer (((S : Subgroup G)) : Set G)
      = (S : Subgroup G)
        ⊔ Subgroup.zpowers fc.toHypothesis.distinguishedInvolution := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  have hSeq := fc.sylow_eq_centralizer_zpowers model ind hB2 S hR₁S
  have hZeq := fc.inf_centralizer_sylow_eq_zpowers model ind hB2 S hR₁S
  rw [← fc.normalizer_zpowers_eq_sylow_sup_zpowers model ind hB2 S hR₁S]
  refine le_antisymm (fun g hg => ?_) (fun g hg => ?_)
  · -- normalizing `R₂` forces normalizing `Z(R₂) = Z₁`
    rw [Subgroup.mem_set_normalizer_iff] at hg
    rw [Subgroup.mem_set_normalizer_iff]
    intro y
    have hcen : ∀ z : G, z ∈ Subgroup.centralizer (((S : Subgroup G)) : Set G)
        ↔ g * z * g⁻¹ ∈ Subgroup.centralizer (((S : Subgroup G)) : Set G) := by
      intro z
      refine ⟨fun hz => Subgroup.mem_centralizer_iff.mpr fun u hu => ?_,
        fun hz => Subgroup.mem_centralizer_iff.mpr fun u hu => ?_⟩
      · have hu' : g⁻¹ * u * g ∈ (S : Subgroup G) := by
          refine (hg (g⁻¹ * u * g)).mpr ?_
          rw [show g * (g⁻¹ * u * g) * g⁻¹ = u by group]
          exact hu
        have h := Subgroup.mem_centralizer_iff.mp hz _ hu'
        calc u * (g * z * g⁻¹) = g * ((g⁻¹ * u * g) * z) * g⁻¹ := by group
          _ = g * (z * (g⁻¹ * u * g)) * g⁻¹ := by rw [h]
          _ = (g * z * g⁻¹) * u := by group
      · have hu' : g * u * g⁻¹ ∈ (S : Subgroup G) := (hg u).mp hu
        have h := Subgroup.mem_centralizer_iff.mp hz _ hu'
        have h2 : (g * u * g⁻¹) * (g * z * g⁻¹) = (g * z * g⁻¹) * (g * u * g⁻¹) := h
        have h3 : g * (u * z) * g⁻¹ = g * (z * u) * g⁻¹ := by
          calc g * (u * z) * g⁻¹ = (g * u * g⁻¹) * (g * z * g⁻¹) := by group
            _ = (g * z * g⁻¹) * (g * u * g⁻¹) := h2
            _ = g * (z * u) * g⁻¹ := by group
        exact mul_left_cancel (mul_right_cancel h3)
    rw [← hZeq]
    constructor
    · rintro ⟨hy1, hy2⟩
      exact ⟨(hg y).mp hy1, (hcen y).mp hy2⟩
    · rintro ⟨hy1, hy2⟩
      exact ⟨(hg y).mpr hy1, (hcen y).mpr hy2⟩
  · -- normalizing `Z₁` forces normalizing `C_G(Z₁) = R₂`
    rw [Subgroup.mem_set_normalizer_iff] at hg
    rw [Subgroup.mem_set_normalizer_iff, ← hSeq]
    intro y
    refine ⟨fun hy => Subgroup.mem_centralizer_iff.mpr fun u hu => ?_,
      fun hy => Subgroup.mem_centralizer_iff.mpr fun u hu => ?_⟩
    · have hu' : g⁻¹ * u * g ∈ Subgroup.zpowers
          (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t) := by
        refine (hg (g⁻¹ * u * g)).mpr ?_
        rw [show g * (g⁻¹ * u * g) * g⁻¹ = u by group]
        exact hu
      have h := Subgroup.mem_centralizer_iff.mp hy _ hu'
      calc u * (g * y * g⁻¹) = g * ((g⁻¹ * u * g) * y) * g⁻¹ := by group
        _ = g * (y * (g⁻¹ * u * g)) * g⁻¹ := by rw [h]
        _ = (g * y * g⁻¹) * u := by group
    · have hu' : g * u * g⁻¹ ∈ Subgroup.zpowers
        (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t) := (hg u).mp hu
      have h : (g * u * g⁻¹) * (g * y * g⁻¹) = (g * y * g⁻¹) * (g * u * g⁻¹) :=
        Subgroup.mem_centralizer_iff.mp hy _ hu'
      have h3 : g * (u * y) * g⁻¹ = g * (y * u) * g⁻¹ := by
        calc g * (u * y) * g⁻¹ = (g * u * g⁻¹) * (g * y * g⁻¹) := by group
          _ = (g * y * g⁻¹) * (g * u * g⁻¹) := h
          _ = g * (y * u) * g⁻¹ := by group
      exact mul_left_cancel (mul_right_cancel h3)

end FirstCaseHypothesis

end OddOrder.Peterfalvi.Appendices.Suzuki
