/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Peterfalvi.Appendices.Suzuki.FirstCase.StepSixteen

/-!
# Peterfalvi Part II, Ch. II, step (17): the conclusion

T. Peterfalvi, *Character Theory for the Odd Order Theorem* (LMS LNS 272,
2000), Part II, Ch. II, (17), p. 114.

The final contradiction runs as follows.  If `x ∈ G` is such that `(Z₁PΣ)^x ⊆ R₂`
then `Z₁^x ⊆ LV` (otherwise `R₂ = LV ⋊ Z₁^x` and one finds `Z₁Σ ⊆ Z(R₂)`, contrary
to (14)), and then `Z₁^x ⊆ Ω₁(LV) = Z₁PΣ`, so `Z₁^x = Z₁` by the uniqueness of the
strongly real line (16) and `x ∈ N_G(Z₁) = N_G(Z₁PΣ)`.  Thus `Z₁PΣ` is an abelian
subgroup weakly closed in `R₂`, and the Hall–Wielandt theorem gives
`G/O³(G) ≅ R₂⟨s⟩/O³(R₂⟨s⟩)`; the structure of `R̄₁ = R₁/Z₁` then produces a quotient
of order `3`, contradicting hypothesis (B2).

This file develops the weak-closure half.  (The Hall–Wielandt input itself is the one
piece of genuinely new shared infrastructure; see issue 2053.)
-/

set_option autoImplicit false

open scoped Pointwise commutatorElement

namespace OddOrder.Peterfalvi.Appendices.Suzuki

section GenericStronglyReal

variable {G' : Type*} [Group G']

/-- The inverse of a strongly real element is strongly real. -/
theorem isStronglyReal_inv {x : G'} (hx : IsStronglyReal x) : IsStronglyReal x⁻¹ := by
  obtain ⟨u, ⟨hu2, hu1⟩, v, ⟨hv2, hv1⟩, rfl⟩ := hx
  have huinv : u⁻¹ = u := inv_eq_of_mul_eq_one_right (by rw [← pow_two]; exact hu2)
  have hvinv : v⁻¹ = v := inv_eq_of_mul_eq_one_right (by rw [← pow_two]; exact hv2)
  exact ⟨v, ⟨hv2, hv1⟩, u, ⟨hu2, hu1⟩, by rw [mul_inv_rev, huinv, hvinv]⟩

/-- A normal subgroup of prime index `p` forces `p ∣ |G^{ab}|`. -/
theorem dvd_card_abelianization_of_index_eq_prime [Finite G'] {H : Subgroup G'}
    [H.Normal] {p : ℕ} (hp : p.Prime) (hidx : H.index = p) :
    p ∣ Nat.card (Abelianization G') := by
  classical
  haveI : Fact p.Prime := ⟨hp⟩
  haveI hcyc : IsCyclic (G' ⧸ H) :=
    isCyclic_of_prime_card (α := G' ⧸ H) (p := p)
      (by rw [← Subgroup.index_eq_card, hidx])
  haveI : IsMulCommutative (G' ⧸ H) := IsCyclic.isMulCommutative
  have hcomm : commutator G' ≤ H := by
    rw [commutator_def]
    refine Subgroup.commutator_le.mpr fun a _ b _ => ?_
    rw [← QuotientGroup.eq_one_iff]
    have h := ‹IsMulCommutative (G' ⧸ H)›.is_comm.comm
      (QuotientGroup.mk (s := H) a) (QuotientGroup.mk (s := H) b)
    calc QuotientGroup.mk (s := H) ⁅a, b⁆
        = ⁅QuotientGroup.mk (s := H) a, QuotientGroup.mk (s := H) b⁆ := by
          simp [commutatorElement_def, QuotientGroup.mk_mul, QuotientGroup.mk_inv]
      _ = 1 := commutatorElement_eq_one_iff_commute.mpr h
  let f : Abelianization G' →* G' ⧸ H :=
    QuotientGroup.map (commutator G') H (MonoidHom.id G') (by simpa using hcomm)
  have hsurj : Function.Surjective f := by
    intro y
    obtain ⟨g, rfl⟩ := QuotientGroup.mk_surjective (s := H) y
    exact ⟨Abelianization.of g, rfl⟩
  have hcard : Nat.card (G' ⧸ H) ∣ Nat.card (Abelianization G') := by
    obtain ⟨e⟩ : Nonempty ((Abelianization G' ⧸ f.ker) ≃* (G' ⧸ H)) :=
      ⟨QuotientGroup.quotientKerEquivOfSurjective f hsurj⟩
    rw [← Nat.card_congr e.toEquiv, ← Subgroup.index_eq_card]
    exact Subgroup.index_dvd_card _
  rwa [← Subgroup.index_eq_card, hidx] at hcard

/-- **Class-`2` commutator bound.**  Let `Z ≤ N ≤ X` with `Z` centralizing `X`,
`⁅N, X⁆ ≤ Z` and `⁅X, X⁆ ≤ N`, and suppose `X` is generated by `N` together with two
elements `u, v`.  Then `⁅X, X⁆ ≤ Z⟨⁅u,v⁆⟩`.

This is the group-theoretic content of "the commutator induces an alternating form on
the two-dimensional space `X/N`, so its image is at most one-dimensional". -/
theorem commutator_le_of_two_generators [Finite G'] {X N Z : Subgroup G'} {u v : G'}
    (hZcen : ∀ z ∈ Z, ∀ x ∈ X, z * x = x * z)
    (hNX : ⁅N, X⁆ ≤ Z) (hXX : ⁅X, X⁆ ≤ N) (huX : u ∈ X) (hvX : v ∈ X)
    (hgen : Subgroup.closure ((N : Set G') ∪ {u, v}) = X) :
    ⁅X, X⁆ ≤ Z ⊔ Subgroup.zpowers ⁅u, v⁆ := by
  classical
  set c : G' := ⁅u, v⁆ with hc_def
  set M : Subgroup G' := Z ⊔ Subgroup.zpowers c with hM_def
  have hcN : c ∈ N := hXX (Subgroup.commutator_mem_commutator huX hvX)
  -- `M` is normalized by every element of `X`
  have hMconj : ∀ x ∈ X, ∀ m ∈ M, x * m * x⁻¹ ∈ M := by
    intro x hx m hm
    have hsub : M ≤ Subgroup.comap (MulAut.conj x).toMonoidHom M := by
      refine sup_le (fun z hz => ?_) (Subgroup.zpowers_le.mpr ?_)
      · have : x * z * x⁻¹ = z := by rw [← hZcen z hz x hx]; group
        exact Subgroup.mem_sup_left (by change x * z * x⁻¹ ∈ Z; rw [this]; exact hz)
      · -- `x c x⁻¹ = ⁅x, c⁆ · c` with `⁅x, c⁆ ∈ Z`
        have hxc : ⁅x, c⁆ ∈ Z := by
          have h := Subgroup.commutator_mem_commutator hcN hx
          have h2 : ⁅c, x⁆ ∈ Z := hNX h
          have h3 : ⁅x, c⁆ = ⁅c, x⁆⁻¹ := by
            rw [commutatorElement_def, commutatorElement_def]; group
          rw [h3]
          exact Subgroup.inv_mem _ h2
        have heq : x * c * x⁻¹ = ⁅x, c⁆ * c := by
          rw [commutatorElement_def]; group
        change x * c * x⁻¹ ∈ M
        rw [heq]
        exact Subgroup.mul_mem _ (Subgroup.mem_sup_left hxc)
          (Subgroup.mem_sup_right (Subgroup.mem_zpowers _))
    exact hsub hm
  -- for fixed `a ∈ X`, the property `⁅a, ·⁆ ∈ M` passes from generators to all of `X`
  have hright : ∀ a ∈ X, (∀ b ∈ (N : Set G') ∪ {u, v}, ⁅a, b⁆ ∈ M) →
      ∀ b ∈ X, ⁅a, b⁆ ∈ M := by
    intro a _ hbase b hb
    rw [← hgen] at hb
    induction hb using Subgroup.closure_induction with
    | mem y hy => exact hbase y hy
    | one =>
        rw [show ⁅a, (1 : G')⁆ = 1 by rw [commutatorElement_def]; group]
        exact M.one_mem
    | mul x y hx hy ihx ihy =>
        have hxX : x ∈ X := by rw [← hgen]; exact hx
        have heq : ⁅a, x * y⁆ = ⁅a, x⁆ * (x * ⁅a, y⁆ * x⁻¹) := by
          rw [commutatorElement_def, commutatorElement_def, commutatorElement_def]
          group
        rw [heq]
        exact M.mul_mem ihx (hMconj x hxX _ ihy)
    | inv x hx ihx =>
        have hxX : x ∈ X := by rw [← hgen]; exact hx
        have heq : ⁅a, x⁻¹⁆ = x⁻¹ * ⁅a, x⁆⁻¹ * (x⁻¹)⁻¹ := by
          rw [commutatorElement_def, commutatorElement_def]; group
        rw [heq]
        exact hMconj x⁻¹ (X.inv_mem hxX) _ (M.inv_mem ihx)
  -- the generators satisfy the property in the first variable as well
  have hbase : ∀ a ∈ (N : Set G') ∪ {u, v}, ∀ b ∈ X, ⁅a, b⁆ ∈ M := by
    rintro a (haN | ha) b hbX
    · exact Subgroup.mem_sup_left (hNX (Subgroup.commutator_mem_commutator haN hbX))
    · have haX : a ∈ X := by rcases ha with rfl | rfl; exacts [huX, hvX]
      refine hright a haX ?_ b hbX
      rintro y (hyN | hy)
      · have h1 : ⁅y, a⁆ ∈ Z :=
          hNX (Subgroup.commutator_mem_commutator hyN haX)
        have h2 : ⁅a, y⁆ = ⁅y, a⁆⁻¹ := by
          rw [commutatorElement_def, commutatorElement_def]; group
        rw [h2]
        exact Subgroup.mem_sup_left (Subgroup.inv_mem _ h1)
      · have hself : ∀ w : G', ⁅w, w⁆ ∈ M := by
          intro w
          rw [show ⁅w, w⁆ = 1 by rw [commutatorElement_def]; group]
          exact M.one_mem
        have hcomm_uv : ⁅u, v⁆ ∈ M :=
          Subgroup.mem_sup_right (Subgroup.mem_zpowers _)
        have hcomm_vu : ⁅v, u⁆ ∈ M := by
          have h2 : ⁅v, u⁆ = c⁻¹ := by
            rw [hc_def, commutatorElement_def, commutatorElement_def]; group
          rw [h2]
          exact Subgroup.mem_sup_right (Subgroup.inv_mem _ (Subgroup.mem_zpowers _))
        rcases ha with rfl | rfl <;> rcases hy with rfl | rfl
        · exact hself _
        · exact hcomm_uv
        · exact hcomm_vu
        · exact hself _
  -- and then to all of `X` in the first variable
  refine Subgroup.commutator_le.mpr fun a ha b hb => ?_
  have hall : ∀ a ∈ X, ∀ b ∈ X, ⁅a, b⁆ ∈ M := by
    intro a haX
    rw [← hgen] at haX
    induction haX using Subgroup.closure_induction with
    | mem y hy => exact hbase y hy
    | one =>
        intro b _
        rw [show ⁅(1 : G'), b⁆ = 1 by rw [commutatorElement_def]; group]
        exact M.one_mem
    | mul x y hx hy ihx ihy =>
        intro b hbX
        have hxX : x ∈ X := by rw [← hgen]; exact hx
        have heq : ⁅x * y, b⁆ = (x * ⁅y, b⁆ * x⁻¹) * ⁅x, b⁆ := by
          rw [commutatorElement_def, commutatorElement_def, commutatorElement_def]
          group
        rw [heq]
        exact M.mul_mem (hMconj x hxX _ (ihy b hbX)) (ihx b hbX)
    | inv x hx ihx =>
        intro b hbX
        have hxX : x ∈ X := by rw [← hgen]; exact hx
        have heq : ⁅x⁻¹, b⁆ = x⁻¹ * ⁅x, b⁆⁻¹ * (x⁻¹)⁻¹ := by
          rw [commutatorElement_def, commutatorElement_def]; group
        rw [heq]
        exact hMconj x⁻¹ (X.inv_mem hxX) _ (M.inv_mem (ihx b hbX))
  exact hall a ha b hb

end GenericStronglyReal

namespace FirstCaseHypothesis

universe uG uΩ

variable {G : Type uG} {Ω : Type uΩ} [Group G] [MulAction G Ω] [Finite G]
  (fc : FirstCaseHypothesis G Ω)
  {F : Type uG} [NearFields.NearField F]
  (model : letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
    NearFields.AffineNearFieldModel fc.rankOneQuotient F)

include model in
/-- **The strongly real elements of `Z₁PΣ` are exactly those of `Z₁`** ((16), p. 114):
a strongly real `y ∈ Z₁PΣ` generates a subgroup of order `3` all of whose elements are
strongly real (the inverse of a strongly real element is strongly real), so that
subgroup is `Z₁`. -/
theorem mem_zpowers_of_isStronglyReal_of_mem
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) {y : G}
    (hy : y ∈ (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
    (hsr : IsStronglyReal y) :
    y ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  rcases eq_or_ne y 1 with rfl | hy1
  · exact Subgroup.one_mem _
  -- `y` has order `3`
  have hZSP_LV : ((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
      ≤ fc.nonsplitTorus ⊔ fc.toHypothesis.V :=
    sup_le (sup_le (fc.zpowers_le_nonsplitTorus.trans le_sup_left)
      ((inf_le_left.trans fc.toHypothesis.W_le_V).trans le_sup_right))
      (fc.P_le_V.trans le_sup_right)
  have hy3 : y ^ 3 = 1 :=
    (fc.pow_three_eq_one_iff_mem_zpowers_sup_sigma_sup_P model ind hB2
      (hZSP_LV hy)).mpr hy
  have hyord : orderOf y = 3 := by
    have h := orderOf_dvd_of_pow_eq_one hy3
    rcases (Nat.dvd_prime (by norm_num)).mp h with h1 | h3
    · exact absurd (orderOf_eq_one_iff.mp h1) hy1
    · exact h3
  have hXeq := fc.eq_zpowers_of_card_three_of_forall_isStronglyReal model ind hB2
    (X := Subgroup.zpowers y) (Subgroup.zpowers_le.mpr hy)
    (by rw [Nat.card_zpowers, hyord])
    (by
      intro z hz hz1
      rcases eq_one_or_eq_or_eq_inv_of_mem_zpowers_of_orderOf_eq_three hyord hz
        with h | h | h
      · exact absurd h hz1
      · rw [h]; exact hsr
      · rw [h]; exact isStronglyReal_inv hsr)
  rw [← hXeq]
  exact Subgroup.mem_zpowers _

include model in
/-- **`Z₁PΣ` is weakly closed in `R₂`, once `Z₁^x ≤ LV`** ((17), p. 114): then
`Z₁^x ≤ Ω₁(LV) = Z₁PΣ` consists of strongly real elements, so `Z₁^x = Z₁` by (16) and
`x ∈ N_G(Z₁) = N_G(Z₁PΣ)`. -/
theorem map_conj_eq_of_map_conj_zpowers_le
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) (S : Sylow 3 G)
    (hR₁S : fc.sylowThreeNormalizerRSigma model ≤ (S : Subgroup G)) {x : G}
    (hxLV : (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)).map (MulAut.conj x).toMonoidHom
      ≤ fc.nonsplitTorus ⊔ fc.toHypothesis.V) :
    (((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
          : Subgroup G).map (MulAut.conj x).toMonoidHom
      = (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  obtain ⟨-, hp3, -, -, -, -⟩ := fc.step_twelve model ind hB2
  have hstord : orderOf (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) = 3 := by
    rw [fc.orderOf_st_eq_char model, fc.char_eq_p model hB2, hp3]
  -- `Z₁^x` lies in `Ω₁(LV) = Z₁PΣ`
  have hle : (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)).map (MulAut.conj x).toMonoidHom
      ≤ (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P := by
    intro y hy
    refine (fc.pow_three_eq_one_iff_mem_zpowers_sup_sigma_sup_P model ind hB2
      (hxLV hy)).mp ?_
    obtain ⟨z, hz, rfl⟩ := hy
    have hz3 : z ^ 3 = 1 := by
      have h := Subgroup.orderOf_dvd_natCard _ hz
      rw [Nat.card_zpowers, hstord] at h
      exact orderOf_dvd_iff_pow_eq_one.mp h
    change (x * z * x⁻¹) ^ 3 = 1
    rw [conj_pow, hz3]
    group
  -- `Z₁^x = Z₁` by the uniqueness of the strongly real line
  have hZeq : (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)).map (MulAut.conj x).toMonoidHom
      = Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) := by
    refine fc.eq_zpowers_of_card_three_of_forall_isStronglyReal model ind hB2 hle ?_ ?_
    · rw [Subgroup.card_map_of_injective, Nat.card_zpowers, hstord]
      exact fun a b h => by
        simpa using congrArg (fun y => (MulAut.conj x).symm y) h
    · rintro y ⟨z, hz, rfl⟩ -
      exact isStronglyReal_conj
        (fc.forall_isStronglyReal_mem_zpowers_st model ind hB2 hz) x
  -- hence `x` normalizes `Z₁`, so also `Z₁PΣ`
  have hxN : x ∈ Subgroup.normalizer ((Subgroup.zpowers
      (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t) : Subgroup G)
        : Set G) := Subgroup.mem_normalizer_iff_map_conj_eq.mpr hZeq
  rw [fc.normalizer_zpowers_eq_normalizer_zpowers_sup_sigma_sup_P model ind hB2
    S hR₁S] at hxN
  exact Subgroup.mem_normalizer_iff_map_conj_eq.mp hxN

include model in
/-- **`Z₁^x ≤ LV`** ((17), p. 114, first paragraph), for `x` with `(Z₁PΣ)^x ≤ R₂`.

Otherwise `R₂ = LV·Z₁^x`, and `A = (Z₁PΣ)^x ⊓ LV` has order `9` and lies in
`Ω₁(LV) = Z₁PΣ`.  Its nonidentity elements are not strongly real: the strongly real
elements of `(Z₁PΣ)^x` are those of `Z₁^x`, which meets `LV` trivially in this case.
Hence `A ⊓ Z₁ = 1` and `Z₁A = Z₁PΣ`, so `Z₁^x` — which centralizes the abelian
`(Z₁PΣ)^x ⊇ A` and the central `Z₁ = Z(R₂)` — centralizes `Z₁PΣ`.  Then `Z₁Σ = Z(LV)`
is centralized by `LV` and by `Z₁^x`, i.e. `Z₁Σ ≤ Z(R₂) = Z₁`, contradicting
`|Z₁Σ| = 9`. -/
theorem map_conj_zpowers_le_sup_nonsplitTorus_V
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) (S : Sylow 3 G)
    (hR₁S : fc.sylowThreeNormalizerRSigma model ≤ (S : Subgroup G)) {x : G}
    (hx : (((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
            * fc.toHypothesis.t)
          ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
            : Subgroup G).map (MulAut.conj x).toMonoidHom ≤ (S : Subgroup G)) :
    (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)).map (MulAut.conj x).toMonoidHom
      ≤ fc.nonsplitTorus ⊔ fc.toHypothesis.V := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  obtain ⟨-, hp3, -, -, -, -⟩ := fc.step_twelve model ind hB2
  have hstord : orderOf (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) = 3 := by
    rw [fc.orderOf_st_eq_char model, fc.char_eq_p model hB2, hp3]
  have hZ₁card : Nat.card ↥(Subgroup.zpowers
      (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t)) = 3 := by
    rw [Nat.card_zpowers, hstord]
  have hconjInj : Function.Injective (MulAut.conj x).toMonoidHom := fun a b h => by
    simpa using congrArg (fun y => (MulAut.conj x).symm y) h
  set B : Subgroup G := (((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
        : Subgroup G).map (MulAut.conj x).toMonoidHom with hB_def
  set Zx : Subgroup G := (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t)).map (MulAut.conj x).toMonoidHom with hZx_def
  have hZxB : Zx ≤ B := Subgroup.map_mono (le_sup_left.trans le_sup_left)
  have hBcard : Nat.card ↥B = 27 := by
    rw [hB_def, Subgroup.card_map_of_injective hconjInj]
    exact fc.card_zpowers_sup_sigma_sup_P model ind hB2
  have hZxcard : Nat.card ↥Zx = 3 := by
    rw [hZx_def, Subgroup.card_map_of_injective hconjInj, hZ₁card]
  by_contra hcon
  have hBnotLV : ¬ B ≤ fc.nonsplitTorus ⊔ fc.toHypothesis.V :=
    fun h => hcon (hZxB.trans h)
  -- `A = B ⊓ LV` has order `9`
  have hBS : B ≤ (S : Subgroup G) := hx
  have hLVS := fc.sup_nonsplitTorus_V_le_sylow model ind hB2 S hR₁S
  have hidx := fc.index_subgroupOf_sup_nonsplitTorus_V_eq_three model ind hB2 S hR₁S
  have hminFac : (Nat.card ↥(S : Subgroup G)).minFac = 3 := by
    rcases fc.card_sylow_eq model ind hB2 S with h | h <;> rw [h] <;> norm_num
  haveI hLVnorm : ((fc.nonsplitTorus ⊔ fc.toHypothesis.V).subgroupOf
      (S : Subgroup G)).Normal :=
    Subgroup.normal_of_index_eq_minFac_card (by rw [hidx, hminFac])
  have hrel : (fc.nonsplitTorus ⊔ fc.toHypothesis.V).relIndex B ∣ 3 := by
    have h := Subgroup.relIndex_dvd_index_of_normal
      (H := (fc.nonsplitTorus ⊔ fc.toHypothesis.V).subgroupOf (S : Subgroup G))
      (K := B.subgroupOf (S : Subgroup G))
    rw [Subgroup.relIndex_subgroupOf hBS, hidx] at h
    exact h
  have hmul : Nat.card ↥((fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊓ B)
      * (fc.nonsplitTorus ⊔ fc.toHypothesis.V).relIndex B = Nat.card ↥B := by
    have hcard1 : Nat.card ↥(((fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊓ B).subgroupOf B)
        = Nat.card ↥((fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊓ B) :=
      Nat.card_congr (Subgroup.subgroupOfEquivOfLe inf_le_right).toEquiv
    have h := (((fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊓ B).subgroupOf B).card_mul_index
    rwa [hcard1, Subgroup.inf_subgroupOf_right] at h
  have hAcard : Nat.card ↥((fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊓ B) = 9 := by
    rw [hBcard] at hmul
    rcases (Nat.dvd_prime (by norm_num)).mp hrel with h1 | h3
    · exfalso
      rw [h1, mul_one] at hmul
      exact hBnotLV (le_trans (le_of_eq (Subgroup.eq_of_le_of_card_ge inf_le_right
        (by rw [hmul, hBcard])).symm) inf_le_left)
    · rw [h3] at hmul; omega
  -- `A ≤ Z₁ΣP`
  have hAZSP : (fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊓ B
      ≤ (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P := by
    intro y hy
    refine (fc.pow_three_eq_one_iff_mem_zpowers_sup_sigma_sup_P model ind hB2
      hy.1).mp ?_
    obtain ⟨z, hz, hzy⟩ := hy.2
    have hz3 : z ^ 3 = 1 :=
      (fc.pow_three_eq_one_iff_mem_zpowers_sup_sigma_sup_P model ind hB2
        (by
          refine sup_le (sup_le (fc.zpowers_le_nonsplitTorus.trans le_sup_left)
            ((inf_le_left.trans fc.toHypothesis.W_le_V).trans le_sup_right))
            (fc.P_le_V.trans le_sup_right) hz)).mpr hz
    have hyz : y = x * z * x⁻¹ := hzy.symm
    rw [hyz, conj_pow, hz3]
    group
  -- `A ⊓ Z₁ = 1`
  have hAZ₁ : ((fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊓ B)
      ⊓ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) = ⊥ := by
    rw [eq_bot_iff]
    intro y hy
    rw [Subgroup.mem_bot]
    by_contra hy1
    -- `y ∈ Z₁^#` is strongly real and lies in `B`, hence in `Z₁^x`
    refine hcon ?_
    have hyB : y ∈ B := hy.1.2
    have hysr : IsStronglyReal y :=
      fc.forall_isStronglyReal_mem_zpowers_st model ind hB2 hy.2
    have hyZx : y ∈ Zx := by
      obtain ⟨w, hwB, hwy⟩ : ∃ w ∈ ((Subgroup.zpowers
          (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t)
          ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P),
          x * w * x⁻¹ = y := by
        obtain ⟨w, hw, hwy⟩ := hyB
        exact ⟨w, hw, hwy⟩
      have hwsr : IsStronglyReal w := by
        have h := isStronglyReal_conj hysr x⁻¹
        rwa [show x⁻¹ * y * x⁻¹⁻¹ = w by rw [← hwy]; group] at h
      have hwZ := fc.mem_zpowers_of_isStronglyReal_of_mem model ind hB2 hwB hwsr
      exact ⟨w, hwZ, hwy⟩
    -- so `Z₁^x = ⟨y⟩ = Z₁ ≤ LV`
    have hyord : orderOf y = 3 := by
      have h := Subgroup.orderOf_dvd_natCard _ hy.2
      rw [hZ₁card] at h
      rcases (Nat.dvd_prime (by norm_num)).mp h with h1 | h3
      · exact absurd (orderOf_eq_one_iff.mp h1) hy1
      · exact h3
    have h1 : Subgroup.zpowers y = Zx :=
      Subgroup.eq_of_le_of_card_ge (Subgroup.zpowers_le.mpr hyZx)
        (by rw [hZxcard, Nat.card_zpowers, hyord])
    rw [← h1]
    exact Subgroup.zpowers_le.mpr
      (Subgroup.mem_sup_left (fc.zpowers_le_nonsplitTorus hy.2))
  -- `Z₁A = Z₁ΣP`
  have hprod : Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ ((fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊓ B)
      = (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P := by
    refine Subgroup.eq_of_le_of_card_ge
      (sup_le (le_sup_left.trans le_sup_left) hAZSP) ?_
    rw [card_sup_eq_mul_of_commute
        (fun a ha b hb => fc.mul_comm_of_mem_zpowers_sup_sigma_sup_P model ind hB2
          (Subgroup.mem_sup_left (Subgroup.mem_sup_left ha)) (hAZSP hb))
        (by rw [← hAZ₁]; exact inf_comm _ _),
      hZ₁card, hAcard, fc.card_zpowers_sup_sigma_sup_P model ind hB2]
  -- `B` is abelian, being a conjugate of `Z₁ΣP`
  have hBcomm : ∀ a ∈ B, ∀ b ∈ B, a * b = b * a := by
    rintro a ⟨c, hc, rfl⟩ b ⟨d, hd, rfl⟩
    have hcd := fc.mul_comm_of_mem_zpowers_sup_sigma_sup_P model ind hB2 hc hd
    change (x * c * x⁻¹) * (x * d * x⁻¹) = (x * d * x⁻¹) * (x * c * x⁻¹)
    calc (x * c * x⁻¹) * (x * d * x⁻¹) = x * (c * d) * x⁻¹ := by group
      _ = x * (d * c) * x⁻¹ := by rw [hcd]
      _ = (x * d * x⁻¹) * (x * c * x⁻¹) := by group
  -- `Z₁ = Z(R₂)` is central in `R₂`
  have hZ₁cen : ∀ z ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t), ∀ u ∈ (S : Subgroup G), z * u = u * z := by
    intro z hz u hu
    have hmem : z ∈ (S : Subgroup G) ⊓ Subgroup.centralizer
        (((S : Subgroup G)) : Set G) := by
      rw [fc.inf_centralizer_sylow_eq_zpowers model ind hB2 S hR₁S]
      exact hz
    exact (Subgroup.mem_centralizer_iff.mp hmem.2 u hu).symm
  -- `Z₁^x` centralizes `Z₁ΣP = Z₁A`
  have hZxcen : ∀ u ∈ Zx, ∀ v ∈ ((Subgroup.zpowers
        (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P),
      u * v = v * u := by
    intro u hu v hv
    rw [← hprod] at hv
    have hcoe := coe_sup_eq_mul_of_commute
      (fun _ (ha : _ ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)) _
        (hb : _ ∈ (fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊓ B) =>
        fc.mul_comm_of_mem_zpowers_sup_sigma_sup_P model ind hB2
          (Subgroup.mem_sup_left (Subgroup.mem_sup_left ha)) (hAZSP hb))
    have hv' : v ∈ ((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) : Subgroup G) : Set G)
        * (((fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊓ B : Subgroup G) : Set G) := by
      rw [← hcoe]; exact hv
    obtain ⟨z, hz, a, ha, hza⟩ := hv'
    have hzav : z * a = v := hza
    have h1 : u * z = z * u := (hZ₁cen z hz u (hBS (hZxB hu))).symm
    have h2 : u * a = a * u := hBcomm u (hZxB hu) a ha.2
    calc u * v = u * (z * a) := by rw [hzav]
      _ = z * (u * a) := by rw [← mul_assoc, h1, mul_assoc]
      _ = z * (a * u) := by rw [h2]
      _ = v * u := by rw [← mul_assoc, hzav]
  -- `R₂ = LV·Z₁^x`
  have hLVcardS : Nat.card ↥(fc.nonsplitTorus ⊔ fc.toHypothesis.V) * 3
      = Nat.card ↥(S : Subgroup G) := by
    have h := ((fc.nonsplitTorus ⊔ fc.toHypothesis.V).subgroupOf
      (S : Subgroup G)).card_mul_index
    rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe hLVS).toEquiv, hidx] at h
    exact h
  have hR₂eq : (fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊔ Zx = (S : Subgroup G) := by
    refine Subgroup.eq_of_le_of_card_ge (sup_le hLVS (hZxB.trans hBS)) ?_
    obtain ⟨m, hm⟩ := Subgroup.card_dvd_of_le
      (le_sup_left : fc.nonsplitTorus ⊔ fc.toHypothesis.V ≤ _ ⊔ Zx)
    have hdvd : Nat.card ↥((fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊔ Zx)
        ∣ Nat.card ↥(S : Subgroup G) :=
      Subgroup.card_dvd_of_le (sup_le hLVS (hZxB.trans hBS))
    have hpos : 0 < Nat.card ↥(fc.nonsplitTorus ⊔ fc.toHypothesis.V) := Nat.card_pos
    have hm3 : m ∣ 3 := by
      rw [hm, ← hLVcardS] at hdvd
      exact (Nat.mul_dvd_mul_iff_left hpos).mp hdvd
    rcases (Nat.dvd_prime (by norm_num)).mp hm3 with h1 | h3
    · exfalso
      refine hcon (le_trans ?_ (le_refl _))
      have heq : (fc.nonsplitTorus ⊔ fc.toHypothesis.V) ⊔ Zx
          = fc.nonsplitTorus ⊔ fc.toHypothesis.V :=
        (Subgroup.eq_of_le_of_card_ge le_sup_left (by rw [hm, h1, mul_one])).symm
      rw [← heq]
      exact le_sup_right
    · rw [hm, h3, hLVcardS]
  -- `Z₁Σ ≤ Z(R₂) = Z₁`, contradicting `|Z₁Σ| = 9`
  have hm : Nat.card F = fc.p ^ 2 := by
    obtain ⟨-, -, hF9, -, -, -⟩ := fc.step_twelve model ind hB2
    rw [hF9, hp3]; norm_num
  have hZ₁R : Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) ≤ fc.invImageF model :=
    (fc.zpowers_distinguishedInvolution_mul_t_le_sInvertedT model ind hB2 hm).trans
      (fc.sInvertedT_spec model ind hB2 hm).1
  have hZSP_S : ((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
      ≤ (S : Subgroup G) := by
    refine le_trans (le_trans ?_ (fc.sup_le_sylowThreeNormalizerRSigma model ind hB2))
      hR₁S
    exact sup_le (sup_le (hZ₁R.trans le_sup_left) le_sup_right)
      ((fc.P_le_invImageF model).trans le_sup_left)
  have hZSle' : (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)))
      ≤ (S : Subgroup G)
        ⊓ Subgroup.centralizer (((S : Subgroup G)) : Set G) := by
    intro y hy
    refine ⟨hZSP_S (Subgroup.mem_sup_left hy), ?_⟩
    rw [← hR₂eq, centralizer_sup]
    refine ⟨?_, ?_⟩
    · have heq := fc.inf_centralizer_sup_nonsplitTorus_V_eq model ind hB2
      rw [← heq] at hy
      exact hy.2
    · refine Subgroup.mem_centralizer_iff.mpr fun u hu => ?_
      exact hZxcen u hu y (Subgroup.mem_sup_left hy)
  have hZSle : (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)))
      ≤ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) :=
    le_trans hZSle'
      (le_of_eq (fc.inf_centralizer_sylow_eq_zpowers model ind hB2 S hR₁S))
  have hcard9 := fc.card_zpowers_sup_sigma model ind hB2
  have hdvd := Subgroup.card_dvd_of_le hZSle
  rw [hcard9, hZ₁card] at hdvd
  exact absurd (Nat.le_of_dvd (by norm_num) hdvd) (by norm_num)

include model in
/-- **`Z₁PΣ` is weakly closed in `R₂`** ((17), p. 114): every `G`-conjugate of `Z₁PΣ`
that is contained in the Sylow `3`-subgroup `R₂` equals `Z₁PΣ`.

This is the hypothesis of the Hall–Wielandt theorem, which then yields
`G/O³(G) ≅ N_G(Z₁PΣ)/O³(N_G(Z₁PΣ)) = R₂⟨s⟩/O³(R₂⟨s⟩)` (`Z₁PΣ` is abelian and
`p = 3 > 2`). -/
theorem map_conj_eq_of_le_sylow
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) (S : Sylow 3 G)
    (hR₁S : fc.sylowThreeNormalizerRSigma model ≤ (S : Subgroup G)) {x : G}
    (hx : (((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
            * fc.toHypothesis.t)
          ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
            : Subgroup G).map (MulAut.conj x).toMonoidHom ≤ (S : Subgroup G)) :
    (((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
          : Subgroup G).map (MulAut.conj x).toMonoidHom
      = (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P :=
  fc.map_conj_eq_of_map_conj_zpowers_le model ind hB2 S hR₁S
    (fc.map_conj_zpowers_le_sup_nonsplitTorus_V model ind hB2 S hR₁S hx)

include model in
/-- **`N_G(R₂) = R₂⟨s⟩ = N_G(Z₁PΣ)`** ((17), p. 114): `R₂ = C_G(Z₁)` and `Z(R₂) = Z₁`
by (14), so normalizing `R₂` is the same as normalizing `Z₁`. -/
theorem normalizer_sylow_eq
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) (S : Sylow 3 G)
    (hR₁S : fc.sylowThreeNormalizerRSigma model ≤ (S : Subgroup G)) :
    Subgroup.normalizer (((S : Subgroup G)) : Set G)
      = (S : Subgroup G)
        ⊔ Subgroup.zpowers fc.toHypothesis.distinguishedInvolution := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  have hSeq := fc.sylow_eq_centralizer_zpowers model ind hB2 S hR₁S
  have hZeq := fc.inf_centralizer_sylow_eq_zpowers model ind hB2 S hR₁S
  rw [← fc.normalizer_zpowers_eq_sylow_sup_zpowers model ind hB2 S hR₁S]
  refine le_antisymm (fun g hg => ?_) (fun g hg => ?_)
  · -- normalizing `R₂` forces normalizing `Z(R₂) = Z₁`
    rw [Subgroup.mem_set_normalizer_iff] at hg
    rw [Subgroup.mem_set_normalizer_iff]
    intro y
    have hcen : ∀ z : G, z ∈ Subgroup.centralizer (((S : Subgroup G)) : Set G)
        ↔ g * z * g⁻¹ ∈ Subgroup.centralizer (((S : Subgroup G)) : Set G) := by
      intro z
      refine ⟨fun hz => Subgroup.mem_centralizer_iff.mpr fun u hu => ?_,
        fun hz => Subgroup.mem_centralizer_iff.mpr fun u hu => ?_⟩
      · have hu' : g⁻¹ * u * g ∈ (S : Subgroup G) := by
          refine (hg (g⁻¹ * u * g)).mpr ?_
          rw [show g * (g⁻¹ * u * g) * g⁻¹ = u by group]
          exact hu
        have h := Subgroup.mem_centralizer_iff.mp hz _ hu'
        calc u * (g * z * g⁻¹) = g * ((g⁻¹ * u * g) * z) * g⁻¹ := by group
          _ = g * (z * (g⁻¹ * u * g)) * g⁻¹ := by rw [h]
          _ = (g * z * g⁻¹) * u := by group
      · have hu' : g * u * g⁻¹ ∈ (S : Subgroup G) := (hg u).mp hu
        have h := Subgroup.mem_centralizer_iff.mp hz _ hu'
        have h2 : (g * u * g⁻¹) * (g * z * g⁻¹) = (g * z * g⁻¹) * (g * u * g⁻¹) := h
        have h3 : g * (u * z) * g⁻¹ = g * (z * u) * g⁻¹ := by
          calc g * (u * z) * g⁻¹ = (g * u * g⁻¹) * (g * z * g⁻¹) := by group
            _ = (g * z * g⁻¹) * (g * u * g⁻¹) := h2
            _ = g * (z * u) * g⁻¹ := by group
        exact mul_left_cancel (mul_right_cancel h3)
    rw [← hZeq]
    constructor
    · rintro ⟨hy1, hy2⟩
      exact ⟨(hg y).mp hy1, (hcen y).mp hy2⟩
    · rintro ⟨hy1, hy2⟩
      exact ⟨(hg y).mpr hy1, (hcen y).mpr hy2⟩
  · -- normalizing `Z₁` forces normalizing `C_G(Z₁) = R₂`
    rw [Subgroup.mem_set_normalizer_iff] at hg
    rw [Subgroup.mem_set_normalizer_iff, ← hSeq]
    intro y
    refine ⟨fun hy => Subgroup.mem_centralizer_iff.mpr fun u hu => ?_,
      fun hy => Subgroup.mem_centralizer_iff.mpr fun u hu => ?_⟩
    · have hu' : g⁻¹ * u * g ∈ Subgroup.zpowers
          (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t) := by
        refine (hg (g⁻¹ * u * g)).mpr ?_
        rw [show g * (g⁻¹ * u * g) * g⁻¹ = u by group]
        exact hu
      have h := Subgroup.mem_centralizer_iff.mp hy _ hu'
      calc u * (g * y * g⁻¹) = g * ((g⁻¹ * u * g) * y) * g⁻¹ := by group
        _ = g * (y * (g⁻¹ * u * g)) * g⁻¹ := by rw [h]
        _ = (g * y * g⁻¹) * u := by group
    · have hu' : g * u * g⁻¹ ∈ Subgroup.zpowers
        (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t) := (hg u).mp hu
      have h : (g * u * g⁻¹) * (g * y * g⁻¹) = (g * y * g⁻¹) * (g * u * g⁻¹) :=
        Subgroup.mem_centralizer_iff.mp hy _ hu'
      have h3 : g * (u * y) * g⁻¹ = g * (y * u) * g⁻¹ := by
        calc g * (u * y) * g⁻¹ = (g * u * g⁻¹) * (g * y * g⁻¹) := by group
          _ = (g * y * g⁻¹) * (g * u * g⁻¹) := h
          _ = g * (y * u) * g⁻¹ := by group
      exact mul_left_cancel (mul_right_cancel h3)

include model in
/-- **`W ⊄ R₁` when `|W| = 9`** ((17), p. 114, last paragraph).

Peterfalvi argues through `C_{R₁}(s) = PΣ`; here it is quicker to compare centres:
if `W ≤ R₁` then `LV ≤ R₁`, and `|LV| = 27·|W| = 3⁵ = |R₁|` forces `LV = R₁`, whence
`Z₁Σ = Z(LV) = Z(R₁) = Z₁` — impossible since `|Z₁Σ| = 9` and `|Z₁| = 3`. -/
theorem not_W_le_sylowThree_of_card_W_eq_nine
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G))
    (hW9 : Nat.card ↥fc.toHypothesis.W = 9) :
    ¬ fc.toHypothesis.W ≤ fc.sylowThreeNormalizerRSigma model := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  intro hWR₁
  have hR₁card := fc.card_sylowThreeNormalizerRSigma model ind hB2
  have hLVcard : Nat.card ↥(fc.nonsplitTorus ⊔ fc.toHypothesis.V) = 3 ^ 5 := by
    rw [fc.card_sup_nonsplitTorus_V model ind hB2, hW9]
    norm_num
  have hPR₁ : fc.P ≤ fc.sylowThreeNormalizerRSigma model :=
    ((fc.P_le_invImageF model).trans le_sup_left).trans
      (fc.sup_le_sylowThreeNormalizerRSigma model ind hB2)
  have hLVle : fc.nonsplitTorus ⊔ fc.toHypothesis.V
      ≤ fc.sylowThreeNormalizerRSigma model := by
    refine sup_le (fc.nonsplitTorus_le_sylowThreeNormalizerRSigma model ind hB2) ?_
    rw [← fc.W_join_P_eq_V]
    exact sup_le hWR₁ hPR₁
  have hLVeq : fc.nonsplitTorus ⊔ fc.toHypothesis.V
      = fc.sylowThreeNormalizerRSigma model :=
    Subgroup.eq_of_le_of_card_ge hLVle (by rw [hLVcard, hR₁card])
  -- the two centres disagree
  have hZLV := fc.inf_centralizer_sup_nonsplitTorus_V_eq model ind hB2
  have hZR₁ := fc.inf_centralizer_sylowThree_eq_zpowers model ind hB2
  rw [hLVeq, hZR₁] at hZLV
  have h9 := fc.card_zpowers_sup_sigma model ind hB2
  obtain ⟨-, hp3, -, -, -, -⟩ := fc.step_twelve model ind hB2
  have hstord : orderOf (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) = 3 := by
    rw [fc.orderOf_st_eq_char model, fc.char_eq_p model hB2, hp3]
  rw [← hZLV, Nat.card_zpowers, hstord] at h9
  omega

include model in
/-- **`R₂⟨s⟩` has a quotient of order `3` when `|W| = 9`** ((17), p. 114, last
paragraph): `R₂ = R₁W` with `R₁` of index `3`, and `s` centralizes `W`, so `R₁⟨s⟩` is
normal of index `3` in `R₂⟨s⟩`. -/
theorem three_dvd_card_abelianization_of_card_W_eq_nine
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) (S : Sylow 3 G)
    (hR₁S : fc.sylowThreeNormalizerRSigma model ≤ (S : Subgroup G))
    (hW9 : Nat.card ↥fc.toHypothesis.W = 9) :
    (3 : ℕ) ∣ Nat.card (Abelianization ↥((S : Subgroup G)
      ⊔ Subgroup.zpowers fc.toHypothesis.distinguishedInvolution)) := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  set s : G := fc.toHypothesis.distinguishedInvolution with hs_def
  have hsord : orderOf s = 2 :=
    orderOf_eq_prime fc.toHypothesis.distinguishedInvolution_sq
      fc.toHypothesis.distinguishedInvolution_ne_one
  have hR₁card := fc.card_sylowThreeNormalizerRSigma model ind hB2
  obtain ⟨-, -, -, -, -, hGp⟩ := fc.step_twelve model ind hB2
  have hScard : Nat.card ↥(S : Subgroup G) = 3 ^ 6 := by
    rw [Sylow.card_eq_multiplicity, hGp, hW9]
    norm_num
  -- `R₁` is normal of index `3` in `R₂`
  have hR₁idx : ((fc.sylowThreeNormalizerRSigma model).subgroupOf
      (S : Subgroup G)).index = 3 := by
    have h := ((fc.sylowThreeNormalizerRSigma model).subgroupOf
      (S : Subgroup G)).card_mul_index
    rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe hR₁S).toEquiv, hR₁card,
      hScard] at h
    omega
  haveI hR₁norm : ((fc.sylowThreeNormalizerRSigma model).subgroupOf
      (S : Subgroup G)).Normal :=
    Subgroup.normal_of_index_eq_minFac_card (by rw [hR₁idx, hScard]; norm_num)
  have hconjR₁ : ∀ g ∈ (S : Subgroup G), ∀ a ∈ fc.sylowThreeNormalizerRSigma model,
      g * a * g⁻¹ ∈ fc.sylowThreeNormalizerRSigma model := by
    intro g hg a ha
    have h := hR₁norm.conj_mem ⟨a, hR₁S ha⟩ (by rwa [Subgroup.mem_subgroupOf])
      ⟨g, hg⟩
    rwa [Subgroup.mem_subgroupOf] at h
  -- `s` normalizes `R₁` and `R₂`
  have hsR₁ : ∀ a ∈ fc.sylowThreeNormalizerRSigma model,
      s * a * s⁻¹ ∈ fc.sylowThreeNormalizerRSigma model := fun a ha =>
    fc.conj_mem_sylowThreeNormalizerRSigma model
      (fc.distinguishedInvolution_mem_normalizerRSigma model) ha
  have hsS : s ∈ Subgroup.normalizer (((S : Subgroup G)) : Set G) := by
    rw [fc.normalizer_sylow_eq model ind hB2 S hR₁S]
    exact Subgroup.mem_sup_right (Subgroup.mem_zpowers _)
  -- `R₂ = R₁W`
  have hWS : fc.toHypothesis.W ≤ (S : Subgroup G) :=
    ((fc.toHypothesis.W_le_V.trans le_sup_right).trans
      (fc.sup_nonsplitTorus_V_le_sylow model ind hB2 S hR₁S))
  have hR₂eq : fc.sylowThreeNormalizerRSigma model ⊔ fc.toHypothesis.W
      = (S : Subgroup G) := by
    refine Subgroup.eq_of_le_of_card_ge (sup_le hR₁S hWS) ?_
    obtain ⟨m, hm⟩ := Subgroup.card_dvd_of_le
      (le_sup_left : fc.sylowThreeNormalizerRSigma model ≤ _ ⊔ fc.toHypothesis.W)
    have hdvd : Nat.card ↥(fc.sylowThreeNormalizerRSigma model
        ⊔ fc.toHypothesis.W) ∣ Nat.card ↥(S : Subgroup G) :=
      Subgroup.card_dvd_of_le (sup_le hR₁S hWS)
    have hm3 : m ∣ 3 := by
      rw [hm, hR₁card, hScard] at hdvd
      refine (Nat.mul_dvd_mul_iff_left (show 0 < 3 ^ 5 by norm_num)).mp ?_
      calc 3 ^ 5 * m ∣ 3 ^ 6 := hdvd
        _ = 3 ^ 5 * 3 := by norm_num
    rcases (Nat.dvd_prime (by norm_num)).mp hm3 with h1 | h3
    · exfalso
      refine fc.not_W_le_sylowThree_of_card_W_eq_nine model ind hB2 hW9 ?_
      have heq : fc.sylowThreeNormalizerRSigma model ⊔ fc.toHypothesis.W
          = fc.sylowThreeNormalizerRSigma model :=
        (Subgroup.eq_of_le_of_card_ge le_sup_left (by rw [hm, h1, mul_one])).symm
      rw [← heq]
      exact le_sup_right
    · rw [hm, h3, hR₁card, hScard]
      norm_num
  -- every element of `R₂` sends `s` into `R₁⟨s⟩`
  have hcoeR₂ : ((S : Subgroup G) : Set G)
      = ((fc.sylowThreeNormalizerRSigma model : Subgroup G) : Set G)
        * (fc.toHypothesis.W : Set G) := by
    rw [← hR₂eq]
    refine Subgroup.coe_mul_of_right_le_normalizer_left _ _ ?_
    intro w hw
    rw [Subgroup.mem_set_normalizer_iff]
    intro y
    refine ⟨fun hy => hconjR₁ w (hWS hw) y hy, fun hy => ?_⟩
    have h1 : w⁻¹ * (w * y * w⁻¹) * w⁻¹⁻¹ = y := by group
    rw [← h1]
    exact hconjR₁ w⁻¹ (Subgroup.inv_mem _ (hWS hw)) _ hy
  have hconjS : ∀ g ∈ (S : Subgroup G),
      g * s * g⁻¹ ∈ fc.sylowThreeNormalizerRSigma model ⊔ Subgroup.zpowers s := by
    intro g hg
    have hg' : g ∈ ((fc.sylowThreeNormalizerRSigma model : Subgroup G) : Set G)
        * (fc.toHypothesis.W : Set G) := by rw [← hcoeR₂]; exact hg
    obtain ⟨a, ha, w, hw, hawg⟩ := hg'
    have haw : a * w = g := hawg
    have hws : w * s = s * w := Subgroup.mem_centralizer_singleton_iff.mp
      (fc.toHypothesis.V_le_centralizer_distinguishedInvolution
        (fc.toHypothesis.W_le_V hw)).2
    have hcalc : g * s * g⁻¹ = (a * (s * a⁻¹ * s⁻¹)) * s := by
      calc g * s * g⁻¹ = a * (w * s * w⁻¹) * a⁻¹ := by rw [← haw]; group
        _ = a * s * a⁻¹ := by rw [hws]; group
        _ = (a * (s * a⁻¹ * s⁻¹)) * s := by group
    rw [hcalc]
    refine Subgroup.mul_mem _ (Subgroup.mem_sup_left ?_)
      (Subgroup.mem_sup_right (Subgroup.mem_zpowers _))
    exact Subgroup.mul_mem _ ha (hsR₁ a⁻¹ (Subgroup.inv_mem _ ha))
  -- `R₁⟨s⟩` is normal in `R₂⟨s⟩`
  have hnorm : ∀ g ∈ (S : Subgroup G) ⊔ Subgroup.zpowers s,
      ∀ y ∈ fc.sylowThreeNormalizerRSigma model ⊔ Subgroup.zpowers s,
      g * y * g⁻¹ ∈ fc.sylowThreeNormalizerRSigma model ⊔ Subgroup.zpowers s := by
    have hgen : ((S : Subgroup G) ⊔ Subgroup.zpowers s)
        ≤ Subgroup.normalizer (((fc.sylowThreeNormalizerRSigma model
          ⊔ Subgroup.zpowers s : Subgroup G)) : Set G) := by
      refine sup_le ?_ ?_
      · intro g hg
        have hconj : ∀ h : G, (∀ a ∈ fc.sylowThreeNormalizerRSigma model,
              h * a * h⁻¹ ∈ fc.sylowThreeNormalizerRSigma model) →
            (h * s * h⁻¹ ∈ fc.sylowThreeNormalizerRSigma model ⊔ Subgroup.zpowers s) →
            ∀ y ∈ fc.sylowThreeNormalizerRSigma model ⊔ Subgroup.zpowers s,
              h * y * h⁻¹ ∈ fc.sylowThreeNormalizerRSigma model
                ⊔ Subgroup.zpowers s := by
          intro h hR hs y hy
          have hsub : fc.sylowThreeNormalizerRSigma model ⊔ Subgroup.zpowers s
              ≤ Subgroup.comap (MulAut.conj h).toMonoidHom
                (fc.sylowThreeNormalizerRSigma model ⊔ Subgroup.zpowers s) := by
            refine sup_le (fun a ha => Subgroup.mem_sup_left (hR a ha))
              (Subgroup.zpowers_le.mpr hs)
          exact hsub hy
        rw [Subgroup.mem_set_normalizer_iff]
        intro y
        refine ⟨fun hy => hconj g (fun a ha => hconjR₁ g hg a ha) (hconjS g hg) y hy,
          fun hy => ?_⟩
        have h1 : g⁻¹ * (g * y * g⁻¹) * g⁻¹⁻¹ = y := by group
        rw [← h1]
        refine hconj g⁻¹ (fun a ha => hconjR₁ g⁻¹ (Subgroup.inv_mem _ hg) a ha) ?_ _ hy
        exact hconjS g⁻¹ (Subgroup.inv_mem _ hg)
      · rw [Subgroup.zpowers_le, Subgroup.mem_set_normalizer_iff]
        have hs2 : s * s = 1 := by
          rw [← pow_two]; exact fc.toHypothesis.distinguishedInvolution_sq
        have hsinv : s⁻¹ = s := inv_eq_of_mul_eq_one_right hs2
        have hconj : ∀ y ∈ fc.sylowThreeNormalizerRSigma model ⊔ Subgroup.zpowers s,
            s * y * s⁻¹ ∈ fc.sylowThreeNormalizerRSigma model
              ⊔ Subgroup.zpowers s := by
          have hsub : fc.sylowThreeNormalizerRSigma model ⊔ Subgroup.zpowers s
              ≤ Subgroup.comap (MulAut.conj s).toMonoidHom
                (fc.sylowThreeNormalizerRSigma model ⊔ Subgroup.zpowers s) := by
            refine sup_le (fun a ha => Subgroup.mem_sup_left (hsR₁ a ha))
              (Subgroup.zpowers_le.mpr (Subgroup.mem_sup_right ?_))
            have hss : (MulAut.conj s).toMonoidHom s = s := by
              change s * s * s⁻¹ = s
              group
            rw [hss]
            exact Subgroup.mem_zpowers _
          intro y hy
          exact hsub hy
        intro y
        refine ⟨fun hy => hconj y hy, fun hy => ?_⟩
        have h1 : y = s * (s * y * s⁻¹) * s⁻¹ := by
          rw [hsinv]
          calc y = (s * s) * y * (s * s) := by rw [hs2]; group
            _ = s * (s * y * s) * s := by group
        rw [h1]
        exact hconj _ hy
    intro g hg y hy
    have h := Subgroup.mem_set_normalizer_iff.mp (hgen hg) y
    exact h.mp hy
  -- cardinalities and the index
  have hR₁inf : fc.sylowThreeNormalizerRSigma model ⊓ Subgroup.zpowers s = ⊥ :=
    (fc.sylowThree_sup_zpowers_distinguishedInvolution model ind hB2).2
  have hSinf : (S : Subgroup G) ⊓ Subgroup.zpowers s = ⊥ := by
    rw [eq_bot_iff]
    intro y hy
    rw [Subgroup.mem_bot]
    have h2 : orderOf y ∣ 2 := by
      have h := Subgroup.orderOf_dvd_natCard _ hy.2
      rwa [Nat.card_zpowers, hsord] at h
    obtain ⟨k, hk⟩ := (IsPGroup.iff_orderOf).mp S.isPGroup' ⟨y, hy.1⟩
    rw [Subgroup.orderOf_mk] at hk
    have h3 : orderOf y ∣ 3 ^ k := by rw [hk]
    have h1 : orderOf y = 1 := Nat.eq_one_of_dvd_coprimes
      (Nat.Coprime.pow_right k (by norm_num)) h2 h3
    exact orderOf_eq_one_iff.mp h1
  have hcardR₁s : Nat.card ↥(fc.sylowThreeNormalizerRSigma model
      ⊔ Subgroup.zpowers s) = 3 ^ 5 * 2 := by
    rw [card_sup_eq_mul_of_le_normalizer (fun b hb => ?_) hR₁inf, hR₁card,
      Nat.card_zpowers, hsord]
    rw [Subgroup.mem_set_normalizer_iff]
    obtain ⟨k, rfl⟩ := hb
    intro y
    have hsk : ∀ a ∈ fc.sylowThreeNormalizerRSigma model,
        s ^ k * a * (s ^ k)⁻¹ ∈ fc.sylowThreeNormalizerRSigma model := by
      intro a ha
      exact fc.conj_mem_sylowThreeNormalizerRSigma model
        (Subgroup.zpow_mem _ (fc.distinguishedInvolution_mem_normalizerRSigma model) k)
        ha
    refine ⟨fun hy => hsk y hy, fun hy => ?_⟩
    have h1 : (s ^ k)⁻¹ * (s ^ k * y * (s ^ k)⁻¹) * ((s ^ k)⁻¹)⁻¹ = y := by group
    rw [← h1]
    have hsk' : ∀ a ∈ fc.sylowThreeNormalizerRSigma model,
        (s ^ k)⁻¹ * a * ((s ^ k)⁻¹)⁻¹ ∈ fc.sylowThreeNormalizerRSigma model := by
      intro a ha
      exact fc.conj_mem_sylowThreeNormalizerRSigma model
        (Subgroup.inv_mem _ (Subgroup.zpow_mem _
          (fc.distinguishedInvolution_mem_normalizerRSigma model) k)) ha
    exact hsk' _ hy
  have hcardSs : Nat.card ↥((S : Subgroup G) ⊔ Subgroup.zpowers s)
      = 3 ^ 6 * 2 := by
    rw [card_sup_eq_mul_of_le_normalizer (fun b hb => ?_) hSinf, hScard,
      Nat.card_zpowers, hsord]
    obtain ⟨k, rfl⟩ := hb
    exact Subgroup.zpow_mem _ hsS k
  have hleSs : fc.sylowThreeNormalizerRSigma model ⊔ Subgroup.zpowers s
      ≤ (S : Subgroup G) ⊔ Subgroup.zpowers s :=
    sup_le (hR₁S.trans le_sup_left) le_sup_right
  haveI hnormSub : ((fc.sylowThreeNormalizerRSigma model
      ⊔ Subgroup.zpowers s).subgroupOf
        ((S : Subgroup G) ⊔ Subgroup.zpowers s)).Normal := by
    constructor
    intro n hn g
    rw [Subgroup.mem_subgroupOf] at hn ⊢
    exact hnorm g g.2 n hn
  have hidx : ((fc.sylowThreeNormalizerRSigma model ⊔ Subgroup.zpowers s).subgroupOf
      ((S : Subgroup G) ⊔ Subgroup.zpowers s)).index = 3 := by
    have h := ((fc.sylowThreeNormalizerRSigma model ⊔ Subgroup.zpowers s).subgroupOf
      ((S : Subgroup G) ⊔ Subgroup.zpowers s)).card_mul_index
    rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe hleSs).toEquiv, hcardR₁s,
      hcardSs] at h
    omega
  exact dvd_card_abelianization_of_index_eq_prime (by norm_num) hidx

/-! ## Towards the `|W| = 3` branch -/

include model in
/-- `Z₁ ⊓ ΣP = 1`: the elements of `Z₁` are strongly real ((16)) while those of
`(ΣP)^#` are not. -/
theorem zpowers_inf_sigma_sup_P_eq_bot
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t)
      ⊓ ((fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) ⊔ fc.P) = ⊥ := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  rw [eq_bot_iff]
  intro y hy
  rw [Subgroup.mem_bot]
  by_contra hy1
  exact fc.not_isStronglyReal_of_mem_P_sup_sigma model ind hB2 hy.2 hy1
    (fc.forall_isStronglyReal_mem_zpowers_st model ind hB2 hy.1)

include model in
/-- `Z₁ ≤ ⁅R₁, R₁⁆`, since `Z₁ = ⁅RΣ, RΣ⁆` by (14) and `RΣ ≤ R₁`. -/
theorem zpowers_le_commutator_sylowThree
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t)
      ≤ ⁅fc.sylowThreeNormalizerRSigma model, fc.sylowThreeNormalizerRSigma model⁆ := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  rw [← fc.commutator_sup_eq_zpowers model ind hB2]
  exact Subgroup.commutator_mono (fc.sup_le_sylowThreeNormalizerRSigma model ind hB2)
    (fc.sup_le_sylowThreeNormalizerRSigma model ind hB2)

include model in
/-- **`ΣP ⊄ ⁅R₁, R₁⁆`**, given the commutator bound `|⁅R₁, R₁⁆| ≤ 9` ((17), p. 114:
"`⁅R̄₁, R̄₁⁆` has order `1` or `3`").

Indeed `Z₁ ≤ ⁅R₁, R₁⁆` and `Z₁ ⊓ ΣP = 1`, so `ΣP ≤ ⁅R₁, R₁⁆` would force
`27 = |Z₁ΣP| ≤ |⁅R₁, R₁⁆| ≤ 9`. -/
theorem not_sigma_sup_P_le_commutator_sylowThree
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G))
    (hbound : Nat.card ↥(⁅fc.sylowThreeNormalizerRSigma model,
      fc.sylowThreeNormalizerRSigma model⁆ : Subgroup G) ≤ 9) :
    ¬ ((fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) ⊔ fc.P)
      ≤ ⁅fc.sylowThreeNormalizerRSigma model,
        fc.sylowThreeNormalizerRSigma model⁆ := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  intro hle
  obtain ⟨-, hp3, -, -, -, -⟩ := fc.step_twelve model ind hB2
  obtain ⟨hpSig, -, -, -, -, -⟩ := fc.step_twelve model ind hB2
  obtain ⟨-, -, -, hSig3, -⟩ :=
    fc.card_field_eq_nine_of_p_dvd_card_centralizer_W ind model hB2 hpSig
  have hstord : orderOf (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) = 3 := by
    rw [fc.orderOf_st_eq_char model, fc.char_eq_p model hB2, hp3]
  -- `|ΣP| = 9`
  have hSPcard : Nat.card ↥((fc.toHypothesis.W
      ⊓ Subgroup.centralizer (fc.P : Set G)) ⊔ fc.P) = 9 := by
    have hinf : (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) ⊓ fc.P
        = ⊥ := by
      rw [eq_bot_iff]
      intro x hx
      have hmem : x ∈ (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
          ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊓ fc.P :=
        ⟨Subgroup.mem_sup_right hx.1, hx.2⟩
      rwa [fc.zpowers_sup_sigma_inf_P_eq_bot model ind hB2] at hmem
    rw [card_sup_eq_mul_of_commute
        (fun a (ha : a ∈ fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))
          b (hb : b ∈ fc.P) =>
          (Subgroup.mem_centralizer_iff.mp ha.2 b hb).symm) hinf,
      hSig3, fc.card_P, hp3]
  -- `Z₁ΣP ≤ ⁅R₁, R₁⁆` has order `27`
  have hSPle : ((fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) ⊔ fc.P)
      ≤ (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P :=
    sup_le (le_sup_right.trans le_sup_left) le_sup_right
  have hZle := fc.zpowers_le_commutator_sylowThree model ind hB2
  have hZSPle : Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ ((fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) ⊔ fc.P)
      ≤ ⁅fc.sylowThreeNormalizerRSigma model,
        fc.sylowThreeNormalizerRSigma model⁆ := sup_le hZle hle
  have hcard27 : Nat.card ↥(Subgroup.zpowers
      (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t)
      ⊔ ((fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) ⊔ fc.P)) = 27 := by
    rw [card_sup_eq_mul_of_commute
        (fun a (ha : a ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
            * fc.toHypothesis.t)) b
          (hb : b ∈ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))
            ⊔ fc.P) =>
          fc.mul_comm_of_mem_zpowers_sup_sigma_sup_P model ind hB2
            (Subgroup.mem_sup_left (Subgroup.mem_sup_left ha))
            (hSPle hb))
        (fc.zpowers_inf_sigma_sup_P_eq_bot model ind hB2),
      Nat.card_zpowers, hstord, hSPcard]
  have hdvd := Subgroup.card_dvd_of_le hZSPle
  rw [hcard27] at hdvd
  have := Nat.le_of_dvd (by
    have : 0 < Nat.card ↥(⁅fc.sylowThreeNormalizerRSigma model,
      fc.sylowThreeNormalizerRSigma model⁆ : Subgroup G) := Nat.card_pos
    omega) hdvd
  omega

include model in
/-- **`|⁅R₁, R₁⁆| ≤ 9`** ((17), p. 114: "`⁅R̄₁, R̄₁⁆` has order `1` or `3`").

`R₁` is generated by `N = Z₁ΣP` together with one element `u ∈ R ∖ Z₁P` and a generator
`v` of `L`, while `⁅N, R₁⁆ ≤ Z₁` by (16) and `⁅R₁, R₁⁆ ≤ N`; so
`commutator_le_of_two_generators` bounds `⁅R₁, R₁⁆` by `Z₁⟨⁅u,v⁆⟩`, of order at most
`9`. -/
theorem card_commutator_sylowThree_le
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G))
    (hcommN : ⁅fc.sylowThreeNormalizerRSigma model,
        fc.sylowThreeNormalizerRSigma model⁆
      ≤ (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P) :
    Nat.card ↥(⁅fc.sylowThreeNormalizerRSigma model,
      fc.sylowThreeNormalizerRSigma model⁆ : Subgroup G) ≤ 9 := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  obtain ⟨-, hp3, hF9, -, -, -⟩ := fc.step_twelve model ind hB2
  have hm : Nat.card F = fc.p ^ 2 := by rw [hF9, hp3]; norm_num
  have hPcard : Nat.card ↥fc.P = 3 := by rw [fc.card_P, hp3]
  have hstord : orderOf (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) = 3 := by
    rw [fc.orderOf_st_eq_char model, fc.char_eq_p model hB2, hp3]
  have hZ₁card : Nat.card ↥(Subgroup.zpowers
      (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t)) = 3 := by
    rw [Nat.card_zpowers, hstord]
  -- basic containments
  have hZ₁R : Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) ≤ fc.invImageF model :=
    (fc.zpowers_distinguishedInvolution_mul_t_le_sInvertedT model ind hB2 hm).trans
      (fc.sInvertedT_spec model ind hB2 hm).1
  have hPR : fc.P ≤ fc.invImageF model := fc.P_le_invImageF model
  have habR := fc.invImageF_mul_comm model ind hB2 hm
  have hRcard : Nat.card ↥(fc.invImageF model) = 27 := by
    rw [fc.card_invImageF model ind, hF9, hPcard]
  have hZPcard := fc.card_zpowers_sup_P_eq_nine model ind hB2
  have hZPR : Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) ⊔ fc.P ≤ fc.invImageF model := sup_le hZ₁R hPR
  -- pick `u ∈ R ∖ Z₁P`
  obtain ⟨u, huR, huZP⟩ : ∃ u ∈ fc.invImageF model,
      u ∉ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) ⊔ fc.P := by
    by_contra hcon
    push Not at hcon
    have hle : fc.invImageF model ≤ Subgroup.zpowers
        (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t) ⊔ fc.P := hcon
    have := Nat.le_of_dvd (by norm_num) (Subgroup.card_dvd_of_le hle)
    rw [hRcard, hZPcard] at this
    omega
  have hu3 : u ^ 3 = 1 := by
    have h := fc.pow_p_eq_one_of_mem_invImageF model ind hB2 hm huR
    rwa [hp3] at h
  have hR_eq : (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) ⊔ fc.P) ⊔ Subgroup.zpowers u = fc.invImageF model := by
    refine Subgroup.eq_of_le_of_card_ge (sup_le hZPR (Subgroup.zpowers_le.mpr huR)) ?_
    have huord : orderOf u = 3 := by
      have hdvd : orderOf u ∣ 3 := orderOf_dvd_iff_pow_eq_one.mpr hu3
      rcases (Nat.dvd_prime (by norm_num)).mp hdvd with h1 | h3
      · exact absurd (by rw [orderOf_eq_one_iff.mp h1]; exact Subgroup.one_mem _) huZP
      · exact h3
    have hinf : (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) ⊔ fc.P) ⊓ Subgroup.zpowers u = ⊥ := by
      rw [eq_bot_iff]
      intro y hy
      rw [Subgroup.mem_bot]
      by_contra hy1
      refine huZP ?_
      have hyord : orderOf y = 3 := by
        have hdvd : orderOf y ∣ 3 := by
          have h := Subgroup.orderOf_dvd_natCard _ hy.2
          rwa [Nat.card_zpowers, huord] at h
        rcases (Nat.dvd_prime (by norm_num)).mp hdvd with h1 | h3
        · exact absurd (orderOf_eq_one_iff.mp h1) hy1
        · exact h3
      have heq : Subgroup.zpowers y = Subgroup.zpowers u :=
        Subgroup.eq_of_le_of_card_ge (Subgroup.zpowers_le.mpr hy.2)
          (by rw [Nat.card_zpowers, Nat.card_zpowers, huord, hyord])
      have hu : u ∈ Subgroup.zpowers y := by rw [heq]; exact Subgroup.mem_zpowers _
      obtain ⟨k, hk⟩ := hu
      rw [← hk]
      exact Subgroup.zpow_mem _ hy.1 k
    have hzuR : Subgroup.zpowers u ≤ fc.invImageF model :=
      Subgroup.zpowers_le.mpr huR
    rw [card_sup_eq_mul_of_commute
        (fun a (ha : a ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
            * fc.toHypothesis.t) ⊔ fc.P) b (hb : b ∈ Subgroup.zpowers u) =>
          habR a (hZPR ha) b (hzuR hb))
        hinf, hZPcard, Nat.card_zpowers, huord, hRcard]
  -- pick a generator `v` of `L`
  obtain ⟨hLcyc, hLcard⟩ := fc.isCyclic_and_card_nonsplitTorus model ind hB2
  obtain ⟨g, hg⟩ := hLcyc.exists_generator
  have hLgen : Subgroup.zpowers ((g : G)) = fc.nonsplitTorus := by
    refine Subgroup.eq_of_le_of_card_ge (Subgroup.zpowers_le.mpr g.2) ?_
    have hgtop : Subgroup.zpowers g = ⊤ := eq_top_iff.mpr fun x _ => hg x
    have hgord : orderOf ((g : G)) = 9 := by
      rw [Subgroup.orderOf_coe, ← Nat.card_zpowers, hgtop, Subgroup.card_top, hLcard]
    rw [hLcard, Nat.card_zpowers, hgord]
  -- `R₁` is generated by `N` together with `u` and `v`
  have hgen : Subgroup.closure ((((Subgroup.zpowers
        (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
        : Subgroup G) ∪ {u, (g : G)})
      = fc.sylowThreeNormalizerRSigma model := by
    refine le_antisymm ?_ ?_
    · rw [Subgroup.closure_le]
      rintro y (hy | hy)
      · exact (fc.sup_le_sylowThreeNormalizerRSigma model ind hB2)
          (sup_le (sup_le (hZ₁R.trans le_sup_left) le_sup_right)
            (hPR.trans le_sup_left) hy)
      · rcases hy with rfl | rfl
        · exact (fc.sup_le_sylowThreeNormalizerRSigma model ind hB2)
            (Subgroup.mem_sup_left huR)
        · exact fc.nonsplitTorus_le_sylowThreeNormalizerRSigma model ind hB2 g.2
    · rw [← fc.sup_invImageF_centralizer_W_sup_nonsplitTorus_eq model ind hB2]
      refine sup_le (sup_le ?_ ?_) ?_
      · refine le_trans (le_of_eq hR_eq.symm) ?_
        refine sup_le (sup_le ?_ ?_) ?_
        · exact fun y hy => Subgroup.subset_closure
            (Or.inl (Subgroup.mem_sup_left (Subgroup.mem_sup_left hy)))
        · exact fun y hy => Subgroup.subset_closure
            (Or.inl (Subgroup.mem_sup_right hy))
        · exact Subgroup.zpowers_le.mpr (Subgroup.subset_closure (Or.inr (by simp)))
      · exact fun y hy => Subgroup.subset_closure
          (Or.inl (Subgroup.mem_sup_left (Subgroup.mem_sup_right hy)))
      · refine le_trans (le_of_eq hLgen.symm) ?_
        exact Subgroup.zpowers_le.mpr (Subgroup.subset_closure (Or.inr (by simp)))
  -- apply the generic bound
  have hbound := commutator_le_of_two_generators
    (X := fc.sylowThreeNormalizerRSigma model)
    (N := (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
    (Z := Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t))
    (u := u) (v := (g : G))
    (fun z hz x hx => by
      have hmem : z ∈ fc.sylowThreeNormalizerRSigma model ⊓ Subgroup.centralizer
          ((fc.sylowThreeNormalizerRSigma model : Subgroup G) : Set G) := by
        rw [fc.inf_centralizer_sylowThree_eq_zpowers model ind hB2]
        exact hz
      exact (Subgroup.mem_centralizer_iff.mp hmem.2 x hx).symm)
    (fc.commutator_zpowers_sup_sigma_sup_P_sylowThree_le model ind hB2) hcommN
    ((fc.sup_le_sylowThreeNormalizerRSigma model ind hB2)
      (Subgroup.mem_sup_left huR))
    (fc.nonsplitTorus_le_sylowThreeNormalizerRSigma model ind hB2 g.2) hgen
  -- the bounding subgroup has order at most `9`
  set c : G := ⁅u, (g : G)⁆ with hc_def
  have hc3 : c ^ 3 = 1 := by
    have hcN : c ∈ (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P :=
      hcommN (Subgroup.commutator_mem_commutator
        ((fc.sup_le_sylowThreeNormalizerRSigma model ind hB2)
          (Subgroup.mem_sup_left huR))
        (fc.nonsplitTorus_le_sylowThreeNormalizerRSigma model ind hB2 g.2))
    exact (fc.pow_three_eq_one_iff_mem_zpowers_sup_sigma_sup_P model ind hB2
      (by
        refine sup_le (sup_le (fc.zpowers_le_nonsplitTorus.trans le_sup_left)
          ((inf_le_left.trans fc.toHypothesis.W_le_V).trans le_sup_right))
          (fc.P_le_V.trans le_sup_right) hcN)).mpr hcN
  have hMcard : Nat.card ↥(Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) ⊔ Subgroup.zpowers c) ≤ 9 := by
    by_cases hcZ : c ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t)
    · have heq : Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t) ⊔ Subgroup.zpowers c
          = Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
            * fc.toHypothesis.t) :=
        sup_eq_left.mpr (Subgroup.zpowers_le.mpr hcZ)
      rw [heq, hZ₁card]
      norm_num
    · have hcord : Nat.card ↥(Subgroup.zpowers c) ≤ 3 := by
        have hdvd : orderOf c ∣ 3 := orderOf_dvd_iff_pow_eq_one.mpr hc3
        rw [Nat.card_zpowers]
        exact Nat.le_of_dvd (by norm_num) hdvd
      have hinf : Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t) ⊓ Subgroup.zpowers c = ⊥ := by
        rw [eq_bot_iff]
        intro y hy
        rw [Subgroup.mem_bot]
        by_contra hy1
        refine hcZ ?_
        have hyord : orderOf y = 3 := by
          have hdvd : orderOf y ∣ 3 := by
            have h := Subgroup.orderOf_dvd_natCard _ hy.1
            rwa [hZ₁card] at h
          rcases (Nat.dvd_prime (by norm_num)).mp hdvd with h1 | h3
          · exact absurd (orderOf_eq_one_iff.mp h1) hy1
          · exact h3
        have hccard : Nat.card ↥(Subgroup.zpowers c) = 3 := by
          refine le_antisymm hcord ?_
          rw [← hyord, ← Nat.card_zpowers]
          exact Nat.le_of_dvd Nat.card_pos
            (Subgroup.card_dvd_of_le (Subgroup.zpowers_le.mpr hy.2))
        have heq : Subgroup.zpowers y = Subgroup.zpowers c :=
          Subgroup.eq_of_le_of_card_ge (Subgroup.zpowers_le.mpr hy.2)
            (by rw [hccard, Nat.card_zpowers, hyord])
        obtain ⟨k, hk⟩ : c ∈ Subgroup.zpowers y := by
          rw [heq]; exact Subgroup.mem_zpowers _
        rw [← hk]
        exact Subgroup.zpow_mem _ hy.1 k
      have hcomm : ∀ a ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t), ∀ b ∈ Subgroup.zpowers c, a * b = b * a := by
        intro a ha b hb
        have hmem : a ∈ fc.sylowThreeNormalizerRSigma model ⊓ Subgroup.centralizer
            ((fc.sylowThreeNormalizerRSigma model : Subgroup G) : Set G) := by
          rw [fc.inf_centralizer_sylowThree_eq_zpowers model ind hB2]
          exact ha
        obtain ⟨k, rfl⟩ := hb
        have huR₁ : u ∈ fc.sylowThreeNormalizerRSigma model :=
          (fc.sup_le_sylowThreeNormalizerRSigma model ind hB2)
            (Subgroup.mem_sup_left huR)
        have hgR₁ : (g : G) ∈ fc.sylowThreeNormalizerRSigma model :=
          fc.nonsplitTorus_le_sylowThreeNormalizerRSigma model ind hB2 g.2
        have hcR₁ : c ∈ fc.sylowThreeNormalizerRSigma model := by
          rw [hc_def, commutatorElement_def]
          exact Subgroup.mul_mem _ (Subgroup.mul_mem _
            (Subgroup.mul_mem _ huR₁ hgR₁) (Subgroup.inv_mem _ huR₁))
            (Subgroup.inv_mem _ hgR₁)
        exact (Commute.zpow_right
          (Subgroup.mem_centralizer_iff.mp hmem.2 c hcR₁).symm k).eq
      rw [card_sup_eq_mul_of_commute hcomm hinf, hZ₁card]
      omega
  exact le_trans (Nat.le_of_dvd Nat.card_pos (Subgroup.card_dvd_of_le hbound)) hMcard

include model in
/-- **`⁅R₁, R₁⁆ ≤ Z₁ΣP`**: `Z₁ΣP` is normal in `R₁` by (16), and the quotient has
order `3⁵/27 = 9 = 3²`, hence is abelian. -/
theorem commutator_sylowThree_le_zpowers_sup_sigma_sup_P
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    ⁅fc.sylowThreeNormalizerRSigma model, fc.sylowThreeNormalizerRSigma model⁆
      ≤ (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  obtain ⟨-, hp3, hF9, -, -, -⟩ := fc.step_twelve model ind hB2
  have hm : Nat.card F = fc.p ^ 2 := by rw [hF9, hp3]; norm_num
  have hZ₁R : Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) ≤ fc.invImageF model :=
    (fc.zpowers_distinguishedInvolution_mul_t_le_sInvertedT model ind hB2 hm).trans
      (fc.sInvertedT_spec model ind hB2 hm).1
  have hZSP_R₁ : ((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
      ≤ fc.sylowThreeNormalizerRSigma model :=
    (sup_le (sup_le (hZ₁R.trans le_sup_left) le_sup_right)
      ((fc.P_le_invImageF model).trans le_sup_left)).trans
      (fc.sup_le_sylowThreeNormalizerRSigma model ind hB2)
  have hcommZ := fc.commutator_zpowers_sup_sigma_sup_P_sylowThree_le model ind hB2
  -- `Z₁ΣP` is normal in `R₁`
  haveI hnorm : (((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P).subgroupOf
        (fc.sylowThreeNormalizerRSigma model)).Normal := by
    constructor
    intro n hn g
    rw [Subgroup.mem_subgroupOf] at hn ⊢
    have hc : ⁅(n : G), (g : G)⁆ ∈ Subgroup.zpowers
        (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t) :=
      hcommZ (Subgroup.commutator_mem_commutator hn g.2)
    have h1 : ((g : G) * (n : G) * (g : G)⁻¹) = ⁅(n : G), (g : G)⁆⁻¹ * (n : G) := by
      rw [commutatorElement_def]; group
    change ((g : G) * (n : G) * (g : G)⁻¹) ∈ _
    rw [h1]
    exact Subgroup.mul_mem _
      (Subgroup.inv_mem _ (Subgroup.mem_sup_left (Subgroup.mem_sup_left hc))) hn
  -- the quotient has order `9`
  have hZSPcard := fc.card_zpowers_sup_sigma_sup_P model ind hB2
  have hR₁card := fc.card_sylowThreeNormalizerRSigma model ind hB2
  have hcardQ : Nat.card (↥(fc.sylowThreeNormalizerRSigma model)
      ⧸ ((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P).subgroupOf
          (fc.sylowThreeNormalizerRSigma model)) = 3 ^ 2 := by
    rw [← Subgroup.index_eq_card]
    have h := (((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P).subgroupOf
        (fc.sylowThreeNormalizerRSigma model)).card_mul_index
    rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe hZSP_R₁).toEquiv, hZSPcard,
      hR₁card] at h
    omega
  haveI : IsMulCommutative (↥(fc.sylowThreeNormalizerRSigma model)
      ⧸ ((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P).subgroupOf
          (fc.sylowThreeNormalizerRSigma model)) :=
    IsPGroup.isMulCommutative_of_card_eq_prime_sq (p := 3) hcardQ
  -- commutators die in the quotient
  refine Subgroup.commutator_le.mpr fun a ha b hb => ?_
  have hq := ‹IsMulCommutative _›.is_comm.comm
    (QuotientGroup.mk (⟨a, ha⟩ : ↥(fc.sylowThreeNormalizerRSigma model)))
    (QuotientGroup.mk (⟨b, hb⟩ : ↥(fc.sylowThreeNormalizerRSigma model)))
  set N₀ : Subgroup ↥(fc.sylowThreeNormalizerRSigma model) :=
    ((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P).subgroupOf
        (fc.sylowThreeNormalizerRSigma model) with hN₀_def
  have hone : ⁅(⟨a, ha⟩ : ↥(fc.sylowThreeNormalizerRSigma model)),
      (⟨b, hb⟩ : ↥(fc.sylowThreeNormalizerRSigma model))⁆ ∈ N₀ := by
    have h1 : (QuotientGroup.mk' N₀)
        ⁅(⟨a, ha⟩ : ↥(fc.sylowThreeNormalizerRSigma model)),
          (⟨b, hb⟩ : ↥(fc.sylowThreeNormalizerRSigma model))⁆ = 1 := by
      rw [map_commutatorElement]
      exact commutatorElement_eq_one_iff_commute.mpr hq
    rwa [QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff] at h1
  rw [hN₀_def, Subgroup.mem_subgroupOf] at hone
  have hcoe : ((⁅(⟨a, ha⟩ : ↥(fc.sylowThreeNormalizerRSigma model)),
      (⟨b, hb⟩ : ↥(fc.sylowThreeNormalizerRSigma model))⁆ : _) : G) = ⁅a, b⁆ :=
    map_commutatorElement (fc.sylowThreeNormalizerRSigma model).subtype _ _
  rwa [hcoe] at hone

/-! ## The endpoint of (17) -/

include model in
/-- **The final contradiction of (17)** (p. 114), as an engine parameterised by its two
remaining inputs.

* `hcontrol` is the transfer-control conclusion: by the weak closure of the abelian
  `Z₁PΣ` in `R₂` (`map_conj_eq_of_le_sylow`), the Hall–Wielandt theorem gives
  `G/O³(G) ≅ N_G(Z₁PΣ)/O³(N_G(Z₁PΣ))`, so hypothesis (B2) (`p ∤ |G^{ab}|`) transports
  to `N_G(Z₁PΣ)`.  See issue 9503.
* `hW3` is the `|W| = 3` branch, where `R₂ = R₁` and the structure of `R̄₁ = R₁/Z₁`
  produces the quotient of order `3`; the `|W| = 9` branch is
  `three_dvd_card_abelianization_of_card_W_eq_nine`, proved above. -/
theorem false_of_transfer_control
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) (S : Sylow 3 G)
    (hR₁S : fc.sylowThreeNormalizerRSigma model ≤ (S : Subgroup G))
    (hcontrol : ¬ (3 : ℕ) ∣ Nat.card (Abelianization
      ↥(Subgroup.normalizer ((((Subgroup.zpowers
            (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t)
          ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
            : Subgroup G) : Set G))))
    (hW3 : Nat.card ↥fc.toHypothesis.W = 3 →
      (3 : ℕ) ∣ Nat.card (Abelianization ↥((S : Subgroup G)
        ⊔ Subgroup.zpowers fc.toHypothesis.distinguishedInvolution))) :
    False := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  obtain ⟨-, -, -, -, hW, -⟩ := fc.step_twelve model ind hB2
  have hNeq : Subgroup.normalizer ((((Subgroup.zpowers
        (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
        : Subgroup G) : Set G)
      = (S : Subgroup G)
        ⊔ Subgroup.zpowers fc.toHypothesis.distinguishedInvolution := by
    rw [← fc.normalizer_zpowers_eq_normalizer_zpowers_sup_sigma_sup_P model ind hB2
      S hR₁S]
    exact fc.normalizer_zpowers_eq_sylow_sup_zpowers model ind hB2 S hR₁S
  rw [hNeq] at hcontrol
  rcases hW with h3 | h9
  · exact hcontrol (hW3 h3)
  · exact hcontrol
      (fc.three_dvd_card_abelianization_of_card_W_eq_nine model ind hB2 S hR₁S h9)

end FirstCaseHypothesis

end OddOrder.Peterfalvi.Appendices.Suzuki
