/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Peterfalvi.Appendices.Suzuki.FirstCase.StepFifteenLV

/-!
# Peterfalvi Part II, Ch. II, step (16)

T. Peterfalvi, *Character Theory for the Odd Order Theorem* (LMS LNS 272,
2000), Part II, Ch. II, (16), p. 114.

> **(16)** `Z₁PΣ ⊆ Z₂(R₁)`, `Z₁` is the only subgroup of order `3` in `Z₁PΣ` consisting
> of strongly real elements, and `N_G(Z₁PΣ) = N_G(Z₁) = R₂⟨s⟩`.

This file collects the structural facts about `R₁` that the proof needs.  The first is
that `L` fills up `R₁` over `RΣ`: `RΣ` has index `3` in `R₁` by (14), and `L ⊄ RΣ`
by (15), so `R₁ = RΣL`.
-/

set_option autoImplicit false

open scoped Pointwise commutatorElement

namespace OddOrder.Peterfalvi.Appendices.Suzuki

section GenericConj

variable {G' : Type*} [Group G']

/-- Iterating a conjugation relation `a^g = a·d` with `d` central for `a` and `g`. -/
theorem conj_pow_eq_mul_pow {a d g : G'} (hdg : Commute d g)
    (h : g * a * g⁻¹ = a * d) : ∀ m : ℕ, g ^ m * a * (g ^ m)⁻¹ = a * d ^ m := by
  intro m
  induction m with
  | zero => simp
  | succ n ih =>
      calc g ^ (n + 1) * a * (g ^ (n + 1))⁻¹
          = g * (g ^ n * a * (g ^ n)⁻¹) * g⁻¹ := by rw [pow_succ']; group
        _ = g * (a * d ^ n) * g⁻¹ := by rw [ih]
        _ = (g * a * g⁻¹) * (g * d ^ n * g⁻¹) := by group
        _ = (a * d) * d ^ n := by
              rw [h, ← (hdg.pow_left n).eq]
              group
        _ = a * d ^ (n + 1) := by rw [pow_succ]; group

/-- A conjugate of a strongly real element is strongly real. -/
theorem isStronglyReal_conj {x : G'} (hx : IsStronglyReal x) (g : G') :
    IsStronglyReal (g * x * g⁻¹) := by
  obtain ⟨u, ⟨hu2, hu1⟩, v, ⟨hv2, hv1⟩, rfl⟩ := hx
  refine ⟨g * u * g⁻¹, ⟨?_, ?_⟩, g * v * g⁻¹, ⟨?_, ?_⟩, by group⟩
  · rw [show (g * u * g⁻¹) ^ 2 = g * u ^ 2 * g⁻¹ by rw [pow_two, pow_two]; group,
      hu2]
    group
  · intro h
    refine hu1 ?_
    have h2 : u = g⁻¹ * (g * u * g⁻¹) * g := by group
    rw [h] at h2
    simpa using h2
  · rw [show (g * v * g⁻¹) ^ 2 = g * v ^ 2 * g⁻¹ by rw [pow_two, pow_two]; group,
      hv2]
    group
  · intro h
    refine hv1 ?_
    have h2 : v = g⁻¹ * (g * v * g⁻¹) * g := by group
    rw [h] at h2
    simpa using h2

end GenericConj

namespace FirstCaseHypothesis

universe uG uΩ

variable {G : Type uG} {Ω : Type uΩ} [Group G] [MulAction G Ω] [Finite G]
  (fc : FirstCaseHypothesis G Ω)
  {F : Type uG} [NearFields.NearField F]
  (model : letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
    NearFields.AffineNearFieldModel fc.rankOneQuotient F)

include model in
/-- **`R₁ = RΣL`** (implicit in (16)/(17), p. 114: "`R₁` is generated by the subgroups
`RΣ` and `LΣP` since `L ⊄ RΣ`").

`|RΣ| = 3⁴` and `|R₁| = 3⁵` by (14), so `RΣ` is maximal in `R₁`; and `L ≤ R₁` but
`L ⊄ RΣ` by (15). -/
theorem sup_invImageF_centralizer_W_sup_nonsplitTorus_eq
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    (fc.invImageF model ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)))
        ⊔ fc.nonsplitTorus
      = fc.sylowThreeNormalizerRSigma model := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  have hRScard := fc.card_sup_invImageF_centralizer_W_eq model ind hB2
  have hR₁card := fc.card_sylowThreeNormalizerRSigma model ind hB2
  have hle : (fc.invImageF model
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)))
      ⊔ fc.nonsplitTorus ≤ fc.sylowThreeNormalizerRSigma model :=
    sup_le (fc.sup_le_sylowThreeNormalizerRSigma model ind hB2)
      (fc.nonsplitTorus_le_sylowThreeNormalizerRSigma model ind hB2)
  -- the order of `RΣL` is a multiple of `3⁴` dividing `3⁵`
  obtain ⟨m, hm⟩ := Subgroup.card_dvd_of_le
    (le_sup_left : (fc.invImageF model
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)))
      ≤ _ ⊔ fc.nonsplitTorus)
  have hdvd : Nat.card ↥((fc.invImageF model
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)))
        ⊔ fc.nonsplitTorus) ∣ 3 ^ 5 := by
    rw [← hR₁card]
    exact Subgroup.card_dvd_of_le hle
  have hm3 : m ∣ 3 := by
    rw [hm, hRScard] at hdvd
    refine (Nat.mul_dvd_mul_iff_left (show 0 < 3 ^ 4 by norm_num)).mp ?_
    calc 3 ^ 4 * m ∣ 3 ^ 5 := hdvd
      _ = 3 ^ 4 * 3 := by norm_num
  rcases (Nat.dvd_prime (by norm_num)).mp hm3 with h1 | h3
  · -- `RΣL = RΣ` would put `L` inside `RΣ`
    exfalso
    refine fc.not_nonsplitTorus_le_sup_invImageF_centralizer_W model ind hB2 ?_
    have heq : (fc.invImageF model
          ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)))
        ⊔ fc.nonsplitTorus
        = fc.invImageF model
          ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) :=
      (Subgroup.eq_of_le_of_card_ge le_sup_left (by rw [hm, h1, mul_one])).symm
    rw [← heq]
    exact le_sup_right
  · refine Subgroup.eq_of_le_of_card_ge hle ?_
    rw [hm, h3, hRScard, hR₁card]
    norm_num

include model in
/-- `L ⊓ Z₁Σ = Z₁`: a factor `σ ∈ Σ ≤ W` of an element of `L` would lie in
`L ⊓ W = 1`. -/
theorem nonsplitTorus_inf_zpowers_sup_sigma_eq
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    fc.nonsplitTorus ⊓ (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)))
      = Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  have hcoe := coe_sup_eq_mul_of_commute
    (fun _ (ha : _ ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)) _
      (hb : _ ∈ fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) =>
      fc.commute_of_mem_nonsplitTorus_of_mem_W (fc.zpowers_le_nonsplitTorus ha) hb.1)
  refine le_antisymm (fun x hx => ?_)
    (le_inf fc.zpowers_le_nonsplitTorus le_sup_left)
  have hx' : x ∈ ((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) : Subgroup G) : Set G)
      * ((fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G) : Subgroup G)
        : Set G) := by
    rw [← hcoe]; exact hx.2
  obtain ⟨z, hz, σ, hσ, hzσ0⟩ := hx'
  have hzσ : z * σ = x := hzσ0
  have hzL : z ∈ fc.nonsplitTorus := fc.zpowers_le_nonsplitTorus hz
  have hσL : σ ∈ fc.nonsplitTorus := by
    have : σ = z⁻¹ * x := by rw [← hzσ]; group
    rw [this]
    exact Subgroup.mul_mem _ (Subgroup.inv_mem _ hzL) hx.1
  have hσ1 : σ = 1 := by
    have hmem : σ ∈ fc.nonsplitTorus ⊓ fc.toHypothesis.W := ⟨hσL, hσ.1⟩
    rwa [fc.nonsplitTorus_inf_W_eq_bot model ind hB2, Subgroup.mem_bot] at hmem
  rw [← hzσ, hσ1, mul_one]
  exact hz

include model in
/-- **`⁅P, L⁆ ≤ Z₁`**: `l⁻¹·l^q` lies in `Z₁Σ` by (15) and in `L` because `P`
normalizes `L`, hence in `L ⊓ Z₁Σ = Z₁`. -/
theorem commutatorElement_mem_zpowers_of_mem_P_of_mem_nonsplitTorus
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) {q l : G} (hq : q ∈ fc.P)
    (hl : l ∈ fc.nonsplitTorus) :
    ⁅q, l⁆ ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  have hconj : q * l * q⁻¹ ∈ fc.nonsplitTorus := by
    have hn := fc.P_le_normalizer_nonsplitTorus model ind hB2 hq
    rw [Subgroup.mem_set_normalizer_iff] at hn
    exact (hn l).mp hl
  have hdZS := fc.inv_mul_conj_mem_zpowers_sup_sigma model ind hB2
    (Subgroup.mem_sup_left hl) hq
  have hdL : l⁻¹ * (q * l * q⁻¹) ∈ fc.nonsplitTorus :=
    Subgroup.mul_mem _ (Subgroup.inv_mem _ hl) hconj
  have hdZ : l⁻¹ * (q * l * q⁻¹)
      ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) := by
    rw [← fc.nonsplitTorus_inf_zpowers_sup_sigma_eq model ind hB2]
    exact ⟨hdL, hdZS⟩
  -- `⁅q, l⁆ = l·(l⁻¹·l^q)·l⁻¹` and `l` centralizes `st`
  have hlst : l * (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t)
      = (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t) * l := by
    rw [fc.nonsplitTorus_def] at hl
    exact Subgroup.mem_centralizer_singleton_iff.mp hl.1
  have hlcen : ∀ z ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t), l * z * l⁻¹ = z := by
    intro z hz
    have hcen : l ∈ Subgroup.centralizer ((Subgroup.zpowers
        (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t)
          : Subgroup G) : Set G) := by
      rw [fc.centralizer_zpowers_st_eq]
      exact Subgroup.mem_centralizer_singleton_iff.mpr hlst
    have := Subgroup.mem_centralizer_iff.mp hcen z hz
    rw [← this]; group
  have heq : ⁅q, l⁆ = l * (l⁻¹ * (q * l * q⁻¹)) * l⁻¹ := by
    rw [commutatorElement_def]; group
  rw [heq, hlcen _ hdZ]
  exact hdZ

include model in
/-- **`⁅Z₁ΣP, R₁⁆ ≤ Z₁`**, i.e. `Z₁PΣ ⊆ Z₂(R₁)` ((16), p. 114).

`Z₁ΣP ≤ RΣ` and `⁅RΣ, RΣ⁆ = Z₁` by (14) handle the `RΣ`-part of `R₁ = RΣL`; against
`L` the factors `Z₁Σ` centralize `L` (they lie in `L` itself and in `W`) and
`⁅P, L⁆ ≤ Z₁`. -/
theorem commutator_zpowers_sup_sigma_sup_P_sylowThree_le
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    ⁅(Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P,
      fc.sylowThreeNormalizerRSigma model⁆
      ≤ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  obtain ⟨-, hp3, hF9, -, -, -⟩ := fc.step_twelve model ind hB2
  have hm : Nat.card F = fc.p ^ 2 := by rw [hF9, hp3]; norm_num
  have hZ₁R : Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) ≤ fc.invImageF model :=
    (fc.zpowers_distinguishedInvolution_mul_t_le_sInvertedT model ind hB2 hm).trans
      (fc.sInvertedT_spec model ind hB2 hm).1
  -- `Z₁ΣP ≤ RΣ`
  have hZSP_le : (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P
      ≤ fc.invImageF model
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) :=
    sup_le (sup_le (hZ₁R.trans le_sup_left) le_sup_right)
      ((fc.P_le_invImageF model).trans le_sup_left)
  -- `Z₁Σ` centralizes `L`
  have hZScenL : ∀ z ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)),
      ∀ l ∈ fc.nonsplitTorus, z * l = l * z := by
    obtain ⟨hLcyc, -⟩ := fc.isCyclic_and_card_nonsplitTorus model ind hB2
    have hle : (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)))
        ≤ Subgroup.centralizer (fc.nonsplitTorus : Set G) := by
      refine sup_le ?_ ?_
      · intro z hz
        refine Subgroup.mem_centralizer_iff.mpr fun y hy => ?_
        exact mul_comm_of_mem_of_isCyclic hLcyc hy (fc.zpowers_le_nonsplitTorus hz)
      · intro z hz
        refine Subgroup.mem_centralizer_iff.mpr fun y hy => ?_
        exact fc.commute_of_mem_nonsplitTorus_of_mem_W hy hz.1
    intro z hz l hl
    exact (Subgroup.mem_centralizer_iff.mp (hle hz) l hl).symm
  -- against `L`
  have hL : ∀ x ∈ (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P,
      ∀ l ∈ fc.nonsplitTorus, ⁅x, l⁆ ∈ Subgroup.zpowers
        (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t) := by
    have hcoe := coe_sup_eq_mul_of_commute
      (fun _ (ha : _ ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) _
        (hb : _ ∈ fc.P) =>
        (Subgroup.mem_centralizer_iff.mp
          (sup_le (fc.zpowers_st_le_centralizer_P model ind hB2) inf_le_right ha) _
            hb).symm)
    intro x hx l hl
    have hx' : x ∈ ((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) : Subgroup G)
          : Set G) * (fc.P : Set G) := by
      rw [← hcoe]; exact hx
    obtain ⟨z, hz, q, hq, rfl⟩ := hx'
    have hql : q * l * q⁻¹ ∈ fc.nonsplitTorus := by
      have hn := fc.P_le_normalizer_nonsplitTorus model ind hB2 hq
      rw [Subgroup.mem_set_normalizer_iff] at hn
      exact (hn l).mp hl
    have hsplit : ⁅z * q, l⁆ = ⁅q, l⁆ := by
      have h1 : z * (q * l * q⁻¹) = (q * l * q⁻¹) * z := hZScenL z hz _ hql
      rw [commutatorElement_def, commutatorElement_def]
      calc z * q * l * (z * q)⁻¹ * l⁻¹ = z * (q * l * q⁻¹) * z⁻¹ * l⁻¹ := by group
        _ = (q * l * q⁻¹) * z * z⁻¹ * l⁻¹ := by rw [h1]
        _ = q * l * q⁻¹ * l⁻¹ := by group
    rw [hsplit]
    exact fc.commutatorElement_mem_zpowers_of_mem_P_of_mem_nonsplitTorus model ind hB2
      hq hl
  -- assembly, using `R₁ = RΣL`
  rw [Subgroup.commutator_le]
  intro x hx y hy
  rw [← fc.sup_invImageF_centralizer_W_sup_nonsplitTorus_eq model ind hB2] at hy
  have hcoeR : (((fc.invImageF model
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)))
      ⊔ fc.nonsplitTorus : Subgroup G) : Set G)
      = ((fc.invImageF model
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) : Subgroup G)
          : Set G) * (fc.nonsplitTorus : Set G) := by
    refine Subgroup.coe_mul_of_right_le_normalizer_left _ _ ?_
    intro b hb
    exact fc.sylowThreeNormalizerRSigma_le model
      (fc.nonsplitTorus_le_sylowThreeNormalizerRSigma model ind hB2 hb)
  have hy' : y ∈ ((fc.invImageF model
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) : Subgroup G)
        : Set G) * (fc.nonsplitTorus : Set G) := by rw [← hcoeR]; exact hy
  obtain ⟨r, hr, l, hl, rfl⟩ := hy'
  -- `⁅x, rl⁆ = ⁅x, r⁆ · r⁅x, l⁆r⁻¹`
  have hxr : ⁅x, r⁆ ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) := by
    rw [← fc.commutator_sup_eq_zpowers model ind hB2]
    exact Subgroup.commutator_mem_commutator (hZSP_le hx) hr
  have hxl := hL x hx l hl
  have hrfix : r * ⁅x, l⁆ * r⁻¹ = ⁅x, l⁆ := by
    have hZcen : ∀ z ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t), z * r = r * z := by
      intro z hz
      have hmem : z ∈ (fc.invImageF model
          ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) : Subgroup G)
            ⊓ Subgroup.centralizer (((fc.invImageF model
              ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)))
                : Subgroup G) : Set G) := by
        rw [fc.inf_centralizer_sup_eq_zpowers_sup_P model ind hB2]
        exact Subgroup.mem_sup_left hz
      exact (Subgroup.mem_centralizer_iff.mp hmem.2 r hr).symm
    rw [← hZcen _ hxl]; group
  have hprod : ⁅x, r * l⁆ = ⁅x, r⁆ * (r * ⁅x, l⁆ * r⁻¹) := by
    rw [commutatorElement_def, commutatorElement_def, commutatorElement_def]
    group
  rw [hprod, hrfix]
  exact Subgroup.mul_mem _ hxr hxl

include fc in
/-- **No element `x ∈ V` with `x² ≠ 1` is strongly real** ((16), p. 114, the
contradiction step; it generalizes `not_isStronglyReal_of_mem_P` from `P` to `V ⊇ PΣ`).

`V = C_D(t) ≤ C_G(s)`, so the involution `s` centralizes `x` and `|C_G(x)|` is even;
but a strongly real element with `x² ≠ 1` has odd centralizer (Ch. I §3, Lemma 3). -/
theorem not_isStronglyReal_of_mem_V {x : G} (hx : x ∈ fc.toHypothesis.V)
    (hx2 : x ^ 2 ≠ 1) : ¬ IsStronglyReal x := by
  intro hsr
  obtain ⟨-, hodd⟩ :=
    fc.toHypothesis.stronglyReal_normalForm_and_centralizer_odd hsr hx2
  set s : G := fc.toHypothesis.distinguishedInvolution with hsdef
  have hsC : s ∈ Subgroup.centralizer ({x} : Set G) := by
    rw [Subgroup.mem_centralizer_iff]
    intro y hy
    rw [Set.mem_singleton_iff] at hy
    subst hy
    exact (Subgroup.mem_centralizer_singleton_iff.mp
      (fc.toHypothesis.V_le_centralizer_distinguishedInvolution hx).2)
  have hs2 : orderOf s = 2 := by
    have h1 : s ^ 2 = 1 := fc.toHypothesis.distinguishedInvolution_sq
    have h2 : orderOf s ∣ 2 := orderOf_dvd_of_pow_eq_one h1
    rcases (Nat.dvd_prime Nat.prime_two).mp h2 with h | h
    · exact absurd (orderOf_eq_one_iff.mp h)
        fc.toHypothesis.distinguishedInvolution_ne_one
    · exact h
  have heven : (2 : ℕ) ∣ Nat.card ↥(Subgroup.centralizer ({x} : Set G)) := by
    have h1 : orderOf (⟨s, hsC⟩ : ↥(Subgroup.centralizer ({x} : Set G)))
        ∣ Nat.card ↥(Subgroup.centralizer ({x} : Set G)) := orderOf_dvd_natCard _
    rwa [Subgroup.orderOf_mk, hs2] at h1
  rcases hodd with ⟨k, hk⟩
  omega

include model in
/-- **No nonidentity element of `PΣ` is strongly real** ((16), p. 114): `PΣ ≤ V` and
its nonidentity elements have order `3`. -/
theorem not_isStronglyReal_of_mem_P_sup_sigma
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) {x : G}
    (hx : x ∈ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) ⊔ fc.P)
    (hx1 : x ≠ 1) : ¬ IsStronglyReal x := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  obtain ⟨hpSig, hp3, -, -, -, -⟩ := fc.step_twelve model ind hB2
  obtain ⟨-, -, -, hSig3, -⟩ :=
    fc.card_field_eq_nine_of_p_dvd_card_centralizer_W ind model hB2 hpSig
  have hle : ((fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) ⊔ fc.P
      : Subgroup G) ≤ fc.toHypothesis.V :=
    sup_le (le_trans inf_le_left fc.toHypothesis.W_le_V) fc.P_le_V
  refine fc.not_isStronglyReal_of_mem_V (hle hx) ?_
  -- every element of `ΣP` is killed by `3`
  have hx3 : x ^ 3 = 1 := by
    refine pow_eq_one_of_mem_sup_of_commute ?_ ?_ ?_ hx
    · intro a ha b hb
      exact (Subgroup.mem_centralizer_iff.mp ha.2 b hb).symm
    · intro a ha
      have h := Subgroup.orderOf_dvd_natCard _ ha
      rw [hSig3] at h
      exact orderOf_dvd_iff_pow_eq_one.mp h
    · intro b hb
      have h := Subgroup.orderOf_dvd_natCard _ hb
      rw [fc.card_P, hp3] at h
      exact orderOf_dvd_iff_pow_eq_one.mp h
  intro h2
  have hord : orderOf x ∣ 3 := orderOf_dvd_iff_pow_eq_one.mpr hx3
  have hord2 : orderOf x ∣ 2 := orderOf_dvd_iff_pow_eq_one.mpr h2
  have h1 : orderOf x = 1 := Nat.eq_one_of_dvd_coprimes (by decide) hord2 hord
  exact hx1 (orderOf_eq_one_iff.mp h1)

/-! ## The elementary abelian group `Z₁ΣP` of order `27` -/

include model in
/-- `Z₁Σ ⊓ P = 1`: a nonidentity element would generate `P` inside `Z(LV) = Z₁Σ`,
making `P` centralize `L`. -/
theorem zpowers_sup_sigma_inf_P_eq_bot
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊓ fc.P = ⊥ := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  obtain ⟨-, hp3, -, -, -, -⟩ := fc.step_twelve model ind hB2
  have hPcard : Nat.card ↥fc.P = 3 := by rw [fc.card_P, hp3]
  have hZScen : (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)))
      ≤ Subgroup.centralizer (((fc.nonsplitTorus ⊔ fc.toHypothesis.V) : Subgroup G)
        : Set G) := by
    rw [← fc.inf_centralizer_sup_nonsplitTorus_V_eq model ind hB2]
    exact inf_le_right
  rw [eq_bot_iff]
  intro y hy
  rw [Subgroup.mem_bot]
  by_contra hy1
  have hyord : orderOf y = 3 := by
    have h := fc.P.orderOf_dvd_natCard hy.2
    rw [hPcard] at h
    rcases (Nat.dvd_prime (by norm_num)).mp h with h1 | h3
    · exact absurd (orderOf_eq_one_iff.mp h1) hy1
    · exact h3
  have hgen : Subgroup.zpowers y = fc.P :=
    Subgroup.eq_of_le_of_card_ge (Subgroup.zpowers_le.mpr hy.2)
      (by rw [Nat.card_zpowers, hyord, hPcard])
  refine fc.not_nonsplitTorus_le_centralizer_P model ind hB2 fun l hl => ?_
  refine Subgroup.mem_centralizer_iff.mpr fun q hq => ?_
  rw [← hgen] at hq
  obtain ⟨k, rfl⟩ := hq
  have hycen := Subgroup.mem_centralizer_iff.mp (hZScen hy.1) l
    (Subgroup.mem_sup_left hl)
  exact (Commute.zpow_left (Commute.symm hycen) k).eq

include model in
/-- `Z₁Σ` is abelian: it is `Z(LV)` by (15). -/
theorem mul_comm_of_mem_zpowers_sup_sigma
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) {a b : G}
    (ha : a ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)))
    (hb : b ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) :
    a * b = b * a := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  rw [← fc.inf_centralizer_sup_nonsplitTorus_V_eq model ind hB2] at ha hb
  exact (Subgroup.mem_centralizer_iff.mp ha.2 b hb.1).symm

include model in
/-- `Z₁ΣP` is abelian. -/
theorem mul_comm_of_mem_zpowers_sup_sigma_sup_P
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) {a b : G}
    (ha : a ∈ (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
    (hb : b ∈ (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P) :
    a * b = b * a := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  obtain ⟨-, hp3, hF9, -, -, -⟩ := fc.step_twelve model ind hB2
  have hm : Nat.card F = fc.p ^ 2 := by rw [hF9, hp3]; norm_num
  have habR := fc.invImageF_mul_comm model ind hB2 hm
  refine mul_comm_of_mem_sup_of_commute
    (fun _ h₁ _ h₂ => fc.mul_comm_of_mem_zpowers_sup_sigma model ind hB2 h₁ h₂)
    (fun _ h₁ _ h₂ => habR _ (fc.P_le_invImageF model h₁) _
      (fc.P_le_invImageF model h₂))
    (fun _ h₁ _ h₂ => (Subgroup.mem_centralizer_iff.mp
      (sup_le (fc.zpowers_st_le_centralizer_P model ind hB2) inf_le_right h₁) _ h₂).symm)
    ha hb

include model in
/-- `|Z₁Σ| = 9`. -/
theorem card_zpowers_sup_sigma
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    Nat.card ↥(Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) = 9 := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  obtain ⟨hpSig, hp3, -, -, -, -⟩ := fc.step_twelve model ind hB2
  obtain ⟨-, -, -, hSig3, -⟩ :=
    fc.card_field_eq_nine_of_p_dvd_card_centralizer_W ind model hB2 hpSig
  have hstord : orderOf (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) = 3 := by
    rw [fc.orderOf_st_eq_char model, fc.char_eq_p model hB2, hp3]
  have hinf : Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t)
      ⊓ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) = ⊥ := by
    rw [eq_bot_iff]
    intro x hx
    have hmem : x ∈ fc.nonsplitTorus ⊓ fc.toHypothesis.W :=
      ⟨fc.zpowers_le_nonsplitTorus hx.1, hx.2.1⟩
    rwa [fc.nonsplitTorus_inf_W_eq_bot model ind hB2] at hmem
  rw [card_sup_eq_mul_of_commute
      (fun _ (ha : _ ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)) _
        (hb : _ ∈ fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) =>
        fc.commute_of_mem_nonsplitTorus_of_mem_W (fc.zpowers_le_nonsplitTorus ha) hb.1)
      hinf,
    Nat.card_zpowers, hstord, hSig3]

include model in
/-- `|Z₁ΣP| = 27`. -/
theorem card_zpowers_sup_sigma_sup_P
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    Nat.card ↥((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P) = 27 := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  obtain ⟨-, hp3, -, -, -, -⟩ := fc.step_twelve model ind hB2
  rw [card_sup_eq_mul_of_commute
      (fun _ ha _ hb => (Subgroup.mem_centralizer_iff.mp
        (sup_le (fc.zpowers_st_le_centralizer_P model ind hB2) inf_le_right ha) _ hb).symm)
      (fc.zpowers_sup_sigma_inf_P_eq_bot model ind hB2),
    fc.card_zpowers_sup_sigma model ind hB2, fc.card_P, hp3]

/-! ## `Z₁` is the unique strongly real line of `Z₁ΣP` -/

include model in
/-- **`Z₁` is the only subgroup of order `3` in `Z₁PΣ` consisting of strongly real
elements** ((16), p. 114).

If `X ≠ Z₁` is such a subgroup, some `g ∈ R₁` fails to centralize `X` (else
`X ≤ Z(R₁) = Z₁`), and then for every `w ∈ X^#` the commutator `d = w⁻¹·w^g` lies in
`Z₁` — by `⁅Z₁ΣP, R₁⁆ ≤ Z₁` — and is nontrivial, hence generates `Z₁`.  So
`w^{g^m} = w·d^m` runs over the whole coset `wZ₁`, and every element of `Z₁X` outside
`Z₁` is `R₁`-conjugate to an element of `X^#`, hence strongly real.  But `Z₁X` and `ΣP`
are subgroups of order `9` of the elementary abelian group `Z₁ΣP` of order `27`, so
they meet nontrivially — and no nonidentity element of `ΣP` is strongly real. -/
theorem eq_zpowers_of_card_three_of_forall_isStronglyReal
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) {X : Subgroup G}
    (hXle : X ≤ (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
    (hXcard : Nat.card ↥X = 3)
    (hXsr : ∀ x ∈ X, x ≠ 1 → IsStronglyReal x) :
    X = Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  obtain ⟨-, hp3, hF9, -, -, -⟩ := fc.step_twelve model ind hB2
  have hm : Nat.card F = fc.p ^ 2 := by rw [hF9, hp3]; norm_num
  have hstord : orderOf (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) = 3 := by
    rw [fc.orderOf_st_eq_char model, fc.char_eq_p model hB2, hp3]
  have hZ₁card : Nat.card ↥(Subgroup.zpowers
      (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t)) = 3 := by
    rw [Nat.card_zpowers, hstord]
  -- `Z₁ΣP ≤ RΣ ≤ R₁`
  have hZ₁R : Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) ≤ fc.invImageF model :=
    (fc.zpowers_distinguishedInvolution_mul_t_le_sInvertedT model ind hB2 hm).trans
      (fc.sInvertedT_spec model ind hB2 hm).1
  have hZSP_RS : ((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
      ≤ fc.invImageF model
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) :=
    sup_le (sup_le (hZ₁R.trans le_sup_left) le_sup_right)
      ((fc.P_le_invImageF model).trans le_sup_left)
  have hZSP_R₁ : ((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P)
      ≤ fc.sylowThreeNormalizerRSigma model :=
    hZSP_RS.trans (fc.sup_le_sylowThreeNormalizerRSigma model ind hB2)
  by_contra hne
  -- a nonidentity element of `X`
  obtain ⟨w₀, hw₀X, hw₀1⟩ : ∃ w ∈ X, w ≠ 1 := by
    by_contra hcon
    push Not at hcon
    have : X = ⊥ := by
      rw [eq_bot_iff]
      intro x hx
      rw [Subgroup.mem_bot]
      exact hcon x hx
    rw [this, Subgroup.card_bot] at hXcard
    omega
  -- every nonidentity element of `X` generates `X`
  have hgenX : ∀ w ∈ X, w ≠ 1 → Subgroup.zpowers w = X := by
    intro w hw hw1
    refine Subgroup.eq_of_le_of_card_ge (Subgroup.zpowers_le.mpr hw) ?_
    have h := Subgroup.orderOf_dvd_natCard _ hw
    rw [hXcard] at h
    rcases (Nat.dvd_prime (by norm_num)).mp h with h1 | h3
    · exact absurd (orderOf_eq_one_iff.mp h1) hw1
    · rw [hXcard, Nat.card_zpowers, h3]
  -- some `g ∈ R₁` moves `w₀`
  obtain ⟨g, hgR₁, hgw⟩ : ∃ g ∈ fc.sylowThreeNormalizerRSigma model,
      g * w₀ * g⁻¹ ≠ w₀ := by
    by_contra hcon
    push Not at hcon
    refine hne ?_
    have hw₀Z : w₀ ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) := by
      rw [← fc.inf_centralizer_sylowThree_eq_zpowers model ind hB2]
      refine ⟨hZSP_R₁ (hXle hw₀X), Subgroup.mem_centralizer_iff.mpr fun y hy => ?_⟩
      have h := hcon y hy
      calc y * w₀ = (y * w₀ * y⁻¹) * y := by group
        _ = w₀ * y := by rw [h]
    refine Subgroup.eq_of_le_of_card_ge ?_ (by rw [hXcard, hZ₁card])
    rw [← hgenX w₀ hw₀X hw₀1]
    exact Subgroup.zpowers_le.mpr hw₀Z
  -- for every `w ∈ X^#` the commutator with `g` generates `Z₁`
  have hkey : ∀ w ∈ X, w ≠ 1 → ∃ d : G, Subgroup.zpowers d
      = Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) ∧ g * w * g⁻¹ = w * d := by
    intro w hwX hw1
    refine ⟨w⁻¹ * (g * w * g⁻¹), ?_, by group⟩
    have hdZ : w⁻¹ * (g * w * g⁻¹)
        ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t) := by
      have hmem : ⁅w⁻¹, g⁆ ∈ ⁅((Subgroup.zpowers
            (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t)
          ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P),
          fc.sylowThreeNormalizerRSigma model⁆ :=
        Subgroup.commutator_mem_commutator
          (Subgroup.inv_mem _ (hXle hwX)) hgR₁
      have := fc.commutator_zpowers_sup_sigma_sup_P_sylowThree_le model ind hB2 hmem
      rwa [show ⁅w⁻¹, g⁆ = w⁻¹ * (g * w * g⁻¹) by rw [commutatorElement_def]; group]
        at this
    have hd1 : w⁻¹ * (g * w * g⁻¹) ≠ 1 := by
      intro hd
      refine hgw ?_
      have hfix : g * w * g⁻¹ = w := by
        have h2 : w * (w⁻¹ * (g * w * g⁻¹)) = w * 1 := by rw [hd]
        simpa using h2
      have hw₀mem : w₀ ∈ Subgroup.zpowers w := by
        rw [hgenX w hwX hw1]; exact hw₀X
      obtain ⟨k, rfl⟩ := hw₀mem
      calc g * w ^ k * g⁻¹ = (g * w * g⁻¹) ^ k := by rw [conj_zpow]
        _ = w ^ k := by rw [hfix]
    refine Subgroup.eq_of_le_of_card_ge (Subgroup.zpowers_le.mpr hdZ) ?_
    rw [hZ₁card, Nat.card_zpowers]
    have h := Subgroup.orderOf_dvd_natCard _ hdZ
    rw [hZ₁card] at h
    rcases (Nat.dvd_prime (by norm_num)).mp h with h1 | h3
    · exact absurd (orderOf_eq_one_iff.mp h1) hd1
    · omega
  -- `Z₁` is central in `R₁`
  have hZ₁cen : ∀ d ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t), ∀ y ∈ fc.sylowThreeNormalizerRSigma model,
      d * y = y * d := by
    intro d hd y hy
    have hmem : d ∈ fc.sylowThreeNormalizerRSigma model
        ⊓ Subgroup.centralizer ((fc.sylowThreeNormalizerRSigma model : Subgroup G)
          : Set G) := by
      rw [fc.inf_centralizer_sylowThree_eq_zpowers model ind hB2]
      exact hd
    exact (Subgroup.mem_centralizer_iff.mp hmem.2 y hy).symm
  -- `Z₁X` and `ΣP` meet nontrivially inside `Z₁ΣP`
  have hZXcard : Nat.card ↥(Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) ⊔ X) = 9 := by
    have hinf : Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) ⊓ X = ⊥ := by
      rw [eq_bot_iff]
      intro x hx
      rw [Subgroup.mem_bot]
      by_contra hx1
      refine hne ?_
      have h1 : Subgroup.zpowers x = X := hgenX x hx.2 hx1
      have hxord : orderOf x = 3 := by
        have h := Subgroup.orderOf_dvd_natCard _ hx.1
        rw [hZ₁card] at h
        rcases (Nat.dvd_prime (by norm_num)).mp h with ha | hb
        · exact absurd (orderOf_eq_one_iff.mp ha) hx1
        · exact hb
      have h2 : Subgroup.zpowers x = Subgroup.zpowers
          (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t) :=
        Subgroup.eq_of_le_of_card_ge (Subgroup.zpowers_le.mpr hx.1)
          (by rw [hZ₁card, Nat.card_zpowers, hxord])
      rw [← h1, h2]
    rw [card_sup_eq_mul_of_commute
        (fun a ha b hb => fc.mul_comm_of_mem_zpowers_sup_sigma_sup_P model ind hB2
          (Subgroup.mem_sup_left (Subgroup.mem_sup_left ha)) (hXle hb))
        hinf, hZ₁card, hXcard]
  have hSPcard : Nat.card ↥((fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))
      ⊔ fc.P) = 9 := by
    obtain ⟨hpSig, -, -, -, -, -⟩ := fc.step_twelve model ind hB2
    obtain ⟨-, -, -, hSig3, -⟩ :=
      fc.card_field_eq_nine_of_p_dvd_card_centralizer_W ind model hB2 hpSig
    have hinf : (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) ⊓ fc.P
        = ⊥ := by
      rw [eq_bot_iff]
      intro x hx
      have hmem : x ∈ (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
          ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊓ fc.P :=
        ⟨Subgroup.mem_sup_right hx.1, hx.2⟩
      rwa [fc.zpowers_sup_sigma_inf_P_eq_bot model ind hB2] at hmem
    rw [card_sup_eq_mul_of_commute
        (fun a (ha : a ∈ fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))
          b (hb : b ∈ fc.P) =>
          (Subgroup.mem_centralizer_iff.mp ha.2 b hb).symm) hinf,
      hSig3, fc.card_P, hp3]
  obtain ⟨y, hyZX, hySP, hy1⟩ : ∃ y : G, y ∈ Subgroup.zpowers
      (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t) ⊔ X
      ∧ y ∈ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) ⊔ fc.P
      ∧ y ≠ 1 := by
    by_contra hcon
    push Not at hcon
    have hbot : (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) ⊔ X)
        ⊓ ((fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) ⊔ fc.P) = ⊥ := by
      rw [eq_bot_iff]
      intro x hx
      rw [Subgroup.mem_bot]
      exact hcon x hx.1 hx.2
    have hleZSP : (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t) ⊔ X)
        ⊔ ((fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) ⊔ fc.P)
        ≤ (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
            * fc.toHypothesis.t)
          ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P :=
      sup_le (sup_le (le_sup_left.trans le_sup_left) hXle)
        (sup_le (le_sup_right.trans le_sup_left) le_sup_right)
    have hcard81 : Nat.card ↥((Subgroup.zpowers
        (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t) ⊔ X)
        ⊔ ((fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) ⊔ fc.P)) = 81 := by
      rw [card_sup_eq_mul_of_commute
          (fun a ha b hb => fc.mul_comm_of_mem_zpowers_sup_sigma_sup_P model ind hB2
            (hleZSP (Subgroup.mem_sup_left ha)) (hleZSP (Subgroup.mem_sup_right hb)))
          hbot, hZXcard, hSPcard]
    have hdvd := Subgroup.card_dvd_of_le hleZSP
    rw [hcard81, fc.card_zpowers_sup_sigma_sup_P model ind hB2] at hdvd
    exact absurd (Nat.le_of_dvd (by norm_num) hdvd) (by norm_num)
  -- decompose `y = z·w` with `z ∈ Z₁`, `w ∈ X`
  have hcoe := coe_sup_eq_mul_of_commute
    (fun _ (ha : _ ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)) _ (hb : _ ∈ X) =>
      fc.mul_comm_of_mem_zpowers_sup_sigma_sup_P model ind hB2
        (Subgroup.mem_sup_left (Subgroup.mem_sup_left ha)) (hXle hb))
  have hy' : y ∈ ((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) : Subgroup G) : Set G) * (X : Set G) := by
    rw [← hcoe]; exact hyZX
  obtain ⟨z, hz, w, hw, hzw0⟩ := hy'
  have hzw : z * w = y := hzw0
  -- `y` is strongly real, contradicting `not_isStronglyReal_of_mem_P_sup_sigma`
  refine fc.not_isStronglyReal_of_mem_P_sup_sigma model ind hB2 hySP hy1 ?_
  rcases eq_or_ne w 1 with rfl | hw1
  · -- `y ∈ Z₁^#`, so `Z₁ = ⟨y⟩ ≤ ΣP` and `st` itself lies in `ΣP`
    exfalso
    have hyZ : y ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) := by rw [← hzw, mul_one]; exact hz
    have hyord : orderOf y = 3 := by
      have h := Subgroup.orderOf_dvd_natCard _ hyZ
      rw [hZ₁card] at h
      rcases (Nat.dvd_prime (by norm_num)).mp h with ha | hb
      · exact absurd (orderOf_eq_one_iff.mp ha) hy1
      · exact hb
    have hgen : Subgroup.zpowers y = Subgroup.zpowers
        (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t) :=
      Subgroup.eq_of_le_of_card_ge (Subgroup.zpowers_le.mpr hyZ)
        (by rw [hZ₁card, Nat.card_zpowers, hyord])
    have hstSP : fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t
        ∈ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) ⊔ fc.P := by
      have : Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t) ≤ (fc.toHypothesis.W
            ⊓ Subgroup.centralizer (fc.P : Set G)) ⊔ fc.P := by
        rw [← hgen]
        exact Subgroup.zpowers_le.mpr hySP
      exact this (Subgroup.mem_zpowers _)
    have hst1 : fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t ≠ 1 := by
      intro h
      rw [h, orderOf_one] at hstord
      omega
    exact fc.not_isStronglyReal_of_mem_P_sup_sigma model ind hB2 hstSP hst1
      fc.toHypothesis.isStronglyReal_distinguishedInvolution_mul_t
  · -- `y` is `R₁`-conjugate to `w ∈ X^#`
    obtain ⟨d, hdgen, hdconj⟩ := hkey w hw hw1
    have hzd : z ∈ Subgroup.zpowers d := by rw [hdgen]; exact hz
    obtain ⟨mnat, hmnat0⟩ := (mem_powers_iff_mem_zpowers).mpr hzd
    have hmnat : d ^ mnat = z := hmnat0
    have hdg : Commute d g := by
      refine hZ₁cen d ?_ g hgR₁
      rw [← hdgen]
      exact Subgroup.mem_zpowers _
    have hyconj : y = g ^ mnat * w * (g ^ mnat)⁻¹ := by
      rw [conj_pow_eq_mul_pow hdg hdconj mnat, hmnat, ← hzw]
      exact fc.mul_comm_of_mem_zpowers_sup_sigma_sup_P model ind hB2
        (Subgroup.mem_sup_left (Subgroup.mem_sup_left hz)) (hXle hw)
    rw [hyconj]
    exact isStronglyReal_conj (hXsr w hw hw1) _

end FirstCaseHypothesis

end OddOrder.Peterfalvi.Appendices.Suzuki
