/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Peterfalvi.Appendices.Suzuki.FirstCase.StepFifteen

/-!
# Peterfalvi Part II, Ch. II, step (15): the subgroup `LV`

T. Peterfalvi, *Character Theory for the Odd Order Theorem* (LMS LNS 272,
2000), Part II, Ch. II, (15), pp. 113-114.

The first half of (15) — `L` is cyclic of order `9`, inverted by `s`, normalized by
`V`, centralized by `W` but not by `P`, and contained in `R₁` — is in
`StepFifteen.lean`.  This file treats the group `LV` it generates:

> … It is also the case that `|R₂ : LV| = 3`, `Z(LV) = Z₁Σ` and `Ω₁(LV) = Z₁ΣP`.

`V = WP` normalizes `L` and meets it trivially, so `|LV| = |L|·|V| = 27·|W|`, while
`|R₂| = 3⁴·|W|` by (10.2); this gives the index.  The abelian subgroup `LW` has index
`3` in `LV`, which pins down the centre, and the `3`-torsion computation for `LV`
gives `Ω₁(LV)`.
-/

set_option autoImplicit false

open scoped Pointwise

namespace OddOrder.Peterfalvi.Appendices.Suzuki

section GenericAbelian

variable {G' : Type*} [Group G']

/-- The join of two elementwise commuting abelian subgroups is abelian. -/
theorem mul_comm_of_mem_sup_of_commute {A B : Subgroup G'}
    (hA : ∀ a₁ ∈ A, ∀ a₂ ∈ A, a₁ * a₂ = a₂ * a₁)
    (hB : ∀ b₁ ∈ B, ∀ b₂ ∈ B, b₁ * b₂ = b₂ * b₁)
    (hAB : ∀ a ∈ A, ∀ b ∈ B, a * b = b * a)
    {x y : G'} (hx : x ∈ A ⊔ B) (hy : y ∈ A ⊔ B) : x * y = y * x := by
  have hcoe := coe_sup_eq_mul_of_commute hAB
  have hx' : x ∈ (A : Set G') * (B : Set G') := by rw [← hcoe]; exact hx
  have hy' : y ∈ (A : Set G') * (B : Set G') := by rw [← hcoe]; exact hy
  obtain ⟨a₁, ha₁, b₁, hb₁, rfl⟩ := hx'
  obtain ⟨a₂, ha₂, b₂, hb₂, rfl⟩ := hy'
  calc a₁ * b₁ * (a₂ * b₂) = a₁ * (b₁ * a₂) * b₂ := by group
    _ = a₁ * (a₂ * b₁) * b₂ := by rw [← hAB a₂ ha₂ b₁ hb₁]
    _ = (a₁ * a₂) * (b₁ * b₂) := by group
    _ = (a₂ * a₁) * (b₂ * b₁) := by rw [hA a₁ ha₁ a₂ ha₂, hB b₁ hb₁ b₂ hb₂]
    _ = a₂ * (a₁ * b₂) * b₁ := by group
    _ = a₂ * (b₂ * a₁) * b₁ := by rw [hAB a₁ ha₁ b₂ hb₂]
    _ = a₂ * b₂ * (a₁ * b₁) := by group

/-- The centralizer of a join is the intersection of the centralizers. -/
theorem centralizer_sup (A B : Subgroup G') :
    Subgroup.centralizer ((A ⊔ B : Subgroup G') : Set G')
      = Subgroup.centralizer (A : Set G') ⊓ Subgroup.centralizer (B : Set G') := by
  rw [show (A ⊔ B : Subgroup G') = Subgroup.closure ((A : Set G') ∪ (B : Set G')) by
      rw [Subgroup.closure_union, Subgroup.closure_eq, Subgroup.closure_eq],
    Subgroup.centralizer_closure, centralizer_union]

/-- Elements of a cyclic subgroup commute. -/
theorem mul_comm_of_mem_of_isCyclic {A : Subgroup G'} (hA : IsCyclic ↥A)
    {a₁ a₂ : G'} (h₁ : a₁ ∈ A) (h₂ : a₂ ∈ A) : a₁ * a₂ = a₂ * a₁ := by
  have : IsMulCommutative ↥A := IsCyclic.isMulCommutative
  exact congrArg Subtype.val
    (‹IsMulCommutative ↥A›.is_comm.comm (⟨a₁, h₁⟩ : ↥A) (⟨a₂, h₂⟩ : ↥A))

end GenericAbelian

namespace FirstCaseHypothesis

universe uG uΩ

variable {G : Type uG} {Ω : Type uΩ} [Group G] [MulAction G Ω] [Finite G]
  (fc : FirstCaseHypothesis G Ω)
  {F : Type uG} [NearFields.NearField F]
  (model : letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
    NearFields.AffineNearFieldModel fc.rankOneQuotient F)

include fc in
/-- `C_G(Z₁) = C_G(st)`: the centralizer of a subgroup generated by one element. -/
theorem centralizer_zpowers_st_eq :
    Subgroup.centralizer ((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) : Subgroup G) : Set G)
      = Subgroup.centralizer ({fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t} : Set G) := by
  rw [Subgroup.zpowers_eq_closure, Subgroup.centralizer_closure]

include model in
/-- **`|LV| = 27·|W|`** ((15), p. 114): `V` normalizes `L`, `L ⊓ V = 1`, `|L| = 9` and
`|V| = |P|·|W| = 3·|W|`. -/
theorem card_sup_nonsplitTorus_V
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    Nat.card ↥(fc.nonsplitTorus ⊔ fc.toHypothesis.V)
      = 27 * Nat.card ↥fc.toHypothesis.W := by
  let := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  obtain ⟨-, hp3, -, -, -, -⟩ := fc.step_twelve model ind hB2
  obtain ⟨-, hLcard⟩ := fc.isCyclic_and_card_nonsplitTorus model ind hB2
  rw [card_sup_eq_mul_of_le_normalizer
      (fun b hb => fc.V_le_normalizer_nonsplitTorus model ind hB2 hb)
      (fc.nonsplitTorus_inf_V_eq_bot model ind hB2),
    hLcard, fc.card_V_eq_card_P_mul_card_W, fc.card_P, hp3]
  ring

include model in
/-- **`LV ≤ R₂`** ((15), p. 114): both `L` and `V` centralize `st`, and
`R₂ = C_G(Z₁)` by (14). -/
theorem sup_nonsplitTorus_V_le_sylow
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) (S : Sylow 3 G)
    (hR₁S : fc.sylowThreeNormalizerRSigma model ≤ (S : Subgroup G)) :
    fc.nonsplitTorus ⊔ fc.toHypothesis.V ≤ (S : Subgroup G) := by
  rw [← fc.sylow_eq_centralizer_zpowers model ind hB2 S hR₁S,
    fc.centralizer_zpowers_st_eq]
  refine sup_le ?_ ?_
  · rw [fc.nonsplitTorus_def]; exact inf_le_left
  · rw [← fc.toHypothesis.centralizer_mul_t_inf_centralizer_eq_V]; exact inf_le_left

include model in
/-- **`|R₂ : LV| = 3`** ((15), p. 114): `|R₂| = 3⁴·|W|` by (10.2) and
`|LV| = 27·|W|`. -/
theorem index_subgroupOf_sup_nonsplitTorus_V_eq_three
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) (S : Sylow 3 G)
    (hR₁S : fc.sylowThreeNormalizerRSigma model ≤ (S : Subgroup G)) :
    ((fc.nonsplitTorus ⊔ fc.toHypothesis.V).subgroupOf (S : Subgroup G)).index = 3 := by
  let := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  have : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  obtain ⟨-, -, -, -, -, hGp⟩ := fc.step_twelve model ind hB2
  have hScard : Nat.card ↥(S : Subgroup G) = 3 ^ 4 * Nat.card ↥fc.toHypothesis.W := by
    rw [Sylow.card_eq_multiplicity]
    exact hGp
  have hle := fc.sup_nonsplitTorus_V_le_sylow model ind hB2 S hR₁S
  have hsub : Nat.card ↥((fc.nonsplitTorus ⊔ fc.toHypothesis.V).subgroupOf
      (S : Subgroup G)) = 27 * Nat.card ↥fc.toHypothesis.W := by
    rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe hle).toEquiv]
    exact fc.card_sup_nonsplitTorus_V model ind hB2
  have hmul := ((fc.nonsplitTorus ⊔ fc.toHypothesis.V).subgroupOf
    (S : Subgroup G)).card_mul_index
  rw [hsub, hScard] at hmul
  have hWpos : 0 < Nat.card ↥fc.toHypothesis.W := Nat.card_pos
  nlinarith [hmul, hWpos]

/-! ## The abelian subgroup `LW` of index `3` -/

include model in
/-- `L ⊓ W = 1` (from `L ⊓ V = 1` and `W ≤ V`). -/
theorem nonsplitTorus_inf_W_eq_bot
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    fc.nonsplitTorus ⊓ fc.toHypothesis.W = ⊥ := by
  rw [eq_bot_iff]
  intro x hx
  have : x ∈ fc.nonsplitTorus ⊓ fc.toHypothesis.V :=
    ⟨hx.1, fc.toHypothesis.W_le_V hx.2⟩
  rwa [fc.nonsplitTorus_inf_V_eq_bot model ind hB2] at this

include fc in
/-- `L` and `W` commute elementwise. -/
theorem commute_of_mem_nonsplitTorus_of_mem_W {a b : G} (ha : a ∈ fc.nonsplitTorus)
    (hb : b ∈ fc.toHypothesis.W) : a * b = b * a :=
  (Subgroup.mem_centralizer_iff.mp (fc.nonsplitTorus_le_centralizer_W ha) b hb).symm

include model in
/-- **`LW` is abelian** ((15), p. 114: "`Z(LV) ⊂ LW` since `LV` is non-abelian"):
`L` is cyclic, `W` is cyclic by (10.2), and they centralize each other. -/
theorem mul_comm_of_mem_sup_nonsplitTorus_W
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G))
    {x y : G} (hx : x ∈ fc.nonsplitTorus ⊔ fc.toHypothesis.W)
    (hy : y ∈ fc.nonsplitTorus ⊔ fc.toHypothesis.W) : x * y = y * x := by
  let := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  obtain ⟨-, -, -, hWcyc, -, -⟩ := fc.step_twelve model ind hB2
  obtain ⟨hLcyc, -⟩ := fc.isCyclic_and_card_nonsplitTorus model ind hB2
  exact mul_comm_of_mem_sup_of_commute
    (fun _ h₁ _ h₂ => mul_comm_of_mem_of_isCyclic hLcyc h₁ h₂)
    (fun _ h₁ _ h₂ => mul_comm_of_mem_of_isCyclic hWcyc h₁ h₂)
    (fun _ ha _ hb => fc.commute_of_mem_nonsplitTorus_of_mem_W ha hb) hx hy

include model in
/-- `|LW| = 9·|W|`. -/
theorem card_sup_nonsplitTorus_W
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    Nat.card ↥(fc.nonsplitTorus ⊔ fc.toHypothesis.W)
      = 9 * Nat.card ↥fc.toHypothesis.W := by
  obtain ⟨-, hLcard⟩ := fc.isCyclic_and_card_nonsplitTorus model ind hB2
  rw [card_sup_eq_mul_of_commute
      (fun _ ha _ hb => fc.commute_of_mem_nonsplitTorus_of_mem_W ha hb)
      (fc.nonsplitTorus_inf_W_eq_bot model ind hB2), hLcard]

include fc in
/-- `LV = (LW)P`. -/
theorem sup_nonsplitTorus_V_eq :
    fc.nonsplitTorus ⊔ fc.toHypothesis.V
      = (fc.nonsplitTorus ⊔ fc.toHypothesis.W) ⊔ fc.P := by
  rw [← fc.W_join_P_eq_V, sup_assoc]

/-! ## The centre of `LV` -/

include model in
/-- **`C_L(P) = Z₁`** ((15), p. 114): `Z₁ ≤ C_L(P)` because `P` centralizes `st`, and
`C_L(P) ≠ L` because `P` does not centralize `L`; the subgroups of the cyclic group `L`
of order `9` leave no other possibility. -/
theorem nonsplitTorus_inf_centralizer_P_eq_zpowers
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    fc.nonsplitTorus ⊓ Subgroup.centralizer (fc.P : Set G)
      = Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) := by
  let := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  obtain ⟨-, hp3, hF9, -, -, -⟩ := fc.step_twelve model ind hB2
  obtain ⟨-, hLcard⟩ := fc.isCyclic_and_card_nonsplitTorus model ind hB2
  have hm : Nat.card F = fc.p ^ 2 := by rw [hF9, hp3]; norm_num
  have hstord : orderOf (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) = 3 := by
    rw [fc.orderOf_st_eq_char model, fc.char_eq_p model hB2, hp3]
  have habR := fc.invImageF_mul_comm model ind hB2 hm
  have hstR : fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t
      ∈ fc.invImageF model :=
    (fc.sInvertedT_spec model ind hB2 hm).1
      (fc.zpowers_distinguishedInvolution_mul_t_le_sInvertedT model ind hB2 hm
        (Subgroup.mem_zpowers _))
  -- `Z₁ ≤ C_L(P)`
  have hZle : Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) ≤ fc.nonsplitTorus ⊓ Subgroup.centralizer (fc.P : Set G) := by
    refine le_inf fc.zpowers_le_nonsplitTorus ?_
    rw [Subgroup.zpowers_le]
    exact Subgroup.mem_centralizer_iff.mpr fun y hy =>
      habR y (fc.P_le_invImageF model hy) _ hstR
  -- the intersection is not all of `L`
  refine (Subgroup.eq_of_le_of_card_ge hZle ?_).symm
  rw [Nat.card_zpowers, hstord]
  have hdvd : Nat.card ↥(fc.nonsplitTorus ⊓ Subgroup.centralizer (fc.P : Set G)) ∣ 9 := by
    rw [← hLcard]
    exact Subgroup.card_dvd_of_le inf_le_left
  have hne : Nat.card ↥(fc.nonsplitTorus ⊓ Subgroup.centralizer (fc.P : Set G)) ≠ 9 := by
    intro h
    refine fc.not_nonsplitTorus_le_centralizer_P model ind hB2 ?_
    have := Subgroup.eq_of_le_of_card_ge (inf_le_left :
      fc.nonsplitTorus ⊓ Subgroup.centralizer (fc.P : Set G) ≤ fc.nonsplitTorus)
      (by rw [h, hLcard])
    rw [← this]
    exact inf_le_right
  obtain ⟨k, hk2, hkeq⟩ := (Nat.dvd_prime_pow (p := 3) (by norm_num)).mp
    (show Nat.card ↥(fc.nonsplitTorus ⊓ Subgroup.centralizer (fc.P : Set G)) ∣ 3 ^ 2 by
      rw [show (3 : ℕ) ^ 2 = 9 by norm_num]; exact hdvd)
  have hk1 : k ≤ 1 := by
    by_contra hcon
    exact hne (by rw [hkeq, show k = 2 by omega]; norm_num)
  rw [hkeq]
  calc (3 : ℕ) ^ k ≤ 3 ^ 1 := Nat.pow_le_pow_right (by norm_num) hk1
    _ = 3 := by norm_num

include model in
/-- **`C_{LW}(P) = Z₁Σ`** ((15), p. 114): `P` normalizes both `L` and `W`, which meet
trivially, so a fixed point of `P` in `LW = L × W` has both components fixed. -/
theorem sup_nonsplitTorus_W_inf_centralizer_P_eq
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    (fc.nonsplitTorus ⊔ fc.toHypothesis.W) ⊓ Subgroup.centralizer (fc.P : Set G)
      = Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) := by
  let := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  have hcoe := coe_sup_eq_mul_of_commute
    (fun _ (ha : _ ∈ fc.nonsplitTorus) _ (hb : _ ∈ fc.toHypothesis.W) =>
      fc.commute_of_mem_nonsplitTorus_of_mem_W ha hb)
  have hLW := fc.nonsplitTorus_inf_W_eq_bot model ind hB2
  refine le_antisymm ?_ ?_
  · rintro x ⟨hxLW, hxP⟩
    have hx' : x ∈ (fc.nonsplitTorus : Set G) * (fc.toHypothesis.W : Set G) := by
      rw [← hcoe]; exact hxLW
    obtain ⟨l, hl, w, hw, rfl⟩ := hx'
    have hlL : l ∈ fc.nonsplitTorus := hl
    have hwW : w ∈ fc.toHypothesis.W := hw
    -- both components are fixed by `P`
    have hfix : ∀ y ∈ fc.P, y * l = l * y ∧ y * w = w * y := by
      intro y hy
      have hcy : y * (l * w) = (l * w) * y :=
        Subgroup.mem_centralizer_iff.mp hxP y hy
      have hyx : y * l * y⁻¹ * (y * w * y⁻¹) = l * w := by
        calc y * l * y⁻¹ * (y * w * y⁻¹) = y * (l * w) * y⁻¹ := by group
          _ = (l * w) * y * y⁻¹ := by rw [hcy]
          _ = l * w := by group
      have hyl : y * l * y⁻¹ ∈ fc.nonsplitTorus := by
        have hn := fc.P_le_normalizer_nonsplitTorus model ind hB2 hy
        rw [Subgroup.mem_set_normalizer_iff] at hn
        exact (hn l).mp hlL
      have hyw : y * w * y⁻¹ ∈ fc.toHypothesis.W := by
        have hn := fc.P_le_normalizer_W hy
        rw [Subgroup.mem_normalizer_iff] at hn
        exact (hn w).mp hwW
      have h2 : (l⁻¹ * (y * l * y⁻¹)) * (y * w * y⁻¹) = w := by
        refine mul_left_cancel (a := l) ?_
        calc l * ((l⁻¹ * (y * l * y⁻¹)) * (y * w * y⁻¹))
            = y * l * y⁻¹ * (y * w * y⁻¹) := by group
          _ = l * w := hyx
      have hkey : l⁻¹ * (y * l * y⁻¹) = w * (y * w * y⁻¹)⁻¹ := by
        calc l⁻¹ * (y * l * y⁻¹)
            = ((l⁻¹ * (y * l * y⁻¹)) * (y * w * y⁻¹)) * (y * w * y⁻¹)⁻¹ := by group
          _ = w * (y * w * y⁻¹)⁻¹ := by rw [h2]
      have hmemL : l⁻¹ * (y * l * y⁻¹) ∈ fc.nonsplitTorus :=
        Subgroup.mul_mem _ (Subgroup.inv_mem _ hlL) hyl
      have hmemW : l⁻¹ * (y * l * y⁻¹) ∈ fc.toHypothesis.W := by
        rw [hkey]
        exact Subgroup.mul_mem _ hwW (Subgroup.inv_mem _ hyw)
      have h1 : l⁻¹ * (y * l * y⁻¹) = 1 := by
        have hmem : l⁻¹ * (y * l * y⁻¹) ∈ fc.nonsplitTorus ⊓ fc.toHypothesis.W :=
          ⟨hmemL, hmemW⟩
        rwa [hLW, Subgroup.mem_bot] at hmem
      have hlfix : y * l * y⁻¹ = l := (inv_mul_eq_one.mp h1).symm
      have hwfix : y * w * y⁻¹ = w := by
        rw [hlfix, inv_mul_cancel, one_mul] at h2
        exact h2
      refine ⟨?_, ?_⟩
      · calc y * l = (y * l * y⁻¹) * y := by group
          _ = l * y := by rw [hlfix]
      · calc y * w = (y * w * y⁻¹) * y := by group
          _ = w * y := by rw [hwfix]
    have hlP : l ∈ Subgroup.centralizer (fc.P : Set G) :=
      Subgroup.mem_centralizer_iff.mpr fun y hy => (hfix y hy).1
    have hwP : w ∈ Subgroup.centralizer (fc.P : Set G) :=
      Subgroup.mem_centralizer_iff.mpr fun y hy => (hfix y hy).2
    have hlZ : l ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) := by
      rw [← fc.nonsplitTorus_inf_centralizer_P_eq_zpowers model ind hB2]
      exact ⟨hlL, hlP⟩
    exact Subgroup.mul_mem _ (Subgroup.mem_sup_left hlZ)
      (Subgroup.mem_sup_right ⟨hwW, hwP⟩)
  · refine sup_le ?_ ?_
    · intro x hx
      rw [← fc.nonsplitTorus_inf_centralizer_P_eq_zpowers model ind hB2] at hx
      exact ⟨Subgroup.mem_sup_left hx.1, hx.2⟩
    · intro x hx
      exact ⟨Subgroup.mem_sup_right hx.1, hx.2⟩

include model in
/-- `Z₁` centralizes `P` (both lie in the abelian group `R` of (11)). -/
theorem zpowers_st_le_centralizer_P
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t)
      ≤ Subgroup.centralizer (fc.P : Set G) := by
  let := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  obtain ⟨-, hp3, hF9, -, -, -⟩ := fc.step_twelve model ind hB2
  have hm : Nat.card F = fc.p ^ 2 := by rw [hF9, hp3]; norm_num
  have habR := fc.invImageF_mul_comm model ind hB2 hm
  have hstR : fc.toHypothesis.distinguishedInvolution * fc.toHypothesis.t
      ∈ fc.invImageF model :=
    (fc.sInvertedT_spec model ind hB2 hm).1
      (fc.zpowers_distinguishedInvolution_mul_t_le_sInvertedT model ind hB2 hm
        (Subgroup.mem_zpowers _))
  rw [Subgroup.zpowers_le]
  exact Subgroup.mem_centralizer_iff.mpr fun y hy =>
    habR y (fc.P_le_invImageF model hy) _ hstR

include model in
/-- **`C_{LV}(L) = LW`** ((15), p. 114, the step behind "`Z(LV) ⊂ LW` since `LV` is
non-abelian"): `LW` is abelian and has index `3` in `LV`, so the centralizer of `L` is
either `LW` or all of `LV`; the latter would make `P` centralize `L`. -/
theorem sup_nonsplitTorus_V_inf_centralizer_nonsplitTorus_eq
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    (fc.nonsplitTorus ⊔ fc.toHypothesis.V)
        ⊓ Subgroup.centralizer (fc.nonsplitTorus : Set G)
      = fc.nonsplitTorus ⊔ fc.toHypothesis.W := by
  let := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  have hcardLW := fc.card_sup_nonsplitTorus_W model ind hB2
  have hcardLV := fc.card_sup_nonsplitTorus_V model ind hB2
  have hWpos : 0 < Nat.card ↥fc.toHypothesis.W := Nat.card_pos
  have hLWle : (fc.nonsplitTorus ⊔ fc.toHypothesis.W)
      ≤ (fc.nonsplitTorus ⊔ fc.toHypothesis.V)
        ⊓ Subgroup.centralizer (fc.nonsplitTorus : Set G) := by
    refine le_inf (sup_le le_sup_left (le_trans fc.toHypothesis.W_le_V le_sup_right)) ?_
    intro x hx
    exact Subgroup.mem_centralizer_iff.mpr fun y hy =>
      fc.mul_comm_of_mem_sup_nonsplitTorus_W model ind hB2 (Subgroup.mem_sup_left hy) hx
  refine (Subgroup.eq_of_le_of_card_ge hLWle ?_).symm
  by_contra hlt
  push Not at hlt
  obtain ⟨m, hm⟩ := Subgroup.card_dvd_of_le hLWle
  have hdvd2 : Nat.card ↥((fc.nonsplitTorus ⊔ fc.toHypothesis.V)
      ⊓ Subgroup.centralizer (fc.nonsplitTorus : Set G))
      ∣ Nat.card ↥(fc.nonsplitTorus ⊔ fc.toHypothesis.V) :=
    Subgroup.card_dvd_of_le inf_le_left
  have hm3 : m ∣ 3 := by
    rw [hm, hcardLW, hcardLV] at hdvd2
    refine (Nat.mul_dvd_mul_iff_left (show 0 < 9 * Nat.card ↥fc.toHypothesis.W by
      omega)).mp ?_
    calc 9 * Nat.card ↥fc.toHypothesis.W * m
        ∣ 27 * Nat.card ↥fc.toHypothesis.W := hdvd2
      _ = 9 * Nat.card ↥fc.toHypothesis.W * 3 := by ring
  rcases (Nat.dvd_prime (by norm_num)).mp hm3 with h1 | h3
  · rw [h1, mul_one, hcardLW] at hm
    omega
  · -- the centralizer is everything, so `P` centralizes `L`
    have hCLV : (fc.nonsplitTorus ⊔ fc.toHypothesis.V)
        ⊓ Subgroup.centralizer (fc.nonsplitTorus : Set G)
        = fc.nonsplitTorus ⊔ fc.toHypothesis.V := by
      refine Subgroup.eq_of_le_of_card_ge inf_le_left ?_
      rw [hm, h3, hcardLW, hcardLV]
      omega
    refine fc.not_nonsplitTorus_le_centralizer_P model ind hB2 ?_
    intro x hx
    refine Subgroup.mem_centralizer_iff.mpr fun y hy => ?_
    have hyC : y ∈ (fc.nonsplitTorus ⊔ fc.toHypothesis.V)
        ⊓ Subgroup.centralizer (fc.nonsplitTorus : Set G) := by
      rw [hCLV]
      exact Subgroup.mem_sup_right (fc.P_le_V hy)
    exact (Subgroup.mem_centralizer_iff.mp hyC.2 x hx).symm

include model in
/-- **`Z(LV) = Z₁Σ`** ((15), p. 114), the centre taken inside `G` as `LV ⊓ C_G(LV)`.

`Z₁Σ` is central: `Z₁ ≤ L` is centralized by the abelian `L`, by `W` (which centralizes
`L`) and by `P` (both lie in the abelian `R`); `Σ ≤ W` centralizes `L`, the cyclic `W`
and `P` by its definition.  Conversely `Z(LV) ≤ C_{LV}(L) = LW` and `Z(LV) ≤ C_G(P)`,
and `C_{LW}(P) = Z₁Σ`. -/
theorem inf_centralizer_sup_nonsplitTorus_V_eq
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    (fc.nonsplitTorus ⊔ fc.toHypothesis.V)
        ⊓ Subgroup.centralizer (((fc.nonsplitTorus ⊔ fc.toHypothesis.V) : Subgroup G)
          : Set G)
      = Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) := by
  let := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  obtain ⟨-, -, -, hWcyc, -, -⟩ := fc.step_twelve model ind hB2
  obtain ⟨hLcyc, -⟩ := fc.isCyclic_and_card_nonsplitTorus model ind hB2
  have hcenLV : Subgroup.centralizer
      (((fc.nonsplitTorus ⊔ fc.toHypothesis.V) : Subgroup G) : Set G)
      = Subgroup.centralizer (fc.nonsplitTorus : Set G)
        ⊓ (Subgroup.centralizer (fc.toHypothesis.W : Set G)
          ⊓ Subgroup.centralizer (fc.P : Set G)) := by
    rw [centralizer_sup, ← fc.W_join_P_eq_V, centralizer_sup]
  refine le_antisymm ?_ ?_
  · rw [← fc.sup_nonsplitTorus_W_inf_centralizer_P_eq model ind hB2]
    intro x hx
    rw [hcenLV] at hx
    refine ⟨?_, hx.2.2.2⟩
    rw [← fc.sup_nonsplitTorus_V_inf_centralizer_nonsplitTorus_eq model ind hB2]
    exact ⟨hx.1, hx.2.1⟩
  · rw [hcenLV]
    refine sup_le ?_ ?_
    · refine le_inf (le_trans fc.zpowers_le_nonsplitTorus le_sup_left) (le_inf ?_ (le_inf ?_ ?_))
      · intro z hz
        exact Subgroup.mem_centralizer_iff.mpr fun y hy =>
          mul_comm_of_mem_of_isCyclic hLcyc hy (fc.zpowers_le_nonsplitTorus hz)
      · exact le_trans fc.zpowers_le_nonsplitTorus fc.nonsplitTorus_le_centralizer_W
      · exact fc.zpowers_st_le_centralizer_P model ind hB2
    · refine le_inf ?_ (le_inf ?_ (le_inf ?_ ?_))
      · exact le_trans (le_trans inf_le_left fc.toHypothesis.W_le_V) le_sup_right
      · intro σ hσ
        exact Subgroup.mem_centralizer_iff.mpr fun y hy =>
          fc.commute_of_mem_nonsplitTorus_of_mem_W hy hσ.1
      · intro σ hσ
        exact Subgroup.mem_centralizer_iff.mpr fun y hy =>
          mul_comm_of_mem_of_isCyclic hWcyc hy hσ.1
      · exact inf_le_right

/-! ## `Ω₁(LV) = Z₁ΣP` -/

include model in
/-- **The `3`-torsion of `W` is `Σ`**: `W` is cyclic of order `3` or `9` by (10.2), and
`|Σ| = 3`. -/
theorem mem_sigma_of_mem_W_of_pow_three
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) {w : G} (hw : w ∈ fc.toHypothesis.W)
    (hw3 : w ^ 3 = 1) :
    w ∈ fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G) := by
  let := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  obtain ⟨hpSig, -, -, hWcyc, hWcard, -⟩ := fc.step_twelve model ind hB2
  obtain ⟨-, -, -, hSig3, -⟩ :=
    fc.card_field_eq_nine_of_p_dvd_card_centralizer_W ind model hB2 hpSig
  rcases hWcard with h3 | h9
  · have heq : fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)
        = fc.toHypothesis.W :=
      Subgroup.eq_of_le_of_card_ge inf_le_left (by rw [h3, hSig3])
    rw [heq]
    exact hw
  · exact mem_of_pow_eq_one_of_isCyclic_card_sq (by norm_num) hWcyc
      (by rw [h9]) inf_le_left hSig3 hw hw3

include model in
/-- `Z₁Σ` has exponent `3`: `|Z₁| = |Σ| = 3` and the two centralize each other. -/
theorem pow_three_eq_one_of_mem_zpowers_sup_sigma
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) {x : G}
    (hx : x ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) :
    x ^ 3 = 1 := by
  let := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  obtain ⟨hpSig, hp3, -, -, -, -⟩ := fc.step_twelve model ind hB2
  obtain ⟨-, -, -, hSig3, -⟩ :=
    fc.card_field_eq_nine_of_p_dvd_card_centralizer_W ind model hB2 hpSig
  have hstord : orderOf (fc.toHypothesis.distinguishedInvolution
      * fc.toHypothesis.t) = 3 := by
    rw [fc.orderOf_st_eq_char model, fc.char_eq_p model hB2, hp3]
  refine pow_eq_one_of_mem_sup_of_commute ?_ ?_ ?_ hx
  · intro a ha b hb
    exact fc.commute_of_mem_nonsplitTorus_of_mem_W (fc.zpowers_le_nonsplitTorus ha) hb.1
  · intro a ha
    have h := Subgroup.orderOf_dvd_natCard _ ha
    rw [Nat.card_zpowers, hstord] at h
    exact orderOf_dvd_iff_pow_eq_one.mp h
  · intro b hb
    have h := Subgroup.orderOf_dvd_natCard _ hb
    rw [hSig3] at h
    exact orderOf_dvd_iff_pow_eq_one.mp h

include model in
/-- **`Ω₁(LW) = Z₁Σ`** ((15), p. 114): in the abelian group `LW = L × W`, an element
`lw` is killed by `3` exactly when both components are, i.e. when `l ∈ Z₁` and
`w ∈ Σ`. -/
theorem pow_three_eq_one_iff_mem_zpowers_sup_sigma
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) {x : G}
    (hx : x ∈ fc.nonsplitTorus ⊔ fc.toHypothesis.W) :
    x ^ 3 = 1 ↔ x ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) := by
  let := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  refine ⟨fun h3 => ?_, fun hmem =>
    fc.pow_three_eq_one_of_mem_zpowers_sup_sigma model ind hB2 hmem⟩
  have hcoe := coe_sup_eq_mul_of_commute
    (fun _ (ha : _ ∈ fc.nonsplitTorus) _ (hb : _ ∈ fc.toHypothesis.W) =>
      fc.commute_of_mem_nonsplitTorus_of_mem_W ha hb)
  have hx' : x ∈ (fc.nonsplitTorus : Set G) * (fc.toHypothesis.W : Set G) := by
    rw [← hcoe]; exact hx
  obtain ⟨l, hl, w, hw, rfl⟩ := hx'
  have hlL : l ∈ fc.nonsplitTorus := hl
  have hwW : w ∈ fc.toHypothesis.W := hw
  have hcomm : Commute l w := fc.commute_of_mem_nonsplitTorus_of_mem_W hlL hwW
  have hsplit : l ^ 3 * w ^ 3 = 1 := by
    rw [← hcomm.mul_pow]
    exact h3
  have hl3 : l ^ 3 = 1 := by
    have hmem : l ^ 3 ∈ fc.nonsplitTorus ⊓ fc.toHypothesis.W := by
      refine ⟨pow_mem hlL 3, ?_⟩
      have : l ^ 3 = (w ^ 3)⁻¹ := by
        rw [eq_inv_iff_mul_eq_one]; exact hsplit
      rw [this]
      exact Subgroup.inv_mem _ (pow_mem hwW 3)
    rwa [fc.nonsplitTorus_inf_W_eq_bot model ind hB2, Subgroup.mem_bot] at hmem
  have hw3 : w ^ 3 = 1 := by rw [hl3, one_mul] at hsplit; exact hsplit
  exact Subgroup.mul_mem _
    (Subgroup.mem_sup_left
      (fc.mem_zpowers_st_of_mem_nonsplitTorus_of_pow_three model ind hB2 hlL hl3))
    (Subgroup.mem_sup_right (fc.mem_sigma_of_mem_W_of_pow_three model ind hB2 hwW hw3))

include model in
/-- Cubes of `LW` lie in `Z₁Σ`: `LW` has exponent dividing `9`. -/
theorem pow_three_mem_zpowers_sup_sigma
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) {x : G}
    (hx : x ∈ fc.nonsplitTorus ⊔ fc.toHypothesis.W) :
    x ^ 3 ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) := by
  let := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  obtain ⟨-, -, -, -, hWcard, -⟩ := fc.step_twelve model ind hB2
  obtain ⟨-, hLcard⟩ := fc.isCyclic_and_card_nonsplitTorus model ind hB2
  refine (fc.pow_three_eq_one_iff_mem_zpowers_sup_sigma model ind hB2
    (pow_mem hx 3)).mp ?_
  -- `LW` has exponent dividing `9`
  have hcoe := coe_sup_eq_mul_of_commute
    (fun _ (ha : _ ∈ fc.nonsplitTorus) _ (hb : _ ∈ fc.toHypothesis.W) =>
      fc.commute_of_mem_nonsplitTorus_of_mem_W ha hb)
  have hx' : x ∈ (fc.nonsplitTorus : Set G) * (fc.toHypothesis.W : Set G) := by
    rw [← hcoe]; exact hx
  obtain ⟨l, hl, w, hw, rfl⟩ := hx'
  have hlL : l ∈ fc.nonsplitTorus := hl
  have hwW : w ∈ fc.toHypothesis.W := hw
  have hcomm : Commute l w := fc.commute_of_mem_nonsplitTorus_of_mem_W hlL hwW
  have hl9 : l ^ 9 = 1 := by
    have h := Subgroup.orderOf_dvd_natCard _ hlL
    rw [hLcard] at h
    exact orderOf_dvd_iff_pow_eq_one.mp h
  have hw9 : w ^ 9 = 1 := by
    have h := Subgroup.orderOf_dvd_natCard _ hwW
    have h9 : Nat.card ↥fc.toHypothesis.W ∣ 9 := by
      rcases hWcard with h | h
      · rw [h]; norm_num
      · rw [h]
    exact orderOf_dvd_iff_pow_eq_one.mp (h.trans h9)
  calc ((l * w) ^ 3) ^ 3 = (l * w) ^ 9 := by rw [← pow_mul]
    _ = l ^ 9 * w ^ 9 := hcomm.mul_pow 9
    _ = 1 := by rw [hl9, hw9, one_mul]

include model in
/-- `P` normalizes `LW`. -/
theorem P_le_normalizer_sup_nonsplitTorus_W
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    fc.P ≤ Subgroup.normalizer
      (((fc.nonsplitTorus ⊔ fc.toHypothesis.W) : Subgroup G) : Set G) := by
  intro y hy
  have hnL := fc.P_le_normalizer_nonsplitTorus model ind hB2 hy
  have hnW := fc.P_le_normalizer_W hy
  rw [Subgroup.mem_set_normalizer_iff] at hnL ⊢
  rw [Subgroup.mem_normalizer_iff] at hnW
  have hconj : ∀ g : G, ∀ z ∈ fc.nonsplitTorus ⊔ fc.toHypothesis.W,
      (∀ u : G, u ∈ fc.nonsplitTorus ↔ g * u * g⁻¹ ∈ fc.nonsplitTorus) →
      (∀ u : G, u ∈ fc.toHypothesis.W ↔ g * u * g⁻¹ ∈ fc.toHypothesis.W) →
      g * z * g⁻¹ ∈ fc.nonsplitTorus ⊔ fc.toHypothesis.W := by
    intro g z hz hL hW
    have hsub : fc.nonsplitTorus ⊔ fc.toHypothesis.W
        ≤ Subgroup.comap (MulAut.conj g).toMonoidHom
          (fc.nonsplitTorus ⊔ fc.toHypothesis.W) := by
      refine sup_le (fun u hu => ?_) (fun u hu => ?_)
      · exact Subgroup.mem_sup_left ((hL u).mp hu)
      · exact Subgroup.mem_sup_right ((hW u).mp hu)
    exact hsub hz
  intro z
  refine ⟨fun hz => hconj y z hz hnL hnW, fun hz => ?_⟩
  have hLinv : ∀ u : G, u ∈ fc.nonsplitTorus ↔ y⁻¹ * u * y⁻¹⁻¹ ∈ fc.nonsplitTorus := by
    intro u
    rw [inv_inv]
    have h1 : y * (y⁻¹ * u * y) * y⁻¹ = u := by group
    refine ⟨fun hu => (hnL (y⁻¹ * u * y)).mpr (by rw [h1]; exact hu), fun hu => ?_⟩
    have h2 := (hnL (y⁻¹ * u * y)).mp hu
    rwa [h1] at h2
  have hWinv : ∀ u : G, u ∈ fc.toHypothesis.W ↔ y⁻¹ * u * y⁻¹⁻¹ ∈ fc.toHypothesis.W := by
    intro u
    rw [inv_inv]
    have h1 : y * (y⁻¹ * u * y) * y⁻¹ = u := by group
    refine ⟨fun hu => (hnW (y⁻¹ * u * y)).mpr (by rw [h1]; exact hu), fun hu => ?_⟩
    have h2 := (hnW (y⁻¹ * u * y)).mp hu
    rwa [h1] at h2
  have h3 := hconj y⁻¹ _ hz hLinv hWinv
  have h4 : y⁻¹ * (y * z * y⁻¹) * y⁻¹⁻¹ = z := by group
  rwa [h4] at h3

include model in
/-- **`⁅LW, P⁆ ≤ Z₁Σ`** ((15), p. 114; also the engine of (16)): for `a ∈ LW` and
`q ∈ P` the element `a⁻¹·a^q` lies in `Z₁Σ = Ω₁(LW)`.

Its cube is `a⁻³·(a³)^q = 1`, because `a³ ∈ C_{LW}(P) = Z₁Σ` is centralized by `q`. -/
theorem inv_mul_conj_mem_zpowers_sup_sigma
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) {a q : G}
    (ha : a ∈ fc.nonsplitTorus ⊔ fc.toHypothesis.W) (hq : q ∈ fc.P) :
    a⁻¹ * (q * a * q⁻¹) ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) := by
  let := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  have hZScen : (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)))
      ≤ Subgroup.centralizer (fc.P : Set G) :=
    sup_le (fc.zpowers_st_le_centralizer_P model ind hB2) inf_le_right
  have hσa : q * a * q⁻¹ ∈ fc.nonsplitTorus ⊔ fc.toHypothesis.W := by
    have hn := fc.P_le_normalizer_sup_nonsplitTorus_W model ind hB2 hq
    rw [Subgroup.mem_set_normalizer_iff] at hn
    exact (hn a).mp ha
  have hdLW : a⁻¹ * (q * a * q⁻¹) ∈ fc.nonsplitTorus ⊔ fc.toHypothesis.W :=
    Subgroup.mul_mem _ (Subgroup.inv_mem _ ha) hσa
  have hcommd : Commute a⁻¹ (q * a * q⁻¹) :=
    fc.mul_comm_of_mem_sup_nonsplitTorus_W model ind hB2 (Subgroup.inv_mem _ ha) hσa
  have hfixa3 : q * a ^ 3 * q⁻¹ = a ^ 3 := by
    have hmem3 := fc.pow_three_mem_zpowers_sup_sigma model ind hB2 ha
    have hc := Subgroup.mem_centralizer_iff.mp (hZScen hmem3) q hq
    rw [hc]; group
  have hd3 : (a⁻¹ * (q * a * q⁻¹)) ^ 3 = 1 := by
    rw [hcommd.mul_pow, inv_pow, conj_pow, hfixa3, inv_mul_cancel]
  exact (fc.pow_three_eq_one_iff_mem_zpowers_sup_sigma model ind hB2 hdLW).mp hd3

include model in
/-- **`Ω₁(LV) = Z₁ΣP`** ((15), p. 114).

Write `x = aq` with `a ∈ LW` and `q ∈ P`.  The commutator `d = a⁻¹·a^q` lies in `LW`
and is killed by `3` (because `a³ ∈ C_{LW}(P) = Z₁Σ`), hence lies in `Z₁Σ ≤ C_G(P)`,
so conjugation by `q` sends `a` to `ad` and `ad` to `ad²`; therefore
`x³ = a³d³ = a³`.  Thus `x³ = 1` iff `a ∈ Ω₁(LW) = Z₁Σ`, i.e. iff `x ∈ Z₁ΣP`, and
conversely `Z₁ΣP` has exponent `3`. -/
theorem pow_three_eq_one_iff_mem_zpowers_sup_sigma_sup_P
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) {x : G}
    (hx : x ∈ fc.nonsplitTorus ⊔ fc.toHypothesis.V) :
    x ^ 3 = 1 ↔ x ∈ (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
          * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G))) ⊔ fc.P := by
  let := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  classical
  obtain ⟨-, hp3, -, -, -, -⟩ := fc.step_twelve model ind hB2
  have hPcard : Nat.card ↥fc.P = 3 := by rw [fc.card_P, hp3]
  -- `Z₁Σ` centralizes `P`
  have hZScen : (Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
      ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)))
      ≤ Subgroup.centralizer (fc.P : Set G) :=
    sup_le (fc.zpowers_st_le_centralizer_P model ind hB2) inf_le_right
  refine ⟨fun h3 => ?_, fun hmem => ?_⟩
  · -- decompose `x = a·q`
    rw [fc.sup_nonsplitTorus_V_eq] at hx
    have hcoe : (((fc.nonsplitTorus ⊔ fc.toHypothesis.W) ⊔ fc.P : Subgroup G) : Set G)
        = ((fc.nonsplitTorus ⊔ fc.toHypothesis.W : Subgroup G) : Set G)
          * (fc.P : Set G) :=
      Subgroup.coe_mul_of_right_le_normalizer_left _ _
        (fc.P_le_normalizer_sup_nonsplitTorus_W model ind hB2)
    have hx' : x ∈ ((fc.nonsplitTorus ⊔ fc.toHypothesis.W : Subgroup G) : Set G)
        * (fc.P : Set G) := by rw [← hcoe]; exact hx
    obtain ⟨a, ha, q, hq, rfl⟩ := hx'
    have haLW : a ∈ fc.nonsplitTorus ⊔ fc.toHypothesis.W := ha
    have hqP : q ∈ fc.P := hq
    have hq3 : q ^ 3 = 1 := by
      have h := Subgroup.orderOf_dvd_natCard _ hqP
      rw [hPcard] at h
      exact orderOf_dvd_iff_pow_eq_one.mp h
    -- the commutator `d`
    have hσa : q * a * q⁻¹ ∈ fc.nonsplitTorus ⊔ fc.toHypothesis.W := by
      have hn := fc.P_le_normalizer_sup_nonsplitTorus_W model ind hB2 hqP
      rw [Subgroup.mem_set_normalizer_iff] at hn
      exact (hn a).mp haLW
    set d : G := a⁻¹ * (q * a * q⁻¹) with hd_def
    have hdLW : d ∈ fc.nonsplitTorus ⊔ fc.toHypothesis.W :=
      Subgroup.mul_mem _ (Subgroup.inv_mem _ haLW) hσa
    have hdZS : d ∈ Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t)
        ⊔ (fc.toHypothesis.W ⊓ Subgroup.centralizer (fc.P : Set G)) :=
      fc.inv_mul_conj_mem_zpowers_sup_sigma model ind hB2 haLW hqP
    have hd3 : d ^ 3 = 1 :=
      fc.pow_three_eq_one_of_mem_zpowers_sup_sigma model ind hB2 hdZS
    have hdfix : q * d * q⁻¹ = d := by
      have hc := Subgroup.mem_centralizer_iff.mp (hZScen hdZS) q hqP
      rw [hc]; group
    -- `(aq)³ = a³d³ = a³`
    have hσa_eq : q * a * q⁻¹ = a * d := by rw [hd_def]; group
    have hσ2a : q * (a * d) * q⁻¹ = a * d * d := by
      calc q * (a * d) * q⁻¹ = (q * a * q⁻¹) * (q * d * q⁻¹) := by group
        _ = (a * d) * d := by rw [hσa_eq, hdfix]
    have hcommad : Commute a d :=
      fc.mul_comm_of_mem_sup_nonsplitTorus_W model ind hB2 haLW hdLW
    have hexpand : (a * q) ^ 3
        = a * (q * a * q⁻¹) * (q * (q * a * q⁻¹) * q⁻¹) * q ^ 3 := by
      rw [pow_three', pow_three']
      group
    have hcube : (a * q) ^ 3 = a ^ 3 := by
      rw [hexpand, hσa_eq, hσ2a, hq3, mul_one]
      calc a * (a * d) * (a * d * d) = (a * a * a) * (d * d * d) := by
            rw [show a * (a * d) * (a * d * d) = a * a * (d * a) * (d * d) by group,
              ← hcommad.eq]
            group
        _ = a ^ 3 * d ^ 3 := by rw [pow_three', pow_three']
        _ = a ^ 3 := by rw [hd3, mul_one]
    have ha3 : a ^ 3 = 1 := by rw [← hcube]; exact h3
    exact Subgroup.mul_mem _
      (Subgroup.mem_sup_left
        ((fc.pow_three_eq_one_iff_mem_zpowers_sup_sigma model ind hB2 haLW).mp ha3))
      (Subgroup.mem_sup_right hqP)
  · -- `Z₁ΣP` has exponent `3`
    refine pow_eq_one_of_mem_sup_of_commute ?_ ?_ ?_ hmem
    · intro z hz y hy
      exact (Subgroup.mem_centralizer_iff.mp (hZScen hz) y hy).symm
    · exact fun z hz => fc.pow_three_eq_one_of_mem_zpowers_sup_sigma model ind hB2 hz
    · intro y hy
      have h := Subgroup.orderOf_dvd_natCard _ hy
      rw [hPcard] at h
      exact orderOf_dvd_iff_pow_eq_one.mp h

end FirstCaseHypothesis

end OddOrder.Peterfalvi.Appendices.Suzuki
