/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Peterfalvi.Appendices.Suzuki.FirstCase.StepFifteen

/-!
# Peterfalvi Part II, Ch. II, step (15): the subgroup `LV`

T. Peterfalvi, *Character Theory for the Odd Order Theorem* (LMS LNS 272,
2000), Part II, Ch. II, (15), pp. 113-114.

The first half of (15) — `L` is cyclic of order `9`, inverted by `s`, normalized by
`V`, centralized by `W` but not by `P`, and contained in `R₁` — is in
`StepFifteen.lean`.  This file treats the group `LV` it generates:

> … It is also the case that `|R₂ : LV| = 3`, `Z(LV) = Z₁Σ` and `Ω₁(LV) = Z₁ΣP`.

`V = WP` normalizes `L` and meets it trivially, so `|LV| = |L|·|V| = 27·|W|`, while
`|R₂| = 3⁴·|W|` by (10.2); this gives the index.  The abelian subgroup `LW` has index
`3` in `LV`, which pins down the centre, and the `3`-torsion computation for `LV`
gives `Ω₁(LV)`.
-/

set_option autoImplicit false

open scoped Pointwise

namespace OddOrder.Peterfalvi.Appendices.Suzuki

namespace FirstCaseHypothesis

universe uG uΩ

variable {G : Type uG} {Ω : Type uΩ} [Group G] [MulAction G Ω] [Finite G]
  (fc : FirstCaseHypothesis G Ω)
  {F : Type uG} [NearFields.NearField F]
  (model : letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
    NearFields.AffineNearFieldModel fc.rankOneQuotient F)

include fc in
/-- `C_G(Z₁) = C_G(st)`: the centralizer of a subgroup generated by one element. -/
theorem centralizer_zpowers_st_eq :
    Subgroup.centralizer ((Subgroup.zpowers (fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t) : Subgroup G) : Set G)
      = Subgroup.centralizer ({fc.toHypothesis.distinguishedInvolution
        * fc.toHypothesis.t} : Set G) := by
  rw [Subgroup.zpowers_eq_closure, Subgroup.centralizer_closure]

include model in
/-- **`|LV| = 27·|W|`** ((15), p. 114): `V` normalizes `L`, `L ⊓ V = 1`, `|L| = 9` and
`|V| = |P|·|W| = 3·|W|`. -/
theorem card_sup_nonsplitTorus_V
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) :
    Nat.card ↥(fc.nonsplitTorus ⊔ fc.toHypothesis.V)
      = 27 * Nat.card ↥fc.toHypothesis.W := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  obtain ⟨-, hp3, -, -, -, -⟩ := fc.step_twelve model ind hB2
  obtain ⟨-, hLcard⟩ := fc.isCyclic_and_card_nonsplitTorus model ind hB2
  rw [card_sup_eq_mul_of_le_normalizer
      (fun b hb => fc.V_le_normalizer_nonsplitTorus model ind hB2 hb)
      (fc.nonsplitTorus_inf_V_eq_bot model ind hB2),
    hLcard, fc.card_V_eq_card_P_mul_card_W, fc.card_P, hp3]
  ring

include model in
/-- **`LV ≤ R₂`** ((15), p. 114): both `L` and `V` centralize `st`, and
`R₂ = C_G(Z₁)` by (14). -/
theorem sup_nonsplitTorus_V_le_sylow
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) (S : Sylow 3 G)
    (hR₁S : fc.sylowThreeNormalizerRSigma model ≤ (S : Subgroup G)) :
    fc.nonsplitTorus ⊔ fc.toHypothesis.V ≤ (S : Subgroup G) := by
  rw [← fc.sylow_eq_centralizer_zpowers model ind hB2 S hR₁S,
    fc.centralizer_zpowers_st_eq]
  refine sup_le ?_ ?_
  · rw [fc.nonsplitTorus_def]; exact inf_le_left
  · rw [← fc.toHypothesis.centralizer_mul_t_inf_centralizer_eq_V]; exact inf_le_left

include model in
/-- **`|R₂ : LV| = 3`** ((15), p. 114): `|R₂| = 3⁴·|W|` by (10.2) and
`|LV| = 27·|W|`. -/
theorem index_subgroupOf_sup_nonsplitTorus_V_eq_three
    (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hB2 : ¬ fc.p ∣ Nat.card (Abelianization G)) (S : Sylow 3 G)
    (hR₁S : fc.sylowThreeNormalizerRSigma model ≤ (S : Subgroup G)) :
    ((fc.nonsplitTorus ⊔ fc.toHypothesis.V).subgroupOf (S : Subgroup G)).index = 3 := by
  letI := fc.toHypothesis.centralizerQuotientMulAction fc.P_le_V
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  obtain ⟨-, -, -, -, -, hGp⟩ := fc.step_twelve model ind hB2
  have hScard : Nat.card ↥(S : Subgroup G) = 3 ^ 4 * Nat.card ↥fc.toHypothesis.W := by
    rw [Sylow.card_eq_multiplicity]
    exact hGp
  have hle := fc.sup_nonsplitTorus_V_le_sylow model ind hB2 S hR₁S
  have hsub : Nat.card ↥((fc.nonsplitTorus ⊔ fc.toHypothesis.V).subgroupOf
      (S : Subgroup G)) = 27 * Nat.card ↥fc.toHypothesis.W := by
    rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe hle).toEquiv]
    exact fc.card_sup_nonsplitTorus_V model ind hB2
  have hmul := ((fc.nonsplitTorus ⊔ fc.toHypothesis.V).subgroupOf
    (S : Subgroup G)).card_mul_index
  rw [hsub, hScard] at hmul
  have hWpos : 0 < Nat.card ↥fc.toHypothesis.W := Nat.card_pos
  nlinarith [hmul, hWpos]

end FirstCaseHypothesis

end OddOrder.Peterfalvi.Appendices.Suzuki
