/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Peterfalvi.Appendices.Suzuki.StructureOfH.FeitSibleyInput
import OddOrder.Peterfalvi.Appendices.Suzuki.KCyclic

/-!
# Peterfalvi Part II, Ch. III: the subgroup `QK`

T. Peterfalvi, *Character Theory for the Odd Order Theorem* (LMS LNS 272,
2000), Part II, Ch. III, §1, p. 115.

Step (4) of the proof of Theorem C reads:

> Let `λ` be a linear character of `H`, `λ ≠ 1_H`, such that `QK ⊂ Ker λ`.
> There is such a character since `H/QK ≅ V` is solvable and non-trivial.

This leaf builds the subgroup `QK = Q ∨ K` and the two facts about it that the
character construction consumes:

* `QK ⊴ H` — `Q ⊴ H` and `K ⊴ D`, and a `Q`-conjugate of an element of `K`
  differs from it by a commutator lying in `Q`;
* `[H : QK]` divides `[H : Q] = |D|`, which is odd.

The book states the stronger `H/QK ≅ V`; only the odd order of the quotient (for
solvability, via Feit–Thompson) and its non-triviality are used downstream, and
both are cheaper than the isomorphism.
-/

set_option autoImplicit false

namespace OddOrder.Peterfalvi.Appendices.Suzuki

universe uG uΩ

namespace Hypothesis

variable {G : Type uG} {Ω : Type uΩ} [Group G] [MulAction G Ω] [Finite G]
  (hyp : Hypothesis G Ω)

/-- The book's `QK` (p. 115): the subgroup generated by `Q` and `K`. -/
def QK : Subgroup G := hyp.Q ⊔ hyp.K

lemma Q_le_QK : hyp.Q ≤ hyp.QK := le_sup_left

lemma K_le_QK : hyp.K ≤ hyp.QK := le_sup_right

lemma QK_le_H : hyp.QK ≤ hyp.H :=
  sup_le hyp.Q_le_H (hyp.K_le_D.trans hyp.D_le_H)

/-- `K ⊴ D`, elementwise. -/
lemma conj_mem_K_of_mem_D {d : G} (hd : d ∈ hyp.D) {k : G} (hk : k ∈ hyp.K) :
    d * k * d⁻¹ ∈ hyp.K := by
  have h := (hyp.K_normal).conj_mem ⟨k, hyp.K_le_D hk⟩
    (Subgroup.mem_subgroupOf.mpr hk) ⟨d, hd⟩
  exact Subgroup.mem_subgroupOf.mp h

open scoped Pointwise in
/-- **`QK ⊴ H`** (implicit in the book's `H/QK`).  Conjugation by `h = q·d ∈ H`
fixes `Q` and moves `K` into `Q·K`: the `d`-part normalises `K`, and the `q`-part
changes an element of `K` by a commutator lying in `Q ⊴ H`. -/
theorem QK_normal_in_H {h : G} (hh : h ∈ hyp.H) {x : G} (hx : x ∈ hyp.QK) :
    h * x * h⁻¹ ∈ hyp.QK := by
  classical
  have hmapQ : hyp.Q.map (MulAut.conj h).toMonoidHom ≤ hyp.QK := by
    rintro _ ⟨y, hy, rfl⟩
    exact hyp.Q_le_QK (hyp.Q_normal_in_H h hh y hy)
  have hmapK : hyp.K.map (MulAut.conj h).toMonoidHom ≤ hyp.QK := by
    rintro _ ⟨k, hk, rfl⟩
    have hset : h ∈ (hyp.Q : Set G) * (hyp.D : Set G) := by
      rw [hyp.Q_mul_D_eq_H]; exact hh
    obtain ⟨q, hq, d, hd, rfl⟩ := Set.mem_mul.mp hset
    have hk' : d * k * d⁻¹ ∈ hyp.K := hyp.conj_mem_K_of_mem_D hd hk
    have hcomm : q * (d * k * d⁻¹) * q⁻¹ * (d * k * d⁻¹)⁻¹ ∈ hyp.Q := by
      have hkH : d * k * d⁻¹ ∈ hyp.H := hyp.D_le_H (hyp.K_le_D hk')
      have hinner : (d * k * d⁻¹) * q⁻¹ * (d * k * d⁻¹)⁻¹ ∈ hyp.Q :=
        hyp.Q_normal_in_H _ hkH _ (inv_mem hq)
      have heq : q * (d * k * d⁻¹) * q⁻¹ * (d * k * d⁻¹)⁻¹
          = q * ((d * k * d⁻¹) * q⁻¹ * (d * k * d⁻¹)⁻¹) := by group
      rw [heq]
      exact hyp.Q.mul_mem hq hinner
    have hval : (MulAut.conj (q * d)).toMonoidHom k
        = (q * (d * k * d⁻¹) * q⁻¹ * (d * k * d⁻¹)⁻¹) * (d * k * d⁻¹) := by
      simp only [MulEquiv.coe_toMonoidHom, MulAut.conj_apply]
      group
    rw [hval]
    exact hyp.QK.mul_mem (hyp.Q_le_QK hcomm) (hyp.K_le_QK hk')
  have hle : hyp.QK.map (MulAut.conj h).toMonoidHom ≤ hyp.QK := by
    rw [QK, Subgroup.map_sup]
    exact sup_le hmapQ hmapK
  exact hle ⟨x, hx, rfl⟩

/-- `[H : QK]` divides `|D|`: `Q ≤ QK ≤ H` and `[H : Q] = |D|`. -/
theorem index_QK_subgroupOf_dvd_card_D :
    (hyp.QK.subgroupOf hyp.H).index ∣ Nat.card ↥hyp.D := by
  have hle : hyp.Q.subgroupOf hyp.H ≤ hyp.QK.subgroupOf hyp.H := fun x hx =>
    Subgroup.mem_subgroupOf.mpr (hyp.Q_le_QK (Subgroup.mem_subgroupOf.mp hx))
  refine (Subgroup.index_dvd_of_le hle).trans ?_
  -- `[H : Q] = |H| / |Q| = |D|`
  have hcard : Nat.card ↥(hyp.Q.subgroupOf hyp.H) * (hyp.Q.subgroupOf hyp.H).index
      = Nat.card ↥hyp.H := (hyp.Q.subgroupOf hyp.H).card_mul_index
  have hQ : Nat.card ↥(hyp.Q.subgroupOf hyp.H) = Nat.card ↥hyp.Q :=
    Nat.card_congr (Subgroup.subgroupOfEquivOfLe hyp.Q_le_H).toEquiv
  have hH : Nat.card ↥hyp.Q * Nat.card ↥hyp.D = Nat.card ↥hyp.H := hyp.card_H_eq.symm
  rw [hQ] at hcard
  exact ⟨1, by
    have := hcard.trans hH.symm
    have hpos : 0 < Nat.card ↥hyp.Q := Nat.card_pos
    rw [mul_one]
    exact (Nat.eq_of_mul_eq_mul_left hpos this).symm⟩

/-- `[H : QK]` is odd, since `|D|` is odd. -/
theorem odd_index_QK_subgroupOf : Odd (hyp.QK.subgroupOf hyp.H).index :=
  hyp.D_odd.of_dvd_nat hyp.index_QK_subgroupOf_dvd_card_D

end Hypothesis

end OddOrder.Peterfalvi.Appendices.Suzuki
