/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Peterfalvi.Appendices.Suzuki.StructureOfH.FeitSibleyInput
import OddOrder.Peterfalvi.Appendices.Suzuki.KCyclic
import OddOrder.GroupTheory.CardSupInf
import OddOrder.Peterfalvi.Appendices.Suzuki.ConjugacyInV

/-!
# Peterfalvi Part II, Ch. III: the subgroup `QK`

T. Peterfalvi, *Character Theory for the Odd Order Theorem* (LMS LNS 272,
2000), Part II, Ch. III, §1, p. 115.

Step (4) of the proof of Theorem C reads:

> Let `λ` be a linear character of `H`, `λ ≠ 1_H`, such that `QK ⊂ Ker λ`.
> There is such a character since `H/QK ≅ V` is solvable and non-trivial.

This leaf builds the subgroup `QK = Q ∨ K` and the two facts about it that the
character construction consumes:

* `QK ⊴ H` — `Q ⊴ H` and `K ⊴ D`, and a `Q`-conjugate of an element of `K`
  differs from it by a commutator lying in `Q`;
* `[H : QK]` divides `[H : Q] = |D|`, which is odd.

The book states the stronger `H/QK ≅ V`; only the odd order of the quotient (for
solvability, via Feit–Thompson) and its non-triviality are used downstream, and
both are cheaper than the isomorphism.
-/

set_option autoImplicit false

namespace OddOrder.Peterfalvi.Appendices.Suzuki

open OddOrder.RepresentationTheory

universe uG uΩ

namespace Hypothesis

variable {G : Type uG} {Ω : Type uΩ} [Group G] [MulAction G Ω] [Finite G]
  (hyp : Hypothesis G Ω)

/-- The book's `QK` (p. 115): the subgroup generated by `Q` and `K`. -/
def QK : Subgroup G := hyp.Q ⊔ hyp.K

lemma Q_le_QK : hyp.Q ≤ hyp.QK := le_sup_left

lemma K_le_QK : hyp.K ≤ hyp.QK := le_sup_right

lemma QK_le_H : hyp.QK ≤ hyp.H :=
  sup_le hyp.Q_le_H (hyp.K_le_D.trans hyp.D_le_H)

/-- `K ⊴ D`, elementwise. -/
lemma conj_mem_K_of_mem_D {d : G} (hd : d ∈ hyp.D) {k : G} (hk : k ∈ hyp.K) :
    d * k * d⁻¹ ∈ hyp.K := by
  have h := (hyp.K_normal).conj_mem ⟨k, hyp.K_le_D hk⟩
    (Subgroup.mem_subgroupOf.mpr hk) ⟨d, hd⟩
  exact Subgroup.mem_subgroupOf.mp h

open scoped Pointwise in
/-- **`QK ⊴ H`** (implicit in the book's `H/QK`).  Conjugation by `h = q·d ∈ H`
fixes `Q` and moves `K` into `Q·K`: the `d`-part normalises `K`, and the `q`-part
changes an element of `K` by a commutator lying in `Q ⊴ H`. -/
theorem QK_normal_in_H {h : G} (hh : h ∈ hyp.H) {x : G} (hx : x ∈ hyp.QK) :
    h * x * h⁻¹ ∈ hyp.QK := by
  classical
  have hmapQ : hyp.Q.map (MulAut.conj h).toMonoidHom ≤ hyp.QK := by
    rintro _ ⟨y, hy, rfl⟩
    exact hyp.Q_le_QK (hyp.Q_normal_in_H h hh y hy)
  have hmapK : hyp.K.map (MulAut.conj h).toMonoidHom ≤ hyp.QK := by
    rintro _ ⟨k, hk, rfl⟩
    have hset : h ∈ (hyp.Q : Set G) * (hyp.D : Set G) := by
      rw [hyp.Q_mul_D_eq_H]; exact hh
    obtain ⟨q, hq, d, hd, rfl⟩ := Set.mem_mul.mp hset
    have hk' : d * k * d⁻¹ ∈ hyp.K := hyp.conj_mem_K_of_mem_D hd hk
    have hcomm : q * (d * k * d⁻¹) * q⁻¹ * (d * k * d⁻¹)⁻¹ ∈ hyp.Q := by
      have hkH : d * k * d⁻¹ ∈ hyp.H := hyp.D_le_H (hyp.K_le_D hk')
      have hinner : (d * k * d⁻¹) * q⁻¹ * (d * k * d⁻¹)⁻¹ ∈ hyp.Q :=
        hyp.Q_normal_in_H _ hkH _ (inv_mem hq)
      have heq : q * (d * k * d⁻¹) * q⁻¹ * (d * k * d⁻¹)⁻¹
          = q * ((d * k * d⁻¹) * q⁻¹ * (d * k * d⁻¹)⁻¹) := by group
      rw [heq]
      exact hyp.Q.mul_mem hq hinner
    have hval : (MulAut.conj (q * d)).toMonoidHom k
        = (q * (d * k * d⁻¹) * q⁻¹ * (d * k * d⁻¹)⁻¹) * (d * k * d⁻¹) := by
      simp only [MulEquiv.coe_toMonoidHom, MulAut.conj_apply]
      group
    rw [hval]
    exact hyp.QK.mul_mem (hyp.Q_le_QK hcomm) (hyp.K_le_QK hk')
  have hle : hyp.QK.map (MulAut.conj h).toMonoidHom ≤ hyp.QK := by
    rw [QK, Subgroup.map_sup]
    exact sup_le hmapQ hmapK
  exact hle ⟨x, hx, rfl⟩

/-- `[H : QK]` divides `|D|`: `Q ≤ QK ≤ H` and `[H : Q] = |D|`. -/
theorem index_QK_subgroupOf_dvd_card_D :
    (hyp.QK.subgroupOf hyp.H).index ∣ Nat.card ↥hyp.D := by
  have hle : hyp.Q.subgroupOf hyp.H ≤ hyp.QK.subgroupOf hyp.H := fun x hx =>
    Subgroup.mem_subgroupOf.mpr (hyp.Q_le_QK (Subgroup.mem_subgroupOf.mp hx))
  refine (Subgroup.index_dvd_of_le hle).trans ?_
  -- `[H : Q] = |H| / |Q| = |D|`
  have hcard : Nat.card ↥(hyp.Q.subgroupOf hyp.H) * (hyp.Q.subgroupOf hyp.H).index
      = Nat.card ↥hyp.H := (hyp.Q.subgroupOf hyp.H).card_mul_index
  have hQ : Nat.card ↥(hyp.Q.subgroupOf hyp.H) = Nat.card ↥hyp.Q :=
    Nat.card_congr (Subgroup.subgroupOfEquivOfLe hyp.Q_le_H).toEquiv
  have hH : Nat.card ↥hyp.Q * Nat.card ↥hyp.D = Nat.card ↥hyp.H := hyp.card_H_eq.symm
  rw [hQ] at hcard
  exact ⟨1, by
    have := hcard.trans hH.symm
    have hpos : 0 < Nat.card ↥hyp.Q := Nat.card_pos
    rw [mul_one]
    exact (Nat.eq_of_mul_eq_mul_left hpos this).symm⟩

/-- `[H : QK]` is odd, since `|D|` is odd. -/
theorem odd_index_QK_subgroupOf : Odd (hyp.QK.subgroupOf hyp.H).index :=
  hyp.D_odd.of_dvd_nat hyp.index_QK_subgroupOf_dvd_card_D

/-- `Q ⊴ H`, in `subgroupOf` form. -/
instance Q_subgroupOf_H_normal : (hyp.Q.subgroupOf hyp.H).Normal := by
  constructor
  intro x hx y
  exact Subgroup.mem_subgroupOf.mpr
    (hyp.Q_normal_in_H y y.2 x (Subgroup.mem_subgroupOf.mp hx))

open scoped Pointwise in
/-- **`QK ∩ V = 1`**.  Writing an element of `QK ∩ V` as `q·k` (legitimate inside
`H`, where `Q` is normal), the factor `q = v·k⁻¹` lies in `Q ∩ D = 1`, so the
element is in `K ∩ V = 1`. -/
theorem QK_inf_V_eq_bot : hyp.QK ⊓ hyp.V = ⊥ := by
  classical
  refine le_bot_iff.mp fun v hv => ?_
  obtain ⟨hvQK, hvV⟩ := Subgroup.mem_inf.mp hv
  have hvH : v ∈ hyp.H := hyp.QK_le_H hvQK
  have hKH : hyp.K ≤ hyp.H := hyp.K_le_D.trans hyp.D_le_H
  have hsub : (⟨v, hvH⟩ : ↥hyp.H) ∈
      hyp.Q.subgroupOf hyp.H ⊔ hyp.K.subgroupOf hyp.H := by
    rw [← Subgroup.subgroupOf_sup hyp.Q_le_H hKH]
    exact Subgroup.mem_subgroupOf.mpr hvQK
  rw [← SetLike.mem_coe, Subgroup.normal_mul, Set.mem_mul] at hsub
  obtain ⟨a, ha, b, hb, hab⟩ := hsub
  have haQ : (a : G) ∈ hyp.Q := Subgroup.mem_subgroupOf.mp ha
  have hbK : (b : G) ∈ hyp.K := Subgroup.mem_subgroupOf.mp hb
  have hval : (a : G) * (b : G) = v := congrArg (fun y : ↥hyp.H => (y : G)) hab
  -- `a = v·b⁻¹ ∈ Q ⊓ D = 1`
  have haD : (a : G) ∈ hyp.D := by
    have : (a : G) = v * (b : G)⁻¹ := by
      rw [← hval]; group
    rw [this]
    exact hyp.D.mul_mem (hyp.V_le_D hvV) (inv_mem (hyp.K_le_D hbK))
  have ha1 : (a : G) = 1 := by
    have hmem : (a : G) ∈ hyp.Q ⊓ hyp.D := Subgroup.mem_inf.mpr ⟨haQ, haD⟩
    rwa [hyp.Q_inf_D_eq_bot, Subgroup.mem_bot] at hmem
  -- so `v = b ∈ K ⊓ V = 1`
  have hvK : v ∈ hyp.K := by
    have : v = (b : G) := by rw [← hval, ha1, one_mul]
    rw [this]; exact hbK
  have hmem : v ∈ hyp.K ⊓ hyp.V := Subgroup.mem_inf.mpr ⟨hvK, hvV⟩
  rw [hyp.K_inf_V_eq_bot, Subgroup.mem_bot] at hmem
  rw [Subgroup.mem_bot]
  exact hmem

/-- **`QK ≠ H`** when `V ≠ 1` (hypothesis (C1)): `V ≤ H` but `QK ∩ V = 1`. -/
theorem QK_ne_H (hV : hyp.V ≠ ⊥) : hyp.QK ≠ hyp.H := by
  intro h
  refine hV (le_bot_iff.mp ?_)
  have hVQK : hyp.V ≤ hyp.QK := h ▸ (hyp.V_le_D.trans hyp.D_le_H)
  have hle : hyp.V ≤ hyp.QK ⊓ hyp.V := le_inf hVQK le_rfl
  rwa [hyp.QK_inf_V_eq_bot] at hle

/-- `QK ⊴ H`, in `subgroupOf` form. -/
instance QK_subgroupOf_H_normal : (hyp.QK.subgroupOf hyp.H).Normal := by
  constructor
  intro x hx y
  exact Subgroup.mem_subgroupOf.mpr
    (hyp.QK_normal_in_H y.2 (Subgroup.mem_subgroupOf.mp hx))

/-- The quotient `H/QK` has odd order (`[H : QK]` divides `|D|`). -/
theorem odd_card_quotient_QK :
    Odd (Nat.card (↥hyp.H ⧸ hyp.QK.subgroupOf hyp.H)) :=
  hyp.odd_index_QK_subgroupOf

/-- `QK.subgroupOf H ≠ ⊤`, i.e. `QK` is a proper subgroup of `H`. -/
theorem QK_subgroupOf_ne_top (hV : hyp.V ≠ ⊥) : hyp.QK.subgroupOf hyp.H ≠ ⊤ := by
  intro h
  exact hyp.QK_ne_H hV (le_antisymm hyp.QK_le_H (Subgroup.subgroupOf_eq_top.mp h))

/-- **`H/QK` has a proper derived subgroup** — the input of the linear-character
construction.  The book's route: `H/QK ≅ V` is solvable and non-trivial.  Here the
quotient has odd order, hence is solvable by the **Feit–Thompson theorem**, and it
is non-trivial because `QK ≠ H` (hypothesis (C1): `V ≠ 1`). -/
theorem commutator_quotient_QK_ne_top (hV : hyp.V ≠ ⊥) :
    _root_.commutator (↥hyp.H ⧸ hyp.QK.subgroupOf hyp.H) ≠ ⊤ := by
  haveI : IsSolvable (↥hyp.H ⧸ hyp.QK.subgroupOf hyp.H) :=
    OddOrder.feitThompson hyp.odd_card_quotient_QK
  haveI : Nontrivial (↥hyp.H ⧸ hyp.QK.subgroupOf hyp.H) := by
    have h1 : (hyp.QK.subgroupOf hyp.H).index ≠ 1 := fun h =>
      hyp.QK_subgroupOf_ne_top hV (Subgroup.index_eq_one.mp h)
    rcases subsingleton_or_nontrivial (↥hyp.H ⧸ hyp.QK.subgroupOf hyp.H) with hs | hn
    · exact absurd (Nat.card_eq_one_iff_unique.mpr ⟨hs, ⟨1⟩⟩ : _root_.Nat.card _ = 1) h1
    · exact hn
  exact (IsSolvable.commutator_lt_top_of_nontrivial _).ne

/-- **Peterfalvi Part II, Ch. III, Theorem C, step (4)** (p. 115): "Let `λ` be a
linear character of `H`, `λ ≠ 1_H`, such that `QK ⊂ Ker λ`.  There is such a
character since `H/QK ≅ V` is solvable and non-trivial." -/
theorem exists_linearCharacter_leKer_QK (hV : hyp.V ≠ ⊥) :
    ∃ θ : IrreducibleCharacter ↥hyp.H,
      θ ≠ OddOrder.RepresentationTheory.trivialIrreducibleCharacter ↥hyp.H ∧
      ((hyp.QK.subgroupOf hyp.H : Subgroup ↥hyp.H) : Set ↥hyp.H) ⊆
        OddOrder.Peterfalvi.S03.characterKernel (θ : ClassFunction ↥hyp.H ℂ) ∧
      (θ : ClassFunction ↥hyp.H ℂ) (1 : ↥hyp.H) = 1 :=
  OddOrder.Peterfalvi.S08.exists_irreducibleCharacter_ne_trivial_subset_kernel_of_commutator_ne_top
    _ (hyp.commutator_quotient_QK_ne_top hV)

end Hypothesis

namespace SecondCaseHypothesis

variable {G : Type uG} {Ω : Type uΩ} [Group G] [MulAction G Ω] [Finite G]
  (sc : SecondCaseHypothesis G Ω)

/-- **Peterfalvi Part II, Ch. III, Theorem C, step (5)** (p. 115): `(|K|, |V|) = 1`.

The book: "If `(|K|,|V|) ≠ 1`, then `D` has a non-cyclic subgroup of order `p²`,
`p` prime, and so `D` cannot act fixed-point-freely on `Q₁` ([H], Kapitel V, Satz
8.15)."

Here the Frobenius-complement structure theorem is not needed: a non-cyclic
abelian subgroup of `D` is already impossible
(`isCyclic_of_isMulCommutative_le_D`).  The `p²` subgroup is built from elements
`x ∈ K`, `y ∈ V` of order `p`; they commute because `K` is cyclic and normal in
`D`, so `y` acts on `⟨x⟩ ≅ C_p` by `x ↦ x^j`, and `y^p = 1` forces
`j^p ≡ 1 (mod p)`, while Fermat gives `j^p ≡ j`, so `j ≡ 1`.  (This replaces the
book's appeal to `|Aut(C_p)| = p − 1`.) -/
theorem coprime_card_K_V (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hQ1 : sc.toHypothesis.Q1 ≠ ⊥) :
    Nat.Coprime (Nat.card ↥sc.toHypothesis.K) (Nat.card ↥sc.toHypothesis.V) := by
  classical
  by_contra hcop
  obtain ⟨p, hp, hpdvd⟩ := Nat.exists_prime_and_dvd hcop
  haveI : Fact p.Prime := ⟨hp⟩
  haveI : Fintype ↥sc.toHypothesis.K := Fintype.ofFinite _
  haveI : Fintype ↥sc.toHypothesis.V := Fintype.ofFinite _
  obtain ⟨xK, hxord⟩ := exists_prime_orderOf_dvd_card (G := ↥sc.toHypothesis.K) p
    (by rw [← Nat.card_eq_fintype_card]; exact hpdvd.trans (Nat.gcd_dvd_left _ _))
  obtain ⟨yV, hyord⟩ := exists_prime_orderOf_dvd_card (G := ↥sc.toHypothesis.V) p
    (by rw [← Nat.card_eq_fintype_card]; exact hpdvd.trans (Nat.gcd_dvd_right _ _))
  set x : G := (xK : G) with hxdef
  set y : G := (yV : G) with hydef
  have hxK : x ∈ sc.toHypothesis.K := xK.2
  have hyV : y ∈ sc.toHypothesis.V := yV.2
  have hxo : orderOf x = p := by rw [hxdef, Subgroup.orderOf_coe]; exact hxord
  have hyo : orderOf y = p := by rw [hydef, Subgroup.orderOf_coe]; exact hyord
  have hyD : y ∈ sc.toHypothesis.D := sc.toHypothesis.V_le_D hyV
  -- (2) `y` normalises the unique order-`p` subgroup `⟨x⟩` of the cyclic `K`
  have hconjK : y * x * y⁻¹ ∈ sc.toHypothesis.K :=
    sc.toHypothesis.conj_mem_K_of_mem_D hyD hxK
  have hconjord : orderOf (y * x * y⁻¹) = p := by
    have h := orderOf_injective (MulAut.conj y).toMonoidHom
      (MulAut.conj y).injective x
    simpa [MulAut.conj_apply, hxo] using h
  have hmemzp : y * x * y⁻¹ ∈ Subgroup.zpowers x := by
    have hcard : Nat.card ↥((Subgroup.zpowers (y * x * y⁻¹)).subgroupOf sc.toHypothesis.K)
        = Nat.card ↥((Subgroup.zpowers x).subgroupOf sc.toHypothesis.K) := by
      rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe
          (Subgroup.zpowers_le.mpr hconjK)).toEquiv,
        Nat.card_congr (Subgroup.subgroupOfEquivOfLe
          (Subgroup.zpowers_le.mpr hxK)).toEquiv,
        Nat.card_zpowers, Nat.card_zpowers, hconjord, hxo]
    have heq := OddOrder.GroupTheory.cyclic_subgroup_eq_of_card_eq
      (C := ↥sc.toHypothesis.K) hcard
    have hmem : (⟨y * x * y⁻¹, hconjK⟩ : ↥sc.toHypothesis.K) ∈
        (Subgroup.zpowers (y * x * y⁻¹)).subgroupOf sc.toHypothesis.K :=
      Subgroup.mem_subgroupOf.mpr (Subgroup.mem_zpowers _)
    rw [heq] at hmem
    exact Subgroup.mem_subgroupOf.mp hmem
  -- (3) `x` and `y` commute, by Fermat
  obtain ⟨j, hj0⟩ := hmemzp
  have hj : x ^ j = y * x * y⁻¹ := hj0
  have hconjx : (MulAut.conj y) x = x ^ j := by
    simpa [MulAut.conj_apply] using hj.symm
  have hpow : ∀ n : ℕ, ((MulAut.conj y ^ n : MulAut G)) x = x ^ (j ^ n) := by
    intro n
    induction n with
    | zero => simp
    | succ k ih =>
        have hstep : ((MulAut.conj y ^ (k + 1) : MulAut G)) x
            = ((MulAut.conj y ^ k : MulAut G)) ((MulAut.conj y) x) := by
          rw [pow_succ]; rfl
        rw [hstep, hconjx, map_zpow, ih, ← zpow_mul, pow_succ]
  have hfix : x ^ (j ^ p) = x := by
    have hyp1 : y ^ p = 1 := by rw [← hyo]; exact pow_orderOf_eq_one y
    have h1 : ((MulAut.conj y ^ p : MulAut G)) x = x := by
      rw [← map_pow, hyp1]
      simp
    rw [← hpow p, h1]
  have hmod : (j ^ p : ℤ) ≡ 1 [ZMOD (p : ℤ)] := by
    have := (zpow_eq_zpow_iff_modEq (x := x) (m := j ^ p) (n := 1)).mp (by
      rw [zpow_one]; exact hfix)
    rwa [hxo] at this
  have hj1 : (j : ℤ) ≡ 1 [ZMOD (p : ℤ)] := by
    have hferm : ((j ^ p : ℤ) : ZMod p) = ((j : ℤ) : ZMod p) := by
      push_cast; exact ZMod.pow_card _
    have h1 : ((j ^ p : ℤ) : ZMod p) = ((1 : ℤ) : ZMod p) :=
      (ZMod.intCast_eq_intCast_iff' _ _ _).mpr (by exact_mod_cast hmod)
    exact (ZMod.intCast_eq_intCast_iff' _ _ _).mp (by rw [← hferm, h1])
  have hcomm : x * y = y * x := by
    have hxj : x ^ j = x := by
      have := (zpow_eq_zpow_iff_modEq (x := x) (m := j) (n := 1)).mpr (by
        rw [hxo]; exact_mod_cast hj1)
      rwa [zpow_one] at this
    have : y * x * y⁻¹ = x := by rw [← hj, hxj]
    calc x * y = (y * x * y⁻¹) * y := by rw [this]
      _ = y * x := by group
  -- (4) `E = ⟨x, y⟩` is abelian and contained in `D`
  set E : Subgroup G := Subgroup.closure ({x, y} : Set G) with hEdef
  haveI : IsMulCommutative ↥E := by
    refine Subgroup.isMulCommutative_closure ?_
    rintro a (rfl | rfl) b (rfl | rfl)
    · rfl
    · exact hcomm
    · exact hcomm.symm
    · rfl
  have hED : E ≤ sc.toHypothesis.D := by
    rw [hEdef, Subgroup.closure_le]
    rintro a (rfl | rfl)
    · exact sc.toHypothesis.K_le_D hxK
    · exact hyD
  haveI : IsCyclic ↥E := sc.isCyclic_of_isMulCommutative_le_D ind hQ1 hED
  -- (5) inside the cyclic `E`, `⟨x⟩` and `⟨y⟩` both have order `p`, so `x ∈ V`
  have hxE : x ∈ E := Subgroup.subset_closure (by simp)
  have hyE : y ∈ E := Subgroup.subset_closure (by simp)
  have hcard : Nat.card ↥(Subgroup.zpowers (⟨x, hxE⟩ : ↥E))
      = Nat.card ↥(Subgroup.zpowers (⟨y, hyE⟩ : ↥E)) := by
    rw [Nat.card_zpowers, Nat.card_zpowers, Subgroup.orderOf_mk, Subgroup.orderOf_mk,
      hxo, hyo]
  have heq := OddOrder.GroupTheory.cyclic_subgroup_eq_of_card_eq (C := ↥E) hcard
  have hxmem : (⟨x, hxE⟩ : ↥E) ∈ Subgroup.zpowers (⟨y, hyE⟩ : ↥E) := by
    rw [← heq]; exact Subgroup.mem_zpowers _
  obtain ⟨n, hn⟩ := hxmem
  have hxV : x ∈ sc.toHypothesis.V := by
    have : y ^ n = x := congrArg (fun z : ↥E => (z : G)) hn
    rw [← this]
    exact zpow_mem hyV n
  have hmemKV : x ∈ sc.toHypothesis.K ⊓ sc.toHypothesis.V :=
    Subgroup.mem_inf.mpr ⟨hxK, hxV⟩
  rw [sc.toHypothesis.K_inf_V_eq_bot, Subgroup.mem_bot] at hmemKV
  rw [hmemKV] at hxo
  simp only [orderOf_one] at hxo
  exact hp.one_lt.ne hxo

end SecondCaseHypothesis

namespace Hypothesis

variable {G : Type uG} {Ω : Type uΩ} [Group G] [MulAction G Ω] [Finite G]
  (hyp : Hypothesis G Ω)

/-- `D` normalises `K` (`K ⊴ D`), in `Subgroup.normalizer` form. -/
theorem D_le_normalizer_K : hyp.D ≤ Subgroup.normalizer (hyp.K : Set G) := by
  intro d hd
  rw [Subgroup.mem_normalizer_iff]
  intro z
  constructor
  · exact fun hz => hyp.conj_mem_K_of_mem_D hd hz
  · intro hz
    have h2 := hyp.conj_mem_K_of_mem_D (inv_mem hd) hz
    simpa [mul_assoc] using h2

/-- `D = V ∨ K` — the book's `D = KV` (`K ⊴ D`, `K ∩ V = 1`). -/
theorem V_sup_K_eq_D : hyp.V ⊔ hyp.K = hyp.D := by
  refine le_antisymm (sup_le hyp.V_le_D hyp.K_le_D) fun d hd => ?_
  obtain ⟨v, hv, z, hz, rfl⟩ := hyp.exists_mem_V_mul_mem_K hd
  exact Subgroup.mul_mem _ (Subgroup.mem_sup_left hv) (Subgroup.mem_sup_right hz)

/-- `|D| = |V|·|K|`.  Computed inside `↥D`, where `K` is normal. -/
theorem card_D_eq : Nat.card ↥hyp.D = Nat.card ↥hyp.V * Nat.card ↥hyp.K := by
  have hdisj : hyp.V.subgroupOf hyp.D ⊓ hyp.K.subgroupOf hyp.D = ⊥ := by
    refine le_bot_iff.mp fun z hz => ?_
    obtain ⟨hzV, hzK⟩ := Subgroup.mem_inf.mp hz
    have hmem : (z : G) ∈ hyp.K ⊓ hyp.V :=
      Subgroup.mem_inf.mpr ⟨Subgroup.mem_subgroupOf.mp hzK, Subgroup.mem_subgroupOf.mp hzV⟩
    rw [hyp.K_inf_V_eq_bot, Subgroup.mem_bot] at hmem
    rw [Subgroup.mem_bot]; exact Subtype.ext hmem
  have hcard := OddOrder.GroupTheory.card_sup_eq_mul_of_disjoint_normal
    (G := ↥hyp.D) (H := hyp.V.subgroupOf hyp.D) (N := hyp.K.subgroupOf hyp.D) hdisj
  rw [← Subgroup.subgroupOf_sup hyp.V_le_D hyp.K_le_D, hyp.V_sup_K_eq_D,
    Subgroup.subgroupOf_self, Nat.card_congr (Subgroup.topEquiv (G := ↥hyp.D)).toEquiv,
    Nat.card_congr (Subgroup.subgroupOfEquivOfLe hyp.V_le_D).toEquiv,
    Nat.card_congr (Subgroup.subgroupOfEquivOfLe hyp.K_le_D).toEquiv] at hcard
  exact hcard

/-- `|QK| = |K|·|Q|`.  Computed inside `↥H`, where `Q` is normal. -/
theorem card_QK_eq : Nat.card ↥hyp.QK = Nat.card ↥hyp.K * Nat.card ↥hyp.Q := by
  have hKH : hyp.K ≤ hyp.H := hyp.K_le_D.trans hyp.D_le_H
  have hdisj : hyp.K.subgroupOf hyp.H ⊓ hyp.Q.subgroupOf hyp.H = ⊥ := by
    refine le_bot_iff.mp fun z hz => ?_
    obtain ⟨hzK', hzQ'⟩ := Subgroup.mem_inf.mp hz
    have hzK : (z : G) ∈ hyp.K := Subgroup.mem_subgroupOf.mp hzK'
    have hzQ : (z : G) ∈ hyp.Q := Subgroup.mem_subgroupOf.mp hzQ'
    have : (z : G) ∈ hyp.Q ⊓ hyp.D := Subgroup.mem_inf.mpr ⟨hzQ, hyp.K_le_D hzK⟩
    rw [hyp.Q_inf_D_eq_bot, Subgroup.mem_bot] at this
    rw [Subgroup.mem_bot]; exact Subtype.ext this
  have hcard := OddOrder.GroupTheory.card_sup_eq_mul_of_disjoint_normal
    (G := ↥hyp.H) (H := hyp.K.subgroupOf hyp.H) (N := hyp.Q.subgroupOf hyp.H) hdisj
  rw [← Subgroup.subgroupOf_sup hKH hyp.Q_le_H,
    Nat.card_congr (Subgroup.subgroupOfEquivOfLe hKH).toEquiv,
    Nat.card_congr (Subgroup.subgroupOfEquivOfLe hyp.Q_le_H).toEquiv,
    Nat.card_congr (Subgroup.subgroupOfEquivOfLe
      (show hyp.K ⊔ hyp.Q ≤ hyp.H from sup_le hKH hyp.Q_le_H)).toEquiv] at hcard
  rw [QK, sup_comm]
  exact hcard

/-- `H/Q ≅ D` has odd order, so `|↥H ⧸ Q.subgroupOf H| = |D|`. -/
theorem card_quotient_Q_eq_card_D :
    Nat.card (↥hyp.H ⧸ hyp.Q.subgroupOf hyp.H) = Nat.card ↥hyp.D := by
  have hmul : Nat.card ↥(hyp.Q.subgroupOf hyp.H) * (hyp.Q.subgroupOf hyp.H).index
      = Nat.card ↥hyp.H := (hyp.Q.subgroupOf hyp.H).card_mul_index
  rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe hyp.Q_le_H).toEquiv,
    hyp.card_H_eq] at hmul
  exact Nat.eq_of_mul_eq_mul_left Nat.card_pos hmul

/-- **`H` is solvable**: `Q` is nilpotent (Ch. I §2, Proposition 1(b)) and
`H/Q ≅ D` has odd order, hence is solvable by the Feit–Thompson theorem.

This is what lets Chapter III apply Hall's theorems inside `H` (the book's "by a
theorem of Hall" in step (6)). -/
instance isSolvable_H : IsSolvable ↥hyp.H := by
  haveI : Group.IsNilpotent ↥hyp.Q := hyp.isNilpotent_Q
  haveI : IsSolvable ↥(hyp.Q.subgroupOf hyp.H) := by
    haveI : IsSolvable ↥hyp.Q := inferInstance
    exact solvable_of_solvable_injective
      (f := (Subgroup.subgroupOfEquivOfLe hyp.Q_le_H).toMonoidHom)
      (Subgroup.subgroupOfEquivOfLe hyp.Q_le_H).injective
  haveI : IsSolvable (↥hyp.H ⧸ hyp.Q.subgroupOf hyp.H) :=
    OddOrder.feitThompson (by
      rw [hyp.card_quotient_Q_eq_card_D]; exact hyp.D_odd)
  exact solvable_of_ker_le_range
    (hyp.Q.subgroupOf hyp.H).subtype (QuotientGroup.mk' (hyp.Q.subgroupOf hyp.H))
    (by rw [QuotientGroup.ker_mk', Subgroup.range_subtype])

/-- **`[H : QK] = |V|`** — the index computation behind the book's `H/QK ≅ V`. -/
theorem index_QK_subgroupOf_eq_card_V :
    (hyp.QK.subgroupOf hyp.H).index = Nat.card ↥hyp.V := by
  have hQK : Nat.card ↥(hyp.QK.subgroupOf hyp.H) = Nat.card ↥hyp.QK :=
    Nat.card_congr (Subgroup.subgroupOfEquivOfLe hyp.QK_le_H).toEquiv
  have hmul : Nat.card ↥(hyp.QK.subgroupOf hyp.H) * (hyp.QK.subgroupOf hyp.H).index
      = Nat.card ↥hyp.H := (hyp.QK.subgroupOf hyp.H).card_mul_index
  rw [hQK, hyp.card_QK_eq] at hmul
  have hH : Nat.card ↥hyp.H = Nat.card ↥hyp.Q * (Nat.card ↥hyp.V * Nat.card ↥hyp.K) := by
    rw [← hyp.card_D_eq]; exact hyp.card_H_eq
  rw [hH] at hmul
  have hpos : 0 < Nat.card ↥hyp.K * Nat.card ↥hyp.Q := Nat.mul_pos Nat.card_pos Nat.card_pos
  refine Nat.eq_of_mul_eq_mul_left hpos ?_
  rw [hmul]; ring

end Hypothesis

namespace SecondCaseHypothesis

variable {G : Type uG} {Ω : Type uΩ} [Group G] [MulAction G Ω] [Finite G]
  (sc : SecondCaseHypothesis G Ω)

/-- **Peterfalvi Part II, Ch. III, Theorem C, step (5) conclusion** (p. 115):
"Thus `QK` is a Hall subgroup of `H`."

`|QK| = |K|·|Q|` and `[H : QK] = |V|`; `(|K|,|V|) = 1` is step (5) and
`(|Q|,|V|) = 1` follows from `(|Q|,|D|) = 1`. -/
theorem coprime_card_QK_index (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hQ1 : sc.toHypothesis.Q1 ≠ ⊥) :
    Nat.Coprime (Nat.card ↥sc.toHypothesis.QK)
      (sc.toHypothesis.QK.subgroupOf sc.toHypothesis.H).index := by
  rw [sc.toHypothesis.card_QK_eq, sc.toHypothesis.index_QK_subgroupOf_eq_card_V]
  refine Nat.coprime_mul_iff_left.mpr ⟨sc.coprime_card_K_V ind hQ1, ?_⟩
  exact (sc.coprime_card_Q_D ind).coprime_dvd_right
    (Subgroup.card_dvd_of_le sc.toHypothesis.V_le_D)

end SecondCaseHypothesis

namespace Hypothesis

variable {G : Type uG} {Ω : Type uΩ} [Group G] [MulAction G Ω] [Finite G]
  (hyp : Hypothesis G Ω)

/-- `|H| = |QK|·|V|`. -/
theorem card_H_eq_card_QK_mul_card_V :
    Nat.card ↥hyp.H = Nat.card ↥hyp.QK * Nat.card ↥hyp.V := by
  rw [hyp.card_H_eq, hyp.card_D_eq, hyp.card_QK_eq]; ring

/-- `[H : V] = |QK|`. -/
theorem index_V_subgroupOf_eq_card_QK :
    (hyp.V.subgroupOf hyp.H).index = Nat.card ↥hyp.QK := by
  have hmul := (hyp.V.subgroupOf hyp.H).card_mul_index
  rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe
      (hyp.V_le_D.trans hyp.D_le_H)).toEquiv,
    hyp.card_H_eq_card_QK_mul_card_V] at hmul
  refine Nat.eq_of_mul_eq_mul_left (Nat.card_pos (α := ↥hyp.V)) ?_
  rw [hmul]; ring

end Hypothesis

namespace SecondCaseHypothesis

variable {G : Type uG} {Ω : Type uΩ} [Group G] [MulAction G Ω] [Finite G]
  (sc : SecondCaseHypothesis G Ω)

/-- `(|QK|, |V|) = 1` — the Hall property in the form used below. -/
theorem coprime_card_QK_V (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hQ1 : sc.toHypothesis.Q1 ≠ ⊥) :
    Nat.Coprime (Nat.card ↥sc.toHypothesis.QK) (Nat.card ↥sc.toHypothesis.V) := by
  have h := sc.coprime_card_QK_index ind hQ1
  rwa [sc.toHypothesis.index_QK_subgroupOf_eq_card_V] at h

/-- **`V` is a Hall `π′`-subgroup of `H`**, where `π` is the set of prime divisors
of `|QK|` — the book's implicit setup for step (6) ("`x` and `x^g` are conjugate in
`H` to elements of `V` by a theorem of Hall").

`|V|` is coprime to `|QK|`, and `[H : V] = |QK|`. -/
theorem isHallSubgroup_V_subgroupOf (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hQ1 : sc.toHypothesis.Q1 ≠ ⊥) :
    OddOrder.Isaacs.Ch03.IsHallSubgroup
      {p : ℕ | p ∉ (Nat.card ↥sc.toHypothesis.QK).primeFactors}
      (sc.toHypothesis.V.subgroupOf sc.toHypothesis.H) := by
  have hVcard : Nat.card ↥(sc.toHypothesis.V.subgroupOf sc.toHypothesis.H)
      = Nat.card ↥sc.toHypothesis.V :=
    Nat.card_congr (Subgroup.subgroupOfEquivOfLe
      (sc.toHypothesis.V_le_D.trans sc.toHypothesis.D_le_H)).toEquiv
  constructor
  · intro p hp
    rw [hVcard] at hp
    simp only [Set.mem_setOf_eq]
    intro hmem
    have hpV : p ∣ Nat.card ↥sc.toHypothesis.V := Nat.dvd_of_mem_primeFactors hp
    have hpQK : p ∣ Nat.card ↥sc.toHypothesis.QK := Nat.dvd_of_mem_primeFactors hmem
    have hprime : p.Prime := Nat.prime_of_mem_primeFactors hp
    exact hprime.one_lt.ne'
      (Nat.eq_one_of_dvd_coprimes (sc.coprime_card_QK_V ind hQ1) hpQK hpV)
  · intro p hp
    simp only [Set.mem_setOf_eq, not_not]
    rwa [sc.toHypothesis.index_V_subgroupOf_eq_card_QK] at hp

end SecondCaseHypothesis

namespace SecondCaseHypothesis

variable {G : Type uG} {Ω : Type uΩ} [Group G] [MulAction G Ω] [Finite G]
  (sc : SecondCaseHypothesis G Ω)

/-- **Peterfalvi Part II, Ch. III, Theorem C, step (6) core** (p. 115): every
`π′`-element of `H` is `H`-conjugate into `V` — the book's "`x` and `x^g` are
conjugate in `H` to elements of `V` **by a theorem of Hall**".

`H` is solvable (`isSolvable_H`) and `V` is a Hall `π′`-subgroup of `H`
(`isHallSubgroup_V_subgroupOf`), so Hall's **D**-theorem puts `⟨x⟩` inside some
Hall `π′`-subgroup and Hall's **C**-theorem conjugates that subgroup onto `V`. -/
theorem exists_conj_mem_V_of_piPrime (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hQ1 : sc.toHypothesis.Q1 ≠ ⊥) {x : ↥sc.toHypothesis.H}
    (hx : ∀ q ∈ (orderOf x).primeFactors,
      q ∉ (Nat.card ↥sc.toHypothesis.QK).primeFactors) :
    ∃ g : ↥sc.toHypothesis.H,
      g * x * g⁻¹ ∈ sc.toHypothesis.V.subgroupOf sc.toHypothesis.H := by
  classical
  have hU : ∀ q ∈ (Nat.card ↥(Subgroup.zpowers x)).primeFactors,
      q ∈ {p : ℕ | p ∉ (Nat.card ↥sc.toHypothesis.QK).primeFactors} := by
    intro q hq
    rw [Nat.card_zpowers] at hq
    exact hx q hq
  obtain ⟨W, hW, hUW⟩ := OddOrder.Isaacs.Ch03.hall_D
    (π := {p : ℕ | p ∉ (Nat.card ↥sc.toHypothesis.QK).primeFactors}) hU
  obtain ⟨g, hg⟩ := OddOrder.Isaacs.Ch03.hall_C hW
    (sc.isHallSubgroup_V_subgroupOf ind hQ1)
  refine ⟨g, ?_⟩
  rw [← hg]
  exact ⟨x, hUW (Subgroup.mem_zpowers x), rfl⟩

end SecondCaseHypothesis

namespace SecondCaseHypothesis

variable {G : Type uG} {Ω : Type uΩ} [Group G] [MulAction G Ω] [Finite G]
  (sc : SecondCaseHypothesis G Ω)

/-- **`QK` is a Hall `π`-subgroup of `H`**, `π` = the prime divisors of `|QK|`. -/
theorem isHallSubgroup_QK_subgroupOf (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hQ1 : sc.toHypothesis.Q1 ≠ ⊥) :
    OddOrder.Isaacs.Ch03.IsHallSubgroup
      {p : ℕ | p ∈ (Nat.card ↥sc.toHypothesis.QK).primeFactors}
      (sc.toHypothesis.QK.subgroupOf sc.toHypothesis.H) := by
  have hcard : Nat.card ↥(sc.toHypothesis.QK.subgroupOf sc.toHypothesis.H)
      = Nat.card ↥sc.toHypothesis.QK :=
    Nat.card_congr (Subgroup.subgroupOfEquivOfLe sc.toHypothesis.QK_le_H).toEquiv
  refine ⟨fun p hp => ?_, fun p hp => ?_⟩
  · rw [hcard] at hp; exact hp
  · rw [sc.toHypothesis.index_QK_subgroupOf_eq_card_V] at hp
    simp only [Set.mem_setOf_eq]
    intro hmem
    have hprime : p.Prime := Nat.prime_of_mem_primeFactors hp
    exact hprime.one_lt.ne'
      (Nat.eq_one_of_dvd_coprimes (sc.coprime_card_QK_V ind hQ1)
        (Nat.dvd_of_mem_primeFactors hmem) (Nat.dvd_of_mem_primeFactors hp))

/-- **Every `π`-element of `H` lies in `QK`** (`π` = prime divisors of `|QK|`) —
the book's "since the `π`-component of `x` is in `QK`" in step (6).

`QK` is a **normal** Hall `π`-subgroup, so Hall's D- and C-theorems put every
`π`-subgroup inside a conjugate of `QK`, which is `QK` itself. -/
theorem mem_QK_of_piElement (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hQ1 : sc.toHypothesis.Q1 ≠ ⊥) {x : ↥sc.toHypothesis.H}
    (hx : ∀ q ∈ (orderOf x).primeFactors,
      q ∈ (Nat.card ↥sc.toHypothesis.QK).primeFactors) :
    x ∈ sc.toHypothesis.QK.subgroupOf sc.toHypothesis.H := by
  classical
  have hU : ∀ q ∈ (Nat.card ↥(Subgroup.zpowers x)).primeFactors,
      q ∈ {p : ℕ | p ∈ (Nat.card ↥sc.toHypothesis.QK).primeFactors} := by
    intro q hq
    rw [Nat.card_zpowers] at hq
    exact hx q hq
  obtain ⟨W, hW, hUW⟩ := OddOrder.Isaacs.Ch03.hall_D
    (π := {p : ℕ | p ∈ (Nat.card ↥sc.toHypothesis.QK).primeFactors}) hU
  obtain ⟨g, hg⟩ := OddOrder.Isaacs.Ch03.hall_C hW
    (sc.isHallSubgroup_QK_subgroupOf ind hQ1)
  -- `g x g⁻¹ ∈ QK`, and `QK ⊴ H`, so `x ∈ QK`
  have hconj : g * x * g⁻¹ ∈ sc.toHypothesis.QK.subgroupOf sc.toHypothesis.H := by
    rw [← hg]
    exact ⟨x, hUW (Subgroup.mem_zpowers x), rfl⟩
  have := (sc.toHypothesis.QK_subgroupOf_H_normal).conj_mem _ hconj g⁻¹
  simpa [mul_assoc] using this

end SecondCaseHypothesis

namespace SecondCaseHypothesis

variable {G : Type uG} {Ω : Type uΩ} [Group G] [MulAction G Ω] [Finite G]
  (sc : SecondCaseHypothesis G Ω)

/-- **Peterfalvi Part II, Ch. III, Theorem C, step (6), first reduction** (p. 115):

> If `π` is the set of prime divisors of `|QK|` and `y` is the `π′`-component of
> `x`, then `λ(x) = λ(y)` … since the `π`-component of `x` is in `QK`.

Stated for **any** factorisation `x = a·b` with `a` a `π`-element (not just the
canonical one), which is what the conjugation step needs: conjugating a
factorisation gives a factorisation.

A degree-one character is multiplicative
(`IsIrreducibleCharacter.map_mul_of_apply_one_eq_one`), the `π`-factor lies in
`QK ⊆ Ker λ` (`mem_QK_of_piElement`), and `λ` is `1` there. -/
theorem apply_eq_of_piFactorization (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hQ1 : sc.toHypothesis.Q1 ≠ ⊥)
    {θ : ClassFunction ↥sc.toHypothesis.H ℂ} (hθ : IsIrreducibleCharacter θ)
    (hdeg : (θ : ↥sc.toHypothesis.H → ℂ) 1 = 1)
    (hker : ((sc.toHypothesis.QK.subgroupOf sc.toHypothesis.H :
      Subgroup ↥sc.toHypothesis.H) : Set ↥sc.toHypothesis.H) ⊆
        OddOrder.Peterfalvi.S03.characterKernel θ)
    {x a b : ↥sc.toHypothesis.H} (hab : a * b = x)
    (ha : ∀ q ∈ (orderOf a).primeFactors,
      q ∈ (Nat.card ↥sc.toHypothesis.QK).primeFactors) :
    (θ : ↥sc.toHypothesis.H → ℂ) x = (θ : ↥sc.toHypothesis.H → ℂ) b := by
  have haQK : a ∈ sc.toHypothesis.QK.subgroupOf sc.toHypothesis.H :=
    sc.mem_QK_of_piElement ind hQ1 ha
  have hθa : (θ : ↥sc.toHypothesis.H → ℂ) a = 1 := by
    have hmem := hker haQK
    rw [OddOrder.Peterfalvi.S03.characterKernel, Set.mem_setOf_eq] at hmem
    rw [hmem, OddOrder.Peterfalvi.S03.characterDegree, hdeg]
  rw [← hab, hθ.map_mul_of_apply_one_eq_one hdeg, hθa, one_mul]

/-- The canonical-decomposition corollary: `λ(x) = λ(y)` for a `π′`-element
`y ∈ ⟨x⟩`. -/
theorem exists_piPrime_apply_eq (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hQ1 : sc.toHypothesis.Q1 ≠ ⊥)
    {θ : ClassFunction ↥sc.toHypothesis.H ℂ} (hθ : IsIrreducibleCharacter θ)
    (hdeg : (θ : ↥sc.toHypothesis.H → ℂ) 1 = 1)
    (hker : ((sc.toHypothesis.QK.subgroupOf sc.toHypothesis.H :
      Subgroup ↥sc.toHypothesis.H) : Set ↥sc.toHypothesis.H) ⊆
        OddOrder.Peterfalvi.S03.characterKernel θ)
    (x : ↥sc.toHypothesis.H) :
    ∃ y : ↥sc.toHypothesis.H,
      (∀ q ∈ (orderOf y).primeFactors,
        q ∉ (Nat.card ↥sc.toHypothesis.QK).primeFactors) ∧
      y ∈ Subgroup.zpowers x ∧
      (θ : ↥sc.toHypothesis.H → ℂ) x = (θ : ↥sc.toHypothesis.H → ℂ) y := by
  classical
  obtain ⟨a, b, hab, _, ha, hb, _, hbz⟩ :=
    OddOrder.GroupTheory.exists_isPiElement_mul
      ((Nat.card ↥sc.toHypothesis.QK).primeFactors : Set ℕ) x
  exact ⟨b, hb, hbz, sc.apply_eq_of_piFactorization ind hQ1 hθ hdeg hker hab ha⟩

end SecondCaseHypothesis

namespace SecondCaseHypothesis

variable {G : Type uG} {Ω : Type uΩ} [Group G] [MulAction G Ω] [Finite G]
  (sc : SecondCaseHypothesis G Ω)

/-- **Peterfalvi Part II, Ch. III, Theorem C, step (6), core** (p. 115):

> Therefore `x` and `x^g` are conjugate in `H` to elements of `V` by a theorem of
> Hall, and we may assume that `x ∈ V` and `x^g ∈ V`.  By Chapter I, §3, Lemma 2,
> `x` and `x^g` are conjugate in `V`.

Two `π′`-elements of `H` that are conjugate **in `G`** take the same value under
**every** class function on `H`: Hall's theorems move both into `V`
(`exists_conj_mem_V_of_piPrime`), and Ch. I §3 Lemma 2
(`exists_mem_V_conj_image_eq`) turns the `G`-conjugacy of two subsets of `V` into
`V`-conjugacy, which lies inside `H`. -/
theorem apply_eq_of_isConj_piPrime (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hQ1 : sc.toHypothesis.Q1 ≠ ⊥) (θ : ClassFunction ↥sc.toHypothesis.H ℂ)
    {x y : ↥sc.toHypothesis.H}
    (hx : ∀ q ∈ (orderOf x).primeFactors,
      q ∉ (Nat.card ↥sc.toHypothesis.QK).primeFactors)
    (hy : ∀ q ∈ (orderOf y).primeFactors,
      q ∉ (Nat.card ↥sc.toHypothesis.QK).primeFactors)
    {g : G} (hconj : g * (x : G) * g⁻¹ = (y : G)) :
    θ x = θ y := by
  classical
  obtain ⟨h₁, hh₁⟩ := sc.exists_conj_mem_V_of_piPrime ind hQ1 hx
  obtain ⟨h₂, hh₂⟩ := sc.exists_conj_mem_V_of_piPrime ind hQ1 hy
  set x' : ↥sc.toHypothesis.H := h₁ * x * h₁⁻¹ with hx'def
  set y' : ↥sc.toHypothesis.H := h₂ * y * h₂⁻¹ with hy'def
  have hx'V : (x' : G) ∈ sc.toHypothesis.V := Subgroup.mem_subgroupOf.mp hh₁
  have hy'V : (y' : G) ∈ sc.toHypothesis.V := Subgroup.mem_subgroupOf.mp hh₂
  -- `x'` and `y'` are conjugate in `G`, by `(h₂ : G) * g * (h₁ : G)⁻¹`
  have hGconj : ((h₂ : G) * g * (h₁ : G)⁻¹) * (x' : G) * ((h₂ : G) * g * (h₁ : G)⁻¹)⁻¹
      = (y' : G) := by
    have hxv : (x' : G) = (h₁ : G) * (x : G) * (h₁ : G)⁻¹ := rfl
    have hyv : (y' : G) = (h₂ : G) * (y : G) * (h₂ : G)⁻¹ := rfl
    rw [hxv, hyv, ← hconj]
    group
  -- Ch. I §3 Lemma 2 on the singletons `{x'}`, `{y'}`
  obtain ⟨v, hvV, hveq⟩ := sc.toHypothesis.exists_mem_V_conj_image_eq
    (X := {(x' : G)}) (Y := {(y' : G)})
    (by simpa using hx'V) (by simpa using hy'V)
    ⟨(h₂ : G) * g * (h₁ : G)⁻¹, by
      simp only [Set.image_singleton, MulEquiv.coe_toMonoidHom, MulAut.conj_apply]
      rw [hGconj]⟩
  have hvH : v ∈ sc.toHypothesis.H :=
    sc.toHypothesis.D_le_H (sc.toHypothesis.V_le_D hvV)
  have hvx : v * (x' : G) * v⁻¹ = (y' : G) := by
    have := hveq
    simp only [Set.image_singleton, MulEquiv.coe_toMonoidHom, MulAut.conj_apply] at this
    exact Set.singleton_eq_singleton_iff.mp this
  have hxy' : (⟨v, hvH⟩ : ↥sc.toHypothesis.H) * x' * (⟨v, hvH⟩ : ↥sc.toHypothesis.H)⁻¹ = y' :=
    Subtype.ext hvx
  calc θ x = θ x' := (ClassFunction.conj_eq θ x h₁).symm
    _ = θ y' := by rw [← hxy']; exact (ClassFunction.conj_eq θ x' ⟨v, hvH⟩).symm
    _ = θ y := ClassFunction.conj_eq θ y h₂

end SecondCaseHypothesis

namespace SecondCaseHypothesis

variable {G : Type uG} {Ω : Type uΩ} [Group G] [MulAction G Ω] [Finite G]
  (sc : SecondCaseHypothesis G Ω)

/-- **Peterfalvi Part II, Ch. III, Theorem C, step (6)** (p. 115): "if `x ∈ H`,
`g ∈ G` and `x^g ∈ H`, then `λ(x^g) = λ(x)`."

Decompose `x = a·b` with `a` a `π`-element and `b` a `π′`-element, both powers of
`x` (`exists_isPiElement_mul`).  Conjugating by `g` carries this to a
factorisation of `y` with the same order profile, so both values collapse to the
`π′`-factors (`apply_eq_of_piFactorization`); those are `G`-conjugate
`π′`-elements of `H`, hence equal under `θ` by the core
(`apply_eq_of_isConj_piPrime`). -/
theorem apply_eq_of_isConj (ind : Hypothesis.TheoremAInductionBelow G Ω)
    (hQ1 : sc.toHypothesis.Q1 ≠ ⊥)
    {θ : ClassFunction ↥sc.toHypothesis.H ℂ} (hθ : IsIrreducibleCharacter θ)
    (hdeg : (θ : ↥sc.toHypothesis.H → ℂ) 1 = 1)
    (hker : ((sc.toHypothesis.QK.subgroupOf sc.toHypothesis.H :
      Subgroup ↥sc.toHypothesis.H) : Set ↥sc.toHypothesis.H) ⊆
        OddOrder.Peterfalvi.S03.characterKernel θ)
    {x y : ↥sc.toHypothesis.H} {g : G}
    (hconj : g * (x : G) * g⁻¹ = (y : G)) :
    (θ : ↥sc.toHypothesis.H → ℂ) x = (θ : ↥sc.toHypothesis.H → ℂ) y := by
  classical
  obtain ⟨a, b, hab, -, ha, hb, haz, hbz⟩ :=
    OddOrder.GroupTheory.exists_isPiElement_mul
      ((Nat.card ↥sc.toHypothesis.QK).primeFactors : Set ℕ) x
  obtain ⟨m, hm₀⟩ := haz
  obtain ⟨n, hn₀⟩ := hbz
  have hm : x ^ m = a := hm₀
  have hn : x ^ n = b := hn₀
  -- conjugation preserves the order profile of the two factors
  have hordm : orderOf (y ^ m) = orderOf a := by
    rw [← hm, ← Subgroup.orderOf_coe (y ^ m), ← Subgroup.orderOf_coe (x ^ m)]
    push_cast
    rw [← hconj, conj_zpow]
    have h := orderOf_injective (MulAut.conj g).toMonoidHom
      (MulAut.conj g).injective ((x : G) ^ m)
    simpa [MulAut.conj_apply] using h
  have hordn : orderOf (y ^ n) = orderOf b := by
    rw [← hn, ← Subgroup.orderOf_coe (y ^ n), ← Subgroup.orderOf_coe (x ^ n)]
    push_cast
    rw [← hconj, conj_zpow]
    have h := orderOf_injective (MulAut.conj g).toMonoidHom
      (MulAut.conj g).injective ((x : G) ^ n)
    simpa [MulAut.conj_apply] using h
  -- the conjugated factorisation of `y`
  have hab' : y ^ m * y ^ n = y := by
    have hx : x ^ (m + n) = x := by rw [zpow_add, hm, hn, hab]
    have hxG : (x : G) ^ (m + n) = (x : G) := by
      have h := congrArg (fun z : ↥sc.toHypothesis.H => (z : G)) hx
      push_cast at h
      exact h
    apply Subtype.ext
    push_cast
    rw [← zpow_add, ← hconj, conj_zpow, hxG]
  have ha' : ∀ q ∈ (orderOf (y ^ m)).primeFactors,
      q ∈ (Nat.card ↥sc.toHypothesis.QK).primeFactors := by
    rw [hordm]; exact ha
  have hb' : ∀ q ∈ (orderOf (y ^ n)).primeFactors,
      q ∉ (Nat.card ↥sc.toHypothesis.QK).primeFactors := by
    rw [hordn]; exact hb
  -- the `π′`-factors are conjugate in `G`
  have hbconj : g * (b : G) * g⁻¹ = ((y ^ n : ↥sc.toHypothesis.H) : G) := by
    rw [← hn]
    push_cast
    rw [← hconj, conj_zpow]
  calc (θ : ↥sc.toHypothesis.H → ℂ) x
      = (θ : ↥sc.toHypothesis.H → ℂ) b :=
        sc.apply_eq_of_piFactorization ind hQ1 hθ hdeg hker hab ha
    _ = (θ : ↥sc.toHypothesis.H → ℂ) (y ^ n) :=
        sc.apply_eq_of_isConj_piPrime ind hQ1 θ hb hb' hbconj
    _ = (θ : ↥sc.toHypothesis.H → ℂ) y :=
        (sc.apply_eq_of_piFactorization ind hQ1 hθ hdeg hker hab' ha').symm

end SecondCaseHypothesis

end OddOrder.Peterfalvi.Appendices.Suzuki
