/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Higman.Suzuki2Groups.HigmanLemmaThirteen.FrattiniMiddleSupport

/-!
# Higman's Lemma 13: diagonal support of middle Frattini commutators

G. Higman, “Suzuki 2-groups,” *Illinois Journal of Mathematics* 7 (1963),
Lemma 13, p. 92.

This file first records the linear-algebra fact that a bilinear map which
vanishes away from a prescribed set of generator pairs maps the generated
submodules onto the span of its supported generator values.  Applied to two
type-B Frobenius eigenfamilies and the middle Frattini commutator, Higman's
weight calculation restricts that support to the diagonal.
-/

set_option autoImplicit false

namespace OddOrder.Higman.Suzuki2Groups

open OddOrder.GroupTheory
open OddOrder.GroupTheory.Suzuki2Group
open OddOrder.Isaacs.Ch03
open scoped IsMulCommutative TensorProduct

universe uR uM uN uW uI uJ uP

/-- If a bilinear map vanishes away from a prescribed set of index pairs,
then its image on the two generated submodules is exactly the span of the
supported generator values. -/
theorem bilinearMap_map₂_span_range_eq_span_support
    {R : Type uR} {M : Type uM} {N : Type uN} {W : Type uW}
    [CommSemiring R]
    [AddCommMonoid M] [Module R M]
    [AddCommMonoid N] [Module R N]
    [AddCommMonoid W] [Module R W]
    (beta : M →ₗ[R] N →ₗ[R] W)
    {I : Type uI} {J : Type uJ} (f : I → M) (g : J → N)
    (support : Set (I × J))
    (hoff : ∀ i j, (i, j) ∉ support → beta (f i) (g j) = 0) :
    Submodule.map₂ beta
        (Submodule.span R (Set.range f))
        (Submodule.span R (Set.range g)) =
      Submodule.span R
        ((fun ij : I × J ↦ beta (f ij.1) (g ij.2)) '' support) := by
  classical
  rw [Submodule.map₂_span_span]
  apply le_antisymm
  · apply Submodule.span_le.2
    rintro z ⟨_, ⟨i, rfl⟩, _, ⟨j, rfl⟩, rfl⟩
    by_cases hij : (i, j) ∈ support
    · exact Submodule.subset_span ⟨(i, j), hij, rfl⟩
    · change beta (f i) (g j) ∈ _
      rw [hoff i j hij]
      exact Submodule.zero_mem _
  · apply Submodule.span_le.2
    rintro z ⟨⟨i, j⟩, hij, rfl⟩
    exact Submodule.subset_span
      ⟨f i, ⟨i, rfl⟩, g j, ⟨j, rfl⟩, rfl⟩

local instance frattiniMiddleDiagonalSupportLayerIsMulCommutative
    (P : Type uP) [Group P] (i : Nat) :
    IsMulCommutative (lowerCentralLayer P i) :=
  lowerCentralLayerIsMulCommutative P i

noncomputable local instance frattiniMiddleDiagonalSupportLayerZModTwoModule
    (P : Type uP) [Group P] (i : Nat) :
    Module (ZMod 2) (Additive (lowerCentralLayer P i)) :=
  lowerCentralLayerZmodModule P i

/-- **Higman Lemma 13 (p. 92), B/B diagonal support.**

The middle Frattini bracket of two Frobenius eigenfamilies of the canonical
type-B weight is generated by the same-index brackets. -/
theorem
    frattiniMiddleCommutatorBilinearBaseChange_map₂_span_range_eq_span_diagonal
    {P : Type uP} [Group P] [Finite P]
    {Y : Subgroup (MulAut P)}
    (hP : IsPGroup 2 P)
    (hxi : IsXiActor Y)
    (hPhiComm : IsMulCommutative (frattini P))
    (hfour : ∀ z : frattini P, z ^ 4 = 1)
    (hexists : ∃ z : frattini P, z ^ 2 ≠ 1)
    {n : Nat} (hn : 2 ≤ n) (c : Y)
    (eSquare :
      let hSquareEA :=
        frattiniSquare_isElementaryAbelian_of_exponent_four hPhiComm hfour
      letI : IsMulCommutative (frattiniSquare P) :=
        IsMulCommutative.of_comm hSquareEA.comm
      letI : Module (ZMod 2) (Additive (frattiniSquare P)) :=
        hSquareEA.zmodModule
      Additive (frattiniSquare P) ≃ₗ[ZMod 2] GaloisField 2 n)
    (nu : GaloisField 2 n)
    (hnuPrimitive : IsPrimitiveRoot nu (2 ^ n - 1))
    (hconj :
      let hSquareInv : IsAInvariant Y.subtype (frattiniSquare P) :=
        (frattiniSquareNormalInvariant Y.subtype).2.2
      let hSquareEA :=
        frattiniSquare_isElementaryAbelian_of_exponent_four hPhiComm hfour
      letI : IsMulCommutative (frattiniSquare P) :=
        IsMulCommutative.of_comm hSquareEA.comm
      letI : Module (ZMod 2) (Additive (frattiniSquare P)) :=
        hSquareEA.zmodModule
      eSquare.conj (elabRepresentation 2 hSquareInv.restrict c) =
        Algebra.lmul (ZMod 2) (GaloisField 2 n) nu)
    (f g : Fin (Module.finrank (ZMod 2) (GaloisField 2 n)) →
      GaloisField 2 n ⊗[ZMod 2] Additive (lowerCentralLayer P 0))
    (hf : ∀ i, (lowerCentralLayerRepresentation Y.subtype 0 c).baseChange
        (GaloisField 2 n) (f i) =
      ((frobeniusEquiv (GaloisField 2 n) 2).symm nu) ^
        (2 ^ i.val) • f i)
    (hg : ∀ i, (lowerCentralLayerRepresentation Y.subtype 0 c).baseChange
        (GaloisField 2 n) (g i) =
      ((frobeniusEquiv (GaloisField 2 n) 2).symm nu) ^
        (2 ^ i.val) • g i) :
    letI : CommGroup (frattini P) :=
      { (inferInstance : Group (frattini P)) with
        mul_comm := hPhiComm.is_comm.comm }
    Submodule.map₂
        (frattiniMiddleCommutatorBilinearBaseChange (GaloisField 2 n)
          hP hxi hPhiComm hexists)
        (Submodule.span (GaloisField 2 n) (Set.range f))
        (Submodule.span (GaloisField 2 n) (Set.range g)) =
      Submodule.span (GaloisField 2 n)
        (Set.range fun i ↦
          frattiniMiddleCommutatorBilinearBaseChange (GaloisField 2 n)
            hP hxi hPhiComm hexists (f i) (g i)) := by
  classical
  let : CommGroup (frattini P) :=
    { (inferInstance : Group (frattini P)) with
      mul_comm := hPhiComm.is_comm.comm }
  let beta := frattiniMiddleCommutatorBilinearBaseChange
    (GaloisField 2 n) hP hxi hPhiComm hexists
  let diagonal : Set
      (Fin (Module.finrank (ZMod 2) (GaloisField 2 n)) ×
        Fin (Module.finrank (ZMod 2) (GaloisField 2 n))) :=
    Set.range fun i ↦ (i, i)
  have hoff : ∀ i j, (i, j) ∉ diagonal → beta (f i) (g j) = 0 := by
    intro i j hij
    apply frattiniMiddleCommutatorBilinearBaseChange_eq_zero_of_ne
      hP hxi hPhiComm hfour hexists hn c eSquare nu hnuPrimitive hconj
      i j (f i) (g j) (hf i) (hg j)
    intro h
    apply hij
    exact ⟨i, by simp [h]⟩
  change Submodule.map₂ beta
      (Submodule.span (GaloisField 2 n) (Set.range f))
      (Submodule.span (GaloisField 2 n) (Set.range g)) = _
  rw [bilinearMap_map₂_span_range_eq_span_support
    beta f g diagonal hoff]
  apply congrArg (Submodule.span (GaloisField 2 n))
  ext z
  constructor
  · rintro ⟨_, ⟨k, rfl⟩, rfl⟩
    exact ⟨k, rfl⟩
  · rintro ⟨i, rfl⟩
    exact ⟨(i, i), ⟨i, rfl⟩, rfl⟩

end OddOrder.Higman.Suzuki2Groups
