/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.GroupTheory.BrauerSuzukiCounting
import OddOrder.GroupTheory.RepresentationTheory.InflationCharacter
import OddOrder.Peterfalvi.S13_MaximalIII_IVBasic
import OddOrder.Isaacs.Ch03_SplitExtensions.Theorem315

/-!
# Brauer–Suzuki: the group-theoretic endgame (Gorenstein Ch. 12, pp. 376–377)

**Gorenstein, *Finite Groups*, Ch. 12, Theorem 1.1** (final steps): from the non-linear
irreducible character `χ` whose kernel contains every involution (`lem_1_9`), one shows that the
subgroup `M = ⟨involutions⟩` (normal in `G`) has cyclic Sylow `2`-subgroup `Q = S ∩ M`, whence a
Burnside normal `2`-complement argument gives `Z(G/O_{2'}(G))` of order `2`, equivalently
`G = O_{2'}(G)·C_G(u)` for the central involution `u`.

This file assembles the endgame.  It opens with the normal subgroup generated by involutions.
-/

open OddOrder.RepresentationTheory OddOrder.Isaacs.Ch03

open scoped Pointwise

namespace OddOrder.GroupTheory

variable {G : Type*} [Group G]

/-- **The subgroup generated by all involutions of `G`** (Gorenstein's `M`).  Since the set of
involutions `{u | orderOf u = 2}` is invariant under conjugation, its generated subgroup is
normal. -/
def involutionClosure (G : Type*) [Group G] : Subgroup G :=
  Subgroup.closure {u : G | orderOf u = 2}

theorem mem_involutionClosure_of_orderOf_eq_two {u : G} (hu : orderOf u = 2) :
    u ∈ involutionClosure G :=
  Subgroup.subset_closure hu

/-- **`M = ⟨involutions⟩` is normal in `G`.**  Conjugation preserves order, so the involution set
is conjugation-invariant and its closure is normalized by all of `G`. -/
instance involutionClosure_normal : (involutionClosure G).Normal := by
  rw [involutionClosure, ← Subgroup.normalizer_eq_top_iff]
  refine top_unique ?_
  rw [Subgroup.le_normalizer_closure_iff]
  rintro g _ u (hu : orderOf u = 2)
  refine Subgroup.subset_closure (show orderOf (g * u * g⁻¹) = 2 from ?_)
  rw [← orderOf_eq_of_isConj (isConj_iff.mpr ⟨g, rfl⟩)]
  exact hu

/-- **In a finite cyclic group an element of order `2` is unique.**  Used to show the image of the
central involution in `Ḡ = G / O_{2'}(G)` is central: the (normal, cyclic) image of `M` has a
unique involution, so conjugation fixes it. -/
theorem eq_of_sq_eq_one_of_isCyclic {C : Type*} [Group C] [Finite C] [IsCyclic C]
    {a b : C} (ha : a ^ 2 = 1) (ha1 : a ≠ 1) (hb : b ^ 2 = 1) (hb1 : b ≠ 1) : a = b := by
  classical
  letI := Fintype.ofFinite C
  by_contra hab
  have hcard : ({1, a, b} : Finset C).card = 3 := by
    rw [Finset.card_insert_of_notMem (by
        simp only [Finset.mem_insert, Finset.mem_singleton, not_or]
        exact ⟨fun h => ha1 h.symm, fun h => hb1 h.symm⟩),
      Finset.card_insert_of_notMem (Finset.notMem_singleton.mpr hab), Finset.card_singleton]
  have h3 : ({1, a, b} : Finset C) ⊆ Finset.filter (fun x : C => x ^ 2 = 1) Finset.univ := by
    intro x hx
    rw [Finset.mem_filter]
    refine ⟨Finset.mem_univ x, ?_⟩
    simp only [Finset.mem_insert, Finset.mem_singleton] at hx
    rcases hx with rfl | rfl | rfl
    · simp
    · exact ha
    · exact hb
  have hle := IsCyclic.card_pow_eq_one_le (α := C) (two_pos)
  have hchain := (Finset.card_le_card h3).trans hle
  omega

/-- **Burnside's normal `2`-complement for a cyclic Sylow `2`-subgroup at the smallest prime.**
If a finite group `H` of even order has a cyclic Sylow `2`-subgroup `P`, then `H` has a normal
`2`-complement `L` consisting *exactly* of the odd-order elements, complementing `P` (Gorenstein
Theorem 7.6.1 via Burnside transfer, `IsCyclic.isComplement'`).  The odd-order characterization is
what makes `L` characteristic (invariant under every automorphism), used to descend to a normal
subgroup of an overgroup. -/
theorem exists_oddComplement_of_isCyclic_sylowTwo {H : Type*} [Group H] [Finite H]
    (P : Sylow 2 H) (hcyc : IsCyclic (P : Subgroup H)) (hev : 2 ∣ Nat.card H) :
    ∃ L : Subgroup H, L.Normal ∧ ¬ 2 ∣ Nat.card L ∧ (∀ h : H, h ∈ L ↔ Odd (orderOf h)) ∧
      L ⊔ (P : Subgroup H) = ⊤ := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  have hH1 : Nat.card H ≠ 1 := fun h => by rw [h] at hev; norm_num at hev
  have hmin : (Nat.card H).minFac = 2 :=
    le_antisymm (Nat.minFac_le_of_dvd le_rfl hev) (Nat.minFac_prime hH1).two_le
  have hcompl := IsCyclic.isComplement' hmin hcyc
  set L := (MonoidHom.transferSylow P (hcyc.normalizer_le_centralizer hmin)).ker with hL
  have hLcard : Nat.card L = (P : Subgroup H).index := hcompl.index_eq_card.symm
  have hLodd : ¬ 2 ∣ Nat.card L := by rw [hLcard]; exact P.not_dvd_index
  refine ⟨L, inferInstance, hLodd, ?_, hcompl.sup_eq_top⟩
  intro c
  constructor
  · intro hc
    have h1 : orderOf c = orderOf (⟨c, hc⟩ : L) :=
      orderOf_injective L.subtype L.subtype_injective ⟨c, hc⟩
    have hdvd : orderOf c ∣ Nat.card L := by rw [h1]; exact orderOf_dvd_natCard _
    rcases Nat.even_or_odd (orderOf c) with he | ho
    · exact absurd (he.two_dvd.trans hdvd) hLodd
    · exact ho
  · intro hodd
    obtain ⟨m, hm⟩ := P.isPGroup'.exists_card_eq
    have h2 : orderOf ((QuotientGroup.mk' L) c) ∣ orderOf c := orderOf_map_dvd _ c
    have hLidx : L.index = Nat.card (P : Subgroup H) := hcompl.symm.index_eq_card
    have h3 : orderOf ((QuotientGroup.mk' L) c) ∣ 2 ^ m := by
      have hdvd := orderOf_dvd_natCard ((QuotientGroup.mk' L) c)
      rwa [show Nat.card (H ⧸ L) = 2 ^ m from by rw [← hm, ← hLidx]; rfl] at hdvd
    obtain ⟨j, _, hj⟩ := (Nat.dvd_prime_pow Nat.prime_two).mp h3
    have hj0 : j = 0 := by
      by_contra h
      have h2div : (2 : ℕ) ∣ orderOf c := (hj ▸ dvd_pow_self 2 h).trans h2
      have hmod := Nat.odd_iff.mp hodd
      omega
    have hone : orderOf ((QuotientGroup.mk' L) c) = 1 := by rw [hj, hj0, pow_zero]
    exact (QuotientGroup.eq_one_iff c).mp (orderOf_eq_one_iff.mp hone)

variable [Finite G] (Q : QuaternionSylowSetup G)

namespace QuaternionSylowSetup

/-- `G₁ = S·M`, the subgroup generated by the Sylow `2`-subgroup `S` and the involution
subgroup `M = ⟨involutions⟩`.  Since `S ≤ G₁` and `S` is a Sylow `2`-subgroup of `G` (a fortiori
of `G₁`), `G₁` again satisfies the `QuaternionSylowSetup` hypotheses (`smSetup`). -/
def SM : Subgroup G := (Q.S : Subgroup G) ⊔ involutionClosure G

theorem S_le_SM : (Q.S : Subgroup G) ≤ Q.SM := le_sup_left

theorem x_mem_SM : Q.x ∈ Q.SM := Q.S_le_SM Q.hxS
theorem y_mem_SM : Q.y ∈ Q.SM := Q.S_le_SM Q.hyS

/-- **`G₁ = SM` again has generalized quaternion Sylow `2`-subgroup `S`**: the
`QuaternionSylowSetup` transported to `↥(SM)` via `Sylow.subtype`, with generators `x, y`
lifted from `S ≤ SM`.  This lets `lem_1_9` (and the whole character theory) apply to `SM`. -/
noncomputable def smSetup : QuaternionSylowSetup ↥Q.SM where
  n := Q.n
  hn := Q.hn
  S := Q.S.subtype Q.S_le_SM
  x := ⟨Q.x, Q.x_mem_SM⟩
  y := ⟨Q.y, Q.y_mem_SM⟩
  hxS := by rw [Sylow.coe_subtype, Subgroup.mem_subgroupOf]; exact Q.hxS
  hyS := by rw [Sylow.coe_subtype, Subgroup.mem_subgroupOf]; exact Q.hyS
  hx_order := by rw [Subgroup.orderOf_mk]; exact Q.hx_order
  hy_sq := Subtype.ext (by push_cast; exact Q.hy_sq)
  hconj := Subtype.ext (by push_cast; exact Q.hconj)
  hclosure := by
    refine Subgroup.map_injective (f := Q.SM.subtype) Subtype.coe_injective ?_
    rw [MonoidHom.map_closure, Sylow.coe_subtype, Subgroup.subgroupOf,
      Subgroup.map_comap_eq, Subgroup.range_subtype, inf_of_le_right Q.S_le_SM,
      show Q.SM.subtype '' {(⟨Q.x, Q.x_mem_SM⟩ : ↥Q.SM), ⟨Q.y, Q.y_mem_SM⟩} = {Q.x, Q.y} from by
        rw [Set.image_pair]; rfl,
      Q.hclosure]

/-- **`SM/M` is not abelian** (Gorenstein Ch.12, the `Q`-cyclic contradiction).  By `lem_1_9`
applied to `G₁ = SM` (`smSetup`), `SM` has a *non-linear* irreducible character `φ` (`φ(1) ≥ 2`)
whose kernel contains every involution, hence all of `M = ⟨involutions⟩`.  If `SM/M` were
abelian, `apply_one_eq_one_of_subset_characterKernel_of_isMulCommutative_quotient` would force
`φ(1) = 1` — a contradiction. -/
theorem not_isMulCommutative_SM_quotient_M :
    ¬ IsMulCommutative (↥Q.SM ⧸ (involutionClosure G).subgroupOf Q.SM) := by
  intro habelian
  haveI : Invertible (Nat.card ↥Q.SM : ℂ) :=
    invertibleOfNonzero (by exact_mod_cast Nat.card_pos.ne')
  haveI : Invertible (Nat.card ↥Q.smSetup.N : ℂ) :=
    invertibleOfNonzero (by exact_mod_cast Nat.card_pos.ne')
  haveI : Invertible (Nat.card ↥(Q.smSetup.C.subgroupOf Q.smSetup.N) : ℂ) :=
    invertibleOfNonzero (by exact_mod_cast Nat.card_pos.ne')
  obtain ⟨φ, ⟨d, hd2, hφd⟩, hφinv⟩ := Q.smSetup.lem_1_9
  have hφchar : IsCharacter (φ : ClassFunction ↥Q.SM ℂ) := φ.2.isCharacter
  have hInvLeSM : involutionClosure G ≤ Q.SM := le_sup_right
  -- every element of `M.subgroupOf SM` lies in the character kernel of `φ`
  have hsub : (involutionClosure G).subgroupOf Q.SM ≤
      OddOrder.Peterfalvi.S13.characterKernelSubgroup hφchar := by
    rw [← Subgroup.map_le_map_iff_of_injective (f := Q.SM.subtype) Subtype.coe_injective,
      Subgroup.subgroupOf_map_subtype, inf_of_le_left hInvLeSM, involutionClosure,
      Subgroup.closure_le]
    rintro u (hu : orderOf u = 2)
    have huSM : u ∈ Q.SM := hInvLeSM (mem_involutionClosure_of_orderOf_eq_two hu)
    refine ⟨⟨u, huSM⟩, ?_, rfl⟩
    rw [SetLike.mem_coe, OddOrder.Peterfalvi.S13.mem_characterKernelSubgroup,
      OddOrder.Peterfalvi.S03.mem_characterKernel]
    exact hφinv ⟨u, huSM⟩ (by rw [Subgroup.orderOf_mk]; exact hu)
  have hMker : ((involutionClosure G).subgroupOf Q.SM : Set ↥Q.SM) ⊆
      OddOrder.Peterfalvi.S03.characterKernel (φ : ClassFunction ↥Q.SM ℂ) :=
    fun _ hg => (OddOrder.Peterfalvi.S13.mem_characterKernelSubgroup hφchar).mp (hsub hg)
  haveI := habelian
  have h1 := apply_one_eq_one_of_subset_characterKernel_of_isMulCommutative_quotient
    ((involutionClosure G).subgroupOf Q.SM) φ hMker
  rw [hφd] at h1
  have : d = 1 := by exact_mod_cast h1
  omega

/-- **`Q = S ∩ M` is cyclic** (Gorenstein Ch.12, p. 376).  Were `Q` non-cyclic, it would not lie
in the cyclic maximal subgroup `X = ⟨x⟩`, so it contains an element `xᵏ·y` of the coset `X·y`.
Conjugating by `x` (which normalizes `Q = S ∩ M`, as `M ⊴ G`) and dividing gives `x⁻² ∈ Q`, hence
`T = ⟨x²⟩ ≤ Q ≤ M`.  Since `S' = ⟨x²⟩ = T` (`comm_mem_T`), the quotient `S/Q` is abelian; by
Noether's second isomorphism theorem so is `SM/M`, contradicting
`not_isMulCommutative_SM_quotient_M`. -/
theorem SinfM_isCyclic :
    IsCyclic ↥((Q.S : Subgroup G) ⊓ involutionClosure G) := by
  by_contra hnc
  -- `Q ⊄ X`, so `Q` contains an element `xᵏ·y` of the coset `X·y`.
  have hnotle : ¬ ((Q.S : Subgroup G) ⊓ involutionClosure G ≤ Q.X) := by
    intro hle
    haveI : IsCyclic ↥Q.X := Subgroup.isCyclic_zpowers Q.x
    exact hnc (Subgroup.isCyclic_of_le hle)
  obtain ⟨q, hqQ, hqX⟩ := SetLike.not_le_iff_exists.mp hnotle
  obtain ⟨hqS, hqM⟩ := Subgroup.mem_inf.mp hqQ
  obtain ⟨k, rfl | rfl⟩ := Q.mem_iff.mp hqS
  · exact hqX (Q.mem_X_iff.mpr ⟨k, rfl⟩)
  -- `x·q·x⁻¹ ∈ Q` (`Q = S ∩ M` normal in `S`); dividing by `q` yields `x⁻² ∈ Q`.
  · have hxq : Q.x * (Q.x ^ k * Q.y) * Q.x⁻¹ ∈ (Q.S : Subgroup G) ⊓ involutionClosure G :=
      Subgroup.mem_inf.mpr ⟨mul_mem (mul_mem Q.hxS hqS) (inv_mem Q.hxS),
        involutionClosure_normal.conj_mem _ hqM Q.x⟩
    have hxinv2 : Q.x ^ (-2 : ℤ) ∈ (Q.S : Subgroup G) ⊓ involutionClosure G := by
      have hmul := mul_mem (inv_mem hqQ) hxq
      rwa [show (Q.x ^ k * Q.y)⁻¹ * (Q.x * (Q.x ^ k * Q.y) * Q.x⁻¹) = Q.x ^ (-2 : ℤ) from by
        calc (Q.x ^ k * Q.y)⁻¹ * (Q.x * (Q.x ^ k * Q.y) * Q.x⁻¹)
            = Q.y⁻¹ * Q.x ^ (1 : ℤ) * Q.y * Q.x⁻¹ := by group
          _ = Q.x ^ (-1 : ℤ) * Q.x⁻¹ := by rw [Q.conj_inv_x_zpow 1]
          _ = Q.x ^ (-2 : ℤ) := by group] at hmul
    -- so `x² ∈ Q`, hence `T = ⟨x²⟩ ≤ Q ≤ M`.
    have hx2 : Q.x ^ (2 : ℕ) ∈ (Q.S : Subgroup G) ⊓ involutionClosure G := by
      have h := inv_mem hxinv2
      rwa [zpow_neg, inv_inv, zpow_two, ← pow_two] at h
    have hTM : Q.T ≤ involutionClosure G :=
      (le_trans (by rw [QuaternionSylowSetup.T, Subgroup.zpowers_le]; exact hx2) inf_le_right)
    -- `commutator ↥S ≤ M.subgroupOf S` since `S' = T ≤ M`, so `S/Q` is abelian.
    haveI hab : IsMulCommutative
        (↥(Q.S : Subgroup G) ⧸ (involutionClosure G).subgroupOf (Q.S : Subgroup G)) := by
      rw [Subgroup.Normal.quotient_commutative_iff_commutator_le, commutator_eq_closure,
        Subgroup.closure_le]
      rintro _ ⟨a, b, rfl⟩
      rw [SetLike.mem_coe, Subgroup.mem_subgroupOf, commutatorElement_def]
      push_cast
      exact hTM (Q.comm_mem_T a.2 b.2)
    -- Transfer along Noether II: `SM/M ≅ S/Q` is abelian, contradiction.
    refine absurd ?_ Q.not_isMulCommutative_SM_quotient_M
    change IsMulCommutative (↥((Q.S : Subgroup G) ⊔ involutionClosure G) ⧸
      (involutionClosure G).subgroupOf ((Q.S : Subgroup G) ⊔ involutionClosure G))
    rw [isMulCommutative_iff]
    intro a b
    apply (QuotientGroup.quotientInfEquivProdNormalQuotient
      (Q.S : Subgroup G) (involutionClosure G)).symm.injective
    rw [map_mul, map_mul, mul_comm']

/-! ### The normal `2`-complement of `M` and the odd core (Gorenstein Ch.12, p. 376) -/

/-- The central involution `z` lies in `Q = S ∩ M`. -/
theorem z_mem_SinfM : Q.z ∈ (Q.S : Subgroup G) ⊓ involutionClosure G :=
  Subgroup.mem_inf.mpr ⟨pow_mem Q.hxS _, mem_involutionClosure_of_orderOf_eq_two Q.orderOf_z⟩

/-- **The image of any Sylow `2`-subgroup of `M` lies in a `G`-conjugate of `Q = S ∩ M`.**  A Sylow
`2`-subgroup `Pₘ` of `M`, pushed into `G`, is a `2`-subgroup contained in some Sylow `2`-subgroup
`T = g·S` of `G`; since `M ⊴ G`, it lands in `T ⊓ M = g·(S ⊓ M)`. -/
theorem sylowTwoM_map_le_conj_SinfM (PM : Sylow 2 ↥(involutionClosure G)) :
    ∃ g : G, ((PM : Subgroup ↥(involutionClosure G)).map (involutionClosure G).subtype)
      ≤ MulAut.conj g • ((Q.S : Subgroup G) ⊓ involutionClosure G) := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  haveI : (involutionClosure G).Normal := involutionClosure_normal
  have hRpg : IsPGroup 2
      ((PM : Subgroup ↥(involutionClosure G)).map (involutionClosure G).subtype) :=
    PM.isPGroup'.map (involutionClosure G).subtype
  obtain ⟨T, hRT⟩ := hRpg.exists_le_sylow
  obtain ⟨g, hg⟩ := MulAction.exists_smul_eq G Q.S T
  refine ⟨g, ?_⟩
  rw [Subgroup.smul_inf]
  refine le_inf ?_ ?_
  · rw [← Sylow.coe_subgroup_smul, hg]; exact hRT
  · rw [Subgroup.Normal.conj_smul_eq_self g (involutionClosure G)]
    exact Subgroup.map_subtype_le _

include Q in
/-- **Every Sylow `2`-subgroup of `M = ⟨involutions⟩` is cyclic** (because `Q = S ∩ M` is cyclic,
`SinfM_isCyclic`).  This makes `M` `2`-nilpotent, so `M` has a normal `2`-complement. -/
theorem sylowTwoM_isCyclic (PM : Sylow 2 ↥(involutionClosure G)) :
    IsCyclic (PM : Subgroup ↥(involutionClosure G)) := by
  obtain ⟨g, hle⟩ := Q.sylowTwoM_map_le_conj_SinfM PM
  haveI hconjcyc : IsCyclic ↥(MulAut.conj g • ((Q.S : Subgroup G) ⊓ involutionClosure G)) := by
    haveI := Q.SinfM_isCyclic
    exact isCyclic_of_surjective (Subgroup.equivSMul (MulAut.conj g)
      ((Q.S : Subgroup G) ⊓ involutionClosure G)).toMonoidHom (Subgroup.equivSMul _ _).surjective
  haveI hRcyc : IsCyclic
      ↥((PM : Subgroup ↥(involutionClosure G)).map (involutionClosure G).subtype) :=
    Subgroup.isCyclic_of_le hle
  refine isCyclic_of_surjective (Subgroup.equivMapOfInjective (PM : Subgroup ↥(involutionClosure G))
    (involutionClosure G).subtype (involutionClosure G).subtype_injective).symm.toMonoidHom ?_
  exact (Subgroup.equivMapOfInjective _ _ _).symm.surjective

/-- The odd core `K = O_{2'}(G)` has odd order, so the central involution `z` is not in it. -/
theorem z_notMem_oPiCore : Q.z ∉ oPiCore {p | p ≠ 2} G := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  intro hz
  have hz2 : orderOf (⟨Q.z, hz⟩ : ↥(oPiCore {p | p ≠ 2} G)) = 2 := by
    rw [Subgroup.orderOf_mk]; exact Q.orderOf_z
  have hd := orderOf_dvd_natCard (⟨Q.z, hz⟩ : ↥(oPiCore {p | p ≠ 2} G))
  rw [hz2] at hd
  exact (oPiCore.isPiGroup {p | p ≠ 2}) 2
    (Nat.mem_primeFactors.mpr ⟨Nat.prime_two, hd, Nat.card_pos.ne'⟩) rfl

include Q in
/-- **The image of `M = ⟨involutions⟩` in `Ḡ = G / O_{2'}(G)` is a cyclic `2`-group.**  By Burnside
(`M` is `2`-nilpotent, its Sylow `2` being cyclic) `M = L·Pₘ` with `L` its odd normal complement;
`L` maps into `K = O_{2'}(G)`, so the image of `M` equals the image of the cyclic `2`-group `Pₘ`. -/
theorem image_M_isCyclic_and_isPGroup :
    IsCyclic ↥((involutionClosure G).map (QuotientGroup.mk' (oPiCore {p | p ≠ 2} G))) ∧
      IsPGroup 2 ((involutionClosure G).map (QuotientGroup.mk' (oPiCore {p | p ≠ 2} G))) := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  haveI : (involutionClosure G).Normal := involutionClosure_normal
  obtain ⟨PM⟩ := (inferInstance : Nonempty (Sylow 2 ↥(involutionClosure G)))
  haveI hPMcyc : IsCyclic (PM : Subgroup ↥(involutionClosure G)) := Q.sylowTwoM_isCyclic PM
  have hev : 2 ∣ Nat.card ↥(involutionClosure G) := by
    have hz : Q.z ∈ involutionClosure G := mem_involutionClosure_of_orderOf_eq_two Q.orderOf_z
    have hz2 : orderOf (⟨Q.z, hz⟩ : ↥(involutionClosure G)) = 2 := by
      rw [Subgroup.orderOf_mk]; exact Q.orderOf_z
    have hd := orderOf_dvd_natCard (⟨Q.z, hz⟩ : ↥(involutionClosure G))
    rwa [hz2] at hd
  obtain ⟨L, _, hLodd, hLmem, hLsup⟩ := exists_oddComplement_of_isCyclic_sylowTwo PM hPMcyc hev
  set LG := L.map (involutionClosure G).subtype with hLG
  set R := (PM : Subgroup ↥(involutionClosure G)).map (involutionClosure G).subtype with hR
  -- membership characterization of `LG` (odd-order elements of `M`)
  have hLGmem : ∀ w : G, w ∈ LG ↔ w ∈ involutionClosure G ∧ Odd (orderOf w) := by
    intro w
    constructor
    · intro hw
      rw [hLG, Subgroup.mem_map] at hw
      obtain ⟨⟨y, hy⟩, hyL, hxw⟩ := hw
      subst hxw
      refine ⟨hy, ?_⟩
      rw [orderOf_injective (involutionClosure G).subtype Subtype.coe_injective ⟨y, hy⟩]
      exact (hLmem ⟨y, hy⟩).mp hyL
    · rintro ⟨hw, hodd⟩
      rw [hLG, Subgroup.mem_map]
      refine ⟨⟨w, hw⟩, (hLmem ⟨w, hw⟩).mpr ?_, rfl⟩
      rw [Subgroup.orderOf_mk]; exact hodd
  -- `LG ⊴ G` (odd-order elements are conjugation-invariant)
  haveI hLGnorm : LG.Normal := by
    refine ⟨fun n hn g => ?_⟩
    rw [hLGmem] at hn ⊢
    refine ⟨involutionClosure_normal.conj_mem n hn.1 g, ?_⟩
    rw [← orderOf_eq_of_isConj (isConj_iff.mpr ⟨g, rfl⟩)]
    exact hn.2
  -- `LG` has odd order, so `LG ≤ K`
  have hLGodd : ¬ 2 ∣ Nat.card LG := by
    rw [hLG, ← Nat.card_congr (Subgroup.equivMapOfInjective L (involutionClosure G).subtype
      Subtype.coe_injective).toEquiv]
    exact hLodd
  have hLGle : LG ≤ oPiCore {p | p ≠ 2} G :=
    Subgroup.IsPiGroup.le_oPiCore fun p hp => by
      rintro rfl; exact hLGodd (Nat.dvd_of_mem_primeFactors hp)
  -- `M = LG ⊔ R`, so its image in `Ḡ` equals the image of `R`
  have hsup : LG ⊔ R = involutionClosure G := by
    rw [hLG, hR, ← Subgroup.map_sup, hLsup, ← MonoidHom.range_eq_map, Subgroup.range_subtype]
  have hMbar : (involutionClosure G).map (QuotientGroup.mk' (oPiCore {p | p ≠ 2} G))
      = R.map (QuotientGroup.mk' (oPiCore {p | p ≠ 2} G)) := by
    rw [← hsup, Subgroup.map_sup,
      show LG.map (QuotientGroup.mk' (oPiCore {p | p ≠ 2} G)) = ⊥ from by
        rw [Subgroup.map_eq_bot_iff, QuotientGroup.ker_mk']; exact hLGle, bot_sup_eq]
  rw [hMbar]
  haveI hRcyc : IsCyclic ↥R := by
    rw [hR]
    exact isCyclic_of_surjective (Subgroup.equivMapOfInjective _ (involutionClosure G).subtype
      Subtype.coe_injective).toMonoidHom (Subgroup.equivMapOfInjective _ _ _).surjective
  exact ⟨isCyclic_of_surjective _
      ((QuotientGroup.mk' (oPiCore {p | p ≠ 2} G)).subgroupMap_surjective R),
    (PM.isPGroup'.map (involutionClosure G).subtype).map (QuotientGroup.mk' _)⟩

include Q in
/-- **The image `z̄` of the central involution is central in `Ḡ = G / O_{2'}(G)`** (Gorenstein
Ch.12, p. 377).  The image of `M` is a normal cyclic `2`-group `M̄` containing `z̄` (order `2`,
since `z ∉ K`).  A cyclic group has a unique involution, so any conjugate `ḡ z̄ ḡ⁻¹` — again an
involution of the normal `M̄` — equals `z̄`; hence `z̄` commutes with all of `Ḡ`. -/
theorem zbar_central :
    QuotientGroup.mk' (oPiCore {p | p ≠ 2} G) Q.z ∈
      Subgroup.center (G ⧸ oPiCore {p | p ≠ 2} G) := by
  set K := oPiCore {p | p ≠ 2} G with hKdef
  set zbar := QuotientGroup.mk' K Q.z with hzbar
  haveI : (involutionClosure G).Normal := involutionClosure_normal
  obtain ⟨hMcyc, _⟩ := Q.image_M_isCyclic_and_isPGroup
  haveI := hMcyc
  haveI hMbarNormal : ((involutionClosure G).map (QuotientGroup.mk' K)).Normal :=
    involutionClosure_normal.map (QuotientGroup.mk' K) (QuotientGroup.mk'_surjective K)
  have hzM : Q.z ∈ involutionClosure G := mem_involutionClosure_of_orderOf_eq_two Q.orderOf_z
  have hzbarM : zbar ∈ (involutionClosure G).map (QuotientGroup.mk' K) :=
    Subgroup.mem_map_of_mem _ hzM
  have hzbar_sq : zbar ^ 2 = 1 := by rw [hzbar, ← map_pow, Q.z_sq, map_one]
  have hzbar_ne : zbar ≠ 1 := by
    rw [hzbar, Ne, QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]; exact Q.z_notMem_oPiCore
  rw [Subgroup.mem_center_iff]
  intro gg
  -- `w = gg·z̄·gg⁻¹` is an involution of the normal `M̄`, hence equals `z̄`.
  have hconj : gg * zbar * gg⁻¹ = MulAut.conj gg zbar := rfl
  have hwM : gg * zbar * gg⁻¹ ∈ (involutionClosure G).map (QuotientGroup.mk' K) :=
    hMbarNormal.conj_mem _ hzbarM gg
  have hw_sq : (gg * zbar * gg⁻¹) ^ 2 = 1 := by
    rw [hconj, ← map_pow, hzbar_sq, map_one]
  have hw_ne : gg * zbar * gg⁻¹ ≠ 1 := by
    rw [hconj]
    exact fun h => hzbar_ne ((MulAut.conj gg).injective (h.trans (map_one (MulAut.conj gg)).symm))
  -- both are involutions of the cyclic `↥M̄`, so equal
  have hkey : (⟨zbar, hzbarM⟩ : ↥((involutionClosure G).map (QuotientGroup.mk' K)))
      = ⟨gg * zbar * gg⁻¹, hwM⟩ :=
    eq_of_sq_eq_one_of_isCyclic
      (Subtype.ext (by push_cast; exact hzbar_sq)) (by simpa using hzbar_ne)
      (Subtype.ext (by push_cast; exact hw_sq)) (by simpa using hw_ne)
  have hz_eq : zbar = gg * zbar * gg⁻¹ := congrArg Subtype.val hkey
  rw [← mul_inv_eq_iff_eq_mul, ← hz_eq]

include Q in
/-- **Brauer–Suzuki theorem, generalized quaternion case** (Gorenstein, *Finite Groups*, Ch.12,
Theorem 1.1): if a Sylow `2`-subgroup of the finite group `G` is generalized quaternion (of order
`≥ 16`), then `G = O_{2'}(G)·C_G(z)` for the central involution `z`, stated as
`oPiCore {p | p ≠ 2} G ⊔ centralizer {z} = ⊤`.

Endgame (p. 377): the image `z̄` of `z` is central in `Ḡ = G/K` (`K = O_{2'}(G)`, `zbar_central`),
so `N := K·⟨z⟩ = ⟨z⟩ ⊔ K` is normal in `G` with `⟨z⟩` a Sylow `2`-subgroup (as `|N| = 2|K|`, `K`
odd).  Frattini's argument gives `N_G(⟨z⟩) ⊔ N = ⊤`, and `N_G(⟨z⟩) ≤ C_G(z)` (unique involution),
`N ≤ K ⊔ ⟨z⟩ ≤ K ⊔ C_G(z)`, whence `K ⊔ C_G(z) = ⊤`. -/
theorem brauerSuzuki_of_quaternionSylow :
    oPiCore {p | p ≠ 2} G ⊔ Subgroup.centralizer {Q.z} = ⊤ := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  set K := oPiCore {p | p ≠ 2} G with hKdef
  have hKodd : ¬ 2 ∣ Nat.card ↥K := fun h2 =>
    (oPiCore.isPiGroup {p | p ≠ 2}) 2
      (Nat.mem_primeFactors.mpr ⟨Nat.prime_two, h2, Nat.card_pos.ne'⟩) rfl
  set zbar := QuotientGroup.mk' K Q.z with hzbar
  have hzbar_sq : zbar ^ 2 = 1 := by rw [hzbar, ← map_pow, Q.z_sq, map_one]
  have hzbar_ne : zbar ≠ 1 := by
    rw [hzbar, Ne, QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]; exact Q.z_notMem_oPiCore
  have hzbar_ord : orderOf zbar = 2 := orderOf_eq_prime hzbar_sq hzbar_ne
  -- `N = ⟨z⟩ ⊔ K`, the preimage of the central subgroup `⟨z̄⟩`.
  have hzpm : Subgroup.zpowers zbar = (Subgroup.zpowers Q.z).map (QuotientGroup.mk' K) := by
    rw [hzbar, ← MonoidHom.map_zpowers]
  set N := Subgroup.zpowers Q.z ⊔ K with hNdef
  have hNeq : (Subgroup.zpowers zbar).comap (QuotientGroup.mk' K) = N := by
    rw [hzpm, Subgroup.comap_map_eq, QuotientGroup.ker_mk', hNdef]
  -- `N ⊴ G` since `⟨z̄⟩ ≤ center` is normal.
  haveI hzbarZp_normal : (Subgroup.zpowers zbar).Normal := by
    refine ⟨fun n hn g => ?_⟩
    have hcomm := Subgroup.mem_center_iff.mp (Subgroup.zpowers_le.mpr Q.zbar_central hn) g
    rw [hcomm, mul_inv_cancel_right]; exact hn
  haveI hNnorm : N.Normal := by rw [← hNeq]; exact hzbarZp_normal.comap _
  have hzpN : Subgroup.zpowers Q.z ≤ N := le_sup_left
  -- `|N| = 2·|K|`, so `⟨z⟩` (order 2) is a Sylow 2-subgroup of `N`.
  have hzbarNcard : Nat.card ↥(Subgroup.zpowers zbar) = 2 := by rw [Nat.card_zpowers, hzbar_ord]
  have hNcard : Nat.card ↥N = 2 * Nat.card ↥K := by
    have e1 : Nat.card ↥N * N.index = Nat.card G := Subgroup.card_mul_index N
    have e2 : Nat.card ↥K * Nat.card (G ⧸ K) = Nat.card G := by
      rw [← Subgroup.index_eq_card]; exact Subgroup.card_mul_index K
    have e3 : Nat.card ↥(Subgroup.zpowers zbar) * (Subgroup.zpowers zbar).index
        = Nat.card (G ⧸ K) := Subgroup.card_mul_index _
    have e4 : N.index = (Subgroup.zpowers zbar).index := by
      rw [← hNeq]
      exact Subgroup.index_comap_of_surjective (Subgroup.zpowers zbar)
        (QuotientGroup.mk'_surjective K)
    have hkey : Nat.card ↥N * N.index = 2 * Nat.card ↥K * N.index := by
      rw [e1, ← e2, ← e3, hzbarNcard, e4]; ring
    exact Nat.eq_of_mul_eq_mul_right
      (Nat.pos_of_ne_zero (Subgroup.index_ne_zero_of_finite)) hkey
  have hzpZcard : Nat.card ↥((Subgroup.zpowers Q.z).subgroupOf N) = 2 := by
    rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe hzpN).toEquiv, Nat.card_zpowers, Q.orderOf_z]
  have hidxK : ((Subgroup.zpowers Q.z).subgroupOf N).index = Nat.card ↥K := by
    have h := Subgroup.card_mul_index ((Subgroup.zpowers Q.z).subgroupOf N)
    rw [hzpZcard, hNcard] at h
    exact Nat.eq_of_mul_eq_mul_left (by norm_num) h
  have hpg : IsPGroup 2 ((Subgroup.zpowers Q.z).subgroupOf N) :=
    IsPGroup.of_card (n := 1) (by rw [hzpZcard, pow_one])
  set P : Sylow 2 ↥N := hpg.toSylow (by rw [hidxK]; exact hKodd) with hP
  have hPmap : (P : Subgroup ↥N).map N.subtype = Subgroup.zpowers Q.z := by
    rw [hP, IsPGroup.toSylow_coe, Subgroup.subgroupOf_map_subtype, inf_of_le_left hzpN]
  -- Frattini's argument.
  have hfrat := Sylow.normalizer_sup_eq_top P
  rw [hPmap] at hfrat
  -- `N_G(⟨z⟩) ≤ C_G(z)` (unique involution of the cyclic `⟨z⟩`).
  have hnorm_le : Subgroup.normalizer (Subgroup.zpowers Q.z) ≤ Subgroup.centralizer {Q.z} := by
    intro g hg
    rw [Subgroup.mem_normalizer_iff] at hg
    have hconj : g * Q.z * g⁻¹ ∈ Subgroup.zpowers Q.z := (hg Q.z).mp (Subgroup.mem_zpowers _)
    have hgz : g * Q.z * g⁻¹ = Q.z := by
      have hsq : (g * Q.z * g⁻¹) ^ 2 = 1 := by
        rw [show g * Q.z * g⁻¹ = MulAut.conj g Q.z from rfl, ← map_pow, Q.z_sq, map_one]
      have hne : g * Q.z * g⁻¹ ≠ 1 := fun h =>
        Q.z_ne_one ((MulAut.conj g).injective (h.trans (map_one (MulAut.conj g)).symm))
      have hkey := eq_of_sq_eq_one_of_isCyclic (C := ↥(Subgroup.zpowers Q.z))
        (a := ⟨g * Q.z * g⁻¹, hconj⟩) (b := ⟨Q.z, Subgroup.mem_zpowers _⟩)
        (Subtype.ext (by push_cast; exact hsq)) (by simpa using hne)
        (Subtype.ext (by push_cast; exact Q.z_sq)) (by simpa using Q.z_ne_one)
      exact congrArg Subtype.val hkey
    rw [Subgroup.mem_centralizer_iff]
    rintro w hw
    rw [Set.mem_singleton_iff] at hw; subst hw
    have hgz2 : g * Q.z = Q.z * g := by
      calc g * Q.z = g * Q.z * g⁻¹ * g := by group
        _ = Q.z * g := by rw [hgz]
    exact hgz2.symm
  -- assemble: `⊤ = N_G(⟨z⟩) ⊔ N ≤ K ⊔ C_G(z)`.
  rw [eq_top_iff, ← hfrat]
  refine sup_le (hnorm_le.trans le_sup_right) ?_
  rw [hNdef]
  refine sup_le (le_sup_of_le_right ?_) le_sup_left
  exact Subgroup.zpowers_le.mpr (Subgroup.mem_centralizer_iff.mpr
    (fun m hm => by rw [Set.mem_singleton_iff] at hm; subst hm; rfl))

end QuaternionSylowSetup

end OddOrder.GroupTheory
