/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.GroupTheory.BrauerSuzukiCounting

/-!
# Brauer–Suzuki: the group-theoretic endgame (Gorenstein Ch. 12, pp. 376–377)

**Gorenstein, *Finite Groups*, Ch. 12, Theorem 1.1** (final steps): from the non-linear
irreducible character `χ` whose kernel contains every involution (`lem_1_9`), one shows that the
subgroup `M = ⟨involutions⟩` (normal in `G`) has cyclic Sylow `2`-subgroup `Q = S ∩ M`, whence a
Burnside normal `2`-complement argument gives `Z(G/O_{2'}(G))` of order `2`, equivalently
`G = O_{2'}(G)·C_G(u)` for the central involution `u`.

This file assembles the endgame.  It opens with the normal subgroup generated by involutions.
-/

namespace OddOrder.GroupTheory

variable {G : Type*} [Group G]

/-- **The subgroup generated by all involutions of `G`** (Gorenstein's `M`).  Since the set of
involutions `{u | orderOf u = 2}` is invariant under conjugation, its generated subgroup is
normal. -/
def involutionClosure (G : Type*) [Group G] : Subgroup G :=
  Subgroup.closure {u : G | orderOf u = 2}

theorem mem_involutionClosure_of_orderOf_eq_two {u : G} (hu : orderOf u = 2) :
    u ∈ involutionClosure G :=
  Subgroup.subset_closure hu

/-- **`M = ⟨involutions⟩` is normal in `G`.**  Conjugation preserves order, so the involution set
is conjugation-invariant and its closure is normalized by all of `G`. -/
instance involutionClosure_normal : (involutionClosure G).Normal := by
  rw [involutionClosure, ← Subgroup.normalizer_eq_top_iff]
  refine top_unique ?_
  rw [Subgroup.le_normalizer_closure_iff]
  rintro g _ u (hu : orderOf u = 2)
  refine Subgroup.subset_closure (show orderOf (g * u * g⁻¹) = 2 from ?_)
  rw [← orderOf_eq_of_isConj (isConj_iff.mpr ⟨g, rfl⟩)]
  exact hu

end OddOrder.GroupTheory
