/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.GroupTheory.BrauerSuzukiSetup
import OddOrder.GroupTheory.UniqueInvolutionSylow
import Mathlib.GroupTheory.Sylow

/-!
# Brauer–Suzuki: counting involutions (Gorenstein Ch. 12, Lemma 1.7)

**Gorenstein, *Finite Groups*, Ch. 12, Lemma 1.7** (pp. 375–376): in the
`QuaternionSylowSetup` (issue 9318), if `β(y)` counts the ordered pairs of involutions with
product `y`, then `β(y) = 0` whenever `y` has even order.

The group-theoretic heart is that **any two commuting involutions of `G` are equal**
(`commute_involution_eq`): a `2`-subgroup containing them lies in a Sylow `2`-subgroup, which
is conjugate to the generalized quaternion group `S` (hence has a *unique* involution
`eq_one_or_eq_z_of_sq_eq_one`).  From this, **the product of two involutions has odd order**
(`odd_orderOf_mul_of_involution`): if `u v` had even order `2s` then `(uv)ˢ` would be a
central involution commuting with (and inverted by) both `u` and `v`, forcing `u = v = (uv)ˢ`
and hence `uv = 1` — contradicting even order `≥ 2`.
-/

open scoped Pointwise

namespace OddOrder.GroupTheory

namespace QuaternionSylowSetup

variable {G : Type*} [Group G] [Finite G] (Q : QuaternionSylowSetup G)

omit [Finite G] in
/-- Conjugation preserves the involution equation `w² = 1`. -/
theorem conj_sq_eq_one {c w : G} (hw : w ^ 2 = 1) : (c * w * c⁻¹) ^ 2 = 1 := by
  rw [show c * w * c⁻¹ = MulAut.conj c w from rfl, ← map_pow, hw, map_one]

omit [Finite G] in
/-- Conjugation preserves nontriviality. -/
theorem conj_ne_one {c w : G} (hw : w ≠ 1) : c * w * c⁻¹ ≠ 1 := by
  intro hcontra
  exact hw (by
    have hwc : w = c⁻¹ * (c * w * c⁻¹) * c := by group
    rw [hwc, hcontra]; group)

include Q

/-- **A `2`-subgroup can be conjugated into `S`.**  Since all Sylow `2`-subgroups are conjugate,
a `2`-group `K` lies in some Sylow `2`-subgroup `P` (`IsPGroup.exists_le_sylow`), and there is a
`c ∈ G` with `c • P = S`, so `c` conjugates every element of `K` into `S`. -/
theorem exists_conj_subgroupLe_S {K : Subgroup G} (hK : IsPGroup 2 K) :
    ∃ c : G, ∀ w ∈ K, c * w * c⁻¹ ∈ (Q.S : Subgroup G) :=
  OddOrder.GroupTheory.exists_conj_subgroupLe_sylow Q.S hK

/-- **Any two commuting involutions of `G` are equal** (Gorenstein Ch. 12, the unique-involution
input to Lemma 1.7).  The subgroup `⟨u, v⟩` generated by two commuting involutions is an
elementary abelian `2`-group, so it lies in a Sylow `2`-subgroup `P`; conjugating `P` onto the
generalized quaternion group `S` sends both `u` and `v` to the *unique* involution `z` of `S`
(`eq_one_or_eq_z_of_sq_eq_one`), whence `u = v`. -/
theorem commute_involution_eq {u v : G} (hu : orderOf u = 2) (hv : orderOf v = 2)
    (huv : Commute u v) : u = v :=
  commute_involution_eq_of_unique_involution Q.S
    (fun _ hs h => Q.eq_one_or_eq_z_of_sq_eq_one hs h) hu hv huv

/-- **Every involution of `G` is conjugate to `z`** (Gorenstein Ch. 12): the cyclic `2`-group
`⟨u⟩` lies in a Sylow `2`-subgroup conjugate to `S`, whose unique involution is `z`. -/
theorem exists_conj_eq_z {u : G} (hu : orderOf u = 2) : ∃ c : G, c * u * c⁻¹ = Q.z := by
  have hu2 : u ^ 2 = 1 := by rw [← hu, pow_orderOf_eq_one]
  have hune : u ≠ 1 := by rintro rfl; simp [orderOf_one] at hu
  have hpg : IsPGroup 2 (Subgroup.zpowers u) :=
    IsPGroup.of_card (show Nat.card (Subgroup.zpowers u) = 2 ^ 1 by
      rw [Nat.card_zpowers, hu, pow_one])
  obtain ⟨c, hconj⟩ := Q.exists_conj_subgroupLe_S hpg
  exact ⟨c, (Q.eq_one_or_eq_z_of_sq_eq_one (hconj u (Subgroup.mem_zpowers u))
    (conj_sq_eq_one hu2)).resolve_left (conj_ne_one hune)⟩

/-- **All involutions of `G` are conjugate** (Gorenstein Ch. 12): `G` has a single class of
involutions, since each is conjugate to `z` (`exists_conj_eq_z`).  This is the input for the
class-sum formula `(9.4.2)` in Lemma 1.8. -/
theorem isConj_of_orderOf_eq_two {u v : G} (hu : orderOf u = 2) (hv : orderOf v = 2) :
    IsConj u v := by
  obtain ⟨c, hc⟩ := Q.exists_conj_eq_z hu
  obtain ⟨d, hd⟩ := Q.exists_conj_eq_z hv
  rw [isConj_iff]
  refine ⟨d⁻¹ * c, ?_⟩
  have he : (d⁻¹ * c) * u * (d⁻¹ * c)⁻¹ = d⁻¹ * (c * u * c⁻¹) * d := by group
  rw [he, hc, ← hd]; group

/-- `z` is an involution: `orderOf z = 2`. -/
theorem orderOf_z : orderOf Q.z = 2 := by
  have hdvd : orderOf Q.z ∣ 2 := orderOf_dvd_of_pow_eq_one Q.z_sq
  rcases (Nat.dvd_prime Nat.prime_two).mp hdvd with h | h
  · exact absurd (orderOf_eq_one_iff.mp h) Q.z_ne_one
  · exact h

/-- **Characterization of the involution class**: `u` is conjugate to `z` iff `u` is an
involution.  Since all involutions are conjugate (`isConj_of_orderOf_eq_two`) and `z` is one
(`orderOf_z`), the involutions of `G` are exactly the conjugacy class of `z` — the class `K`
used in the class-sum formula for Lemma 1.8. -/
theorem isConj_z_iff_orderOf_eq_two {u : G} : IsConj u Q.z ↔ orderOf u = 2 := by
  constructor
  · intro h
    obtain ⟨c, hc⟩ := isConj_iff.mp h
    have heq : orderOf u = orderOf (c * u * c⁻¹) :=
      SemiconjBy.orderOf_eq c (show SemiconjBy c u (c * u * c⁻¹) by
        change c * u = c * u * c⁻¹ * c; group)
    rw [hc, Q.orderOf_z] at heq
    exact heq
  · intro hu
    obtain ⟨c, hc⟩ := Q.exists_conj_eq_z hu
    exact isConj_iff.mpr ⟨c, hc⟩

/-- **The product of two involutions has odd order** (Gorenstein Ch. 12, Lemma 1.7).  If `u v`
had even order `2s`, the involution `z' = (uv)ˢ` (a power of `uv`) would be inverted by both
`u` and `v` (each inverts `uv`), hence centralized by them (`z'` is an involution).  By
`commute_involution_eq`, `u = z' = v`, so `uv = z'² = 1`, contradicting even order `≥ 2`. -/
theorem odd_orderOf_mul_of_involution {u v : G} (hu : orderOf u = 2) (hv : orderOf v = 2) :
    Odd (orderOf (u * v)) :=
  odd_orderOf_mul_of_involution_of_unique_involution Q.S
    (fun _ hs h => Q.eq_one_or_eq_z_of_sq_eq_one hs h) hu hv

end QuaternionSylowSetup

end OddOrder.GroupTheory
