/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.GroupTheory.BrauerSuzukiSetup
import Mathlib.GroupTheory.Sylow

/-!
# Brauer–Suzuki: counting involutions (Gorenstein Ch. 12, Lemma 1.7)

**Gorenstein, *Finite Groups*, Ch. 12, Lemma 1.7** (pp. 375–376): in the
`QuaternionSylowSetup` (issue 9318), if `β(y)` counts the ordered pairs of involutions with
product `y`, then `β(y) = 0` whenever `y` has even order.

The group-theoretic heart is that **any two commuting involutions of `G` are equal**
(`commute_involution_eq`): a `2`-subgroup containing them lies in a Sylow `2`-subgroup, which
is conjugate to the generalized quaternion group `S` (hence has a *unique* involution
`eq_one_or_eq_z_of_sq_eq_one`).  From this, **the product of two involutions has odd order**
(`odd_orderOf_mul_of_involution`): if `u v` had even order `2s` then `(uv)ˢ` would be a
central involution commuting with (and inverted by) both `u` and `v`, forcing `u = v = (uv)ˢ`
and hence `uv = 1` — contradicting even order `≥ 2`.
-/

open scoped Pointwise

namespace OddOrder.GroupTheory

namespace QuaternionSylowSetup

variable {G : Type*} [Group G] [Finite G] (Q : QuaternionSylowSetup G)

omit [Finite G] in
/-- Conjugation preserves the involution equation `w² = 1`. -/
theorem conj_sq_eq_one {c w : G} (hw : w ^ 2 = 1) : (c * w * c⁻¹) ^ 2 = 1 := by
  rw [show c * w * c⁻¹ = MulAut.conj c w from rfl, ← map_pow, hw, map_one]

omit [Finite G] in
/-- Conjugation preserves nontriviality. -/
theorem conj_ne_one {c w : G} (hw : w ≠ 1) : c * w * c⁻¹ ≠ 1 := by
  intro hcontra
  exact hw (by
    have hwc : w = c⁻¹ * (c * w * c⁻¹) * c := by group
    rw [hwc, hcontra]; group)

include Q

/-- **A `2`-subgroup can be conjugated into `S`.**  Since all Sylow `2`-subgroups are conjugate,
a `2`-group `K` lies in some Sylow `2`-subgroup `P` (`IsPGroup.exists_le_sylow`), and there is a
`c ∈ G` with `c • P = S`, so `c` conjugates every element of `K` into `S`. -/
theorem exists_conj_subgroupLe_S {K : Subgroup G} (hK : IsPGroup 2 K) :
    ∃ c : G, ∀ w ∈ K, c * w * c⁻¹ ∈ (Q.S : Subgroup G) := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  obtain ⟨P, hKP⟩ := hK.exists_le_sylow
  obtain ⟨c, hc⟩ := MulAction.exists_smul_eq G P Q.S
  refine ⟨c, fun w hw => ?_⟩
  have hwP : w ∈ (P : Subgroup G) := hKP hw
  have hmem : MulAut.conj c • w ∈ MulAut.conj c • (P : Subgroup G) :=
    Subgroup.smul_mem_pointwise_smul w (MulAut.conj c) _ hwP
  rw [← Sylow.coe_subgroup_smul, hc] at hmem
  simpa only [MulAut.smul_def, MulAut.conj_apply] using hmem

/-- **Any two commuting involutions of `G` are equal** (Gorenstein Ch. 12, the unique-involution
input to Lemma 1.7).  The subgroup `⟨u, v⟩` generated by two commuting involutions is an
elementary abelian `2`-group, so it lies in a Sylow `2`-subgroup `P`; conjugating `P` onto the
generalized quaternion group `S` sends both `u` and `v` to the *unique* involution `z` of `S`
(`eq_one_or_eq_z_of_sq_eq_one`), whence `u = v`. -/
theorem commute_involution_eq {u v : G} (hu : orderOf u = 2) (hv : orderOf v = 2)
    (huv : Commute u v) : u = v := by
  have hu2 : u ^ 2 = 1 := by rw [← hu, pow_orderOf_eq_one]
  have hv2 : v ^ 2 = 1 := by rw [← hv, pow_orderOf_eq_one]
  have hune : u ≠ 1 := by rintro rfl; simp [orderOf_one] at hu
  have hvne : v ≠ 1 := by rintro rfl; simp [orderOf_one] at hv
  set K := Subgroup.closure ({u, v} : Set G) with hKdef
  have huK : u ∈ K := Subgroup.subset_closure (by left; rfl)
  have hvK : v ∈ K := Subgroup.subset_closure (by right; rfl)
  -- `K` is abelian (commuting generators)
  have hcomm_gen : ∀ a ∈ ({u, v} : Set G), ∀ b ∈ ({u, v} : Set G), Commute a b := by
    intro a ha b hb
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at ha hb
    rcases ha with rfl | rfl <;> rcases hb with rfl | rfl
    · exact Commute.refl _
    · exact huv
    · exact huv.symm
    · exact Commute.refl _
  have habelian : ∀ a ∈ K, ∀ b ∈ K, Commute a b := by
    intro a ha b hb
    refine Subgroup.closure_induction₂ (fun x y hx hy => hcomm_gen x hx y hy)
      (fun x _ => Commute.one_left x) (fun x _ => Commute.one_right x)
      (fun x y z _ _ _ h1 h2 => h1.mul_left h2)
      (fun y z x _ _ _ h1 h2 => h1.mul_right h2)
      (fun x y _ _ h => h.inv_left) (fun x y _ _ h => h.inv_right) ha hb
  -- every element of `K` squares to `1`
  have hsq : ∀ g ∈ K, g ^ 2 = 1 := by
    intro g hg
    induction hg using Subgroup.closure_induction with
    | mem x hx =>
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
        rcases hx with rfl | rfl
        · exact hu2
        · exact hv2
    | one => exact one_pow 2
    | mul a b ha hb h1 h2 =>
        rw [(habelian a ha b hb).mul_pow, h1, h2, one_mul]
    | inv a ha h => rw [inv_pow, h, inv_one]
  -- hence `K` is a `2`-group
  have hpgroup : IsPGroup 2 K := by
    intro g
    refine ⟨1, ?_⟩
    have h := hsq (g : G) g.2
    apply Subtype.ext
    push_cast
    simpa using h
  -- conjugate `K` into `S` by some `c`; both `c u c⁻¹`, `c v c⁻¹` are involutions of `S`, hence `z`
  obtain ⟨c, hconjS⟩ := Q.exists_conj_subgroupLe_S hpgroup
  have hu_z : c * u * c⁻¹ = Q.z :=
    (Q.eq_one_or_eq_z_of_sq_eq_one (hconjS u huK) (conj_sq_eq_one hu2)).resolve_left
      (conj_ne_one hune)
  have hv_z : c * v * c⁻¹ = Q.z :=
    (Q.eq_one_or_eq_z_of_sq_eq_one (hconjS v hvK) (conj_sq_eq_one hv2)).resolve_left
      (conj_ne_one hvne)
  have hconj_eq : c * u * c⁻¹ = c * v * c⁻¹ := hu_z.trans hv_z.symm
  exact mul_left_cancel (mul_right_cancel hconj_eq)

/-- **Every involution of `G` is conjugate to `z`** (Gorenstein Ch. 12): the cyclic `2`-group
`⟨u⟩` lies in a Sylow `2`-subgroup conjugate to `S`, whose unique involution is `z`. -/
theorem exists_conj_eq_z {u : G} (hu : orderOf u = 2) : ∃ c : G, c * u * c⁻¹ = Q.z := by
  have hu2 : u ^ 2 = 1 := by rw [← hu, pow_orderOf_eq_one]
  have hune : u ≠ 1 := by rintro rfl; simp [orderOf_one] at hu
  have hpg : IsPGroup 2 (Subgroup.zpowers u) :=
    IsPGroup.of_card (show Nat.card (Subgroup.zpowers u) = 2 ^ 1 by
      rw [Nat.card_zpowers, hu, pow_one])
  obtain ⟨c, hconj⟩ := Q.exists_conj_subgroupLe_S hpg
  exact ⟨c, (Q.eq_one_or_eq_z_of_sq_eq_one (hconj u (Subgroup.mem_zpowers u))
    (conj_sq_eq_one hu2)).resolve_left (conj_ne_one hune)⟩

/-- **All involutions of `G` are conjugate** (Gorenstein Ch. 12): `G` has a single class of
involutions, since each is conjugate to `z` (`exists_conj_eq_z`).  This is the input for the
class-sum formula `(9.4.2)` in Lemma 1.8. -/
theorem isConj_of_orderOf_eq_two {u v : G} (hu : orderOf u = 2) (hv : orderOf v = 2) :
    IsConj u v := by
  obtain ⟨c, hc⟩ := Q.exists_conj_eq_z hu
  obtain ⟨d, hd⟩ := Q.exists_conj_eq_z hv
  rw [isConj_iff]
  refine ⟨d⁻¹ * c, ?_⟩
  have he : (d⁻¹ * c) * u * (d⁻¹ * c)⁻¹ = d⁻¹ * (c * u * c⁻¹) * d := by group
  rw [he, hc, ← hd]; group

/-- `z` is an involution: `orderOf z = 2`. -/
theorem orderOf_z : orderOf Q.z = 2 := by
  have hdvd : orderOf Q.z ∣ 2 := orderOf_dvd_of_pow_eq_one Q.z_sq
  rcases (Nat.dvd_prime Nat.prime_two).mp hdvd with h | h
  · exact absurd (orderOf_eq_one_iff.mp h) Q.z_ne_one
  · exact h

/-- **Characterization of the involution class**: `u` is conjugate to `z` iff `u` is an
involution.  Since all involutions are conjugate (`isConj_of_orderOf_eq_two`) and `z` is one
(`orderOf_z`), the involutions of `G` are exactly the conjugacy class of `z` — the class `K`
used in the class-sum formula for Lemma 1.8. -/
theorem isConj_z_iff_orderOf_eq_two {u : G} : IsConj u Q.z ↔ orderOf u = 2 := by
  constructor
  · intro h
    obtain ⟨c, hc⟩ := isConj_iff.mp h
    have heq : orderOf u = orderOf (c * u * c⁻¹) :=
      SemiconjBy.orderOf_eq c (show SemiconjBy c u (c * u * c⁻¹) by
        change c * u = c * u * c⁻¹ * c; group)
    rw [hc, Q.orderOf_z] at heq
    exact heq
  · intro hu
    obtain ⟨c, hc⟩ := Q.exists_conj_eq_z hu
    exact isConj_iff.mpr ⟨c, hc⟩

/-- **The product of two involutions has odd order** (Gorenstein Ch. 12, Lemma 1.7).  If `u v`
had even order `2s`, the involution `z' = (uv)ˢ` (a power of `uv`) would be inverted by both
`u` and `v` (each inverts `uv`), hence centralized by them (`z'` is an involution).  By
`commute_involution_eq`, `u = z' = v`, so `uv = z'² = 1`, contradicting even order `≥ 2`. -/
theorem odd_orderOf_mul_of_involution {u v : G} (hu : orderOf u = 2) (hv : orderOf v = 2) :
    Odd (orderOf (u * v)) := by
  by_contra hodd
  rw [Nat.not_odd_iff_even] at hodd
  set g := u * v with hgdef
  obtain ⟨s, hs⟩ := hodd
  -- `orderOf g = 2 s`, and `orderOf g > 0`, so `s ≥ 1`
  have hgpos : 0 < orderOf g := orderOf_pos g
  have hspos : 0 < s := by omega
  have hu2 : u ^ 2 = 1 := by rw [← hu, pow_orderOf_eq_one]
  have hv2 : v ^ 2 = 1 := by rw [← hv, pow_orderOf_eq_one]
  have huinv : u⁻¹ = u := inv_eq_of_mul_eq_one_right (by rw [← sq]; exact hu2)
  have hvinv : v⁻¹ = v := inv_eq_of_mul_eq_one_right (by rw [← sq]; exact hv2)
  -- `z' = gˢ` is an involution
  set z' := g ^ s with hz'def
  have hz'2 : z' ^ 2 = 1 := by
    rw [hz'def, ← pow_mul, show s * 2 = orderOf g from by omega, pow_orderOf_eq_one]
  have hz'inv : z'⁻¹ = z' := inv_eq_of_mul_eq_one_right (by rw [← sq]; exact hz'2)
  have hz'ne : z' ≠ 1 := by
    rw [hz'def]
    intro h
    have hdvd : orderOf g ∣ s := orderOf_dvd_of_pow_eq_one h
    have := Nat.le_of_dvd hspos hdvd
    omega
  have hz'ord : orderOf z' = 2 := by
    have hdvd : orderOf z' ∣ 2 := orderOf_dvd_of_pow_eq_one hz'2
    rcases (Nat.dvd_prime Nat.prime_two).mp hdvd with h | h
    · exact absurd (orderOf_eq_one_iff.mp h) hz'ne
    · exact h
  -- `u` and `v` each invert `g`, hence centralize the involution `z' = gˢ`
  have hg_inv_u : u * g * u⁻¹ = g⁻¹ := by
    rw [hgdef, huinv, mul_inv_rev, huinv, hvinv]
    calc u * (u * v) * u = (u * u) * v * u := by group
      _ = v * u := by rw [← sq, hu2, one_mul]
  have hg_inv_v : v * g * v⁻¹ = g⁻¹ := by
    rw [hgdef, hvinv, mul_inv_rev, huinv, hvinv]
    calc v * (u * v) * v = v * u * (v * v) := by group
      _ = v * u := by rw [← sq, hv2, mul_one]
  have commute_of_inv : ∀ w : G, w * g * w⁻¹ = g⁻¹ → Commute w z' := by
    intro w hw
    have hsemi : SemiconjBy w g g⁻¹ := mul_inv_eq_iff_eq_mul.mp hw
    have hsp : w * g ^ s = g⁻¹ ^ s * w := hsemi.pow_right s
    have hg_inv_s : g⁻¹ ^ s = z' := by rw [inv_pow, ← hz'def]; exact hz'inv
    rw [hg_inv_s, ← hz'def] at hsp
    exact hsp
  have hu_eq : u = z' := commute_involution_eq Q hu hz'ord (commute_of_inv u hg_inv_u)
  have hv_eq : v = z' := commute_involution_eq Q hv hz'ord (commute_of_inv v hg_inv_v)
  -- then `g = u v = z'² = 1`, contradicting even order `≥ 2`
  have hg1 : g = 1 := by rw [hgdef, hu_eq, hv_eq, ← sq, hz'2]
  rw [hg1, orderOf_one] at hs
  omega

end QuaternionSylowSetup

end OddOrder.GroupTheory
