/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.GroupTheory.BrauerSuzukiSetup
import Mathlib.GroupTheory.Sylow

/-!
# Brauer–Suzuki: counting involutions (Gorenstein Ch. 12, Lemma 1.7)

**Gorenstein, *Finite Groups*, Ch. 12, Lemma 1.7** (pp. 375–376): in the
`QuaternionSylowSetup` (issue 9318), if `β(y)` counts the ordered pairs of involutions with
product `y`, then `β(y) = 0` whenever `y` has even order.

The group-theoretic heart is that **any two commuting involutions of `G` are equal**
(`commute_involution_eq`): a `2`-subgroup containing them lies in a Sylow `2`-subgroup, which
is conjugate to the generalized quaternion group `S` (hence has a *unique* involution
`eq_one_or_eq_z_of_sq_eq_one`).  From this, **the product of two involutions has odd order**
(`odd_orderOf_mul_of_involution`): if `u v` had even order `2s` then `(uv)ˢ` would be a
central involution commuting with (and inverted by) both `u` and `v`, forcing `u = v = (uv)ˢ`
and hence `uv = 1` — contradicting even order `≥ 2`.
-/

open scoped Pointwise

namespace OddOrder.GroupTheory

namespace QuaternionSylowSetup

variable {G : Type*} [Group G] [Finite G] (Q : QuaternionSylowSetup G)

include Q

/-- **Any two commuting involutions of `G` are equal** (Gorenstein Ch. 12, the unique-involution
input to Lemma 1.7).  The subgroup `⟨u, v⟩` generated by two commuting involutions is an
elementary abelian `2`-group, so it lies in a Sylow `2`-subgroup `P`; conjugating `P` onto the
generalized quaternion group `S` sends both `u` and `v` to the *unique* involution `z` of `S`
(`eq_one_or_eq_z_of_sq_eq_one`), whence `u = v`. -/
theorem commute_involution_eq {u v : G} (hu : orderOf u = 2) (hv : orderOf v = 2)
    (huv : Commute u v) : u = v := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  have hu2 : u ^ 2 = 1 := by rw [← hu, pow_orderOf_eq_one]
  have hv2 : v ^ 2 = 1 := by rw [← hv, pow_orderOf_eq_one]
  have hune : u ≠ 1 := by rintro rfl; simp [orderOf_one] at hu
  have hvne : v ≠ 1 := by rintro rfl; simp [orderOf_one] at hv
  set K := Subgroup.closure ({u, v} : Set G) with hKdef
  have huK : u ∈ K := Subgroup.subset_closure (by left; rfl)
  have hvK : v ∈ K := Subgroup.subset_closure (by right; rfl)
  -- `K` is abelian (commuting generators)
  have hcomm_gen : ∀ a ∈ ({u, v} : Set G), ∀ b ∈ ({u, v} : Set G), Commute a b := by
    intro a ha b hb
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at ha hb
    rcases ha with rfl | rfl <;> rcases hb with rfl | rfl
    · exact Commute.refl _
    · exact huv
    · exact huv.symm
    · exact Commute.refl _
  have habelian : ∀ a ∈ K, ∀ b ∈ K, Commute a b := by
    intro a ha b hb
    refine Subgroup.closure_induction₂ (fun x y hx hy => hcomm_gen x hx y hy)
      (fun x _ => Commute.one_left x) (fun x _ => Commute.one_right x)
      (fun x y z _ _ _ h1 h2 => h1.mul_left h2)
      (fun y z x _ _ _ h1 h2 => h1.mul_right h2)
      (fun x y _ _ h => h.inv_left) (fun x y _ _ h => h.inv_right) ha hb
  -- every element of `K` squares to `1`
  have hsq : ∀ g ∈ K, g ^ 2 = 1 := by
    intro g hg
    induction hg using Subgroup.closure_induction with
    | mem x hx =>
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
        rcases hx with rfl | rfl
        · exact hu2
        · exact hv2
    | one => exact one_pow 2
    | mul a b ha hb h1 h2 =>
        rw [(habelian a ha b hb).mul_pow, h1, h2, one_mul]
    | inv a ha h => rw [inv_pow, h, inv_one]
  -- hence `K` is a `2`-group
  have hpgroup : IsPGroup 2 K := by
    intro g
    refine ⟨1, ?_⟩
    have h := hsq (g : G) g.2
    apply Subtype.ext
    push_cast
    simpa using h
  -- `K ≤ P` for some Sylow `2`-subgroup `P`, and `P` is conjugate to `S`
  obtain ⟨P, hKP⟩ := hpgroup.exists_le_sylow
  obtain ⟨c, hc⟩ := MulAction.exists_smul_eq G P Q.S
  -- conjugation by `c` carries `K` into `S`
  have hconjS : ∀ w, w ∈ K → c * w * c⁻¹ ∈ (Q.S : Subgroup G) := by
    intro w hw
    have hwP : w ∈ (P : Subgroup G) := hKP hw
    have hmem : MulAut.conj c • w ∈ MulAut.conj c • (P : Subgroup G) :=
      Subgroup.smul_mem_pointwise_smul w (MulAut.conj c) _ hwP
    rw [← Sylow.coe_subgroup_smul, hc] at hmem
    simpa only [MulAut.smul_def, MulAut.conj_apply] using hmem
  -- both `c u c⁻¹` and `c v c⁻¹` are involutions of `S`, hence equal `z`
  have conj_sq : ∀ w : G, w ^ 2 = 1 → (c * w * c⁻¹) ^ 2 = 1 := by
    intro w hw
    rw [show c * w * c⁻¹ = MulAut.conj c w from rfl, ← map_pow, hw, map_one]
  have conj_ne : ∀ w : G, w ≠ 1 → c * w * c⁻¹ ≠ 1 := by
    intro w hw hcontra
    exact hw (by
      have : w = c⁻¹ * (c * w * c⁻¹) * c := by group
      rw [this, hcontra]; group)
  have hu_z : c * u * c⁻¹ = Q.z :=
    (Q.eq_one_or_eq_z_of_sq_eq_one (hconjS u huK) (conj_sq u hu2)).resolve_left (conj_ne u hune)
  have hv_z : c * v * c⁻¹ = Q.z :=
    (Q.eq_one_or_eq_z_of_sq_eq_one (hconjS v hvK) (conj_sq v hv2)).resolve_left (conj_ne v hvne)
  have hconj_eq : c * u * c⁻¹ = c * v * c⁻¹ := hu_z.trans hv_z.symm
  exact mul_left_cancel (mul_right_cancel hconj_eq)

/-- **The product of two involutions has odd order** (Gorenstein Ch. 12, Lemma 1.7).  If `u v`
had even order `2s`, the involution `z' = (uv)ˢ` (a power of `uv`) would be inverted by both
`u` and `v` (each inverts `uv`), hence centralized by them (`z'` is an involution).  By
`commute_involution_eq`, `u = z' = v`, so `uv = z'² = 1`, contradicting even order `≥ 2`. -/
theorem odd_orderOf_mul_of_involution {u v : G} (hu : orderOf u = 2) (hv : orderOf v = 2) :
    Odd (orderOf (u * v)) := by
  by_contra hodd
  rw [Nat.not_odd_iff_even] at hodd
  set g := u * v with hgdef
  obtain ⟨s, hs⟩ := hodd
  -- `orderOf g = 2 s`, and `orderOf g > 0`, so `s ≥ 1`
  have hgpos : 0 < orderOf g := orderOf_pos g
  have hspos : 0 < s := by omega
  have hu2 : u ^ 2 = 1 := by rw [← hu, pow_orderOf_eq_one]
  have hv2 : v ^ 2 = 1 := by rw [← hv, pow_orderOf_eq_one]
  have huinv : u⁻¹ = u := inv_eq_of_mul_eq_one_right (by rw [← sq]; exact hu2)
  have hvinv : v⁻¹ = v := inv_eq_of_mul_eq_one_right (by rw [← sq]; exact hv2)
  -- `z' = gˢ` is an involution
  set z' := g ^ s with hz'def
  have hz'2 : z' ^ 2 = 1 := by
    rw [hz'def, ← pow_mul, show s * 2 = orderOf g from by omega, pow_orderOf_eq_one]
  have hz'inv : z'⁻¹ = z' := inv_eq_of_mul_eq_one_right (by rw [← sq]; exact hz'2)
  have hz'ne : z' ≠ 1 := by
    rw [hz'def]
    intro h
    have hdvd : orderOf g ∣ s := orderOf_dvd_of_pow_eq_one h
    have := Nat.le_of_dvd hspos hdvd
    omega
  have hz'ord : orderOf z' = 2 := by
    have hdvd : orderOf z' ∣ 2 := orderOf_dvd_of_pow_eq_one hz'2
    rcases (Nat.dvd_prime Nat.prime_two).mp hdvd with h | h
    · exact absurd (orderOf_eq_one_iff.mp h) hz'ne
    · exact h
  -- `u` and `v` each invert `g`, hence centralize the involution `z' = gˢ`
  have hg_inv_u : u * g * u⁻¹ = g⁻¹ := by
    rw [hgdef, huinv, mul_inv_rev, huinv, hvinv]
    calc u * (u * v) * u = (u * u) * v * u := by group
      _ = v * u := by rw [← sq, hu2, one_mul]
  have hg_inv_v : v * g * v⁻¹ = g⁻¹ := by
    rw [hgdef, hvinv, mul_inv_rev, huinv, hvinv]
    calc v * (u * v) * v = v * u * (v * v) := by group
      _ = v * u := by rw [← sq, hv2, mul_one]
  have commute_of_inv : ∀ w : G, w * g * w⁻¹ = g⁻¹ → Commute w z' := by
    intro w hw
    have hsemi : SemiconjBy w g g⁻¹ := mul_inv_eq_iff_eq_mul.mp hw
    have hsp : w * g ^ s = g⁻¹ ^ s * w := hsemi.pow_right s
    have hg_inv_s : g⁻¹ ^ s = z' := by rw [inv_pow, ← hz'def]; exact hz'inv
    rw [hg_inv_s, ← hz'def] at hsp
    exact hsp
  have hu_eq : u = z' := commute_involution_eq Q hu hz'ord (commute_of_inv u hg_inv_u)
  have hv_eq : v = z' := commute_involution_eq Q hv hz'ord (commute_of_inv v hg_inv_v)
  -- then `g = u v = z'² = 1`, contradicting even order `≥ 2`
  have hg1 : g = 1 := by rw [hgdef, hu_eq, hv_eq, ← sq, hz'2]
  rw [hg1, orderOf_one] at hs
  omega

end QuaternionSylowSetup

end OddOrder.GroupTheory
