/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.GroupTheory.Commutator.Basic
import Mathlib.GroupTheory.Subgroup.Center

/-!
# Internal central products of subgroups

`OddOrder.GroupTheory` shared module: the (internal, two-factor) **central product**
of two subgroups `R₁ R₂ ≤ G`.

mathlib v4.30.0-rc2 に二因子の内部 central product 述語 `IsCentralProduct` /
`isCentralProduct` 不在を確認済 (`Mathlib/GroupTheory/` で 0 hits; mathlib が持つ
`MonoidHom.CentralProduct` 系は別概念の外部構成).

**BG §4 Thm 4.16 case (2)** (Blackburn) — `r(R) ≤ 2` の `p`-群 `R` が
`R = R₁ ∘ R₂` (`R₁` = exponent-`p` extraspecial of order `p³`, `R₂` cyclic with
`Ω₁(R₂) = R₁′`) と分解される結論 — を **記述する**ための最小述語. 後続 §5/§7 でも
`R = S ∘ C` 型分解を運ぶのに使う.

## Main definitions

* `OddOrder.GroupTheory.IsCentralProduct R R₁ R₂`: `R` は `R₁` と `R₂` の内部
  central product. すなわち `R = R₁ ⊔ R₂` かつ `⁅R₁, R₂⁆ = ⊥`
  (`R₁` の各元と `R₂` の各元が可換).

## Main results (本 module で提供, 最小)

* `IsCentralProduct.symm`: 因子を入れ替えても central product.
* `IsCentralProduct.le_left` / `le_right`: `R₁ ≤ R`, `R₂ ≤ R`.
* `IsCentralProduct.le_centralizer_right` / `le_centralizer_left`:
  `R₁ ≤ C_G(R₂)`, `R₂ ≤ C_G(R₁)` (`⁅R₁,R₂⁆ = ⊥` の両向き消費形).
* `IsCentralProduct.commute_of_mem`: `x ∈ R₁`, `y ∈ R₂ ⟹ Commute x y`.
* `IsCentralProduct.mul_mem`: `x ∈ R₁`, `y ∈ R₂ ⟹ x * y ∈ R`.
* `IsCentralProduct.inf_le_centralizer`: **overlap 補題** `R₁ ⊓ R₂ ≤ C_G(R)`.
  教科書の `R₁ ∩ R₂ ⊆ Z(R)` に対応. これは `⁅R₁,R₂⁆ = ⊥` から **導出**され,
  仮定フィールドにしてはならない (hoisting = scaffold trap).
* `IsCentralProduct.of_le_centralizer`: smart constructor — `R = R₁ ⊔ R₂` と
  `R₁ ≤ C_G(R₂)` (centralizer 形) から producing する (BG Case B-1 が自然に
  出す形). `⁅R₁,R₂⁆ = ⊥` への変換を call site から隠す.

## Design notes

* **第 2 連言 = `⁅R₁, R₂⁆ = ⊥`** を採用 (≠ `R₁ ≤ C_G(R₂)`).
  理由: (1) 対称形なので `symm` が自明 (`commutator_comm`); (2) BG Case B-1 の
  producibility — `C = C_R(S)` から `C ≤ C_G(S)`, ゆえに
  `⁅C,S⁆ = ⊥` (`commutator_eq_bot_iff_le_centralizer`), `commutator_comm` で
  `⁅S,C⁆ = ⊥` が直ちに従い, `R₁ := S, R₂ := C` のどちらを centralizer 側に
  するかの非対称に悩まない; (3) 消費は `commutator_eq_bot_iff_le_centralizer` 一発で
  centralizer 形/`Commute` 形に展開できる. `R₁ ≤ C_G(R₂)` 形と
  `commutator_eq_bot_iff_le_centralizer` で証明可換なので情報量は同一.
* `structure` 形 (Prop). 2 条件を field 化して dot-notation
  (`h.sup_eq`, `h.commutator_eq_bot`). `IsExtraspecial` と同じ流儀.
* overlap `R₁ ⊓ R₂ ≤ Z(R)` は **導出補題** `inf_le_centralizer` として提供.
  field 化すると本来不要な仮定を持ち込み, producer に立証義務を課す
  (`notes/.../scaffold-sorry-free-not-done`). 教科書 `Z(R)` (= `R` を群とみた
  中心) の subtype 版が必要なら `centralizer ↑R ⊓ R` から別途構成 (openQuestion).
* `p` prime / `[Finite G]` 仮定は def 段階で不要 (mathlib 慣用). Thm 4.16
  記述時に `[Fact p.Prime]` 等を付与.
* 将来 mathlib upstream 視野で `OddOrder/Mathlib/CentralProduct.lean` 候補.

## References

* Bender–Glauberman, _Local Analysis for the Odd Order Theorem_ (LMS LNS 188, 1994),
  §4, p. 37 (central product の定義), Thm 4.16 (Blackburn) case (2), Lem 4.15.

## Audit context

BG §4 Thm 4.16 着手 (issue 0051, 2026-05-30) の前提 shared module.
設計メモは `notes/bg/s04_thm416_handoff.md`.
-/

namespace OddOrder.GroupTheory

open scoped commutatorElement

variable {G : Type*} [Group G]

/-- **Internal central product** of two subgroups: `R` is the central product
`R₁ ∘ R₂` when `R = R₁ ⊔ R₂` (the join generates `R`) and `⁅R₁, R₂⁆ = ⊥`
(every element of `R₁` commutes with every element of `R₂`).

これは BG §4, p. 37 の二因子版 `G = G₁ ∘ G₂`. BG は `Gᵢ ⊴ G` も課すが,
`R = R₁ ⊔ R₂` のもとでは `⁅R₁,R₂⁆ = ⊥ ⟹ R₁, R₂ ⊴ R` が従う
(各因子はもう一方を中心化し自身を正規化するので join 内で正規) ので,
最小述語としては normality を field に持たない. 必要なら別補題で供給する. -/
structure IsCentralProduct (R R₁ R₂ : Subgroup G) : Prop where
  /-- `R` is generated by the two factors: `R = R₁ ⊔ R₂`. -/
  sup_eq : R = R₁ ⊔ R₂
  /-- The two factors commute elementwise: `⁅R₁, R₂⁆ = ⊥`. -/
  commutator_eq_bot : ⁅R₁, R₂⁆ = ⊥

namespace IsCentralProduct

variable {R R₁ R₂ : Subgroup G}

/-- Swapping the two factors preserves the central-product structure:
`R = R₁ ∘ R₂ ⟹ R = R₂ ∘ R₁`.

`R = R₁ ⊔ R₂ = R₂ ⊔ R₁` by `sup_comm`, and `⁅R₂,R₁⁆ = ⁅R₁,R₂⁆ = ⊥` by
`Subgroup.commutator_comm`. -/
theorem symm (h : IsCentralProduct R R₁ R₂) : IsCentralProduct R R₂ R₁ where
  sup_eq := h.sup_eq.trans (sup_comm R₁ R₂)
  commutator_eq_bot := (Subgroup.commutator_comm R₂ R₁).trans h.commutator_eq_bot

/-- The first factor is contained in the product: `R₁ ≤ R`. -/
theorem le_left (h : IsCentralProduct R R₁ R₂) : R₁ ≤ R :=
  h.sup_eq ▸ le_sup_left

/-- The second factor is contained in the product: `R₂ ≤ R`. -/
theorem le_right (h : IsCentralProduct R R₁ R₂) : R₂ ≤ R :=
  h.sup_eq ▸ le_sup_right

/-- The first factor centralizes the second: `R₁ ≤ C_G(R₂)`.

This is the consumption form of `⁅R₁, R₂⁆ = ⊥` via
`Subgroup.commutator_eq_bot_iff_le_centralizer`. -/
theorem le_centralizer_right (h : IsCentralProduct R R₁ R₂) :
    R₁ ≤ Subgroup.centralizer (R₂ : Set G) :=
  Subgroup.commutator_eq_bot_iff_le_centralizer.mp h.commutator_eq_bot

/-- The second factor centralizes the first: `R₂ ≤ C_G(R₁)`. -/
theorem le_centralizer_left (h : IsCentralProduct R R₁ R₂) :
    R₂ ≤ Subgroup.centralizer (R₁ : Set G) :=
  Subgroup.le_centralizer_iff.mp h.le_centralizer_right

/-- Elements of the two factors commute: `x ∈ R₁`, `y ∈ R₂ ⟹ Commute x y`. -/
theorem commute_of_mem (h : IsCentralProduct R R₁ R₂) {x y : G}
    (hx : x ∈ R₁) (hy : y ∈ R₂) : Commute x y :=
  (Subgroup.mem_centralizer_iff.mp (h.le_centralizer_right hx) y hy).symm

/-- A product of a first-factor element and a second-factor element lands in `R`:
`x ∈ R₁`, `y ∈ R₂ ⟹ x * y ∈ R`. -/
theorem mul_mem (h : IsCentralProduct R R₁ R₂) {x y : G}
    (hx : x ∈ R₁) (hy : y ∈ R₂) : x * y ∈ R :=
  h.sup_eq ▸ Subgroup.mul_mem_sup hx hy

/-- **Overlap lemma** (derived, not assumed): the intersection of the two factors
centralizes the whole product, `R₁ ⊓ R₂ ≤ C_G(R)`.

This is the formal content of the textbook statement `R₁ ∩ R₂ ⊆ Z(R)` (BG §4):
an element `g` lying in both factors commutes with every `a ∈ R₁` (since `g ∈ R₂`)
and every `b ∈ R₂` (since `g ∈ R₁`), hence with every product `a * b`, and
`R = R₁ ⊔ R₂` is generated by such products.

Crucially this is *proved* from `commutator_eq_bot`, so it is **not** a hypothesis
field of `IsCentralProduct`: putting it in the structure would hoist a derivable
fact into an undischarged obligation on every producer (scaffold trap). -/
theorem inf_le_centralizer (h : IsCentralProduct R R₁ R₂) :
    R₁ ⊓ R₂ ≤ Subgroup.centralizer (R : Set G) := by
  intro g hg
  obtain ⟨hg₁, hg₂⟩ := hg
  -- It suffices to show that `R` is contained in the centralizer of `g`,
  -- i.e. `R ≤ C_G({g})`. Each factor lies in `C_G({g})`: `g ∈ R₂` centralizes `R₁`,
  -- and `g ∈ R₁` centralizes `R₂`. Since `R = R₁ ⊔ R₂` and `C_G({g})` is a subgroup,
  -- the join is contained in it. (`Subgroup.mem_sup` is unavailable for
  -- noncommutative `G`, so we reason through the subgroup-lattice `sup_le`.)
  have hsub : R ≤ Subgroup.centralizer ({g} : Set G) := by
    rw [h.sup_eq, sup_le_iff]
    constructor
    · -- `R₁ ≤ C_G({g})`: every `a ∈ R₁` commutes with `g` (as `g ∈ R₂`).
      intro a ha
      rw [Subgroup.mem_centralizer_singleton_iff]
      exact h.commute_of_mem ha hg₂
    · -- `R₂ ≤ C_G({g})`: every `b ∈ R₂` commutes with `g` (as `g ∈ R₁`).
      intro b hb
      rw [Subgroup.mem_centralizer_singleton_iff]
      exact (h.commute_of_mem hg₁ hb).symm
  -- `g` centralizes every element of `R` because `R ≤ C_G({g})`.
  rw [Subgroup.mem_centralizer_iff]
  intro r hr
  exact Subgroup.mem_centralizer_singleton_iff.mp (hsub hr)

/-- **Smart constructor** from the centralizer side: if `R = R₁ ⊔ R₂` and
`R₁ ≤ C_G(R₂)`, then `R` is the central product `R₁ ∘ R₂`.

BG Case B-1 most naturally supplies `C ≤ C_G(S)` (from `C = C_R(S)`), so producing
`IsCentralProduct` from the centralizer hypothesis (rather than re-deriving
`⁅R₁, R₂⁆ = ⊥` at the call site) is the ergonomic entry point. The conversion is
`Subgroup.commutator_eq_bot_iff_le_centralizer`. -/
theorem of_le_centralizer (hsup : R = R₁ ⊔ R₂)
    (hcent : R₁ ≤ Subgroup.centralizer (R₂ : Set G)) : IsCentralProduct R R₁ R₂ where
  sup_eq := hsup
  commutator_eq_bot := Subgroup.commutator_eq_bot_iff_le_centralizer.mpr hcent

end IsCentralProduct

end OddOrder.GroupTheory
