/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.Algebra.Module.ZMod
import Mathlib.Algebra.Module.Equiv.Basic
import Mathlib.LinearAlgebra.GeneralLinearGroup.Basic

/-!
# An elementary abelian `p`-group is a vector space, and its automorphisms are linear

For a commutative group `E` of exponent dividing `n`, `Additive E` carries a
`ZMod n`-module structure (`AddCommGroup.zmodModule`), and — because every additive map
between `ZMod n`-modules is automatically `ZMod n`-linear (`ZMod.map_smul`) — the
automorphism group of `E` *is* the linear group:

`MulAut E ≃* (Additive E ≃ₗ[ZMod n] Additive E)`.

For `n = 2` this identifies `Aut(E)` of an elementary abelian `2`-group with `GL(E)` over
`𝔽₂`, which is what Isaacs Problem 8C.6 is about.

The module structure is taken as an instance *argument* rather than derived inside each
statement: `AddCommGroup.zmodModule` is a `reducible non-instance`, so a caller supplies it
with `letI := AddCommGroup.zmodModule h` and then everything below applies.
`zmodModule_of_pow_eq_one` packages the exponent hypothesis into the shape it wants.

## Main results

* `OddOrder.GroupTheory.zmodModule_of_pow_eq_one` — the module structure from `x ^ n = 1`.
* `OddOrder.GroupTheory.mulAutEquivLinearEquiv` — `MulAut E ≃* (Additive E ≃ₗ[ZMod n] _)`,
  with `mulAutEquivLinearEquiv_apply` for the forward direction.
-/

set_option autoImplicit false

namespace OddOrder.GroupTheory

variable {n : ℕ} {E : Type*} [CommGroup E]

/-- **A commutative group of exponent dividing `n` is a `ZMod n`-module.**

`AddCommGroup.zmodModule` in multiplicative notation; the `n`-torsion hypothesis is the
exponent condition read through `Additive`. -/
abbrev zmodModule_of_pow_eq_one (h : ∀ x : E, x ^ n = 1) : Module (ZMod n) (Additive E) :=
  AddCommGroup.zmodModule (n := n) (G := Additive E) fun x => by
    have hx : (Additive.toMul x) ^ n = 1 := h _
    have hax := congrArg Additive.ofMul hx
    rw [ofMul_pow] at hax
    exact hax

variable [Module (ZMod n) (Additive E)]

/-- **The automorphisms of a `ZMod n`-module group are exactly its linear automorphisms.**

Every additive map between `ZMod n`-modules is `ZMod n`-linear (`ZMod.map_smul`), because
the scalars are generated by `1`; so passing to `Additive` loses nothing. -/
def mulAutEquivLinearEquiv : MulAut E ≃* (Additive E ≃ₗ[ZMod n] Additive E) where
  toFun φ :=
    { MulEquiv.toAdditive φ with
      map_smul' := fun c x => ZMod.map_smul (MulEquiv.toAdditive φ) c x }
  invFun ψ := MulEquiv.toAdditive.symm ψ.toAddEquiv
  left_inv _ := by ext; rfl
  right_inv _ := by ext; rfl
  map_mul' _ _ := by ext; rfl

@[simp]
theorem mulAutEquivLinearEquiv_apply (φ : MulAut E) (x : E) :
    (mulAutEquivLinearEquiv (n := n) φ) (Additive.ofMul x) = Additive.ofMul (φ x) := rfl

/-- **群作用から `ZMod n`-線形表現へ.** `A` が可換で指数が `n` を割るとき, 作用
`φ : G →* MulAut A` は `Additive A` 上の `ZMod n`-線形表現を定める
(`mulAutEquivLinearEquiv` で線形同型に移し, 単元群から `End` へ落とす).

Maschke (`MonoidAlgebra.Submodule.exists_isCompl`) を当てるための入口. -/
noncomputable def linearOfMulAutHom {G : Type*} [Group G] (φ : G →* MulAut E) :
    G →* (Additive E) →ₗ[ZMod n] (Additive E) :=
  (Units.coeHom (Module.End (ZMod n) (Additive E))).comp
    (((LinearMap.GeneralLinearGroup.generalLinearEquiv (ZMod n)
        (Additive E)).symm.toMonoidHom).comp
      ((mulAutEquivLinearEquiv (n := n) (E := E)).toMonoidHom.comp φ))

@[simp]
theorem linearOfMulAutHom_apply {G : Type*} [Group G] (φ : G →* MulAut E) (g : G) (x : E) :
    linearOfMulAutHom (n := n) φ g (Additive.ofMul x) = Additive.ofMul (φ g x) := rfl

/-- 指数が `n` を割る可換群では, **部分群と `ZMod n`-部分加群が順序同型で対応する**
(`Subgroup.toAddSubgroup` と mathlib の `AddSubgroup.toZModSubmodule` の合成).

`⊓`, `⊔`, `⊥` を保つので, Maschke で得た補元をそのまま部分群の言葉に戻せる. -/
def subgroupOrderIsoSubmodule : Subgroup E ≃o Submodule (ZMod n) (Additive E) :=
  Subgroup.toAddSubgroup.trans (AddSubgroup.toZModSubmodule n)

@[simp]
theorem mem_subgroupOrderIsoSubmodule {S : Subgroup E} {x : E} :
    Additive.ofMul x ∈ subgroupOrderIsoSubmodule (n := n) S ↔ x ∈ S := Iff.rfl

/-! ## 正規部分群への共役作用 -/

/-- 正規部分群への共役作用は中心化群を殺す. -/
theorem conjNormal_eq_one_of_mem_centralizer {G : Type*} [Group G] {N : Subgroup G} [N.Normal]
    {g : G} (hg : g ∈ Subgroup.centralizer (N : Set G)) :
    (MulAut.conjNormal g : MulAut ↥N) = 1 := by
  ext h
  rw [MulAut.conjNormal_apply]
  have hcomm := (Subgroup.mem_centralizer_iff.mp hg) (h : G) h.2
  calc (g : G) * (h : G) * g⁻¹ = ((h : G) * g) * g⁻¹ := by rw [hcomm]
    _ = (h : G) := by group

/-- 共役不変な `Subgroup ↥N` は `G` の正規部分群を与える. -/
theorem normal_map_subtype_of_conj_invariant {G : Type*} [Group G] {N : Subgroup G} [N.Normal]
    {S : Subgroup ↥N} (hS : ∀ (g : G) (x : ↥N), x ∈ S → MulAut.conjNormal g x ∈ S) :
    (S.map N.subtype).Normal := by
  refine ⟨fun x hx g => ?_⟩
  obtain ⟨s, hs, rfl⟩ := Subgroup.mem_map.mp hx
  exact Subgroup.mem_map.mpr ⟨MulAut.conjNormal g s, hS g s hs, MulAut.conjNormal_apply g s⟩

/-- 逆に, `G`-正規で `N` に含まれる部分群は共役不変な `Subgroup ↥N` を与える. -/
theorem conj_invariant_subgroupOf {G : Type*} [Group G] {N : Subgroup G} [N.Normal]
    {M : Subgroup G} [M.Normal] (g : G) (x : ↥N) (hx : x ∈ M.subgroupOf N) :
    MulAut.conjNormal g x ∈ M.subgroupOf N := by
  have : ((MulAut.conjNormal g x : ↥N) : G) = g * (x : G) * g⁻¹ := MulAut.conjNormal_apply g x
  rw [Subgroup.mem_subgroupOf, this]
  exact ‹M.Normal›.conj_mem _ hx g

open scoped IsMulCommutative in
/-- **`N ◁ G` が可換なら, 共役作用は `G ⧸ C_G(N)` の `ZMod n`-線形表現を定める.**

Maschke (`MonoidAlgebra.Submodule.exists_isCompl`) は `p ∤ |G ⧸ C_G(N)|` のときに
この表現へ適用できる. -/
noncomputable def conjQuotientLinear {G : Type*} [Group G] {N : Subgroup G} [N.Normal]
    [IsMulCommutative ↥N] {n : ℕ} [Module (ZMod n) (Additive ↥N)] :
    (G ⧸ Subgroup.centralizer (N : Set G)) →*
      (Additive ↥N) →ₗ[ZMod n] (Additive ↥N) :=
  linearOfMulAutHom
    (QuotientGroup.lift (Subgroup.centralizer (N : Set G)) MulAut.conjNormal
      fun _ hg => conjNormal_eq_one_of_mem_centralizer hg)

open scoped IsMulCommutative in
@[simp]
theorem conjQuotientLinear_apply {G : Type*} [Group G] {N : Subgroup G} [N.Normal]
    [IsMulCommutative ↥N] {n : ℕ} [Module (ZMod n) (Additive ↥N)] (g : G) (x : ↥N) :
    conjQuotientLinear (n := n) (QuotientGroup.mk g) (Additive.ofMul x)
      = Additive.ofMul (MulAut.conjNormal g x) := rfl

end OddOrder.GroupTheory
