/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.GroupTheory.PRank
import OddOrder.GroupTheory.CriticalSubgroup

/-!
# Narrow p-Groups

`OddOrder.GroupTheory` shared module: the **narrow** `p`-group predicate `IsNarrow`
(Bender–Glauberman, _Local Analysis for the Odd Order Theorem_, §1 p.2 / §5 p.44).

This is a cross-cutting concept used by BG §5 (narrow `p`-groups proper) and cited in
§6/§10/§16 and Peterfalvi §9, so it lives in the shared `GroupTheory` namespace alongside
`pRank`, `Omega`, `SCN` rather than in a single `BG` section file.

## Main definitions

* `OddOrder.GroupTheory.IsNarrow p R`: a `p`-group `R` is *narrow* iff `r(R) ≤ 2`
  (`pRank R p ≤ 2`) **or** there is an order-`p` subgroup `R₀` whose centralizer is
  generated by `R₀` and a cyclic subgroup `R₁`, with `R₀ ∩ R₁ = 1` (BG
  `C_R(R₀) = R₀ × R₁`).

## Main results

* `OddOrder.GroupTheory.isNarrow_of_pRank_le_two`: `pRank R p ≤ 2 → IsNarrow p R`.

## References

* Bender, Glauberman, _Local Analysis for the Odd Order Theorem_ (LMS LNS 188, 1994),
  Chapter I §1 (p.2), §5 (p.44), mmd `references/bg/local-analysis.mmd` L354, L1789.
-/

namespace OddOrder.GroupTheory

/-- **BG narrow `p`-group** (§1 p.2 / §5 p.44). For a prime `p`, a `p`-group `R` is
*narrow* iff `r(R) ≤ 2` (`pRank R p ≤ 2`) or there is an order-`p` subgroup `R₀` whose
centralizer is generated by `R₀` and a cyclic subgroup `R₁`, with `R₀ ∩ R₁ = 1`.

The internal direct product `C_R(R₀) = R₀ × R₁` is encoded inside the centralizer by
`R₀ ⊓ R₁ = ⊥` and `Subgroup.centralizer R₀ = R₀ ⊔ R₁`. We deliberately do not use
`Subgroup.IsComplement' R₀ R₁`, since that would make `R₀` and `R₁` complements in the
ambient group `R`, forcing `R₀ ⊔ R₁ = ⊤` rather than only filling `C_R(R₀)`. The naïve
form `pRank R p ≤ 2` is used for `r(R) ≤ 2`; BG Theorem 5.3 / Corollary 5.4 supply the
equivalent characterisations when `r(R) ≥ 3`. -/
def IsNarrow (p : ℕ) (R : Type*) [Group R] : Prop :=
  pRank R p ≤ 2 ∨
    ∃ R₀ R₁ : Subgroup R, Nat.card R₀ = p ∧ IsCyclic R₁ ∧
      R₀ ⊓ R₁ = ⊥ ∧ Subgroup.centralizer (R₀ : Set R) = R₀ ⊔ R₁

/-- A `p`-group of rank at most `2` is narrow (the first disjunct of `IsNarrow`). -/
theorem isNarrow_of_pRank_le_two {p : ℕ} {R : Type*} [Group R] (h : pRank R p ≤ 2) :
    IsNarrow p R :=
  Or.inl h

/-- **`IsNarrow` is invariant under group isomorphism**: transport the rank bound or the
narrow witness `(R₀, R₁)` along `e : R ≃* R'`. Used to move narrowness between a Sylow
subgroup and its isomorphic images (BG Thm 5.6: `S ≅ S̄ ≤ G/O_{p'}(G)`,
`S̄ = O_p(Ḡ)`). -/
theorem IsNarrow.of_mulEquiv {p : ℕ} {R R' : Type*} [Group R] [Group R'] [Finite R]
    (e : R ≃* R') (h : IsNarrow p R) : IsNarrow p R' := by
  haveI : Finite R' := Finite.of_equiv R e.toEquiv
  rcases h with hrank | ⟨R₀, R₁, hcard, hcyc, hinf, hcent⟩
  · exact Or.inl (le_trans
      (pRank_le_of_injective (f := e.symm.toMonoidHom) e.symm.injective) hrank)
  · refine Or.inr ⟨R₀.map e.toMonoidHom, R₁.map e.toMonoidHom, ?_, ?_, ?_, ?_⟩
    · rw [← hcard]
      exact (Nat.card_congr
        (Subgroup.equivMapOfInjective R₀ e.toMonoidHom e.injective).toEquiv).symm
    · haveI := hcyc
      exact isCyclic_of_surjective _ (e.toMonoidHom.subgroupMap_surjective R₁)
    · rw [← Subgroup.map_inf R₀ R₁ e.toMonoidHom e.injective, hinf, Subgroup.map_bot]
    · have hmap_cent :
          Subgroup.centralizer ((R₀.map e.toMonoidHom : Subgroup R') : Set R') =
            (Subgroup.centralizer (R₀ : Set R)).map e.toMonoidHom := by
        ext x
        constructor
        · intro hx
          have hx' := Subgroup.mem_centralizer_iff.mp hx
          refine ⟨e.symm x, ?_, by simp⟩
          rw [SetLike.mem_coe, Subgroup.mem_centralizer_iff]
          intro r hr
          apply e.injective
          rw [map_mul, map_mul]
          simp only [MulEquiv.apply_symm_apply]
          exact hx' (e r) ⟨r, hr, rfl⟩
        · rintro ⟨y, hy, rfl⟩
          rw [SetLike.mem_coe, Subgroup.mem_centralizer_iff] at hy
          rw [Subgroup.mem_centralizer_iff]
          rintro _ ⟨r, hr, rfl⟩
          rw [← map_mul, ← map_mul, hy r hr]
      rw [hmap_cent, hcent, Subgroup.map_sup]

/-- **`E*(R)`: maximal elementary abelian subgroup** (BG §5 p.45). A subgroup `E ≤ R` is
`p`-elementary abelian and is contained in no strictly larger `p`-elementary abelian
subgroup of `R`.

The "no larger" condition is phrased as: any `p`-elementary abelian `F` with `E ≤ F`
satisfies `F = E`. BG's `E²(R) ∩ E*(R)` (elementary abelian of order `p²` not contained
in any `E_{p³}`) is expressed at use sites as
`Nat.card E = p ^ 2 ∧ IsMaximalElementaryAbelian p E` (no separate abbreviation). -/
def IsMaximalElementaryAbelian (p : ℕ) {R : Type*} [Group R] (E : Subgroup R) : Prop :=
  E.IsElementaryAbelian p ∧
    ∀ F : Subgroup R, F.IsElementaryAbelian p → E ≤ F → F = E

namespace IsMaximalElementaryAbelian

variable {p : ℕ} {R : Type*} [Group R] {E F : Subgroup R}

/-- A maximal elementary abelian subgroup is, in particular, elementary abelian. -/
theorem isElementaryAbelian (h : IsMaximalElementaryAbelian p E) : E.IsElementaryAbelian p :=
  h.1

/-- Maximality: any `p`-elementary abelian `F ⊇ E` collapses back to `E`. -/
theorem eq_of_le (h : IsMaximalElementaryAbelian p E) (hF : F.IsElementaryAbelian p)
    (hEF : E ≤ F) : F = E :=
  h.2 F hF hEF

/-- If an elementary abelian subgroup `F` centralizes a maximal elementary abelian
subgroup `E`, then adjoining `F` to `E` adds nothing. -/
theorem sup_eq_left_of_le_centralizer (h : IsMaximalElementaryAbelian p E)
    (hF : F.IsElementaryAbelian p) (hEF : E ≤ Subgroup.centralizer (F : Set R)) :
    E ⊔ F = E :=
  h.eq_of_le
    (Subgroup.IsElementaryAbelian.sup_of_le_centralizer h.isElementaryAbelian hF hEF)
    le_sup_left

/-- If an elementary abelian subgroup `F` centralizes a maximal elementary abelian
subgroup `E`, then `F ≤ E`. -/
theorem le_of_le_centralizer (h : IsMaximalElementaryAbelian p E)
    (hF : F.IsElementaryAbelian p) (hEF : E ≤ Subgroup.centralizer (F : Set R)) :
    F ≤ E := by
  have hsup : E ⊔ F = E := h.sup_eq_left_of_le_centralizer hF hEF
  intro x hx
  rw [← hsup]
  exact (le_sup_right : F ≤ E ⊔ F) hx

end IsMaximalElementaryAbelian

/-- **Existence of a maximal elementary abelian subgroup above a given one** (used by
BG Theorem 5.3 ⇐). In a finite group, every `p`-elementary abelian subgroup `E` is
contained in some `E* ∈ E*(R)`, i.e. a `p`-elementary abelian subgroup maximal under
inclusion.

This is a pure finite-poset maximality statement: take a `≤`-maximal element of the
finite subgroup lattice among the `p`-elementary abelian subgroups containing `E`
(`Finite.exists_le_maximal`); the maximality witness upgrades to
`IsMaximalElementaryAbelian` via antisymmetry. -/
theorem exists_maximalElementaryAbelian_ge
    {p : ℕ} {R : Type*} [Group R] [Finite R] {E : Subgroup R}
    (hE : E.IsElementaryAbelian p) :
    ∃ F : Subgroup R, E ≤ F ∧ IsMaximalElementaryAbelian p F := by
  obtain ⟨F, hEF, hFmax⟩ :=
    Finite.exists_le_maximal (p := fun F : Subgroup R => F.IsElementaryAbelian p) hE
  exact ⟨F, hEF, hFmax.1, fun G hG hFG => le_antisymm (hFmax.2 hG hFG) hFG⟩

/-! ## `W = Ω₁(Z₂(R))` (BG Lemma 4.5, exp-`p` half)

For an odd `p`-group `R`, BG Lemma 4.5 studies `W = Ω₁(Z₂(R))`, the order-`p`
elements of the second centre `Z₂(R) = upperCentralSeries R 2`. Since `Z₂(R)` has
class `≤ 2` (`⁅Z₂, Z₂⁆ ≤ Z₁ = Z(R)`), the exponent-`p` half of Lemma 4.5(c) follows
from `Omega.pow_eq_one_of_class_le_two`: every element of `W` has `p`-th power `1`.

`Z₂(R)` is in general **non-abelian** (it has class `≤ 2`, not `≤ 1`), so `W` is
built with the `omega1Map` template (`OmegaSubgroup` / `CriticalSubgroup`): take
`Ω₁` of the subtype `↥Z₂(R)`, then map back along `Z₂(R).subtype`. The noncyclic
half of Lemma 4.5(c) is **not** proved here (it needs the general Lemma 4.5(a)). -/

section Omega1UpperCentralTwo

open scoped commutatorElement

/-- **BG Lemma 4.5** `W = Ω₁(Z₂(R))`. For a prime `p`, the subgroup of `R` generated
by the order-`p` elements of the second centre `Z₂(R) = upperCentralSeries R 2`,
realised as the image of `Ω₁(↥Z₂(R))` under `Z₂(R).subtype` (the `omega1Map`
template, since `Z₂(R)` is generally non-abelian). -/
def omega1UpperCentralTwo (R : Type*) [Group R] (p : ℕ) : Subgroup R :=
  (Omega ↥(Subgroup.upperCentralSeries R 2) p 1).map (Subgroup.upperCentralSeries R 2).subtype

/-- `W = Ω₁(Z₂(R)) ≤ Z₂(R)`. -/
theorem omega1UpperCentralTwo_le (R : Type*) [Group R] (p : ℕ) :
    omega1UpperCentralTwo R p ≤ Subgroup.upperCentralSeries R 2 :=
  Subgroup.map_subtype_le _

/-- `W = Ω₁(Z₂(R))` is characteristic in `R` (char-in-char: `Ω₁` is characteristic
in `Z₂(R)`, `Z₂(R)` is characteristic in `R`). -/
instance omega1UpperCentralTwo_characteristic {R : Type*} [Group R] {p : ℕ} :
    (omega1UpperCentralTwo R p).Characteristic :=
  characteristic_map_subtype_of_characteristic inferInstance Omega.characteristic

/-- `Z₂(R) = upperCentralSeries R 2` has class `≤ 2`: `⁅Z₂, Z₂⁆ ≤ Z(↥Z₂)`.

For `x, y ∈ Z₂(R) = upperCentralSeries R 2`, `mem_upperCentralSeries_succ_iff` (with
`n = 1`) gives `⁅x, y⁆ = x * y * x⁻¹ * y⁻¹ ∈ upperCentralSeries R 1 = Z(R)`, so
`⁅x, y⁆` commutes with all of `R`, in particular centralises `Z₂(R)`. Translating
along `Z₂(R).subtype` yields the claim. -/
theorem commutator_upperCentralSeries_two_le_center {R : Type*} [Group R] :
    _root_.commutator ↥(Subgroup.upperCentralSeries R 2) ≤
      Subgroup.center ↥(Subgroup.upperCentralSeries R 2) := by
  set Z := Subgroup.upperCentralSeries R 2 with hZ
  -- `⁅Z, Z⁆ ≤ Z(R)`: for `x, y ∈ Z = upperCentralSeries R 2`, `⁅x, y⁆ ∈ Z(R)`.
  have hZZ_le_center : ⁅Z, Z⁆ ≤ Subgroup.center R := by
    rw [Subgroup.commutator_le]
    intro x hx y _
    -- `x ∈ upperCentralSeries R (1 + 1)` ⇒ `⁅x, y⁆ ∈ upperCentralSeries R 1`.
    have hmem : ⁅x, y⁆ ∈ Subgroup.upperCentralSeries R 1 :=
      Subgroup.mem_upperCentralSeries_succ_iff.mp hx y
    rwa [Subgroup.upperCentralSeries_one] at hmem
  -- `Z(R)` centralises everything, so `⁅Z, Z⁆ ≤ centralizer (Z : Set R)`.
  have hZZ_cent : ⁅Z, Z⁆ ≤ Subgroup.centralizer (Z : Set R) := by
    intro x hx
    rw [Subgroup.mem_centralizer_iff]
    intro w _
    exact Subgroup.mem_center_iff.mp (hZZ_le_center hx) w
  -- Translate `⁅Z, Z⁆ ≤ centralizer Z` to `commutator ↥Z ≤ center ↥Z`.
  rw [← Z.map_subtype_le_map_subtype, Z.map_subtype_commutator]
  intro x hx
  have hxZ : x ∈ Z := Z.commutator_le_self hx
  rw [Subgroup.mem_map]
  refine ⟨⟨x, hxZ⟩, ?_, rfl⟩
  rw [Subgroup.mem_center_iff]
  intro k
  apply Subtype.ext
  rw [Subgroup.coe_mul, Subgroup.coe_mul]
  exact Subgroup.mem_centralizer_iff.mp (hZZ_cent hx) (k : R) k.2

/-- **BG Lemma 4.5(c)** (exponent-`p` half). For odd `p`, every element of
`W = Ω₁(Z₂(R))` has `p`-th power `1`. -/
theorem pow_eq_one_of_mem_omega1UpperCentralTwo
    {R : Type*} [Group R] {p : ℕ} (hp_odd : Odd p) {g : R}
    (hg : g ∈ omega1UpperCentralTwo R p) : g ^ p = 1 := by
  rw [omega1UpperCentralTwo, Subgroup.mem_map] at hg
  obtain ⟨z, hz, rfl⟩ := hg
  have hzp : z ^ p = 1 :=
    Omega.pow_eq_one_of_class_le_two hp_odd commutator_upperCentralSeries_two_le_center hz
  rw [Subgroup.coe_subtype, ← Subgroup.coe_pow, hzp, Subgroup.coe_one]

/-! ### `T = C_R(W)`: basic properties (BG §5, used in Theorem 5.3 (c)(d))

`T = C_R(W) = Subgroup.centralizer (Ω₁(Z₂(R)))`. Three basic facts hold for any
`p`-group: `T` is characteristic (centralizer of the characteristic `W`),
`Z(R) ⊆ T` (the centre centralises everything), and `R' ⊆ T`. The last one is a
three-subgroups argument from `W ≤ Z₂(R)`: both `[W,R]` and `[R,W]` lie in `Z(R)`,
so `[[R,R],W]=1`. -/

/-- **`T = C_R(W)` is characteristic** (BG §5). The centralizer of the
characteristic subgroup `W = Ω₁(Z₂(R))` is characteristic
(`Subgroup.characteristic_centralizer` + `omega1UpperCentralTwo_characteristic`). -/
instance centralizer_omega1UpperCentralTwo_characteristic
    {R : Type*} [Group R] {p : ℕ} :
    (Subgroup.centralizer (omega1UpperCentralTwo R p : Set R)).Characteristic :=
  Subgroup.characteristic_centralizer

/-- `Z(R) ⊆ T = C_R(W)` (BG §5): the centre centralises every subset, in
particular `W = Ω₁(Z₂(R))` (`Subgroup.center_le_centralizer`). -/
theorem center_le_centralizer_omega1UpperCentralTwo
    {R : Type*} [Group R] {p : ℕ} :
    Subgroup.center R ≤ Subgroup.centralizer (omega1UpperCentralTwo R p : Set R) :=
  Subgroup.center_le_centralizer _

/-- `R' ⊆ T = C_R(W)` (BG §5, mmd L1862), where `W = Ω₁(Z₂(R))`.

This only uses `W ≤ Z₂(R)`: for `w ∈ W`, the defining property of `Z₂(R)` gives
`[w,R] ≤ Z(R)`, hence also `[R,w] ≤ Z(R)`. The three-subgroups lemma then gives
`[[R,R],W]=1`, i.e. the commutator subgroup centralizes `W`. -/
theorem commutator_le_centralizer_omega1UpperCentralTwo
    {R : Type*} [Group R] {p : ℕ} :
    _root_.commutator R ≤ Subgroup.centralizer (omega1UpperCentralTwo R p : Set R) := by
  let W : Subgroup R := omega1UpperCentralTwo R p
  have hW_top_center : ⁅W, (⊤ : Subgroup R)⁆ ≤ Subgroup.center R := by
    rw [Subgroup.commutator_le]
    intro x hx y _
    have hxZ2 : x ∈ Subgroup.upperCentralSeries R 2 := omega1UpperCentralTwo_le R p hx
    have hmem : ⁅x, y⁆ ∈ Subgroup.upperCentralSeries R 1 :=
      Subgroup.mem_upperCentralSeries_succ_iff.mp hxZ2 y
    rwa [Subgroup.upperCentralSeries_one] at hmem
  have htop_W_center : ⁅(⊤ : Subgroup R), W⁆ ≤ Subgroup.center R := by
    rw [Subgroup.commutator_comm]
    exact hW_top_center
  have hW_top_top : ⁅⁅W, (⊤ : Subgroup R)⁆, (⊤ : Subgroup R)⁆ = ⊥ :=
    Subgroup.commutator_eq_bot_iff_le_centralizer.mpr
      (hW_top_center.trans (Subgroup.center_le_centralizer _))
  have htop_W_top : ⁅⁅(⊤ : Subgroup R), W⁆, (⊤ : Subgroup R)⁆ = ⊥ :=
    Subgroup.commutator_eq_bot_iff_le_centralizer.mpr
      (htop_W_center.trans (Subgroup.center_le_centralizer _))
  have hderived_W : ⁅⁅(⊤ : Subgroup R), (⊤ : Subgroup R)⁆, W⁆ = ⊥ :=
    Subgroup.commutator_commutator_eq_bot_of_rotate htop_W_top hW_top_top
  rw [_root_.commutator_def]
  exact Subgroup.commutator_eq_bot_iff_le_centralizer.mp hderived_W

end Omega1UpperCentralTwo

end OddOrder.GroupTheory
