/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.Algebra.Group.Subgroup.Basic
import Mathlib.Algebra.Group.Subgroup.Map

/-!
# Omega Subgroups

`OddOrder.GroupTheory` shared module: 'Omega subgroup' Ω_n(G) の概念.

mathlib v4.29.1 に `Omega1` / `Omega` / `omega1` / `omegaSubgroup` 不在を確認済
(0 hits across `Mathlib/GroupTheory/`).

**BG §1 Thm 1.11 (Ω₁ fixed under coprime auto ⇒ trivial)**, **BG §1 Cor 1.12**,
**BG §1 Thm 1.13 (Thompson critical)**, **BG §4 全節 (rank theory)**,
**BG §5 全節 (narrow p-groups)**, **Isaacs Thm 4.36 (Ch.4 §4D)** で必要.

## Main definitions

* `OddOrder.GroupTheory.Omega p n G`: 部分群 `⟨g ∈ G : g^(p^n) = 1⟩` (i.e. `Subgroup.closure
  {g : G | g^(p^n) = 1}`). For abelian p-group it agrees with the set `{g : g^(p^n) = 1}`.

## Main results (本 module で提供, 最小)

* `Omega.subset_closure_of_pow_eq_one`: `g^(p^n) = 1 ⇒ g ∈ Omega p n G`.
* `Omega.mono`: `m ≤ n ⇒ Omega p m G ≤ Omega p n G`.

## Design notes

* `Subgroup.closure` 形 (一般 G, abelian 仮定なし). abelian の場合の
  `g ∈ Omega p n G ↔ g^(p^n) = 1` 同値は補強で.
* `p` prime 仮定は def 段階では不要. 主結果記述時に `[Fact p.Prime]` 付与.
* characteristic / normal 性質 (Aut G で不変) は補強で.
* 将来 mathlib upstream 視野で `OddOrder/Mathlib/OmegaSubgroup.lean` 候補.

## References

* BG §1, §4, §5.
* Isaacs FGT Ch.4 §4D, Thm 4.36.

## Audit context

Phase 2a 第 1 波 audit 2026-05-23 で新規 shared module 候補として確定.
詳細は `notes/meta/bg_phase2a_wave1_audit_2026_05_23.md`.
-/

namespace OddOrder.GroupTheory

variable (G : Type*) [Group G]

/-- **Omega subgroup** `Ω_n(G)` at prime `p`:
the subgroup of `G` generated by all elements `g` with `g^(p^n) = 1`.

For abelian `p`-groups, this equals the set `{g : g^(p^n) = 1}`. For non-abelian
groups, the generated subgroup is generally larger than this set. -/
def Omega (p n : ℕ) : Subgroup G :=
  Subgroup.closure {g : G | g ^ (p ^ n) = 1}

variable {G}

namespace Omega

variable {p n : ℕ}

/-- An element `g` with `g^(p^n) = 1` is in `Omega p n G`. -/
theorem mem_of_pow_eq_one {g : G} (hg : g ^ (p ^ n) = 1) : g ∈ Omega G p n :=
  Subgroup.subset_closure hg

/-- Monotonicity: `Omega p m G ≤ Omega p n G` whenever `m ≤ n`.

Proof: if `g^(p^m) = 1` then `g^(p^n) = (g^(p^m))^(p^(n-m)) = 1^(p^(n-m)) = 1`,
so the generator set for `Omega p m G` is contained in that of `Omega p n G`. -/
theorem mono {m n : ℕ} (h : m ≤ n) : Omega G p m ≤ Omega G p n := by
  refine Subgroup.closure_mono ?_
  intro g (hg : g ^ (p ^ m) = 1)
  change g ^ (p ^ n) = 1
  obtain ⟨k, rfl⟩ := Nat.exists_eq_add_of_le h
  rw [Nat.pow_add, pow_mul, hg, one_pow]

/-- **`Ω_n(G)` は characteristic**: 任意の自己同型 `φ : G ≃* G` は生成集合
`{g | g ^ (p ^ n) = 1}` を保つ (`(φ g) ^ (p ^ n) = φ (g ^ (p ^ n)) = φ 1 = 1`),
ゆえに `Ω_n(G)` を固定する.

BG Thm 1.13 (issue 0016) で `H = Ω₁(C)` を `C` で characteristic にし,
`C char G` と合わせて ambient `G` での characteristic を導く土台. -/
instance characteristic : (Omega G p n).Characteristic := by
  rw [Subgroup.characteristic_iff_map_eq]
  intro φ
  rw [Omega, MonoidHom.map_closure]
  congr 1
  ext h
  simp only [Set.mem_image, Set.mem_setOf_eq, MulEquiv.coe_toMonoidHom]
  constructor
  · rintro ⟨g, hg, rfl⟩
    rw [← map_pow, hg, map_one]
  · intro hh
    exact ⟨φ.symm h, by rw [← map_pow, hh, map_one], φ.apply_symm_apply h⟩

end Omega

/-! ## Agemo subgroups `℧_n(G)` = `𝒰^n(G)` (the dual of `Ω_n`)

BG denotes (local-analysis.mmd line 1375)
  `𝒰^n(R) = ⟨ x^(p^n) | x ∈ R ⟩`.
This is the **agemo** subgroup ("Omega" reversed; classical symbol `℧`, the
upside-down `Ω`).  We name it `Agemo` to pair visually with `Omega` in this
file.  `Agemo p n G` matches BG's `𝒰^n`, so BG's `𝒰^1(R)` = `Agemo p 1 R`
(generated by the `p`-th powers `x^p`), which is what BG Prop 4.11 (Huppert)
and Thm 4.12 / Thm 4.16 use.

mathlib v4.30.0-rc2 に `Agemo` / `agemo` / `mho` / pow-closure subgroup 不在を確認済
(0 genuine hits across `Mathlib/GroupTheory/` and `Mathlib/Algebra/Group/Subgroup/`;
the only `…mho`/`agemo`-substring hits are `imageMono…` false positives).

Note the **opposite monotonicity to `Omega`**: `Ω` *increases* in `n`
(`Omega.mono`), whereas `℧` *decreases* in `n` (`Agemo.anti`), because the
generators of `𝒰^(n+1)` are powers of the generators of `𝒰^n`. -/

variable (G) in
/-- **Agemo subgroup** `℧_n(G)` (BG's `𝒰^n(G)`) at prime `p`:
the subgroup of `G` generated by all `p^n`-th powers `x^(p^n)`.

This is the precise dual of `Omega G p n`.  For abelian `p`-groups it equals
the set `{x^(p^n) : x ∈ G}`; for non-abelian groups the generated subgroup is
generally larger.  BG Prop 4.11 / Thm 4.12 / Thm 4.16 use `𝒰^1(R) = Agemo p 1 R`. -/
def Agemo (p n : ℕ) : Subgroup G :=
  Subgroup.closure {g : G | ∃ x : G, g = x ^ (p ^ n)}

namespace Agemo

variable {p n : ℕ}

/-- A `p^n`-th power `x^(p^n)` lies in `Agemo p n G`. -/
theorem mem_of_eq_pow (x : G) : x ^ (p ^ n) ∈ Agemo G p n :=
  Subgroup.subset_closure ⟨x, rfl⟩

/-- Antitone in `n`: `Agemo p n G ≤ Agemo p m G` whenever `m ≤ n`.

This is the **dual direction** to `Omega.mono` (`Ω` grows, `℧` shrinks).
Proof: a generator of `Agemo p n G` is `x^(p^n)`.  Writing `n = m + k`,
`x^(p^n) = (x^(p^m))^(p^k)`, which is a power of the generator `x^(p^m)` of
`Agemo p m G`, hence lies in `Agemo p m G` (subgroups are closed under powers).
So every generator of `Agemo p n G` is in `Agemo p m G`; conclude by
`closure_le`.  (`closure_mono` does *not* apply: the generator sets are not
nested — the larger-exponent generators sit inside the smaller closure.) -/
theorem anti {m n : ℕ} (h : m ≤ n) : Agemo G p n ≤ Agemo G p m := by
  rw [Agemo, Subgroup.closure_le]
  rintro g ⟨x, rfl⟩
  obtain ⟨k, rfl⟩ := Nat.exists_eq_add_of_le h
  rw [Nat.pow_add, pow_mul]
  exact Subgroup.pow_mem _ (mem_of_eq_pow x) _

/-- **`℧_n(G)` is characteristic**: any automorphism `φ : G ≃* G` permutes the
generating set `{x^(p^n) : x ∈ G}` (`φ (x^(p^n)) = (φ x)^(p^n)`), hence fixes
`℧_n(G)`.  Verbatim dual of `Omega.characteristic`. -/
instance characteristic : (Agemo G p n).Characteristic := by
  rw [Subgroup.characteristic_iff_map_eq]
  intro φ
  rw [Agemo, MonoidHom.map_closure]
  congr 1
  ext h
  simp only [Set.mem_image, Set.mem_setOf_eq, MulEquiv.coe_toMonoidHom]
  constructor
  · rintro ⟨g, ⟨x, rfl⟩, rfl⟩
    exact ⟨φ x, by rw [map_pow]⟩
  · rintro ⟨x, rfl⟩
    exact ⟨φ.symm x ^ (p ^ n), ⟨φ.symm x, rfl⟩, by rw [map_pow, φ.apply_symm_apply]⟩

end Agemo

/-! ## `Ω₁` of an abelian subgroup

When `H ≤ G` is abelian (carries a `CommGroup` structure), the set
`{h ∈ H | h^p = 1}` is itself a subgroup of `G`.  This is the standard
`Ω₁(H)` for abelian `H`; without abelianness `(xy)^p ≠ x^p y^p` in general
and one must fall back to the closure form `Omega G p 1`.

This is the form needed for **Isaacs Thm 7.6 Step 7** where
`V := Ω₁(Z(O_p(G)))` and `Z(O_p(G))` is abelian. -/

/-- **`Ω₁` of an abelian subgroup**: given a subgroup `H ≤ G` whose
underlying group is commutative (witnessed by `hH : ∀ x y ∈ H, x * y = y * x`),
the set `{g ∈ H | g^p = 1}` is a subgroup of `G`.

This wraps the standard abelian-group fact `(xy)^p = x^p * y^p` and packages
it with the membership-in-`H` predicate to land directly in `Subgroup G`. -/
def omega1OfAbelian (G : Type*) [Group G] (H : Subgroup G) (p : ℕ)
    (hH : ∀ x ∈ H, ∀ y ∈ H, x * y = y * x) :
    Subgroup G where
  carrier := {g : G | g ∈ H ∧ g ^ p = 1}
  mul_mem' := by
    rintro x y ⟨hxH, hxp⟩ ⟨hyH, hyp⟩
    refine ⟨H.mul_mem hxH hyH, ?_⟩
    have hcomm : Commute x y := hH x hxH y hyH
    rw [hcomm.mul_pow, hxp, hyp, mul_one]
  one_mem' := ⟨H.one_mem, one_pow p⟩
  inv_mem' := by
    rintro x ⟨hxH, hxp⟩
    refine ⟨H.inv_mem hxH, ?_⟩
    rw [inv_pow, hxp, inv_one]

variable {p : ℕ}

@[simp]
theorem mem_omega1OfAbelian {H : Subgroup G} {p : ℕ}
    {hH : ∀ x ∈ H, ∀ y ∈ H, x * y = y * x} {g : G} :
    g ∈ omega1OfAbelian G H p hH ↔ g ∈ H ∧ g ^ p = 1 :=
  Iff.rfl

theorem omega1OfAbelian_le {H : Subgroup G} {p : ℕ}
    {hH : ∀ x ∈ H, ∀ y ∈ H, x * y = y * x} :
    omega1OfAbelian G H p hH ≤ H :=
  fun _ hg => hg.1

theorem pow_eq_one_of_mem_omega1OfAbelian {H : Subgroup G} {p : ℕ}
    {hH : ∀ x ∈ H, ∀ y ∈ H, x * y = y * x} {g : G}
    (hg : g ∈ omega1OfAbelian G H p hH) : g ^ p = 1 :=
  hg.2

end OddOrder.GroupTheory
