/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.Algebra.Group.Subgroup.Basic

/-!
# Omega Subgroups

`OddOrder.GroupTheory` shared module: 'Omega subgroup' Ω_n(G) の概念.

mathlib v4.29.1 に `Omega1` / `Omega` / `omega1` / `omegaSubgroup` 不在を確認済
(0 hits across `Mathlib/GroupTheory/`).

**BG §1 Thm 1.11 (Ω₁ fixed under coprime auto ⇒ trivial)**, **BG §1 Cor 1.12**,
**BG §1 Thm 1.13 (Thompson critical)**, **BG §4 全節 (rank theory)**,
**BG §5 全節 (narrow p-groups)**, **Isaacs Thm 4.36 (Ch.4 §4D)** で必要.

## Main definitions

* `OddOrder.GroupTheory.Omega p n G`: 部分群 `⟨g ∈ G : g^(p^n) = 1⟩` (i.e. `Subgroup.closure
  {g : G | g^(p^n) = 1}`). For abelian p-group it agrees with the set `{g : g^(p^n) = 1}`.

## Main results (本 module で提供, 最小)

* `Omega.subset_closure_of_pow_eq_one`: `g^(p^n) = 1 ⇒ g ∈ Omega p n G`.
* `Omega.mono`: `m ≤ n ⇒ Omega p m G ≤ Omega p n G`.

## Design notes

* `Subgroup.closure` 形 (一般 G, abelian 仮定なし). abelian の場合の
  `g ∈ Omega p n G ↔ g^(p^n) = 1` 同値は補強で.
* `p` prime 仮定は def 段階では不要. 主結果記述時に `[Fact p.Prime]` 付与.
* characteristic / normal 性質 (Aut G で不変) は補強で.
* 将来 mathlib upstream 視野で `OddOrder/Mathlib/OmegaSubgroup.lean` 候補.

## References

* BG §1, §4, §5.
* Isaacs FGT Ch.4 §4D, Thm 4.36.

## Audit context

Phase 2a 第 1 波 audit 2026-05-23 で新規 shared module 候補として確定.
詳細は `notes/meta/bg_phase2a_wave1_audit_2026_05_23.md`.
-/

namespace OddOrder.GroupTheory

variable (G : Type*) [Group G]

/-- **Omega subgroup** `Ω_n(G)` at prime `p`:
the subgroup of `G` generated by all elements `g` with `g^(p^n) = 1`.

For abelian `p`-groups, this equals the set `{g : g^(p^n) = 1}`. For non-abelian
groups, the generated subgroup is generally larger than this set. -/
def Omega (p n : ℕ) : Subgroup G :=
  Subgroup.closure {g : G | g ^ (p ^ n) = 1}

variable {G}

namespace Omega

variable {p n : ℕ}

/-- An element `g` with `g^(p^n) = 1` is in `Omega p n G`. -/
theorem mem_of_pow_eq_one {g : G} (hg : g ^ (p ^ n) = 1) : g ∈ Omega G p n :=
  Subgroup.subset_closure hg

/-- Monotonicity: `Omega p m G ≤ Omega p n G` whenever `m ≤ n`.

Proof: if `g^(p^m) = 1` then `g^(p^n) = (g^(p^m))^(p^(n-m)) = 1^(p^(n-m)) = 1`,
so the generator set for `Omega p m G` is contained in that of `Omega p n G`. -/
theorem mono {m n : ℕ} (h : m ≤ n) : Omega G p m ≤ Omega G p n := by
  refine Subgroup.closure_mono ?_
  intro g (hg : g ^ (p ^ m) = 1)
  change g ^ (p ^ n) = 1
  obtain ⟨k, rfl⟩ := Nat.exists_eq_add_of_le h
  rw [Nat.pow_add, pow_mul, hg, one_pow]

end Omega

end OddOrder.GroupTheory
