/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Mathlib.Subgroup
import Mathlib.GroupTheory.Sylow

/-!
# Prime-complement residuals

For a prime `p` and a finite group `G`, `primeComplementResidual p G` is the
subgroup generated by all Sylow `p`-subgroups. It is the smallest normal subgroup
whose index is coprime to `p`, and equals the normal closure of any Sylow
`p`-subgroup.

This is shared infrastructure for **Peterfalvi, Part II, Chapter I, section 3
(pp. 100-107), Lemma 1**, where the case `p = 2` is denoted by the
prime-complement residual notation.
-/

namespace Subgroup

variable {G : Type*} [Group G]

section /- Conjugate joins and normal closures -/

/-- The supremum of all conjugates of a subgroup is normal. -/
instance iSup_map_conj_normal (H : Subgroup G) :
    (⨆ g : G, H.map (MulAut.conj g).toMonoidHom).Normal := by
  refine normal_iff_map_conj_eq.mpr fun g => ?_
  conv_rhs => rw [← Equiv.iSup_comp (Equiv.mulLeft g)]
  rw [map_iSup]
  simp [map_map, MulAut.mul_def]

/-- The normal closure of a subgroup is the supremum of all its conjugates. -/
theorem normalClosure_eq_iSup_map_conj (H : Subgroup G) :
    normalClosure (H : Set G) = ⨆ g : G, H.map (MulAut.conj g).toMonoidHom := by
  apply le_antisymm
  · refine normalClosure_le_normal fun x hx => ?_
    have h1 : H.map (MulAut.conj (1 : G)).toMonoidHom = H := by
      simp [MulAut.one_def]
    exact le_iSup (fun g : G => H.map (MulAut.conj g).toMonoidHom) 1 (h1.symm ▸ hx)
  · refine iSup_le fun g => ?_
    rintro x ⟨s, hs, rfl⟩
    simpa using normalClosure_normal.conj_mem _ (subset_normalClosure hs) g

end

section /- Prime-complement residuals -/

/-- The prime-complement residual, generated by the Sylow `p`-subgroups of `G`. -/
def primeComplementResidual (p : ℕ) (G : Type*) [Group G] : Subgroup G :=
  ⨆ P : Sylow p G, (P : Subgroup G)

/-- Every Sylow `p`-subgroup lies in the prime-complement residual. -/
theorem le_primeComplementResidual {p : ℕ} (P : Sylow p G) :
    (P : Subgroup G) ≤ primeComplementResidual p G :=
  le_iSup (fun Q : Sylow p G => (Q : Subgroup G)) P

/-- The residual is the join of the conjugates of any Sylow `p`-subgroup. -/
theorem primeComplementResidual_eq_iSup_map_conj [Finite G] {p : ℕ} [Fact p.Prime]
    (P : Sylow p G) :
    primeComplementResidual p G =
      ⨆ g : G, (P : Subgroup G).map (MulAut.conj g).toMonoidHom := by
  apply le_antisymm
  · refine iSup_le fun Q => ?_
    obtain ⟨g, hg⟩ := MulAction.exists_smul_eq G P Q
    rw [← hg]
    change (P : Subgroup G).map (MulAut.conj g).toMonoidHom ≤ _
    exact le_iSup (fun h : G => (P : Subgroup G).map (MulAut.conj h).toMonoidHom) g
  · refine iSup_le fun g => ?_
    change ((g • P : Sylow p G) : Subgroup G) ≤ _
    exact le_primeComplementResidual (g • P)

/-- The residual is the normal closure of any Sylow `p`-subgroup. -/
theorem primeComplementResidual_eq_normalClosure [Finite G] {p : ℕ} [Fact p.Prime]
    (P : Sylow p G) :
    primeComplementResidual p G = normalClosure ((P : Subgroup G) : Set G) := by
  rw [primeComplementResidual_eq_iSup_map_conj P, ← normalClosure_eq_iSup_map_conj]

instance primeComplementResidual_normal [Finite G] (p : ℕ) [Fact p.Prime] :
    (primeComplementResidual p G).Normal := by
  let P : Sylow p G := Classical.choice Sylow.nonempty
  rw [primeComplementResidual_eq_normalClosure P]
  infer_instance

/-- The residual lies in every normal subgroup with index coprime to `p`. -/
theorem primeComplementResidual_le_of_coprime_index [Finite G] {p : ℕ} [Fact p.Prime]
    {N : Subgroup G} [N.Normal] (hN : Nat.Coprime p N.index) :
    primeComplementResidual p G ≤ N := by
  refine iSup_le fun P => Subgroup.le_of_coprime_card_index_of_normal ?_
  rw [P.card_eq_multiplicity]
  exact hN.pow_left _

/-- The index of the residual is coprime to `p`. -/
theorem primeComplementResidual_index_coprime [Finite G] (p : ℕ) [Fact p.Prime] :
    Nat.Coprime p (primeComplementResidual p G).index := by
  rw [(Fact.out : p.Prime).coprime_iff_not_dvd]
  intro hp
  let P : Sylow p G := Classical.choice Sylow.nonempty
  exact P.not_dvd_index (hp.trans (Subgroup.index_dvd_of_le (le_primeComplementResidual P)))

end

end Subgroup
