/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.GroupTheory.RankOneBNPair
import OddOrder.GroupTheory.PrimeComplementResidual

/-!
# The rigidity Lemma of a rank-one split BN-pair

T. Peterfalvi, *Character Theory for the Odd Order Theorem* (LMS LNS 272, 2000),
Part II, Ch. IV §1, the Lemma on p. 123:

> If `L` acts faithfully on `X`, then `⟨Q^x | x ∈ L⟩` is determined up to isomorphism by
> `Q` and `f`, and also `L` is determined up to isomorphism by `M = Q ⋊ D` and `f`.

`RankOneBNPair` supplies the model: `X = L ⧸ M` is identified with `Q ∪ {a}`
(`coordsEquiv`), in which `t` acts by `f` (`coords_smul_t_some`) and `M` acts through
its `Q ⋊ D` structure alone (`coords_smul_some_of_mem_M`).  This file turns that model
into a homomorphism `permHom : L →* Equiv.Perm (Option ↥Q)` and reads the Lemma off it:

* faithfulness (`M.normalCore = ⊥`) makes `permHom` injective, so `L ≃* permHom.range`;
* `L = ⟨M, t⟩` makes that range the subgroup generated by the permutation of `t` and the
  permutations of `M`, and `⟨Q^x | x ∈ L⟩ = ⟨Q, Q^t⟩` makes the range of the latter the
  subgroup generated by the permutations of `Q` and their conjugates by that of `t`;
* so a bijection of point sets matching those generators transports one to the other.

## Main results

* `permHom`, `permHom_t_some`, `permHom_some_of_mem_M` — the permutation model as a
  homomorphism, with `t` acting by `f` and `M` by `mAct`.
* `permHom_range_eq`, `permHom_map_conjQ_eq` — the two generation statements, in
  permutations.
* `mulEquivOfPermMatch`, `conjQMulEquivOfPermMatch` — the transport: matching point sets
  give `L ≃* L'` and `⟨Q^x⟩ ≃* ⟨Q'^x⟩`.
* `mulEquivOfData` — the Lemma in the book's terms: an isomorphism `M ≃* M'` compatible
  with the point sets, together with `f' ∘ ε = ε ∘ f`, gives `L ≃* L'`.
* `closure_iUnion_conj_eq_primeComplementResidual` — for `Q` a Sylow `p`-subgroup the
  subgroup `⟨Q^x | x ∈ L⟩` the Lemma is about is `O^{p'}(L)`, which is how Corollary 1
  of §3 (p. 132) invokes it.
* `Setup.closure_Q_union_conj_eq_top`, `Setup.normalCore_eq_bot` — when `Q` is a
  Sylow subgroup and `L` has no `p′`-quotient and trivial centre, `M` has trivial normal
  core; this is the faithfulness input of `Hypothesis.ofRankOneSetup`.
* `Setup.normalCore_eq_bot_of_isSimpleGroup` — the same conclusion in one line when `L`
  happens to be simple, which is the case Peterfalvi Ch. IV §4, step (2) needs.
-/

set_option autoImplicit false

namespace OddOrder.GroupTheory.RankOneBNPair

universe u v

variable {L : Type u} [Group L] {M Q D : Subgroup L} {t : L} {f g h : L → L}

/-! ## The `Q ⋊ D` action of `M` on the point set

`Setup.split` says every element of `M` is uniquely `q · d`.  Naming the two factors
turns `coords_smul_some_of_mem_M` into a genuine action of `M` on `Q`, which is the form
in which the Lemma's phrase "the action of `M` is determined by the specification of
`Q ⋊ D`" can be used.
-/

/-- The `Q`-part of an element of `M` in the decomposition `M = Q ⋊ D`. -/
noncomputable def qPart (hS : Setup M Q D t) {a : L} (ha : a ∈ M) : ↥Q :=
  (hS.split a ha).choose.1

/-- The `D`-part of an element of `M` in the decomposition `M = Q ⋊ D`. -/
noncomputable def dPart (hS : Setup M Q D t) {a : L} (ha : a ∈ M) : ↥D :=
  (hS.split a ha).choose.2

theorem qPart_mul_dPart (hS : Setup M Q D t) {a : L} (ha : a ∈ M) :
    a = (qPart hS ha : L) * (dPart hS ha : L) :=
  (hS.split a ha).choose_spec.1

theorem qPart_eq (hS : Setup M Q D t) {a : L} (ha : a ∈ M) {q : ↥Q} {d : ↥D}
    (hqd : a = (q : L) * (d : L)) : qPart hS ha = q :=
  (congrArg Prod.fst ((hS.split a ha).choose_spec.2 (q, d) hqd)).symm

/-- `m x⁻¹ ∈ M` for `m ∈ M` and `x ∈ Q`, the element whose `Q`-part names the image of
the point `x` under `m`. -/
theorem mul_inv_mem_M (hS : Setup M Q D t) (m : ↥M) (x : ↥Q) :
    (m : L) * (x : L)⁻¹ ∈ M :=
  M.mul_mem m.2 (M.inv_mem (hS.QM x.2))

/-- **The action of `M` on the point set `Q`**, read off the decomposition
`M = Q ⋊ D`: `m` sends the point `x` to `q⁻¹`, where `m x⁻¹ = q d`.

This is `coords_smul_some_of_mem_M` with the `Q`-part named; the `D`-part is invisible
because `d t M = t (t d t) M = t M`. -/
noncomputable def mAct (hS : Setup M Q D t) (m : ↥M) (x : ↥Q) : ↥Q :=
  (qPart hS (mul_inv_mem_M hS m x))⁻¹

theorem mAct_eq (hS : Setup M Q D t) (m : ↥M) (x : ↥Q) {q : ↥Q} {d : ↥D}
    (hqd : (m : L) * (x : L)⁻¹ = (q : L) * (d : L)) : mAct hS m x = q⁻¹ := by
  rw [mAct, qPart_eq hS _ hqd]

/-! ## The permutation model as a homomorphism -/

/-- `Equiv.permCongrHom` applied, unfolded — mathlib states the `simp` lemma for
`Equiv.permCongr` and gets to the `MulEquiv` version by `rfl`. -/
theorem permCongrHom_apply {α β : Type*} (ε : α ≃ β) (p : Equiv.Perm α) (y : β) :
    Equiv.permCongrHom ε p y = ε (p (ε.symm y)) := rfl

/-- **The action of `L` on `X ≅ Q ∪ {a}`**, as a homomorphism to `Equiv.Perm`.

This is `MulAction.toPermHom L (L ⧸ M)` read through the identification `coordsEquiv`
of Peterfalvi Part II, Ch. IV §1, p. 123. -/
noncomputable def permHom (hS : Setup M Q D t) : L →* Equiv.Perm (Option ↥Q) :=
  (Equiv.permCongrHom (coordsEquiv hS).symm).toMonoidHom.comp
    (MulAction.toPermHom L (L ⧸ M))

theorem permHom_apply (hS : Setup M Q D t) (l : L) (o : Option ↥Q) :
    permHom hS l o = (coordsEquiv hS).symm (l • coords M Q t o) := rfl

/-- Reading off a value of `permHom` from the corresponding computation in `L ⧸ M`. -/
theorem permHom_apply_eq (hS : Setup M Q D t) {l : L} {o o' : Option ↥Q}
    (hl : l • coords M Q t o = coords M Q t o') : permHom hS l o = o' := by
  rw [permHom_apply, hl]
  exact (coordsEquiv hS).symm_apply_apply o'

/-- `t` sends the point `a` to the point `1`. -/
theorem permHom_t_none (hS : Setup M Q D t) :
    permHom hS t (none : Option ↥Q) = some 1 :=
  permHom_apply_eq hS coords_smul_t_none

/-- ... and the point `1` back to `a`. -/
theorem permHom_t_one (hS : Setup M Q D t) :
    permHom hS t (some (1 : ↥Q)) = (none : Option ↥Q) :=
  permHom_apply_eq hS (coords_smul_t_one hS)

/-- **`t` acts by `f`** (Peterfalvi Part II, Ch. IV §1, p. 123). -/
theorem permHom_t_some (hS : Setup M Q D t) (H : IsFGH M Q D t f g h) {x : ↥Q}
    (hx1 : (x : L) ≠ 1) :
    permHom hS t (some x) = some ⟨f (x : L), H.f_mem x.2 hx1⟩ :=
  permHom_apply_eq hS (coords_smul_t_some hS H hx1)

/-- `M` fixes the point `a`. -/
theorem permHom_none_of_mem_M (hS : Setup M Q D t) {m : L} (hm : m ∈ M) :
    permHom hS m (none : Option ↥Q) = none :=
  permHom_apply_eq hS (coords_smul_none_of_mem_M hm)

/-- **`M` acts through `Q ⋊ D`** (Peterfalvi Part II, Ch. IV §1, p. 123). -/
theorem permHom_some_of_mem_M (hS : Setup M Q D t) (m : ↥M) (x : ↥Q) :
    permHom hS (m : L) (some x) = some (mAct hS m x) :=
  permHom_apply_eq hS
    (coords_smul_some_of_mem_M hS x (qPart hS (mul_inv_mem_M hS m x)).2
      (dPart hS (mul_inv_mem_M hS m x)).2 (qPart_mul_dPart hS (mul_inv_mem_M hS m x)))

/-! ## Faithfulness -/

theorem permHom_ker (hS : Setup M Q D t) : (permHom hS).ker = M.normalCore := by
  rw [Subgroup.normalCore_eq_ker]
  ext l
  constructor
  · intro hl
    exact (MulEquiv.map_eq_one_iff (Equiv.permCongrHom (coordsEquiv hS).symm)).mp hl
  · intro hl
    change (Equiv.permCongrHom (coordsEquiv hS).symm)
      (MulAction.toPermHom L (L ⧸ M) l) = 1
    rw [show MulAction.toPermHom L (L ⧸ M) l = 1 from hl, map_one]

/-- **The action on `X` is faithful exactly when `M` has trivial normal core.** -/
theorem permHom_injective (hS : Setup M Q D t) (hcore : M.normalCore = ⊥) :
    Function.Injective (permHom hS) :=
  (MonoidHom.ker_eq_bot_iff _).mp (by rw [permHom_ker, hcore])

/-! ## Generation

`L = ⟨M, t⟩` and `⟨Q^x | x ∈ L⟩ = ⟨Q, Q^t⟩`, transported to permutations.  These are
the two displays that close the Lemma's proof.
-/

/-- **`permHom` has image `⟨permutations of `M`, permutation of `t`⟩`**, since
`L = ⟨M, t⟩` (`Setup.closure_M_union_t`). -/
theorem permHom_range_eq (hS : Setup M Q D t) :
    (permHom hS).range
      = Subgroup.closure (insert (permHom hS t) (permHom hS '' (M : Set L))) := by
  rw [MonoidHom.range_eq_map, ← hS.closure_M_union_t, MonoidHom.map_closure,
    Set.image_union, Set.image_singleton, Set.union_singleton]

/-- **The image of `⟨Q^x | x ∈ L⟩`** is generated by the permutations of `Q` and their
conjugates by the permutation of `t`, since `⟨Q^x | x ∈ L⟩ = ⟨Q, Q^t⟩`
(`Setup.closure_conj_Q`). -/
theorem permHom_map_conjQ_eq (hS : Setup M Q D t) :
    (Subgroup.closure (⋃ y : L, ((fun q => y⁻¹ * q * y) '' (Q : Set L)))).map (permHom hS)
      = Subgroup.closure ((permHom hS '' (Q : Set L))
          ∪ (fun σ => permHom hS t * σ * permHom hS t) '' (permHom hS '' (Q : Set L))) := by
  have himg : permHom hS '' ((fun z => t * z * t) '' (Q : Set L))
      = (fun σ => permHom hS t * σ * permHom hS t) '' (permHom hS '' (Q : Set L)) := by
    rw [← Set.image_comp, ← Set.image_comp]
    refine Set.image_congr' fun z => ?_
    simp only [Function.comp_apply]
    rw [map_mul, map_mul]
  rw [hS.closure_conj_Q, MonoidHom.map_closure, Set.image_union, himg]

/-! ## `⟨Q^x | x ∈ L⟩` as a residual

Peterfalvi Part II, Ch. IV §3, Corollary 1 (p. 132) opens with "`O^{2'}(G) =
⟨Q^x | x ∈ G⟩`".  The subgroup the Lemma is about is therefore the `2`-complement
residual of `L` whenever `Q` is a Sylow `2`-subgroup, and the rigidity statements above
apply to it verbatim.
-/

/-- `⟨H^x | x ∈ L⟩` is the normal closure of `H`. -/
theorem closure_iUnion_conj_eq_normalClosure (H : Subgroup L) :
    Subgroup.closure (⋃ y : L, ((fun q => y⁻¹ * q * y) '' (H : Set L)))
      = Subgroup.normalClosure (H : Set L) := by
  rw [Subgroup.normalClosure_eq_iSup_map_conj, Subgroup.iSup_eq_closure]
  congr 1
  ext x
  simp only [Set.mem_iUnion, Set.mem_image, SetLike.mem_coe, Subgroup.coe_map]
  constructor
  · rintro ⟨y, q, hq, rfl⟩
    refine ⟨y⁻¹, q, hq, ?_⟩
    simp
  · rintro ⟨g, q, hq, rfl⟩
    refine ⟨g⁻¹, q, hq, ?_⟩
    simp

/-- **`⟨Q^x | x ∈ L⟩ = O^{p'}(L)` for `Q` a Sylow `p`-subgroup** (Peterfalvi Part II,
Ch. IV §3, Corollary 1, p. 132, with `p = 2`).

`primeComplementResidual` is the join of the Sylow `p`-subgroups, hence the normal
closure of any one of them (`primeComplementResidual_eq_normalClosure`), which is
`⟨Q^x | x ∈ L⟩`. -/
theorem closure_iUnion_conj_eq_primeComplementResidual [Finite L] {p : ℕ} [Fact p.Prime]
    (P : Sylow p L) :
    Subgroup.closure
        (⋃ y : L, ((fun q => y⁻¹ * q * y) '' ((P : Subgroup L) : Set L)))
      = Subgroup.primeComplementResidual p L := by
  rw [closure_iUnion_conj_eq_normalClosure,
    Subgroup.primeComplementResidual_eq_normalClosure P]

/-! ## The transport

Two setups whose permutation models match — same point set up to a bijection, matching
permutation for `t`, matching set of permutations for `M` — have isomorphic `L`'s.  This
is the sense in which the Lemma's "determined up to isomorphism" is meant.
-/

variable {L' : Type v} [Group L'] {M' Q' D' : Subgroup L'} {t' : L'} {f' g' h' : L' → L'}

/-- The two ranges correspond under a matching bijection of point sets. -/
theorem map_permHom_range_eq (hS : Setup M Q D t) (hS' : Setup M' Q' D' t')
    (ε : Option ↥Q ≃ Option ↥Q')
    (ht : Equiv.permCongrHom ε (permHom hS t) = permHom hS' t')
    (hM : (Equiv.permCongrHom ε) '' (permHom hS '' (M : Set L))
      = permHom hS' '' (M' : Set L')) :
    (permHom hS).range.map
        ((Equiv.permCongrHom ε : Equiv.Perm (Option ↥Q) ≃* Equiv.Perm (Option ↥Q')) :
          Equiv.Perm (Option ↥Q) →* Equiv.Perm (Option ↥Q'))
      = (permHom hS').range := by
  rw [permHom_range_eq, permHom_range_eq, MonoidHom.map_closure, Set.image_insert_eq]
  simp only [MonoidHom.coe_coe]
  rw [ht, hM]

/-- **The Lemma of Peterfalvi Part II, Ch. IV §1** (p. 123), transport step: if a
bijection of the two point sets carries the permutation of `t` to that of `t'` and the
permutations of `M` onto those of `M'`, then `L ≃* L'`.

Faithfulness enters as `M.normalCore = ⊥`, which by `Subgroup.normalCore_eq_ker` is
exactly faithfulness of the action of `L` on `L ⧸ M`. -/
noncomputable def mulEquivOfPermMatch (hS : Setup M Q D t) (hS' : Setup M' Q' D' t')
    (hcore : M.normalCore = ⊥) (hcore' : M'.normalCore = ⊥)
    (ε : Option ↥Q ≃ Option ↥Q')
    (ht : Equiv.permCongrHom ε (permHom hS t) = permHom hS' t')
    (hM : (Equiv.permCongrHom ε) '' (permHom hS '' (M : Set L))
      = permHom hS' '' (M' : Set L')) :
    L ≃* L' :=
  (MonoidHom.ofInjective (permHom_injective hS hcore)).trans
    (((Equiv.permCongrHom ε).subgroupMap (permHom hS).range).trans
      ((MulEquiv.subgroupCongr (map_permHom_range_eq hS hS' ε ht hM)).trans
        (MonoidHom.ofInjective (permHom_injective hS' hcore')).symm))

/-- The images of `⟨Q^x | x ∈ L⟩` correspond under a matching bijection of point sets —
here only the permutations of `Q` (and that of `t`) are needed, not those of all of
`M`.  This is the first half of the Lemma: `⟨Q^x | x ∈ L⟩` is determined by `Q` and
`f`. -/
theorem map_permHom_conjQ_eq (hS : Setup M Q D t) (hS' : Setup M' Q' D' t')
    (ε : Option ↥Q ≃ Option ↥Q')
    (ht : Equiv.permCongrHom ε (permHom hS t) = permHom hS' t')
    (hQ : (Equiv.permCongrHom ε) '' (permHom hS '' (Q : Set L))
      = permHom hS' '' (Q' : Set L')) :
    ((Subgroup.closure (⋃ y : L, ((fun q => y⁻¹ * q * y) '' (Q : Set L)))).map
        (permHom hS)).map
        ((Equiv.permCongrHom ε : Equiv.Perm (Option ↥Q) ≃* Equiv.Perm (Option ↥Q')) :
          Equiv.Perm (Option ↥Q) →* Equiv.Perm (Option ↥Q'))
      = (Subgroup.closure
          (⋃ y : L', ((fun q => y⁻¹ * q * y) '' (Q' : Set L')))).map (permHom hS') := by
  have himg : ∀ S : Set (Equiv.Perm (Option ↥Q)),
      (Equiv.permCongrHom ε) '' ((fun σ => permHom hS t * σ * permHom hS t) '' S)
        = (fun σ => permHom hS' t' * σ * permHom hS' t')
            '' ((Equiv.permCongrHom ε) '' S) := by
    intro S
    rw [← Set.image_comp, ← Set.image_comp]
    refine Set.image_congr' fun σ => ?_
    simp only [Function.comp_apply]
    rw [map_mul, map_mul, ht]
  rw [permHom_map_conjQ_eq, permHom_map_conjQ_eq, MonoidHom.map_closure, Set.image_union]
  simp only [MonoidHom.coe_coe]
  rw [himg, hQ]

/-- **The first half of the Lemma**: `⟨Q^x | x ∈ L⟩` is determined up to isomorphism by
`Q` and `f`. -/
noncomputable def conjQMulEquivOfPermMatch (hS : Setup M Q D t) (hS' : Setup M' Q' D' t')
    (hcore : M.normalCore = ⊥) (hcore' : M'.normalCore = ⊥)
    (ε : Option ↥Q ≃ Option ↥Q')
    (ht : Equiv.permCongrHom ε (permHom hS t) = permHom hS' t')
    (hQ : (Equiv.permCongrHom ε) '' (permHom hS '' (Q : Set L))
      = permHom hS' '' (Q' : Set L')) :
    ↥(Subgroup.closure (⋃ y : L, ((fun q => y⁻¹ * q * y) '' (Q : Set L))))
      ≃* ↥(Subgroup.closure (⋃ y : L', ((fun q => y⁻¹ * q * y) '' (Q' : Set L')))) :=
  ((Subgroup.equivMapOfInjective _ _ (permHom_injective hS hcore)).trans
    (((Equiv.permCongrHom ε).subgroupMap _).trans
      ((MulEquiv.subgroupCongr (map_permHom_conjQ_eq hS hS' ε ht hQ)).trans
        (Subgroup.equivMapOfInjective _ _ (permHom_injective hS' hcore')).symm)))

/-! ## The Lemma in the book's terms

The matching hypotheses above are statements about permutations.  What the book supplies
is a bijection `ε` of the point sets intertwining `f` with `f'`, and an isomorphism
`M ≃* M'` intertwining the two `Q ⋊ D` actions.  These two produce the matchings.
-/

/-- A bijection of point sets fixing the base point sends non-identity points to
non-identity points. -/
theorem ne_one_of_ne_one (εQ : ↥Q ≃ ↥Q') (hε1 : εQ 1 = 1) {x : ↥Q} (hx1 : (x : L) ≠ 1) :
    ((εQ x : ↥Q') : L') ≠ 1 := by
  intro hc
  have hx : x = 1 := εQ.injective (by rw [hε1]; exact Subtype.ext hc)
  exact hx1 (by rw [hx]; rfl)

/-- **`t` acts by `f`, so `f` determines the permutation of `t`.** -/
theorem permCongrHom_permHom_t (hS : Setup M Q D t) (hS' : Setup M' Q' D' t')
    (H : IsFGH M Q D t f g h) (H' : IsFGH M' Q' D' t' f' g' h')
    (εQ : ↥Q ≃ ↥Q') (hε1 : εQ 1 = 1)
    (hεf : ∀ (x : ↥Q) (hx1 : (x : L) ≠ 1),
      ((εQ ⟨f (x : L), H.f_mem x.2 hx1⟩ : ↥Q') : L') = f' ((εQ x : ↥Q') : L')) :
    Equiv.permCongrHom (Equiv.optionCongr εQ) (permHom hS t) = permHom hS' t' := by
  refine Equiv.ext fun o => ?_
  rw [permCongrHom_apply, ← Equiv.optionCongr_symm]
  simp only [Equiv.optionCongr_apply]
  cases o with
  | none =>
    rw [Option.map_none, permHom_t_none, permHom_t_none, Option.map_some, hε1]
  | some y =>
    rw [Option.map_some]
    by_cases hy1 : ((εQ.symm y : ↥Q) : L) = 1
    · have hy : y = 1 := by
        have hs : εQ.symm y = 1 := Subtype.ext hy1
        rw [← εQ.apply_symm_apply y, hs, hε1]
      subst hy
      have h1 : εQ.symm (1 : ↥Q') = 1 := by rw [← hε1, εQ.symm_apply_apply]
      rw [h1, permHom_t_one, permHom_t_one, Option.map_none]
    · have hy1' : ((y : ↥Q') : L') ≠ 1 := by
        have hne := ne_one_of_ne_one εQ hε1 hy1
        rwa [εQ.apply_symm_apply] at hne
      rw [permHom_t_some hS H hy1, permHom_t_some hS' H' hy1', Option.map_some]
      exact congrArg some (Subtype.ext (by rw [hεf _ hy1, εQ.apply_symm_apply]))

/-- **`M` acts through `Q ⋊ D`, so an isomorphism `M ≃* M'` compatible with the point
sets matches the permutations.** -/
theorem permCongrHom_permHom_mem_M (hS : Setup M Q D t) (hS' : Setup M' Q' D' t')
    (εQ : ↥Q ≃ ↥Q') (θ : ↥M ≃* ↥M')
    (hθ : ∀ (m : ↥M) (x : ↥Q), εQ (mAct hS m x) = mAct hS' (θ m) (εQ x))
    (m : ↥M) :
    Equiv.permCongrHom (Equiv.optionCongr εQ) (permHom hS (m : L))
      = permHom hS' ((θ m : ↥M') : L') := by
  refine Equiv.ext fun o => ?_
  rw [permCongrHom_apply, ← Equiv.optionCongr_symm]
  simp only [Equiv.optionCongr_apply]
  cases o with
  | none =>
    rw [Option.map_none, permHom_none_of_mem_M hS m.2,
      permHom_none_of_mem_M hS' (θ m).2, Option.map_none]
  | some y =>
    rw [Option.map_some, permHom_some_of_mem_M hS m, permHom_some_of_mem_M hS' (θ m),
      Option.map_some]
    exact congrArg some (by rw [hθ m (εQ.symm y), εQ.apply_symm_apply])

/-- **`Q` acts on the point set by right translation**: for `q ∈ Q ≤ M` the
decomposition of `q x⁻¹` is itself, with trivial `D`-part.

This is why the first half of the Lemma needs only a *group* isomorphism `Q ≃* Q'` —
no separate compatibility with the action is required, the action being translation. -/
theorem mAct_of_mem_Q (hS : Setup M Q D t) (q x : ↥Q) :
    mAct hS ⟨(q : L), hS.QM q.2⟩ x = x * q⁻¹ := by
  rw [mAct_eq hS _ x (q := q * x⁻¹) (d := 1) (by simp)]
  rw [mul_inv_rev, inv_inv]

/-- A group isomorphism `Q ≃* Q'` matches the permutations of `Q`. -/
theorem permCongrHom_permHom_mem_Q (hS : Setup M Q D t) (hS' : Setup M' Q' D' t')
    (εQ : ↥Q ≃* ↥Q') (q : ↥Q) :
    Equiv.permCongrHom (Equiv.optionCongr εQ.toEquiv) (permHom hS (q : L))
      = permHom hS' ((εQ q : ↥Q') : L') := by
  refine Equiv.ext fun o => ?_
  cases o with
  | none =>
    change Option.map (⇑εQ) (permHom hS (q : L) none)
      = permHom hS' ((εQ q : ↥Q') : L') none
    rw [permHom_none_of_mem_M hS (hS.QM q.2),
      permHom_none_of_mem_M hS' (hS'.QM (εQ q).2), Option.map_none]
  | some y =>
    change Option.map (⇑εQ) (permHom hS (q : L) (some (εQ.symm y)))
      = permHom hS' ((εQ q : ↥Q') : L') (some y)
    have e1 : permHom hS (q : L) (some (εQ.symm y))
        = some (mAct hS ⟨(q : L), hS.QM q.2⟩ (εQ.symm y)) :=
      permHom_some_of_mem_M hS ⟨(q : L), hS.QM q.2⟩ _
    have e2 : permHom hS' ((εQ q : ↥Q') : L') (some y)
        = some (mAct hS' ⟨((εQ q : ↥Q') : L'), hS'.QM (εQ q).2⟩ y) :=
      permHom_some_of_mem_M hS' ⟨((εQ q : ↥Q') : L'), hS'.QM (εQ q).2⟩ _
    rw [e1, e2, mAct_of_mem_Q, mAct_of_mem_Q, Option.map_some, map_mul, map_inv,
      εQ.apply_symm_apply]

/-- The permutations of `Q` and of `Q'` correspond under a group isomorphism. -/
theorem permCongr_image_Q (hS : Setup M Q D t) (hS' : Setup M' Q' D' t')
    (εQ : ↥Q ≃* ↥Q') :
    (Equiv.permCongrHom (Equiv.optionCongr εQ.toEquiv)) '' (permHom hS '' (Q : Set L))
      = permHom hS' '' (Q' : Set L') := by
  ext σ
  simp only [Set.mem_image]
  constructor
  · rintro ⟨τ, ⟨q, hq, rfl⟩, rfl⟩
    exact ⟨((εQ ⟨q, hq⟩ : ↥Q') : L'), (εQ ⟨q, hq⟩).2,
      (permCongrHom_permHom_mem_Q hS hS' εQ ⟨q, hq⟩).symm⟩
  · rintro ⟨q', hq', rfl⟩
    refine ⟨permHom hS ((εQ.symm ⟨q', hq'⟩ : ↥Q) : L),
      ⟨((εQ.symm ⟨q', hq'⟩ : ↥Q) : L), (εQ.symm ⟨q', hq'⟩).2, rfl⟩, ?_⟩
    rw [permCongrHom_permHom_mem_Q hS hS' εQ (εQ.symm ⟨q', hq'⟩), εQ.apply_symm_apply]

/-- **The first half of the Lemma of Peterfalvi Part II, Ch. IV §1** (p. 123), in the
book's terms: `⟨Q^x | x ∈ L⟩` is determined up to isomorphism by `Q` and `f`.

Only a group isomorphism `Q ≃* Q'` intertwining `f` with `f'` is needed — the action of
`Q` on the point set is translation (`mAct_of_mem_Q`), so no separate compatibility is
required, and `t` contributes exactly `f` (`permCongrHom_permHom_t`). -/
noncomputable def conjQMulEquivOfData (hS : Setup M Q D t) (hS' : Setup M' Q' D' t')
    (H : IsFGH M Q D t f g h) (H' : IsFGH M' Q' D' t' f' g' h')
    (hcore : M.normalCore = ⊥) (hcore' : M'.normalCore = ⊥)
    (εQ : ↥Q ≃* ↥Q')
    (hεf : ∀ (x : ↥Q) (hx1 : (x : L) ≠ 1),
      ((εQ ⟨f (x : L), H.f_mem x.2 hx1⟩ : ↥Q') : L') = f' ((εQ x : ↥Q') : L')) :
    ↥(Subgroup.closure (⋃ y : L, ((fun q => y⁻¹ * q * y) '' (Q : Set L))))
      ≃* ↥(Subgroup.closure (⋃ y : L', ((fun q => y⁻¹ * q * y) '' (Q' : Set L')))) :=
  conjQMulEquivOfPermMatch hS hS' hcore hcore' (Equiv.optionCongr εQ.toEquiv)
    (permCongrHom_permHom_t hS hS' H H' εQ.toEquiv (map_one εQ) hεf)
    (permCongr_image_Q hS hS' εQ)

/-- **The Lemma of Peterfalvi Part II, Ch. IV §1** (p. 123), in the book's terms:
`L` is determined up to isomorphism by `M = Q ⋊ D` and `f`.

`εQ` identifies the two point sets `Q`, `Q'` compatibly with the base point and with
`f`; `θ` identifies `M` with `M'` compatibly with their `Q ⋊ D` actions on those point
sets.  Faithfulness is `M.normalCore = ⊥`. -/
noncomputable def mulEquivOfData (hS : Setup M Q D t) (hS' : Setup M' Q' D' t')
    (H : IsFGH M Q D t f g h) (H' : IsFGH M' Q' D' t' f' g' h')
    (hcore : M.normalCore = ⊥) (hcore' : M'.normalCore = ⊥)
    (εQ : ↥Q ≃ ↥Q') (hε1 : εQ 1 = 1)
    (hεf : ∀ (x : ↥Q) (hx1 : (x : L) ≠ 1),
      ((εQ ⟨f (x : L), H.f_mem x.2 hx1⟩ : ↥Q') : L') = f' ((εQ x : ↥Q') : L'))
    (θ : ↥M ≃* ↥M')
    (hθ : ∀ (m : ↥M) (x : ↥Q), εQ (mAct hS m x) = mAct hS' (θ m) (εQ x)) :
    L ≃* L' :=
  mulEquivOfPermMatch hS hS' hcore hcore' (Equiv.optionCongr εQ)
    (permCongrHom_permHom_t hS hS' H H' εQ hε1 hεf)
    (by
      ext σ
      simp only [Set.mem_image]
      constructor
      · rintro ⟨τ, ⟨m, hm, rfl⟩, rfl⟩
        exact ⟨((θ ⟨m, hm⟩ : ↥M') : L'), (θ ⟨m, hm⟩).2,
          (permCongrHom_permHom_mem_M hS hS' εQ θ hθ ⟨m, hm⟩).symm⟩
      · rintro ⟨m', hm', rfl⟩
        refine ⟨permHom hS ((θ.symm ⟨m', hm'⟩ : ↥M) : L),
          ⟨((θ.symm ⟨m', hm'⟩ : ↥M) : L), (θ.symm ⟨m', hm'⟩).2, rfl⟩, ?_⟩
        rw [permCongrHom_permHom_mem_M hS hS' εQ θ hθ (θ.symm ⟨m', hm'⟩),
          θ.apply_symm_apply])

/-! ## Faithfulness

`Hypothesis.ofRankOneSetup` asks for `M.normalCore = ⊥`.  `Setup.normalCore_le_center`
reduces that to `L` being generated by the conjugates of `Q` plus a trivial centre, and
when `Q` is a Sylow `p`-subgroup the generation is `O^{p′}(L) = ⊤`. -/

/-- **`L` is generated by `Q` and `Q^t`** when `Q` is a Sylow `p`-subgroup and `L` has no
non-trivial `p′`-quotient. -/
theorem Setup.closure_Q_union_conj_eq_top [Finite L] {p : ℕ} [Fact p.Prime]
    (hS : Setup M Q D t) (P : Sylow p L) (hPQ : (P : Subgroup L) = Q)
    (htop : Subgroup.primeComplementResidual p L = ⊤) :
    Subgroup.closure ((Q : Set L) ∪ (fun z => t * z * t) '' (Q : Set L)) = ⊤ := by
  have h := closure_iUnion_conj_eq_primeComplementResidual P
  rw [hPQ, htop] at h
  rw [← hS.closure_conj_Q, h]

/-- **`M` has trivial normal core** — the faithfulness input of
`Hypothesis.ofRankOneSetup`, for a setup whose `Q` is a Sylow `p`-subgroup, in a group
with no non-trivial `p′`-quotient and with trivial centre. -/
theorem Setup.normalCore_eq_bot [Finite L] {p : ℕ} [Fact p.Prime]
    (hS : Setup M Q D t) (P : Sylow p L) (hPQ : (P : Subgroup L) = Q)
    (htop : Subgroup.primeComplementResidual p L = ⊤)
    (hcenter : Subgroup.center L = ⊥) :
    M.normalCore = ⊥ := by
  rw [eq_bot_iff, ← hcenter]
  exact hS.normalCore_le_center (hS.closure_Q_union_conj_eq_top P hPQ htop)

/-- **`M` has trivial normal core when `L` is simple** — `M` is a proper subgroup because
`t ∉ M`, so its normal core, being normal, cannot be `⊤`.

Peterfalvi Ch. IV §4, step (2) (p. 133) applies `Hypothesis.ofRankOneSetup` to
`L = U/Z(U)`, which Ch. I §3 Proposition 1(c) identifies with `PSU(3, ℓ)`; simplicity of
that group is Ch. I §3 Lemma 1, so this is the cheapest of the two faithfulness routes. -/
theorem Setup.normalCore_eq_bot_of_isSimpleGroup [IsSimpleGroup L] (hS : Setup M Q D t) :
    M.normalCore = ⊥ := by
  rcases (Subgroup.normalCore_normal M).eq_bot_or_eq_top with hbot | htop
  · exact hbot
  · refine absurd (M.normalCore_le ?_) hS.tnotmem
    rw [htop]
    exact Subgroup.mem_top t

/-! ## The order formula, and `Q` as a Sylow subgroup

`M = Q ⋊ D` and `L ⧸ M ≅ Q ∪ {a}` give `|L| = |Q| · |D| · (1 + |Q|)`.  When `Q` is a
`2`-group and `|D|` is odd, the other two factors are odd, so `Q` is a Sylow
`2`-subgroup — which is what identifies `M` with its normalizer, and hence identifies the
standing hypothesis up to conjugacy (Peterfalvi Part II, Ch. IV §4, step (2), p. 133). -/

/-- `|M| = |Q| · |D|`: the decomposition `M = Q ⋊ D` is a bijection `Q × D ≃ M`. -/
theorem Setup.natCard_M [Finite L] (hS : Setup M Q D t) :
    Nat.card ↥M = Nat.card ↥Q * Nat.card ↥D := by
  classical
  have hf : Function.Bijective (fun p : ↥Q × ↥D => (⟨(p.1 : L) * (p.2 : L),
      M.mul_mem (hS.QM p.1.2) (hS.DM p.2.2)⟩ : ↥M)) := by
    constructor
    · rintro ⟨q, d⟩ ⟨q', d'⟩ hqd
      have hval : (q : L) * (d : L) = (q' : L) * (d' : L) := congrArg Subtype.val hqd
      obtain ⟨p₀, -, huniq⟩ :=
        hS.split ((q : L) * (d : L)) (M.mul_mem (hS.QM q.2) (hS.DM d.2))
      exact (huniq (q, d) rfl).trans (huniq (q', d') hval).symm
    · rintro ⟨a, ha⟩
      obtain ⟨⟨q, d⟩, hqd, -⟩ := hS.split a ha
      exact ⟨(q, d), Subtype.ext hqd.symm⟩
  rw [← Nat.card_congr (Equiv.ofBijective _ hf), Nat.card_prod]

/-- `[L : M] = 1 + |Q|`, because `L ⧸ M ≅ Q ∪ {a}` (Ch. IV §1, p. 123). -/
theorem Setup.index_M [Finite L] (hS : Setup M Q D t) :
    M.index = Nat.card ↥Q + 1 := by
  classical
  rw [Subgroup.index, ← Nat.card_congr (coordsEquiv hS)]
  simp

/-- **`|L| = |Q| · |D| · (1 + |Q|)`.** -/
theorem Setup.natCard_L [Finite L] (hS : Setup M Q D t) :
    Nat.card L = Nat.card ↥Q * (Nat.card ↥D * (Nat.card ↥Q + 1)) := by
  rw [← Subgroup.card_mul_index M, hS.natCard_M, hS.index_M, mul_assoc]

/-- **`Q` is a Sylow `2`-subgroup of `L`** when it is a `2`-group and `|D|` is odd: the
index `|D| · (1 + |Q|)` is then odd, so no `2`-subgroup properly contains `Q`. -/
theorem Setup.exists_sylow_two_eq [Finite L] (hS : Setup M Q D t) (hQ : IsPGroup 2 ↥Q)
    (hDodd : Odd (Nat.card ↥D)) (hQeven : Even (Nat.card ↥Q)) :
    ∃ S : Sylow 2 L, (S : Subgroup L) = Q := by
  classical
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  obtain ⟨S, hQS⟩ := hQ.exists_le_sylow
  refine ⟨S, (Subgroup.eq_of_le_of_card_ge hQS ?_).symm⟩
  obtain ⟨k, hk⟩ := S.2.exists_card_eq
  obtain ⟨j, hj⟩ := hQ.exists_card_eq
  have hodd : Odd (Nat.card ↥D * (Nat.card ↥Q + 1)) := hDodd.mul hQeven.add_one
  have hdvd : (2 : ℕ) ^ k ∣ 2 ^ j * (Nat.card ↥D * (Nat.card ↥Q + 1)) := by
    rw [← hk, ← hj, ← hS.natCard_L]
    exact Subgroup.card_subgroup_dvd_card _
  have hcop : Nat.Coprime ((2 : ℕ) ^ k) (Nat.card ↥D * (Nat.card ↥Q + 1)) :=
    Nat.Coprime.pow_left k (Nat.coprime_two_left.mpr hodd)
  have hpow : (2 : ℕ) ^ k ∣ 2 ^ j := hcop.dvd_of_dvd_mul_right hdvd
  rw [hk, hj]
  exact Nat.le_of_dvd (by positivity) hpow

/-- **`M = N_L(Q)`** — `M` normalizes `Q` (`Setup.conj_mem_Q`), and nothing outside does:
an `x ∉ M` factors as `a · t · b` with `a ∈ M` and `b ∈ Q`, so `t` would normalize `Q`
too, and then `t q t ∈ Q ≤ M` for `q ∈ Q^#` contradicts `Setup.tconj`.

Together with `Setup.exists_sylow_two_eq` this is the rigidity Ch. IV §4, step (2) needs:
two setups on the same group have conjugate `Q`s (Sylow), hence conjugate `M`s. -/
theorem Setup.normalizer_Q_eq (hS : Setup M Q D t) (hQ1 : Q ≠ ⊥) :
    Subgroup.normalizer Q = M := by
  have hMle : M ≤ Subgroup.normalizer Q := fun m hm =>
    Subgroup.mem_normalizer_iff.mpr fun n =>
      ⟨fun hn => by
        have hc := hS.conj_mem_Q (M.inv_mem hm) hn
        rwa [inv_inv] at hc,
       fun hn => by
        have hc := hS.conj_mem_Q hm hn
        have e : m⁻¹ * (m * n * m⁻¹) * m = n := by group
        rwa [e] at hc⟩
  refine le_antisymm (fun x hx => ?_) hMle
  by_contra hxM
  obtain ⟨p, hp, -⟩ := hS.fact x hxM
  have htN : t ∈ Subgroup.normalizer Q := by
    have he : t = (p.1 : L)⁻¹ * x * (p.2 : L)⁻¹ := by rw [hp]; group
    have h1 : (p.1 : L)⁻¹ ∈ Subgroup.normalizer (Q : Set L) := inv_mem (hMle p.1.2)
    have h2 : (p.2 : L)⁻¹ ∈ Subgroup.normalizer (Q : Set L) :=
      inv_mem (Subgroup.le_normalizer p.2.2)
    rw [he]
    exact mul_mem (mul_mem h1 hx) h2
  obtain ⟨q, hqQ, hq1⟩ : ∃ q ∈ Q, q ≠ 1 := by
    by_contra hc
    refine hQ1 (eq_bot_iff.mpr fun z hz => Subgroup.mem_bot.mpr ?_)
    by_contra hz1
    exact hc ⟨z, hz, hz1⟩
  refine hS.tconj q hqQ hq1 ?_
  have hmem := (Subgroup.mem_normalizer_iff.mp htN q).mp hqQ
  rw [hS.tinv] at hmem
  exact hS.QM hmem

/-- **Two rank-one setups on the same group have conjugate `Q` and `M`.**

Both `Q`s are Sylow `2`-subgroups (`Setup.exists_sylow_two_eq`), hence conjugate; and
`M = N_L(Q)` (`Setup.normalizer_Q_eq`), so the same conjugation carries `M` to `M'`.

Peterfalvi Part II, Ch. IV §4, step (2) (p. 133) compares the setup `U/Z(U)` inherits
from `U` with the one Ch. I §3 Proposition 1(c) transports from the standard `PSU(3, ℓ)`;
this is the first half of that comparison. -/
theorem Setup.exists_conj_eq [Finite L] {M' Q' D' : Subgroup L} {t' : L}
    (hS : Setup M Q D t) (hS' : Setup M' Q' D' t')
    (hQ : IsPGroup 2 ↥Q) (hDodd : Odd (Nat.card ↥D)) (hQeven : Even (Nat.card ↥Q))
    (hQ' : IsPGroup 2 ↥Q') (hDodd' : Odd (Nat.card ↥D')) (hQeven' : Even (Nat.card ↥Q'))
    (hQ1 : Q ≠ ⊥) (hQ1' : Q' ≠ ⊥) :
    ∃ c : L, Q.map (MulAut.conj c).toMonoidHom = Q' ∧
      M.map (MulAut.conj c).toMonoidHom = M' := by
  classical
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  obtain ⟨S, hSQ⟩ := hS.exists_sylow_two_eq hQ hDodd hQeven
  obtain ⟨S', hSQ'⟩ := hS'.exists_sylow_two_eq hQ' hDodd' hQeven'
  obtain ⟨c, hc⟩ := MulAction.exists_smul_eq L S S'
  have hQc : Q.map (MulAut.conj c).toMonoidHom = Q' := by
    rw [← hSQ, ← hSQ', ← hc]
    rfl
  refine ⟨c, hQc, ?_⟩
  rw [← hS.normalizer_Q_eq hQ1, Subgroup.map_equiv_normalizer_eq Q (MulAut.conj c), hQc,
    hS'.normalizer_Q_eq hQ1']

/-- Two rank-one setups on the same group have the same `|Q|` and the same `|D|` — both
factors of `|L| = |Q| · |D| · (1 + |Q|)` are determined, because `Q` is a Sylow
`2`-subgroup. -/
theorem Setup.natCard_eq_of_setup [Finite L] {M' Q' D' : Subgroup L} {t' : L}
    (hS : Setup M Q D t) (hS' : Setup M' Q' D' t')
    (hQ : IsPGroup 2 ↥Q) (hDodd : Odd (Nat.card ↥D)) (hQeven : Even (Nat.card ↥Q))
    (hQ' : IsPGroup 2 ↥Q') (hDodd' : Odd (Nat.card ↥D')) (hQeven' : Even (Nat.card ↥Q'))
    (hQ1 : Q ≠ ⊥) (hQ1' : Q' ≠ ⊥) :
    Nat.card ↥Q = Nat.card ↥Q' ∧ Nat.card ↥D = Nat.card ↥D' := by
  obtain ⟨c, hQc, hMc⟩ :=
    hS.exists_conj_eq hS' hQ hDodd hQeven hQ' hDodd' hQeven' hQ1 hQ1'
  have hcard : ∀ K : Subgroup L,
      Nat.card ↥(K.map (MulAut.conj c).toMonoidHom) = Nat.card ↥K := fun K =>
    (Nat.card_congr (Subgroup.equivMapOfInjective K (MulAut.conj c).toMonoidHom
      (MulAut.conj c).injective).toEquiv).symm
  have hQeq : Nat.card ↥Q = Nat.card ↥Q' := by rw [← hQc, hcard]
  refine ⟨hQeq, ?_⟩
  have hMeq : Nat.card ↥M = Nat.card ↥M' := by rw [← hMc, hcard]
  have h1 := hS.natCard_M
  have h2 := hS'.natCard_M
  rw [hMeq, h2, hQeq] at h1
  have hpos : 0 < Nat.card ↥Q' := Nat.card_pos
  exact Nat.eq_of_mul_eq_mul_left hpos h1.symm

end OddOrder.GroupTheory.RankOneBNPair
