/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.GroupTheory.OmegaSubgroup

/-!
# `p`-groups of class less than `p`

A `p`-group whose nilpotence class is smaller than `p` behaves, for the purposes
of `p`-th powers, like an abelian group: its elements of order dividing `p` form
a subgroup.  This is the group-theoretic pay-off of Hall's collection formula
(Bender–Glauberman Theorem E.1, proved in
`OddOrder/GroupTheory/HallPetresco.lean`), and it is BG Proposition E.2.

This file collects the two reductions the proof of E.2 runs on, both of them
generic:

* the class bound passes to subgroups (`lowerCentralSeries_eq_bot_of_subgroup`),
  which is what makes an induction on `|G|` possible;
* to know that `Ω₁(G)` has exponent `p` it suffices to know that the `p`-torsion
  elements are closed under multiplication
  (`Omega.pow_eq_one_of_mul_closed`), because then they already form a subgroup.
-/

namespace OddOrder.GroupTheory

variable {G : Type*} [Group G]

/-! ## The class bound passes to subgroups -/

/-- A bound on the nilpotence class is inherited by every subgroup: if
`γ_{n+1}(G) = 1` then `γ_{n+1}(H) = 1` for every `H ≤ G`.  (Indices are
mathlib's: `lowerCentralSeries n` is the book's `γ_{n+1}`.) -/
theorem lowerCentralSeries_eq_bot_of_subgroup (H : Subgroup G) {n : ℕ}
    (h : (⊤ : Subgroup G).lowerCentralSeries n = ⊥) :
    (⊤ : Subgroup ↥H).lowerCentralSeries n = ⊥ := by
  have hmap := Subgroup.top_subtype_lowerCentralSeries H n
  have hle : H.lowerCentralSeries n ≤ (⊤ : Subgroup G).lowerCentralSeries n :=
    Subgroup.lowerCentralSeries_mono n le_top
  rw [h, le_bot_iff] at hle
  rw [hle, Subgroup.map_eq_bot_iff, H.ker_subtype, le_bot_iff] at hmap
  exact hmap

/-! ## Reducing `Ω₁` to closure under multiplication -/

namespace Omega

/-- If the elements of order dividing `p` are closed under multiplication then
they already form a subgroup, so `Ω₁` consists of exactly those elements — in
particular `Ω₁` has exponent dividing `p`. -/
theorem pow_eq_one_of_mul_closed {p : ℕ}
    (hclosed : ∀ x y : G, x ^ p = 1 → y ^ p = 1 → (x * y) ^ p = 1)
    {g : G} (hg : g ∈ Omega G p 1) : g ^ p = 1 := by
  let S : Subgroup G :=
    { carrier := {x : G | x ^ p = 1}
      one_mem' := one_pow p
      mul_mem' := fun {x y} hx hy => hclosed x y hx hy
      inv_mem' := fun {x} hx => by
        simp only [Set.mem_setOf_eq] at hx ⊢
        rw [inv_pow, hx, inv_one] }
  have hsub : Omega G p 1 ≤ S := by
    refine Subgroup.closure_le S |>.mpr fun x hx => ?_
    simpa [S, pow_one] using hx
  exact hsub hg

end Omega

/-! ## The `p`-torsion of a normal subgroup -/

/-- The elements of order dividing `p` inside a subgroup `M`, given that they are
closed under multiplication.  Taking them as an explicit subgroup of the *ambient*
group — rather than pushing `Ω₁(M)` forward along `M.subtype` — makes normality
immediate, since conjugation visibly preserves both conditions. -/
def torsionOf (M : Subgroup G) (p : ℕ)
    (hclosed : ∀ a b : G, a ∈ M → b ∈ M → a ^ p = 1 → b ^ p = 1 → (a * b) ^ p = 1) :
    Subgroup G where
  carrier := {g : G | g ∈ M ∧ g ^ p = 1}
  one_mem' := ⟨M.one_mem, one_pow p⟩
  mul_mem' := fun {a b} ha hb => ⟨M.mul_mem ha.1 hb.1, hclosed a b ha.1 hb.1 ha.2 hb.2⟩
  inv_mem' := fun {a} ha => ⟨M.inv_mem ha.1, by rw [inv_pow, ha.2, inv_one]⟩

@[simp] theorem mem_torsionOf {M : Subgroup G} {p : ℕ} {hclosed} {g : G} :
    g ∈ torsionOf M p hclosed ↔ g ∈ M ∧ g ^ p = 1 := Iff.rfl

/-- The `p`-torsion of a normal subgroup is normal. -/
instance torsionOf_normal (M : Subgroup G) [hM : M.Normal] (p : ℕ) (hclosed) :
    (torsionOf M p hclosed).Normal :=
  ⟨fun a ha g => ⟨hM.conj_mem a ha.1 g, by rw [conj_pow, ha.2, mul_one, mul_inv_cancel]⟩⟩

/-! ## Two-generator groups with one generator in a normal subgroup -/

/-- If `G` is generated by `x` and `y` and `y` already lies in a normal subgroup
`N`, then `G / N` is generated by the image of `x`, hence abelian, so `G' ≤ N`. -/
theorem commutator_le_of_closure_pair (N : Subgroup G) [N.Normal] {x y : G}
    (hgen : Subgroup.closure ({x, y} : Set G) = ⊤) (hyN : y ∈ N) :
    _root_.commutator G ≤ N := by
  have hy1 : (QuotientGroup.mk' N) y = 1 := (QuotientGroup.eq_one_iff y).mpr hyN
  have htop : (⊤ : Subgroup (G ⧸ N)) = Subgroup.zpowers ((QuotientGroup.mk' N) x) := by
    rw [← Subgroup.map_top_of_surjective _ (QuotientGroup.mk'_surjective N), ← hgen,
      MonoidHom.map_closure]
    have himg : (QuotientGroup.mk' N) '' ({x, y} : Set G) = {(QuotientGroup.mk' N) x, 1} := by
      rw [Set.image_insert_eq, Set.image_singleton, hy1]
    rw [himg, Subgroup.zpowers_eq_closure]
    refine le_antisymm (Subgroup.closure_le _ |>.mpr fun z hz => ?_)
      (Subgroup.closure_mono (Set.singleton_subset_iff.mpr (Set.mem_insert _ _)))
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
    rcases hz with rfl | rfl
    · exact Subgroup.subset_closure rfl
    · exact Subgroup.one_mem _
  have hcomm : ∀ a b : G ⧸ N, Commute a b := by
    intro a b
    obtain ⟨i, hi⟩ : a ∈ Subgroup.zpowers ((QuotientGroup.mk' N) x) := htop ▸ Subgroup.mem_top a
    obtain ⟨j, hj⟩ : b ∈ Subgroup.zpowers ((QuotientGroup.mk' N) x) := htop ▸ Subgroup.mem_top b
    rw [← hi, ← hj]
    exact (Commute.refl _).zpow_zpow i j
  refine Subgroup.commutator_le.mpr fun a _ b _ => ?_
  rw [← QuotientGroup.eq_one_iff, ← QuotientGroup.mk'_apply, map_commutatorElement]
  exact (hcomm _ _).commutator_eq

/-! ## Proper subgroups are smaller -/

/-- A proper subgroup of a finite group has strictly smaller order. -/
theorem card_lt_card_of_lt_top [Finite G] {H : Subgroup G} (h : H ≠ ⊤) :
    Nat.card ↥H < Nat.card G := by
  rcases lt_or_eq_of_le
      (Nat.card_le_card_of_injective H.subtype Subtype.val_injective) with hlt | heq
  · exact hlt
  · exact absurd (Subgroup.eq_top_of_card_eq H heq) h

end OddOrder.GroupTheory
