/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.Data.Nat.Choose.Dvd
import OddOrder.GroupTheory.HallPetresco
import OddOrder.GroupTheory.OmegaSubgroup

/-!
# `p`-groups of class less than `p`

A `p`-group whose nilpotence class is smaller than `p` behaves, for the purposes
of `p`-th powers, like an abelian group: its elements of order dividing `p` form
a subgroup.  This is the group-theoretic pay-off of Hall's collection formula
(Bender–Glauberman Theorem E.1, proved in
`OddOrder/GroupTheory/HallPetresco.lean`), and it is BG Proposition E.2.

## Main results

* `pow_mul_pow_eq_pow_of_commutator_exponent` — BG Proposition E.2, Step 1: if
  the class is `< p` and `G'` has exponent dividing `p`, the `p`-power map is
  multiplicative.  This is Hall's formula with every intermediate term killed,
  either by `p ∣ C(p, k)` or by `γ_p = 1`.
* `pow_mul_eq_one_of_class_lt` — **BG Proposition E.2(a)**, core induction: in a
  finite group of class `< p` the elements of order dividing `p` are closed under
  multiplication.  Combined with `Omega.pow_eq_one_of_mul_closed` this says that
  `Ω₁` has exponent dividing `p`.

The supporting reductions, all generic: the class bound passes to subgroups
(`lowerCentralSeries_eq_bot_of_subgroup`), which is what makes the induction on
`|G|` possible; the `p`-torsion of a normal subgroup is itself a normal subgroup
(`torsionOf`, `torsionOf_normal`); and a two-generator group with one generator
inside a normal subgroup `N` has `G' ≤ N` (`commutator_le_of_closure_pair`).
-/

namespace OddOrder.GroupTheory

universe u

variable {G : Type*} [Group G]

/-! ## The class bound passes to subgroups -/

/-- A bound on the nilpotence class is inherited by every subgroup: if
`γ_{n+1}(G) = 1` then `γ_{n+1}(H) = 1` for every `H ≤ G`.  (Indices are
mathlib's: `lowerCentralSeries n` is the book's `γ_{n+1}`.) -/
theorem lowerCentralSeries_eq_bot_of_subgroup (H : Subgroup G) {n : ℕ}
    (h : (⊤ : Subgroup G).lowerCentralSeries n = ⊥) :
    (⊤ : Subgroup ↥H).lowerCentralSeries n = ⊥ := by
  have hmap := Subgroup.top_subtype_lowerCentralSeries H n
  have hle : H.lowerCentralSeries n ≤ (⊤ : Subgroup G).lowerCentralSeries n :=
    Subgroup.lowerCentralSeries_mono n le_top
  rw [h, le_bot_iff] at hle
  rw [hle, Subgroup.map_eq_bot_iff, H.ker_subtype, le_bot_iff] at hmap
  exact hmap

/-! ## Reducing `Ω₁` to closure under multiplication -/

namespace Omega

/-- If the elements of order dividing `p` are closed under multiplication then
they already form a subgroup, so `Ω₁` consists of exactly those elements — in
particular `Ω₁` has exponent dividing `p`. -/
theorem pow_eq_one_of_mul_closed {p : ℕ}
    (hclosed : ∀ x y : G, x ^ p = 1 → y ^ p = 1 → (x * y) ^ p = 1)
    {g : G} (hg : g ∈ Omega G p 1) : g ^ p = 1 := by
  let S : Subgroup G :=
    { carrier := {x : G | x ^ p = 1}
      one_mem' := one_pow p
      mul_mem' := fun {x y} hx hy => hclosed x y hx hy
      inv_mem' := fun {x} hx => by
        simp only [Set.mem_setOf_eq] at hx ⊢
        rw [inv_pow, hx, inv_one] }
  have hsub : Omega G p 1 ≤ S := by
    refine Subgroup.closure_le S |>.mpr fun x hx => ?_
    simpa [S, pow_one] using hx
  exact hsub hg

end Omega

/-! ## The `p`-torsion of a normal subgroup -/

/-- The elements of order dividing `p` inside a subgroup `M`, given that they are
closed under multiplication.  Taking them as an explicit subgroup of the *ambient*
group — rather than pushing `Ω₁(M)` forward along `M.subtype` — makes normality
immediate, since conjugation visibly preserves both conditions. -/
def torsionOf (M : Subgroup G) (p : ℕ)
    (hclosed : ∀ a b : G, a ∈ M → b ∈ M → a ^ p = 1 → b ^ p = 1 → (a * b) ^ p = 1) :
    Subgroup G where
  carrier := {g : G | g ∈ M ∧ g ^ p = 1}
  one_mem' := ⟨M.one_mem, one_pow p⟩
  mul_mem' := fun {a b} ha hb => ⟨M.mul_mem ha.1 hb.1, hclosed a b ha.1 hb.1 ha.2 hb.2⟩
  inv_mem' := fun {a} ha => ⟨M.inv_mem ha.1, by rw [inv_pow, ha.2, inv_one]⟩

@[simp] theorem mem_torsionOf {M : Subgroup G} {p : ℕ} {hclosed} {g : G} :
    g ∈ torsionOf M p hclosed ↔ g ∈ M ∧ g ^ p = 1 := Iff.rfl

/-- The `p`-torsion of a normal subgroup is normal. -/
instance torsionOf_normal (M : Subgroup G) [hM : M.Normal] (p : ℕ) (hclosed) :
    (torsionOf M p hclosed).Normal :=
  ⟨fun a ha g => ⟨hM.conj_mem a ha.1 g, by rw [conj_pow, ha.2, mul_one, mul_inv_cancel]⟩⟩

/-! ## Two-generator groups with one generator in a normal subgroup -/

/-- If `G` is generated by `x` and `y` and `y` already lies in a normal subgroup
`N`, then `G / N` is generated by the image of `x`, hence abelian, so `G' ≤ N`. -/
theorem commutator_le_of_closure_pair (N : Subgroup G) [N.Normal] {x y : G}
    (hgen : Subgroup.closure ({x, y} : Set G) = ⊤) (hyN : y ∈ N) :
    _root_.commutator G ≤ N := by
  have hy1 : (QuotientGroup.mk' N) y = 1 := (QuotientGroup.eq_one_iff y).mpr hyN
  have htop : (⊤ : Subgroup (G ⧸ N)) = Subgroup.zpowers ((QuotientGroup.mk' N) x) := by
    rw [← Subgroup.map_top_of_surjective _ (QuotientGroup.mk'_surjective N), ← hgen,
      MonoidHom.map_closure]
    have himg : (QuotientGroup.mk' N) '' ({x, y} : Set G) = {(QuotientGroup.mk' N) x, 1} := by
      rw [Set.image_insert_eq, Set.image_singleton, hy1]
    rw [himg, Subgroup.zpowers_eq_closure]
    refine le_antisymm (Subgroup.closure_le _ |>.mpr fun z hz => ?_)
      (Subgroup.closure_mono (Set.singleton_subset_iff.mpr (Set.mem_insert _ _)))
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
    rcases hz with rfl | rfl
    · exact Subgroup.subset_closure rfl
    · exact Subgroup.one_mem _
  have hcomm : ∀ a b : G ⧸ N, Commute a b := by
    intro a b
    obtain ⟨i, hi⟩ : a ∈ Subgroup.zpowers ((QuotientGroup.mk' N) x) := htop ▸ Subgroup.mem_top a
    obtain ⟨j, hj⟩ : b ∈ Subgroup.zpowers ((QuotientGroup.mk' N) x) := htop ▸ Subgroup.mem_top b
    rw [← hi, ← hj]
    exact (Commute.refl _).zpow_zpow i j
  refine Subgroup.commutator_le.mpr fun a _ b _ => ?_
  rw [← QuotientGroup.eq_one_iff, ← QuotientGroup.mk'_apply, map_commutatorElement]
  exact (hcomm _ _).commutator_eq

/-! ## Proper subgroups are smaller -/

/-- A proper subgroup of a finite group has strictly smaller order. -/
theorem card_lt_card_of_lt_top [Finite G] {H : Subgroup G} (h : H ≠ ⊤) :
    Nat.card ↥H < Nat.card G := by
  rcases lt_or_eq_of_le
      (Nat.card_le_card_of_injective H.subtype Subtype.val_injective) with hlt | heq
  · exact hlt
  · exact absurd (Subgroup.eq_top_of_card_eq H heq) h

/-! ## The `p`-power map on a group of class `< p`

Hall's collection formula turns into a statement about `p`-th powers as soon as
the derived subgroup has exponent `p`: every intermediate term of the collection
is killed, either because `p ∣ C(p, k)` for `1 < k < p` or because `γ_p = 1`.
-/

/-- **The `p`-power map is multiplicative** on a group of class `< p` whose
derived subgroup has exponent dividing `p`.  (BG Proposition E.2, Step 1.) -/
theorem pow_mul_pow_eq_pow_of_commutator_exponent {p : ℕ} (hp : p.Prime)
    (hgamma : (⊤ : Subgroup G).lowerCentralSeries (p - 1) = ⊥)
    (hexp : ∀ g ∈ _root_.commutator G, g ^ p = 1) (x y : G) :
    x ^ p * y ^ p = (x * y) ^ p := by
  have hp2 := hp.two_le
  obtain ⟨m, rfl⟩ : ∃ m, p = m + 1 := ⟨p - 1, by omega⟩
  simp only [Nat.add_sub_cancel] at hgamma
  obtain ⟨τ, hmem, hτ1, hprod⟩ :=
    HallPetresco.exists_hallPetresco (G := G) [x, y] (Nat.le_add_left 1 m)
  have hlhs : (([x, y] : List G).map fun g => g ^ (m + 1)).prod = x ^ (m + 1) * y ^ (m + 1) := by
    simp
  rw [hlhs, List.range'_succ, List.map_cons, List.prod_cons, Nat.choose_one_right] at hprod
  have hτ : τ 1 = x * y := by simpa using hτ1
  have htail : ((List.range' 2 m).map fun k => τ k ^ (m + 1).choose k).prod = 1 := by
    refine List.prod_eq_one fun z hz => ?_
    obtain ⟨k, hk, rfl⟩ := List.mem_map.mp hz
    obtain ⟨hk2, hklt⟩ := List.mem_range'_1.mp hk
    have hkle : k ≤ m + 1 := by omega
    have hmemk := hmem k (by omega) hkle
    rcases eq_or_lt_of_le hkle with rfl | hlt
    · rw [Nat.add_sub_cancel, hgamma, Subgroup.mem_bot] at hmemk
      rw [hmemk, one_pow]
    · have hle : (⊤ : Subgroup G).lowerCentralSeries (k - 1) ≤
          (⊤ : Subgroup G).lowerCentralSeries 1 :=
        Subgroup.lowerCentralSeries_antitone ⊤ (by omega)
      rw [Subgroup.top_lowerCentralSeries_one] at hle
      obtain ⟨j, hj⟩ := Nat.Prime.dvd_choose_self hp (by omega) hlt
      rw [hj, pow_mul, hexp _ (hle hmemk), one_pow]
  rw [hprod, hτ, htail, mul_one]

/-! ## The main induction -/

/-- **BG Proposition E.2(a), core induction.**  In a finite group of nilpotence
class at most `p - 1` the elements of order dividing `p` are closed under
multiplication.

The induction is on `|R|`.  If `x` and `y` generate a proper subgroup, or if `y`
generates the whole group, there is nothing to do.  Otherwise a maximal subgroup
`M ⊇ ⟨y⟩` is normal (the group is nilpotent), the induction hypothesis makes the
`p`-torsion of `M` a subgroup `N ⊴ R` containing `y`, the quotient `R / N` is
generated by the image of `x` and hence abelian, so `R' ≤ N` has exponent `p` —
and then Step 1 applies. -/
theorem pow_mul_eq_one_of_class_lt {p : ℕ} (hp : p.Prime) :
    ∀ (n : ℕ) (R : Type u) [Group R] [Finite R], Nat.card R < n →
      (⊤ : Subgroup R).lowerCentralSeries (p - 1) = ⊥ →
      ∀ x y : R, x ^ p = 1 → y ^ p = 1 → (x * y) ^ p = 1 := by
  intro n
  induction n with
  | zero => intro R _ _ hcard; exact absurd hcard (by omega)
  | succ n ih =>
      intro R _ _ hcard hgamma x y hx hy
      by_cases hgen : Subgroup.closure ({x, y} : Set R) = ⊤
      · by_cases hycyc : Subgroup.zpowers y = ⊤
        · obtain ⟨k, hk⟩ : x * y ∈ Subgroup.zpowers y := hycyc ▸ Subgroup.mem_top _
          rw [← hk, ← zpow_natCast, ← zpow_mul, mul_comm, zpow_mul, zpow_natCast, hy, one_zpow]
        · haveI hnil : Group.IsNilpotent R :=
            Subgroup.nilpotent_iff_lowerCentralSeries.mpr ⟨p - 1, hgamma⟩
          obtain ⟨M, hMco, hyM⟩ :=
            (IsCoatomic.eq_top_or_exists_le_coatom (Subgroup.zpowers y)).resolve_left hycyc
          have htfae := (Group.isNilpotent_of_finite_tfae (G := R)).out 0 2
          haveI : M.Normal := htfae.mp hnil M hMco
          have hcardM : Nat.card ↥M < Nat.card R := card_lt_card_of_lt_top hMco.1
          have hMclosed : ∀ a b : R, a ∈ M → b ∈ M → a ^ p = 1 → b ^ p = 1 →
              (a * b) ^ p = 1 := by
            intro a b haM hbM ha hb
            have hres := ih ↥M (by omega) (lowerCentralSeries_eq_bot_of_subgroup M hgamma)
              ⟨a, haM⟩ ⟨b, hbM⟩ (by ext; simpa using ha) (by ext; simpa using hb)
            simpa using congrArg (Subgroup.subtype M) hres
          have hyN : y ∈ torsionOf M p hMclosed := ⟨hyM (Subgroup.mem_zpowers y), hy⟩
          have hRcomm : _root_.commutator R ≤ torsionOf M p hMclosed :=
            commutator_le_of_closure_pair _ hgen hyN
          have hexp : ∀ g ∈ _root_.commutator R, g ^ p = 1 := fun g hg => (hRcomm hg).2
          rw [← pow_mul_pow_eq_pow_of_commutator_exponent hp hgamma hexp x y, hx, hy, one_mul]
      · have hxH : x ∈ Subgroup.closure ({x, y} : Set R) := Subgroup.subset_closure (by simp)
        have hyH : y ∈ Subgroup.closure ({x, y} : Set R) := Subgroup.subset_closure (by simp)
        have hcardH : Nat.card ↥(Subgroup.closure ({x, y} : Set R)) < Nat.card R :=
          card_lt_card_of_lt_top hgen
        have hres := ih ↥(Subgroup.closure ({x, y} : Set R)) (by omega)
          (lowerCentralSeries_eq_bot_of_subgroup _ hgamma)
          ⟨x, hxH⟩ ⟨y, hyH⟩ (by ext; simpa using hx) (by ext; simpa using hy)
        simpa using congrArg (Subgroup.subtype _) hres

end OddOrder.GroupTheory
