/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Higman.Suzuki2Groups.HigmanLowerCentralGraded

/-!
# Transport of Higman's lower-central layers

G. Higman, *Suzuki 2-groups*, Illinois J. Math. 7 (1963), section 4,
pp. 84--85; used in the comparison of pairwise factors in Lemma 13,
pp. 93--94.

Higman's elementary layer

`Lᵢ(H) = Hᵢ / (Hᵢ² Hᵢ₊₁)`

is functorial under group isomorphisms.  This file constructs that
functoriality explicitly.  A multiplicative equivalence transports the
lower-central term, the square subgroup, the next term, and hence the
quotient kernel.  The resulting quotient equivalence is used to compare one
actual factor when it is embedded in two different pairwise joins.
-/

set_option autoImplicit false

namespace OddOrder.Higman.Suzuki2Groups

open OddOrder.GroupTheory
open scoped IsMulCommutative

universe uA uB uX uY

local instance transportLayerIsMulCommutative
    (H : Type*) [Group H] (i : ℕ) :
    IsMulCommutative (lowerCentralLayer H i) :=
  lowerCentralLayerIsMulCommutative H i

local instance transportLayerCommGroup
    (H : Type*) [Group H] (i : ℕ) :
    CommGroup (lowerCentralLayer H i) :=
  { (inferInstance : Group (lowerCentralLayer H i)) with
    mul_comm := (lowerCentralLayer_isElementaryAbelian H i).comm }

noncomputable local instance transportLayerZModTwoModule
    (H : Type*) [Group H] (i : ℕ) :
    Module (ZMod 2) (Additive (lowerCentralLayer H i)) :=
  lowerCentralLayerZmodModule H i

/-- A multiplicative equivalence transports the subgroup generated by
`p ^ s`-th powers. -/
theorem map_agemo_mulEquiv
    {A : Type uA} {B : Type uB} [Group A] [Group B]
    (e : A ≃* B) (p s : ℕ) :
    (Agemo A p s).map e.toMonoidHom = Agemo B p s := by
  rw [Agemo, MonoidHom.map_closure]
  congr 1
  ext y
  simp only [Set.mem_image, Set.mem_setOf_eq]
  constructor
  · rintro ⟨z, ⟨x, rfl⟩, rfl⟩
    refine ⟨e x, ?_⟩
    simpa only [MulEquiv.coe_toMonoidHom] using
      map_pow e x (p ^ s)
  · rintro ⟨x, rfl⟩
    exact ⟨e.symm x ^ (p ^ s), ⟨e.symm x, rfl⟩, by
      simpa only [MulEquiv.coe_toMonoidHom, e.apply_symm_apply] using
        map_pow e (e.symm x) (p ^ s)⟩

/-- A multiplicative equivalence transports every lower-central term. -/
theorem map_lowerCentralTerm_mulEquiv
    {A : Type uA} {B : Type uB} [Group A] [Group B]
    (e : A ≃* B) (i : ℕ) :
    (lowerCentralTerm A i).map e.toMonoidHom =
      lowerCentralTerm B i := by
  calc
    (lowerCentralTerm A i).map e.toMonoidHom =
        ((⊤ : Subgroup A).map e.toMonoidHom).lowerCentralSeries i := by
      rw [lowerCentralTerm, Subgroup.map_lowerCentralSeries]
    _ = (⊤ : Subgroup B).lowerCentralSeries i := by
      have htop :
          (⊤ : Subgroup A).map e.toMonoidHom = (⊤ : Subgroup B) :=
        Subgroup.map_top_of_surjective e.toMonoidHom e.surjective
      rw [htop]
    _ = lowerCentralTerm B i := rfl

/-- The restriction of a multiplicative equivalence to corresponding
lower-central terms. -/
noncomputable def lowerCentralTermMulEquiv
    {A : Type uA} {B : Type uB} [Group A] [Group B]
    (e : A ≃* B) (i : ℕ) :
    lowerCentralTerm A i ≃* lowerCentralTerm B i :=
  (e.subgroupMap (lowerCentralTerm A i)).trans
    (MulEquiv.subgroupCongr (map_lowerCentralTerm_mulEquiv e i))

@[simp]
theorem lowerCentralTermMulEquiv_apply_val
    {A : Type uA} {B : Type uB} [Group A] [Group B]
    (e : A ≃* B) (i : ℕ) (x : lowerCentralTerm A i) :
    ((lowerCentralTermMulEquiv e i x : lowerCentralTerm B i) : B) =
      e x := by
  rfl

/-- Inside corresponding lower-central terms, the restricted equivalence
transports the next term. -/
theorem map_lowerCentralNext_subgroupOf_mulEquiv
    {A : Type uA} {B : Type uB} [Group A] [Group B]
    (e : A ≃* B) (i : ℕ) :
    ((lowerCentralTerm A (i + 1)).subgroupOf
        (lowerCentralTerm A i)).map
          (lowerCentralTermMulEquiv e i).toMonoidHom =
      (lowerCentralTerm B (i + 1)).subgroupOf
        (lowerCentralTerm B i) := by
  ext y
  constructor
  · rintro ⟨x, hx, rfl⟩
    change e (x : A) ∈ lowerCentralTerm B (i + 1)
    rw [← map_lowerCentralTerm_mulEquiv e (i + 1)]
    exact ⟨(x : A), hx, rfl⟩
  · intro hy
    let x : lowerCentralTerm A i :=
      (lowerCentralTermMulEquiv e i).symm y
    refine ⟨x, ?_, (lowerCentralTermMulEquiv e i).apply_symm_apply y⟩
    have hy' : (y : B) ∈ lowerCentralTerm B (i + 1) := hy
    rw [← map_lowerCentralTerm_mulEquiv e (i + 1)] at hy'
    obtain ⟨z, hz, hzy⟩ := hy'
    change (x : A) ∈ lowerCentralTerm A (i + 1)
    have hxval : e (x : A) = (y : B) := by
      rw [← lowerCentralTermMulEquiv_apply_val e i x]
      exact congrArg Subtype.val
        ((lowerCentralTermMulEquiv e i).apply_symm_apply y)
    have hzx : z = (x : A) :=
      e.injective (hzy.trans hxval.symm)
    simpa [hzx] using hz

/-- The restricted equivalence transports the full layer kernel
`Hᵢ² Hᵢ₊₁`. -/
theorem map_lowerCentralLayerKernel_mulEquiv
    {A : Type uA} {B : Type uB} [Group A] [Group B]
    (e : A ≃* B) (i : ℕ) :
    (lowerCentralLayerKernel A i).map
        (lowerCentralTermMulEquiv e i).toMonoidHom =
      lowerCentralLayerKernel B i := by
  change
    (Agemo (lowerCentralTerm A i) 2 1 ⊔
      (lowerCentralTerm A (i + 1)).subgroupOf
        (lowerCentralTerm A i)).map
          (lowerCentralTermMulEquiv e i).toMonoidHom =
      Agemo (lowerCentralTerm B i) 2 1 ⊔
        (lowerCentralTerm B (i + 1)).subgroupOf
          (lowerCentralTerm B i)
  rw [Subgroup.map_sup, map_agemo_mulEquiv,
    map_lowerCentralNext_subgroupOf_mulEquiv]

/-- A multiplicative equivalence induces an equivalence on every elementary
lower-central layer. -/
noncomputable def lowerCentralLayerMulEquiv
    {A : Type uA} {B : Type uB} [Group A] [Group B]
    (e : A ≃* B) (i : ℕ) :
    lowerCentralLayer A i ≃* lowerCentralLayer B i :=
  QuotientGroup.congr _ _
    (lowerCentralTermMulEquiv e i)
    (map_lowerCentralLayerKernel_mulEquiv e i)

@[simp]
theorem lowerCentralLayerMulEquiv_mk
    {A : Type uA} {B : Type uB} [Group A] [Group B]
    (e : A ≃* B) (i : ℕ) (x : lowerCentralTerm A i) :
    lowerCentralLayerMulEquiv e i
        (QuotientGroup.mk' (lowerCentralLayerKernel A i) x) =
      QuotientGroup.mk' (lowerCentralLayerKernel B i)
        (lowerCentralTermMulEquiv e i x) := by
  rfl

/-- Additive-linear form of the equivalence induced on an elementary
lower-central layer. -/
noncomputable def lowerCentralLayerLinearEquiv
    {A : Type uA} {B : Type uB} [Group A] [Group B]
    (e : A ≃* B) (i : ℕ) :
    Additive (lowerCentralLayer A i) ≃ₗ[ZMod 2]
      Additive (lowerCentralLayer B i) :=
  (MulEquiv.toAdditive (lowerCentralLayerMulEquiv e i)).toLinearEquiv
    (fun c x => ZMod.map_smul
      (MulEquiv.toAdditive
        (lowerCentralLayerMulEquiv e i)).toAddMonoidHom c x)

/-- Naturality of the induced layer equivalence for one pair of actor
elements. -/
theorem lowerCentralLayerMulEquiv_equivariant
    {A : Type uA} {B : Type uB} {X : Type uX} {Y : Type uY}
    [Group A] [Group B] [Group X] [Group Y]
    (e : A ≃* B)
    (actA : X →* MulAut A) (actB : Y →* MulAut B)
    (a : X) (b : Y)
    (he : ∀ z : A, e (actA a z) = actB b (e z))
    (i : ℕ) (q : lowerCentralLayer A i) :
    lowerCentralLayerMulEquiv e i
        (lowerCentralLayerAction actA i a q) =
      lowerCentralLayerAction actB i b
        (lowerCentralLayerMulEquiv e i q) := by
  obtain ⟨z, rfl⟩ :=
    QuotientGroup.mk'_surjective (lowerCentralLayerKernel A i) q
  rw [lowerCentralLayerAction_apply_mk,
    lowerCentralLayerMulEquiv_mk,
    lowerCentralLayerMulEquiv_mk,
    lowerCentralLayerAction_apply_mk]
  apply congrArg (QuotientGroup.mk' (lowerCentralLayerKernel B i))
  apply Subtype.ext
  change e (actA a (z : A)) = actB b (e (z : A))
  exact he (z : A)

/-- Linear naturality of the induced layer equivalence for one pair of actor
elements. -/
theorem lowerCentralLayerLinearEquiv_equivariant
    {A : Type uA} {B : Type uB} {X : Type uX} {Y : Type uY}
    [Group A] [Group B] [Group X] [Group Y]
    (e : A ≃* B)
    (actA : X →* MulAut A) (actB : Y →* MulAut B)
    (a : X) (b : Y)
    (he : ∀ z : A, e (actA a z) = actB b (e z))
    (i : ℕ) (x : Additive (lowerCentralLayer A i)) :
    lowerCentralLayerLinearEquiv e i
        (lowerCentralLayerRepresentation actA i a x) =
      lowerCentralLayerRepresentation actB i b
        (lowerCentralLayerLinearEquiv e i x) := by
  change Additive.ofMul
      (lowerCentralLayerMulEquiv e i
        (lowerCentralLayerAction actA i a x.toMul)) =
    Additive.ofMul
      (lowerCentralLayerAction actB i b
        (lowerCentralLayerMulEquiv e i x.toMul))
  exact congrArg Additive.ofMul
    (lowerCentralLayerMulEquiv_equivariant
      e actA actB a b he i x.toMul)
end OddOrder.Higman.Suzuki2Groups
