/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Higman.Suzuki2Groups.HigmanNormalCover

/-!
# Higman Lemma 8: derived and power series of a cover

This file develops the exact lower-central and power series used in
G. Higman, *Suzuki 2-groups*, Lemma 8, p. 87.

The first bridge says that if the derived subgroup of a normal invariant
cover `A ⋖ C` maps onto `A`, then the subgroup generated by the squares of
`C` is exactly its derived subgroup.  Higman's subsequent identifications
`C₂ = A`, `C₃ = A²`, and `C₄ = A⁴` are built on this equality.
-/

set_option autoImplicit false

namespace OddOrder.Higman.Suzuki2Groups

open OddOrder.GroupTheory

namespace NormalInvariantCover

/-- **Higman, Suzuki 2-groups, Lemma 8 (p. 87), first bridge.**

Let `A ⋖ C` be a cover among ambient-normal actor-invariant subgroups.
If `C` is a finite `2`-group and its derived subgroup maps onto `A`, then
the subgroup generated by the squares of `C` is exactly its derived subgroup.

No commutativity of `A`, Frattini equality, or cyclicity of the actor is
needed for this step. -/
theorem agemo_one_eq_commutator_of_derived_map_eq_left
    {P X : Type*} [Group P] [Group X]
    {act : X →* MulAut P} {A C : Subgroup P}
    [Finite C] (h : NormalInvariantCover act A C)
    (hC : IsPGroup 2 C)
    (hderived : (_root_.commutator C).map C.subtype = A) :
    Agemo C 2 1 = _root_.commutator C := by
  letI : C.Normal := h.right.1
  have hCne : C ≠ ⊥ := by
    intro hCbot
    have hlt : A < (⊥ : Subgroup P) := by
      simpa [hCbot] using h.lt
    exact (not_lt_of_ge bot_le) hlt
  letI : Nontrivial C := (Subgroup.nontrivial_iff_ne_bot C).mpr hCne
  let B : Subgroup P := (Agemo C 2 1).map C.subtype
  obtain ⟨hBinv, hBnormal, hBC⟩ :=
    aInvariant_normal_map_of_characteristic h.right.2 (Agemo C 2 1)
  have hAB : A ≤ B := by
    rw [← hderived]
    exact Subgroup.map_mono (commutator_le_agemo_two_one C)
  rcases h.eq_left_or_eq_right
      ⟨hBnormal, hBinv⟩ hAB hBC with hBA | hBCeq
  · apply Subgroup.map_injective C.subtype_injective
    calc
      (Agemo C 2 1).map C.subtype = B := rfl
      _ = A := hBA
      _ = (_root_.commutator C).map C.subtype := hderived.symm
  · exfalso
    have hmaps :
        (Agemo C 2 1).map C.subtype =
          (⊤ : Subgroup C).map C.subtype := by
      calc
        (Agemo C 2 1).map C.subtype = B := rfl
        _ = C := hBCeq
        _ = (⊤ : Subgroup C).map C.subtype := by
          rw [← MonoidHom.range_eq_map, Subgroup.range_subtype]
    have hagemoTop : Agemo C 2 1 = ⊤ :=
      Subgroup.map_injective C.subtype_injective hmaps
    have hagemoLe : Agemo C 2 1 ≤ frattini C := by
      rw [Agemo, Subgroup.closure_le]
      rintro _ ⟨c, rfl⟩
      simpa using IsPGroup.pow_mem_frattini hC c
    have hfrattiniTop : frattini C = ⊤ := by
      apply top_unique
      rw [← hagemoTop]
      exact hagemoLe
    have hbotTop : (⊥ : Subgroup C) = ⊤ := by
      apply frattini_nongenerating
      simp [hfrattiniTop]
    exact (bot_ne_top : (⊥ : Subgroup C) ≠ ⊤) hbotTop

end NormalInvariantCover

end OddOrder.Higman.Suzuki2Groups
