/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Higman.Suzuki2Groups.HigmanCoverAbelian

/-!
# Higman Lemma 8: derived and power series of a cover

This file develops the exact lower-central and power series used in
G. Higman, *Suzuki 2-groups*, Lemma 8, p. 87.

The first bridge says that if the derived subgroup of a normal invariant
cover `A ⋖ C` maps onto `A`, then the subgroup generated by the squares of
`C` is exactly its derived subgroup.  Higman's subsequent identifications
`C₂ = A`, `C₃ = A²`, and `C₄ = A⁴` are built on this equality.
-/

set_option autoImplicit false

namespace OddOrder.Higman.Suzuki2Groups

open OddOrder.GroupTheory
open OddOrder.GroupTheory.Suzuki2Group
open OddOrder.Isaacs.Ch03
open scoped IsMulCommutative

namespace NormalInvariantCover

/-- **Higman, Suzuki 2-groups, Lemma 8 (p. 87), first bridge.**

Let `A ⋖ C` be a cover among ambient-normal actor-invariant subgroups.
If `C` is a finite `2`-group and its derived subgroup maps onto `A`, then
the subgroup generated by the squares of `C` is exactly its derived subgroup.

No commutativity of `A`, Frattini equality, or cyclicity of the actor is
needed for this step. -/
theorem agemo_one_eq_commutator_of_derived_map_eq_left
    {P X : Type*} [Group P] [Group X]
    {act : X →* MulAut P} {A C : Subgroup P}
    [Finite C] (h : NormalInvariantCover act A C)
    (hC : IsPGroup 2 C)
    (hderived : (_root_.commutator C).map C.subtype = A) :
    Agemo C 2 1 = _root_.commutator C := by
  letI : C.Normal := h.right.1
  have hCne : C ≠ ⊥ := by
    intro hCbot
    have hlt : A < (⊥ : Subgroup P) := by
      simpa [hCbot] using h.lt
    exact (not_lt_of_ge bot_le) hlt
  letI : Nontrivial C := (Subgroup.nontrivial_iff_ne_bot C).mpr hCne
  let B : Subgroup P := (Agemo C 2 1).map C.subtype
  obtain ⟨hBinv, hBnormal, hBC⟩ :=
    aInvariant_normal_map_of_characteristic h.right.2 (Agemo C 2 1)
  have hAB : A ≤ B := by
    rw [← hderived]
    exact Subgroup.map_mono (commutator_le_agemo_two_one C)
  rcases h.eq_left_or_eq_right
      ⟨hBnormal, hBinv⟩ hAB hBC with hBA | hBCeq
  · apply Subgroup.map_injective C.subtype_injective
    calc
      (Agemo C 2 1).map C.subtype = B := rfl
      _ = A := hBA
      _ = (_root_.commutator C).map C.subtype := hderived.symm
  · exfalso
    have hmaps :
        (Agemo C 2 1).map C.subtype =
          (⊤ : Subgroup C).map C.subtype := by
      calc
        (Agemo C 2 1).map C.subtype = B := rfl
        _ = C := hBCeq
        _ = (⊤ : Subgroup C).map C.subtype := by
          rw [← MonoidHom.range_eq_map, Subgroup.range_subtype]
    have hagemoTop : Agemo C 2 1 = ⊤ :=
      Subgroup.map_injective C.subtype_injective hmaps
    have hagemoLe : Agemo C 2 1 ≤ frattini C := by
      rw [Agemo, Subgroup.closure_le]
      rintro _ ⟨c, rfl⟩
      simpa using IsPGroup.pow_mem_frattini hC c
    have hfrattiniTop : frattini C = ⊤ := by
      apply top_unique
      rw [← hagemoTop]
      exact hagemoLe
    have hbotTop : (⊥ : Subgroup C) = ⊤ := by
      apply frattini_nongenerating
      simp [hfrattiniTop]
    exact (bot_ne_top : (⊥ : Subgroup C) ≠ ⊤) hbotTop

/-! ## The first terms of the lower-central series -/

/-- A lower-central term of `C`, transported into an ambient subgroup `A`.
This is used only inside the proof that Higman's lower-central series agrees
with the Agemo series of `A`. -/
private def lowerCentralTermIn
    {P : Type*} [Group P] (A C : Subgroup P) (i : ℕ) : Subgroup A :=
  ((lowerCentralTerm C i).map C.subtype).subgroupOf A

/-- A stationary term in the lower-central series of a nilpotent group is
trivial. -/
private theorem lowerCentralTerm_eq_bot_of_eq_succ
    {C : Type*} [Group C] [Group.IsNilpotent C] (i : ℕ)
    (hstable : lowerCentralTerm C (i + 1) = lowerCentralTerm C i) :
    lowerCentralTerm C i = ⊥ := by
  have hall : ∀ k : ℕ,
      lowerCentralTerm C (i + k) = lowerCentralTerm C i := by
    intro k
    induction k with
    | zero => simp
    | succ k ih =>
      calc
        lowerCentralTerm C (i + (k + 1)) =
            ⁅lowerCentralTerm C (i + k), (⊤ : Subgroup C)⁆ := by
          rw [show i + (k + 1) = (i + k) + 1 by omega]
          exact Subgroup.lowerCentralSeries_succ _ _
        _ = ⁅lowerCentralTerm C i, (⊤ : Subgroup C)⁆ := by rw [ih]
        _ = lowerCentralTerm C (i + 1) := by
          simp only [lowerCentralTerm, Subgroup.lowerCentralSeries_succ]
        _ = lowerCentralTerm C i := hstable
  obtain ⟨n, hn⟩ := Subgroup.nilpotent_iff_lowerCentralSeries.mp
    (inferInstance : Group.IsNilpotent C)
  have hle : lowerCentralTerm C (i + n) ≤ lowerCentralTerm C n :=
    (⊤ : Subgroup C).lowerCentralSeries_antitone (by omega)
  change lowerCentralTerm C n = ⊥ at hn
  rw [← hall n]
  rw [hn] at hle
  exact le_bot_iff.mp hle

/-- Between two consecutive Agemo terms, an invariant subgroup classified by
the Agemo series is one of the endpoints. -/
private theorem eq_agemo_or_succ_of_classification_of_between
    {A X : Type*} [CommGroup A] [Group X]
    (φ : X →* MulAut A)
    (classify : ∀ U : Subgroup A, IsAInvariant φ U →
      ∃ t : ℕ, U = Agemo A 2 t)
    {U : Subgroup A} (hUinv : IsAInvariant φ U) (s : ℕ)
    (hlower : Agemo A 2 (s + 1) ≤ U)
    (hupper : U ≤ Agemo A 2 s) :
    U = Agemo A 2 s ∨ U = Agemo A 2 (s + 1) := by
  obtain ⟨t, rfl⟩ := classify U hUinv
  by_cases hts : t ≤ s
  · left
    exact le_antisymm hupper (Agemo.anti hts)
  · right
    exact le_antisymm (Agemo.anti (by omega)) hlower

/-- If one lower-central term is an Agemo term and its squares lie in the
next lower-central term, then the next Agemo term lies there as well. -/
private theorem agemo_succ_le_lowerCentralTermIn
    {P : Type*} [Group P] {A C : Subgroup P}
    (hAcomm : IsMulCommutative A) (i s : ℕ)
    (hmap : (lowerCentralTerm C i).map C.subtype =
      (Agemo A 2 s).map A.subtype)
    (hsquares : (Agemo (lowerCentralTerm C i) 2 1).map
      (lowerCentralTerm C i).subtype ≤ lowerCentralTerm C (i + 1)) :
    letI : CommGroup A :=
      { (inferInstance : Group A) with mul_comm := hAcomm.is_comm.comm }
    Agemo A 2 (s + 1) ≤ lowerCentralTermIn A C (i + 1) := by
  letI : CommGroup A :=
    { (inferInstance : Group A) with mul_comm := hAcomm.is_comm.comm }
  intro x hx
  change ((x : A) : P) ∈ (lowerCentralTerm C (i + 1)).map C.subtype
  obtain ⟨y, hy, hxy⟩ := mem_agemo_succ_iff.mp hx
  have hyP : ((y : A) : P) ∈ (Agemo A 2 s).map A.subtype :=
    ⟨y, hy, rfl⟩
  rw [← hmap] at hyP
  obtain ⟨z, hz, hzP⟩ := Subgroup.mem_map.mp hyP
  let zi : lowerCentralTerm C i := ⟨z, hz⟩
  have hziAgemo : zi ^ 2 ∈ Agemo (lowerCentralTerm C i) 2 1 := by
    simpa using (Agemo.mem_of_eq_pow
      (G := lowerCentralTerm C i) (p := 2) (n := 1) zi)
  have hzsq : z ^ 2 ∈ lowerCentralTerm C (i + 1) := by
    apply hsquares
    exact ⟨zi ^ 2, hziAgemo, rfl⟩
  refine ⟨z ^ 2, hzsq, ?_⟩
  rw [hxy]
  exact congrArg (fun w : P => w ^ 2) hzP

/-- One step of Higman's identification of the lower-central series with the
Agemo series of its abelian derived subgroup. -/
private theorem lowerCentralTerm_map_eq_agemo_succ
    {P X : Type*} [Group P] [Group X]
    {act : X →* MulAut P} {A C : Subgroup P}
    [Group.IsNilpotent C]
    (hAinv : IsAInvariant act A) (hCinv : IsAInvariant act C)
    (hAcomm : IsMulCommutative A)
    (classify :
      letI : CommGroup A :=
        { (inferInstance : Group A) with mul_comm := hAcomm.is_comm.comm }
      ∀ U : Subgroup A, IsAInvariant hAinv.restrict U →
        ∃ t : ℕ, U = Agemo A 2 t)
    (i s : ℕ)
    (hmap : (lowerCentralTerm C i).map C.subtype =
      (Agemo A 2 s).map A.subtype)
    (hsquares : (Agemo (lowerCentralTerm C i) 2 1).map
      (lowerCentralTerm C i).subtype ≤ lowerCentralTerm C (i + 1)) :
    (lowerCentralTerm C (i + 1)).map C.subtype =
      (Agemo A 2 (s + 1)).map A.subtype := by
  letI : CommGroup A :=
    { (inferInstance : Group A) with mul_comm := hAcomm.is_comm.comm }
  let U : Subgroup A := lowerCentralTermIn A C (i + 1)
  have hnextLeA : (lowerCentralTerm C (i + 1)).map C.subtype ≤ A := by
    calc
      (lowerCentralTerm C (i + 1)).map C.subtype ≤
          (lowerCentralTerm C i).map C.subtype :=
        Subgroup.map_mono (lowerCentralTerm_succ_le C i)
      _ = (Agemo A 2 s).map A.subtype := hmap
      _ ≤ A := Subgroup.map_subtype_le _
  have hUmap : U.map A.subtype =
      (lowerCentralTerm C (i + 1)).map C.subtype :=
    Subgroup.map_subgroupOf_eq_of_le hnextLeA
  have hUinv : IsAInvariant hAinv.restrict U := by
    apply hAinv.subgroupOf
    exact aInvariant_map_subtype_of_restrict hCinv
      (IsAInvariant.lowerCentralSeries hCinv.restrict (i + 1))
  have hlower : Agemo A 2 (s + 1) ≤ U :=
    agemo_succ_le_lowerCentralTermIn hAcomm i s hmap hsquares
  have hupper : U ≤ Agemo A 2 s := by
    rw [← Subgroup.map_le_map_iff_of_injective A.subtype_injective,
      hUmap, ← hmap]
    exact Subgroup.map_mono (lowerCentralTerm_succ_le C i)
  rcases eq_agemo_or_succ_of_classification_of_between
      hAinv.restrict classify hUinv s hlower hupper with hsame | hsucc
  · have hterms : lowerCentralTerm C (i + 1) = lowerCentralTerm C i := by
      apply Subgroup.map_injective C.subtype_injective
      calc
        (lowerCentralTerm C (i + 1)).map C.subtype = U.map A.subtype :=
          hUmap.symm
        _ = (Agemo A 2 s).map A.subtype := by rw [hsame]
        _ = (lowerCentralTerm C i).map C.subtype := hmap.symm
    have hbot : lowerCentralTerm C i = ⊥ :=
      lowerCentralTerm_eq_bot_of_eq_succ i hterms
    have hnextBot : lowerCentralTerm C (i + 1) = ⊥ := by rw [hterms, hbot]
    have hagemoBot : Agemo A 2 s = ⊥ := by
      apply Subgroup.map_injective A.subtype_injective
      rw [Subgroup.map_bot, ← hmap, hbot, Subgroup.map_bot]
    have hsuccBot : Agemo A 2 (s + 1) = ⊥ :=
      eq_bot_iff.mpr ((Agemo.anti (Nat.le_succ s)).trans
        (eq_bot_iff.mp hagemoBot))
    rw [hnextBot, Subgroup.map_bot, hsuccBot, Subgroup.map_bot]
  · calc
      (lowerCentralTerm C (i + 1)).map C.subtype = U.map A.subtype :=
        hUmap.symm
      _ = (Agemo A 2 (s + 1)).map A.subtype := by rw [hsucc]

/-- **Higman, Suzuki 2-groups, Lemma 8 (p. 87), lower-central chain.**

Under Higman's Lemma 1 classification, a normal invariant cover with
`C' = A` has the first lower-central terms
`C₂ = A`, `C₃ = A²`, and `C₄ = A⁴` (all equalities are expressed after
mapping the subgroup terms into the common ambient group).

The proof constructs the source's assertion that all lower-central factors
have exponent two: `C² = C'` starts the square containment, and the
lower-central commutator identity propagates it to each following term. -/
theorem lowerCentralTerm_maps_eq_first_agemo_terms_of_derived_map_eq_left
    {P X : Type*} [Group P] [Group X]
    {act : X →* MulAut P} {A C : Subgroup P}
    [Finite C] (h : NormalInvariantCover act A C)
    (hC : IsPGroup 2 C) (hAcomm : IsMulCommutative A)
    (classify :
      letI : CommGroup A :=
        { (inferInstance : Group A) with mul_comm := hAcomm.is_comm.comm }
      ∀ U : Subgroup A, IsAInvariant h.left.2.restrict U →
        ∃ s : ℕ, U = Agemo A 2 s)
    (hderived : (_root_.commutator C).map C.subtype = A) :
    (lowerCentralTerm C 1).map C.subtype = A ∧
      (lowerCentralTerm C 2).map C.subtype =
        (Agemo A 2 1).map A.subtype ∧
      (lowerCentralTerm C 3).map C.subtype =
        (Agemo A 2 2).map A.subtype := by
  letI : Group.IsNilpotent C := hC.isNilpotent
  have htermOne : lowerCentralTerm C 1 = _root_.commutator C := by
    rw [lowerCentralTerm, Subgroup.top_lowerCentralSeries_one]
  have hmapOne : (lowerCentralTerm C 1).map C.subtype = A := by
    rw [htermOne]
    exact hderived
  have hagemoTermOne : Agemo C 2 1 = lowerCentralTerm C 1 :=
    (h.agemo_one_eq_commutator_of_derived_map_eq_left hC hderived).trans
      htermOne.symm
  have hsquaresZero : LowerCentralSquaresLieInSecond C :=
    lowerCentralSquaresLieInSecond_of_agemo_eq C hagemoTermOne
  have hsquaresOne : (Agemo (lowerCentralTerm C 1) 2 1).map
      (lowerCentralTerm C 1).subtype ≤ lowerCentralTerm C 2 := by
    simpa using lowerCentralTerm_succ_squares_le_of_squares_le C 0 hsquaresZero
  have hmapTwo : (lowerCentralTerm C 2).map C.subtype =
      (Agemo A 2 1).map A.subtype := by
    have hmapZero : (lowerCentralTerm C 1).map C.subtype =
        (Agemo A 2 0).map A.subtype := by
      rw [agemo_zero_eq_top, ← MonoidHom.range_eq_map,
        Subgroup.range_subtype]
      exact hmapOne
    simpa using lowerCentralTerm_map_eq_agemo_succ
      h.left.2 h.right.2 hAcomm classify 1 0 hmapZero hsquaresOne
  have hsquaresTwo : (Agemo (lowerCentralTerm C 2) 2 1).map
      (lowerCentralTerm C 2).subtype ≤ lowerCentralTerm C 3 := by
    simpa using lowerCentralTerm_succ_squares_le_of_squares_le C 1 hsquaresOne
  have hmapThree : (lowerCentralTerm C 3).map C.subtype =
      (Agemo A 2 2).map A.subtype := by
    simpa using lowerCentralTerm_map_eq_agemo_succ
      h.left.2 h.right.2 hAcomm classify 2 1 hmapTwo hsquaresTwo
  exact ⟨hmapOne, hmapTwo, hmapThree⟩

/-- **Higman, Suzuki 2-groups, Lemma 8 (p. 87), Frattini bridge.**

For a finite `2`-group cover with `C' = A`, the equality `C² = C'` makes the
zeroth lower-central layer denominator equal to `C'`.  Hence `Φ(C) = A`.
No commutativity or invariant-subgroup classification is needed here. -/
theorem ambientFrattini_eq_left_of_derived_map_eq_left
    {P X : Type*} [Group P] [Group X]
    {act : X →* MulAut P} {A C : Subgroup P}
    [Finite C] (h : NormalInvariantCover act A C)
    (hC : IsPGroup 2 C)
    (hderived : (_root_.commutator C).map C.subtype = A) :
    ambientFrattini C = A := by
  have htermOne : lowerCentralTerm C 1 = _root_.commutator C := by
    rw [lowerCentralTerm, Subgroup.top_lowerCentralSeries_one]
  have hAgemo : Agemo C 2 1 = lowerCentralTerm C 1 :=
    (h.agemo_one_eq_commutator_of_derived_map_eq_left hC hderived).trans
      htermOne.symm
  rw [ambientFrattini,
    ← lowerCentralLayerKernelInAmbient_zero_eq_frattini C hC,
    lowerCentralLayerKernelInAmbient_eq,
    agemo_lowerCentralTerm_zero_map_eq, hAgemo, sup_idem, htermOne, hderived]

/-- **Higman, Suzuki 2-groups, Lemma 8 (p. 87), layer denominators.**

Under the exact lower-central chain `C₂=A`, `C₃=A²`, `C₄=A⁴`, the actual
denominators of `L₂(C)` and `L₃(C)` map respectively to `A²` and `A⁴` in the
common ambient group. -/
theorem lowerCentralLayerKernel_maps_eq_first_agemo_terms_of_derived_map_eq_left
    {P X : Type*} [Group P] [Group X]
    {act : X →* MulAut P} {A C : Subgroup P}
    [Finite C] (h : NormalInvariantCover act A C)
    (hC : IsPGroup 2 C) (hAcomm : IsMulCommutative A)
    (classify :
      letI : CommGroup A :=
        { (inferInstance : Group A) with mul_comm := hAcomm.is_comm.comm }
      ∀ U : Subgroup A, IsAInvariant h.left.2.restrict U →
        ∃ s : ℕ, U = Agemo A 2 s)
    (hderived : (_root_.commutator C).map C.subtype = A) :
    (lowerCentralLayerKernelInAmbient C 1).map C.subtype =
        (Agemo A 2 1).map A.subtype ∧
      (lowerCentralLayerKernelInAmbient C 2).map C.subtype =
        (Agemo A 2 2).map A.subtype := by
  have htermOne : lowerCentralTerm C 1 = _root_.commutator C := by
    rw [lowerCentralTerm, Subgroup.top_lowerCentralSeries_one]
  have hAgemo : Agemo C 2 1 = lowerCentralTerm C 1 :=
    (h.agemo_one_eq_commutator_of_derived_map_eq_left hC hderived).trans
      htermOne.symm
  have hSqZero : LowerCentralSquaresLieInSecond C :=
    lowerCentralSquaresLieInSecond_of_agemo_eq C hAgemo
  have hSqOne : (Agemo (lowerCentralTerm C 1) 2 1).map
      (lowerCentralTerm C 1).subtype ≤ lowerCentralTerm C 2 := by
    simpa using
      lowerCentralTerm_succ_squares_le_of_squares_le C 0 hSqZero
  have hSqTwo : (Agemo (lowerCentralTerm C 2) 2 1).map
      (lowerCentralTerm C 2).subtype ≤ lowerCentralTerm C 3 := by
    simpa using
      lowerCentralTerm_succ_squares_le_of_squares_le C 1 hSqOne
  obtain ⟨_hmapOne, hmapTwo, hmapThree⟩ :=
    h.lowerCentralTerm_maps_eq_first_agemo_terms_of_derived_map_eq_left
      hC hAcomm classify hderived
  have hKernelOne : lowerCentralLayerKernelInAmbient C 1 =
      lowerCentralTerm C 2 := by
    rw [lowerCentralLayerKernelInAmbient_eq, sup_eq_right.mpr hSqOne]
  have hKernelTwo : lowerCentralLayerKernelInAmbient C 2 =
      lowerCentralTerm C 3 := by
    rw [lowerCentralLayerKernelInAmbient_eq, sup_eq_right.mpr hSqTwo]
  constructor
  · rw [hKernelOne]
    exact hmapTwo
  · rw [hKernelTwo]
    exact hmapThree

/-- **Higman, Suzuki 2-groups, Lemma 8 (p. 87), power-factor bridge.**

If `C' = A`, Higman's exact lower-central chain identifies the actual layers
`L₂(C)` and `L₃(C)` with `A/A²` and `A²/A⁴`.  When the latter factor is
nontrivial, irreducibility of `A/A²` upgrades the actual square map to an
equivariant linear equivalence between these two lower-central layers. -/
theorem exists_lowerCentralLayerOne_linearEquiv_layerTwo_of_derived_map_eq_left
    {P X : Type*} [Group P] [Group X]
    {act : X →* MulAut P} {A C : Subgroup P}
    [Finite C] (h : NormalInvariantCover act A C)
    (hC : IsPGroup 2 C) (hAcomm : IsMulCommutative A)
    (classify :
      letI : CommGroup A :=
        { (inferInstance : Group A) with mul_comm := hAcomm.is_comm.comm }
      ∀ U : Subgroup A, IsAInvariant h.left.2.restrict U →
        ∃ s : ℕ, U = Agemo A 2 s)
    (hderived : (_root_.commutator C).map C.subtype = A) :
    letI : CommGroup A :=
      { (inferInstance : Group A) with mul_comm := hAcomm.is_comm.comm }
    letI : IsMulCommutative (lowerCentralLayer C 1) :=
      lowerCentralLayerIsMulCommutative C 1
    letI : Module (ZMod 2) (Additive (lowerCentralLayer C 1)) :=
      lowerCentralLayerZmodModule C 1
    letI : IsMulCommutative (lowerCentralLayer C 2) :=
      lowerCentralLayerIsMulCommutative C 2
    letI : Module (ZMod 2) (Additive (lowerCentralLayer C 2)) :=
      lowerCentralLayerZmodModule C 2
    ∀ (_hirr : Representation.IsIrreducible
        (agemoSuccQuotientRepresentation h.left.2.restrict 0))
      (_hA1 : Nontrivial (AgemoSuccQuotient A 1)),
    ∃ E : Additive (lowerCentralLayer C 1) ≃ₗ[ZMod 2]
        Additive (lowerCentralLayer C 2),
      ∀ g q,
        E (lowerCentralLayerRepresentation h.right.2.restrict 1 g q) =
          lowerCentralLayerRepresentation h.right.2.restrict 2 g (E q) := by
  letI : CommGroup A :=
    { (inferInstance : Group A) with mul_comm := hAcomm.is_comm.comm }
  letI : IsMulCommutative (lowerCentralLayer C 1) :=
    lowerCentralLayerIsMulCommutative C 1
  letI : Module (ZMod 2) (Additive (lowerCentralLayer C 1)) :=
    lowerCentralLayerZmodModule C 1
  letI : IsMulCommutative (lowerCentralLayer C 2) :=
    lowerCentralLayerIsMulCommutative C 2
  letI : Module (ZMod 2) (Additive (lowerCentralLayer C 2)) :=
    lowerCentralLayerZmodModule C 2
  intro hirr hA1
  letI : Nontrivial (AgemoSuccQuotient A 1) := hA1
  obtain ⟨hmapOne, hmapTwo, _hmapThree⟩ :=
    h.lowerCentralTerm_maps_eq_first_agemo_terms_of_derived_map_eq_left
      hC hAcomm classify hderived
  obtain ⟨hkernelOne, hkernelTwo⟩ :=
    h.lowerCentralLayerKernel_maps_eq_first_agemo_terms_of_derived_map_eq_left
      hC hAcomm classify hderived
  have hmapOne' : (lowerCentralTerm C 1).map C.subtype =
      (Agemo A 2 0).map A.subtype := by
    rw [agemo_zero_eq_top, ← MonoidHom.range_eq_map,
      Subgroup.range_subtype]
    exact hmapOne
  let E1 := lowerCentralLayerLinearEquivAgemoSuccAt
    A C hAcomm 1 0 hmapOne' hkernelOne
  let E2 := lowerCentralLayerLinearEquivAgemoSuccAt
    A C hAcomm 2 1 hmapTwo hkernelTwo
  have hE1 : ∀ g q,
      E1 (lowerCentralLayerRepresentation h.right.2.restrict 1 g q) =
        agemoSuccQuotientRepresentation h.left.2.restrict 0 g (E1 q) :=
    lowerCentralLayerLinearEquivAgemoSuccAt_equivariant
      act A C hAcomm h.left.2 h.right.2 1 0 hmapOne' hkernelOne
  have hE2 : ∀ g q,
      E2 (lowerCentralLayerRepresentation h.right.2.restrict 2 g q) =
        agemoSuccQuotientRepresentation h.left.2.restrict 1 g (E2 q) :=
    lowerCentralLayerLinearEquivAgemoSuccAt_equivariant
      act A C hAcomm h.left.2 h.right.2 2 1 hmapTwo hkernelTwo
  obtain ⟨Ep, hEp⟩ :=
    exists_agemoZero_linearEquiv_succ_of_irreducible
      h.left.2.restrict 1 hirr
  have hE2symm : ∀ g q,
      E2.symm (agemoSuccQuotientRepresentation h.left.2.restrict 1 g q) =
        lowerCentralLayerRepresentation h.right.2.restrict 2 g
          (E2.symm q) := by
    intro g q
    apply E2.injective
    rw [E2.apply_symm_apply, hE2, E2.apply_symm_apply]
  let E : Additive (lowerCentralLayer C 1) ≃ₗ[ZMod 2]
      Additive (lowerCentralLayer C 2) :=
    E1.trans (Ep.trans E2.symm)
  refine ⟨E, ?_⟩
  intro g q
  change E2.symm (Ep (E1
    (lowerCentralLayerRepresentation h.right.2.restrict 1 g q))) =
      lowerCentralLayerRepresentation h.right.2.restrict 2 g
        (E2.symm (Ep (E1 q)))
  rw [hE1, hEp, hE2symm]

end NormalInvariantCover

local instance lemmaEightLayerIsMulCommutative
    (H : Type*) [Group H] (i : ℕ) :
    IsMulCommutative (lowerCentralLayer H i) :=
  lowerCentralLayerIsMulCommutative H i

noncomputable local instance lemmaEightLayerModTwo
    (H : Type*) [Group H] (i : ℕ) :
    Module (ZMod 2) (Additive (lowerCentralLayer H i)) :=
  lowerCentralLayerZmodModule H i

/-- **Higman, Suzuki 2-groups, Lemma 8 (p. 87), source-strength form.**

Let `A` be an abelian normal actor-invariant subgroup and `C` a normal
actor-invariant subgroup covering `A`. If `C' = A`, then `A` has exponent
at most two. The actual `L₂(C) ≃ L₃(C)` used in the contradiction is
constructed from the square map and the exact lower-central chain above.

The actor is only required to be transitive on ambient involutions and to
have odd order.  Its restriction to `C` need not be injective: Lemma 6 is
applied to the faithful range of that restriction. -/
theorem higmanLemmaEight_pow_two_eq_one_of_transitive
    {P : Type*} [Group P] [Finite P]
    (hP : IsPGroup 2 P)
    (X : Subgroup (MulAut P))
    (hXcyc : IsCyclic X)
    (htransP : ActsTransitivelyOnInvolutions X)
    (hXodd : Odd (Nat.card X))
    (hmulti : ∃ x y : P,
      x ∈ involutions P ∧ y ∈ involutions P ∧ x ≠ y)
    (A C : Subgroup P)
    (hcover : NormalInvariantCover X.subtype A C)
    (hAcomm : IsMulCommutative A)
    (hderived : (_root_.commutator C).map C.subtype = A) :
    ∀ a : A, a ^ 2 = 1 := by
  letI : A.Normal := hcover.left.1
  letI : IsCyclic X := hXcyc
  letI : CommGroup X := IsCyclic.commGroup
  by_contra hnotexp
  have hCtwo : IsPGroup 2 C := hP.to_subgroup C
  have hAne : A ≠ ⊥ := by
    intro hAbot
    apply hnotexp
    intro a
    have haone : a = 1 := by
      apply Subtype.ext
      have ha : (a : P) ∈ (⊥ : Subgroup P) := by
        rw [← hAbot]
        exact a.property
      simpa using ha
    rw [haone]
    simp
  letI : Nontrivial A := (Subgroup.nontrivial_iff_ne_bot A).mpr hAne
  obtain ⟨x, y, hx, hy, hxy⟩ := hmulti
  have hinvA : involutions P ⊆ A :=
    involutions_subset_of_nontrivial_invariant
      hP X htransP hcover.left.2 hAne
  have htransA : ∀ a ∈ involutions A, ∀ b ∈ involutions A,
      ∃ g : X, hcover.left.2.restrict g a = b := by
    intro a ha b hb
    have haP : (a : P) ∈ involutions P := by
      refine ⟨congrArg Subtype.val ha.1, ?_⟩
      intro ha1
      exact ha.2 (Subtype.ext ha1)
    have hbP : (b : P) ∈ involutions P := by
      refine ⟨congrArg Subtype.val hb.1, ?_⟩
      intro hb1
      exact hb.2 (Subtype.ext hb1)
    obtain ⟨g, hg⟩ := htransP (a : P) haP (b : P) hbP
    exact ⟨g, Subtype.ext hg⟩
  obtain ⟨ι, hι, e, he, hε, classify⟩ :=
    exists_homocyclic_and_invariant_eq_agemo
      (hP.to_subgroup A) hcover.left.2.restrict htransA
  letI : Fintype ι := hι
  obtain ⟨ε⟩ := hε
  have heTwo : 1 < e := by
    by_contra h
    have heOne : e ≤ 1 := by omega
    apply hnotexp
    intro a
    have hpow : a ^ (2 ^ e) = 1 :=
      pow_two_pow_eq_one_of_equiv_pi_zmod ε a
    have horder : orderOf a ∣ 2 ^ e :=
      orderOf_dvd_iff_pow_eq_one.mpr hpow
    have hdvd : 2 ^ e ∣ 2 := by
      simpa using Nat.pow_dvd_pow 2 heOne
    exact orderOf_dvd_iff_pow_eq_one.mp (horder.trans hdvd)
  let xA : A := ⟨x, hinvA hx⟩
  let yA : A := ⟨y, hinvA hy⟩
  have hxA : xA ∈ involutions A := by
    refine ⟨Subtype.ext hx.1, ?_⟩
    intro hx1
    exact hx.2 (congrArg Subtype.val hx1)
  have hyA : yA ∈ involutions A := by
    refine ⟨Subtype.ext hy.1, ?_⟩
    intro hy1
    exact hy.2 (congrArg Subtype.val hy1)
  have hxyA : xA ≠ yA := by
    intro h
    exact hxy (congrArg Subtype.val h)
  have hncycZero : ¬ IsCyclic (AgemoSuccQuotient A 0) :=
    not_isCyclic_agemoQuotient_of_two_involutions
      ε (by omega) (by omega) hxA hyA hxyA
  have hncycOne : ¬ IsCyclic (AgemoSuccQuotient A 1) :=
    not_isCyclic_agemoQuotient_of_two_involutions
      ε (by omega) (by omega) hxA hyA hxyA
  letI : Nontrivial (AgemoSuccQuotient A 1) :=
    Nontrivial.of_not_isCyclic hncycOne
  letI : Nontrivial (AgemoSuccQuotient A 0) :=
    Nontrivial.of_not_isCyclic hncycZero
  have htransAZero : ∀ v w : Additive (AgemoSuccQuotient A 0),
      v ≠ 0 → w ≠ 0 →
        ∃ g : X,
          agemoSuccQuotientRepresentation hcover.left.2.restrict 0 g v = w := by
    intro v w hv hw
    have hv' : v.toMul ≠ 1 := by simpa using hv
    have hw' : w.toMul ≠ 1 := by simpa using hw
    obtain ⟨g, hg⟩ :=
      agemoSuccQuotientAction_transitive_on_nonidentity
        hcover.left.2.restrict ε htransA he v.toMul w.toMul hv' hw'
    exact ⟨g, Additive.toMul.injective hg⟩
  have hirrAZero : Representation.IsIrreducible
      (agemoSuccQuotientRepresentation hcover.left.2.restrict 0) :=
    representation_isIrreducible_of_transitive_nonzero
      (agemoSuccQuotientRepresentation hcover.left.2.restrict 0) htransAZero
  obtain ⟨E, hE⟩ :=
    hcover.exists_lowerCentralLayerOne_linearEquiv_layerTwo_of_derived_map_eq_left
      hCtwo hAcomm (fun U hU => by
        obtain ⟨s, _hs, hsU⟩ := classify U hU
        exact ⟨s, hsU⟩) hderived hirrAZero inferInstance
  obtain ⟨hmapOne, _hmapTwo, _hmapThree⟩ :=
    hcover.lowerCentralTerm_maps_eq_first_agemo_terms_of_derived_map_eq_left
      hCtwo hAcomm (fun U hU => by
        obtain ⟨s, _hs, hsU⟩ := classify U hU
        exact ⟨s, hsU⟩) hderived
  obtain ⟨hkernelOne, _hkernelTwo⟩ :=
    hcover.lowerCentralLayerKernel_maps_eq_first_agemo_terms_of_derived_map_eq_left
      hCtwo hAcomm (fun U hU => by
        obtain ⟨s, _hs, hsU⟩ := classify U hU
        exact ⟨s, hsU⟩) hderived
  have hmapOne' : (lowerCentralTerm C 1).map C.subtype =
      (Agemo A 2 0).map A.subtype := by
    rw [agemo_zero_eq_top, ← MonoidHom.range_eq_map,
      Subgroup.range_subtype]
    exact hmapOne
  let EOne := lowerCentralLayerLinearEquivAgemoSuccAt
    A C hAcomm 1 0 hmapOne' hkernelOne
  have hEOne : ∀ g q,
      EOne (lowerCentralLayerRepresentation hcover.right.2.restrict 1 g q) =
        agemoSuccQuotientRepresentation hcover.left.2.restrict 0 g (EOne q) :=
    lowerCentralLayerLinearEquivAgemoSuccAt_equivariant
      X.subtype A C hAcomm hcover.left.2 hcover.right.2
        1 0 hmapOne' hkernelOne
  have hfinrank : 2 ≤ Module.finrank (ZMod 2)
      (Additive (lowerCentralLayer C 1)) :=
    finrank_ge_two_of_linearEquiv_agemoSucc 0 EOne hncycZero
  have htransTwo : ∀ v w : Additive (lowerCentralLayer C 1),
      v ≠ 0 → w ≠ 0 →
        ∃ g : X,
          lowerCentralLayerRepresentation hcover.right.2.restrict 1 g v = w :=
    transitive_nonzero_of_equivariant_agemoSucc
      (lowerCentralLayerRepresentation hcover.right.2.restrict 1)
      hcover.left.2.restrict ε htransA he EOne hEOne
  have hPhi : NormalInvariantCover.ambientFrattini C = A :=
    hcover.ambientFrattini_eq_left_of_derived_map_eq_left hCtwo hderived
  have hirrZero : Representation.IsIrreducible
      (lowerCentralLayerRepresentation hcover.right.2.restrict 0) :=
    hcover.lowerCentralLayerZeroRepresentation_isIrreducible hP hPhi
  have hAgemo : Agemo C 2 1 = lowerCentralTerm C 1 :=
    (hcover.agemo_one_eq_commutator_of_derived_map_eq_left
      hCtwo hderived).trans (by
        rw [lowerCentralTerm, Subgroup.top_lowerCentralSeries_one])
  exact
    (not_exists_equivariant_linearEquiv_of_higman_tripleBracket_of_odd_action
    hCtwo hcover.right.2.restrict hXodd hAgemo
    (Module.finrank (ZMod 2) (Additive (lowerCentralLayer C 1)))
    hfinrank rfl hirrZero htransTwo) ⟨E, hE⟩

/-- Compatibility form of Higman Lemma 8 for an actor already known to act
regularly on the involutions. -/
theorem higmanLemmaEight_pow_two_eq_one
    {P : Type*} [Group P] [Finite P]
    (hP : IsPGroup 2 P)
    (X : Subgroup (MulAut P))
    (hXcyc : IsCyclic X)
    (hreg : ActsRegularlyOnInvolutions X)
    (hmulti : ∃ x y : P,
      x ∈ involutions P ∧ y ∈ involutions P ∧ x ≠ y)
    (A C : Subgroup P)
    (hcover : NormalInvariantCover X.subtype A C)
    (hAcomm : IsMulCommutative A)
    (hderived : (_root_.commutator C).map C.subtype = A) :
    ∀ a : A, a ^ 2 = 1 := by
  have hinv : (involutions P).Nonempty := by
    obtain ⟨x, _, hx, _, _⟩ := hmulti
    exact ⟨x, hx⟩
  exact higmanLemmaEight_pow_two_eq_one_of_transitive
    hP X hXcyc hreg.transitive
      (actor_card_odd_of_regular_on_involutions hP X hreg hinv)
      hmulti A C hcover hAcomm hderived

end OddOrder.Higman.Suzuki2Groups
