/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.Algebra.Module.Submodule.LinearMap
import OddOrder.Peterfalvi.S06_DadeIsometryCertain

/-!
# Peterfalvi §7: Coherence

T. Peterfalvi, *Character Theory for the Odd Order Theorem* (LMS LNS 272, 2000),
§7, pp. 25-29.

This file defines the first Lean interface for Peterfalvi coherence.  Following
the audit note, (5.1) is encoded as an extension property only: the
"character-difference" conclusion belongs to (5.9), and the difference used in
§7 is `chi - conj chi`.

Reference note: `notes/peterfalvi/s07_coherence.md`.
-/

namespace OddOrder.Peterfalvi.S07

open OddOrder.RepresentationTheory

variable {L G : Type*} [Group L] [Group G]

/- 5: Coherence (pp. 25-29) -/

/-- The integral span generated by a set of class functions. -/
def zSpan (S : Set (ClassFunction L ℂ)) : Submodule ℤ (ClassFunction L ℂ) :=
  Submodule.span ℤ S

/-- The part of `Z[S]` supported on `A`.

This is kept as a predicate-shaped set for now, because the `CF(L,A)` complex
submodule and the integral lattice `Z[S]` live over different scalar rings. -/
def zSupportedSpan (S : Set (ClassFunction L ℂ)) (A : Set L) :
    Set (ClassFunction L ℂ) :=
  {φ | φ ∈ zSpan (L := L) S ∧ φ.support ⊆ A}

theorem mem_zSupportedSpan_iff {S : Set (ClassFunction L ℂ)} {A : Set L}
    {φ : ClassFunction L ℂ} :
    φ ∈ zSupportedSpan (L := L) S A ↔
      φ ∈ zSpan (L := L) S ∧ φ.support ⊆ A :=
  Iff.rfl

theorem mem_zSpan_of_mem_zSupportedSpan {S : Set (ClassFunction L ℂ)} {A : Set L}
    {φ : ClassFunction L ℂ} (hφ : φ ∈ zSupportedSpan (L := L) S A) :
    φ ∈ zSpan (L := L) S :=
  hφ.1

theorem support_subset_of_mem_zSupportedSpan {S : Set (ClassFunction L ℂ)} {A : Set L}
    {φ : ClassFunction L ℂ} (hφ : φ ∈ zSupportedSpan (L := L) S A) :
    φ.support ⊆ A :=
  hφ.2

theorem zero_mem_zSupportedSpan {S : Set (ClassFunction L ℂ)} {A : Set L} :
    (0 : ClassFunction L ℂ) ∈ zSupportedSpan (L := L) S A := by
  exact ⟨Submodule.zero_mem _, by simp⟩

theorem neg_mem_zSupportedSpan {S : Set (ClassFunction L ℂ)} {A : Set L}
    {φ : ClassFunction L ℂ} (hφ : φ ∈ zSupportedSpan (L := L) S A) :
    -φ ∈ zSupportedSpan (L := L) S A := by
  constructor
  · exact Submodule.neg_mem _ hφ.1
  · intro x hx
    exact hφ.2 (by simpa [ClassFunction.mem_support] using hx)

theorem add_mem_zSupportedSpan {S : Set (ClassFunction L ℂ)} {A : Set L}
    {φ ψ : ClassFunction L ℂ}
    (hφ : φ ∈ zSupportedSpan (L := L) S A)
    (hψ : ψ ∈ zSupportedSpan (L := L) S A) :
    φ + ψ ∈ zSupportedSpan (L := L) S A := by
  constructor
  · exact Submodule.add_mem _ hφ.1 hψ.1
  · intro x hx
    rcases ClassFunction.support_add_subset φ ψ hx with hxφ | hxψ
    · exact hφ.2 hxφ
    · exact hψ.2 hxψ

theorem sub_mem_zSupportedSpan {S : Set (ClassFunction L ℂ)} {A : Set L}
    {φ ψ : ClassFunction L ℂ}
    (hφ : φ ∈ zSupportedSpan (L := L) S A)
    (hψ : ψ ∈ zSupportedSpan (L := L) S A) :
    φ - ψ ∈ zSupportedSpan (L := L) S A := by
  simpa [sub_eq_add_neg] using
    add_mem_zSupportedSpan (L := L) hφ (neg_mem_zSupportedSpan (L := L) hψ)

theorem zSupportedSpan_mono_left {S₁ S : Set (ClassFunction L ℂ)} {A : Set L}
    (hS : S₁ ⊆ S) {φ : ClassFunction L ℂ}
    (hφ : φ ∈ zSupportedSpan (L := L) S₁ A) :
    φ ∈ zSupportedSpan (L := L) S A :=
  ⟨Submodule.span_mono hS hφ.1, hφ.2⟩

theorem zSupportedSpan_mono_right {S : Set (ClassFunction L ℂ)} {A₁ A : Set L}
    (hA : A₁ ⊆ A) {φ : ClassFunction L ℂ}
    (hφ : φ ∈ zSupportedSpan (L := L) S A₁) :
    φ ∈ zSupportedSpan (L := L) S A :=
  ⟨hφ.1, hφ.2.trans hA⟩

/-- An integral linear map between virtual-character lattices, represented at
the class-function level. -/
abbrev IntegralCharacterMap (L G : Type*) [Group L] [Group G] :=
  ClassFunction L ℂ →ₗ[ℤ] ClassFunction G ℂ

/-- The normalized inner-product part of an integral isometry. -/
structure IsIntegralIsometry (τ : IntegralCharacterMap L G)
    [Fintype L] [Fintype G]
    [Invertible (Nat.card L : ℂ)] [Invertible (Nat.card G : ℂ)] : Prop where
  inner_eq :
    ∀ φ ψ : ClassFunction L ℂ,
      ClassFunction.inner (τ φ) (τ ψ) = ClassFunction.inner φ ψ

/-- The Peterfalvi (5.2.d) image data for one character difference.

For `χ ∈ S`, later applications prove that the image of `χ - χ̄` under the
integral isometry is a signed difference of two irreducible characters of `G`.
The hard existence theorem is supplied by
`OddOrder.RepresentationTheory.isometry_difference_pair_structure`; this
structure records the reusable conclusion in the coherence interface. -/
structure CharacterDifferenceImage (τ : IntegralCharacterMap L G)
    (χ : ClassFunction L ℂ) where
  mu : IrreducibleCharacter G
  nu : IrreducibleCharacter G
  distinct : mu ≠ nu
  sign : ℤ
  sign_eq : sign = 1 ∨ sign = -1
  image_eq :
    τ (χ - χ.conj) =
      sign • ((mu : ClassFunction G ℂ) - (nu : ClassFunction G ℂ))

namespace CharacterDifferenceImage

variable {τ : IntegralCharacterMap L G} {χ ψ : ClassFunction L ℂ}

/-- The first irreducible character appearing in the signed image, as a class
function. -/
abbrev muClassFunction (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    ClassFunction G ℂ :=
  hχ.mu

/-- The second irreducible character appearing in the signed image, as a class
function. -/
abbrev nuClassFunction (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    ClassFunction G ℂ :=
  hχ.nu

@[simp] theorem mu_irreducible
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    IsIrreducibleCharacter hχ.muClassFunction :=
  hχ.mu.isIrreducible

@[simp] theorem nu_irreducible
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    IsIrreducibleCharacter hχ.nuClassFunction :=
  hχ.nu.isIrreducible

/-- The two irreducible characters appearing in the image of `χ - χ̄`.

This is the current two-element form of Peterfalvi's `R(χ)` from (5.2.d). -/
def imageSet (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    Set (ClassFunction G ℂ) :=
  {hχ.muClassFunction, hχ.nuClassFunction}

@[simp] theorem muClassFunction_mem_imageSet
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    hχ.muClassFunction ∈ hχ.imageSet := by
  simp [imageSet]

@[simp] theorem nuClassFunction_mem_imageSet
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    hχ.nuClassFunction ∈ hχ.imageSet := by
  simp [imageSet]

theorem mem_imageSet_iff
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ)
    {φ : ClassFunction G ℂ} :
    φ ∈ hχ.imageSet ↔ φ = hχ.muClassFunction ∨ φ = hχ.nuClassFunction := by
  simp [imageSet]

theorem imageSet_irreducible
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ)
    {φ : ClassFunction G ℂ} (hφ : φ ∈ hχ.imageSet) :
    IsIrreducibleCharacter φ := by
  rw [hχ.mem_imageSet_iff] at hφ
  rcases hφ with rfl | rfl
  · exact hχ.mu_irreducible
  · exact hχ.nu_irreducible

theorem muClassFunction_ne_nuClassFunction
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    hχ.muClassFunction ≠ hχ.nuClassFunction := by
  intro h
  exact hχ.distinct (IrreducibleCharacter.ext h)

theorem signed_image_ne_zero
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    hχ.sign • (hχ.muClassFunction - hχ.nuClassFunction) ≠ 0 := by
  have hdiff : hχ.muClassFunction - hχ.nuClassFunction ≠ 0 :=
    sub_ne_zero.mpr hχ.muClassFunction_ne_nuClassFunction
  rcases hχ.sign_eq with hsign | hsign
  · simpa [hsign] using hdiff
  · have hneg : -(hχ.muClassFunction - hχ.nuClassFunction) ≠ 0 := neg_ne_zero.mpr hdiff
    simpa [hsign] using hneg

/-- Orthogonality of the two image sets `R(χ)` and `R(ψ)` from Peterfalvi
(5.2.e). -/
def Orthogonal (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ)
    (hψ : CharacterDifferenceImage (L := L) (G := G) τ ψ)
    [Fintype G] [Invertible (Nat.card G : ℂ)] : Prop :=
  ∀ ⦃φ η : ClassFunction G ℂ⦄, φ ∈ hχ.imageSet → η ∈ hψ.imageSet →
    ClassFunction.inner φ η = 0

/-- Restatement using the named §3/§7 helper for the expression `χ - χ̄`. -/
theorem image_conjugateDifference (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    τ (OddOrder.Peterfalvi.S03.conjugateDifference χ) =
      hχ.sign • (hχ.muClassFunction - hχ.nuClassFunction) := by
  simpa [OddOrder.Peterfalvi.S03.conjugateDifference] using hχ.image_eq

theorem image_conjugateDifference_ne_zero
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    τ (OddOrder.Peterfalvi.S03.conjugateDifference χ) ≠ 0 := by
  rw [hχ.image_conjugateDifference]
  exact hχ.signed_image_ne_zero

end CharacterDifferenceImage

/-- Peterfalvi (5.1): `τ` is coherent for `(S,A)` if it admits an integral
isometric extension on `Z[S]` that agrees with `τ` on `Z[S,A]`. -/
structure IsCoherent (τ : IntegralCharacterMap L G)
    (S : Set (ClassFunction L ℂ)) (A : Set L)
    [Fintype L] [Fintype G]
    [Invertible (Nat.card L : ℂ)] [Invertible (Nat.card G : ℂ)] where
  nonzero : ∃ φ : ClassFunction L ℂ, φ ∈ zSupportedSpan (L := L) S A ∧ φ ≠ 0
  extension : IntegralCharacterMap L G
  extension_isometry : IsIntegralIsometry (L := L) (G := G) extension
  extends_on_supported :
    ∀ φ : ClassFunction L ℂ, φ ∈ zSupportedSpan (L := L) S A → extension φ = τ φ

namespace IsCoherent

variable {τ : IntegralCharacterMap L G} {S : Set (ClassFunction L ℂ)} {A : Set L}
variable [Fintype L] [Fintype G]
variable [Invertible (Nat.card L : ℂ)] [Invertible (Nat.card G : ℂ)]

theorem exists_nonzero_supported (hτ : IsCoherent τ S A) :
    ∃ φ : ClassFunction L ℂ, φ ∈ zSupportedSpan (L := L) S A ∧ φ ≠ 0 :=
  hτ.nonzero

theorem extension_agrees (hτ : IsCoherent τ S A)
    {φ : ClassFunction L ℂ} (hφ : φ ∈ zSupportedSpan (L := L) S A) :
    hτ.extension φ = τ φ :=
  hτ.extends_on_supported φ hφ

theorem extension_inner_eq (hτ : IsCoherent τ S A)
    (φ ψ : ClassFunction L ℂ) :
    ClassFunction.inner (hτ.extension φ) (hτ.extension ψ) =
      ClassFunction.inner φ ψ :=
  hτ.extension_isometry.inner_eq φ ψ

theorem inner_eq_on_supported (hτ : IsCoherent τ S A)
    {φ ψ : ClassFunction L ℂ}
    (hφ : φ ∈ zSupportedSpan (L := L) S A)
    (hψ : ψ ∈ zSupportedSpan (L := L) S A) :
    ClassFunction.inner (τ φ) (τ ψ) = ClassFunction.inner φ ψ := by
  rw [← hτ.extension_agrees hφ, ← hτ.extension_agrees hψ]
  exact hτ.extension_inner_eq φ ψ

end IsCoherent

/-- Peterfalvi (5.2)-style hypotheses for coherence applications.  This is a
carrier for later theorems, not a proof that the hypotheses hold in any
particular Dade situation. -/
structure Hypothesis (S : Set (ClassFunction L ℂ)) (A : Set L)
    [Fintype L] [Fintype G]
    [Invertible (Nat.card L : ℂ)] [Invertible (Nat.card G : ℂ)] where
  tau : IntegralCharacterMap L G
  tau_isometry : IsIntegralIsometry (L := L) (G := G) tau
  conjugate_closed : OddOrder.Peterfalvi.S03.ClosedUnderConjugate S
  no_real_characters : OddOrder.Peterfalvi.S03.HasNoRealCharacters S
  pairwise_orthogonal : OddOrder.Peterfalvi.S03.PairwiseOrthogonal S
  difference_image :
    ∀ ⦃χ : ClassFunction L ℂ⦄, χ ∈ S → CharacterDifferenceImage (L := L) (G := G) tau χ
  difference_images_orthogonal :
    ∀ ⦃φ χ : ClassFunction L ℂ⦄ (hφ : φ ∈ S) (hχ : χ ∈ S),
      ClassFunction.inner φ χ = 0 → ClassFunction.inner φ χ.conj = 0 →
        (difference_image hφ).Orthogonal (difference_image hχ)

namespace Hypothesis

variable {S : Set (ClassFunction L ℂ)} {A : Set L}
variable [Fintype L] [Fintype G]
variable [Invertible (Nat.card L : ℂ)] [Invertible (Nat.card G : ℂ)]

/-- The map carried by a §7 hypothesis, as a coherence predicate target. -/
abbrev IsCoherentTarget (hyp : Hypothesis (L := L) (G := G) S A) :=
  IsCoherent hyp.tau S A

theorem tau_inner_eq (hyp : Hypothesis (L := L) (G := G) S A)
    (φ ψ : ClassFunction L ℂ) :
    ClassFunction.inner (hyp.tau φ) (hyp.tau ψ) = ClassFunction.inner φ ψ :=
  hyp.tau_isometry.inner_eq φ ψ

/-- The signed irreducible-difference image of `χ - χ̄` supplied by a §7
hypothesis. -/
theorem difference_image_eq {hyp : Hypothesis (L := L) (G := G) S A}
    {χ : ClassFunction L ℂ} (hχ : χ ∈ S) :
    hyp.tau (OddOrder.Peterfalvi.S03.conjugateDifference χ) =
      (hyp.difference_image hχ).sign •
        ((hyp.difference_image hχ).muClassFunction -
          (hyp.difference_image hχ).nuClassFunction) :=
  (hyp.difference_image hχ).image_conjugateDifference

theorem difference_image_ne_zero {hyp : Hypothesis (L := L) (G := G) S A}
    {χ : ClassFunction L ℂ} (hχ : χ ∈ S) :
    hyp.tau (OddOrder.Peterfalvi.S03.conjugateDifference χ) ≠ 0 :=
  (hyp.difference_image hχ).image_conjugateDifference_ne_zero

theorem signed_difference_image_ne_zero {hyp : Hypothesis (L := L) (G := G) S A}
    {χ : ClassFunction L ℂ} (hχ : χ ∈ S) :
    (hyp.difference_image hχ).sign •
        ((hyp.difference_image hχ).muClassFunction -
          (hyp.difference_image hχ).nuClassFunction) ≠ 0 :=
  (hyp.difference_image hχ).signed_image_ne_zero

theorem conjugate_mem {hyp : Hypothesis (L := L) (G := G) S A}
    {χ : ClassFunction L ℂ} (hχ : χ ∈ S) :
    χ.conj ∈ S :=
  hyp.conjugate_closed hχ

theorem not_isReal {hyp : Hypothesis (L := L) (G := G) S A}
    {χ : ClassFunction L ℂ} (hχ : χ ∈ S) :
    ¬ χ.IsReal :=
  hyp.no_real_characters hχ

theorem ne_conj {hyp : Hypothesis (L := L) (G := G) S A}
    {χ : ClassFunction L ℂ} (hχ : χ ∈ S) :
    χ ≠ χ.conj := by
  intro hχ_eq
  exact hyp.not_isReal hχ hχ_eq.symm

theorem conjugateDifference_ne_zero {hyp : Hypothesis (L := L) (G := G) S A}
    {χ : ClassFunction L ℂ} (hχ : χ ∈ S) :
    OddOrder.Peterfalvi.S03.conjugateDifference χ ≠ 0 :=
  (OddOrder.Peterfalvi.S03.conjugateDifference_ne_zero_iff_not_isReal χ).mpr
    (hyp.not_isReal hχ)

theorem difference_images_orthogonal_of_inner_pair
    {hyp : Hypothesis (L := L) (G := G) S A}
    {φ χ : ClassFunction L ℂ} (hφ : φ ∈ S) (hχ : χ ∈ S)
    (hφχ : ClassFunction.inner φ χ = 0)
    (hφχ_conj : ClassFunction.inner φ χ.conj = 0) :
    (hyp.difference_image hφ).Orthogonal (hyp.difference_image hχ) :=
  hyp.difference_images_orthogonal hφ hχ hφχ hφχ_conj

end Hypothesis

end OddOrder.Peterfalvi.S07
