/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.Algebra.Module.Submodule.LinearMap
import OddOrder.GroupTheory.RepresentationTheory.RowOrthogonality
import OddOrder.Peterfalvi.S06_DadeIsometryCertain

/-!
# Peterfalvi §7: Coherence

T. Peterfalvi, *Character Theory for the Odd Order Theorem* (LMS LNS 272, 2000),
§7, pp. 25-29.

This file defines the first Lean interface for Peterfalvi coherence.  Following
the audit note, (5.1) is encoded as an extension property only: the
"character-difference" conclusion belongs to (5.9), and the difference used in
§7 is `chi - conj chi`.

Reference note: `notes/peterfalvi/s07_coherence.md`.
-/

namespace OddOrder.Peterfalvi.S07

open OddOrder.RepresentationTheory

variable {L G : Type*} [Group L] [Group G]

/- 5: Coherence (pp. 25-29) -/

/-- The integral span generated by a set of class functions. -/
def zSpan (S : Set (ClassFunction L ℂ)) : Submodule ℤ (ClassFunction L ℂ) :=
  Submodule.span ℤ S

/-- The part of `Z[S]` supported on `A`.

This is kept as a predicate-shaped set for now, because the `CF(L,A)` complex
submodule and the integral lattice `Z[S]` live over different scalar rings. -/
def zSupportedSpan (S : Set (ClassFunction L ℂ)) (A : Set L) :
    Set (ClassFunction L ℂ) :=
  {φ | φ ∈ zSpan (L := L) S ∧ φ.support ⊆ A}

theorem mem_zSupportedSpan_iff {S : Set (ClassFunction L ℂ)} {A : Set L}
    {φ : ClassFunction L ℂ} :
    φ ∈ zSupportedSpan (L := L) S A ↔
      φ ∈ zSpan (L := L) S ∧ φ.support ⊆ A :=
  Iff.rfl

theorem mem_zSpan_of_mem_zSupportedSpan {S : Set (ClassFunction L ℂ)} {A : Set L}
    {φ : ClassFunction L ℂ} (hφ : φ ∈ zSupportedSpan (L := L) S A) :
    φ ∈ zSpan (L := L) S :=
  hφ.1

theorem support_subset_of_mem_zSupportedSpan {S : Set (ClassFunction L ℂ)} {A : Set L}
    {φ : ClassFunction L ℂ} (hφ : φ ∈ zSupportedSpan (L := L) S A) :
    φ.support ⊆ A :=
  hφ.2

theorem zero_mem_zSupportedSpan {S : Set (ClassFunction L ℂ)} {A : Set L} :
    (0 : ClassFunction L ℂ) ∈ zSupportedSpan (L := L) S A := by
  exact ⟨Submodule.zero_mem _, by simp⟩

theorem neg_mem_zSupportedSpan {S : Set (ClassFunction L ℂ)} {A : Set L}
    {φ : ClassFunction L ℂ} (hφ : φ ∈ zSupportedSpan (L := L) S A) :
    -φ ∈ zSupportedSpan (L := L) S A := by
  constructor
  · exact Submodule.neg_mem _ hφ.1
  · intro x hx
    exact hφ.2 (by simpa [ClassFunction.mem_support] using hx)

theorem add_mem_zSupportedSpan {S : Set (ClassFunction L ℂ)} {A : Set L}
    {φ ψ : ClassFunction L ℂ}
    (hφ : φ ∈ zSupportedSpan (L := L) S A)
    (hψ : ψ ∈ zSupportedSpan (L := L) S A) :
    φ + ψ ∈ zSupportedSpan (L := L) S A := by
  constructor
  · exact Submodule.add_mem _ hφ.1 hψ.1
  · intro x hx
    rcases ClassFunction.support_add_subset φ ψ hx with hxφ | hxψ
    · exact hφ.2 hxφ
    · exact hψ.2 hxψ

theorem sub_mem_zSupportedSpan {S : Set (ClassFunction L ℂ)} {A : Set L}
    {φ ψ : ClassFunction L ℂ}
    (hφ : φ ∈ zSupportedSpan (L := L) S A)
    (hψ : ψ ∈ zSupportedSpan (L := L) S A) :
    φ - ψ ∈ zSupportedSpan (L := L) S A := by
  simpa [sub_eq_add_neg] using
    add_mem_zSupportedSpan (L := L) hφ (neg_mem_zSupportedSpan (L := L) hψ)

theorem zSupportedSpan_mono_left {S₁ S : Set (ClassFunction L ℂ)} {A : Set L}
    (hS : S₁ ⊆ S) {φ : ClassFunction L ℂ}
    (hφ : φ ∈ zSupportedSpan (L := L) S₁ A) :
    φ ∈ zSupportedSpan (L := L) S A :=
  ⟨Submodule.span_mono hS hφ.1, hφ.2⟩

theorem zSupportedSpan_mono_right {S : Set (ClassFunction L ℂ)} {A₁ A : Set L}
    (hA : A₁ ⊆ A) {φ : ClassFunction L ℂ}
    (hφ : φ ∈ zSupportedSpan (L := L) S A₁) :
    φ ∈ zSupportedSpan (L := L) S A :=
  ⟨hφ.1, hφ.2.trans hA⟩

/-- An integral linear map between virtual-character lattices, represented at
the class-function level. -/
abbrev IntegralCharacterMap (L G : Type*) [Group L] [Group G] :=
  ClassFunction L ℂ →ₗ[ℤ] ClassFunction G ℂ

/-- The normalized inner-product part of an integral isometry. -/
structure IsIntegralIsometry (τ : IntegralCharacterMap L G)
    [Fintype L] [Fintype G]
    [Invertible (Nat.card L : ℂ)] [Invertible (Nat.card G : ℂ)] : Prop where
  inner_eq :
    ∀ φ ψ : ClassFunction L ℂ,
      ClassFunction.inner (τ φ) (τ ψ) = ClassFunction.inner φ ψ

/-- The Peterfalvi (5.2.d) image data for one character difference.

For `χ ∈ S`, later applications prove that the image of `χ - χ̄` under the
integral isometry is a signed difference of two irreducible characters of `G`.
The hard existence theorem is supplied by
`OddOrder.RepresentationTheory.isometry_difference_pair_structure`; this
structure records the reusable conclusion in the coherence interface. -/
structure CharacterDifferenceImage (τ : IntegralCharacterMap L G)
    (χ : ClassFunction L ℂ) where
  mu : IrreducibleCharacter G
  nu : IrreducibleCharacter G
  distinct : mu ≠ nu
  sign : ℤ
  sign_eq : sign = 1 ∨ sign = -1
  image_eq :
    τ (χ - χ.conj) =
      sign • ((mu : ClassFunction G ℂ) - (nu : ClassFunction G ℂ))

namespace CharacterDifferenceImage

variable {τ : IntegralCharacterMap L G} {χ ψ : ClassFunction L ℂ}

/-- The first irreducible character appearing in the signed image, as a class
function. -/
abbrev muClassFunction (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    ClassFunction G ℂ :=
  hχ.mu

/-- The second irreducible character appearing in the signed image, as a class
function. -/
abbrev nuClassFunction (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    ClassFunction G ℂ :=
  hχ.nu

/-- The unsigned difference `μ - ν` attached to the image of `χ - χ̄`. -/
abbrev difference (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    ClassFunction G ℂ :=
  hχ.muClassFunction - hχ.nuClassFunction

/-- The signed difference `ε • (μ - ν)` attached to the image of `χ - χ̄`. -/
abbrev signedDifference (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    ClassFunction G ℂ :=
  hχ.sign • hχ.difference

@[simp] theorem mu_irreducible
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    IsIrreducibleCharacter hχ.muClassFunction :=
  hχ.mu.isIrreducible

@[simp] theorem nu_irreducible
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    IsIrreducibleCharacter hχ.nuClassFunction :=
  hχ.nu.isIrreducible

/-- The two irreducible characters appearing in the image of `χ - χ̄`.

This is the current two-element form of Peterfalvi's `R(χ)` from (5.2.d). -/
def imageSet (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    Set (ClassFunction G ℂ) :=
  {hχ.muClassFunction, hχ.nuClassFunction}

@[simp] theorem muClassFunction_mem_imageSet
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    hχ.muClassFunction ∈ hχ.imageSet := by
  simp [imageSet]

@[simp] theorem nuClassFunction_mem_imageSet
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    hχ.nuClassFunction ∈ hχ.imageSet := by
  simp [imageSet]

theorem mem_imageSet_iff
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ)
    {φ : ClassFunction G ℂ} :
    φ ∈ hχ.imageSet ↔ φ = hχ.muClassFunction ∨ φ = hχ.nuClassFunction := by
  simp [imageSet]

theorem imageSet_irreducible
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ)
    {φ : ClassFunction G ℂ} (hφ : φ ∈ hχ.imageSet) :
    IsIrreducibleCharacter φ := by
  rw [hχ.mem_imageSet_iff] at hφ
  rcases hφ with rfl | rfl
  · exact hχ.mu_irreducible
  · exact hχ.nu_irreducible

theorem muClassFunction_ne_nuClassFunction
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    hχ.muClassFunction ≠ hχ.nuClassFunction := by
  intro h
  exact hχ.distinct (IrreducibleCharacter.ext h)

theorem difference_ne_zero
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    hχ.difference ≠ 0 :=
  sub_ne_zero.mpr hχ.muClassFunction_ne_nuClassFunction

theorem sign_ne_zero
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    hχ.sign ≠ 0 := by
  rcases hχ.sign_eq with hsign | hsign <;> simp [hsign]

theorem sign_mul_self
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    hχ.sign * hχ.sign = 1 := by
  rcases hχ.sign_eq with hsign | hsign <;> simp [hsign]

theorem image_eq_signedDifference
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    τ (χ - χ.conj) = hχ.signedDifference := by
  simpa [signedDifference, difference] using hχ.image_eq

theorem signed_image_ne_zero
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    hχ.signedDifference ≠ 0 := by
  rcases hχ.sign_eq with hsign | hsign
  · simpa [signedDifference, hsign] using hχ.difference_ne_zero
  · have hneg : -hχ.difference ≠ 0 := neg_ne_zero.mpr hχ.difference_ne_zero
    simpa [signedDifference, hsign] using hneg

theorem difference_inner_self
    [Fintype G] [Invertible (Nat.card G : ℂ)]
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    ClassFunction.inner hχ.difference hχ.difference = 2 := by
  rw [difference, ClassFunction.inner_sub_left, ClassFunction.inner_sub_right,
    ClassFunction.inner_sub_right]
  have hμμ :
      ClassFunction.inner hχ.muClassFunction hχ.muClassFunction = 1 := by
    simpa [muClassFunction, OddOrder.RepresentationTheory.characterTableRowPairing] using
      OddOrder.RepresentationTheory.CharacterTableRowOrthogonality.diagonal
        (G := G) OddOrder.RepresentationTheory.characterTableRowOrthogonality hχ.mu
  have hμν :
      ClassFunction.inner hχ.muClassFunction hχ.nuClassFunction = 0 := by
    simpa [muClassFunction, nuClassFunction,
      OddOrder.RepresentationTheory.characterTableRowPairing] using
      OddOrder.RepresentationTheory.CharacterTableRowOrthogonality.offDiagonal
        (G := G) OddOrder.RepresentationTheory.characterTableRowOrthogonality hχ.distinct
  have hνμ :
      ClassFunction.inner hχ.nuClassFunction hχ.muClassFunction = 0 := by
    simpa [muClassFunction, nuClassFunction,
      OddOrder.RepresentationTheory.characterTableRowPairing] using
      OddOrder.RepresentationTheory.CharacterTableRowOrthogonality.offDiagonal
        (G := G) OddOrder.RepresentationTheory.characterTableRowOrthogonality (Ne.symm hχ.distinct)
  have hνν :
      ClassFunction.inner hχ.nuClassFunction hχ.nuClassFunction = 1 := by
    simpa [nuClassFunction, OddOrder.RepresentationTheory.characterTableRowPairing] using
      OddOrder.RepresentationTheory.CharacterTableRowOrthogonality.diagonal
        (G := G) OddOrder.RepresentationTheory.characterTableRowOrthogonality hχ.nu
  rw [hμμ, hμν, hνμ, hνν]
  norm_num

theorem signedDifference_inner_self
    [Fintype G] [Invertible (Nat.card G : ℂ)]
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    ClassFunction.inner hχ.signedDifference hχ.signedDifference = 2 := by
  rcases hχ.sign_eq with hsign | hsign
  · simpa [signedDifference, hsign] using hχ.difference_inner_self
  · calc
      ClassFunction.inner hχ.signedDifference hχ.signedDifference =
          ClassFunction.inner (-hχ.difference) (-hχ.difference) := by
            simp [signedDifference, hsign]
      _ = ClassFunction.inner hχ.difference hχ.difference := by
            rw [ClassFunction.inner_neg_left, ClassFunction.inner_neg_right, neg_neg]
      _ = 2 := hχ.difference_inner_self

/-- Orthogonality of the two image sets `R(χ)` and `R(ψ)` from Peterfalvi
(5.2.e). -/
def Orthogonal (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ)
    (hψ : CharacterDifferenceImage (L := L) (G := G) τ ψ)
    [Fintype G] [Invertible (Nat.card G : ℂ)] : Prop :=
  ∀ ⦃φ η : ClassFunction G ℂ⦄, φ ∈ hχ.imageSet → η ∈ hψ.imageSet →
    ClassFunction.inner φ η = 0

/-- Restatement using the named §3/§7 helper for the expression `χ - χ̄`. -/
theorem image_conjugateDifference (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    τ (OddOrder.Peterfalvi.S03.conjugateDifference χ) =
      hχ.signedDifference := by
  simpa [OddOrder.Peterfalvi.S03.conjugateDifference] using hχ.image_eq_signedDifference

theorem image_conjugateDifference_ne_zero
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    τ (OddOrder.Peterfalvi.S03.conjugateDifference χ) ≠ 0 := by
  rw [hχ.image_conjugateDifference]
  exact hχ.signed_image_ne_zero

theorem image_conjugateDifference_inner_self
    [Fintype G] [Invertible (Nat.card G : ℂ)]
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    ClassFunction.inner
        (τ (OddOrder.Peterfalvi.S03.conjugateDifference χ))
        (τ (OddOrder.Peterfalvi.S03.conjugateDifference χ)) = 2 := by
  rw [hχ.image_conjugateDifference]
  exact hχ.signedDifference_inner_self

theorem Orthogonal.difference_inner_eq_zero
    [Fintype G] [Invertible (Nat.card G : ℂ)]
    {hχ : CharacterDifferenceImage (L := L) (G := G) τ χ}
    {hψ : CharacterDifferenceImage (L := L) (G := G) τ ψ}
    (horth : hχ.Orthogonal hψ) :
    ClassFunction.inner hχ.difference hψ.difference = 0 := by
  rw [difference, ClassFunction.inner_sub_left, ClassFunction.inner_sub_right,
    ClassFunction.inner_sub_right]
  rw [horth hχ.muClassFunction_mem_imageSet hψ.muClassFunction_mem_imageSet]
  rw [horth hχ.muClassFunction_mem_imageSet hψ.nuClassFunction_mem_imageSet]
  rw [horth hχ.nuClassFunction_mem_imageSet hψ.muClassFunction_mem_imageSet]
  rw [horth hχ.nuClassFunction_mem_imageSet hψ.nuClassFunction_mem_imageSet]
  simp

theorem Orthogonal.signedDifference_inner_eq_zero
    [Fintype G] [Invertible (Nat.card G : ℂ)]
    {hχ : CharacterDifferenceImage (L := L) (G := G) τ χ}
    {hψ : CharacterDifferenceImage (L := L) (G := G) τ ψ}
    (horth : hχ.Orthogonal hψ) :
    ClassFunction.inner hχ.signedDifference hψ.signedDifference = 0 := by
  rcases hχ.sign_eq with hχsign | hχsign <;>
    rcases hψ.sign_eq with hψsign | hψsign
  · simpa [signedDifference, hχsign, hψsign] using horth.difference_inner_eq_zero
  · calc
      ClassFunction.inner hχ.signedDifference hψ.signedDifference =
          ClassFunction.inner hχ.difference (-hψ.difference) := by
            simp [signedDifference, hχsign, hψsign]
      _ = 0 := by
            rw [ClassFunction.inner_neg_right, horth.difference_inner_eq_zero, neg_zero]
  · calc
      ClassFunction.inner hχ.signedDifference hψ.signedDifference =
          ClassFunction.inner (-hχ.difference) hψ.difference := by
            simp [signedDifference, hχsign, hψsign]
      _ = 0 := by
            rw [ClassFunction.inner_neg_left, horth.difference_inner_eq_zero, neg_zero]
  · calc
      ClassFunction.inner hχ.signedDifference hψ.signedDifference =
          ClassFunction.inner (-hχ.difference) (-hψ.difference) := by
            simp [signedDifference, hχsign, hψsign]
      _ = ClassFunction.inner hχ.difference hψ.difference := by
            rw [ClassFunction.inner_neg_left, ClassFunction.inner_neg_right, neg_neg]
      _ = 0 := horth.difference_inner_eq_zero

theorem Orthogonal.image_conjugateDifference_inner_eq_zero
    [Fintype G] [Invertible (Nat.card G : ℂ)]
    {hχ : CharacterDifferenceImage (L := L) (G := G) τ χ}
    {hψ : CharacterDifferenceImage (L := L) (G := G) τ ψ}
    (horth : hχ.Orthogonal hψ) :
    ClassFunction.inner
        (τ (OddOrder.Peterfalvi.S03.conjugateDifference χ))
        (τ (OddOrder.Peterfalvi.S03.conjugateDifference ψ)) = 0 := by
  rw [hχ.image_conjugateDifference, hψ.image_conjugateDifference]
  exact horth.signedDifference_inner_eq_zero

end CharacterDifferenceImage

/-! ### Peterfalvi (5.2.d): the general orthonormal difference-image family `R(χ)`

The two-element `CharacterDifferenceImage` records the special case where `R(χ) = {ε·μ, -ε·ν}`
has exactly two elements.  Peterfalvi (5.2.d) is more general: `(χ - χ̄)^τ = ∑_{α ∈ R(χ)} α` for
an **orthonormal subset `R(χ)` of `ℤ[Irr G]`** (norm-`1`, pairwise-orthogonal virtual
characters, not necessarily single irreducibles).  This is the gateway that the §7 (5.4)
norm inequalities are stated against. -/

open scoped Classical in
open OddOrder.RepresentationTheory in
/-- **Peterfalvi (5.2.d): orthonormal character-difference image.**

For `χ ∈ S`, the image of `χ - χ̄` under the integral isometry `τ` is a sum
`(χ - χ̄)^τ = ∑_{α ∈ R(χ)} α` over a finite **orthonormal** family `R(χ) = imageSet`
of virtual characters (each `α ∈ ℤ[Irr G]`, `‖α‖² = 1`, mutually orthogonal).  This is
the general form of `CharacterDifferenceImage`, which is recovered as the two-element case
via `CharacterDifferenceImage.toOrthonormalImage`. -/
structure OrthonormalCharacterImageFamily (τ : IntegralCharacterMap L G)
    (χ : ClassFunction L ℂ)
    [Fintype G] [Invertible (Nat.card G : ℂ)] where
  /-- The orthonormal subset `R(χ)` of `ℤ[Irr G]`. -/
  imageSet : Finset (ClassFunction G ℂ)
  /-- Every member of `R(χ)` is a virtual character of `G`. -/
  mem_ZIrr : ∀ α ∈ imageSet, α ∈ ZIrr G
  /-- `R(χ)` is orthonormal: `⟨α, β⟩ = δ_{α,β}` for `α, β ∈ R(χ)`. -/
  orthonormal :
    ∀ α ∈ imageSet, ∀ β ∈ imageSet,
      ClassFunction.inner α β = if α = β then (1 : ℂ) else 0
  /-- The image equation `(χ - χ̄)^τ = ∑_{α ∈ R(χ)} α`. -/
  image_eq : τ (χ - χ.conj) = ∑ α ∈ imageSet, α

namespace OrthonormalCharacterImageFamily

open OddOrder.RepresentationTheory

variable {τ : IntegralCharacterMap L G} {χ ψ : ClassFunction L ℂ}
variable [Fintype G] [Invertible (Nat.card G : ℂ)]

/-- The squared norm of an element of `R(χ)` is `1`. -/
theorem inner_self_of_mem (R : OrthonormalCharacterImageFamily (L := L) (G := G) τ χ)
    {α : ClassFunction G ℂ} (hα : α ∈ R.imageSet) :
    ClassFunction.inner α α = 1 := by
  rw [R.orthonormal α hα α hα, if_pos rfl]

/-- Distinct members of `R(χ)` are orthogonal. -/
theorem inner_eq_zero_of_ne (R : OrthonormalCharacterImageFamily (L := L) (G := G) τ χ)
    {α β : ClassFunction G ℂ} (hα : α ∈ R.imageSet) (hβ : β ∈ R.imageSet) (hαβ : α ≠ β) :
    ClassFunction.inner α β = 0 := by
  rw [R.orthonormal α hα β hβ, if_neg hαβ]

/-- The image equation in `conjugateDifference` form: `τ (χ - χ̄) = ∑_{α ∈ R(χ)} α`. -/
theorem image_conjugateDifference
    (R : OrthonormalCharacterImageFamily (L := L) (G := G) τ χ) :
    τ (OddOrder.Peterfalvi.S03.conjugateDifference χ) = ∑ α ∈ R.imageSet, α := by
  simpa [OddOrder.Peterfalvi.S03.conjugateDifference] using R.image_eq

/-- **Peterfalvi (5.2.e): disjoint-pair orthogonality.**  Two image families `R(χ)`,
`R(ψ)` are orthogonal if every `α ∈ R(χ)` is orthogonal to every `β ∈ R(ψ)`. -/
def Orthogonal (R : OrthonormalCharacterImageFamily (L := L) (G := G) τ χ)
    (R' : OrthonormalCharacterImageFamily (L := L) (G := G) τ ψ) : Prop :=
  ∀ α ∈ R.imageSet, ∀ β ∈ R'.imageSet, ClassFunction.inner α β = 0

theorem Orthogonal.inner_eq_zero
    {R : OrthonormalCharacterImageFamily (L := L) (G := G) τ χ}
    {R' : OrthonormalCharacterImageFamily (L := L) (G := G) τ ψ}
    (h : R.Orthogonal R') {α β : ClassFunction G ℂ}
    (hα : α ∈ R.imageSet) (hβ : β ∈ R'.imageSet) :
    ClassFunction.inner α β = 0 :=
  h α hα β hβ

end OrthonormalCharacterImageFamily

namespace CharacterDifferenceImage

open OddOrder.RepresentationTheory

variable {τ : IntegralCharacterMap L G} {χ : ClassFunction L ℂ}
variable [Fintype G] [Invertible (Nat.card G : ℂ)]

open scoped Classical in
/-- `⟨ε·μ, ε·μ⟩ = 1`, `⟨-ε·ν, -ε·ν⟩ = 1`, `⟨ε·μ, -ε·ν⟩ = 0`: the orthonormality
of the two-element family `{ε·μ, -ε·ν}` underlying the two-element case.

Stated as the `δ_{·,·}` identity for the (ℤ-scaled) pair, by reducing the
`ℤ`-scalar `ε` to the `ℂ`-scalar `(ε : ℂ)` and using row orthogonality with
`ε² = 1`.  (The sign hypotheses `hs`/`ht` are unused in the proof but pin down
which scaled pair is meant.) -/
theorem inner_signSmul_pair_eq_ite
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) {s t : ℤ}
    {a b : ClassFunction G ℂ}
    (ha : a = hχ.muClassFunction ∨ a = hχ.nuClassFunction)
    (hb : b = hχ.muClassFunction ∨ b = hχ.nuClassFunction) :
    ClassFunction.inner (s • a) (t • b) =
      (s : ℂ) * (t : ℂ) * (if a = b then (1 : ℂ) else 0) := by
  classical
  have hpair : ClassFunction.inner a b = if a = b then (1 : ℂ) else 0 := by
    have hμμ : ClassFunction.inner hχ.muClassFunction hχ.muClassFunction = 1 := by
      simpa [muClassFunction, OddOrder.RepresentationTheory.characterTableRowPairing] using
        OddOrder.RepresentationTheory.CharacterTableRowOrthogonality.diagonal
          (G := G) OddOrder.RepresentationTheory.characterTableRowOrthogonality hχ.mu
    have hνν : ClassFunction.inner hχ.nuClassFunction hχ.nuClassFunction = 1 := by
      simpa [nuClassFunction, OddOrder.RepresentationTheory.characterTableRowPairing] using
        OddOrder.RepresentationTheory.CharacterTableRowOrthogonality.diagonal
          (G := G) OddOrder.RepresentationTheory.characterTableRowOrthogonality hχ.nu
    have hμν : ClassFunction.inner hχ.muClassFunction hχ.nuClassFunction = 0 := by
      simpa [muClassFunction, nuClassFunction,
        OddOrder.RepresentationTheory.characterTableRowPairing] using
        OddOrder.RepresentationTheory.CharacterTableRowOrthogonality.offDiagonal
          (G := G) OddOrder.RepresentationTheory.characterTableRowOrthogonality hχ.distinct
    have hνμ : ClassFunction.inner hχ.nuClassFunction hχ.muClassFunction = 0 := by
      simpa [muClassFunction, nuClassFunction,
        OddOrder.RepresentationTheory.characterTableRowPairing] using
        OddOrder.RepresentationTheory.CharacterTableRowOrthogonality.offDiagonal
          (G := G) OddOrder.RepresentationTheory.characterTableRowOrthogonality
          (Ne.symm hχ.distinct)
    have hμν_ne : hχ.muClassFunction ≠ hχ.nuClassFunction :=
      hχ.muClassFunction_ne_nuClassFunction
    rcases ha with rfl | rfl <;> rcases hb with rfl | rfl
    · rw [hμμ, if_pos rfl]
    · rw [hμν, if_neg hμν_ne]
    · rw [hνμ, if_neg (Ne.symm hμν_ne)]
    · rw [hνν, if_pos rfl]
  rw [← Int.cast_smul_eq_zsmul ℂ s a, ← Int.cast_smul_eq_zsmul ℂ t b,
    ClassFunction.inner_smul_left, OddOrder.RepresentationTheory.inner_smul_right,
    hpair, star_intCast]
  ring

/-- The two members `ε·μ` and `-ε·ν` of the two-element family are distinct. -/
theorem signMu_ne_negSignNu (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    hχ.sign • (hχ.muClassFunction) ≠ (-hχ.sign) • (hχ.nuClassFunction) := by
  intro h
  -- `⟨ε·μ, ε·μ⟩ = ε² = 1`, but if `ε·μ = -ε·ν` it equals `⟨ε·μ, -ε·ν⟩ = -ε²⟨μ,ν⟩ = 0`.
  have hself := hχ.inner_signSmul_pair_eq_ite (s := hχ.sign) (t := hχ.sign)
    (a := hχ.muClassFunction) (b := hχ.muClassFunction) (Or.inl rfl) (Or.inl rfl)
  have hcross := hχ.inner_signSmul_pair_eq_ite (s := hχ.sign) (t := -hχ.sign)
    (a := hχ.muClassFunction) (b := hχ.nuClassFunction) (Or.inl rfl) (Or.inr rfl)
  rw [if_pos rfl, mul_one] at hself
  rw [if_neg hχ.muClassFunction_ne_nuClassFunction, mul_zero] at hcross
  have hsign : (hχ.sign : ℂ) * (hχ.sign : ℂ) = 1 := by
    have := hχ.sign_mul_self; exact_mod_cast congrArg (Int.cast : ℤ → ℂ) this
  rw [hsign] at hself
  -- `⟨ε·μ, ε·μ⟩ = 1`; replace the *second* `ε·μ` by `-ε·ν` via `h`, then `hcross` gives `1 = 0`.
  nth_rewrite 2 [h] at hself
  rw [hcross] at hself
  exact one_ne_zero hself.symm

open scoped Classical in
/-- **Two-element case of (5.2.d).**  The special two-element `CharacterDifferenceImage`
data yields a genuine `OrthonormalCharacterImageFamily` with `R(χ) = {ε·μ, -ε·ν}`.  This
shows the general gateway subsumes the existing two-element interface. -/
noncomputable def toOrthonormalImage
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    OrthonormalCharacterImageFamily (L := L) (G := G) τ χ where
  imageSet := {hχ.sign • hχ.muClassFunction, (-hχ.sign) • hχ.nuClassFunction}
  mem_ZIrr := by
    intro α hα
    simp only [Finset.mem_insert, Finset.mem_singleton] at hα
    rcases hα with rfl | rfl
    · exact Submodule.smul_mem _ _ hχ.mu.mem_ZIrr
    · exact Submodule.smul_mem _ _ hχ.nu.mem_ZIrr
  orthonormal := by
    classical
    have hsign : (hχ.sign : ℂ) * (hχ.sign : ℂ) = 1 := by
      have := hχ.sign_mul_self; exact_mod_cast congrArg (Int.cast : ℤ → ℂ) this
    have hne := hχ.signMu_ne_negSignNu
    intro α hα β hβ
    simp only [Finset.mem_insert, Finset.mem_singleton] at hα hβ
    rcases hα with rfl | rfl <;> rcases hβ with rfl | rfl
    · rw [if_pos rfl, hχ.inner_signSmul_pair_eq_ite (Or.inl rfl) (Or.inl rfl),
        if_pos rfl, mul_one, hsign]
    · rw [if_neg hne, hχ.inner_signSmul_pair_eq_ite (Or.inl rfl) (Or.inr rfl),
        if_neg hχ.muClassFunction_ne_nuClassFunction, mul_zero]
    · rw [if_neg (Ne.symm hne), hχ.inner_signSmul_pair_eq_ite (Or.inr rfl) (Or.inl rfl),
        if_neg (Ne.symm hχ.muClassFunction_ne_nuClassFunction), mul_zero]
    · rw [if_pos rfl, hχ.inner_signSmul_pair_eq_ite (Or.inr rfl) (Or.inr rfl),
        if_pos rfl, mul_one]
      push_cast
      rw [neg_mul_neg, hsign]
  image_eq := by
    rw [hχ.image_eq, Finset.sum_pair hχ.signMu_ne_negSignNu, neg_smul, ← sub_eq_add_neg,
      ← smul_sub]

end CharacterDifferenceImage

/-! ### Peterfalvi (5.4): the norm inequalities for `X` and `Y`

Setup: `χ ∈ S`, `ψ ∈ ℤ[S]` with `(χ,ψ) = (χ̄,ψ) = 0`; an isometry `τ₁` on
`ℤ[χ-ψ, χ-χ̄]` coinciding with `τ` on `ℤ[χ-χ̄]`; `(χ-ψ)^{τ₁} = X - Y` with
`X ∈ ℤ[R(χ)]` and `Y ⊥ R(χ)`.  The conclusions are:

* (5.4.a) `‖X‖² ≥ ‖χ‖²`;
* (5.4.b) if also `‖Y‖² ≥ ‖ψ‖²`, then `‖X‖² = ‖χ‖²`, `‖Y‖² = ‖ψ‖²` and
  `X = ∑_{α ∈ E} α` for some `E ⊆ R(χ)`.

The whole argument is the integer Cauchy–Schwarz `∑ c_α ≤ ∑ c_α²` against the
orthonormal `R(χ)`, run through the Parseval identities of `ZIrrFourier`. -/

open OddOrder.RepresentationTheory in
/-- **Peterfalvi (5.4) setup.**  Bundles the hypotheses of (5.4): the orthonormal
image family `R(χ)`, the auxiliary isometry `τ₁` agreeing with `τ` on `χ - χ̄`, the
decomposition `(χ - ψ)^{τ₁} = X - Y` with `X ∈ ℤ[R(χ)]` (recorded via integer
coefficients `coeff`) and `Y ⊥ R(χ)`, and the orthogonality relations
`(χ,ψ) = (χ̄,ψ) = (χ,χ̄) = 0`. -/
structure CharacterPsiDecomposition (τ : IntegralCharacterMap L G)
    (χ ψ : ClassFunction L ℂ)
    [Fintype L] [Fintype G]
    [Invertible (Nat.card L : ℂ)] [Invertible (Nat.card G : ℂ)] where
  /-- The orthonormal image family `R(χ)` with `(χ - χ̄)^τ = ∑_{α ∈ R(χ)} α`. -/
  imageFamily : OrthonormalCharacterImageFamily (L := L) (G := G) τ χ
  /-- The auxiliary isometry `τ₁` on `ℤ[χ - ψ, χ - χ̄]`. -/
  tau1 : IntegralCharacterMap L G
  /-- `τ₁` is an integral isometry. -/
  tau1_isometry : IsIntegralIsometry (L := L) (G := G) tau1
  /-- `τ₁` coincides with `τ` on `χ - χ̄`. -/
  tau1_agrees : tau1 (χ - χ.conj) = τ (χ - χ.conj)
  /-- The image side `X` of `(χ - ψ)^{τ₁} = X - Y`. -/
  X : ClassFunction G ℂ
  /-- The orthogonal side `Y` of `(χ - ψ)^{τ₁} = X - Y`. -/
  Y : ClassFunction G ℂ
  /-- The decomposition `(χ - ψ)^{τ₁} = X - Y`. -/
  tau1_image : tau1 (χ - ψ) = X - Y
  /-- The integer coefficients of `X ∈ ℤ[R(χ)]`. -/
  coeff : ClassFunction G ℂ → ℤ
  /-- `X = ∑_{α ∈ R(χ)} (coeff α) • α`, i.e. `X ∈ ℤ[R(χ)]`. -/
  X_eq : X = ∑ α ∈ imageFamily.imageSet, (coeff α : ℂ) • α
  /-- `Y` is orthogonal to `R(χ)`. -/
  Y_orthogonal : ∀ α ∈ imageFamily.imageSet, ClassFunction.inner Y α = 0
  /-- `(χ, ψ) = 0`. -/
  chi_psi_orthogonal : ClassFunction.inner χ ψ = 0
  /-- `(χ̄, ψ) = 0`. -/
  chiConj_psi_orthogonal : ClassFunction.inner χ.conj ψ = 0
  /-- `(χ, χ̄) = 0` (the distinct elements `χ`, `χ̄ ∈ S` are orthogonal by (5.2.c)). -/
  chi_chiConj_orthogonal : ClassFunction.inner χ χ.conj = 0

namespace CharacterPsiDecomposition

open OddOrder.RepresentationTheory

variable {τ : IntegralCharacterMap L G} {χ ψ : ClassFunction L ℂ}
variable [Fintype L] [Fintype G]
variable [Invertible (Nat.card L : ℂ)] [Invertible (Nat.card G : ℂ)]

/-- `⟨X, α⟩ = coeff α` for `α ∈ R(χ)` (orthonormal coefficient recovery). -/
theorem inner_X_eq_coeff (D : CharacterPsiDecomposition (L := L) (G := G) τ χ ψ)
    {α : ClassFunction G ℂ} (hα : α ∈ D.imageFamily.imageSet) :
    ClassFunction.inner D.X α = (D.coeff α : ℂ) := by
  rw [D.X_eq]
  exact inner_orthonormalSum_eq_coeff D.imageFamily.orthonormal hα

/-- `‖X‖² = ∑_{α ∈ R(χ)} (coeff α)²` (Parseval). -/
theorem inner_self_X (D : CharacterPsiDecomposition (L := L) (G := G) τ χ ψ) :
    ClassFunction.inner D.X D.X = ∑ α ∈ D.imageFamily.imageSet, (D.coeff α : ℂ) ^ 2 := by
  rw [D.X_eq]
  exact inner_self_orthonormalSum_eq_sum_sq D.imageFamily.orthonormal

/-- `⟨X, ∑_{α ∈ R(χ)} α⟩ = ∑_{α ∈ R(χ)} coeff α`. -/
theorem inner_X_sum (D : CharacterPsiDecomposition (L := L) (G := G) τ χ ψ) :
    ClassFunction.inner D.X (∑ α ∈ D.imageFamily.imageSet, α) =
      ∑ α ∈ D.imageFamily.imageSet, (D.coeff α : ℂ) := by
  rw [D.X_eq]
  exact inner_orthonormalSum_sum_eq_sum_coeff D.imageFamily.orthonormal

/-- `Y ⊥ R(χ)` extends to the sum: `⟨Y, ∑_{α ∈ R(χ)} α⟩ = 0`. -/
theorem inner_Y_sum (D : CharacterPsiDecomposition (L := L) (G := G) τ χ ψ) :
    ClassFunction.inner D.Y (∑ α ∈ D.imageFamily.imageSet, α) = 0 := by
  rw [inner_sum_right]
  exact Finset.sum_eq_zero fun α hα => D.Y_orthogonal α hα

/-- **The keystone identity of (5.4.a).**  `‖χ‖² = ∑_{α ∈ R(χ)} coeff α`.

`‖χ‖² = ⟨χ - ψ, χ - χ̄⟩` (using the three orthogonality relations), `= ⟨X - Y, ∑ α⟩`
(by the isometry of `τ₁` and `τ₁ = τ` on `χ - χ̄`), `= ⟨X, ∑ α⟩` (since `Y ⊥ R(χ)`),
`= ∑ coeff α`. -/
theorem inner_self_chi_eq_sum_coeff
    (D : CharacterPsiDecomposition (L := L) (G := G) τ χ ψ) :
    ClassFunction.inner χ χ = ∑ α ∈ D.imageFamily.imageSet, (D.coeff α : ℂ) := by
  -- Step 1: `⟨χ, χ⟩ = ⟨χ - ψ, χ - χ̄⟩`.
  have hpsi_chi : ClassFunction.inner ψ χ = 0 := by
    rw [OddOrder.RepresentationTheory.inner_conj_symm, D.chi_psi_orthogonal, star_zero]
  have hpsi_chiConj : ClassFunction.inner ψ χ.conj = 0 := by
    rw [OddOrder.RepresentationTheory.inner_conj_symm, D.chiConj_psi_orthogonal, star_zero]
  have hsrc : ClassFunction.inner χ χ =
      ClassFunction.inner (χ - ψ) (χ - χ.conj) := by
    rw [ClassFunction.inner_sub_left, ClassFunction.inner_sub_right,
      ClassFunction.inner_sub_right, D.chi_chiConj_orthogonal, hpsi_chi, hpsi_chiConj]
    ring
  -- Step 2: transport across `τ₁` (isometry, agreeing with `τ` on `χ - χ̄`).
  have himg : ClassFunction.inner (χ - ψ) (χ - χ.conj) =
      ClassFunction.inner (D.X - D.Y) (∑ α ∈ D.imageFamily.imageSet, α) := by
    rw [← D.tau1_isometry.inner_eq, D.tau1_image, D.tau1_agrees, D.imageFamily.image_eq]
  -- Step 3: `Y ⊥ R(χ)` drops `Y`; coefficient recovery finishes.
  rw [hsrc, himg, ClassFunction.inner_sub_left, D.inner_Y_sum, sub_zero, D.inner_X_sum]

/-- **Peterfalvi (5.4.a):** `‖X‖² ≥ ‖χ‖²`.

By the keystone identity `‖χ‖² = ∑ coeff α` and Parseval `‖X‖² = ∑ (coeff α)²`, the
integer Cauchy–Schwarz `∑ coeff α ≤ ∑ (coeff α)²` gives the inequality. -/
theorem inner_self_chi_re_le_inner_self_X
    (D : CharacterPsiDecomposition (L := L) (G := G) τ χ ψ) :
    (ClassFunction.inner χ χ).re ≤ (ClassFunction.inner D.X D.X).re := by
  classical
  have hχ : ClassFunction.inner χ χ =
      ((∑ α ∈ D.imageFamily.imageSet, D.coeff α : ℤ) : ℂ) := by
    rw [D.inner_self_chi_eq_sum_coeff]; push_cast; ring
  have hX : ClassFunction.inner D.X D.X =
      ((∑ α ∈ D.imageFamily.imageSet, (D.coeff α) ^ 2 : ℤ) : ℂ) := by
    rw [D.inner_self_X]; push_cast; ring
  rw [hχ, hX, Complex.intCast_re, Complex.intCast_re]
  exact_mod_cast finset_sum_le_sum_sq D.imageFamily.imageSet D.coeff

/-- `⟨χ, χ⟩` is the integer cast `(∑ coeff α : ℤ)`. -/
theorem inner_self_chi_eq_intCast
    (D : CharacterPsiDecomposition (L := L) (G := G) τ χ ψ) :
    ClassFunction.inner χ χ = ((∑ α ∈ D.imageFamily.imageSet, D.coeff α : ℤ) : ℂ) := by
  rw [D.inner_self_chi_eq_sum_coeff]; push_cast; ring

/-- `⟨X, X⟩` is the integer cast `(∑ (coeff α)² : ℤ)`. -/
theorem inner_self_X_eq_intCast
    (D : CharacterPsiDecomposition (L := L) (G := G) τ χ ψ) :
    ClassFunction.inner D.X D.X = ((∑ α ∈ D.imageFamily.imageSet, (D.coeff α) ^ 2 : ℤ) : ℂ) := by
  rw [D.inner_self_X]; push_cast; ring

/-- `X ⊥ Y`: `⟨X, Y⟩ = 0` (since `X ∈ ℤ[R(χ)]` and `Y ⊥ R(χ)`). -/
theorem inner_X_Y (D : CharacterPsiDecomposition (L := L) (G := G) τ χ ψ) :
    ClassFunction.inner D.X D.Y = 0 := by
  rw [D.X_eq, inner_sum_left]
  refine Finset.sum_eq_zero fun α hα => ?_
  rw [ClassFunction.inner_smul_left,
    OddOrder.RepresentationTheory.inner_conj_symm, D.Y_orthogonal α hα, star_zero, mul_zero]

/-- `‖X - Y‖² = ‖X‖² + ‖Y‖²` (Pythagoras, since `X ⊥ Y`). -/
theorem inner_self_X_sub_Y (D : CharacterPsiDecomposition (L := L) (G := G) τ χ ψ) :
    ClassFunction.inner (D.X - D.Y) (D.X - D.Y) =
      ClassFunction.inner D.X D.X + ClassFunction.inner D.Y D.Y := by
  have hYX : ClassFunction.inner D.Y D.X = 0 := by
    rw [OddOrder.RepresentationTheory.inner_conj_symm, D.inner_X_Y, star_zero]
  rw [ClassFunction.inner_sub_left, ClassFunction.inner_sub_right,
    ClassFunction.inner_sub_right, D.inner_X_Y, hYX]
  ring

/-- `‖χ - ψ‖² = ‖χ‖² + ‖ψ‖²` (Pythagoras, since `(χ, ψ) = (ψ, χ) = 0`). -/
theorem inner_self_chi_sub_psi (D : CharacterPsiDecomposition (L := L) (G := G) τ χ ψ) :
    ClassFunction.inner (χ - ψ) (χ - ψ) =
      ClassFunction.inner χ χ + ClassFunction.inner ψ ψ := by
  have hpsi_chi : ClassFunction.inner ψ χ = 0 := by
    rw [OddOrder.RepresentationTheory.inner_conj_symm, D.chi_psi_orthogonal, star_zero]
  rw [ClassFunction.inner_sub_left, ClassFunction.inner_sub_right,
    ClassFunction.inner_sub_right, D.chi_psi_orthogonal, hpsi_chi]
  ring

/-- The total-norm identity `‖χ‖² + ‖ψ‖² = ‖X‖² + ‖Y‖²` from the isometry of `τ₁`. -/
theorem inner_self_chi_add_psi_eq
    (D : CharacterPsiDecomposition (L := L) (G := G) τ χ ψ) :
    ClassFunction.inner χ χ + ClassFunction.inner ψ ψ =
      ClassFunction.inner D.X D.X + ClassFunction.inner D.Y D.Y := by
  rw [← D.inner_self_chi_sub_psi, ← D.inner_self_X_sub_Y, ← D.tau1_image,
    D.tau1_isometry.inner_eq]

/-- **Peterfalvi (5.6.2) opening bound:** `‖Y‖² ≤ ‖ψ‖²`.

This is the first step of (5.6.2) ("We note first that `‖χ‖² + a²‖χ₁‖² = ‖X‖² + ‖Y‖²`;
by (5.4.a) `‖X‖² ≥ ‖χ‖²`, so `‖Y‖² ≤ a²‖χ₁‖²`").  It follows directly from the total-norm
identity `‖χ‖² + ‖ψ‖² = ‖X‖² + ‖Y‖²` and (5.4.a) `‖χ‖² ≤ ‖X‖²`, with `ψ = a·χ₁` in the
application.  Stated for the general `ψ` of the (5.4) decomposition. -/
theorem inner_self_Y_re_le_inner_self_psi
    (D : CharacterPsiDecomposition (L := L) (G := G) τ χ ψ) :
    (ClassFunction.inner D.Y D.Y).re ≤ (ClassFunction.inner ψ ψ).re := by
  have htotal : (ClassFunction.inner χ χ).re + (ClassFunction.inner ψ ψ).re =
      (ClassFunction.inner D.X D.X).re + (ClassFunction.inner D.Y D.Y).re := by
    have := congrArg Complex.re D.inner_self_chi_add_psi_eq
    simpa [Complex.add_re] using this
  have hXge := D.inner_self_chi_re_le_inner_self_X
  linarith

/-- **Peterfalvi (5.4.b).**  If `‖Y‖² ≥ ‖ψ‖²`, then `‖X‖² = ‖χ‖²`, `‖Y‖² = ‖ψ‖²`
and `X = ∑_{α ∈ E} α` for some `E ⊆ R(χ)` with `|E| = ‖χ‖²`.

The total-norm identity `‖χ‖² + ‖ψ‖² = ‖X‖² + ‖Y‖²` together with `‖X‖² ≥ ‖χ‖²`
(5.4.a) and the hypothesis `‖Y‖² ≥ ‖ψ‖²` forces both inequalities to be equalities.
The norm equality `‖χ‖² = ‖X‖²` reads `∑ coeff α = ∑ (coeff α)²`, so by the tightness
of integer Cauchy–Schwarz each `coeff α ∈ {0, 1}`; then `E = {α | coeff α = 1}` and
`X = ∑_{α ∈ E} α`.  The cardinality `|E| = ∑ coeff α = ‖χ‖²` is the form used in
(5.6.3) to compute `‖χ̄^{τ₂}‖² = |R(χ)| - |E| = ‖χ - χ̄‖² - ‖χ‖² = ‖χ̄‖²`. -/
theorem norm_eq_and_X_eq_sum_of_norm_Y_ge
    (D : CharacterPsiDecomposition (L := L) (G := G) τ χ ψ)
    (hY : (ClassFunction.inner ψ ψ).re ≤ (ClassFunction.inner D.Y D.Y).re) :
    (ClassFunction.inner χ χ).re = (ClassFunction.inner D.X D.X).re ∧
      (ClassFunction.inner ψ ψ).re = (ClassFunction.inner D.Y D.Y).re ∧
      ∃ E ⊆ D.imageFamily.imageSet, D.X = ∑ α ∈ E, α ∧
        (E.card : ℂ) = ClassFunction.inner χ χ := by
  classical
  -- The `.re` total-norm identity.
  have htotal : (ClassFunction.inner χ χ).re + (ClassFunction.inner ψ ψ).re =
      (ClassFunction.inner D.X D.X).re + (ClassFunction.inner D.Y D.Y).re := by
    have := congrArg Complex.re D.inner_self_chi_add_psi_eq
    simpa [Complex.add_re] using this
  have hXge := D.inner_self_chi_re_le_inner_self_X
  -- Both inequalities are forced to equalities.
  have hχX : (ClassFunction.inner χ χ).re = (ClassFunction.inner D.X D.X).re := by linarith
  have hψY : (ClassFunction.inner ψ ψ).re = (ClassFunction.inner D.Y D.Y).re := by linarith
  refine ⟨hχX, hψY, ?_⟩
  -- Tightness: `∑ coeff = ∑ coeff²` as integers.
  have hsum_eq : (∑ α ∈ D.imageFamily.imageSet, D.coeff α) =
      ∑ α ∈ D.imageFamily.imageSet, (D.coeff α) ^ 2 := by
    have h1 := hχX
    rw [D.inner_self_chi_eq_intCast, D.inner_self_X_eq_intCast,
      Complex.intCast_re, Complex.intCast_re] at h1
    exact_mod_cast h1
  have hcoeff01 : ∀ α ∈ D.imageFamily.imageSet, D.coeff α = 0 ∨ D.coeff α = 1 :=
    (finset_sum_eq_sum_sq_iff D.imageFamily.imageSet D.coeff).mp hsum_eq
  -- `E = {α | coeff α = 1}`.
  set E := D.imageFamily.imageSet.filter (fun α => D.coeff α = 1) with hE
  refine ⟨E, Finset.filter_subset _ _, ?_, ?_⟩
  · -- `X = ∑_{α ∈ E} α`.
    rw [D.X_eq, hE, Finset.sum_filter]
    refine Finset.sum_congr rfl fun α hα => ?_
    rcases hcoeff01 α hα with h0 | h1
    · rw [h0, if_neg (by norm_num), Int.cast_zero, zero_smul]
    · rw [h1, if_pos rfl, Int.cast_one, one_smul]
  · -- `|E| = ∑ coeff α = ‖χ‖²`: on `R(χ)`, `coeff α = (if coeff α = 1 then 1 else 0)`.
    have hcard : (E.card : ℤ) = ∑ α ∈ D.imageFamily.imageSet, D.coeff α := by
      rw [hE, Finset.card_filter, Nat.cast_sum]
      refine Finset.sum_congr rfl fun α hα => ?_
      rcases hcoeff01 α hα with h0 | h1
      · rw [h0, if_neg (by norm_num), Nat.cast_zero]
      · rw [h1, if_pos rfl, Nat.cast_one]
    rw [D.inner_self_chi_eq_intCast]
    exact_mod_cast hcard

/-- **Peterfalvi (5.5).**  Applying (5.4) with `ψ = 0`: the hypothesis `‖Y‖² ≥ ‖ψ‖² = 0`
of (5.4.b) holds automatically (the inner product is positive semidefinite), so `Y = 0`
and `χ^{τ₁} = X = ∑_{α ∈ E} α` for some `E ⊆ R(χ)` with `|E| = ‖χ‖²`.

`‖ψ‖² = ⟨0, 0⟩ = 0 ≤ ‖Y‖²` feeds (5.4.b), whose norm equality `‖Y‖² = ‖ψ‖² = 0` forces
`Y = 0` by positive definiteness of `ClassFunction.inner`.  Then
`χ^{τ₁} = (χ - 0)^{τ₁} = X - Y = X`. -/
theorem eq_sum_of_psi_eq_zero
    (D : CharacterPsiDecomposition (L := L) (G := G) τ χ 0) :
    D.Y = 0 ∧ D.tau1 χ = D.X ∧
      ∃ E ⊆ D.imageFamily.imageSet, D.X = ∑ α ∈ E, α ∧
        (E.card : ℂ) = ClassFunction.inner χ χ := by
  -- `‖ψ‖² = ‖0‖² = 0 ≤ ‖Y‖²` by positive semidefiniteness.
  have hψY : (ClassFunction.inner (0 : ClassFunction L ℂ) 0).re ≤
      (ClassFunction.inner D.Y D.Y).re := by
    rw [ClassFunction.inner_zero_left, Complex.zero_re]
    exact inner_self_re_nonneg D.Y
  obtain ⟨_, hYnorm, E, hEsub, hXsum, hEcard⟩ := D.norm_eq_and_X_eq_sum_of_norm_Y_ge hψY
  -- `‖Y‖² = ‖0‖² = 0`, so `Y = 0` by positive definiteness.
  have hY0 : D.Y = 0 := by
    apply eq_zero_of_inner_self_re_eq_zero
    rw [← hYnorm, ClassFunction.inner_zero_left, Complex.zero_re]
  -- `χ^{τ₁} = (χ - 0)^{τ₁} = X - Y = X`.
  have hτ1χ : D.tau1 χ = D.X := by
    have := D.tau1_image
    rw [sub_zero] at this
    rw [this, hY0, sub_zero]
  exact ⟨hY0, hτ1χ, E, hEsub, hXsum, hEcard⟩

end CharacterPsiDecomposition

/-- Peterfalvi (5.1): `τ` is coherent for `(S,A)` if it admits an integral
isometric extension on `Z[S]` that agrees with `τ` on `Z[S,A]`. -/
structure IsCoherent (τ : IntegralCharacterMap L G)
    (S : Set (ClassFunction L ℂ)) (A : Set L)
    [Fintype L] [Fintype G]
    [Invertible (Nat.card L : ℂ)] [Invertible (Nat.card G : ℂ)] where
  nonzero : ∃ φ : ClassFunction L ℂ, φ ∈ zSupportedSpan (L := L) S A ∧ φ ≠ 0
  extension : IntegralCharacterMap L G
  extension_isometry : IsIntegralIsometry (L := L) (G := G) extension
  extends_on_supported :
    ∀ φ : ClassFunction L ℂ, φ ∈ zSupportedSpan (L := L) S A → extension φ = τ φ

namespace IsCoherent

variable {τ : IntegralCharacterMap L G} {S : Set (ClassFunction L ℂ)} {A : Set L}
variable [Fintype L] [Fintype G]
variable [Invertible (Nat.card L : ℂ)] [Invertible (Nat.card G : ℂ)]

theorem exists_nonzero_supported (hτ : IsCoherent τ S A) :
    ∃ φ : ClassFunction L ℂ, φ ∈ zSupportedSpan (L := L) S A ∧ φ ≠ 0 :=
  hτ.nonzero

theorem extension_agrees (hτ : IsCoherent τ S A)
    {φ : ClassFunction L ℂ} (hφ : φ ∈ zSupportedSpan (L := L) S A) :
    hτ.extension φ = τ φ :=
  hτ.extends_on_supported φ hφ

theorem extension_inner_eq (hτ : IsCoherent τ S A)
    (φ ψ : ClassFunction L ℂ) :
    ClassFunction.inner (hτ.extension φ) (hτ.extension ψ) =
      ClassFunction.inner φ ψ :=
  hτ.extension_isometry.inner_eq φ ψ

theorem inner_eq_on_supported (hτ : IsCoherent τ S A)
    {φ ψ : ClassFunction L ℂ}
    (hφ : φ ∈ zSupportedSpan (L := L) S A)
    (hψ : ψ ∈ zSupportedSpan (L := L) S A) :
    ClassFunction.inner (τ φ) (τ ψ) = ClassFunction.inner φ ψ := by
  rw [← hτ.extension_agrees hφ, ← hτ.extension_agrees hψ]
  exact hτ.extension_inner_eq φ ψ

end IsCoherent

/-- Peterfalvi (5.2)-style hypotheses for coherence applications.  This is a
carrier for later theorems, not a proof that the hypotheses hold in any
particular Dade situation. -/
structure Hypothesis (S : Set (ClassFunction L ℂ)) (A : Set L)
    [Fintype L] [Fintype G]
    [Invertible (Nat.card L : ℂ)] [Invertible (Nat.card G : ℂ)] where
  tau : IntegralCharacterMap L G
  tau_isometry : IsIntegralIsometry (L := L) (G := G) tau
  conjugate_closed : OddOrder.Peterfalvi.S03.ClosedUnderConjugate S
  no_real_characters : OddOrder.Peterfalvi.S03.HasNoRealCharacters S
  pairwise_orthogonal : OddOrder.Peterfalvi.S03.PairwiseOrthogonal S
  difference_image :
    ∀ ⦃χ : ClassFunction L ℂ⦄, χ ∈ S → CharacterDifferenceImage (L := L) (G := G) tau χ
  difference_images_orthogonal :
    ∀ ⦃φ χ : ClassFunction L ℂ⦄ (hφ : φ ∈ S) (hχ : χ ∈ S),
      ClassFunction.inner φ χ = 0 → ClassFunction.inner φ χ.conj = 0 →
        (difference_image hφ).Orthogonal (difference_image hχ)

namespace Hypothesis

variable {S : Set (ClassFunction L ℂ)} {A : Set L}
variable [Fintype L] [Fintype G]
variable [Invertible (Nat.card L : ℂ)] [Invertible (Nat.card G : ℂ)]

/-- The map carried by a §7 hypothesis, as a coherence predicate target. -/
abbrev IsCoherentTarget (hyp : Hypothesis (L := L) (G := G) S A) :=
  IsCoherent hyp.tau S A

theorem tau_inner_eq (hyp : Hypothesis (L := L) (G := G) S A)
    (φ ψ : ClassFunction L ℂ) :
    ClassFunction.inner (hyp.tau φ) (hyp.tau ψ) = ClassFunction.inner φ ψ :=
  hyp.tau_isometry.inner_eq φ ψ

/-- The signed irreducible-difference image of `χ - χ̄` supplied by a §7
hypothesis. -/
theorem difference_image_eq {hyp : Hypothesis (L := L) (G := G) S A}
    {χ : ClassFunction L ℂ} (hχ : χ ∈ S) :
    hyp.tau (OddOrder.Peterfalvi.S03.conjugateDifference χ) =
      (hyp.difference_image hχ).sign •
        ((hyp.difference_image hχ).muClassFunction -
          (hyp.difference_image hχ).nuClassFunction) :=
  (hyp.difference_image hχ).image_conjugateDifference

theorem difference_image_ne_zero {hyp : Hypothesis (L := L) (G := G) S A}
    {χ : ClassFunction L ℂ} (hχ : χ ∈ S) :
    hyp.tau (OddOrder.Peterfalvi.S03.conjugateDifference χ) ≠ 0 :=
  (hyp.difference_image hχ).image_conjugateDifference_ne_zero

theorem signed_difference_image_ne_zero {hyp : Hypothesis (L := L) (G := G) S A}
    {χ : ClassFunction L ℂ} (hχ : χ ∈ S) :
    (hyp.difference_image hχ).sign •
        ((hyp.difference_image hχ).muClassFunction -
          (hyp.difference_image hχ).nuClassFunction) ≠ 0 :=
  (hyp.difference_image hχ).signed_image_ne_zero

theorem conjugate_mem {hyp : Hypothesis (L := L) (G := G) S A}
    {χ : ClassFunction L ℂ} (hχ : χ ∈ S) :
    χ.conj ∈ S :=
  hyp.conjugate_closed hχ

theorem not_isReal {hyp : Hypothesis (L := L) (G := G) S A}
    {χ : ClassFunction L ℂ} (hχ : χ ∈ S) :
    ¬ χ.IsReal :=
  hyp.no_real_characters hχ

theorem ne_conj {hyp : Hypothesis (L := L) (G := G) S A}
    {χ : ClassFunction L ℂ} (hχ : χ ∈ S) :
    χ ≠ χ.conj := by
  intro hχ_eq
  exact hyp.not_isReal hχ hχ_eq.symm

theorem conjugateDifference_ne_zero {hyp : Hypothesis (L := L) (G := G) S A}
    {χ : ClassFunction L ℂ} (hχ : χ ∈ S) :
    OddOrder.Peterfalvi.S03.conjugateDifference χ ≠ 0 :=
  (OddOrder.Peterfalvi.S03.conjugateDifference_ne_zero_iff_not_isReal χ).mpr
    (hyp.not_isReal hχ)

theorem difference_images_orthogonal_of_inner_pair
    {hyp : Hypothesis (L := L) (G := G) S A}
    {φ χ : ClassFunction L ℂ} (hφ : φ ∈ S) (hχ : χ ∈ S)
    (hφχ : ClassFunction.inner φ χ = 0)
    (hφχ_conj : ClassFunction.inner φ χ.conj = 0) :
    (hyp.difference_image hφ).Orthogonal (hyp.difference_image hχ) :=
  hyp.difference_images_orthogonal hφ hχ hφχ hφχ_conj

theorem difference_image_inner_self
    {hyp : Hypothesis (L := L) (G := G) S A}
    {χ : ClassFunction L ℂ} (hχ : χ ∈ S) :
    ClassFunction.inner
        (hyp.tau (OddOrder.Peterfalvi.S03.conjugateDifference χ))
        (hyp.tau (OddOrder.Peterfalvi.S03.conjugateDifference χ)) = 2 :=
  (hyp.difference_image hχ).image_conjugateDifference_inner_self

theorem difference_images_inner_eq_zero_of_inner_pair
    {hyp : Hypothesis (L := L) (G := G) S A}
    {φ χ : ClassFunction L ℂ} (hφ : φ ∈ S) (hχ : χ ∈ S)
    (hφχ : ClassFunction.inner φ χ = 0)
    (hφχ_conj : ClassFunction.inner φ χ.conj = 0) :
    ClassFunction.inner
        (hyp.tau (OddOrder.Peterfalvi.S03.conjugateDifference φ))
        (hyp.tau (OddOrder.Peterfalvi.S03.conjugateDifference χ)) = 0 :=
  CharacterDifferenceImage.Orthogonal.image_conjugateDifference_inner_eq_zero
    (hyp.difference_images_orthogonal_of_inner_pair hφ hχ hφχ hφχ_conj)

end Hypothesis

/-! ### Peterfalvi (5.6): the coherence-union theorem

`S₁ = {χ₁,…,χₙ}` is a conjugation-closed coherent subset of `S` and `{χ, χ̄}` is disjoint
from `S₁` with `χ₁(1) ∣ χ(1)` (write `χ(1) = a·χ₁(1)`).  Under the degree-ratio inequality
`2·χ(1)·χ₁(1) < ∑ᵢ χᵢ(1)²/‖χᵢ‖²`, the union `S₁ ∪ {χ, χ̄}` is coherent.

The proof runs through the (5.4)/(5.5) decomposition machinery: writing
`(χ - a·χ₁)^τ = X - Y` against the orthonormal `R(χ)`, the inequality forces the integer
coefficient `λ` of the orthogonal part `Y` to vanish (5.6.2), so `Y = a·χ₁^{τ₁}` (5.6.1) and
`X = ∑_{α ∈ E} α` for some `E ⊆ R(χ)` with `|E| = ‖χ‖²` (5.5/5.4.b); the extension `τ₂` with
`χ^{τ₂} = X`, `χ̄^{τ₂} = X - (χ - χ̄)^τ` is then the coherence witness. -/

/-- **Peterfalvi (5.6.2): the integer-forcing core.**

The quadratic inequality produced by the (5.6.2) norm computation forces `λ = 0`.  Concretely:
if `D` is a positive rational, `z ≥ 0`, `0 ≤ a`, the strict degree-ratio bound `2·a < D` holds,
and the integer `λ` satisfies `λ²·D - 2·λ·a + z ≤ 0`, then `λ = 0`.

This is exactly the step `λ² - bλ ≤ 0`, `0 < b < 1` (with `b = 2a/D`) `⟹ λ = 0` of the text,
kept division-free: the strict bound `2a < D` is the `b < 1` hypothesis and `0 ≤ a`, `0 < D`
give `0 < b`.  The slack term `z = ‖Z‖² ≥ 0` is carried so the caller need not drop it first. -/
theorem int_eq_zero_of_sq_mul_le_of_two_mul_lt
    {lam : ℤ} {D a z : ℚ}
    (hD : 0 < D) (hz : 0 ≤ z) (ha : 0 ≤ a) (hbnd : 2 * a < D)
    (hquad : (lam : ℚ) ^ 2 * D - 2 * (lam : ℚ) * a + z ≤ 0) :
    lam = 0 := by
  -- From `λ²·D - 2λa + z ≤ 0` and `z ≥ 0`: `λ²·D ≤ 2λa`.
  have hcore : (lam : ℚ) ^ 2 * D ≤ 2 * (lam : ℚ) * a := by linarith
  -- `λ ≠ 0` is impossible.
  by_contra hne
  have hne' : lam ≠ 0 := hne
  -- WLOG via cases on the sign of `λ`.
  rcases lt_trichotomy lam 0 with hneg | hzero | hpos
  · -- `λ < 0`: then `2λa ≤ 0 ≤ λ²·D` with `λ²·D > 0`, contradiction.
    have hlamR : (lam : ℚ) < 0 := by exact_mod_cast hneg
    have hsq_pos : 0 < (lam : ℚ) ^ 2 := by positivity
    have hlhs_pos : 0 < (lam : ℚ) ^ 2 * D := mul_pos hsq_pos hD
    have hrhs_nonpos : 2 * (lam : ℚ) * a ≤ 0 := by nlinarith [hlamR, ha]
    linarith
  · exact hne' hzero
  · -- `λ > 0`: divide `λ²·D ≤ 2λa` by `λ > 0` to get `λ·D ≤ 2a < D`, so `λ < 1`, contradiction.
    have hlamR : (0 : ℚ) < (lam : ℚ) := by exact_mod_cast hpos
    have hlam1 : (1 : ℚ) ≤ (lam : ℚ) := by
      have : (1 : ℤ) ≤ lam := hpos
      exact_mod_cast this
    -- `λ²·D = λ·(λ·D)` and `2λa = λ·(2a)`, cancel one `λ`.
    have hcancel : (lam : ℚ) * D ≤ 2 * a := by
      have h2 : (lam : ℚ) * ((lam : ℚ) * D) ≤ (lam : ℚ) * (2 * a) := by nlinarith [hcore]
      exact le_of_mul_le_mul_left h2 hlamR
    -- But `λ ≥ 1` gives `D ≤ λ·D ≤ 2a < D`, contradiction.
    have hDle : D ≤ (lam : ℚ) * D := by nlinarith [hlam1, hD]
    linarith

namespace CharacterPsiDecomposition

open OddOrder.RepresentationTheory

variable {τ : IntegralCharacterMap L G} {χ ψ : ClassFunction L ℂ}
variable [Fintype L] [Fintype G]
variable [Invertible (Nat.card L : ℂ)] [Invertible (Nat.card G : ℂ)]

open scoped Classical in
/-- **Peterfalvi (5.6.2) quadratic bound.**  Suppose the orthogonal part `Y` of the (5.4)
decomposition is written against an **orthogonal family** `v : ι → CF(G)` (indexed over
`s`, with real gram `⟨v i, v j⟩ = if i = j then m i else 0`) plus a residual `Z` orthogonal
to the family, with real coefficients `c`:

`Y = (∑ i ∈ s, (c i) • v i) + Z`.

Then `∑ i ∈ s, (c i)² · m i + ‖Z‖² ≤ ‖ψ‖²`.

This is the geometric half of (5.6.2): the Pythagoras expansion of `‖Y‖²` against the
orthogonal family, combined with the opening bound `‖Y‖² ≤ ‖ψ‖²` (`inner_self_Y_re_le_inner_self_psi`).
The arithmetic half — substituting the (5.6.1) coefficients and forcing the integer `λ = 0` —
is `int_eq_zero_of_sq_mul_le_of_two_mul_lt`. -/
theorem sum_sq_mul_add_normSq_Z_le
    (D : CharacterPsiDecomposition (L := L) (G := G) τ χ ψ)
    {ι : Type*} (s : Finset ι) (v : ι → ClassFunction G ℂ) (c m : ι → ℝ)
    (Z : ClassFunction G ℂ)
    (hY : D.Y = (∑ i ∈ s, (c i : ℂ) • v i) + Z)
    (horth : ∀ i ∈ s, ∀ j ∈ s, ClassFunction.inner (v i) (v j) =
      if i = j then (m i : ℂ) else 0)
    (hZ : ∀ i ∈ s, ClassFunction.inner Z (v i) = 0) :
    (∑ i ∈ s, (c i) ^ 2 * m i) + (ClassFunction.inner Z Z).re ≤
      (ClassFunction.inner ψ ψ).re := by
  have hpyth := inner_self_orthogonalSum_add_re (G := G) s v c m Z horth hZ
  have hYnorm : (ClassFunction.inner D.Y D.Y).re =
      (∑ i ∈ s, (c i) ^ 2 * m i) + (ClassFunction.inner Z Z).re := by
    rw [hY]; exact hpyth
  have hbound := D.inner_self_Y_re_le_inner_self_psi
  rw [hYnorm] at hbound
  exact hbound

open scoped Classical in
/-- **Peterfalvi (5.6.2) capstone: `λ = 0` and `Z = 0`.**

Composes the geometric half (`sum_sq_mul_add_normSq_Z_le`) and the arithmetic half
(`int_eq_zero_of_sq_mul_le_of_two_mul_lt`).  The (5.6.1) decomposition writes the orthogonal
part as

`Y = (∑ i ∈ s, (a·[i = i₁] - λ·r i) • v i) + Z`,

against the orthogonal family `v i` (real gram `m i = ‖χ_i‖²`, `v i = χ_i^{τ₁}`) with `Z`
orthogonal to the family, where `r i = a_i / ‖χ_i‖²`, `i₁` indexes `χ₁`, and `ψ = a·χ₁` (so
`‖ψ‖² = a²·m i₁`, hypothesis `hψ`) with `a₁ = 1` (so `r i₁ · m i₁ = 1`, hypothesis `hr₁`).

The Pythagoras expansion gives `∑ (a·[i=i₁] - λ·r i)²·m i + ‖Z‖² ≤ ‖ψ‖² = a²·m i₁`; the
algebraic identity collapses the left sum to `a²·m i₁ - 2·a·λ + λ²·D` with
`D = ∑ (r i)²·m i`, so `λ²·D - 2·λ·a + ‖Z‖² ≤ 0`.  Hypothesis (c) `2·a < D` then forces
`λ = 0` (`int_eq_zero_of_sq_mul_le_of_two_mul_lt`), and feeding `λ = 0` back gives `‖Z‖² ≤ 0`,
hence `Z = 0` by positive definiteness. -/
theorem lambda_eq_zero_and_Z_eq_zero
    (D : CharacterPsiDecomposition (L := L) (G := G) τ χ ψ)
    {ι : Type*} (s : Finset ι) (i₁ : ι) (hi₁ : i₁ ∈ s)
    (a : ℝ) (lam : ℤ) (Z : ClassFunction G ℂ)
    (vc : ι → ClassFunction G ℂ) (mc : ι → ℝ) (rc : ι → ℝ)
    (hY : D.Y = (∑ i ∈ s, ((a * (if i = i₁ then 1 else 0) - (lam : ℝ) * rc i : ℝ) : ℂ) • vc i)
      + Z)
    (horth : ∀ i ∈ s, ∀ j ∈ s, ClassFunction.inner (vc i) (vc j) =
      if i = j then (mc i : ℂ) else 0)
    (hZ : ∀ i ∈ s, ClassFunction.inner Z (vc i) = 0)
    (hψ : (ClassFunction.inner ψ ψ).re = a ^ 2 * mc i₁)
    (hr₁ : rc i₁ * mc i₁ = 1)
    (ha : 0 ≤ a)
    (hD : 2 * a < ∑ i ∈ s, (rc i) ^ 2 * mc i) :
    lam = 0 ∧ Z = 0 := by
  classical
  -- Geometric half: `∑ (c i)²·m i + ‖Z‖² ≤ ‖ψ‖²`.
  have hgeo := D.sum_sq_mul_add_normSq_Z_le s vc
    (fun i => a * (if i = i₁ then 1 else 0) - (lam : ℝ) * rc i) mc Z hY horth hZ
  -- Algebraic collapse of the left sum.
  have halg : (∑ i ∈ s, (a * (if i = i₁ then 1 else 0) - (lam : ℝ) * rc i) ^ 2 * mc i)
      = a ^ 2 * mc i₁ - 2 * a * (lam : ℝ) * (rc i₁ * mc i₁)
        + (lam : ℝ) ^ 2 * ∑ i ∈ s, (rc i) ^ 2 * mc i := by
    have key : ∀ i ∈ s,
        (a * (if i = i₁ then 1 else 0) - (lam : ℝ) * rc i) ^ 2 * mc i
        = (if i = i₁ then (a ^ 2 * mc i₁ - 2 * a * (lam : ℝ) * (rc i₁ * mc i₁)) else 0)
          + (lam : ℝ) ^ 2 * ((rc i) ^ 2 * mc i) := by
      intro i hi
      by_cases h : i = i₁
      · subst h; rw [if_pos rfl, if_pos rfl]; ring
      · rw [if_neg h, if_neg h]; ring
    rw [Finset.sum_congr rfl key, Finset.sum_add_distrib, Finset.sum_ite_eq' s i₁,
      if_pos hi₁, ← Finset.mul_sum]
  -- Substitute `r i₁ · m i₁ = 1` and `‖ψ‖² = a²·m i₁`; obtain the quadratic `≤ 0`.
  set Dsum := ∑ i ∈ s, (rc i) ^ 2 * mc i with hDsum
  have hquad : (lam : ℝ) ^ 2 * Dsum - 2 * (lam : ℝ) * a + (ClassFunction.inner Z Z).re ≤ 0 := by
    rw [halg, hr₁, hψ, mul_one] at hgeo
    nlinarith [hgeo]
  -- Integer forcing (cast to ℚ) gives `λ = 0`.
  have hZre_nonneg : (0 : ℝ) ≤ (ClassFunction.inner Z Z).re := inner_self_re_nonneg Z
  have hlam0 : lam = 0 := by
    -- Work over ℝ directly: the integer-forcing argument transcribed.
    by_contra hne
    rcases lt_trichotomy lam 0 with hneg | hzero | hpos
    · have hlamR : (lam : ℝ) < 0 := by exact_mod_cast hneg
      have hsq_pos : 0 < (lam : ℝ) ^ 2 := by positivity
      have hDpos : 0 < Dsum := by
        have : (0 : ℝ) ≤ 2 * a := by linarith
        linarith [hD]
      nlinarith [mul_pos hsq_pos hDpos, hZre_nonneg, mul_nonneg ha (le_of_lt (neg_pos.mpr hlamR))]
    · exact hne hzero
    · have hlam1 : (1 : ℝ) ≤ (lam : ℝ) := by
        have : (1 : ℤ) ≤ lam := hpos; exact_mod_cast this
      have hlampos : (0 : ℝ) < (lam : ℝ) := by linarith
      -- `λ²·D - 2λa + ‖Z‖² ≤ 0`, `‖Z‖² ≥ 0` ⟹ `λ²·D ≤ 2λa`, cancel `λ` ⟹ `λ·D ≤ 2a < D`.
      have hcore : (lam : ℝ) ^ 2 * Dsum ≤ 2 * (lam : ℝ) * a := by linarith
      have hcancel : (lam : ℝ) * Dsum ≤ 2 * a := by
        have h2 : (lam : ℝ) * ((lam : ℝ) * Dsum) ≤ (lam : ℝ) * (2 * a) := by nlinarith [hcore]
        exact le_of_mul_le_mul_left h2 hlampos
      nlinarith [hcancel, hlam1, hD]
  refine ⟨hlam0, ?_⟩
  -- Feed `λ = 0` back: `‖Z‖² ≤ 0`, hence `Z = 0`.
  have hZ0 : (ClassFunction.inner Z Z).re ≤ 0 := by
    rw [hlam0] at hquad; push_cast at hquad; nlinarith [hquad]
  exact eq_zero_of_inner_self_re_eq_zero (le_antisymm hZ0 hZre_nonneg)

open scoped Classical in
/-- **Peterfalvi (5.6.3) conjugate image as a complementary signed sum.**
Given the (5.4.b)/(5.5) output `X = ∑_{α ∈ E} α` for a subset `E ⊆ R(χ)`, the candidate
image of `χ̄` under `τ₂`, namely `X - (χ - χ̄)^τ`, equals the **negated** sum over the
complement `R(χ) - E`:

`X - τ(χ - χ̄) = -∑_{α ∈ R(χ) - E} α`.

Since `(χ - χ̄)^τ = ∑_{α ∈ R(χ)} α` (the image-family equation) and `E ⊆ R(χ)`, the
difference telescopes to the complement. -/
theorem conjImage_eq_neg_sum_sdiff
    (D : CharacterPsiDecomposition (L := L) (G := G) τ χ ψ)
    {E : Finset (ClassFunction G ℂ)} (hE : E ⊆ D.imageFamily.imageSet)
    (hX : D.X = ∑ α ∈ E, α) :
    D.X - τ (χ - χ.conj) = -(∑ α ∈ D.imageFamily.imageSet \ E, α) := by
  classical
  rw [hX, D.imageFamily.image_eq]
  have h := Finset.sum_sdiff (s₁ := E) (s₂ := D.imageFamily.imageSet) hE (f := fun a => a)
  rw [← h]; abel

open scoped Classical in
/-- **Peterfalvi (5.6.3) norm of the conjugate image:** `‖X - (χ - χ̄)^τ‖² = |R(χ)| - |E|`.
With `X = ∑_{α ∈ E} α` (`E ⊆ R(χ)`), the candidate `χ̄^{τ₂} = X - (χ - χ̄)^τ` is the negated
sum over `R(χ) - E`, whose squared norm is the cardinality `|R(χ) - E| = |R(χ)| - |E|` by
orthonormality of `R(χ)`.  This is the computation
`‖χ̄^{τ₂}‖² = |R(χ) - E| = ‖χ - χ̄‖² - ‖χ‖² = ‖χ̄‖²` of the text. -/
theorem inner_self_conjImage_eq_card_sdiff
    (D : CharacterPsiDecomposition (L := L) (G := G) τ χ ψ)
    {E : Finset (ClassFunction G ℂ)} (hE : E ⊆ D.imageFamily.imageSet)
    (hX : D.X = ∑ α ∈ E, α) :
    ClassFunction.inner (D.X - τ (χ - χ.conj)) (D.X - τ (χ - χ.conj)) =
      ((D.imageFamily.imageSet.card : ℤ) - (E.card : ℤ) : ℂ) := by
  classical
  have horth' : ∀ a ∈ D.imageFamily.imageSet \ E, ∀ b ∈ D.imageFamily.imageSet \ E,
      ClassFunction.inner a b = if a = b then (1 : ℂ) else 0 :=
    fun a ha b hb => D.imageFamily.orthonormal a (Finset.mem_sdiff.mp ha).1 b
      (Finset.mem_sdiff.mp hb).1
  rw [D.conjImage_eq_neg_sum_sdiff hE hX, ClassFunction.inner_neg_left,
    ClassFunction.inner_neg_right, neg_neg,
    inner_self_sum_orthonormal_eq_card horth', Finset.card_sdiff_of_subset hE]
  have hle : E.card ≤ D.imageFamily.imageSet.card := Finset.card_le_card hE
  push_cast [Nat.cast_sub hle]
  ring

open scoped Classical in
/-- **Peterfalvi (5.6.3) orthogonality `⟨X, χ̄^{τ₂}⟩ = 0`.**  The candidate images
`χ^{τ₂} = X = ∑_{α ∈ E} α` and `χ̄^{τ₂} = X - (χ - χ̄)^τ = -∑_{α ∈ R(χ) - E} α` are
orthogonal: their inner product is a cross term over the disjoint subsets `E` and
`R(χ) - E` of the orthonormal family `R(χ)`, hence `0`. -/
theorem inner_X_conjImage_eq_zero
    (D : CharacterPsiDecomposition (L := L) (G := G) τ χ ψ)
    {E : Finset (ClassFunction G ℂ)} (hE : E ⊆ D.imageFamily.imageSet)
    (hX : D.X = ∑ α ∈ E, α) :
    ClassFunction.inner D.X (D.X - τ (χ - χ.conj)) = 0 := by
  classical
  rw [D.conjImage_eq_neg_sum_sdiff hE hX, ClassFunction.inner_neg_right, hX,
    inner_sum_orthonormal_eq_zero_of_disjoint hE (Finset.sdiff_subset)
      (Finset.disjoint_sdiff) D.imageFamily.orthonormal, neg_zero]

end CharacterPsiDecomposition

/-! ### The orthonormal-block isometry re-targeting keystone

The (5.6.3) construction of `τ₂` from `τ₁` is an instance of a reusable operation: given a
**global** integral isometry `τ₁ : ℤ[Irr L] → ℤ[Irr G]` (here at the class-function level over
`ℂ`), an **orthonormal pair** `{χ, χ̄}` in the source and an **orthonormal pair** `{X, X̄}` in the
target with the *same* gram matrix, re-target the rank-`2` block: send `χ ↦ X`, `χ̄ ↦ X̄`, keeping
`τ₁` on the orthogonal complement of `{χ, χ̄}`.  The single hypothesis making this a global isometry
is that `X` and `X̄` are orthogonal to `τ₁ ψ` for *every* `ψ` orthogonal to both `χ` and `χ̄`
(in the (5.6) application this is `(5.5) + (5.2.e)`: `S₁^{τ₁} ⊥ R(χ)` and `X, X̄ ∈ ℤ[R(χ)]`).

The construction is the explicit correction map
`τ₂ φ = τ₁ φ + ⟨φ,χ⟩·(X − τ₁χ) + ⟨φ,χ̄⟩·(X̄ − τ₁χ̄)`,
which automatically equals `τ₁` off `{χ, χ̄}` (the Gram–Schmidt residual
`φ⊥ = φ − ⟨φ,χ⟩χ − ⟨φ,χ̄⟩χ̄` lands in `{χ, χ̄}^⊥`, so the hypothesis applies to it). -/

namespace IntegralCharacterMap

open OddOrder.RepresentationTheory

variable [Fintype L] [Invertible (Nat.card L : ℂ)]

/-- The integral-linear functional `φ ↦ ⟨φ, η⟩` (linear in the **first** argument). -/
noncomputable def innerLeftℤ (η : ClassFunction L ℂ) : ClassFunction L ℂ →ₗ[ℤ] ℂ where
  toFun φ := ClassFunction.inner φ η
  map_add' a b := ClassFunction.inner_add_left a b η
  map_smul' n a := by
    simp only [RingHom.id_apply, zsmul_eq_mul]
    rw [← Int.cast_smul_eq_zsmul ℂ n a, ClassFunction.inner_smul_left]

@[simp] theorem innerLeftℤ_apply (η φ : ClassFunction L ℂ) :
    innerLeftℤ (L := L) η φ = ClassFunction.inner φ η := rfl

/-- The Gram–Schmidt residual `φ⊥ = φ − ⟨φ,χ⟩χ − ⟨φ,χ̄⟩χ̄` against `{χ, χ̄}`, as a `ℤ`-linear
endomorphism of `ClassFunction L ℂ`.  This is `ℂ`-linear (the inner product is `ℂ`-linear in
its first argument), and in particular `ℤ`-linear, so it composes with the `ℤ`-linear `τ₁`. -/
noncomputable def orthoResidualMap (χ chibar : ClassFunction L ℂ) :
    ClassFunction L ℂ →ₗ[ℤ] ClassFunction L ℂ :=
  LinearMap.id - (innerLeftℤ (L := L) χ).smulRight χ
    - (innerLeftℤ (L := L) chibar).smulRight chibar

@[simp] theorem orthoResidualMap_apply (χ chibar φ : ClassFunction L ℂ) :
    orthoResidualMap (L := L) χ chibar φ =
      φ - ClassFunction.inner φ χ • χ - ClassFunction.inner φ chibar • chibar := by
  simp [orthoResidualMap, LinearMap.smulRight_apply]

/-- The residual `φ⊥` is orthogonal to `χ` (using orthonormality of `{χ, χ̄}`). -/
theorem inner_orthoResidualMap_left {χ chibar : ClassFunction L ℂ}
    (hχχ : ClassFunction.inner χ χ = 1) (hχbarχ : ClassFunction.inner chibar χ = 0)
    (φ : ClassFunction L ℂ) :
    ClassFunction.inner (orthoResidualMap (L := L) χ chibar φ) χ = 0 := by
  rw [orthoResidualMap_apply, ClassFunction.inner_sub_left, ClassFunction.inner_sub_left,
    ClassFunction.inner_smul_left, ClassFunction.inner_smul_left, hχχ, hχbarχ,
    mul_one, mul_zero, sub_zero, sub_self]

/-- The residual `φ⊥` is orthogonal to `χ̄` (using orthonormality of `{χ, χ̄}`). -/
theorem inner_orthoResidualMap_right {χ chibar : ClassFunction L ℂ}
    (hχχbar : ClassFunction.inner χ chibar = 0) (hχbarχbar : ClassFunction.inner chibar chibar = 1)
    (φ : ClassFunction L ℂ) :
    ClassFunction.inner (orthoResidualMap (L := L) χ chibar φ) chibar = 0 := by
  rw [orthoResidualMap_apply, ClassFunction.inner_sub_left, ClassFunction.inner_sub_left,
    ClassFunction.inner_smul_left, ClassFunction.inner_smul_left, hχχbar, hχbarχbar,
    mul_one, mul_zero, sub_zero, sub_self]

/-- The rank-`2` **re-targeting** of an integral isometry `τ₁`:
`φ ↦ τ₁ φ⊥ + ⟨φ,χ⟩·X + ⟨φ,χ̄⟩·X̄`, where `φ⊥ = φ − ⟨φ,χ⟩χ − ⟨φ,χ̄⟩χ̄` is the Gram–Schmidt
residual.  For an orthonormal pair `{χ, χ̄}` this sends `χ ↦ X`, `χ̄ ↦ X̄`, and keeps `τ₁`
on the orthogonal complement `{χ, χ̄}^⊥` (where `φ⊥ = φ`).

Concretely, `τ₂ = τ₁ ∘ φ⊥ + ⟨·,χ⟩·X + ⟨·,χ̄⟩·X̄`, a genuine `ℤ`-linear map (the projection is
`ℂ`-linear, hence `ℤ`-linear; the inner-product functionals are `ℤ`-linear).  Note `τ₁` is *not*
applied to the complex Fourier coefficients, so the construction is correct even though `τ₁` is
only `ℤ`-linear. -/
noncomputable def retarget (τ₁ : IntegralCharacterMap L G)
    (χ chibar : ClassFunction L ℂ) (X Xbar : ClassFunction G ℂ) :
    IntegralCharacterMap L G :=
  τ₁ ∘ₗ orthoResidualMap (L := L) χ chibar
    + (innerLeftℤ (L := L) χ).smulRight X
    + (innerLeftℤ (L := L) chibar).smulRight Xbar

@[simp] theorem retarget_apply (τ₁ : IntegralCharacterMap L G)
    (χ chibar : ClassFunction L ℂ) (X Xbar : ClassFunction G ℂ) (φ : ClassFunction L ℂ) :
    retarget τ₁ χ chibar X Xbar φ =
      τ₁ (orthoResidualMap (L := L) χ chibar φ)
        + ClassFunction.inner φ χ • X + ClassFunction.inner φ chibar • Xbar := by
  simp [retarget, LinearMap.smulRight_apply]

variable {τ₁ : IntegralCharacterMap L G} {χ chibar : ClassFunction L ℂ}
  {X Xbar : ClassFunction G ℂ}

/-- On the orthogonal complement of `{χ, χ̄}` the re-targeting agrees with `τ₁`. -/
theorem retarget_eq_of_orthogonal {φ : ClassFunction L ℂ}
    (hφχ : ClassFunction.inner φ χ = 0) (hφχbar : ClassFunction.inner φ chibar = 0) :
    retarget τ₁ χ chibar X Xbar φ = τ₁ φ := by
  rw [retarget_apply, hφχ, hφχbar, zero_smul, zero_smul, add_zero, add_zero,
    orthoResidualMap_apply, hφχ, hφχbar, zero_smul, zero_smul, sub_zero, sub_zero]

/-- `χ ↦ X` for an orthonormal pair `{χ, χ̄}`. -/
theorem retarget_apply_left
    (hχχ : ClassFunction.inner χ χ = 1) (hχχbar : ClassFunction.inner χ chibar = 0) :
    retarget τ₁ χ chibar X Xbar χ = X := by
  have hres : orthoResidualMap (L := L) χ chibar χ = 0 := by
    rw [orthoResidualMap_apply, hχχ, hχχbar, one_smul, zero_smul, sub_zero, sub_self]
  rw [retarget_apply, hres, map_zero, hχχ, hχχbar, one_smul, zero_smul, add_zero, zero_add]

/-- `χ̄ ↦ X̄` for an orthonormal pair `{χ, χ̄}`. -/
theorem retarget_apply_right
    (hχbarχ : ClassFunction.inner chibar χ = 0)
    (hχbarχbar : ClassFunction.inner chibar chibar = 1) :
    retarget τ₁ χ chibar X Xbar chibar = Xbar := by
  have hres : orthoResidualMap (L := L) χ chibar chibar = 0 := by
    rw [orthoResidualMap_apply, hχbarχ, hχbarχbar, one_smul, zero_smul, sub_zero, sub_self]
  rw [retarget_apply, hres, map_zero, hχbarχ, hχbarχbar, one_smul, zero_smul, add_zero, zero_add]

/-- **Block expansion of a sesquilinear inner product against an orthonormal pair.**
For `u, u' ∈ W` with `⟨e,e⟩ = ⟨f,f⟩ = 1`, `⟨e,f⟩ = ⟨f,e⟩ = 0`, and `u, u'` each orthogonal
to `e` and `f`, the inner product of `u + s·e + t·f` and `u' + s'·e + t'·f` collapses to
`⟨u,u'⟩ + s·conj s' + t·conj t'`.  This is the common normal form both sides of the
re-targeting isometry reduce to. -/
theorem inner_block_expand {W : Type*} [Group W] [Fintype W] [Invertible (Nat.card W : ℂ)]
    {e f u u' : ClassFunction W ℂ} {s t s' t' : ℂ}
    (hee : ClassFunction.inner e e = 1) (hff : ClassFunction.inner f f = 1)
    (hef : ClassFunction.inner e f = 0) (hfe : ClassFunction.inner f e = 0)
    (hue : ClassFunction.inner u e = 0) (huf : ClassFunction.inner u f = 0)
    (hu'e : ClassFunction.inner u' e = 0) (hu'f : ClassFunction.inner u' f = 0) :
    ClassFunction.inner (u + s • e + t • f) (u' + s' • e + t' • f) =
      ClassFunction.inner u u' + s * star s' + t * star t' := by
  have heu' : ClassFunction.inner e u' = 0 := by
    rw [OddOrder.RepresentationTheory.inner_conj_symm, hu'e, star_zero]
  have hfu' : ClassFunction.inner f u' = 0 := by
    rw [OddOrder.RepresentationTheory.inner_conj_symm, hu'f, star_zero]
  simp only [ClassFunction.inner_add_left, ClassFunction.inner_add_right,
    ClassFunction.inner_smul_left, OddOrder.RepresentationTheory.inner_smul_right,
    hue, huf, heu', hfu', hee, hff, hef, hfe]
  ring

/-- **The orthonormal-block isometry re-targeting keystone.**

Let `τ₁` be a *global* integral isometry, `{χ, χ̄}` an orthonormal pair in the source and
`{X, X̄}` an orthonormal pair in the target with the same gram matrix.  Suppose `X` and `X̄`
are each orthogonal to `τ₁ ξ` for **every** `ξ` orthogonal to both `χ` and `χ̄`.  Then the
re-targeted map `τ₂ = retarget τ₁ χ χ̄ X X̄` is again a global integral isometry.

This is the reusable form of Peterfalvi (5.6.3)'s `τ₂`: the orthogonality hypothesis is
exactly `(5.5) + (5.2.e)` (`X, X̄ ∈ ℤ[R(χ)]` and `S₁^{τ₁} ⊥ R(χ)`), and the conclusion is the
global isometry that, together with `retarget_apply_left`/`retarget_apply_right`/
`retarget_eq_of_orthogonal`, witnesses coherence of `S₁ ∪ {χ, χ̄}`. -/
theorem retarget_isIntegralIsometry [Fintype G] [Invertible (Nat.card G : ℂ)]
    (hτ₁ : IsIntegralIsometry (L := L) (G := G) τ₁)
    (hχχ : ClassFunction.inner χ χ = 1) (hχbarχbar : ClassFunction.inner chibar chibar = 1)
    (hχχbar : ClassFunction.inner χ chibar = 0) (hχbarχ : ClassFunction.inner chibar χ = 0)
    (hXX : ClassFunction.inner X X = 1) (hXbarXbar : ClassFunction.inner Xbar Xbar = 1)
    (hXXbar : ClassFunction.inner X Xbar = 0) (hXbarX : ClassFunction.inner Xbar X = 0)
    (hX_ortho : ∀ ξ : ClassFunction L ℂ, ClassFunction.inner ξ χ = 0 →
      ClassFunction.inner ξ chibar = 0 → ClassFunction.inner (τ₁ ξ) X = 0)
    (hXbar_ortho : ∀ ξ : ClassFunction L ℂ, ClassFunction.inner ξ χ = 0 →
      ClassFunction.inner ξ chibar = 0 → ClassFunction.inner (τ₁ ξ) Xbar = 0) :
    IsIntegralIsometry (L := L) (G := G) (retarget τ₁ χ chibar X Xbar) := by
  refine ⟨fun φ ψ => ?_⟩
  set s := ClassFunction.inner φ χ with hs
  set t := ClassFunction.inner φ chibar with ht
  set s' := ClassFunction.inner ψ χ with hs'
  set t' := ClassFunction.inner ψ chibar with ht'
  set φperp := orthoResidualMap (L := L) χ chibar φ with hφperp
  set ψperp := orthoResidualMap (L := L) χ chibar ψ with hψperp
  -- Orthogonality of the residuals to `{χ, χ̄}`.
  have hφperp_χ : ClassFunction.inner φperp χ = 0 :=
    inner_orthoResidualMap_left hχχ hχbarχ φ
  have hφperp_χbar : ClassFunction.inner φperp chibar = 0 :=
    inner_orthoResidualMap_right hχχbar hχbarχbar φ
  have hψperp_χ : ClassFunction.inner ψperp χ = 0 :=
    inner_orthoResidualMap_left hχχ hχbarχ ψ
  have hψperp_χbar : ClassFunction.inner ψperp chibar = 0 :=
    inner_orthoResidualMap_right hχχbar hχbarχbar ψ
  -- Image side: `⟨τ₂φ, τ₂ψ⟩ = ⟨τ₁φ⊥, τ₁ψ⊥⟩ + s·conj s' + t·conj t'`.
  have himg : ClassFunction.inner (retarget τ₁ χ chibar X Xbar φ)
      (retarget τ₁ χ chibar X Xbar ψ) =
      ClassFunction.inner (τ₁ φperp) (τ₁ ψperp) + s * star s' + t * star t' := by
    rw [retarget_apply, retarget_apply, ← hφperp, ← hψperp, ← hs, ← ht, ← hs', ← ht']
    exact inner_block_expand hXX hXbarXbar hXXbar hXbarX
      (hX_ortho φperp hφperp_χ hφperp_χbar) (hXbar_ortho φperp hφperp_χ hφperp_χbar)
      (hX_ortho ψperp hψperp_χ hψperp_χbar) (hXbar_ortho ψperp hψperp_χ hψperp_χbar)
  -- Source side: `⟨φ, ψ⟩ = ⟨φ⊥, ψ⊥⟩ + s·conj s' + t·conj t'`.
  have hsrc : ClassFunction.inner φ ψ =
      ClassFunction.inner φperp ψperp + s * star s' + t * star t' := by
    have hφ : φ = φperp + s • χ + t • chibar := by
      rw [hφperp, orthoResidualMap_apply, ← hs, ← ht]; abel
    have hψ : ψ = ψperp + s' • χ + t' • chibar := by
      rw [hψperp, orthoResidualMap_apply, ← hs', ← ht']; abel
    rw [hφ, hψ]
    exact inner_block_expand hχχ hχbarχbar hχχbar hχbarχ
      hφperp_χ hφperp_χbar hψperp_χ hψperp_χbar
  rw [himg, hsrc, hτ₁.inner_eq φperp ψperp]

/-! #### Agreement on the supported span

The `extends_on_supported` field of `IsCoherent` for the re-targeted map `τ₂` is discharged by
a `span_induction`: two integral character maps that agree on a generating set `T` agree on all of
`ℤ[T] = Submodule.span ℤ T` (`eq_on_zSpan_of_eq_on`).  For (5.6) the generating set is the three
*differences* `{χ - χ̄, χ - a·χ₁} ∪ Z[S₁, L^#]` — Peterfalvi's "which generate `Z[S₁∪S₂, L^#]`"
— and the `zSupportedSpan` is contained in their `ℤ`-span (the (5.1)-type generation input).  -/

omit [Fintype L] [Invertible (Nat.card L : ℂ)] in
/-- **Two integral character maps agreeing on a set agree on its integral span.**
If `f, g : IntegralCharacterMap L G` agree on every element of `T ⊆ ClassFunction L ℂ`, they
agree on all of `Submodule.span ℤ T`.  Pure `span_induction`; reused to discharge
`extends_on_supported`. -/
theorem eq_on_zSpan_of_eq_on {f g : IntegralCharacterMap L G}
    {T : Set (ClassFunction L ℂ)} (h : ∀ x ∈ T, f x = g x)
    {φ : ClassFunction L ℂ} (hφ : φ ∈ Submodule.span ℤ T) :
    f φ = g φ := by
  induction hφ using Submodule.span_induction with
  | mem x hx => exact h x hx
  | zero => simp
  | add x y _ _ ihx ihy => rw [map_add, map_add, ihx, ihy]
  | smul a x _ ih => rw [map_zsmul, map_zsmul, ih]

/-- A class function orthogonal to every element of `T` is orthogonal to all of `ℤ[T]`. -/
theorem inner_eq_zero_of_mem_zSpan {η : ClassFunction L ℂ}
    {T : Set (ClassFunction L ℂ)} (h : ∀ x ∈ T, ClassFunction.inner η x = 0)
    {φ : ClassFunction L ℂ} (hφ : φ ∈ Submodule.span ℤ T) :
    ClassFunction.inner η φ = 0 := by
  induction hφ using Submodule.span_induction with
  | mem x hx => exact h x hx
  | zero => exact ClassFunction.inner_zero_right η
  | add x y _ _ ihx ihy => rw [ClassFunction.inner_add_right, ihx, ihy, add_zero]
  | smul a x _ ih =>
      rw [← Int.cast_smul_eq_zsmul ℂ a x,
        OddOrder.RepresentationTheory.inner_smul_right, ih, mul_zero]

/-- **(5.5)+(5.2.e) orthogonality, sum form.**  If `X = ∑_{α ∈ R} c(α)·α` is an integer
combination of an indexed family and `η` is orthogonal to every `α ∈ R`, then `⟨η, X⟩ = 0`.

This packages the `hX_ortho`/`hXbar_ortho` hypotheses of `retarget_isCoherent` from the (5.5)
output `X ∈ ℤ[R(χ)]` (in the explicit `CharacterPsiDecomposition.X_eq` form `X = ∑ coeff α • α`)
and the per-element (5.2.e) orthogonality `⟨τ₁ ξ, α⟩ = 0` for `α ∈ R(χ)`. -/
theorem inner_eq_zero_of_eq_intCast_sum {W : Type*} [Group W] [Fintype W]
    [Invertible (Nat.card W : ℂ)] {η X : ClassFunction W ℂ}
    {R : Finset (ClassFunction W ℂ)} {c : ClassFunction W ℂ → ℤ}
    (hX : X = ∑ α ∈ R, (c α : ℂ) • α)
    (hη : ∀ α ∈ R, ClassFunction.inner η α = 0) :
    ClassFunction.inner η X = 0 := by
  rw [hX, OddOrder.RepresentationTheory.inner_sum_right]
  refine Finset.sum_eq_zero fun α hα => ?_
  rw [OddOrder.RepresentationTheory.inner_smul_right, hη α hα, mul_zero]

/-- On the integral span of a set orthogonal to `{χ, χ̄}`, the re-targeting agrees with `τ₁`. -/
theorem retarget_eq_on_zSpan_of_orthogonal {τ₁ : IntegralCharacterMap L G}
    {χ chibar : ClassFunction L ℂ} {X Xbar : ClassFunction G ℂ}
    {T : Set (ClassFunction L ℂ)}
    (hTχ : ∀ x ∈ T, ClassFunction.inner χ x = 0)
    (hTχbar : ∀ x ∈ T, ClassFunction.inner chibar x = 0)
    {φ : ClassFunction L ℂ} (hφ : φ ∈ Submodule.span ℤ T) :
    retarget τ₁ χ chibar X Xbar φ = τ₁ φ := by
  refine retarget_eq_of_orthogonal ?_ ?_
  · rw [OddOrder.RepresentationTheory.inner_conj_symm,
      inner_eq_zero_of_mem_zSpan hTχ hφ, star_zero]
  · rw [OddOrder.RepresentationTheory.inner_conj_symm,
      inner_eq_zero_of_mem_zSpan hTχbar hφ, star_zero]

end IntegralCharacterMap

/-! ### Peterfalvi (5.6.3): the coherence-union extension `τ₂`

The keystone `IntegralCharacterMap.retarget_isIntegralIsometry` builds the global isometry `τ₂`;
this section assembles it into the actual `IsCoherent (S₁ ∪ {χ, χ̄}) A` witness.  The data threaded
in are the honest outputs of (5.4)/(5.5)/(5.6.2): the coherent `τ₁` (= `hS₁.extension`), the
orthonormal pairs `{χ, χ̄}`, `{X, X̄}` (with `‖χ‖² = ‖χ̄‖² = 1` for irreducibles, hence
`‖X‖² = ‖X̄‖² = 1`), the conjugate-image definition `X̄ = X − (χ − χ̄)^τ`, the (5.5)+(5.2.e)
orthogonality `X, X̄ ⊥ τ₁ ξ` for `ξ ⊥ {χ, χ̄}`, the (5.6.2) image equation `(χ − aχ₁)^τ = X − aχ₁^{τ₁}`,
and the (5.1)-type generation `Z[S₁∪S₂, L^#] ⊆ ℤ[Z[S₁,L^#] ∪ {χ−χ̄, χ−aχ₁}]`.  No hypothesis
assumes the extension itself: `τ₂` is *constructed* as `retarget τ₁ χ χ̄ X X̄`. -/

open IntegralCharacterMap in
/-- **Peterfalvi (5.6.3): coherence of `S₁ ∪ {χ, χ̄}`.**

Given a coherent `τ` on `S₁` (witness `hS₁`, with `τ₁ := hS₁.extension`), an orthonormal pair
`{χ, χ̄}` disjoint from and orthogonal to `S₁`, and the (5.4)/(5.5)/(5.6.2) target data `{X, X̄}`
— orthonormal in `ℤ[Irr G]`, with `X̄ = X − (χ − χ̄)^τ`, both orthogonal to `τ₁ ξ` for every `ξ`
orthogonal to `{χ, χ̄}` (the (5.5)+(5.2.e) input), and with the (5.6.2) image equation
`(χ − a·χ₁)^τ = X − a·χ₁^{τ₁}` — the union `S₁ ∪ {χ, χ̄}` is coherent.

The constructed extension is `τ₂ := retarget τ₁ χ χ̄ X X̄`: it is a global integral isometry by the
keystone `retarget_isIntegralIsometry`, sends `χ ↦ X`, `χ̄ ↦ X̄`, keeps `τ₁` off `{χ, χ̄}`, and
agrees with `τ` on the supported span — checked on the three difference generators
`{χ − χ̄, χ − a·χ₁} ∪ Z[S₁, L^#]` via `eq_on_zSpan_of_eq_on`, using the generation hypothesis
`hgen`.  The degree ratio `a : ℕ` (`χ(1) = a·χ₁(1)` from hypothesis (b) divisibility,
`exists_pos_natDegreeRatio_of_dvd`) enters as a *natural* scalar, so the difference `χ − a·χ₁`
is preserved by the `ℤ`-linear `τ₂`. -/
noncomputable def retarget_isCoherent
    {τ : IntegralCharacterMap L G} {S₁ : Set (ClassFunction L ℂ)} {A : Set L}
    [Fintype L] [Fintype G] [Invertible (Nat.card L : ℂ)] [Invertible (Nat.card G : ℂ)]
    (hS₁ : IsCoherent τ S₁ A)
    {χ chibar chi1 : ClassFunction L ℂ} {a : ℕ} {X Xbar : ClassFunction G ℂ}
    (hχχ : ClassFunction.inner χ χ = 1) (hχbarχbar : ClassFunction.inner chibar chibar = 1)
    (hχχbar : ClassFunction.inner χ chibar = 0) (hχbarχ : ClassFunction.inner chibar χ = 0)
    (hXX : ClassFunction.inner X X = 1) (hXbarXbar : ClassFunction.inner Xbar Xbar = 1)
    (hXXbar : ClassFunction.inner X Xbar = 0) (hXbarX : ClassFunction.inner Xbar X = 0)
    (hX_ortho : ∀ ξ : ClassFunction L ℂ, ClassFunction.inner ξ χ = 0 →
      ClassFunction.inner ξ chibar = 0 → ClassFunction.inner (hS₁.extension ξ) X = 0)
    (hXbar_ortho : ∀ ξ : ClassFunction L ℂ, ClassFunction.inner ξ χ = 0 →
      ClassFunction.inner ξ chibar = 0 → ClassFunction.inner (hS₁.extension ξ) Xbar = 0)
    (hXbar_def : Xbar = X - τ (χ - chibar))
    (hχ_S1 : ∀ x ∈ S₁, ClassFunction.inner χ x = 0)
    (hχbar_S1 : ∀ x ∈ S₁, ClassFunction.inner chibar x = 0)
    (hchi1 : chi1 ∈ S₁)
    (himg : τ (χ - a • chi1) = X - a • hS₁.extension chi1)
    (hgen : zSupportedSpan (L := L) (S₁ ∪ {χ, chibar}) A ⊆
      Submodule.span ℤ (zSupportedSpan (L := L) S₁ A ∪ {χ - chibar, χ - a • chi1})) :
    IsCoherent τ (S₁ ∪ {χ, chibar}) A := by
  classical
  set τ₁ := hS₁.extension with hτ₁def
  set τ₂ := retarget τ₁ χ chibar X Xbar with hτ₂def
  -- χ, χ̄ are orthogonal to all of ℤ[S₁].
  have hχ_zspan : ∀ φ : ClassFunction L ℂ, φ ∈ Submodule.span ℤ S₁ →
      ClassFunction.inner χ φ = 0 := fun φ hφ =>
    IntegralCharacterMap.inner_eq_zero_of_mem_zSpan hχ_S1 hφ
  have hχbar_zspan : ∀ φ : ClassFunction L ℂ, φ ∈ Submodule.span ℤ S₁ →
      ClassFunction.inner chibar φ = 0 := fun φ hφ =>
    IntegralCharacterMap.inner_eq_zero_of_mem_zSpan hχbar_S1 hφ
  -- (1) τ₂ is a global integral isometry (the keystone).
  have hτ₂_isom : IsIntegralIsometry (L := L) (G := G) τ₂ :=
    retarget_isIntegralIsometry hS₁.extension_isometry hχχ hχbarχbar hχχbar hχbarχ
      hXX hXbarXbar hXXbar hXbarX hX_ortho hXbar_ortho
  -- (2) Agreement of τ₂ with τ on the three difference generators.
  -- (2a) On χ - χ̄: τ₂(χ-χ̄) = X - X̄ = X - (X - τ(χ-χ̄)) = τ(χ-χ̄).
  have hagree_diff : τ₂ (χ - chibar) = τ (χ - chibar) := by
    rw [hτ₂def, map_sub, retarget_apply_left hχχ hχχbar, retarget_apply_right hχbarχ hχbarχbar,
      hXbar_def]; abel
  -- (2b) On χ - a·χ₁: τ₂(χ - a•χ₁) = X - a•τ₁χ₁ = τ(χ - a•χ₁).
  have hagree_ratio : τ₂ (χ - a • chi1) = τ (χ - a • chi1) := by
    have hχ₁ : τ₂ chi1 = τ₁ chi1 :=
      retarget_eq_of_orthogonal
        (by rw [OddOrder.RepresentationTheory.inner_conj_symm, hχ_S1 chi1 hchi1, star_zero])
        (by rw [OddOrder.RepresentationTheory.inner_conj_symm, hχbar_S1 chi1 hchi1, star_zero])
    rw [hτ₂def, map_sub, map_nsmul, retarget_apply_left hχχ hχχbar, ← hτ₂def, hχ₁,
      himg, hτ₁def]
  -- (2c) On Z[S₁, L^#]: τ₂ φ = τ₁ φ = τ φ.
  have hagree_S1 : ∀ x ∈ zSupportedSpan (L := L) S₁ A, τ₂ x = τ x := by
    intro x hx
    have hxspan : x ∈ Submodule.span ℤ S₁ := hx.1
    have hτ₂x : τ₂ x = τ₁ x := by
      rw [hτ₂def]
      exact retarget_eq_of_orthogonal
        (by rw [OddOrder.RepresentationTheory.inner_conj_symm, hχ_zspan x hxspan, star_zero])
        (by rw [OddOrder.RepresentationTheory.inner_conj_symm, hχbar_zspan x hxspan, star_zero])
    rw [hτ₂x, hτ₁def, hS₁.extends_on_supported x hx]
  -- (3) τ₂ = τ on the generating set T, hence on its span (eq_on_zSpan_of_eq_on).
  have hagree_T : ∀ y ∈ zSupportedSpan (L := L) S₁ A ∪ {χ - chibar, χ - a • chi1},
      τ₂ y = τ y := by
    intro y hy
    rcases hy with hyS1 | hypair
    · exact hagree_S1 y hyS1
    · rcases hypair with hy1 | hy2
      · rw [hy1]; exact hagree_diff
      · rw [hy2]; exact hagree_ratio
  -- (4) Assemble the IsCoherent witness.
  refine ⟨?_, τ₂, hτ₂_isom, ?_⟩
  · -- nonzero: inherited from S₁ ⊆ S₁ ∪ {χ, χ̄}.
    obtain ⟨φ, hφmem, hφne⟩ := hS₁.nonzero
    exact ⟨φ, zSupportedSpan_mono_left (Set.subset_union_left) hφmem, hφne⟩
  · -- extends_on_supported via span generation + generator agreement.
    intro φ hφ
    exact IntegralCharacterMap.eq_on_zSpan_of_eq_on hagree_T (hgen hφ)

/-! ### Peterfalvi (5.6.1): the family bundle

The (5.6) coherence-union argument carries a whole **family** `{χᵢ}_{i ∈ s} ⊆ S₁` with `χ₁` a
distinguished member, integer degree ratios `aᵢ` (`χᵢ(1) = aᵢ·χ₁(1)`, `a₁ = 1`), squared norms
`mᵢ = ‖χᵢ‖²`, and the auxiliary isometry `τ₁` on `ℤ[S₁]` extending `τ`.  The single non-trivial
fact threaded through (5.6.1)→(5.6.2) is the **cross-difference orthogonality**

`⟨(χ − a·χ₁), (χᵢ − aᵢ·χ₁)⟩ = a·aᵢ·‖χ₁‖²`  (for `i ≠ 1`),

derived from `χ ⊥ S₁` and pairwise orthogonality of `S₁`.  The bundle records the family data and
*derives* this identity (it is not posited): `crossDifference_inner` below. -/

open OddOrder.RepresentationTheory in
/-- **Peterfalvi (5.6.1) family bundle.**

Bundles the family `{χᵢ}_{i ∈ s} ⊆ S₁` (with distinguished `χ₁ = chiFam i₁`), the integer degree
ratios `ratio i = aᵢ` (`χᵢ(1) = aᵢ·χ₁(1)`, `ratio i₁ = 1`), the squared norms `normSq i = ‖χᵢ‖²`,
and the orthogonality data threaded through (5.6.1): `χ` is orthogonal to every `χᵢ` and to every
`χ̄ᵢ`, and `{χᵢ}` is pairwise orthogonal.  These are exactly the `(5.2)`-level inputs; the bundle
*derives* the cross-difference orthogonality `crossDifference_inner` rather than assuming it.

This carries no extension witness for the union `S₁ ∪ {χ, χ̄}`; it is pure source-side family data
(the `degree`, `norm` and `orthogonality` hypotheses of (5.6)), constructed from `(5.2)`. -/
structure CharacterFamilyBundle
    (chi chi1 : ClassFunction L ℂ) (a : ℝ)
    {ι : Type*} (s : Finset ι) (i₁ : ι)
    [Fintype L] [Invertible (Nat.card L : ℂ)] where
  /-- The distinguished index `i₁` lies in the family. -/
  i₁_mem : i₁ ∈ s
  /-- The characters of the family `S₁`. -/
  chiFam : ι → ClassFunction L ℂ
  /-- `χ₁ = chiFam i₁`. -/
  chi1_eq : chiFam i₁ = chi1
  /-- The integer degree ratios `aᵢ`. -/
  ratio : ι → ℕ
  /-- `a₁ = 1`. -/
  ratio_one : ratio i₁ = 1
  /-- The degree scaling `χᵢ(1) = aᵢ·χ₁(1)`, recorded via `characterDegree`. -/
  degree_eq : ∀ i ∈ s, OddOrder.Peterfalvi.S03.characterDegree (chiFam i) =
    (ratio i : ℂ) * OddOrder.Peterfalvi.S03.characterDegree chi1
  /-- The complex degree ratio `a = χ(1)/χ₁(1)`. -/
  degree_chi : OddOrder.Peterfalvi.S03.characterDegree chi =
    (a : ℂ) * OddOrder.Peterfalvi.S03.characterDegree chi1
  /-- `χ` is orthogonal to every family member. -/
  chi_orthogonal : ∀ i ∈ s, ClassFunction.inner chi (chiFam i) = 0
  /-- `{χᵢ}` is pairwise orthogonal. -/
  chiFam_pairwise : ∀ i ∈ s, ∀ j ∈ s, i ≠ j →
    ClassFunction.inner (chiFam i) (chiFam j) = 0

namespace CharacterFamilyBundle

open OddOrder.RepresentationTheory

variable {chi chi1 : ClassFunction L ℂ} {a : ℝ}
variable {ι : Type*} {s : Finset ι} {i₁ : ι}
variable [Fintype L] [Invertible (Nat.card L : ℂ)]

/-- `‖χ₁‖²` written through the bundle. -/
abbrev normSq1 (_B : CharacterFamilyBundle (L := L) chi chi1 a s i₁) : ℂ :=
  ClassFunction.inner chi1 chi1

/-- **Peterfalvi (5.6.1) cross-difference orthogonality (source side).**

For `i ∈ s` with `i ≠ i₁`, the inner product of the differences `χ − a·χ₁` and
`χᵢ − aᵢ·χ₁` equals `a·aᵢ·‖χ₁‖²`.

`⟨χ − aχ₁, χᵢ − aᵢχ₁⟩ = ⟨χ,χᵢ⟩ − aᵢ⟨χ,χ₁⟩ − a⟨χ₁,χᵢ⟩ + a·aᵢ⟨χ₁,χ₁⟩`.  The first three
inner products vanish: `⟨χ,χᵢ⟩ = ⟨χ,χ₁⟩ = 0` since `χ ⊥ S₁`, and `⟨χ₁,χᵢ⟩ = 0` since `i ≠ i₁`
and `{χᵢ}` is pairwise orthogonal.  Only `a·aᵢ·‖χ₁‖²` survives. -/
theorem crossDifference_inner (B : CharacterFamilyBundle (L := L) chi chi1 a s i₁)
    {i : ι} (hi : i ∈ s) (hii₁ : i ≠ i₁) :
    ClassFunction.inner (chi - (a : ℂ) • chi1)
        (B.chiFam i - (B.ratio i : ℂ) • chi1) =
      (a : ℂ) * (B.ratio i : ℂ) * ClassFunction.inner chi1 chi1 := by
  have hchi_i : ClassFunction.inner chi (B.chiFam i) = 0 := B.chi_orthogonal i hi
  have hchi_1 : ClassFunction.inner chi chi1 = 0 := by
    have := B.chi_orthogonal i₁ B.i₁_mem; rwa [B.chi1_eq] at this
  have h1_i : ClassFunction.inner chi1 (B.chiFam i) = 0 := by
    have := B.chiFam_pairwise i₁ B.i₁_mem i hi (fun h => hii₁ h.symm)
    rwa [B.chi1_eq] at this
  rw [ClassFunction.inner_sub_left, ClassFunction.inner_sub_right,
    ClassFunction.inner_sub_right, ClassFunction.inner_smul_left,
    OddOrder.RepresentationTheory.inner_smul_right,
    OddOrder.RepresentationTheory.inner_smul_right, ClassFunction.inner_smul_left,
    hchi_i, hchi_1, h1_i]
  rw [star_natCast]
  ring

end CharacterFamilyBundle

end OddOrder.Peterfalvi.S07
