/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.Algebra.Module.Submodule.LinearMap
import OddOrder.Peterfalvi.S06_DadeIsometryCertain

/-!
# Peterfalvi §7: Coherence

T. Peterfalvi, *Character Theory for the Odd Order Theorem* (LMS LNS 272, 2000),
§7, pp. 25-29.

This file defines the first Lean interface for Peterfalvi coherence.  Following
the audit note, (5.1) is encoded as an extension property only: the
"character-difference" conclusion belongs to (5.9), and the difference used in
§7 is `chi - conj chi`.

Reference note: `notes/peterfalvi/s07_coherence.md`.
-/

namespace OddOrder.Peterfalvi.S07

open OddOrder.RepresentationTheory

variable {L G : Type*} [Group L] [Group G]

/- 5: Coherence (pp. 25-29) -/

/-- The integral span generated by a set of class functions. -/
def zSpan (S : Set (ClassFunction L ℂ)) : Submodule ℤ (ClassFunction L ℂ) :=
  Submodule.span ℤ S

/-- The part of `Z[S]` supported on `A`.

This is kept as a predicate-shaped set for now, because the `CF(L,A)` complex
submodule and the integral lattice `Z[S]` live over different scalar rings. -/
def zSupportedSpan (S : Set (ClassFunction L ℂ)) (A : Set L) :
    Set (ClassFunction L ℂ) :=
  {φ | φ ∈ zSpan (L := L) S ∧ φ.support ⊆ A}

/-- An integral linear map between virtual-character lattices, represented at
the class-function level. -/
abbrev IntegralCharacterMap (L G : Type*) [Group L] [Group G] :=
  ClassFunction L ℂ →ₗ[ℤ] ClassFunction G ℂ

/-- The normalized inner-product part of an integral isometry. -/
structure IsIntegralIsometry (τ : IntegralCharacterMap L G)
    [Fintype L] [Fintype G]
    [Invertible (Nat.card L : ℂ)] [Invertible (Nat.card G : ℂ)] : Prop where
  inner_eq :
    ∀ φ ψ : ClassFunction L ℂ,
      ClassFunction.inner (τ φ) (τ ψ) = ClassFunction.inner φ ψ

/-- The Peterfalvi (5.2.d) image data for one character difference.

For `χ ∈ S`, later applications prove that the image of `χ - χ̄` under the
integral isometry is a signed difference of two irreducible characters of `G`.
The hard existence theorem is supplied by
`OddOrder.RepresentationTheory.isometry_difference_pair_structure`; this
structure records the reusable conclusion in the coherence interface. -/
structure CharacterDifferenceImage (τ : IntegralCharacterMap L G)
    (χ : ClassFunction L ℂ) where
  mu : IrreducibleCharacter G
  nu : IrreducibleCharacter G
  distinct : mu ≠ nu
  sign : ℤ
  sign_eq : sign = 1 ∨ sign = -1
  image_eq :
    τ (χ - χ.conj) =
      sign • ((mu : ClassFunction G ℂ) - (nu : ClassFunction G ℂ))

namespace CharacterDifferenceImage

variable {τ : IntegralCharacterMap L G} {χ : ClassFunction L ℂ}

/-- The first irreducible character appearing in the signed image, as a class
function. -/
abbrev muClassFunction (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    ClassFunction G ℂ :=
  hχ.mu

/-- The second irreducible character appearing in the signed image, as a class
function. -/
abbrev nuClassFunction (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    ClassFunction G ℂ :=
  hχ.nu

@[simp] theorem mu_irreducible
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    IsIrreducibleCharacter hχ.muClassFunction :=
  hχ.mu.isIrreducible

@[simp] theorem nu_irreducible
    (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    IsIrreducibleCharacter hχ.nuClassFunction :=
  hχ.nu.isIrreducible

/-- Restatement using the named §3/§7 helper for the expression `χ - χ̄`. -/
theorem image_conjugateDifference (hχ : CharacterDifferenceImage (L := L) (G := G) τ χ) :
    τ (OddOrder.Peterfalvi.S03.conjugateDifference χ) =
      hχ.sign • (hχ.muClassFunction - hχ.nuClassFunction) := by
  simpa [OddOrder.Peterfalvi.S03.conjugateDifference] using hχ.image_eq

end CharacterDifferenceImage

/-- Peterfalvi (5.1): `τ` is coherent for `(S,A)` if it admits an integral
isometric extension on `Z[S]` that agrees with `τ` on `Z[S,A]`. -/
structure IsCoherent (τ : IntegralCharacterMap L G)
    (S : Set (ClassFunction L ℂ)) (A : Set L)
    [Fintype L] [Fintype G]
    [Invertible (Nat.card L : ℂ)] [Invertible (Nat.card G : ℂ)] where
  nonzero : ∃ φ : ClassFunction L ℂ, φ ∈ zSupportedSpan (L := L) S A
  extension : IntegralCharacterMap L G
  extension_isometry : IsIntegralIsometry (L := L) (G := G) extension
  extends_on_supported :
    ∀ φ : ClassFunction L ℂ, φ ∈ zSupportedSpan (L := L) S A → extension φ = τ φ

namespace IsCoherent

variable {τ : IntegralCharacterMap L G} {S : Set (ClassFunction L ℂ)} {A : Set L}
variable [Fintype L] [Fintype G]
variable [Invertible (Nat.card L : ℂ)] [Invertible (Nat.card G : ℂ)]

theorem extension_agrees (hτ : IsCoherent τ S A)
    {φ : ClassFunction L ℂ} (hφ : φ ∈ zSupportedSpan (L := L) S A) :
    hτ.extension φ = τ φ :=
  hτ.extends_on_supported φ hφ

end IsCoherent

/-- Peterfalvi (5.2)-style hypotheses for coherence applications.  This is a
carrier for later theorems, not a proof that the hypotheses hold in any
particular Dade situation. -/
structure Hypothesis (S : Set (ClassFunction L ℂ)) (A : Set L)
    [Fintype L] [Fintype G]
    [Invertible (Nat.card L : ℂ)] [Invertible (Nat.card G : ℂ)] where
  tau : IntegralCharacterMap L G
  tau_isometry : IsIntegralIsometry (L := L) (G := G) tau
  conjugate_closed : OddOrder.Peterfalvi.S03.ClosedUnderConjugate S
  no_real_characters : OddOrder.Peterfalvi.S03.HasNoRealCharacters S
  pairwise_orthogonal : OddOrder.Peterfalvi.S03.PairwiseOrthogonal S
  difference_image :
    ∀ ⦃χ : ClassFunction L ℂ⦄, χ ∈ S → CharacterDifferenceImage (L := L) (G := G) tau χ

namespace Hypothesis

variable {S : Set (ClassFunction L ℂ)} {A : Set L}
variable [Fintype L] [Fintype G]
variable [Invertible (Nat.card L : ℂ)] [Invertible (Nat.card G : ℂ)]

/-- The map carried by a §7 hypothesis, as a coherence predicate target. -/
abbrev IsCoherentTarget (hyp : Hypothesis (L := L) (G := G) S A) :=
  IsCoherent hyp.tau S A

/-- The signed irreducible-difference image of `χ - χ̄` supplied by a §7
hypothesis. -/
theorem difference_image_eq {hyp : Hypothesis (L := L) (G := G) S A}
    {χ : ClassFunction L ℂ} (hχ : χ ∈ S) :
    hyp.tau (OddOrder.Peterfalvi.S03.conjugateDifference χ) =
      (hyp.difference_image hχ).sign •
        ((hyp.difference_image hχ).muClassFunction -
          (hyp.difference_image hχ).nuClassFunction) :=
  (hyp.difference_image hχ).image_conjugateDifference

theorem conjugate_mem {hyp : Hypothesis (L := L) (G := G) S A}
    {χ : ClassFunction L ℂ} (hχ : χ ∈ S) :
    χ.conj ∈ S :=
  hyp.conjugate_closed hχ

theorem not_isReal {hyp : Hypothesis (L := L) (G := G) S A}
    {χ : ClassFunction L ℂ} (hχ : χ ∈ S) :
    ¬ χ.IsReal :=
  hyp.no_real_characters hχ

theorem ne_conj {hyp : Hypothesis (L := L) (G := G) S A}
    {χ : ClassFunction L ℂ} (hχ : χ ∈ S) :
    χ ≠ χ.conj := by
  intro hχ_eq
  exact hyp.not_isReal hχ hχ_eq.symm

theorem conjugateDifference_ne_zero {hyp : Hypothesis (L := L) (G := G) S A}
    {χ : ClassFunction L ℂ} (hχ : χ ∈ S) :
    OddOrder.Peterfalvi.S03.conjugateDifference χ ≠ 0 :=
  (OddOrder.Peterfalvi.S03.conjugateDifference_ne_zero_iff_not_isReal χ).mpr
    (hyp.not_isReal hχ)

end Hypothesis

end OddOrder.Peterfalvi.S07
