/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.BG.AppC_Problem1Lattice

/-!
# BG Appendix C, Problem 1: the trace obstruction

`OddOrder.BG.AppC.Problem1.false_of_collisionSet_spanning` refutes hypothesis (B) once the
`S`-values of *all* collisions span `𝔽_{3^q}` over the prime field.  This file replaces that
spanning hypothesis by a **single collision**:

> if one collision has `Tr(S) ≠ 0`, hypothesis (B) has no witness.

The mechanism is that the collision data is *Frobenius-equivariant*.  A collision is a pair
`p, r` of elements of the Paley set with `p^E - (p-1)^E = r^E - (r-1)^E`; in characteristic three
`p ↦ p³` is a ring endomorphism and `p³ - 1 = (p-1)³`, so cubing a collision is again a collision
and its `S`-value is cubed:

`S(p³, r³) = S(p, r)³`.

Relation (4) of `notes/bg/appC_problem1_partial_resolution.md` says `b(S)^{a(-1)} = b(S')`, i.e.
`x · b(S) · x⁻¹ = b(S')`.  Applying it to the `q` Frobenius conjugates of one collision and
multiplying the resulting relations inside the abelian second layer gives

`x · b(Tr S) · x⁻¹ = b(Tr S')`,     `Tr S = ∑_{j<q} S^{3^j}`.

Both traces lie in the prime field `𝔽₃`, so `b(Tr S)` and `b(Tr S')` lie in the group of order
three generated by `w = b(1) = x^g`.  Conjugation by `x` therefore acts on `⟨w⟩ ≅ C₃` through
`Aut(C₃) ≅ C₂`, and `x³ = 1`, so it acts trivially: `x` centralises `x^g`.  That is exactly the
configuration refuted by `not_commute_conj` (Theorem 1's endgame).

Compared with `false_of_collisionSet_spanning` the criterion here is strictly weaker in its
hypotheses — one collision instead of a spanning family — and it does not need the exponent to be
non-Frobenius (`hnotfrob`), because the contradiction no longer runs through the perfectness of
`N`.  It is the criterion verified computationally in `notes/meta/gap/verify_trace_obstruction.g`.

## Main results

* `CollisionPair` — the collision data of relation (4), keeping *both* `S` and `S'`.
* `CollisionPair.frobenius` — cubing a collision cubes its `S`-values.
* `conj_layerFieldHom_one_eq` — relation (4) as an equation.
* `fieldTrace_pow_char` — `Tr S` lies in the prime field.
* `false_of_collisionPair_trace_ne_zero` — **the trace obstruction**.
-/

namespace OddOrder.BG.AppC.Problem1

open Finset

section PrimeField

variable {p q : ℕ} [Fact p.Prime]

/-- The absolute trace `Tr_{𝔽_{p^q}/𝔽_p}(S) = ∑_{j<q} S^{p^j}`, written out as a sum of Frobenius
conjugates rather than through `Algebra.trace`.  Only two facts about it are used: it is additive
along the relation family (automatic, being a sum of power maps applied to one element) and it
lands in the prime field (`fieldTrace_pow_char`). -/
noncomputable def fieldTrace (p q : ℕ) [Fact p.Prime] (S : GaloisField p q) : GaloisField p q :=
  ∑ j ∈ Finset.range q, S ^ p ^ j

/-- The Frobenius has order `q` on `𝔽_{p^q}`. -/
theorem pow_card_pow (hq : q ≠ 0) (z : GaloisField p q) : z ^ p ^ q = z := by
  classical
  letI : Fintype (GaloisField p q) := Fintype.ofFinite _
  have hcard : Fintype.card (GaloisField p q) = p ^ q := by
    rw [← Nat.card_eq_fintype_card]
    exact GaloisField.card p q hq
  have := FiniteField.pow_card z
  rwa [hcard] at this

/-- **The trace lands in the prime field.**  `Tr(S)^p = Tr(S)`, because raising the sum
`∑_{j<q} S^{p^j}` to the `p`-th power shifts the summands cyclically (`S^{p^q} = S`). -/
theorem fieldTrace_pow_char (hq : q ≠ 0) (S : GaloisField p q) :
    fieldTrace p q S ^ p = fieldTrace p q S := by
  have hp0 : p ≠ 0 := (Fact.out : p.Prime).ne_zero
  have hfrob : ∀ (n : ℕ) (f : ℕ → GaloisField p q),
      (∑ j ∈ Finset.range n, f j) ^ p = ∑ j ∈ Finset.range n, f j ^ p := by
    intro n f
    induction n with
    | zero => simp [hp0]
    | succ k ih => rw [Finset.sum_range_succ, Finset.sum_range_succ, add_pow_char, ih]
  have hstep : ∀ j : ℕ, (S ^ p ^ j) ^ p = S ^ p ^ (j + 1) := by
    intro j
    rw [← pow_mul, ← pow_succ]
  simp only [fieldTrace, hfrob, hstep]
  have h1 : (∑ j ∈ Finset.range (q + 1), S ^ p ^ j)
      = (∑ j ∈ Finset.range q, S ^ p ^ (j + 1)) + S ^ p ^ 0 :=
    Finset.sum_range_succ' _ q
  have h2 : (∑ j ∈ Finset.range (q + 1), S ^ p ^ j)
      = (∑ j ∈ Finset.range q, S ^ p ^ j) + S ^ p ^ q :=
    Finset.sum_range_succ _ q
  have h3 : S ^ p ^ q = S ^ p ^ 0 := by
    rw [pow_zero, pow_one, pow_card_pow hq]
  rw [h3, h1] at h2
  exact add_right_cancel h2

/-- **The prime field of characteristic three has three elements.**  An element fixed by the
Frobenius is `0`, `1` or `-1`. -/
theorem eq_zero_or_one_or_neg_one_of_pow_char (hp : p = 3) {T : GaloisField p q}
    (hT : T ^ p = T) : T = 0 ∨ T = 1 ∨ T = -1 := by
  subst hp
  have hfac : T * ((T - 1) * (T + 1)) = 0 := by linear_combination hT
  rcases mul_eq_zero.mp hfac with h | h
  · exact Or.inl h
  rcases mul_eq_zero.mp h with h' | h'
  · exact Or.inr (Or.inl (sub_eq_zero.mp h'))
  · exact Or.inr (Or.inr (eq_neg_of_add_eq_zero_left h'))

end PrimeField

section Aut

variable {G : Type*} [Group G]

/-- **`Aut(C₃)` has no element of order three.**  If `x³ = 1` and conjugation by `x` inverts an
element `w` with `w³ = 1`, then `w = 1`.

Indeed conjugation by `x²` then fixes `w`, so conjugation by `x³ = 1` inverts it, i.e.
`w = w⁻¹`; combined with `w³ = 1` this gives `w = 1`. -/
theorem eq_one_of_conj_eq_inv {x w : G} (hx : x ^ 3 = 1) (hw : w ^ 3 = 1)
    (h : x * w * x⁻¹ = w⁻¹) : w = 1 := by
  have hx' : x * x * x = 1 := by rw [← hx, pow_succ, pow_succ, pow_one]
  have hcan : ∀ r : G, x * (x * (x * r)) = r := by
    intro r
    rw [← mul_assoc, ← mul_assoc, hx', one_mul]
  have hinvcube : x⁻¹ * (x⁻¹ * x⁻¹) = 1 := by
    rw [← mul_inv_rev, ← mul_inv_rev, hx', inv_one]
  have h2 : x * w⁻¹ * x⁻¹ = w := by
    have hcalc : x * w⁻¹ * x⁻¹ = (x * w * x⁻¹)⁻¹ := by
      simp only [mul_inv_rev, inv_inv, mul_assoc]
    rw [hcalc, h, inv_inv]
  -- conjugating three times is conjugating by `x³ = 1`
  have key : x * (x * (x * w * x⁻¹) * x⁻¹) * x⁻¹ = w := by
    have hassoc : x * (x * (x * w * x⁻¹) * x⁻¹) * x⁻¹
        = x * (x * (x * (w * (x⁻¹ * (x⁻¹ * x⁻¹))))) := by
      simp only [mul_assoc]
    rw [hassoc, hcan, hinvcube, mul_one]
  have h3 : w = w⁻¹ := by
    rw [h, h2, h] at key
    exact key.symm
  have hww : w * w = 1 := mul_eq_one_iff_eq_inv.mpr h3
  have hcube : w ^ 3 = w := by rw [pow_succ, pow_two, hww, one_mul]
  rw [hcube] at hw
  exact hw

end Aut

section GroupSide

variable {p q : ℕ} [Fact p.Prime] {G : Type*} [Group G]

/-! ### The collision data, keeping both endpoints

`collisionSet` records only the `S`-value that gets conjugated; the trace obstruction needs the
*pair* `(S, S')` of relation (4), because the Frobenius moves both. -/

/-- **A collision of the map `p ↦ p^E - (p-1)^E` on the Paley set, with square difference.**
`p₀ = p₁ + 1` and `r₀ = r₁ + 1` are the two Paley pairs, `d₀` is the (norm-one, i.e. square)
difference `δ = r₀^e - p₀^e`, and `S`, `S'` are the two normalised third-layer values.  Relation
(4) reads `x · b(S) · x⁻¹ = b(S')` (`conj_layerFieldHom_one_eq`). -/
def CollisionPair (p q e : ℕ) [Fact p.Prime] (S S' : GaloisField p q) : Prop :=
  ∃ p₀ p₁ r₀ r₁ d₀ : NormSet.normOneUnits p q,
    normOneVal p₀ = normOneVal p₁ + 1 ∧ normOneVal r₀ = normOneVal r₁ + 1 ∧
    normOneVal p₀ ^ e - normOneVal p₁ ^ e = normOneVal r₀ ^ e - normOneVal r₁ ^ e ∧
    normOneVal d₀ = normOneVal r₀ ^ e - normOneVal p₀ ^ e ∧
    S = (normOneVal p₁ ^ (e * e) - normOneVal p₀ ^ (e * e)) *
        normOneVal (d₀⁻¹ ^ (e * e)) ^ (e * e) ∧
    S' = (normOneVal r₁ ^ (e * e) - normOneVal r₀ ^ (e * e)) *
        normOneVal (d₀⁻¹ ^ (e * e)) ^ (e * e)

/-- `collisionSet` is the set of first components of collision pairs. -/
theorem mem_collisionSet_iff_exists_pair {e : ℕ} (S : GaloisField p q) :
    S ∈ collisionSet p q e ↔ ∃ S', CollisionPair p q e S S' := by
  constructor
  · rintro ⟨p₀, p₁, r₀, r₁, d₀, hpp, hrr, hcoll, hd, hS⟩
    exact ⟨_, p₀, p₁, r₀, r₁, d₀, hpp, hrr, hcoll, hd, hS, rfl⟩
  · rintro ⟨S', p₀, p₁, r₀, r₁, d₀, hpp, hrr, hcoll, hd, hS, -⟩
    exact ⟨p₀, p₁, r₀, r₁, d₀, hpp, hrr, hcoll, hd, hS⟩

/-- **The collision data is Frobenius-equivariant.**  In characteristic `p` the map `a ↦ a^p` is a
ring endomorphism fixing `1`, so it carries a Paley pair to a Paley pair, a collision to a
collision and the difference `δ` to `δ^p`; the two normalised values are raised to the `p`-th
power. -/
theorem CollisionPair.frobenius {e : ℕ} {S S' : GaloisField p q}
    (h : CollisionPair p q e S S') : CollisionPair p q e (S ^ p) (S' ^ p) := by
  obtain ⟨p₀, p₁, r₀, r₁, d₀, hpp, hrr, hcoll, hd, rfl, rfl⟩ := h
  have hswap : ∀ (a : GaloisField p q) (k : ℕ), (a ^ p) ^ k = (a ^ k) ^ p := by
    intro a k
    rw [← pow_mul, Nat.mul_comm, pow_mul]
  have hd0 : ((d₀ ^ p)⁻¹ : NormSet.normOneUnits p q) ^ (e * e) = (d₀⁻¹ ^ (e * e)) ^ p := by
    rw [← inv_pow, ← pow_mul, ← pow_mul, Nat.mul_comm p (e * e)]
  refine ⟨p₀ ^ p, p₁ ^ p, r₀ ^ p, r₁ ^ p, d₀ ^ p, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · simp only [normOneVal_pow]
    rw [hpp, add_pow_char, one_pow]
  · simp only [normOneVal_pow]
    rw [hrr, add_pow_char, one_pow]
  · simp only [normOneVal_pow, hswap, ← sub_pow_char, hcoll]
  · simp only [normOneVal_pow, hswap, ← sub_pow_char]
    rw [hd]
  · rw [hd0]
    simp only [normOneVal_pow, hswap, ← sub_pow_char, ← mul_pow]
  · rw [hd0]
    simp only [normOneVal_pow, hswap, ← sub_pow_char, ← mul_pow]

/-- Iterating `CollisionPair.frobenius`. -/
theorem CollisionPair.frobenius_iterate {e : ℕ} {S S' : GaloisField p q}
    (h : CollisionPair p q e S S') (j : ℕ) :
    CollisionPair p q e (S ^ p ^ j) (S' ^ p ^ j) := by
  induction j with
  | zero => simpa using h
  | succ k ih =>
      have hstep := ih.frobenius
      rwa [← pow_mul, ← pow_mul, ← pow_succ] at hstep

/-- **Relation (4) as an equation.**  For a collision with square difference, conjugation by
`x = σ(1)` carries the second-layer element `b(S)` to `b(S')`.

This is `layerFieldHom_one_conj` with the normalisation `δ z^e = 1`, which turns the two
first-layer factors into `a(1) = x` and `a(-1) = x⁻¹`. -/
theorem conj_layerFieldHom_one_eq (data : FieldNormalizerData p q G) (hp : p = 3) {e : ℕ}
    (hexp : ∀ w ∈ data.U, conjGen data * w = w ^ e * conjGen data)
    {S S' : GaloisField p q} (hpair : CollisionPair p q e S S') :
    data.s * layerFieldHom data 1 (Multiplicative.ofAdd S) * (data.s)⁻¹
      = layerFieldHom data 1 (Multiplicative.ofAdd S') := by
  obtain ⟨p₀, p₁, r₀, r₁, d₀, hpp, hrr, hcoll, hd, rfl, rfl⟩ := hpair
  set z : NormSet.normOneUnits p q := d₀⁻¹ ^ (e * e) with hz
  have hcube := normOneUnits_pow_cube data hp hexp d₀⁻¹
  have hze : normOneVal z ^ e = (normOneVal d₀)⁻¹ := by
    have hstep : normOneVal (z ^ e) = normOneVal (d₀⁻¹) := by
      rw [hz, ← pow_mul, hcube]
    rw [normOneVal_pow] at hstep
    rw [hstep, normOneVal_inv]
  have hone : (normOneVal r₀ ^ e - normOneVal p₀ ^ e) * normOneVal z ^ e = 1 := by
    rw [hze, ← hd]
    exact mul_inv_cancel₀ (Units.ne_zero _)
  have h3 := layerFieldHom_one_conj data hp hexp p₀ p₁ r₀ r₁ z hpp hrr hcoll
  rw [hone] at h3
  have ha1 : layerFieldHom data 0 (Multiplicative.ofAdd (1 : GaloisField p q)) = data.s := by
    simp only [layerFieldHom_apply, pow_zero, inv_one, one_mul, mul_one]
    rfl
  have ha2 : layerFieldHom data 0 (Multiplicative.ofAdd (-1 : GaloisField p q)) = (data.s)⁻¹ := by
    rw [← ha1, ← map_inv]
    rfl
  rw [ha1, ha2] at h3
  exact h3.symm

/-- **Relation (4), traced.**  Multiplying the `q` Frobenius conjugates of relation (4) inside the
abelian second layer replaces `S` and `S'` by their absolute traces. -/
theorem conj_layerFieldHom_one_trace (data : FieldNormalizerData p q G) (hp : p = 3) {e : ℕ}
    (hexp : ∀ w ∈ data.U, conjGen data * w = w ^ e * conjGen data)
    {S S' : GaloisField p q} (hpair : CollisionPair p q e S S') :
    data.s * layerFieldHom data 1 (Multiplicative.ofAdd (fieldTrace p q S)) * (data.s)⁻¹
      = layerFieldHom data 1 (Multiplicative.ofAdd (fieldTrace p q S')) := by
  have key : ∀ n : ℕ,
      data.s * layerFieldHom data 1
          (Multiplicative.ofAdd (∑ j ∈ Finset.range n, S ^ p ^ j)) * (data.s)⁻¹
        = layerFieldHom data 1
          (Multiplicative.ofAdd (∑ j ∈ Finset.range n, S' ^ p ^ j)) := by
    intro n
    induction n with
    | zero =>
        simp only [Finset.range_zero, Finset.sum_empty, ofAdd_zero, map_one, mul_one,
          mul_inv_cancel]
    | succ k ih =>
        rw [Finset.sum_range_succ, Finset.sum_range_succ, ofAdd_add, ofAdd_add, map_mul, map_mul]
        have hstep := conj_layerFieldHom_one_eq data hp hexp (hpair.frobenius_iterate k)
        have hsplit : ∀ a b : G, data.s * (a * b) * (data.s)⁻¹
            = (data.s * a * (data.s)⁻¹) * (data.s * b * (data.s)⁻¹) := by
          intro a b
          simp only [mul_assoc, inv_mul_cancel_left]
        rw [hsplit, ih, hstep]
  exact key q

/-- **The trace obstruction.**  A *single* collision whose `S`-value has non-zero absolute trace
already refutes hypothesis (B) of BG Appendix C, Problem 1 for `p = 3`.

Tracing relation (4) gives `x · b(Tr S) · x⁻¹ = b(Tr S')` with both traces in the prime field, so
both sides lie in the group of order dividing three generated by `w = b(1) = x^g`.  Conjugation by
`x` therefore either fixes `w` or inverts it, and inverting is impossible for an element of order
three (`eq_one_of_conj_eq_inv`) unless `w = 1`.  Either way `x` centralises `x^g`, which
`not_commute_conj` refutes.

Unlike `false_of_collisionSet_spanning` this needs neither a spanning family of collisions nor the
non-Frobenius hypothesis on the exponent. -/
theorem false_of_collisionPair_trace_ne_zero (data : FieldNormalizerData p q G) (hp : p = 3)
    (hq : q ≠ 0) {e : ℕ}
    (hexp : ∀ w ∈ data.U, conjGen data * w = w ^ e * conjGen data)
    {S S' : GaloisField p q} (hpair : CollisionPair p q e S S')
    (htr : fieldTrace p q S ≠ 0) : False := by
  set w : G := layerFieldHom data 1 (Multiplicative.ofAdd (1 : GaloisField p q)) with hwdef
  -- `x` has order three, and so does `w = x^g`
  have hx3 : data.s ^ 3 = 1 := by
    rw [← hp, FieldNormalizerData.s, ← map_pow, primeLineGenerator_pow_p, map_one]
  have hchar : ((3 : ℕ) : GaloisField p q) = 0 := by
    rw [← hp]
    exact CharP.cast_eq_zero (GaloisField p q) p
  have hw3 : w ^ 3 = 1 := by
    rw [hwdef, ← map_pow, ← ofAdd_nsmul]
    have : (3 : ℕ) • (1 : GaloisField p q) = 0 := by
      rw [nsmul_eq_mul, mul_one, hchar]
    rw [this, ofAdd_zero, map_one]
  -- the three values of the second layer on the prime field
  have hb0 : layerFieldHom data 1 (Multiplicative.ofAdd (0 : GaloisField p q)) = 1 := by
    rw [ofAdd_zero, map_one]
  have hbneg : layerFieldHom data 1 (Multiplicative.ofAdd (-1 : GaloisField p q)) = w⁻¹ := by
    rw [hwdef, ← map_inv, ← ofAdd_neg]
  -- the traced relation
  have hTr := conj_layerFieldHom_one_trace data hp hexp hpair
  have hT := eq_zero_or_one_or_neg_one_of_pow_char hp (fieldTrace_pow_char (q := q) hq S)
  have hT' := eq_zero_or_one_or_neg_one_of_pow_char hp (fieldTrace_pow_char (q := q) hq S')
  -- two auxiliary reductions
  have hkill : data.s * w * (data.s)⁻¹ = 1 → data.s * w * (data.s)⁻¹ = w := by
    intro hv
    have h1 : data.s * w = data.s := mul_inv_eq_one.mp hv
    have hw1 : w = 1 := mul_left_cancel (a := data.s) (by rw [h1, mul_one])
    rw [hw1] at hv ⊢
    exact hv
  have hinv : data.s * w * (data.s)⁻¹ = w⁻¹ → data.s * w * (data.s)⁻¹ = w := by
    intro hv
    have hw1 : w = 1 := eq_one_of_conj_eq_inv hx3 hw3 hv
    rw [hw1] at hv ⊢
    rw [hv, inv_one]
  -- `x` centralises `w`
  have hkey : data.s * w * (data.s)⁻¹ = w := by
    rcases hT with hT0 | hT1 | hTm
    · exact absurd hT0 htr
    · rw [hT1, ← hwdef] at hTr
      rcases hT' with hT0' | hT1' | hTm'
      · exact hkill (by rw [hTr, hT0', hb0])
      · rw [hTr, hT1', ← hwdef]
      · exact hinv (by rw [hTr, hTm', hbneg])
    · rw [hTm, hbneg] at hTr
      -- `x · w⁻¹ · x⁻¹ = b(Tr S')`, so `x · w · x⁻¹ = b(Tr S')⁻¹`
      have hTr' : data.s * w * (data.s)⁻¹
          = (layerFieldHom data 1 (Multiplicative.ofAdd (fieldTrace p q S')))⁻¹ := by
        rw [← hTr]
        group
      rcases hT' with hT0' | hT1' | hTm'
      · exact hkill (by rw [hTr', hT0', hb0, inv_one])
      · exact hinv (by rw [hTr', hT1', ← hwdef])
      · rw [hTr', hTm', hbneg, inv_inv]
  -- ... which is exactly the configuration refuted by Theorem 1
  have hcomm : data.s * w = w * data.s := by
    calc data.s * w = data.s * w * (data.s)⁻¹ * data.s := by group
      _ = w * data.s := by rw [hkey]
  refine not_commute_conj data hp ?_
  have hwval : w = (MulAut.conj data.y data.s)⁻¹ * data.s * MulAut.conj data.y data.s := by
    rw [hwdef]
    simp only [layerFieldHom_apply, pow_one, conjGen_def]
    rfl
  rw [← hwval]
  exact hcomm

end GroupSide

end OddOrder.BG.AppC.Problem1
