/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.BG.AppC_LemmaC2
import OddOrder.Peterfalvi.S16_NonExistenceG

/-!
# BG Appendix C: The Final Contradiction

H. Bender and G. Glauberman, *Local Analysis for the Odd Order Theorem*
(LMS LNS 188, 1994), Appendix C, pp. 145--152.

Appendix C records the Carlip--Wheeler presentation of Peterfalvi's finite-field
argument for the final contradiction.  In Peterfalvi Section 16 the same endpoint
appears as Theorem (14.2): a field-normalizer configuration is constructed with
primes `q < p`.  BG Appendix C proves that any such configuration forces
`p <= q`.

This file is the BG-side scaffold for that last interface.  Lemmas C.1 and C.2
are wired to the concrete finite-field norm-set development in
`OddOrder.BG.AppC.NormSet`; Lemma C.3 consumes the concrete generator relation
constructed in Peterfalvi's field-normalizer data.  The final bridge to
Peterfalvi Section 16 is connected and axiom-clean.
-/

namespace OddOrder.BG.AppC
-- scaffold opaque-Prop convention: see notes/meta/scaffold_opaque_prop_convention.md

open OddOrder.GroupTheory
open OddOrder.Peterfalvi
open scoped Pointwise

variable {G : Type*} [Group G]

/-! ## Theorem C setup -/

/-- **BG Appendix C, Condition (A)**: the cyclotomic factor attached to
`F_{p^q}` is coprime to `p - 1`. -/
def conditionA (p q : ℕ) : Prop :=
  Nat.Coprime ((p ^ q - 1) / (p - 1)) (p - 1)

/-- The concrete norm set cardinality conclusion attached to a Peterfalvi
Section 16 hypothesis.

This adapter keeps the `Fact hyp.base.p.Prime` instance local, because the
concrete type `GaloisField hyp.base.p hyp.base.q` needs that instance even to be
formed. -/
def normSetCardGeTwo (hyp : S16.Hypothesis (G := G)) : Prop :=
  letI : Fact hyp.base.p.Prime := ⟨hyp.base.p_prime⟩
  2 ≤ (NormSet.normSetE hyp.base.p hyp.base.q).ncard

/-- The concrete norm set inversion-closure conclusion attached to a Peterfalvi
Section 16 hypothesis. -/
def normSetInverseClosed (hyp : S16.Hypothesis (G := G)) : Prop :=
  letI : Fact hyp.base.p.Prime := ⟨hyp.base.p_prime⟩
  NormSet.normSetE hyp.base.p hyp.base.q =
    (NormSet.normSetE hyp.base.p hyp.base.q)⁻¹

/-- The concrete Frobenius group `H = P \rtimes U` from BG Appendix C,
with Peterfalvi Section 16 parameters. -/
abbrev hypothesisBFrobeniusGroup (hyp : S16.Hypothesis (G := G)) : Type _ :=
  letI : Fact hyp.base.p.Prime := ⟨hyp.base.p_prime⟩
  NormSet.normOneFrobeniusGroup hyp.base.p hyp.base.q

/-- The prime-field additive line `P₀ ≤ P` inside the concrete BG Frobenius
group, generated by `1 : F_{p^q}`. -/
noncomputable def hypothesisBPrimeLine (hyp : S16.Hypothesis (G := G)) :
    Subgroup (hypothesisBFrobeniusGroup hyp) :=
  letI : Fact hyp.base.p.Prime := ⟨hyp.base.p_prime⟩
  NormSet.normOneFrobeniusSubspaceKernel hyp.base.p hyp.base.q
    (Submodule.span (ZMod hyp.base.p)
      ({(1 : GaloisField hyp.base.p hyp.base.q)} :
        Set (GaloisField hyp.base.p hyp.base.q)))

/-- The norm-one complement `U ≤ H` inside the concrete BG Frobenius group. -/
noncomputable def hypothesisBComplement (hyp : S16.Hypothesis (G := G)) :
    Subgroup (hypothesisBFrobeniusGroup hyp) :=
  letI : Fact hyp.base.p.Prime := ⟨hyp.base.p_prime⟩
  NormSet.normOneFrobeniusComplement hyp.base.p hyp.base.q

/-- **BG Appendix C, Hypothesis (B)**, transported to the Peterfalvi Section 16
field-normalizer data.  This records the concrete monomorphism `H -> G`, the
identification of the prime-field line with Peterfalvi's `W₂`, the
identification of the complement with Peterfalvi's `U`, and the two normalizer
assumptions used in Lemma C.3. -/
structure HypothesisB (hyp : S16.Hypothesis (G := G)) where
  data : S16.FieldNormalizerData hyp
  sigma : hypothesisBFrobeniusGroup hyp →* G
  sigma_injective : Function.Injective sigma
  sigma_P0_eq_W2 : (hypothesisBPrimeLine hyp).map sigma = hyp.base.W2
  sigma_U_eq_U : (hypothesisBComplement hyp).map sigma = hyp.base.U
  P0_normalizes_Q :
    (hypothesisBPrimeLine hyp).map sigma ≤ Subgroup.normalizer (hyp.base.Q : Set G)
  P0_conj_y_normalizes_U :
    MulAut.conj data.y • ((hypothesisBPrimeLine hyp).map sigma) ≤
      Subgroup.normalizer (hyp.base.U : Set G)

/-- The norm-set outputs needed to assemble BG Theorem C from Lemmas C.1--C.3. -/
structure NormSetData (hyp : S16.Hypothesis (G := G)) where
  conditionA_holds : conditionA hyp.base.p hyp.base.q
  E_card_ge_two : normSetCardGeTwo hyp
  E_inverse_closed : normSetInverseClosed hyp

/-! ## Lemmas C.1--C.3 -/

/-- **BG Lemma C.1**: if the norm set is inverse-closed and has at least two
elements, the polynomial root count gives `p <= q`. -/
theorem lemmaC1_root_count [Finite G]
    (hyp : S16.Hypothesis (G := G)) (norms : NormSetData hyp) :
    hyp.base.p ≤ hyp.base.q := by
  haveI : Fact hyp.base.p.Prime := ⟨hyp.base.p_prime⟩
  have hEinv :
      NormSet.normSetE hyp.base.p hyp.base.q =
        (NormSet.normSetE hyp.base.p hyp.base.q)⁻¹ := by
    simpa [normSetInverseClosed] using norms.E_inverse_closed
  have hcard : 2 ≤ (NormSet.normSetE hyp.base.p hyp.base.q).ncard := by
    simpa [normSetCardGeTwo] using norms.E_card_ge_two
  exact NormSet.lemmaC1 (p := hyp.base.p) (q := hyp.base.q)
    hyp.base.q_prime hEinv hcard

/-- **BG Lemma C.2**: condition (A) alone gives that the norm set has at
least two elements. -/
theorem lemmaC2_card_ge_two_of_conditionA [Finite G]
    (hyp : S16.Hypothesis (G := G)) (hA : conditionA hyp.base.p hyp.base.q) :
    normSetCardGeTwo hyp := by
  haveI : Fact hyp.base.p.Prime := ⟨hyp.base.p_prime⟩
  have hcard := NormSet.lemmaC2 (p := hyp.base.p) (q := hyp.base.q)
    hyp.base.p_odd hyp.base.q_prime hyp.base.q_odd hA
  simpa [normSetCardGeTwo] using hcard

/-- **BG Lemma C.2**: the field-normalizer data supplies condition (A), hence
the norm set has at least two elements. -/
theorem lemmaC2_card_ge_two [Finite G]
    (hyp : S16.Hypothesis (G := G)) (data : S16.FieldNormalizerData hyp) :
    normSetCardGeTwo hyp :=
  lemmaC2_card_ge_two_of_conditionA hyp data.cyclotomic_coprime

/-- **BG Lemma C.3**: the norm set is closed under inversion. -/
theorem lemmaC3_inverse_closed [Finite G]
    (hyp : S16.Hypothesis (G := G)) (data : S16.FieldNormalizerData hyp) :
    normSetInverseClosed hyp := by
  haveI : Fact hyp.base.p.Prime := ⟨hyp.base.p_prime⟩
  simpa [normSetInverseClosed]
    using NormSet.normSetE_eq_inv_of_forall_normN_two_mul_sub_one
      (p := hyp.base.p) (q := hyp.base.q) hyp.base.q_prime.pos
      data.appC_normSet_generator_relation

/-! ## Theorem C and the Peterfalvi bridge -/

/-- **BG Theorem C**: the field-normalizer configuration constructed in
Peterfalvi (14.2) forces `p <= q`. -/
theorem theoremC [Finite G] (hyp : S16.Hypothesis (G := G)) :
    S16.FieldNormalizerData hyp → hyp.base.p ≤ hyp.base.q := by
  intro data
  exact lemmaC1_root_count hyp
    { conditionA_holds := data.cyclotomic_coprime
      E_card_ge_two := lemmaC2_card_ge_two hyp data
      E_inverse_closed := lemmaC3_inverse_closed hyp data }

/-- **BG Appendix C + Peterfalvi Section 16**: once Peterfalvi constructs the
field-normalizer data, BG Theorem C contradicts the standing hypothesis `q < p`. -/
theorem final_contradiction [Finite G]
    (hG : OddOrder.BG.IsMinimalSimpleOdd G)
    (hnoV : ¬ ∃ M : Subgroup G, M ∈ maximalSubgroups G ∧ OddOrder.GroupTheory.IsTypeV M)
    (hncH0C : OddOrder.Peterfalvi.S13.H0CNoncoherenceRefuter G)
    (hyp : S16.Hypothesis (G := G)) :
    False :=
  S16.nonexistence_of_G hG hnoV hncH0C hyp (theoremC hyp)

end OddOrder.BG.AppC
