/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Peterfalvi.Appendices.Suzuki.CentralizerInductionBridge
import OddOrder.Peterfalvi.Appendices.Suzuki.DistinguishedInvolution
import OddOrder.Peterfalvi.Appendices.Suzuki.QStructure

/-!
# Peterfalvi Part II, Chapter I §3, Proposition 2: the non-simple case

T. Peterfalvi, *Character Theory for the Odd Order Theorem* (LMS LNS 272,
2000), Part II, Chapter I §3, Proposition 2, pp. 106–107.

This leaf follows the first reduction in Peterfalvi's proof.  If `G` is not
simple, choose `1 < M < G` normal.  Proposition 1(e), together with the
faithfulness of the action, gives `O_{2'}(G) = 1`.  Consequently `M` cannot
have odd order; an involution in `M` and the single involution class from
§1 Proposition 2(b) show that every involution of `G` belongs to `M`.
Thus the subgroup `L = ⟨I⟩` generated by all involutions is itself a
nontrivial proper normal subgroup.

The later part of the proposition restricts (A1)--(A3) to this `L`, applies
the induction hypothesis, and transports its concrete target back to `G`.
Those steps are kept separate from the normal-subgroup reduction below.
-/

set_option autoImplicit false

namespace OddOrder.Peterfalvi.Appendices.Suzuki

open OddOrder.Isaacs
open MulAction
open scoped Pointwise
open scoped LinearAlgebra.Projectivization

universe u v

/-! ## The subgroup generated by all involutions -/

/-- Peterfalvi source notation `I`: the nonidentity involutions of `G`. -/
def involutionSet (G : Type u) [Group G] : Set G :=
  {x | x ^ 2 = 1 ∧ x ≠ 1}

/-- Peterfalvi's `⟨I⟩`: the subgroup generated by the nonidentity
involutions of `G`. -/
def involutionClosure (G : Type u) [Group G] : Subgroup G :=
  Subgroup.closure (involutionSet G)

/-- The set of involutions is invariant under conjugation, so its generated
subgroup is normal.  This is the normality implicit in the source when the
initial normal subgroup is replaced by `⟨I⟩`. -/
theorem involutionClosure_normal (G : Type u) [Group G] :
    (involutionClosure G).Normal := by
  rw [← Subgroup.normalizer_eq_top_iff]
  apply top_unique
  change (⊤ : Subgroup G) ≤
    Subgroup.normalizer
      (Subgroup.closure (involutionSet G))
  rw [Subgroup.le_normalizer_closure_iff]
  rintro g _ x ⟨hx2, hx1⟩
  apply Subgroup.subset_closure
  refine ⟨?_, ?_⟩
  · calc
      (g * x * g⁻¹) ^ 2 = g * x ^ 2 * g⁻¹ := by
        simp only [pow_two, mul_assoc, inv_mul_cancel_left]
      _ = 1 := by rw [hx2]; simp
  · intro hconj
    apply hx1
    have h := congrArg (fun z : G => g⁻¹ * z * g) hconj
    simpa [mul_assoc] using h

/-- Since `⟨I⟩` is normal, its ordinary subgroup closure agrees with
the normal closure of the involution set. -/
theorem involutionClosure_eq_normalClosure (G : Type u) [Group G] :
    involutionClosure G =
      Subgroup.normalClosure (involutionSet G) := by
  apply le_antisymm Subgroup.closure_le_normalClosure
  letI : (involutionClosure G).Normal := involutionClosure_normal G
  exact Subgroup.normalClosure_le_normal
    (s := involutionSet G)
    (N := involutionClosure G) Subgroup.subset_closure

namespace Hypothesis

variable {G : Type u} {Omega : Type v} [Group G] [MulAction G Omega]
  [Finite G]
  (hyp : OddOrder.Peterfalvi.Appendices.Suzuki.Hypothesis G Omega)

/-- Transport a concrete Theorem A target for the top subgroup of `L`
to the same concrete target for `L` as a subgroup of the ambient group.
The group coordinate is composed with the canonical equivalence `L ≃* ⊤`,
while the permutation coordinate on `Omega` is unchanged. -/
noncomputable def TheoremATarget.ofTop (L : Subgroup G)
    (target : TheoremATarget (G := L) (Omega := Omega) (⊤ : Subgroup L)) :
    TheoremATarget (G := G) (Omega := Omega) L := by
  cases target with
  | psl2 data =>
      letI : Field data.F := data.fieldF
      letI : Finite data.F := data.finiteF
      letI : CharP data.F 2 := data.charTwoF
      exact .psl2
        { F := data.F
          fieldF := data.fieldF
          finiteF := data.finiteF
          charTwoF := data.charTwoF
          cardF_gt_two := data.cardF_gt_two
          groupEquiv := (Subgroup.topEquiv (G := L)).symm.trans data.groupEquiv
          actionEquiv :=
            { toFun := data.actionEquiv.toFun
              map_smul' := fun l omega => by
                change data.actionEquiv.toFun ((l : L) • omega) =
                  data.groupEquiv ((Subgroup.topEquiv (G := L)).symm l) •
                    data.actionEquiv.toFun omega
                simpa [MulAction.subgroup_smul_def] using data.actionEquiv.map_smul'
                  ((Subgroup.topEquiv (G := L)).symm l) omega }
          actionEquiv_bijective := data.actionEquiv_bijective }
  | suzuki data =>
      exact .suzuki
        { m := data.m
          m_pos := data.m_pos
          groupEquiv := (Subgroup.topEquiv (G := L)).symm.trans data.groupEquiv
          actionEquiv :=
            { toFun := data.actionEquiv.toFun
              map_smul' := fun l omega => by
                change data.actionEquiv.toFun ((l : L) • omega) =
                  data.groupEquiv ((Subgroup.topEquiv (G := L)).symm l) •
                    data.actionEquiv.toFun omega
                simpa [MulAction.subgroup_smul_def] using data.actionEquiv.map_smul'
                  ((Subgroup.topEquiv (G := L)).symm l) omega }
          actionEquiv_bijective := data.actionEquiv_bijective }
  | psu3 data =>
      exact .psu3
        { n := data.n
          one_lt_n := data.one_lt_n
          groupEquiv := (Subgroup.topEquiv (G := L)).symm.trans data.groupEquiv
          actionEquiv :=
            { toFun := data.actionEquiv.toFun
              map_smul' := fun l omega => by
                change data.actionEquiv.toFun ((l : L) • omega) =
                  data.groupEquiv ((Subgroup.topEquiv (G := L)).symm l) •
                    data.actionEquiv.toFun omega
                simpa [MulAction.subgroup_smul_def] using data.actionEquiv.map_smul'
                  ((Subgroup.topEquiv (G := L)).symm l) omega }
          actionEquiv_bijective := data.actionEquiv_bijective }

section /- 3: Application of the Induction Hypothesis (pp. 105–107) -/

include hyp

/-! ## The proper normal subgroup and the odd core -/

/-- A group satisfying (A1)--(A3) is nontrivial: its distinguished element
`t` is a nonidentity involution. -/
theorem nontrivial_group : Nontrivial G :=
  ⟨⟨hyp.t, 1, hyp.t_ne_one⟩⟩

/-- Negating simplicity therefore supplies an honest normal subgroup
`1 < M < G`; no normal subgroup is added as carrier data. -/
theorem exists_proper_nontrivial_normal_subgroup_of_not_simple
    (hG : ¬ IsSimpleGroup G) :
    ∃ M : Subgroup G, M.Normal ∧ M ≠ ⊥ ∧ M ≠ ⊤ := by
  by_contra hM
  apply hG
  rw [isSimpleGroup_iff]
  refine ⟨hyp.nontrivial_group, ?_⟩
  intro M hMnormal
  by_contra hcases
  have hMbot : M ≠ ⊥ := fun h => hcases (Or.inl h)
  have hMtop : M ≠ ⊤ := fun h => hcases (Or.inr h)
  exact hM ⟨M, hMnormal, hMbot, hMtop⟩

/-- By (A2), (A3), and §1 Proposition 1(e), `O_{2'}(G) = 1`.
Faithfulness makes the normal core of the point stabilizer trivial. -/
theorem oPiCore_two_compl_eq_bot :
    Ch03.oPiCore ({2}ᶜ : Set ℕ) G = ⊥ := by
  rw [hyp.oPiCore_two_compl_eq_normalCore, hyp.normalCore_H_eq_bot]

/-- Every nontrivial normal subgroup has even order.  Otherwise it would be
a normal `2'`-subgroup and hence lie in the trivial `2'`-core. -/
theorem even_card_of_normal_ne_bot (M : Subgroup G) (hMnormal : M.Normal)
    (hMbot : M ≠ ⊥) : Even (Nat.card M) := by
  by_contra hMeven
  have hModd : Odd (Nat.card M) := Nat.not_even_iff_odd.mp hMeven
  letI : M.Normal := hMnormal
  have hMpi : Ch03.Subgroup.IsPiGroup ({2}ᶜ : Set ℕ) M := by
    intro p hp
    simp only [Set.mem_compl_iff, Set.mem_singleton_iff]
    intro hp2
    subst p
    exact (Nat.two_dvd_ne_zero.mpr (Nat.odd_iff.mp hModd))
      (Nat.mem_primeFactors.mp hp).2.1
  have hMle : M ≤ Ch03.oPiCore ({2}ᶜ : Set ℕ) G := hMpi.le_oPiCore
  rw [hyp.oPiCore_two_compl_eq_bot] at hMle
  exact hMbot (le_bot_iff.mp hMle)

/-! ## Every involution belongs to every nontrivial normal subgroup -/

/-- Once `O_{2'}(G)=1`, every involution of `G` lies in every nontrivial
normal subgroup.  The subgroup has even order, hence contains one
involution, and §1 Proposition 2(b) says all involutions are conjugate. -/
theorem involution_mem_normal_subgroup (M : Subgroup G)
    (hMnormal : M.Normal) (hMbot : M ≠ ⊥) {u : G}
    (hu2 : u ^ 2 = 1) (hu1 : u ≠ 1) : u ∈ M := by
  obtain ⟨s, hsM, hs2, hs1⟩ :=
    exists_sq_eq_one_of_even_card
      (hyp.even_card_of_normal_ne_bot M hMnormal hMbot)
  obtain ⟨g, hg⟩ := isConj_iff.mp
    (hyp.isConj_of_involutions hs2 hs1 hu2 hu1)
  rw [← hg]
  exact hMnormal.conj_mem s hsM g

/-- The source subgroup `L = ⟨I⟩` lies in every nontrivial normal
subgroup. -/
theorem involutionClosure_le_normal_subgroup (M : Subgroup G)
    (hMnormal : M.Normal) (hMbot : M ≠ ⊥) :
    involutionClosure G ≤ M := by
  rw [involutionClosure, Subgroup.closure_le]
  rintro u ⟨hu2, hu1⟩
  exact hyp.involution_mem_normal_subgroup M hMnormal hMbot hu2 hu1

/-- The source subgroup `L = ⟨I⟩` is nontrivial because it contains
the distinguished involution `t`. -/
theorem involutionClosure_ne_bot : involutionClosure G ≠ ⊥ := by
  intro hbot
  have ht : hyp.t ∈ involutionClosure G := by
    apply Subgroup.subset_closure
    exact ⟨hyp.t_sq, hyp.t_ne_one⟩
  rw [hbot, Subgroup.mem_bot] at ht
  exact hyp.t_ne_one ht

/-- If `G` is not simple, Peterfalvi's replacement `L = ⟨I⟩` is an
honestly constructed nontrivial proper normal subgroup. -/
theorem involutionClosure_proper_normal_of_not_simple
    (hG : ¬ IsSimpleGroup G) :
    (involutionClosure G).Normal ∧
      involutionClosure G ≠ ⊥ ∧ involutionClosure G ≠ ⊤ := by
  obtain ⟨M, hMnormal, hMbot, hMtop⟩ :=
    hyp.exists_proper_nontrivial_normal_subgroup_of_not_simple hG
  have hLM : involutionClosure G ≤ M :=
    hyp.involutionClosure_le_normal_subgroup M hMnormal hMbot
  refine ⟨involutionClosure_normal G, hyp.involutionClosure_ne_bot, ?_⟩
  intro hLtop
  rw [hLtop] at hLM
  exact hMtop (top_unique hLM)

/-! ## The `K` witness and the commutator bijection -/

/-- The nonidentity witness `k ∈ K` from §1 Proposition 3 belongs to
`L = ⟨I⟩`.  Peterfalvi writes `k = t(tk)`; both factors are
involutions because `tkt = k⁻¹`. -/
theorem exists_ne_one_mem_KSet_involutionClosure :
    ∃ k : G, k ∈ hyp.KSet ∧ k ≠ 1 ∧ k ∈ involutionClosure G := by
  obtain ⟨k, hkK, hk1⟩ := hyp.exists_ne_one_mem_KSet
  have htt : hyp.t * hyp.t = 1 := by
    simpa [pow_two] using hyp.t_sq
  have htk2 : (hyp.t * k) ^ 2 = 1 := by
    rw [pow_two]
    calc
      hyp.t * k * (hyp.t * k) = (hyp.t * k * hyp.t) * k := by
        simp only [mul_assoc]
      _ = k⁻¹ * k := by rw [hkK.2]
      _ = 1 := inv_mul_cancel k
  have htk1 : hyp.t * k ≠ 1 := by
    intro htk
    apply hyp.t_not_mem_H
    have htkinv : hyp.t = k⁻¹ := eq_inv_of_mul_eq_one_left htk
    rw [htkinv]
    exact inv_mem (hyp.D_le_H hkK.1)
  have htL : hyp.t ∈ involutionClosure G := by
    apply Subgroup.subset_closure
    exact ⟨hyp.t_sq, hyp.t_ne_one⟩
  have htkL : hyp.t * k ∈ involutionClosure G := by
    apply Subgroup.subset_closure
    exact ⟨htk2, htk1⟩
  have hkfactor : k = hyp.t * (hyp.t * k) := by
    calc
      k = 1 * k := (one_mul k).symm
      _ = (hyp.t * hyp.t) * k := by rw [htt]
      _ = hyp.t * (hyp.t * k) := by rw [mul_assoc]
  refine ⟨k, hkK, hk1, ?_⟩
  rw [hkfactor]
  exact (involutionClosure G).mul_mem htL htkL

/-- The source map `x ↦ [x,k]` on `Q`, using the book convention

`[x,k] = x⁻¹xᵏ = x⁻¹k⁻¹xk`.

Normality of `Q` in `H` makes this an endomap of the actual subgroup `Q`;
it is not asserted to be a group homomorphism. -/
def qCommutatorMap {k : G} (hkK : k ∈ hyp.KSet) : hyp.Q → hyp.Q :=
  fun x =>
    ⟨(x : G)⁻¹ * k⁻¹ * (x : G) * k, by
      have hkH : k ∈ hyp.H := hyp.D_le_H hkK.1
      have hconj : k⁻¹ * (x : G) * k ∈ hyp.Q := by
        have h := hyp.Q_normal_in_H k⁻¹ (inv_mem hkH) (x : G) x.2
        simpa using h
      simpa [mul_assoc] using
        hyp.Q.mul_mem (hyp.Q.inv_mem x.2) hconj⟩

@[simp]
theorem coe_qCommutatorMap {k : G} (hkK : k ∈ hyp.KSet) (x : hyp.Q) :
    (hyp.qCommutatorMap hkK x : G) =
      (x : G)⁻¹ * k⁻¹ * (x : G) * k := rfl

/-- §2 Proposition 1(a), `C_Q(k)=1`, makes the commutator endomap
injective.  Equality of two commutators puts `yx⁻¹` in `C_Q(k)`. -/
theorem qCommutatorMap_injective {k : G} (hkK : k ∈ hyp.KSet)
    (hk1 : k ≠ 1) : Function.Injective (hyp.qCommutatorMap hkK) := by
  intro x y hxy
  have hval := congrArg Subtype.val hxy
  change (x : G)⁻¹ * k⁻¹ * (x : G) * k =
    (y : G)⁻¹ * k⁻¹ * (y : G) * k at hval
  have hcancel :
      (x : G)⁻¹ * k⁻¹ * (x : G) =
        (y : G)⁻¹ * k⁻¹ * (y : G) :=
    mul_right_cancel hval
  have hleft :
      (y : G) * (x : G)⁻¹ * k⁻¹ * (x : G) =
        k⁻¹ * (y : G) := by
    have h := congrArg (fun z : G => (y : G) * z) hcancel
    simpa [mul_assoc] using h
  have hcommInvEq :
      ((y : G) * (x : G)⁻¹) * k⁻¹ =
        k⁻¹ * ((y : G) * (x : G)⁻¹) := by
    have h := congrArg (fun z : G => z * (x : G)⁻¹) hleft
    simpa [mul_assoc] using h
  have hcommInv : Commute ((y : G) * (x : G)⁻¹) k⁻¹ :=
    hcommInvEq
  have hcomm : Commute ((y : G) * (x : G)⁻¹) k := by
    simpa using hcommInv.inv_right
  have hmem : (y : G) * (x : G)⁻¹ ∈
      hyp.Q ⊓ Subgroup.centralizer {k} :=
    ⟨hyp.Q.mul_mem y.2 (hyp.Q.inv_mem x.2),
      Subgroup.mem_centralizer_singleton_iff.mpr hcomm⟩
  rw [hyp.Q_inf_centralizer_eq_bot_of_mem_KSet hkK hk1,
    Subgroup.mem_bot] at hmem
  exact Subtype.ext (mul_inv_eq_one.mp hmem).symm

/-- Since `Q` is finite, the injective commutator endomap is surjective. -/
theorem qCommutatorMap_surjective {k : G} (hkK : k ∈ hyp.KSet)
    (hk1 : k ≠ 1) : Function.Surjective (hyp.qCommutatorMap hkK) :=
  Finite.injective_iff_surjective.mp
    (hyp.qCommutatorMap_injective hkK hk1)

/-- Peterfalvi conclusion `Q = [Q,k] ≤ L`.  Surjectivity expresses each
`q ∈ Q` as `x⁻¹k⁻¹xk`; normality of `L = ⟨I⟩` and `k ∈ L`
then put both factors in `L`. -/
theorem Q_le_involutionClosure : hyp.Q ≤ involutionClosure G := by
  obtain ⟨k, hkK, hk1, hkL⟩ :=
    hyp.exists_ne_one_mem_KSet_involutionClosure
  have hsurj : Function.Surjective (hyp.qCommutatorMap hkK) :=
    hyp.qCommutatorMap_surjective hkK hk1
  have hLnormal : (involutionClosure G).Normal :=
    involutionClosure_normal G
  intro q hqQ
  obtain ⟨x, hx⟩ := hsurj ⟨q, hqQ⟩
  have hxval := congrArg Subtype.val hx
  change (x : G)⁻¹ * k⁻¹ * (x : G) * k = q at hxval
  have hconjL : (x : G)⁻¹ * k⁻¹ * (x : G) ∈
      involutionClosure G := by
    have h := hLnormal.conj_mem k⁻¹
      ((involutionClosure G).inv_mem hkL) (x : G)⁻¹
    simpa [mul_assoc] using h
  rw [← hxval]
  exact (involutionClosure G).mul_mem hconjL hkL


/-! ## Restricting (A1)--(A3) to the involution closure -/

section

variable (L : Subgroup G) (hQL : hyp.Q ≤ L) (htL : hyp.t ∈ L)

include hQL htL

/-- The transitivity step in **Peterfalvi Part II, Ch. I §3,
Proposition 2**.  If `omega` is not the base point, regularity of `Q` gives
`q ∈ Q` with `q • (t • basept) = omega`; the element `qt ∈ L` therefore
moves `basept` to `omega`. -/
lemma exists_mem_subgroup_smul_basept_eq (omega : Omega) :
    ∃ l : L, l • hyp.basept = omega := by
  by_cases homega : omega = hyp.basept
  · exact ⟨1, by simp [homega]⟩
  · obtain ⟨q, hq⟩ := hyp.qRegularEquiv.surjective ⟨omega, homega⟩
    let l : L := ⟨(q : G) * hyp.t, L.mul_mem (hQL q.2) htL⟩
    refine ⟨l, ?_⟩
    change ((q : G) * hyp.t) • hyp.basept = omega
    rw [mul_smul]
    exact congrArg Subtype.val hq

/-- **Peterfalvi Part II, Ch. I §3, Proposition 2**: if `Q ≤ L` and
`t ∈ L`, then the restricted action of `L` on `Omega` is doubly transitive.
The proof uses the regular `Q`-coordinates on the punctured domain to send
any ordered pair of distinct points to any other such pair. -/
theorem subgroup_isMultiplyPretransitive_two :
    IsMultiplyPretransitive L Omega 2 := by
  rw [is_two_pretransitive_iff]
  intro a b c d hab hcd
  obtain ⟨la, hla⟩ := hyp.exists_mem_subgroup_smul_basept_eq L hQL htL a
  obtain ⟨lc, hlc⟩ := hyp.exists_mem_subgroup_smul_basept_eq L hQL htL c
  have hb' : la⁻¹ • b ≠ hyp.basept := by
    intro heq
    apply hab
    have hba : b = a := by
      calc
        b = la • (la⁻¹ • b) := (smul_inv_smul la b).symm
        _ = la • hyp.basept := congrArg (fun z => la • z) heq
        _ = a := hla
    exact hba.symm
  have hd' : lc⁻¹ • d ≠ hyp.basept := by
    intro heq
    apply hcd
    have hdc : d = c := by
      calc
        d = lc • (lc⁻¹ • d) := (smul_inv_smul lc d).symm
        _ = lc • hyp.basept := congrArg (fun z => lc • z) heq
        _ = c := hlc
    exact hdc.symm
  obtain ⟨qb, hqb⟩ := hyp.qRegularEquiv.surjective ⟨la⁻¹ • b, hb'⟩
  obtain ⟨qd, hqd⟩ := hyp.qRegularEquiv.surjective ⟨lc⁻¹ • d, hd'⟩
  have hqb_val : (qb : G) • (hyp.t • hyp.basept) = (la : G)⁻¹ • b :=
    congrArg Subtype.val hqb
  have hqd_val : (qd : G) • (hyp.t • hyp.basept) = (lc : G)⁻¹ • d :=
    congrArg Subtype.val hqd
  let qL : L :=
    ⟨(qd : G) * (qb : G)⁻¹,
      L.mul_mem (hQL qd.2) (L.inv_mem (hQL qb.2))⟩
  refine ⟨lc * qL * la⁻¹, ?_, ?_⟩
  · change (((lc : G) * (qL : G) * (la : G)⁻¹) • a) = c
    rw [mul_smul, mul_smul]
    have hla' : (la : G)⁻¹ • a = hyp.basept := by
      rw [← hla]
      exact inv_smul_smul la hyp.basept
    rw [hla']
    have hqQ : (qL : G) ∈ hyp.Q :=
      hyp.Q.mul_mem qd.2 (hyp.Q.inv_mem qb.2)
    rw [hyp.smul_basept_eq_of_mem_H (hyp.Q_le_H hqQ)]
    exact hlc
  · change (((lc : G) * (qL : G) * (la : G)⁻¹) • b) = d
    rw [mul_smul, mul_smul]
    have hqmap : (qL : G) • ((la : G)⁻¹ • b) = (lc : G)⁻¹ • d := by
      change ((qd : G) * (qb : G)⁻¹) • ((la : G)⁻¹ • b) =
        (lc : G)⁻¹ • d
      rw [← hqb_val, ← hqd_val]
      rw [mul_smul, inv_smul_smul]
    change (lc : G) • ((qL : G) • ((la : G)⁻¹ • b)) = d
    rw [hqmap, smul_inv_smul]

/-- **Peterfalvi Part II, Ch. I §3, Proposition 2**: the action of `L`
on `Omega` satisfies the same hypotheses (A1)--(A3).  Its point stabilizer,
root group, and two-point stabilizer are the actual intersections with `L`,
encoded by `subgroupOf`; every structure field is derived from the ambient
hypothesis, `Q ≤ L`, and `t ∈ L`. -/
noncomputable def subgroupHypothesis : Hypothesis L Omega := by
  let tL : L := ⟨hyp.t, htL⟩
  letI : FaithfulSMul G Omega := hyp.faithful
  refine
    { basept := hyp.basept
      doubly_transitive := hyp.subgroup_isMultiplyPretransitive_two L hQL htL
      faithful := inferInstance
      H := hyp.H.subgroupOf L
      Q := hyp.Q.subgroupOf L
      D := hyp.D.subgroupOf L
      H_def := ?_
      t := tL
      t_sq := ?_
      t_ne_one := ?_
      t_not_mem_H := ?_
      D_def := ?_
      Q_le_H := ?_
      Q_normal_in_H := ?_
      Q_inf_D_eq_bot := ?_
      Q_mul_D_eq_H := ?_
      Q_even := ?_
      D_odd := ?_
      two_rank_ge_two := ?_ }
  · ext l
    change (l : G) ∈ hyp.H ↔ (l : G) • hyp.basept = hyp.basept
    rw [hyp.H_def, mem_stabilizer_iff]
  · exact Subtype.ext hyp.t_sq
  · intro h
    exact hyp.t_ne_one (congrArg Subtype.val h)
  · exact hyp.t_not_mem_H
  · ext l
    rw [Subgroup.mem_inf, Subgroup.mem_map_equiv, MulAut.conj_symm_apply]
    change (l : G) ∈ hyp.D ↔
      (l : G) ∈ hyp.H ∧ hyp.t⁻¹ * (l : G) * hyp.t ∈ hyp.H
    exact hyp.mem_D_iff
  · intro q hq
    exact hyp.Q_le_H hq
  · intro h hh q hq
    exact hyp.Q_normal_in_H (h : G) hh (q : G) hq
  · rw [eq_bot_iff]
    intro x hx
    rw [Subgroup.mem_bot]
    have hx' : (x : G) ∈ hyp.Q ⊓ hyp.D := ⟨hx.1, hx.2⟩
    rw [hyp.Q_inf_D_eq_bot, Subgroup.mem_bot] at hx'
    exact Subtype.ext hx'
  · apply Set.Subset.antisymm
    · rintro y ⟨q, hq, d, hd, rfl⟩
      change (q : G) * (d : G) ∈ hyp.H
      exact hyp.H.mul_mem (hyp.Q_le_H hq) (hyp.D_le_H hd)
    · intro y hy
      have hyprod : (y : G) ∈ (hyp.Q : Set G) * (hyp.D : Set G) := by
        rw [hyp.Q_mul_D_eq_H]
        exact hy
      obtain ⟨q, hq, d, hd, hqd⟩ := hyprod
      have hdL : d ∈ L := by
        have hdeq : d = q⁻¹ * (y : G) := by
          rw [← hqd]
          simp
        rw [hdeq]
        exact L.mul_mem (L.inv_mem (hQL hq)) y.2
      refine ⟨⟨q, hQL hq⟩, hq, ⟨d, hdL⟩, hd, ?_⟩
      exact Subtype.ext hqd
  · have hcard : Nat.card ↥(hyp.Q.subgroupOf L) = Nat.card ↥hyp.Q :=
      Nat.card_congr (Subgroup.subgroupOfEquivOfLe hQL).toEquiv
    rw [hcard]
    exact hyp.Q_even
  · have hcard : Nat.card ↥(hyp.D.subgroupOf L) =
        Nat.card ↥(hyp.D ⊓ L) := by
      rw [← Subgroup.inf_subgroupOf_right hyp.D L]
      exact Nat.card_congr
        (Subgroup.subgroupOfEquivOfLe (K := L) inf_le_right).toEquiv
    rw [hcard]
    exact hyp.D_odd.of_dvd_nat (Subgroup.card_dvd_of_le inf_le_left)
  · obtain ⟨X, hXQ, hX4, hXsq⟩ := hyp.exists_four_subgroup_le_Q
    have hXL : X ≤ L := hXQ.trans hQL
    refine ⟨X.subgroupOf L, ?_, ?_⟩
    · rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe hXL).toEquiv]
      exact hX4
    · intro x hx
      apply Subtype.ext
      exact hXsq (x : G) hx

end

/-! ## The factorization `G = LD` and odd index -/

/-- **Peterfalvi Part II, Ch. I §3, Proposition 2**: double transitivity
of `L` gives the subgroup form `L ⊔ D = G` of the source factorization
`G = LD`.  The proof explicitly writes every `g` as `l d`, where `l ∈ L`
and `d` fixes both `basept` and `t • basept`. -/
theorem sup_D_eq_top_of_two_pretransitive
    (L : Subgroup G) (hLtwo : IsMultiplyPretransitive L Omega 2) :
    L ⊔ hyp.D = ⊤ := by
  apply top_unique
  intro g _
  have hbt : hyp.basept ≠ hyp.t • hyp.basept :=
    (hyp.smul_basept_ne_of_not_mem_H hyp.t_not_mem_H).symm
  have hgbt : g • hyp.basept ≠ g • (hyp.t • hyp.basept) := by
    intro h
    exact hbt (smul_left_cancel g h)
  obtain ⟨l, hlb, hlt⟩ :=
    (is_two_pretransitive_iff.mp hLtwo) hbt hgbt
  let d : G := (l : G)⁻¹ * g
  have hdD : d ∈ hyp.D := by
    rw [hyp.D_eq_stabilizer_inf, Subgroup.mem_inf]
    constructor
    · rw [mem_stabilizer_iff]
      change ((l : G)⁻¹ * g) • hyp.basept = hyp.basept
      rw [mul_smul, ← hlb]
      change (l : G)⁻¹ • (l : G) • hyp.basept = hyp.basept
      exact inv_smul_smul (l : G) hyp.basept
    · rw [mem_stabilizer_iff]
      change ((l : G)⁻¹ * g) • (hyp.t • hyp.basept) =
        hyp.t • hyp.basept
      rw [mul_smul, ← hlt]
      change (l : G)⁻¹ • (l : G) • (hyp.t • hyp.basept) =
        hyp.t • hyp.basept
      exact inv_smul_smul (l : G) (hyp.t • hyp.basept)
  have hlSup : (l : G) ∈ L ⊔ hyp.D :=
    (show L ≤ L ⊔ hyp.D from le_sup_left) l.2
  have hdSup : d ∈ L ⊔ hyp.D :=
    (show hyp.D ≤ L ⊔ hyp.D from le_sup_right) hdD
  have hprod : (l : G) * d ∈ L ⊔ hyp.D :=
    (L ⊔ hyp.D).mul_mem hlSup hdSup
  simpa [d] using hprod

/-- **Peterfalvi Part II, Ch. I §3, Proposition 2**: if a normal `L`
satisfies `G = LD`, then `[G:L]` divides the odd order of `D`, hence is
odd. -/
theorem odd_index_of_sup_D_eq_top
    (L : Subgroup G) (hLnormal : L.Normal)
    (hsup : L ⊔ hyp.D = ⊤) : Odd L.index := by
  letI : L.Normal := hLnormal
  have hindex : L.index = L.relIndex hyp.D := by
    rw [← Subgroup.relIndex_top_right, ← hsup, Subgroup.relIndex_sup_left]
  rw [hindex]
  exact hyp.D_odd.of_dvd_nat (Subgroup.relIndex_dvd_card L hyp.D)

/-- For the source subgroup `L = ⟨I⟩`, the restricted double
transitivity proved above gives Peterfalvi factorization `G = LD`. -/
theorem involutionClosure_sup_D_eq_top :
    involutionClosure G ⊔ hyp.D = ⊤ := by
  have htL : hyp.t ∈ involutionClosure G := by
    apply Subgroup.subset_closure
    exact ⟨hyp.t_sq, hyp.t_ne_one⟩
  have hLtwo : IsMultiplyPretransitive (involutionClosure G) Omega 2 :=
    hyp.subgroup_isMultiplyPretransitive_two
      (involutionClosure G) hyp.Q_le_involutionClosure htL
  exact hyp.sup_D_eq_top_of_two_pretransitive
    (involutionClosure G) hLtwo

/-- The source subgroup `L = ⟨I⟩` has odd index in `G`. -/
theorem involutionClosure_odd_index :
    Odd (involutionClosure G).index :=
  hyp.odd_index_of_sup_D_eq_top (involutionClosure G)
    (involutionClosure_normal G) hyp.involutionClosure_sup_D_eq_top

/-- **Peterfalvi Part II, Ch. I §3, Proposition 2.**  If `G` is not
simple, then the conclusion of Suzuki Theorem A holds for `G`.

Take `L = ⟨I⟩`.  The preceding results construct it as a proper normal
subgroup, prove `Q ≤ L`, restrict (A1)--(A3) to `L`, and prove both `G = LD`
and oddness of `[G:L]`.  Induction therefore supplies a normal odd-index
subgroup `result.L ≤ L` with a concrete target.

The source leaves implicit why this returned subgroup is all of `L`.  Its
quotient has odd order, so for every involution `z ∈ L`, the standard fact
`z ^ [L : result.L] ∈ result.L` and oddness of the index give `z ∈ result.L`.
Since `L` is generated by all ambient involutions, `result.L = ⊤`.  The
concrete target then transports along the canonical equivalence `L ≃* ⊤`.
No simplicity or classification statement is assumed in this step. -/
theorem theoremAConclusion_of_not_simple (hG : ¬ IsSimpleGroup G)
    (inductionHypothesis : TheoremAInductionBelow G Omega) :
    Nonempty (TheoremAConclusion G Omega) := by
  obtain ⟨hLnormal, _, hLproper⟩ :=
    hyp.involutionClosure_proper_normal_of_not_simple hG
  let L : Subgroup G := involutionClosure G
  change L.Normal at hLnormal
  change L ≠ ⊤ at hLproper
  have hLodd : Odd L.index := by
    change Odd (involutionClosure G).index
    exact hyp.involutionClosure_odd_index
  have hQL : hyp.Q ≤ L := by
    change hyp.Q ≤ involutionClosure G
    exact hyp.Q_le_involutionClosure
  have htL : hyp.t ∈ L := by
    change hyp.t ∈ involutionClosure G
    apply Subgroup.subset_closure
    exact ⟨hyp.t_sq, hyp.t_ne_one⟩
  let hHypL : Hypothesis L Omega :=
    hyp.subgroupHypothesis L hQL htL
  have hsmall : Nat.card L < Nat.card G :=
    Subgroup.card_lt_card_of_ne_top hLproper
  obtain ⟨result⟩ := inductionHypothesis hsmall hHypL
  letI : result.L.Normal := result.normal
  have hresultLtop : result.L = ⊤ := by
    apply top_unique
    intro l _
    exact Subgroup.closure_induction
      (p := fun x hx => (⟨x, hx⟩ : L) ∈ result.L)
      (fun u hu => by
        let z : L := ⟨u, Subgroup.subset_closure hu⟩
        change z ∈ result.L
        have hz2 : z ^ 2 = 1 := by
          apply Subtype.ext
          exact hu.1
        obtain ⟨j, hj⟩ := result.oddIndex
        have hzpow : z ^ result.L.index ∈ result.L :=
          Subgroup.pow_index_mem result.L z
        have heq : z ^ result.L.index = z := by
          rw [hj, pow_add, pow_mul, hz2]
          simp
        rwa [heq] at hzpow)
      result.L.one_mem
      (fun _ _ _ _ hx hy => result.L.mul_mem hx hy)
      (fun _ _ hx => result.L.inv_mem hx)
      l.2
  have targetTop :
      TheoremATarget (G := L) (Omega := Omega) (⊤ : Subgroup L) := by
    rw [← hresultLtop]
    exact result.target
  exact ⟨
    { L := L
      normal := hLnormal
      oddIndex := hLodd
      target := TheoremATarget.ofTop L targetTop }⟩

end

end Hypothesis

end OddOrder.Peterfalvi.Appendices.Suzuki
