/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.GroupTheory.DoubleCoset
import OddOrder.Peterfalvi.Appendices.Suzuki.DistinguishedInvolution
import OddOrder.Peterfalvi.Appendices.Suzuki.KCyclic

/-!
# Peterfalvi Part II, Ch. I §3: the order-three rank-one subgroup

T. Peterfalvi, *Character Theory for the Odd Order Theorem* (LMS LNS 272,
2000), Part II, Ch. I §3, Lemma 4, p. 107.

Assume that the product of the distinguished involution `s` and `t` has
order three.  The computational first half of Lemma 4 proves the braid
relation `tst = sts`, uses the `K`-parametrization of the involutions of
`Q0`, and obtains the two-cell decomposition

`<Q0, K, t> = Q0 K union Q0 K t Q0`.

The printed display `t Q0 t subset Q0 K t Q0` on p. 107 omits the sharp:
it cannot include `1 in Q0`, since `t * 1 * t = 1` belongs to the small
cell.  The source computation proves `t Q0# t subset Q0 K t Q0`; below we
state both that sharp version and the unit-inclusive union version.
-/

set_option autoImplicit false

namespace OddOrder.Peterfalvi.Appendices.Suzuki

open scoped Pointwise

section /- Lemma 4: the braid relation -/

variable {G : Type*} [Group G]

/-- **Peterfalvi Part II, Ch. I §3, Lemma 4** (p. 107), the braid
relation used in the rank-one computation: if `s` and `t` are involutions
and `st` has order three, then `tst = sts`. -/
lemma braid_of_involutions_of_orderOf_mul_eq_three {s t : G}
    (hs : s ^ 2 = 1) (ht : t ^ 2 = 1)
    (hst : orderOf (s * t) = 3) :
    t * s * t = s * t * s := by
  have hs' : s * s = 1 := by simpa [pow_two] using hs
  have ht' : t * t = 1 := by simpa [pow_two] using ht
  have hcube : (s * t) ^ 3 = 1 := by
    rw [← hst]
    exact pow_orderOf_eq_one _
  have hfour : t * s * t * s = s * t := by
    calc
      t * s * t * s = s * ((s * t) ^ 3) * t := by
        rw [pow_three]
        calc
          t * s * t * s = (s * s) * t * s * t * s * (t * t) := by
            rw [hs', ht', one_mul, mul_one]
          _ = s * ((s * t) * ((s * t) * (s * t))) * t := by group
      _ = s * t := by rw [hcube, mul_one]
  calc
    t * s * t = (t * s * t * s) * s := by
      calc
        t * s * t = t * s * t * (s * s) := by rw [hs', mul_one]
        _ = (t * s * t * s) * s := by group
    _ = s * t * s := by rw [hfour]

end

namespace Hypothesis

variable {G Omega : Type*} [Group G] [MulAction G Omega] [Finite G]
  (hyp : Hypothesis G Omega)

include hyp

/-! ## The small cell `Q0 K` -/

/-- The small-cell subgroup `B = <Q0, K>`. -/
def orderThreeBorel : Subgroup G := hyp.Q0 ⊔ hyp.K

/-- The subgroup generated by `Q0`, `K`, and `t`, written as
`<B, t>`. -/
def orderThreeGeneratedSubgroup : Subgroup G :=
  hyp.orderThreeBorel ⊔ Subgroup.zpowers hyp.t

/-- The candidate two-cell carrier `B union B t B`. -/
def orderThreeBruhatSet : Set G :=
  (hyp.orderThreeBorel : Set G) ∪
    DoubleCoset.doubleCoset hyp.t hyp.orderThreeBorel hyp.orderThreeBorel

/-- `K` normalizes `Q0`, because `K <= D` and `D` normalizes `Q0`. -/
lemma K_le_normalizer_Q0 :
    hyp.K ≤ Subgroup.normalizer (hyp.Q0 : Set G) := by
  intro k hkK
  have hkD : k ∈ hyp.D := hyp.K_le_D hkK
  rw [Subgroup.mem_normalizer_iff]
  intro q
  constructor
  · exact fun hq => hyp.conj_mem_Q0_of_mem_D hkD hq
  · intro hconj
    have hback := hyp.conj_mem_Q0_of_mem_D (hyp.D.inv_mem hkD) hconj
    simpa [mul_assoc] using hback

/-- The small cell really is the pointwise product `Q0 K`. -/
lemma coe_orderThreeBorel :
    (hyp.orderThreeBorel : Set G) = (hyp.Q0 : Set G) * (hyp.K : Set G) := by
  exact Subgroup.coe_mul_of_right_le_normalizer_left hyp.Q0 hyp.K
    hyp.K_le_normalizer_Q0


/-- The big cell `B t B` is exactly the source's `Q0 K t Q0`.
The final `K` factor can be moved to the left of `t`: for
`b ∈ B`, `q ∈ Q0`, and `k ∈ K`,

`b t (q k) = (b k⁻¹) t (k⁻¹ q k)`.

Here `b k⁻¹ ∈ B` and `k⁻¹ q k ∈ Q0`, since `K ≤ D`
normalizes `Q0`. -/
lemma orderThreeBigCell_eq_Q0K_t_Q0 :
    DoubleCoset.doubleCoset hyp.t hyp.orderThreeBorel
        hyp.orderThreeBorel =
      ((hyp.Q0 : Set G) * (hyp.K : Set G)) * {hyp.t} *
        (hyp.Q0 : Set G) := by
  ext x
  constructor
  · intro hx
    rcases DoubleCoset.mem_doubleCoset.mp hx with
      ⟨b, hbB, c, hcB, rfl⟩
    have hc : c ∈ (hyp.Q0 : Set G) * (hyp.K : Set G) := by
      rw [← hyp.coe_orderThreeBorel]
      exact hcB
    rcases Set.mem_mul.mp hc with ⟨q, hqQ0, k, hkK, rfl⟩
    have hkKSet : k ∈ hyp.KSet := by
      change k ∈ (hyp.K : Set G) at hkK
      rwa [hyp.coe_K] at hkK
    have hleftB : b * k⁻¹ ∈ hyp.orderThreeBorel :=
      hyp.orderThreeBorel.mul_mem hbB
        ((show hyp.K ≤ hyp.orderThreeBorel from le_sup_right)
          (hyp.K.inv_mem hkK))
    have hleft : b * k⁻¹ ∈
        (hyp.Q0 : Set G) * (hyp.K : Set G) := by
      rw [← hyp.coe_orderThreeBorel]
      exact hleftB
    have hright : k⁻¹ * q * k ∈ hyp.Q0 := by
      simpa only [inv_inv] using
        hyp.conj_mem_Q0_of_mem_D (hyp.D.inv_mem (hyp.K_le_D hkK)) hqQ0
    have heq : b * hyp.t * (q * k) =
        (b * k⁻¹) * hyp.t * (k⁻¹ * q * k) := by
      calc
        b * hyp.t * (q * k) = b * (hyp.t * k) * (k⁻¹ * q * k) := by
          group
        _ = (b * k⁻¹) * hyp.t * (k⁻¹ * q * k) := by
          rw [hyp.t_mul_eq_of_mem_KSet hkKSet]
          group
    rw [heq]
    exact Set.mul_mem_mul
      (Set.mul_mem_mul hleft (Set.mem_singleton hyp.t)) hright
  · intro hx
    rcases Set.mem_mul.mp hx with ⟨bt, hbt, q, hqQ0, hbtq⟩
    rcases Set.mem_mul.mp hbt with ⟨b, hb, z, hz, hbz⟩
    have hz' : z = hyp.t := Set.mem_singleton_iff.mp hz
    subst z
    have hbB : b ∈ hyp.orderThreeBorel := by
      change b ∈ (hyp.orderThreeBorel : Set G)
      rwa [hyp.coe_orderThreeBorel]
    have hqB : q ∈ hyp.orderThreeBorel :=
      (show hyp.Q0 ≤ hyp.orderThreeBorel from le_sup_left) hqQ0
    apply DoubleCoset.mem_doubleCoset.mpr
    refine ⟨b, hbB, q, hqB, ?_⟩
    rw [← hbtq, ← hbz]

/-! ## The source computation `t Q0# t subset B t B` -/

/-- **Peterfalvi Part II, Ch. I §3, Lemma 4** (p. 107), the displayed
rank-one computation.  For `u in Q0#`, write `u = k^-1 s k` by section 1
Proposition 3.  Then

`t u t = k (t s t) k^-1
       = k (s t s) k^-1
       = (k s k^-1) k^2 t (k s k^-1)`,

whose two outer factors lie in `B = Q0 K`. -/
lemma t_mul_Q0_mul_t_mem_bigCell
    (hst : orderOf (hyp.distinguishedInvolution * hyp.t) = 3)
    {u : G} (huQ0 : u ∈ hyp.Q0) (hu1 : u ≠ 1) :
    hyp.t * u * hyp.t ∈
      DoubleCoset.doubleCoset hyp.t hyp.orderThreeBorel
        hyp.orderThreeBorel := by
  let s := hyp.distinguishedInvolution
  have hsH : s ∈ hyp.H := hyp.distinguishedInvolution_mem_H
  have hs2 : s ^ 2 = 1 := hyp.distinguishedInvolution_sq
  have hs1 : s ≠ 1 := hyp.distinguishedInvolution_ne_one
  have huI : u ∈ {x : G | x ^ 2 = 1 ∧ x ≠ 1 ∧ x ∈ hyp.H} :=
    ⟨huQ0.1, hu1, huQ0.2⟩
  rw [← hyp.image_conj_KSet_eq_involutions_H hsH hs2 hs1] at huI
  obtain ⟨k, hkKSet, rfl⟩ := huI
  have hkK : k ∈ hyp.K := by
    change k ∈ (hyp.K : Set G)
    rw [hyp.coe_K]
    exact hkKSet
  have hsQ0 : s ∈ hyp.Q0 := ⟨hs2, hsH⟩
  have hksQ0 : k * s * k⁻¹ ∈ hyp.Q0 :=
    hyp.conj_mem_Q0_of_mem_D (hyp.K_le_D hkK) hsQ0
  have hk2K : k ^ 2 ∈ hyp.K := hyp.K.pow_mem hkK 2
  have hksB : k * s * k⁻¹ ∈ hyp.orderThreeBorel :=
    (show hyp.Q0 ≤ hyp.orderThreeBorel from le_sup_left) hksQ0
  have hleftB : (k * s * k⁻¹) * k ^ 2 ∈ hyp.orderThreeBorel :=
    hyp.orderThreeBorel.mul_mem hksB
      ((show hyp.K ≤ hyp.orderThreeBorel from le_sup_right) hk2K)
  have hbraid : hyp.t * s * hyp.t = s * hyp.t * s :=
    braid_of_involutions_of_orderOf_mul_eq_three hs2 hyp.t_sq hst
  have hrelation :
      hyp.t * (k⁻¹ * s * k) * hyp.t =
        ((k * s * k⁻¹) * k ^ 2) * hyp.t * (k * s * k⁻¹) := by
    calc
      hyp.t * (k⁻¹ * s * k) * hyp.t =
          k * (hyp.t * s * hyp.t) * k⁻¹ :=
        hyp.t_conj_conj_of_mem_KSet hkKSet
      _ = k * (s * hyp.t * s) * k⁻¹ := by rw [hbraid]
      _ = k * s * (k * hyp.t * k) * s * k⁻¹ := by
        rw [hyp.mul_t_mul_self_of_mem_KSet hkKSet]
        group
      _ = ((k * s * k⁻¹) * k ^ 2) * hyp.t * (k * s * k⁻¹) := by
        rw [pow_two]
        group
  exact DoubleCoset.mem_doubleCoset.mpr
    ⟨(k * s * k⁻¹) * k ^ 2, hleftB,
      k * s * k⁻¹, hksB, hrelation⟩

/-- The unit-inclusive correction of the source's printed display:
`t Q0 t` lies in `B union B t B`; the identity member lands in `B`, while
the sharp members land in the big cell by the preceding computation. -/
lemma t_mul_Q0_mul_t_mem_bruhatSet
    (hst : orderOf (hyp.distinguishedInvolution * hyp.t) = 3)
    {u : G} (huQ0 : u ∈ hyp.Q0) :
    hyp.t * u * hyp.t ∈ hyp.orderThreeBruhatSet := by
  by_cases hu1 : u = 1
  · subst u
    left
    simp [mul_one, ← pow_two, hyp.t_sq]
  · right
    exact hyp.t_mul_Q0_mul_t_mem_bigCell hst huQ0 hu1


/-! ## Closure of the two cells -/

/-- The union `B union B t B` is stable under multiplication on the left
by the small cell `B`. -/
lemma orderThreeBorel_mul_mem_bruhatSet {b x : G}
    (hb : b ∈ hyp.orderThreeBorel) (hx : x ∈ hyp.orderThreeBruhatSet) :
    b * x ∈ hyp.orderThreeBruhatSet := by
  change x ∈ (hyp.orderThreeBorel : Set G) ∪
      DoubleCoset.doubleCoset hyp.t hyp.orderThreeBorel
        hyp.orderThreeBorel at hx
  change b * x ∈ (hyp.orderThreeBorel : Set G) ∪
      DoubleCoset.doubleCoset hyp.t hyp.orderThreeBorel
        hyp.orderThreeBorel
  rcases hx with hxB | hxBig
  · exact Or.inl (hyp.orderThreeBorel.mul_mem hb hxB)
  · rcases DoubleCoset.mem_doubleCoset.mp hxBig with
      ⟨c, hc, d, hd, rfl⟩
    exact Or.inr (DoubleCoset.mem_doubleCoset.mpr
      ⟨b * c, hyp.orderThreeBorel.mul_mem hb hc, d, hd, by group⟩)

/-- The union `B union B t B` is stable under multiplication on the right
by the small cell `B`. -/
lemma mul_orderThreeBorel_mem_bruhatSet {x b : G}
    (hx : x ∈ hyp.orderThreeBruhatSet) (hb : b ∈ hyp.orderThreeBorel) :
    x * b ∈ hyp.orderThreeBruhatSet := by
  change x ∈ (hyp.orderThreeBorel : Set G) ∪
      DoubleCoset.doubleCoset hyp.t hyp.orderThreeBorel
        hyp.orderThreeBorel at hx
  change x * b ∈ (hyp.orderThreeBorel : Set G) ∪
      DoubleCoset.doubleCoset hyp.t hyp.orderThreeBorel
        hyp.orderThreeBorel
  rcases hx with hxB | hxBig
  · exact Or.inl (hyp.orderThreeBorel.mul_mem hxB hb)
  · rcases DoubleCoset.mem_doubleCoset.mp hxBig with
      ⟨c, hc, d, hd, rfl⟩
    exact Or.inr (DoubleCoset.mem_doubleCoset.mpr
      ⟨c, hc, d * b, hyp.orderThreeBorel.mul_mem hd hb, by group⟩)

/-- The unit-inclusive source computation extends from `Q0` to all of
`B = Q0 K`: conjugating the `K` factor by `t` only inverts it. -/
lemma t_mul_orderThreeBorel_mul_t_mem_bruhatSet
    (hst : orderOf (hyp.distinguishedInvolution * hyp.t) = 3)
    {b : G} (hb : b ∈ hyp.orderThreeBorel) :
    hyp.t * b * hyp.t ∈ hyp.orderThreeBruhatSet := by
  have hb' : b ∈ (hyp.Q0 : Set G) * (hyp.K : Set G) := by
    rw [← hyp.coe_orderThreeBorel]
    exact hb
  rcases Set.mem_mul.mp hb' with ⟨q, hqQ0, k, hkK, rfl⟩
  have hkKSet : k ∈ hyp.KSet := by
    rw [← hyp.coe_K]
    exact hkK
  have hconj := hyp.t_mul_Q0_mul_t_mem_bruhatSet hst hqQ0
  have hkinvB : k⁻¹ ∈ hyp.orderThreeBorel :=
    (show hyp.K ≤ hyp.orderThreeBorel from le_sup_right)
      (hyp.K.inv_mem hkK)
  have heq : hyp.t * (q * k) * hyp.t = (hyp.t * q * hyp.t) * k⁻¹ := by
    calc
      hyp.t * (q * k) * hyp.t = hyp.t * q * (k * hyp.t) := by group
      _ = hyp.t * q * (hyp.t * k⁻¹) := by
        rw [hyp.mul_t_eq_of_mem_KSet hkKSet]
      _ = (hyp.t * q * hyp.t) * k⁻¹ := by group
  rw [heq]
  exact hyp.mul_orderThreeBorel_mem_bruhatSet hconj hkinvB


/-- Under the order-three hypothesis, the two cells form a genuine
subgroup.  This is the source's sentence following the displayed
calculation on p. 107. -/
def orderThreeBruhatSubgroup
    (hst : orderOf (hyp.distinguishedInvolution * hyp.t) = 3) :
    Subgroup G where
  carrier := hyp.orderThreeBruhatSet
  one_mem' := Or.inl hyp.orderThreeBorel.one_mem
  inv_mem' := by
    intro x hx
    change x ∈ (hyp.orderThreeBorel : Set G) ∪
        DoubleCoset.doubleCoset hyp.t hyp.orderThreeBorel
          hyp.orderThreeBorel at hx
    change x⁻¹ ∈ (hyp.orderThreeBorel : Set G) ∪
        DoubleCoset.doubleCoset hyp.t hyp.orderThreeBorel
          hyp.orderThreeBorel
    rcases hx with hxB | hxBig
    · exact Or.inl (hyp.orderThreeBorel.inv_mem hxB)
    · rcases DoubleCoset.mem_doubleCoset.mp hxBig with
        ⟨b, hb, c, hc, rfl⟩
      exact Or.inr (DoubleCoset.mem_doubleCoset.mpr
        ⟨c⁻¹, hyp.orderThreeBorel.inv_mem hc,
          b⁻¹, hyp.orderThreeBorel.inv_mem hb, by
            rw [mul_inv_rev, mul_inv_rev, hyp.t_inv_eq]
            group⟩)
  mul_mem' := by
    intro x y hx hy
    change x ∈ (hyp.orderThreeBorel : Set G) ∪
        DoubleCoset.doubleCoset hyp.t hyp.orderThreeBorel
          hyp.orderThreeBorel at hx
    change y ∈ (hyp.orderThreeBorel : Set G) ∪
        DoubleCoset.doubleCoset hyp.t hyp.orderThreeBorel
          hyp.orderThreeBorel at hy
    rcases hx with hxB | hxBig
    · exact hyp.orderThreeBorel_mul_mem_bruhatSet hxB hy
    · rcases hy with hyB | hyBig
      · exact hyp.mul_orderThreeBorel_mem_bruhatSet (Or.inr hxBig) hyB
      · rcases DoubleCoset.mem_doubleCoset.mp hxBig with
          ⟨a, ha, b, hb, rfl⟩
        rcases DoubleCoset.mem_doubleCoset.mp hyBig with
          ⟨c, hc, d, hd, rfl⟩
        have hmiddle : hyp.t * (b * c) * hyp.t ∈
            hyp.orderThreeBruhatSet :=
          hyp.t_mul_orderThreeBorel_mul_t_mem_bruhatSet hst
            (hyp.orderThreeBorel.mul_mem hb hc)
        have hleft := hyp.orderThreeBorel_mul_mem_bruhatSet ha hmiddle
        have hright := hyp.mul_orderThreeBorel_mem_bruhatSet hleft hd
        simpa only [mul_assoc] using hright

@[simp] lemma coe_orderThreeBruhatSubgroup
    (hst : orderOf (hyp.distinguishedInvolution * hyp.t) = 3) :
    (hyp.orderThreeBruhatSubgroup hst : Set G) = hyp.orderThreeBruhatSet := rfl

/-- The source's exact two-cell equality
`<Q0, K, t> = B union B t B`, represented as an equality between the
generated subgroup and the subgroup just constructed on that carrier. -/
theorem orderThreeGeneratedSubgroup_eq_bruhatSubgroup
    (hst : orderOf (hyp.distinguishedInvolution * hyp.t) = 3) :
    hyp.orderThreeGeneratedSubgroup = hyp.orderThreeBruhatSubgroup hst := by
  apply le_antisymm
  · apply sup_le
    · intro b hb
      exact Or.inl hb
    · rw [Subgroup.zpowers_le]
      exact Or.inr
        (DoubleCoset.mem_doubleCoset_self hyp.orderThreeBorel
          hyp.orderThreeBorel hyp.t)
  · intro x hx
    change x ∈ (hyp.orderThreeBorel : Set G) ∪
        DoubleCoset.doubleCoset hyp.t hyp.orderThreeBorel
          hyp.orderThreeBorel at hx
    rcases hx with hxB | hxBig
    · exact (show hyp.orderThreeBorel ≤ hyp.orderThreeGeneratedSubgroup
        from le_sup_left) hxB
    · rcases DoubleCoset.mem_doubleCoset.mp hxBig with
        ⟨b, hb, c, hc, rfl⟩
      have hb' : b ∈ hyp.orderThreeGeneratedSubgroup :=
        (show hyp.orderThreeBorel ≤ hyp.orderThreeGeneratedSubgroup
          from le_sup_left) hb
      have hc' : c ∈ hyp.orderThreeGeneratedSubgroup :=
        (show hyp.orderThreeBorel ≤ hyp.orderThreeGeneratedSubgroup
          from le_sup_left) hc
      have ht' : hyp.t ∈ hyp.orderThreeGeneratedSubgroup :=
        (show Subgroup.zpowers hyp.t ≤ hyp.orderThreeGeneratedSubgroup
          from le_sup_right) (Subgroup.mem_zpowers hyp.t)
      exact hyp.orderThreeGeneratedSubgroup.mul_mem
        (hyp.orderThreeGeneratedSubgroup.mul_mem hb' ht') hc'


/-- **Peterfalvi Part II, Ch. I §3, Lemma 4** (p. 107), the exact
set-level equality printed after correcting the omitted sharp in the
intermediate display:

`<Q0, K, t> = Q0 K union Q0 K t Q0`. -/
theorem coe_orderThreeGeneratedSubgroup_eq_Q0K_union_Q0KtQ0
    (hst : orderOf (hyp.distinguishedInvolution * hyp.t) = 3) :
    (hyp.orderThreeGeneratedSubgroup : Set G) =
      ((hyp.Q0 : Set G) * (hyp.K : Set G)) ∪
        (((hyp.Q0 : Set G) * (hyp.K : Set G)) * {hyp.t} *
          (hyp.Q0 : Set G)) := by
  rw [hyp.orderThreeGeneratedSubgroup_eq_bruhatSubgroup hst]
  change hyp.orderThreeBruhatSet = _
  rw [orderThreeBruhatSet, hyp.orderThreeBigCell_eq_Q0K_t_Q0,
    hyp.coe_orderThreeBorel]

end Hypothesis

end OddOrder.Peterfalvi.Appendices.Suzuki
