/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Peterfalvi.Appendices.Suzuki.OrderThreePSL
import OddOrder.Peterfalvi.Appendices.Suzuki.CentralizerPSLRoot
import OddOrder.Peterfalvi.Appendices.Suzuki.CentralizerSuzukiRoot
import OddOrder.Peterfalvi.Appendices.Suzuki.CentralizerPSURoot

/-!
# Peterfalvi Part II, Ch. I §3 Lemma 4: the order-three PSL subgroup

T. Peterfalvi, *Character Theory for the Odd Order Theorem* (LMS LNS 272,
2000), Part II, Ch. I §3, Lemma 4, p. 107.

This file completes the induction half of Lemma 4 after the two-cell
calculation in `OrderThreePSL`. The subgroup generated by `Q₀`, `K`, and `t`
acts on the orbit of the ambient base point. The Bruhat decomposition
identifies its point stabilizer with `Q₀ K`, supplies regular `Q₀` coordinates
on the punctured orbit, and yields a faithful doubly transitive action
satisfying hypotheses (A1)--(A3) with `Q₀` and `K` in place of `Q` and `D`.

If `V ≠ 1`, a nonidentity element of `V` cannot lie in the generated
subgroup, so the subgroup is proper without relying on an assumed order
formula. Suzuki's Theorem A therefore applies inductively. The returned
normal odd-index subgroup contains the involution generators and hence is
the whole generated subgroup. Finally, the Suzuki and unitary alternatives
are excluded because their root groups are noncommutative Suzuki 2-groups,
whereas `Q₀` is commutative. The remaining target gives the source conclusion
`⟨Q₀, K, t⟩ ≅ PSL(2,q)` with `q = |Q₀|`.
-/

set_option autoImplicit false

namespace OddOrder.Peterfalvi.Appendices.Suzuki.Hypothesis

open MulAction
open scoped Pointwise LinearAlgebra.Projectivization

universe u v

variable {G : Type u} {Omega : Type v} [Group G] [MulAction G Omega]
  [Finite G]
  (hyp : Hypothesis G Omega)

local notation "B" => hyp.orderThreeBorel
local notation "L" => hyp.orderThreeGeneratedSubgroup

/-- The small cell `B = ⟨Q₀, K⟩` lies in the ambient point stabilizer. -/
lemma orderThreeBorel_le_H : B ≤ hyp.H := by
  rw [orderThreeBorel]
  exact sup_le (hyp.Q0_le_Q.trans hyp.Q_le_H)
    (hyp.K_le_D.trans hyp.D_le_H)

/-- The intersection of the Lemma 4 small cell with `D` is exactly `K`. -/
lemma orderThreeBorel_inf_D_eq_K : B ⊓ hyp.D = hyp.K := by
  apply le_antisymm
  · intro x hx
    have hxB : x ∈ B := hx.1
    change x ∈ (B : Set G) at hxB
    rw [hyp.coe_orderThreeBorel] at hxB
    obtain ⟨q, hq, k, hk, rfl⟩ := hxB
    have hkK : k ∈ hyp.K := hk
    have hqD : q ∈ hyp.D := by
      have hqeq : q = (q * k) * k⁻¹ := by simp
      rw [hqeq]
      exact hyp.D.mul_mem hx.2 (hyp.D.inv_mem (hyp.K_le_D hkK))
    have hqbot : q ∈ hyp.Q ⊓ hyp.D := ⟨hyp.Q0_le_Q hq, hqD⟩
    rw [hyp.Q_inf_D_eq_bot, Subgroup.mem_bot] at hqbot
    simpa [hqbot] using hkK
  · exact le_inf le_sup_right hyp.K_le_D

/-- The root group `Q₀` and complement `K` intersect trivially. -/
lemma orderThreeQ0_inf_K_eq_bot : hyp.Q0 ⊓ hyp.K = ⊥ := by
  rw [eq_bot_iff]
  intro x hx
  have hx' : x ∈ hyp.Q ⊓ hyp.D :=
    ⟨hyp.Q0_le_Q hx.1, hyp.K_le_D hx.2⟩
  rw [hyp.Q_inf_D_eq_bot, Subgroup.mem_bot] at hx'
  exact hx'

/-- The distinguished involution `t` belongs to `⟨Q₀, K, t⟩`. -/
lemma orderThree_t_mem : hyp.t ∈ L := by
  exact (show Subgroup.zpowers hyp.t ≤ L from le_sup_right)
    (Subgroup.mem_zpowers hyp.t)

/-- The root group `Q₀` lies in the generated Lemma 4 subgroup. -/
lemma orderThree_Q0_le : hyp.Q0 ≤ L :=
  le_sup_of_le_left le_sup_left

/-- The complement `K` lies in the generated Lemma 4 subgroup. -/
lemma orderThree_K_le : hyp.K ≤ L :=
  le_sup_of_le_left le_sup_right

/-- **Peterfalvi Part II, Ch. I §3, Lemma 4.** If `V ≠ 1`, the subgroup
`⟨Q₀, K, t⟩` is proper. A nonidentity `v ∈ V` would otherwise lie in the
small cell and hence in `K`; being both centralized and inverted by `t`
would make `v` an involution in the odd-order group `D`. -/
lemma orderThreeGeneratedSubgroup_ne_top
    (hBruhat : (L : Set G) = hyp.orderThreeBruhatSet)
    (hV : hyp.V ≠ ⊥) : L ≠ ⊤ := by
  obtain ⟨⟨v, hvV⟩, hv1sub⟩ := Subgroup.ne_bot_iff_exists_ne_one.mp hV
  have hv1 : v ≠ 1 := fun hv => hv1sub (Subtype.ext hv)
  intro htop
  have hvL : (v : G) ∈ L := by rw [htop]; exact Subgroup.mem_top v
  change (v : G) ∈ (L : Set G) at hvL
  rw [hBruhat, orderThreeBruhatSet] at hvL
  have hvB : v ∈ B := by
    rcases hvL with hvB | hvBig
    · exact hvB
    · obtain ⟨b₁, hb₁, b₂, hb₂, hv⟩ :=
        DoubleCoset.mem_doubleCoset.mp hvBig
      have htH : hyp.t ∈ hyp.H := by
        have hvH : v ∈ hyp.H := hyp.D_le_H (hyp.V_le_D hvV)
        have hb₁H : b₁ ∈ hyp.H := hyp.orderThreeBorel_le_H hb₁
        have hb₂H : b₂ ∈ hyp.H := hyp.orderThreeBorel_le_H hb₂
        have htEq : hyp.t = b₁⁻¹ * v * b₂⁻¹ := by
          rw [hv]
          group
        rw [htEq]
        exact hyp.H.mul_mem
          (hyp.H.mul_mem (hyp.H.inv_mem hb₁H) hvH)
          (hyp.H.inv_mem hb₂H)
      exact (hyp.t_not_mem_H htH).elim
  have hvK : v ∈ hyp.K := by
    have hvBD : v ∈ B ⊓ hyp.D := ⟨hvB, hyp.V_le_D hvV⟩
    rwa [hyp.orderThreeBorel_inf_D_eq_K] at hvBD
  have hvKSet : v ∈ hyp.KSet := by
    rw [← hyp.coe_K]
    exact hvK
  have hvcomm : Commute v hyp.t := hyp.commute_t_of_mem_V hvV
  have hvinv : hyp.t * v * hyp.t = v⁻¹ := hvKSet.2
  have hvfix : hyp.t * v * hyp.t = v := by
    rw [← hvcomm.eq]
    have htt : hyp.t * hyp.t = 1 := by
      simpa [pow_two] using hyp.t_sq
    simp [mul_assoc, htt]
  have hvInvEq : v = v⁻¹ := hvfix.symm.trans hvinv
  have hv2 : v ^ 2 = 1 := by
    rw [pow_two]
    exact (congrArg (fun z : G => z * v) hvInvEq).trans (inv_mul_cancel v)
  exact hv1 (eq_one_of_sq_eq_one_of_odd_card hyp.D_odd
    (hyp.V_le_D hvV) hv2)


/-- The orbit of the ambient base point under the Lemma 4 subgroup. -/
abbrev OrderThreeOrbit := MulAction.orbit L hyp.basept

/-- The ambient base point, regarded as a member of the generated orbit. -/
def orderThreeBasept : hyp.OrderThreeOrbit :=
  ⟨hyp.basept, MulAction.mem_orbit_self hyp.basept⟩

/-- On the generated orbit, the stabilizer of the base point is `Q₀ K`. -/
lemma orderThreeBorel_eq_stabilizer
    (hBruhat : (L : Set G) = hyp.orderThreeBruhatSet) :
    hyp.orderThreeBorel.subgroupOf L =
      stabilizer L hyp.orderThreeBasept := by
  ext l
  rw [Subgroup.mem_subgroupOf, mem_stabilizer_iff]
  constructor
  · intro hlB
    apply Subtype.ext
    change (l : G) • hyp.basept = hyp.basept
    exact hyp.smul_basept_eq_of_mem_H (hyp.orderThreeBorel_le_H hlB)
  · intro hfix
    have hlH : (l : G) ∈ hyp.H := by
      rw [hyp.H_def, mem_stabilizer_iff]
      exact congrArg Subtype.val hfix
    have hlL : (l : G) ∈ L := l.2
    change (l : G) ∈ (L : Set G) at hlL
    rw [hBruhat, orderThreeBruhatSet] at hlL
    rcases hlL with hlB | hlBig
    · exact hlB
    · obtain ⟨b₁, hb₁, b₂, hb₂, hl⟩ :=
        DoubleCoset.mem_doubleCoset.mp hlBig
      exfalso
      apply hyp.t_not_mem_H
      have hb₁H : b₁ ∈ hyp.H := hyp.orderThreeBorel_le_H hb₁
      have hb₂H : b₂ ∈ hyp.H := hyp.orderThreeBorel_le_H hb₂
      have htEq : hyp.t = b₁⁻¹ * (l : G) * b₂⁻¹ := by
        rw [hl]
        group
      rw [htEq]
      exact hyp.H.mul_mem
        (hyp.H.mul_mem (hyp.H.inv_mem hb₁H) hlH)
        (hyp.H.inv_mem hb₂H)

/-- The two-point stabilizer in the restricted action is the subgroup `K`. -/
lemma orderThreeD_def
    (_hBruhat : (L : Set G) = hyp.orderThreeBruhatSet) :
    hyp.K.subgroupOf L =
      hyp.orderThreeBorel.subgroupOf L ⊓
        (hyp.orderThreeBorel.subgroupOf L).map
          (MulAut.conj
            (⟨hyp.t, hyp.orderThree_t_mem⟩ : L)).toMonoidHom := by
  ext l
  rw [Subgroup.mem_inf, Subgroup.mem_subgroupOf, Subgroup.mem_map_equiv,
    MulAut.conj_symm_apply]
  change (l : G) ∈ hyp.K ↔
    (l : G) ∈ B ∧ hyp.t⁻¹ * (l : G) * hyp.t ∈ B
  constructor
  · intro hlK
    have hlB : (l : G) ∈ B :=
      (show hyp.K ≤ hyp.orderThreeBorel from le_sup_right) hlK
    refine ⟨hlB, ?_⟩
    have hlKSet : (l : G) ∈ hyp.KSet := by
      rw [← hyp.coe_K]
      exact hlK
    have hconj : hyp.t⁻¹ * (l : G) * hyp.t = (l : G)⁻¹ := by
      rw [hyp.t_inv_eq]
      exact hlKSet.2
    rw [hconj]
    exact hyp.orderThreeBorel.inv_mem hlB
  · rintro ⟨hlB, hconjB⟩
    have hlH : (l : G) ∈ hyp.H := hyp.orderThreeBorel_le_H hlB
    have hconjH : hyp.t⁻¹ * (l : G) * hyp.t ∈ hyp.H :=
      hyp.orderThreeBorel_le_H hconjB
    have hlD : (l : G) ∈ hyp.D := hyp.mem_D_iff.mpr ⟨hlH, hconjH⟩
    have hlBD : (l : G) ∈ B ⊓ hyp.D := ⟨hlB, hlD⟩
    rwa [hyp.orderThreeBorel_inf_D_eq_K] at hlBD

/-- The small cell `Q₀ K` normalizes its root group `Q₀`. -/
lemma orderThree_Q0_normal_in_B
    (b : G) (hb : b ∈ B) (q : G) (hq : q ∈ hyp.Q0) :
    b * q * b⁻¹ ∈ hyp.Q0 := by
  have hBnorm : B ≤ Subgroup.normalizer (hyp.Q0 : Set G) := by
    rw [orderThreeBorel]
    apply sup_le
    · exact Subgroup.le_normalizer
    · exact hyp.K_le_normalizer_Q0
  exact (Subgroup.mem_normalizer_iff.mp (hBnorm hb) q).mp hq

/-- The pointwise product `Q₀ K` is the entire small-cell subgroup. -/
lemma orderThree_Q0_mul_K_eq_B :
    (hyp.Q0 : Set G) * (hyp.K : Set G) = (B : Set G) := by
  exact hyp.coe_orderThreeBorel.symm

/-- The root group `Q₀` has even order. -/
lemma orderThree_Q0_even : Even (Nat.card hyp.Q0) := by
  exact even_card_of_sq_eq_one_mem
    (K := hyp.Q0)
    ⟨hyp.distinguishedInvolution_sq,
      hyp.distinguishedInvolution_mem_H⟩
    hyp.distinguishedInvolution_sq hyp.distinguishedInvolution_ne_one

/-- The complement `K`, as a subgroup of `D`, has odd order. -/
lemma orderThree_K_odd : Odd (Nat.card hyp.K) :=
  hyp.D_odd.of_dvd_nat (Subgroup.card_dvd_of_le hyp.K_le_D)

/-- The ambient four-subgroup from (A3) lies in `Q₀`. -/
lemma exists_four_subgroup_le_Q0 :
    ∃ E : Subgroup G, E ≤ hyp.Q0 ∧ Nat.card E = 4 ∧
      ∀ x ∈ E, x ^ 2 = 1 := by
  obtain ⟨E, hEQ, hE4, hEsq⟩ := hyp.exists_four_subgroup_le_Q
  refine ⟨E, ?_, hE4, hEsq⟩
  intro x hx
  exact ⟨hEsq x hx, hyp.Q_le_H (hEQ hx)⟩



/-- **Peterfalvi Part II, Ch. I §3, Lemma 4.** The group `Q₀` acts
regularly on the generated orbit with its base point removed. -/
noncomputable def orderThreeQ0RegularEquiv
    (hBruhat : (L : Set G) = hyp.orderThreeBruhatSet) :
    hyp.Q0 ≃ {ω : hyp.OrderThreeOrbit // ω ≠ hyp.orderThreeBasept} :=
  Equiv.ofBijective
    (fun q =>
      ⟨⟨(q : G) • (hyp.t • hyp.basept), by
          refine ⟨
            (⟨(q : G) * hyp.t,
              hyp.orderThreeGeneratedSubgroup.mul_mem (hyp.orderThree_Q0_le q.2)
                hyp.orderThree_t_mem⟩ : L), ?_⟩
          simp [mul_smul]⟩,
        by
          intro heq
          exact hyp.Q_smul_t_basept_ne (hyp.Q0_le_Q q.2)
            (congrArg Subtype.val heq)⟩)
    (by
      constructor
      · rintro ⟨x, hx⟩ ⟨y, hy⟩ hxy
        simp only [Subtype.mk.injEq] at hxy ⊢
        have hst : y⁻¹ * x ∈ stabilizer G (hyp.t • hyp.basept) := by
          rw [mem_stabilizer_iff, mul_smul, hxy, inv_smul_smul]
        have hQ : y⁻¹ * x ∈ hyp.Q :=
          hyp.Q.mul_mem (hyp.Q.inv_mem (hyp.Q0_le_Q hy))
            (hyp.Q0_le_Q hx)
        have hD : y⁻¹ * x ∈ hyp.D := by
          rw [hyp.D_def]
          exact Subgroup.mem_inf.mpr
            ⟨hyp.Q_le_H hQ, hyp.stabilizer_t_basept ▸ hst⟩
        have hbot : y⁻¹ * x ∈ hyp.Q ⊓ hyp.D := ⟨hQ, hD⟩
        rw [hyp.Q_inf_D_eq_bot, Subgroup.mem_bot] at hbot
        exact (inv_mul_eq_one.mp hbot).symm
      · rintro ⟨ω, hω⟩
        obtain ⟨l, hl⟩ := ω.2
        have hlL : (l : G) ∈ L := l.2
        change (l : G) ∈ (L : Set G) at hlL
        rw [hBruhat, orderThreeBruhatSet] at hlL
        rcases hlL with hlB | hlBig
        · exfalso
          apply hω
          apply Subtype.ext
          calc
            (ω : Omega) = (l : G) • hyp.basept := hl.symm
            _ = hyp.basept :=
              hyp.smul_basept_eq_of_mem_H
                (hyp.orderThreeBorel_le_H hlB)
        · obtain ⟨b₁, hb₁, b₂, hb₂, hlval⟩ :=
            DoubleCoset.mem_doubleCoset.mp hlBig
          have hb₁prod : b₁ ∈ (hyp.Q0 : Set G) * (hyp.K : Set G) := by
            rw [← hyp.coe_orderThreeBorel]
            exact hb₁
          obtain ⟨q, hq, k, hk, hb₁eq⟩ := hb₁prod
          change q * k = b₁ at hb₁eq
          refine ⟨⟨q, hq⟩, ?_⟩
          apply Subtype.ext
          apply Subtype.ext
          calc
            q • (hyp.t • hyp.basept)
                = (q * k * hyp.t * b₂) • hyp.basept := by
                    rw [mul_smul, mul_smul, mul_smul,
                      hyp.smul_basept_eq_of_mem_H
                        (hyp.orderThreeBorel_le_H hb₂),
                      hyp.smul_t_basept_eq_of_mem_D (hyp.K_le_D hk)]
            _ = (l : G) • hyp.basept := by rw [hb₁eq, ← hlval]
            _ = ω := hl)

/-- **Peterfalvi Part II, Ch. I §3, Lemma 4.** The generated subgroup
acts doubly transitively on the orbit of the base point. -/
theorem orderThree_isMultiplyPretransitive_two
    (hBruhat : (L : Set G) = hyp.orderThreeBruhatSet) :
    IsMultiplyPretransitive L hyp.OrderThreeOrbit 2 := by
  rw [is_two_pretransitive_iff]
  intro a b c d hab hcd
  obtain ⟨la, hla⟩ :=
    MulAction.exists_smul_eq L hyp.orderThreeBasept a
  obtain ⟨lc, hlc⟩ :=
    MulAction.exists_smul_eq L hyp.orderThreeBasept c
  have hb' : la⁻¹ • b ≠ hyp.orderThreeBasept := by
    intro heq
    apply hab
    calc
      a = la • hyp.orderThreeBasept := hla.symm
      _ = la • (la⁻¹ • b) := by rw [heq]
      _ = b := smul_inv_smul la b
  have hd' : lc⁻¹ • d ≠ hyp.orderThreeBasept := by
    intro heq
    apply hcd
    calc
      c = lc • hyp.orderThreeBasept := hlc.symm
      _ = lc • (lc⁻¹ • d) := by rw [heq]
      _ = d := smul_inv_smul lc d
  obtain ⟨qb, hqb⟩ :=
    (hyp.orderThreeQ0RegularEquiv hBruhat).surjective
      ⟨la⁻¹ • b, hb'⟩
  obtain ⟨qd, hqd⟩ :=
    (hyp.orderThreeQ0RegularEquiv hBruhat).surjective
      ⟨lc⁻¹ • d, hd'⟩
  have hqb' :
      (⟨(qb : G) • (hyp.t • hyp.basept), by
          refine ⟨
            (⟨(qb : G) * hyp.t,
              hyp.orderThreeGeneratedSubgroup.mul_mem (hyp.orderThree_Q0_le qb.2)
                hyp.orderThree_t_mem⟩ : L), ?_⟩
          simp [mul_smul]⟩ : hyp.OrderThreeOrbit) = la⁻¹ • b :=
    congrArg Subtype.val hqb
  have hqd' :
      (⟨(qd : G) • (hyp.t • hyp.basept), by
          refine ⟨
            (⟨(qd : G) * hyp.t,
              hyp.orderThreeGeneratedSubgroup.mul_mem (hyp.orderThree_Q0_le qd.2)
                hyp.orderThree_t_mem⟩ : L), ?_⟩
          simp [mul_smul]⟩ : hyp.OrderThreeOrbit) = lc⁻¹ • d :=
    congrArg Subtype.val hqd
  let qL : L :=
    ⟨(qd : G) * (qb : G)⁻¹,
      hyp.orderThreeGeneratedSubgroup.mul_mem (hyp.orderThree_Q0_le qd.2)
        (hyp.orderThreeGeneratedSubgroup.inv_mem (hyp.orderThree_Q0_le qb.2))⟩
  refine ⟨lc * qL * la⁻¹, ?_, ?_⟩
  · rw [mul_smul, mul_smul]
    have hla' : la⁻¹ • a = hyp.orderThreeBasept := by
      rw [← hla]
      exact inv_smul_smul la hyp.orderThreeBasept
    rw [hla']
    have hqH : (qL : G) ∈ hyp.H :=
      hyp.Q_le_H (hyp.Q.mul_mem (hyp.Q0_le_Q qd.2)
        (hyp.Q.inv_mem (hyp.Q0_le_Q qb.2)))
    apply Subtype.ext
    change (lc : G) • ((qL : G) • hyp.basept) = (c : Omega)
    rw [hyp.smul_basept_eq_of_mem_H hqH]
    exact congrArg Subtype.val hlc
  · rw [mul_smul, mul_smul]
    have hqmap : qL • (la⁻¹ • b) = lc⁻¹ • d := by
      rw [← hqb', ← hqd']
      apply Subtype.ext
      change ((qd : G) * (qb : G)⁻¹) •
          ((qb : G) • (hyp.t • hyp.basept)) =
        (qd : G) • (hyp.t • hyp.basept)
      rw [mul_smul, inv_smul_smul]
    rw [hqmap, smul_inv_smul]


/-- **Peterfalvi Part II, Ch. I §3, Lemma 4.** The generated subgroup
acts faithfully on its orbit. The proof uses `C_Q(k) = 1` for `1 ≠ k ∈ K`. -/
theorem orderThree_faithfulSMul
    (hBruhat : (L : Set G) = hyp.orderThreeBruhatSet) :
    FaithfulSMul L hyp.OrderThreeOrbit := by
  rw [faithfulSMul_iff]
  intro g hg
  have hgBase : g • hyp.orderThreeBasept = hyp.orderThreeBasept :=
    hg hyp.orderThreeBasept
  have hgBsub : g ∈ hyp.orderThreeBorel.subgroupOf L := by
    rw [hyp.orderThreeBorel_eq_stabilizer hBruhat]
    exact mem_stabilizer_iff.mpr hgBase
  have hgB : (g : G) ∈ B := hgBsub
  let tPoint : hyp.OrderThreeOrbit :=
    ⟨hyp.t • hyp.basept,
      ⟨(⟨hyp.t, hyp.orderThree_t_mem⟩ : L), rfl⟩⟩
  have hgtPoint := hg tPoint
  have hgt : (g : G) • (hyp.t • hyp.basept) =
      hyp.t • hyp.basept := congrArg Subtype.val hgtPoint
  have hgD : (g : G) ∈ hyp.D := by
    rw [hyp.D_eq_stabilizer_inf, Subgroup.mem_inf]
    exact ⟨hyp.smul_basept_eq_of_mem_H
      (hyp.orderThreeBorel_le_H hgB), hgt⟩
  have hgK : (g : G) ∈ hyp.K := by
    have hgBD : (g : G) ∈ B ⊓ hyp.D := ⟨hgB, hgD⟩
    rwa [hyp.orderThreeBorel_inf_D_eq_K] at hgBD
  apply Subtype.ext
  by_contra hg1
  have hgKSet : (g : G) ∈ hyp.KSet := by
    rw [← hyp.coe_K]
    exact hgK
  let s := hyp.distinguishedInvolution
  have hsQ0 : s ∈ hyp.Q0 :=
    ⟨hyp.distinguishedInvolution_sq,
      hyp.distinguishedInvolution_mem_H⟩
  let sPoint : hyp.OrderThreeOrbit :=
    ⟨s • (hyp.t • hyp.basept),
      ⟨(⟨s * hyp.t,
        hyp.orderThreeGeneratedSubgroup.mul_mem (hyp.orderThree_Q0_le hsQ0)
          hyp.orderThree_t_mem⟩ : L), by simp [mul_smul]⟩⟩
  have hgsPoint := hg sPoint
  have hgs : (g : G) • (s • (hyp.t • hyp.basept)) =
      s • (hyp.t • hyp.basept) := congrArg Subtype.val hgsPoint
  have hginvt : (g : G)⁻¹ • (hyp.t • hyp.basept) =
      hyp.t • hyp.basept := by
    calc
      (g : G)⁻¹ • (hyp.t • hyp.basept) =
          (g : G)⁻¹ • ((g : G) • (hyp.t • hyp.basept)) :=
        congrArg (fun z : Omega => (g : G)⁻¹ • z) hgt.symm
      _ = hyp.t • hyp.basept := inv_smul_smul (g : G) _
  have hconjQ0 : (g : G) * s * (g : G)⁻¹ ∈ hyp.Q0 :=
    hyp.conj_mem_Q0_of_mem_D hgD hsQ0
  let a : hyp.Q := ⟨(g : G) * s * (g : G)⁻¹,
    hyp.Q0_le_Q hconjQ0⟩
  let b : hyp.Q := ⟨s, hyp.Q0_le_Q hsQ0⟩
  have habAct : (a : G) • (hyp.t • hyp.basept) =
      (b : G) • (hyp.t • hyp.basept) := by
    change ((g : G) * s * (g : G)⁻¹) •
        (hyp.t • hyp.basept) = s • (hyp.t • hyp.basept)
    rw [mul_smul, mul_smul, hginvt]
    exact hgs
  have hab : a = b := by
    apply hyp.qRegularEquiv.injective
    apply Subtype.ext
    exact habAct
  have hconj : (g : G) * s * (g : G)⁻¹ = s :=
    congrArg Subtype.val hab
  have hgsEq : (g : G) * s = s * (g : G) := by
    have h := congrArg (fun z : G => z * (g : G)) hconj
    simpa [mul_assoc] using h
  have hsCentral : s ∈ Subgroup.centralizer {(g : G)} :=
    Subgroup.mem_centralizer_singleton_iff.mpr hgsEq.symm
  have hsBot : s ∈ hyp.Q ⊓ Subgroup.centralizer {(g : G)} :=
    ⟨hyp.Q0_le_Q hsQ0, hsCentral⟩
  rw [hyp.Q_inf_centralizer_eq_bot_of_mem_KSet hgKSet hg1,
    Subgroup.mem_bot] at hsBot
  exact hyp.distinguishedInvolution_ne_one hsBot

/-- **Peterfalvi Part II, Ch. I §3, Lemma 4.** Package the restricted
orbit action as an honest Theorem A hypothesis with root group `Q₀` and
two-point stabilizer `K`. -/
noncomputable def orderThreeHypothesisOfAction
    (hBruhat : (L : Set G) = hyp.orderThreeBruhatSet)
    (hTwo : IsMultiplyPretransitive L hyp.OrderThreeOrbit 2)
    (hFaithful : FaithfulSMul L hyp.OrderThreeOrbit) :
    Hypothesis L hyp.OrderThreeOrbit := by
  let tL : L := ⟨hyp.t, hyp.orderThree_t_mem⟩
  refine
    { basept := hyp.orderThreeBasept
      doubly_transitive := hTwo
      faithful := hFaithful
      H := hyp.orderThreeBorel.subgroupOf L
      Q := hyp.Q0.subgroupOf L
      D := hyp.K.subgroupOf L
      H_def := hyp.orderThreeBorel_eq_stabilizer hBruhat
      t := tL
      t_sq := Subtype.ext hyp.t_sq
      t_ne_one := ?_
      t_not_mem_H := ?_
      D_def := hyp.orderThreeD_def hBruhat
      Q_le_H := ?_
      Q_normal_in_H := ?_
      Q_inf_D_eq_bot := ?_
      Q_mul_D_eq_H := ?_
      Q_even := ?_
      D_odd := ?_
      two_rank_ge_two := ?_ }
  · intro ht
    exact hyp.t_ne_one (congrArg Subtype.val ht)
  · intro htB
    exact hyp.t_not_mem_H (hyp.orderThreeBorel_le_H htB)
  · intro q hq
    exact (show hyp.Q0 ≤ hyp.orderThreeBorel from le_sup_left) hq
  · intro b hb q hq
    exact hyp.orderThree_Q0_normal_in_B (b : G) hb (q : G) hq
  · rw [eq_bot_iff]
    intro x hx
    rw [Subgroup.mem_bot]
    have hx' : (x : G) ∈ hyp.Q0 ⊓ hyp.K := ⟨hx.1, hx.2⟩
    rw [hyp.orderThreeQ0_inf_K_eq_bot, Subgroup.mem_bot] at hx'
    exact Subtype.ext hx'
  · apply Set.Subset.antisymm
    · rintro y ⟨q, hq, k, hk, rfl⟩
      change (q : G) * (k : G) ∈ (B : Set G)
      rw [hyp.coe_orderThreeBorel]
      exact ⟨q, hq, k, hk, rfl⟩
    · intro y hy
      have hy' : (y : G) ∈ (hyp.Q0 : Set G) * (hyp.K : Set G) := by
        rw [← hyp.coe_orderThreeBorel]
        exact hy
      obtain ⟨q, hq, k, hk, hqk⟩ := hy'
      refine ⟨⟨q, hyp.orderThree_Q0_le hq⟩, hq,
        ⟨k, hyp.orderThree_K_le hk⟩, hk, ?_⟩
      exact Subtype.ext hqk
  · have hcard : Nat.card ↥(hyp.Q0.subgroupOf L) = Nat.card ↥hyp.Q0 :=
      Nat.card_congr
        (Subgroup.subgroupOfEquivOfLe hyp.orderThree_Q0_le).toEquiv
    rw [hcard]
    exact hyp.orderThree_Q0_even
  · have hcard : Nat.card ↥(hyp.K.subgroupOf L) = Nat.card ↥hyp.K :=
      Nat.card_congr
        (Subgroup.subgroupOfEquivOfLe hyp.orderThree_K_le).toEquiv
    rw [hcard]
    exact hyp.orderThree_K_odd
  · obtain ⟨E, hEQ0, hE4, hEsq⟩ := hyp.exists_four_subgroup_le_Q0
    have hEL : E ≤ L := hEQ0.trans hyp.orderThree_Q0_le
    refine ⟨E.subgroupOf L, ?_, ?_⟩
    · rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe hEL).toEquiv]
      exact hE4
    · intro x hx
      apply Subtype.ext
      exact hEsq (x : G) hx


/-- An involution belongs to every normal subgroup of odd index. -/
lemma mem_subgroup_of_sq_eq_one_of_odd_index
    {A : Type*} [Group A] [Finite A] (R : Subgroup A)
    (hnormal : R.Normal) (hodd : Odd R.index)
    {z : A} (hz : z ^ 2 = 1) : z ∈ R := by
  letI : R.Normal := hnormal
  obtain ⟨j, hj⟩ := hodd
  have hzpow : z ^ R.index ∈ R := Subgroup.pow_index_mem R z
  have heq : z ^ R.index = z := by
    rw [hj, pow_add, pow_mul, hz]
    simp
  rwa [heq] at hzpow

/-- **Peterfalvi Part II, Ch. I §3, Lemma 4** (p. 107). If `st` has
order three and `V ≠ 1`, then `⟨Q₀, K, t⟩` is isomorphic to `PSL(2,q)`
for a finite field of characteristic two with `q = |Q₀|`. -/
theorem exists_orderThreeGeneratedSubgroup_mulEquiv_psl2
    (hst : orderOf
      (hyp.distinguishedInvolution * hyp.t) = 3)
    (hV : hyp.V ≠ ⊥)
    (inductionHypothesis : TheoremAInductionBelow G Omega) :
    ∃ (F : Type u) (_ : Field F) (_ : Finite F) (_ : CharP F 2),
      Nat.card F = Nat.card hyp.Q0 ∧
        Nonempty
          (L ≃* Matrix.ProjectiveSpecialLinearGroup (Fin 2) F) := by
  have hBruhat : (L : Set G) = hyp.orderThreeBruhatSet := by
    rw [hyp.orderThreeGeneratedSubgroup_eq_bruhatSubgroup hst]
    exact hyp.coe_orderThreeBruhatSubgroup hst
  have hTwo : IsMultiplyPretransitive L hyp.OrderThreeOrbit 2 :=
    hyp.orderThree_isMultiplyPretransitive_two hBruhat
  have hFaithful : FaithfulSMul L hyp.OrderThreeOrbit :=
    hyp.orderThree_faithfulSMul hBruhat
  let hHyp : Hypothesis L hyp.OrderThreeOrbit :=
    hyp.orderThreeHypothesisOfAction hBruhat hTwo hFaithful
  have hsmall : Nat.card L < Nat.card G :=
    Subgroup.card_lt_card_of_ne_top
      (hyp.orderThreeGeneratedSubgroup_ne_top hBruhat hV)
  obtain ⟨result⟩ := inductionHypothesis hsmall hHyp
  let R : Subgroup G := result.L.map hyp.orderThreeGeneratedSubgroup.subtype
  have htResult :
      (⟨hyp.t, hyp.orderThree_t_mem⟩ : L) ∈ result.L := by
    apply mem_subgroup_of_sq_eq_one_of_odd_index result.L result.normal result.oddIndex
    exact Subtype.ext hyp.t_sq
  have htR : hyp.t ∈ R :=
    ⟨⟨hyp.t, hyp.orderThree_t_mem⟩, htResult, rfl⟩
  have hQ0R : hyp.Q0 ≤ R := by
    intro q hq
    let qL : L := ⟨q, hyp.orderThree_Q0_le hq⟩
    have hqResult : qL ∈ result.L := by
      apply mem_subgroup_of_sq_eq_one_of_odd_index result.L result.normal result.oddIndex
      exact Subtype.ext hq.1
    exact ⟨qL, hqResult, rfl⟩
  have hKR : hyp.K ≤ R := by
    intro k hk
    have hkKSet : k ∈ hyp.KSet := by
      rw [← hyp.coe_K]
      exact hk
    have hktL : k * hyp.t ∈ L :=
      hyp.orderThreeGeneratedSubgroup.mul_mem (hyp.orderThree_K_le hk) hyp.orderThree_t_mem
    let ktL : L := ⟨k * hyp.t, hktL⟩
    have hktResult : ktL ∈ result.L := by
      apply mem_subgroup_of_sq_eq_one_of_odd_index result.L result.normal result.oddIndex
      exact Subtype.ext (hyp.mul_t_mem_of_mem_KSet hkKSet).1
    have hktR : k * hyp.t ∈ R := ⟨ktL, hktResult, rfl⟩
    have hprod := R.mul_mem hktR htR
    have htt : hyp.t * hyp.t = 1 := by
      simpa [pow_two] using hyp.t_sq
    simpa [mul_assoc, htt] using hprod
  have hLR : L ≤ R := by
    change hyp.orderThreeBorel ⊔ Subgroup.zpowers hyp.t ≤ R
    apply sup_le
    · change hyp.Q0 ⊔ hyp.K ≤ R
      exact sup_le hQ0R hKR
    · exact Subgroup.zpowers_le.mpr htR
  have hresultLtop : result.L = ⊤ := by
    apply top_unique
    intro l _
    have hlR : (l : G) ∈ R := hLR l.2
    obtain ⟨r, hr, hrl⟩ := hlR
    have hre : r = l := Subtype.ext hrl
    simpa [hre] using hr
  have hQeq : hHyp.Q = hyp.Q0.subgroupOf L := rfl
  have hQcomm : IsMulCommutative ↥hHyp.Q := by
    rw [hQeq]
    refine ⟨⟨fun x y => Subtype.ext (Subtype.ext ?_)⟩⟩
    exact (hyp.commute_of_mem_Q0 x.2 y.2).eq
  have hcardQ : Nat.card hHyp.Q = Nat.card hyp.Q0 := by
    rw [hQeq]
    exact Nat.card_congr
      (Subgroup.subgroupOfEquivOfLe hyp.orderThree_Q0_le).toEquiv
  cases result.target with
  | psl2 data =>
      letI : Field data.F := data.fieldF
      letI : Finite data.F := data.finiteF
      letI : CharP data.F 2 := data.charTwoF
      have hcardTarget : Nat.card hHyp.Q = Nat.card data.F :=
        hHyp.natCard_Q_eq_field_of_psl2Target result.L result.normal
          result.oddIndex data
      have targetTop :
          (⊤ : Subgroup L) ≃*
            Matrix.ProjectiveSpecialLinearGroup (Fin 2) data.F := by
        rw [← hresultLtop]
        exact data.groupEquiv
      refine ⟨data.F, data.fieldF, data.finiteF, data.charTwoF,
        hcardTarget.symm.trans hcardQ, ?_⟩
      exact ⟨(Subgroup.topEquiv (G := L)).symm.trans targetTop⟩
  | suzuki data =>
      have hSuzuki := hHyp.q_isSuzuki2Group_of_suzukiTarget
        result.L result.normal result.oddIndex data
      exact (hSuzuki.2.1 hQcomm).elim
  | psu3 data =>
      have hSuzuki := hHyp.q_isSuzuki2Group_of_psu3Target
        result.L result.normal result.oddIndex data
      exact (hSuzuki.2.1 hQcomm).elim

end OddOrder.Peterfalvi.Appendices.Suzuki.Hypothesis
