/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Peterfalvi.Appendices.Suzuki.CentralizerTrichotomy
import OddOrder.Peterfalvi.Appendices.Suzuki.OrderThreePSLInduction

/-!
# Peterfalvi Part II, Ch. I §3 Lemma 5: centralizers of nontrivial elements of W

T. Peterfalvi, *Character Theory for the Odd Order Theorem* (LMS LNS 272,
2000), Part II, Ch. I §3, Lemma 5, p. 107.

This file proves the first reduction in Lemma 5.  If the distinguished product
`st` has order three and `w` is a nonidentity element of `W`, Proposition 1(c)
applied to `X = ⟨w⟩` gives the linear or unitary centralizer alternative; the
Suzuki alternative would force `|st| = 5`.  In the linear case the centralizer
root is `Q₀`.  In the unitary case it has the full prescribed order `|Q₀|³ =
|Q|`, so `w` centralizes `Q`, contradicting `C_D(Q) = 1`.  Hence
`C_Q(w) = Q₀`, exactly as used at the start of the source proof.
-/

set_option autoImplicit false

namespace OddOrder.Peterfalvi.Appendices.Suzuki.Hypothesis

universe u v

variable {G : Type u} {Omega : Type v} [Group G] [MulAction G Omega]
  [Finite G]
  (hyp : Hypothesis G Omega)

section /- §3 Lemma 5 (p. 107): the centralizer reduction -/

/-- Every element of `Q₀` centralizes the cyclic subgroup generated by an
element of `W`. -/
lemma Q0_le_centralizer_zpowers_of_mem_W {w : G} (hw : w ∈ hyp.W) :
    hyp.Q0 ≤ Subgroup.centralizer (Subgroup.zpowers w : Set G) := by
  rw [Subgroup.zpowers_eq_closure, Subgroup.centralizer_closure]
  have hw' :
      w ∈ hyp.D ⊓
        Subgroup.centralizer
          {x : G | x ^ 2 = 1 ∧ x ≠ 1 ∧ x ∈ hyp.H} := by
    rwa [← hyp.W_eq_centralizer_involutions_H]
  intro x hx
  rw [Subgroup.mem_centralizer_singleton_iff]
  rcases eq_or_ne x 1 with rfl | hx1
  · simp
  · exact Subgroup.mem_centralizer_iff.mp hw'.2 x ⟨hx.1, hx1, hx.2⟩

/-- The four-subgroup from (A3) lies in the centralizer of `⟨w⟩` for
`w ∈ W`. -/
lemma exists_four_subgroup_centralizer_zpowers_of_mem_W {w : G}
    (hw : w ∈ hyp.W) :
    ∃ E : Subgroup (Subgroup.centralizer (Subgroup.zpowers w : Set G)),
      Nat.card E = 4 ∧ ∀ x ∈ E, x ^ 2 = 1 := by
  obtain ⟨E, hEQ0, hE4, hEsq⟩ := hyp.exists_four_subgroup_le_Q0
  have hEC : E ≤ Subgroup.centralizer (Subgroup.zpowers w : Set G) :=
    hEQ0.trans (hyp.Q0_le_centralizer_zpowers_of_mem_W hw)
  refine ⟨E.subgroupOf _, ?_, ?_⟩
  · rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe hEC).toEquiv]
    exact hE4
  · intro x hx
    apply Subtype.ext
    exact hEsq (x : G) hx

/-- **Peterfalvi Part II, Ch. I §3, Lemma 5** (first reduction, p. 107).
For every `1 ≠ w ∈ W`, the centralizer of `w` inside `Q` is exactly `Q₀`.

The source assumes that `Q` is a Suzuki `2`-group of order `q³`, with
`q = |Q₀|`.  This reduction only uses the order equality; the Suzuki
structure enters the subsequent Appendix-III classification step. -/
theorem Q_inf_centralizer_singleton_eq_Q0_of_orderThree
    {w : G} (hw : w ∈ hyp.W) (hw1 : w ≠ 1)
    (hst : orderOf (hyp.distinguishedInvolution * hyp.t) = 3)
    (hcardQ : Nat.card hyp.Q = Nat.card hyp.Q0 ^ 3)
    (inductionHypothesis : TheoremAInductionBelow G Omega) :
    hyp.Q ⊓ Subgroup.centralizer {w} = hyp.Q0 := by
  let X : Subgroup G := Subgroup.zpowers w
  have hXV : X ≤ hyp.V := by
    change Subgroup.zpowers w ≤ hyp.V
    rw [Subgroup.zpowers_le]
    exact hyp.W_le_V hw
  have hX : X ≠ ⊥ := by
    change Subgroup.zpowers w ≠ ⊥
    rw [ne_eq, Subgroup.zpowers_eq_bot]
    exact hw1
  have hQ0C : hyp.Q0 ≤ Subgroup.centralizer (X : Set G) := by
    simpa only [X] using hyp.Q0_le_centralizer_zpowers_of_mem_W hw
  have hA3 :
      ∃ E : Subgroup (Subgroup.centralizer (X : Set G)),
        Nat.card E = 4 ∧ ∀ x ∈ E, x ^ 2 = 1 := by
    simpa only [X] using
      hyp.exists_four_subgroup_centralizer_zpowers_of_mem_W hw
  letI := hyp.centralizerQuotientMulAction hXV
  obtain ⟨tri⟩ :=
    hyp.centralizer_trichotomy_of_induction hXV hX hA3 inductionHypothesis
  let C : Subgroup G := Subgroup.centralizer (X : Set G)
  have hQ0Q : hyp.Q0.subgroupOf C ≤ hyp.Q.subgroupOf C := by
    intro x hx
    exact hyp.Q0_le_Q hx
  have hcentralizerSubgroup :
      hyp.Q.subgroupOf C = hyp.Q0.subgroupOf C := by
    cases tri.branch with
    | psl2 data target_eq details =>
        symm
        apply Subgroup.eq_of_le_of_card_ge hQ0Q
        rw [details.natCard_cQ_eq_field,
          details.natCard_cQ0_eq_field]
    | suzuki data target_eq details =>
        have : (3 : ℕ) = 5 := hst.symm.trans details.distinguishedProduct_order
        omega
    | psu3 data target_eq details =>
        have hQ0card : Nat.card (hyp.Q0.subgroupOf C) = Nat.card hyp.Q0 := by
          rw [Nat.card_congr
            (Subgroup.subgroupOfEquivOfLe hQ0C).toEquiv]
        have hQCcard : Nat.card ↥(hyp.Q ⊓ C) = Nat.card hyp.Q := by
          calc
            Nat.card ↥(hyp.Q ⊓ C) =
                Nat.card ↥((hyp.Q ⊓ C).subgroupOf C) :=
              Nat.card_congr
                (Subgroup.subgroupOfEquivOfLe
                  (inf_le_right : hyp.Q ⊓ C ≤ C)).symm.toEquiv
            _ = Nat.card (hyp.Q.subgroupOf C) := by
              rw [Subgroup.inf_subgroupOf_right]
            _ = Nat.card (hyp.Q0.subgroupOf C) ^ 3 :=
              details.natCard_cQ_eq_cQ0_cube
            _ = Nat.card hyp.Q0 ^ 3 := by rw [hQ0card]
            _ = Nat.card hyp.Q := hcardQ.symm
        have hQinf : hyp.Q ⊓ C = hyp.Q :=
          Subgroup.eq_of_le_of_card_ge inf_le_left
            (Nat.le_of_eq hQCcard.symm)
        have hQleC : hyp.Q ≤ C := by
          intro q hq
          have : q ∈ hyp.Q ⊓ C := hQinf.symm ▸ hq
          exact this.2
        have hXCQ : X ≤ Subgroup.centralizer (hyp.Q : Set G) :=
          Subgroup.le_centralizer_iff.mp hQleC
        have hwCQ : w ∈ Subgroup.centralizer (hyp.Q : Set G) :=
          hXCQ (Subgroup.mem_zpowers w)
        have hwD : w ∈ hyp.D := hyp.V_le_D (hyp.W_le_V hw)
        have hwBot : w ∈ hyp.D ⊓ Subgroup.centralizer (hyp.Q : Set G) :=
          ⟨hwD, hwCQ⟩
        rw [hyp.centralizer_Q_inf_D_eq_bot, Subgroup.mem_bot] at hwBot
        exact (hw1 hwBot).elim
  have hCeq :
      Subgroup.centralizer (X : Set G) = Subgroup.centralizer {w} := by
    simpa only [X, Subgroup.zpowers_eq_closure] using
      Subgroup.centralizer_closure ({w} : Set G)
  ext x
  constructor
  · intro hx
    have hxC : x ∈ C := by
      change x ∈ Subgroup.centralizer (X : Set G)
      rw [hCeq]
      exact hx.2
    have hxSub : (⟨x, hxC⟩ : C) ∈ hyp.Q.subgroupOf C := hx.1
    rw [hcentralizerSubgroup] at hxSub
    exact hxSub
  · intro hx
    refine ⟨hyp.Q0_le_Q hx, ?_⟩
    rw [← hCeq]
    exact hQ0C hx

end

end OddOrder.Peterfalvi.Appendices.Suzuki.Hypothesis
