/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Peterfalvi.Appendices.Suzuki.QStructure
import OddOrder.Peterfalvi.Appendices.Suzuki.DistinguishedInvolution
import OddOrder.GroupTheory.SpecificGroups.ProjectiveUnitary.TorusCentralizer

/-!
# The standard `PSU(3, ℓ)` model satisfies Peterfalvi's hypothesis

T. Peterfalvi, *Character Theory for the Odd Order Theorem* (LMS LNS 272, 2000),
Part II, Ch. III §3 (pp. 119–121) and Ch. IV §4, step (2) (p. 133).

Chapter IV §4 applies the results of §2 and §3 "relative to `U`, `U ∩ H` and `t`", where
`U = O^{2′}(C_G(P))` and `U/(P ∩ U) ≅ PSU(3, ℓ)`.  Every endpoint of §3 carries the
hypothesis `V = W`, which is *not* available for the faithful centralizer quotient
`C_G(P)/𝒩(C_G(P))` — there `V` is the image of `V ∩ C_G(P)`, which is larger than the
`V ∩ U` the book's argument controls.

In the standard model `V = W` is a theorem rather than an assumption, and a cheap one:
`W = C_V(K)` with `K ⊆ D`, and `D` is the determinant-one torus, which is abelian.  So
this file puts the standing hypothesis on `standardPermGroup n` acting on its unital,
where the §3 machinery applies unconditionally and the conclusions transport back along
`CentralizerPSUData.residualQuotientEquiv`.

## Main results

* `standardHypothesis` — the (A1)–(A3) carrier for `standardPermGroup n` acting on
  `Unital n`, with `H` the standard Borel, `Q` the standard root subgroup, `D` the
  determinant-one torus and `t` the Weyl element.
* `standardHypothesis_V_eq_W` — the `V = W` that every §3 endpoint requires.
* `standardHypothesis_Q0`, `natCard_standardHypothesis_Q0`,
  `natCard_standardHypothesis_Q` — `Q₀` is `Ω₁(S₀)`, of order `ℓ = 2ⁿ`, and
  `|Q| = |Q₀|³`.  These are `exists_standardModel`'s `hQ0card` and `hcardQ`.

* `standardHypothesis_distinguishedInvolution`,
  `standardHypothesis_orderOf_distinguishedInvolution_mul_t` — the distinguished
  involution is the canonical root involution `s = (0, 1)`, and `|s t| = 3`
  (`exists_standardModel`'s `hst`).

`hQsuz` needs no work here: `Q` is `standardRootSubgroup n` on the nose, so
`standardRootSubgroup_isSuzuki2Group` applies directly.  `ih` is *not* derivable in the
model — `TheoremAInductionBelow` quantifies over all smaller groups, so §4 has to supply
it from the ambient induction hypothesis together with
`Nat.card (standardPermGroup n) ≤ Nat.card G`.
-/

set_option autoImplicit false

namespace OddOrder.Peterfalvi.Appendices.Suzuki

open OddOrder.GroupTheory.SpecificGroups.ProjectiveUnitary

section /- The standard model as a source hypothesis -/

variable {n : ℕ}

/-- The Weyl element moves the point at infinity, so it is neither trivial nor Borel. -/
theorem weylElement_smul_infinity_ne (n : ℕ) :
    weylElement n • Unital.infinity n ≠ Unital.infinity n := by
  rw [weylElement_smul_infinity, Unital.origin_eq_affine_one]
  simp [Unital.affine, Unital.infinity]

/-- The standard root subgroup is normalised by the standard Borel: the Borel is
generated by root translations, which normalise the root group because it is a subgroup,
and by torus elements, which scale it (`psuTorusHom_mul_rootHom_mul_inv`). -/
theorem conj_mem_standardRootSubgroup_of_mem_standardBorel
    {h x : standardPermGroup n} (hh : h ∈ standardBorel n)
    (hx : x ∈ standardRootSubgroup n) :
    h * x * h⁻¹ ∈ standardRootSubgroup n := by
  obtain ⟨p, hp, -⟩ := (mem_standardBorel_iff_existsUnique_root_torus h).mp hh
  obtain ⟨u, rfl⟩ := hx
  subst hp
  have hconj := psuTorusHom_mul_rootHom_mul_inv p.2 u
  refine ⟨p.1 * psuTorusScaleHom n p.2 u * p.1⁻¹, ?_⟩
  rw [map_mul, map_mul, map_inv, ← hconj]
  group

/-- The determinant-one torus has odd order: it is a subgroup of the unit group of
`𝔽_{ℓ²}`, whose order `ℓ² − 1` is odd because `ℓ` is a power of two. -/
theorem odd_natCard_psuTorusRange (n : ℕ) (hn : 0 < n) :
    Odd (Nat.card ((psuTorusHom n).range)) := by
  have hcard : Nat.card ((psuTorusHom n).range) = Nat.card (PSUTorusParameter n) :=
    (Nat.card_congr (MonoidHom.ofInjective (psuTorusHom_injective n)).toEquiv).symm
  have hdvd : Nat.card (PSUTorusParameter n) ∣ Nat.card (Field n)ˣ :=
    Subgroup.card_subgroup_dvd_card _
  rw [natCard_units_field n hn] at hdvd
  have hodd : Odd (2 ^ (2 * n) - 1) := by
    have h1 : 1 ≤ 2 ^ (2 * n) := Nat.one_le_two_pow
    have h2 : 2 ∣ 2 ^ (2 * n) := dvd_pow_self 2 (by positivity)
    rcases h2 with ⟨k, hk⟩
    exact ⟨k - 1, by omega⟩
  rw [hcard]
  exact hodd.of_dvd_nat hdvd

/-- **`2`-rank at least two for the standard model.**

`Ω₁(S₀)` — the central line of the root group — is elementary abelian of order `ℓ = 2ⁿ`,
so for `n ≥ 2` it contains a subgroup of order `4`, and every element of it squares to
`1`.  (Taking the order-`4` subgroup from the whole group would not do: it could be
cyclic.) -/
theorem exists_subgroup_card_four (n : ℕ) (hn : 1 < n) :
    ∃ E : Subgroup (standardPermGroup n), Nat.card E = 4 ∧ ∀ x ∈ E, x ^ 2 = 1 := by
  classical
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  set L : Subgroup (standardPermGroup n) :=
    (RootGroup.centerLine n).map (rootHom n) with hL
  -- every element of `L` is an involution
  have hLsq : ∀ x ∈ L, x ^ 2 = 1 := by
    rintro _ ⟨u, hu, rfl⟩
    rw [← map_pow, (RootGroup.mem_centerLine_iff_sq_eq_one u).mp hu, map_one]
  -- `|L| = |Ω₁(S₀)| = 2ⁿ`
  have hLcard : Nat.card L = Nat.card (RootGroup.centerLine n) :=
    (Nat.card_congr
      (Subgroup.equivMapOfInjective _ _ (rootHom_injective n)).toEquiv).symm
  have hfix : Nat.card (RootGroup.centerLine n) = 2 ^ n := by
    rw [Nat.card_congr (RootGroup.centerLineEquivFixed n),
      natCard_fixedByConjugation n (by omega)]
  have hdvd : (2 : ℕ) ^ 2 ∣ Nat.card L := by
    rw [hLcard, hfix]
    exact pow_dvd_pow 2 hn
  obtain ⟨K, hK⟩ := Sylow.exists_subgroup_card_pow_prime (G := L) 2
    (by simpa using (Nat.card_congr (Equiv.refl L)) ▸ hdvd)
  refine ⟨K.map L.subtype, ?_, ?_⟩
  · rw [Nat.card_congr (Subgroup.equivMapOfInjective _ _ L.subtype_injective).toEquiv.symm,
      hK]
    norm_num
  · rintro _ ⟨y, -, rfl⟩
    exact hLsq _ (y : L).2

/-- **The standard `PSU(3, ℓ)` model satisfies Peterfalvi's hypothesis (A1)–(A3)**
(Part II, Ch. III §3, pp. 119–121).

`H` is the standard Borel (the stabilizer of infinity), `Q` the standard root subgroup,
`D` the determinant-one torus and `t` the Weyl element.  `D = H ∩ H^t` because Weyl
conjugation turns the stabilizer of infinity into the stabilizer of the origin, and the
two-point stabilizer is the torus (`standardBorel_inf_conj_weylElement`). -/
noncomputable def standardHypothesis (n : ℕ) (hn : 1 < n) :
    Hypothesis (standardPermGroup n) (Unital n) where
  basept := Unital.infinity n
  doubly_transitive := standardPermGroup_isMultiplyPretransitive n
  faithful := ⟨fun {g₁ g₂} h => Subtype.ext (Equiv.ext fun x => h x)⟩
  H := standardBorel n
  Q := standardRootSubgroup n
  D := (psuTorusHom n).range
  H_def := standardBorel_eq_infinityStabilizer n (Nat.zero_lt_one.trans hn)
  t := weylElement n
  t_sq := weylElement_sq_eq_one n
  t_ne_one := by
    intro h
    exact weylElement_smul_infinity_ne n (by rw [h, one_smul])
  t_not_mem_H := fun h =>
    weylElement_smul_infinity_ne n (standardBorel_le_infinityStabilizer h)
  D_def := (standardBorel_inf_conj_weylElement (Nat.zero_lt_one.trans hn)).symm
  Q_le_H := by
    rintro _ ⟨u, rfl⟩
    exact rootHom_mem_standardBorel u
  Q_normal_in_H := fun _ hh _ hx => conj_mem_standardRootSubgroup_of_mem_standardBorel hh hx
  Q_inf_D_eq_bot := standardRootSubgroup_inf_psuTorusRange n
  Q_mul_D_eq_H := standardRootSubgroup_mul_psuTorusRange n
  Q_even := by
    rw [natCard_standardRootSubgroup n (Nat.zero_lt_one.trans hn)]
    exact (Nat.even_pow' (by omega)).mpr even_two
  D_odd := odd_natCard_psuTorusRange n (Nat.zero_lt_one.trans hn)
  two_rank_ge_two := exists_subgroup_card_four n hn

/-- **`Q₀` in the standard model is `Ω₁(S₀)`**, the central line of the root group.

`Q₀` is by definition the involutions of `H` together with `1`.  Writing an element of
the Borel as `r · c` in the semidirect decomposition, squaring to `1` forces `c² = 1`,
hence `c = 1` because the torus has odd order; what is left is an involution of the root
group, i.e. an element of the central line. -/
theorem standardHypothesis_Q0 (n : ℕ) (hn : 1 < n) :
    (standardHypothesis n hn).Q0 = (RootGroup.centerLine n).map (rootHom n) := by
  have hn0 : 0 < n := Nat.zero_lt_one.trans hn
  ext x
  rw [(standardHypothesis n hn).mem_Q0_iff]
  constructor
  · rintro ⟨hx2, hxH⟩
    obtain ⟨y, rfl⟩ : ∃ y : BorelModel n, borelHom n y = x := hxH
    have hy2 : y ^ 2 = 1 := borelHom_injective n (by rw [map_pow, hx2, map_one])
    have hright : y.right = 1 := by
      have hr : y.right ^ 2 = 1 := by
        have := congrArg (SemidirectProduct.rightHom (φ := psuTorusScaleHom n)) hy2
        rwa [map_pow, map_one] at this
      have hdvd : orderOf y.right ∣ 2 := orderOf_dvd_of_pow_eq_one hr
      have hodd : Odd (orderOf y.right) := odd_orderOf_psuTorusParameter n hn0 y.right
      rcases (Nat.dvd_prime Nat.prime_two).mp hdvd with h1 | h2
      · exact orderOf_eq_one_iff.mp h1
      · exact absurd (h2 ▸ hodd) (by decide)
    have hleft : y.left ^ 2 = 1 := by
      have hinl : y = SemidirectProduct.inl y.left :=
        SemidirectProduct.ext rfl hright
      have := hy2
      rw [hinl, ← map_pow] at this
      exact SemidirectProduct.inl_injective this
    refine ⟨y.left, (RootGroup.mem_centerLine_iff_sq_eq_one y.left).mpr hleft, ?_⟩
    rw [borelHom_apply, hright, map_one, mul_one]
  · rintro ⟨u, hu, rfl⟩
    refine ⟨?_, rootHom_mem_standardBorel u⟩
    rw [← map_pow, (RootGroup.mem_centerLine_iff_sq_eq_one u).mp hu, map_one]

/-- **`|Q₀| = ℓ = 2ⁿ`** in the standard model. -/
theorem natCard_standardHypothesis_Q0 (n : ℕ) (hn : 1 < n) :
    Nat.card ((standardHypothesis n hn).Q0) = 2 ^ n := by
  rw [standardHypothesis_Q0 n hn,
    Nat.card_congr
      (Subgroup.equivMapOfInjective _ _ (rootHom_injective n)).toEquiv.symm,
    Nat.card_congr (RootGroup.centerLineEquivFixed n),
    natCard_fixedByConjugation n (Nat.zero_lt_one.trans hn)]

/-- **`|Q| = |Q₀|³`** in the standard model: `q³` against `q = 2ⁿ`. -/
theorem natCard_standardHypothesis_Q (n : ℕ) (hn : 1 < n) :
    Nat.card ((standardHypothesis n hn).Q)
      = Nat.card ((standardHypothesis n hn).Q0) ^ 3 := by
  rw [natCard_standardHypothesis_Q0 n hn,
    show (standardHypothesis n hn).Q = standardRootSubgroup n from rfl,
    natCard_standardRootSubgroup n (Nat.zero_lt_one.trans hn), ← pow_mul]
  ring_nf

/-- **The distinguished involution of the standard model is the canonical root
involution** `s = (0, 1)` of Peterfalvi Part II, Ch. III §3.

The distinguished pair is characterised by the structure equation `t s t = r⁻¹ t r`
(Ch. I §1 Prop 4(b)), and the standard braid relation
`w s w = s w s` (`standard_braid`) exhibits `s` itself as the conjugator, since `s` is an
involution.  Uniqueness (`eq_distinguishedPair_of_structure`) then identifies it. -/
theorem standardHypothesis_distinguishedInvolution (n : ℕ) (hn : 1 < n) :
    (standardHypothesis n hn).distinguishedInvolution
      = rootHom n (RootGroup.centralInvolution n) := by
  set s : standardPermGroup n := rootHom n (RootGroup.centralInvolution n) with hs
  have hsq : s ^ 2 = 1 := by
    rw [hs, ← map_pow, RootGroup.centralInvolution_sq, map_one]
  have hmul : s * s = 1 := by rw [← sq]; exact hsq
  have hinv : s⁻¹ = s := inv_eq_of_mul_eq_one_left hmul
  have hne : s ≠ 1 := by
    intro h
    refine RootGroup.centralInvolution_ne_one n (rootHom_injective n ?_)
    rw [map_one, ← hs, h]
  refine (((standardHypothesis n hn).eq_distinguishedPair_of_structure
    (rootHom_mem_standardBorel _) hsq hne
    ⟨RootGroup.centralInvolution n, rfl⟩ ?_).1).symm
  rw [hinv]
  exact standard_braid n

/-- **`|s t| = 3` in the standard model** — `exists_standardModel`'s `hst`. -/
theorem standardHypothesis_orderOf_distinguishedInvolution_mul_t (n : ℕ) (hn : 1 < n) :
    orderOf ((standardHypothesis n hn).distinguishedInvolution *
        (standardHypothesis n hn).t) = 3 := by
  rw [standardHypothesis_distinguishedInvolution n hn]
  exact standard_st_order n

/-- **`V = W` in the standard model** — the hypothesis every §3 endpoint carries, here a
theorem.

`W = C_V(K)` with `K ⊆ D`, and `D` is the determinant-one torus, which is abelian: it is
the image of a subgroup of `(𝔽_{ℓ²})ˣ`.  So `V ≤ D` centralizes `K` automatically.

This is why Ch. IV §4 step (2) runs §2/§3 inside `U/(P ∩ U) ≅ PSU(3, ℓ)` rather than the
faithful centralizer quotient: `V = W` fails to be available there, while here it costs
nothing. -/
theorem standardHypothesis_V_eq_W (n : ℕ) (hn : 1 < n) :
    (standardHypothesis n hn).V = (standardHypothesis n hn).W := by
  refine le_antisymm (fun v hv => ⟨hv, Subgroup.mem_centralizer_iff.mpr fun x hx => ?_⟩)
    (standardHypothesis n hn).W_le_V
  obtain ⟨c₁, hc₁⟩ : v ∈ (psuTorusHom n).range :=
    (standardHypothesis n hn).V_le_D hv
  obtain ⟨c₂, hc₂⟩ : x ∈ (psuTorusHom n).range := hx.1
  rw [← hc₁, ← hc₂, ← map_mul, ← map_mul, mul_comm]

end

end OddOrder.Peterfalvi.Appendices.Suzuki
