/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import OddOrder.Isaacs.Ch07_ThompsonSubgroup.S7B2_NormalJ_PComplement

/-!
# Isaacs FGT Ch.7 (Thompson subgroup) — S7D part 1: Burnside p^a q^b setup (Thm 7.8 stmt, scaffolding, Steps 2-9 decomp, faithful-action bridge) (pp. 219-222)
-/

namespace OddOrder.Isaacs.Ch07

open scoped commutatorElement
open scoped Pointwise
open scoped IsMulCommutative -- rc2: IsMulCommutative→CommGroup (for IsNilpotent) now scoped

variable {G : Type*} [Group G]

/-! ## §7D: Burnside `p^a q^b` (pp. 219-222) -/


/-! ### Thm 7.8 — Burnside `p^a q^b` ⇒ solvable (conditional on 9-step argument)

**Isaacs Thm 7.8** (mmd L3955):

> `|G| = p^a q^b` ⇒ G solvable.

**character 不使用** (Goldschmidt + Bender + Matsuyama, 9 Step proof).

**先行 dep**: Thm 7.6 normal-J + Ch.2 Thm **2.13 Baer** ✅ + Ch.4 Thm **4.33** (p-local).

BG/Peterfalvi 直接被引用無いので最後着手. Phase 1 完成度のため必須 (BG L2633 で
"we can obtain Burnside's `p^a q^b` very easily now" として言及). -/

/-! ### §7D scaffolding — `IsPCentral`, `IsPType`, helper lemmas

We formalize the supporting machinery of Isaacs' §7D proof.  These definitions
are local to §7D (Burnside `p^a q^b`); the term "p-central element" appears
informally in the textbook on p.220 and does not have a mathlib analog. -/

/-- **Isaacs p.220** (definition of *p-central element*).

`x` is `p`-central if it is a nonidentity element of the center of some Sylow
`p`-subgroup of `G`.  Used in §7D Steps 4-9.

The condition is phrased via `(Subgroup.center P).map P.subtype` so that the
membership predicate lives in the ambient group `G`. -/
def IsPCentral (p : ℕ) {G : Type*} [Group G] (x : G) : Prop :=
  x ≠ 1 ∧ ∃ P : Sylow p G,
    x ∈ (Subgroup.center (P : Subgroup G)).map (P : Subgroup G).subtype

/-- **Isaacs p.219** (definition of *p-type maximal subgroup*).

A maximal subgroup `M` of `G` is `p`-type if `O_p(M) ≠ ⊥` (where `O_p(M)`
denotes the largest normal `p`-subgroup of `M` as a group in its own right).
In Isaacs §7D this notion partitions the maximal subgroups of a simple group
of order `p^a q^b` into two flavors. -/
def IsPType (p : ℕ) {G : Type*} [Group G] (M : Subgroup G) : Prop :=
  IsCoatom M ∧ OddOrder.Isaacs.Ch01.opCore p ↥M ≠ ⊥

/-- Dual of `IsPType` with roles of `p` and `q` swapped (just a convenience
re-export of `IsPType q`). -/
abbrev IsQType (q : ℕ) {G : Type*} [Group G] (M : Subgroup G) : Prop :=
  IsPType q M

/-- A group whose order is a `{p, q}`-number: `|G| = p^a * q^b`. -/
def IsPaQbOrder (p q : ℕ) (G : Type*) [Group G] : Prop :=
  ∃ a b : ℕ, Nat.card G = p ^ a * q ^ b

/-- A `p`-central element is nonidentity. -/
theorem IsPCentral.ne_one {G : Type*} [Group G] {p : ℕ} {x : G}
    (hx : IsPCentral p x) : x ≠ 1 := hx.1

/-- A `p`-central element lies in the center of some Sylow `p`-subgroup. -/
theorem IsPCentral.mem_center {G : Type*} [Group G] {p : ℕ} {x : G}
    (hx : IsPCentral p x) :
    ∃ P : Sylow p G,
      x ∈ (Subgroup.center (P : Subgroup G)).map (P : Subgroup G).subtype :=
  hx.2

/-- A `p`-central element of `G` lies in the chosen Sylow `p`-subgroup `P`. -/
theorem IsPCentral.mem_sylow {G : Type*} [Group G] {p : ℕ} {x : G}
    (hx : IsPCentral p x) :
    ∃ P : Sylow p G, x ∈ (P : Subgroup G) := by
  obtain ⟨P, hP_mem⟩ := hx.2
  refine ⟨P, ?_⟩
  obtain ⟨⟨y, hy⟩, _, rfl⟩ := hP_mem
  exact hy

/-- **§7D** — conjugation preserves `p`-centrality: if `x` is `p`-central then so
is `g * x * g⁻¹`.  (The conjugate of `Z(P)` is `Z(g • P)`, the center of the
conjugate Sylow.)  Used in Step 4 to show `N_G(U)` normalizes the subgroup
generated by the `p`-central elements of `U`. -/
theorem IsPCentral.conj {G : Type*} [Group G] [Finite G] {p : ℕ} [Fact p.Prime]
    {x : G} (hx : IsPCentral p x) (g : G) : IsPCentral p (g * x * g⁻¹) := by
  obtain ⟨hx_ne, P, hxP⟩ := hx
  refine ⟨?_, g • P, ?_⟩
  · intro h
    apply hx_ne
    have : x = g⁻¹ * (g * x * g⁻¹) * g := by group
    rw [this, h]; group
  · -- x ∈ (center ↑P).map subtype ; conjugate to (center ↑(g•P)).map subtype.
    obtain ⟨⟨xv, hxv_mem⟩, hxv_center, hxv_eq⟩ := hxP
    -- hxv_eq : ↑⟨xv,hxv_mem⟩ = x, i.e. xv = x.
    simp only [Subgroup.coe_subtype] at hxv_eq
    subst hxv_eq
    -- want: g * xv * g⁻¹ ∈ (center ↑(g • P)).map subtype.
    -- ↑(g•P) = conj g • ↑P. g*xv*g⁻¹ ∈ ↑(g•P).
    have hmem_conj : g * xv * g⁻¹ ∈ ((g • P : Sylow p G) : Subgroup G) := by
      rw [Sylow.coe_subgroup_smul]
      exact ⟨xv, hxv_mem, rfl⟩
    refine ⟨⟨g * xv * g⁻¹, hmem_conj⟩, ?_, rfl⟩
    -- ⟨g xv g⁻¹, _⟩ ∈ center ↑(g•P): commutes with all of ↑(g•P).
    rw [SetLike.mem_coe, Subgroup.mem_center_iff]
    rintro ⟨w, hw⟩
    -- w ∈ ↑(g•P) = conj g • ↑P, so w = g w₀ g⁻¹ with w₀ ∈ ↑P.
    rw [Sylow.coe_subgroup_smul] at hw
    obtain ⟨w₀, hw₀_mem, rfl⟩ := hw
    -- xv central in ↑P ⇒ commutes with w₀.
    have hcomm := (Subgroup.mem_center_iff.mp hxv_center) ⟨w₀, hw₀_mem⟩
    have hc : xv * w₀ = w₀ * xv := by
      have := congrArg (Subgroup.subtype (P : Subgroup G)) hcomm
      simpa using this.symm
    apply Subtype.ext
    show (MulAut.conj g w₀) * (g * xv * g⁻¹) = (g * xv * g⁻¹) * (MulAut.conj g w₀)
    simp only [MulAut.conj_apply]
    calc g * w₀ * g⁻¹ * (g * xv * g⁻¹)
        = g * (w₀ * xv) * g⁻¹ := by group
      _ = g * (xv * w₀) * g⁻¹ := by rw [hc]
      _ = g * xv * g⁻¹ * (g * w₀ * g⁻¹) := by group

/-- **Step 1 reduction** — turn the `hMinCounterexample` data into the
statement "`H` is simple".

`hMinCounterexample` says that every proper normal subgroup of `H` is solvable
and every proper quotient is solvable.  Combined with the existence theorem for
solvable extensions (`solvable_of_ker_le_range`), this forces `H` to have no
nontrivial proper normal subgroup, i.e., `H` is simple. -/
theorem isSimpleGroup_of_minCounterexample
    {H : Type*} [Group H] [Nontrivial H]
    (hH_nsol : ¬ IsSolvable H)
    (hN_solvable : ∀ N : Subgroup H, N ≠ ⊤ → N.Normal → IsSolvable N)
    (hQ_solvable : ∀ (N : Subgroup H) [N.Normal], N ≠ ⊥ → IsSolvable (H ⧸ N)) :
    IsSimpleGroup H := by
  refine ⟨fun N hN_norm => ?_⟩
  by_contra h_not_bot_top
  push Not at h_not_bot_top
  obtain ⟨h_ne_bot, h_ne_top⟩ := h_not_bot_top
  -- N solvable as subgroup
  have hN_sol : IsSolvable N := hN_solvable N h_ne_top hN_norm
  -- H/N solvable as quotient
  have hQ_sol : IsSolvable (H ⧸ N) := hQ_solvable N h_ne_bot
  -- Build H solvable from extension: N → H → H/N
  have hH_sol : IsSolvable H := by
    -- Use f = N.subtype, g = mk' N.  ker g = N = range f.
    refine solvable_of_ker_le_range (N.subtype) (QuotientGroup.mk' N) ?_
    rw [QuotientGroup.ker_mk']
    exact N.range_subtype.ge
  exact hH_nsol hH_sol

/-- Helper: the order of a finite nontrivial subgroup is positive. -/
private theorem Nat.card_pos_of_finite {H : Type*} [Group H] [Finite H] :
    0 < Nat.card H := Nat.card_pos

/-- **Isaacs §7D Step "preliminary"**: a finite nonsolvable group is not a
`p`-group.

If `H` were a `p`-group it would be nilpotent (mathlib `IsPGroup.isNilpotent`)
hence solvable, contradicting non-solvability. -/
private theorem not_isPGroup_of_nonsolvable {H : Type*} [Group H] [Finite H]
    {p : ℕ} [Fact p.Prime] (hH_nsol : ¬ IsSolvable H) :
    ¬ IsPGroup p H := by
  intro h_pgroup
  haveI : Group.IsNilpotent H := h_pgroup.isNilpotent
  exact hH_nsol inferInstance

/-- **§7D helper**: in a finite simple non-solvable group, the `r`-core is
trivial for every prime `r`.

In a simple group, the normal subgroup `O_r(G)` is either `⊥` or `⊤`.  If it
were `⊤` then `G` would be an `r`-group, hence nilpotent and solvable,
contradicting non-solvability. -/
theorem opCore_eq_bot_of_simple_nonsolvable
    {H : Type*} [Group H] [Finite H] {r : ℕ} [Fact r.Prime]
    (_hH_simple : IsSimpleGroup H) (hH_nsol : ¬ IsSolvable H) :
    OddOrder.Isaacs.Ch01.opCore r H = ⊥ := by
  haveI := OddOrder.Isaacs.Ch01.opCore.normal r H
  rcases Subgroup.Normal.eq_bot_or_eq_top
    (OddOrder.Isaacs.Ch01.opCore.normal r H) with h | h
  · exact h
  · exfalso
    -- opCore r H = ⊤ ⇒ H is an r-group ⇒ solvable, contradiction.
    have h_top_pgroup : IsPGroup r ↥(OddOrder.Isaacs.Ch01.opCore r H) :=
      OddOrder.Isaacs.Ch01.opCore_isPGroup r H
    -- Top equivalence: ⊤ subgroup of H is equivalent to H itself.
    have h_iso : OddOrder.Isaacs.Ch01.opCore r H ≃* H := by
      have hEq : OddOrder.Isaacs.Ch01.opCore r H = ⊤ := h
      exact (MulEquiv.subgroupCongr hEq).trans Subgroup.topEquiv
    have hH_pgroup : IsPGroup r H := h_top_pgroup.of_equiv h_iso
    exact not_isPGroup_of_nonsolvable hH_nsol hH_pgroup

/-- **§7D helper**: in a finite simple non-solvable group, the order is
divisible by at least 2 distinct primes.

This is immediate from `not_isPGroup_of_nonsolvable`: if only one prime
divided `|H|`, then `|H| = r^n` (by unique factorization), so `H` is an
`r`-group by `IsPGroup.of_card`, hence solvable. -/
theorem two_primes_dvd_of_simple_nonsolvable
    {H : Type*} [Group H] [Finite H]
    (_hH_simple : IsSimpleGroup H) (hH_nsol : ¬ IsSolvable H) :
    ∃ r₁ r₂ : ℕ, r₁.Prime ∧ r₂.Prime ∧ r₁ ≠ r₂ ∧
      r₁ ∣ Nat.card H ∧ r₂ ∣ Nat.card H := by
  classical
  by_contra h_not_two
  push Not at h_not_two
  haveI : Nontrivial H := (inferInstance : IsSimpleGroup H).toNontrivial
  have hH_card_gt : 1 < Nat.card H := Finite.one_lt_card
  -- Pick any prime divisor.
  obtain ⟨r, hr_prime, hr_dvd⟩ := Nat.exists_prime_and_dvd hH_card_gt.ne'
  haveI : Fact r.Prime := ⟨hr_prime⟩
  -- Every prime divisor equals r.
  have hr_only : ∀ s ∈ Nat.primeFactorsList (Nat.card H), s = r := by
    intro s hs
    obtain ⟨hs_prime, hs_dvd⟩ := (Nat.mem_primeFactorsList Nat.card_pos.ne').mp hs
    by_contra hsr
    exact h_not_two r s hr_prime hs_prime (Ne.symm hsr) hr_dvd hs_dvd
  -- Then |H| = r^|primeFactorsList H| via IsPGroup.iff_card mpr argument.
  have h_eq : Nat.card H = r ^ (Nat.card H).primeFactorsList.length := by
    have hH_ne : Nat.card H ≠ 0 := Nat.card_pos.ne'
    rw [← List.prod_replicate, ← List.eq_replicate_of_mem hr_only,
        Nat.prod_primeFactorsList hH_ne]
  have hH_pgroup : IsPGroup r H := IsPGroup.of_card h_eq
  exact not_isPGroup_of_nonsolvable hH_nsol hH_pgroup

/-- **§7D helper** (specialization): a simple non-solvable group of order
dividing `p^a * q^b` (with `p ≠ q` prime) has its order divisible by both
`p` and `q`. -/
theorem p_and_q_dvd_card_of_simple_nonsolvable
    {H : Type*} [Group H] [Finite H] {p q : ℕ}
    [Fact p.Prime] [Fact q.Prime] (_hpq : p ≠ q)
    (hH_simple : IsSimpleGroup H) (hH_nsol : ¬ IsSolvable H)
    {a b : ℕ} (hH_dvd : Nat.card H ∣ p ^ a * q ^ b) :
    p ∣ Nat.card H ∧ q ∣ Nat.card H := by
  obtain ⟨r₁, r₂, hr₁_prime, hr₂_prime, hr_ne, hr₁_dvd, hr₂_dvd⟩ :=
    two_primes_dvd_of_simple_nonsolvable hH_simple hH_nsol
  have hp_prime : p.Prime := Fact.out
  have hq_prime : q.Prime := Fact.out
  -- Each rᵢ divides p^a * q^b, so by Nat.Prime.dvd_mul rᵢ ∈ {p, q}.
  have hr_in : ∀ r : ℕ, r.Prime → r ∣ Nat.card H → r = p ∨ r = q := by
    intro r hr_prime hr_dvd_H
    have hr_dvd : r ∣ p ^ a * q ^ b := hr_dvd_H.trans hH_dvd
    rcases (Nat.Prime.dvd_mul hr_prime).mp hr_dvd with hp_branch | hq_branch
    · left
      exact (Nat.prime_dvd_prime_iff_eq hr_prime hp_prime).mp
        (hr_prime.dvd_of_dvd_pow hp_branch)
    · right
      exact (Nat.prime_dvd_prime_iff_eq hr_prime hq_prime).mp
        (hr_prime.dvd_of_dvd_pow hq_branch)
  -- We have r₁ ≠ r₂, each ∈ {p, q}. Therefore {r₁, r₂} = {p, q}.
  rcases hr_in r₁ hr₁_prime hr₁_dvd with hr₁p | hr₁q
  · rcases hr_in r₂ hr₂_prime hr₂_dvd with hr₂p | hr₂q
    · exact absurd (hr₁p.trans hr₂p.symm) hr_ne
    · exact ⟨hr₁p ▸ hr₁_dvd, hr₂q ▸ hr₂_dvd⟩
  · rcases hr_in r₂ hr₂_prime hr₂_dvd with hr₂p | hr₂q
    · exact ⟨hr₂p ▸ hr₂_dvd, hr₁q ▸ hr₁_dvd⟩
    · exact absurd (hr₁q.trans hr₂q.symm) hr_ne

/-- **§7D Step 2 helper** — in a simple group, the normal closure of any
nontrivial subgroup is the whole group.

Used in Step 2 to argue: if `H' = ⟨V, Q⟩ < G` contains all `G`-conjugates of
`V` (which it does in Step 2's setup), then `H'` contains `V^G = G`, contradiction. -/
theorem normalClosure_eq_top_of_simple_of_ne_bot
    {G : Type*} [Group G] [hG : IsSimpleGroup G]
    {V : Subgroup G} (hV_ne_bot : V ≠ ⊥) :
    Subgroup.normalClosure (V : Set G) = ⊤ := by
  haveI := Subgroup.normalClosure_normal (s := (V : Set G))
  rcases Subgroup.Normal.eq_bot_or_eq_top
    (Subgroup.normalClosure_normal (s := (V : Set G))) with h | h
  · -- V ≤ normalClosure V = ⊥ ⇒ V = ⊥, contradiction.
    exfalso
    apply hV_ne_bot
    apply le_antisymm _ bot_le
    calc V ≤ Subgroup.normalClosure (V : Set G) := Subgroup.le_normalClosure
      _ = ⊥ := h
  · exact h

/-- **§7D Step 2 main consequence** — in a simple group, if a subgroup `K`
contains every conjugate `g * v * g⁻¹` of a nontrivial subgroup `V`, then
`K = ⊤`.

This is the cleanest form of Step 2's argument: `V` nontrivial and simple `G`
imply `V^G = ⊤`, so any `K` containing `V^G` (equivalently, all conjugates of
elements of `V`) must be `⊤`. -/
theorem eq_top_of_contains_all_conjugates_of_simple
    {G : Type*} [Group G] [IsSimpleGroup G]
    {V K : Subgroup G} (hV_ne_bot : V ≠ ⊥)
    (h_contains : ∀ g : G, ∀ v ∈ V, g * v * g⁻¹ ∈ K) :
    K = ⊤ := by
  have h_top : Subgroup.normalClosure (V : Set G) = ⊤ :=
    normalClosure_eq_top_of_simple_of_ne_bot hV_ne_bot
  -- K contains the normalClosure since K is closed under containing conjugates.
  have hK_normal_aux : ∀ x : G, x ∈ Subgroup.normalClosure (V : Set G) → x ∈ K := by
    intro x hx
    refine Subgroup.closure_induction (p := fun y _ => y ∈ K)
      (fun y hy_conj => ?_) ?_ ?_ ?_ hx
    · -- y is a conjugate of some v ∈ V
      rcases (Group.mem_conjugatesOfSet_iff (s := (V : Set G)) (x := y)).mp hy_conj with
        ⟨a, ha_inV, hConj⟩
      obtain ⟨g, hg⟩ := isConj_iff.mp hConj
      -- y = g * a * g⁻¹
      rw [← hg]
      exact h_contains g a ha_inV
    · exact K.one_mem
    · intro x y _ _ hx hy
      exact K.mul_mem hx hy
    · intro x _ hx
      exact K.inv_mem hx
  rw [eq_top_iff]
  intro x _
  apply hK_normal_aux
  rw [h_top]
  exact Subgroup.mem_top x

/-- A Sylow `p`-subgroup is nontrivial whenever `p ∣ |G|`. -/
theorem Sylow.ne_bot_of_dvd_card
    {G : Type*} [Group G] [Finite G] {p : ℕ} [Fact p.Prime]
    (hp_dvd : p ∣ Nat.card G) (P : Sylow p G) :
    (P : Subgroup G) ≠ ⊥ := by
  intro hP_bot
  have hp_prime : p.Prime := Fact.out
  have h_card : Nat.card (P : Subgroup G) = 1 := by rw [hP_bot]; exact Subgroup.card_bot
  have h_eq := P.card_eq_multiplicity
  rw [h_card] at h_eq
  have h_pos : 0 < (Nat.card G).factorization p :=
    hp_prime.factorization_pos_of_dvd Nat.card_pos.ne' hp_dvd
  have h1 : (1 : ℕ) = p ^ 0 := by simp
  rw [h1] at h_eq
  have h_mult_zero : (Nat.card G).factorization p = 0 :=
    (Nat.pow_right_injective hp_prime.two_le h_eq).symm
  omega

/-- **§7D IsPCentral existence** — in a finite group with `p ∣ |G|`, every
Sylow `p`-subgroup has a nontrivial element in its center (since a nontrivial
finite `p`-group has nontrivial center), and any such nontrivial center
element is `p`-central. -/
theorem exists_isPCentral {G : Type*} [Group G] [Finite G] {p : ℕ}
    [Fact p.Prime] (hp_dvd : p ∣ Nat.card G) :
    ∃ x : G, IsPCentral p x := by
  classical
  haveI : Nontrivial G := by
    rw [← Finite.one_lt_card_iff_nontrivial]
    exact lt_of_lt_of_le (Fact.out (p := p.Prime)).one_lt
      (Nat.le_of_dvd Nat.card_pos hp_dvd)
  -- Pick a Sylow p-subgroup; it is nontrivial.
  obtain ⟨P⟩ := Sylow.nonempty (p := p) (G := G)
  have hP_ne_bot : (P : Subgroup G) ≠ ⊥ := Sylow.ne_bot_of_dvd_card hp_dvd P
  -- P is a finite nontrivial p-group, so its center is nontrivial.
  haveI : Nontrivial ↥(P : Subgroup G) := P.toSubgroup.nontrivial_iff_ne_bot.mpr hP_ne_bot
  haveI : Finite ↥(P : Subgroup G) := inferInstance
  have hPpg : IsPGroup p ↥(P : Subgroup G) := P.isPGroup'
  have h_center_nt : Nontrivial (Subgroup.center ↥(P : Subgroup G)) :=
    hPpg.center_nontrivial
  -- Pick a nontrivial center element.
  obtain ⟨⟨⟨c, hc_mem⟩, hc_in_center⟩, hc_ne_one⟩ :=
    exists_ne (1 : Subgroup.center ↥(P : Subgroup G))
  -- c ∈ G, c ∈ (Subgroup.center P).map P.subtype, c ≠ 1.
  refine ⟨c, ?_, P, ?_⟩
  · -- c ≠ 1 since (⟨⟨c, hc_mem⟩, hc_in_center⟩) ≠ 1 inside center.
    intro hc1
    apply hc_ne_one
    apply Subtype.ext
    apply Subtype.ext
    exact hc1
  · -- c ∈ (Subgroup.center P).map P.subtype
    exact ⟨⟨c, hc_mem⟩, hc_in_center, rfl⟩

/-- **§7D Sylow extraction** — in a finite simple non-solvable group of order
dividing `p^a * q^b`, every Sylow `p`-subgroup is nontrivial. -/
theorem sylow_ne_bot_of_simple_nonsolvable_paqb
    {H : Type*} [Group H] [Finite H] {p q : ℕ}
    [Fact p.Prime] [Fact q.Prime] (hpq : p ≠ q)
    (hH_simple : IsSimpleGroup H) (hH_nsol : ¬ IsSolvable H)
    {a b : ℕ} (hH_dvd : Nat.card H ∣ p ^ a * q ^ b)
    (P : Sylow p H) : (P : Subgroup H) ≠ ⊥ :=
  Sylow.ne_bot_of_dvd_card
    (p_and_q_dvd_card_of_simple_nonsolvable hpq hH_simple hH_nsol hH_dvd).1 P

/-- **§7D auxiliary observation** (Isaacs L3965) — if `M` is a maximal subgroup
of a simple group `G` and `K ≤ M` is a nontrivial subgroup normalized by every
element of `M`, then `M = N_G(K)`.

Proof: `M ⊆ N_G(K)` by hypothesis.  `N_G(K) ≠ ⊤` since otherwise `K ⊴ G`
which (by simplicity) forces `K = ⊥` (contradicting nontriviality) or `K = ⊤`
(contradicting `K ≤ M < G`).  By maximality, `N_G(K) = M`. -/
theorem maximal_eq_normalizer_of_M_normalizes
    {G : Type*} [Group G] [IsSimpleGroup G]
    {M K : Subgroup G} (hM_max : IsCoatom M)
    (hK_ne_bot : K ≠ ⊥) (hKM_le : K ≤ M)
    (hM_normalizes : M ≤ Subgroup.normalizer K) :
    Subgroup.normalizer K = M := by
  rcases hM_max.le_iff.mp hM_normalizes with h | h
  · -- N_G(K) = ⊤ ⇒ K is normal in G ⇒ K ∈ {⊥, ⊤} by simplicity.
    exfalso
    have hK_norm_G : K.Normal := by
      refine ⟨fun x hx g => ?_⟩
      have hg_in_N : g ∈ Subgroup.normalizer K := h ▸ Subgroup.mem_top g
      rw [Subgroup.mem_normalizer_iff] at hg_in_N
      exact (hg_in_N x).mp hx
    rcases hK_norm_G.eq_bot_or_eq_top with hK_bot | hK_top
    · exact hK_ne_bot hK_bot
    · -- K = ⊤ contradicts K ≤ M and M < ⊤ (since M is a coatom).
      have : K ≤ M := hKM_le
      rw [hK_top] at this
      exact hM_max.ne_top (le_antisymm le_top this)
  · -- h : N_G(K) = M is exactly the goal.
    exact h

/-- **§7D Step 5 (first half)** — every `p`-subgroup of a finite group is
centralized by some `p`-central element.

Isaacs L3995-3998: "Given a `p`-subgroup `V ⊆ G`, choose `P ∈ Syl_p(G)` with
`P ⊇ V`.  Then `Z(P) ⊆ C_G(V)`, and so `C_G(V)` contains a `p`-central
element."

This requires `p ∣ |G|` (so `P` is nontrivial) and `V` to be a finite
`p`-subgroup (so it's contained in some Sylow). -/
theorem exists_isPCentral_centralizing
    {G : Type*} [Group G] [Finite G] {p : ℕ} [Fact p.Prime]
    (hp_dvd : p ∣ Nat.card G)
    (V : Subgroup G) (hV_pgroup : IsPGroup p V) :
    ∃ x : G, IsPCentral p x ∧ ∀ v ∈ V, x * v = v * x := by
  classical
  -- Extend V to a Sylow p-subgroup P; it is nontrivial since p ∣ |G|.
  obtain ⟨P, hVP⟩ := IsPGroup.exists_le_sylow hV_pgroup
  have hP_ne_bot : (P : Subgroup G) ≠ ⊥ := Sylow.ne_bot_of_dvd_card hp_dvd P
  -- P nontrivial p-group ⇒ Z(P) nontrivial.
  haveI : Nontrivial ↥(P : Subgroup G) :=
    (P : Subgroup G).nontrivial_iff_ne_bot.mpr hP_ne_bot
  haveI : Finite ↥(P : Subgroup G) := inferInstance
  have hPpg : IsPGroup p ↥(P : Subgroup G) := P.isPGroup'
  have h_center_nt : Nontrivial (Subgroup.center ↥(P : Subgroup G)) :=
    hPpg.center_nontrivial
  obtain ⟨⟨⟨c, hc_mem⟩, hc_in_center⟩, hc_ne_one⟩ :=
    exists_ne (1 : Subgroup.center ↥(P : Subgroup G))
  -- c is p-central.
  have hc_pcentral : IsPCentral p c := by
    refine ⟨?_, P, ⟨c, hc_mem⟩, hc_in_center, rfl⟩
    intro hc1
    apply hc_ne_one
    apply Subtype.ext
    apply Subtype.ext
    exact hc1
  -- c commutes with everything in P, in particular with everything in V ⊆ P.
  have hc_center_iff : ∀ g : ↥(P : Subgroup G),
      g * ⟨c, hc_mem⟩ = ⟨c, hc_mem⟩ * g :=
    Subgroup.mem_center_iff.mp hc_in_center
  have hc_comm : ∀ v ∈ V, c * v = v * c := by
    intro v hv
    have hv_P : v ∈ (P : Subgroup G) := hVP hv
    have hcomm := hc_center_iff ⟨v, hv_P⟩
    have := (congrArg Subtype.val hcomm).symm
    simpa [Subgroup.coe_mul] using this
  exact ⟨c, hc_pcentral, hc_comm⟩

/-- **§7D Step 7 (q = 2 application of Matsuyama)** — if `H` is a finite simple
non-solvable group and `q = 2`, then for any involution `t ∈ H` with `t ≠ 1`,
there exists an element `x` of odd prime order with `t * x * t = x⁻¹`.

This combines `opCore_eq_bot_of_simple_nonsolvable` (giving `t ∉ O_2(H)`) with
Matsuyama's theorem (Isaacs Thm 2.13).  Step 7 will use this to derive a
contradiction with Step 6 ("`q`-central elements normalize no nontrivial
`p`-subgroup"). -/
theorem matsuyama_of_simple_nonsolvable_q_two
    {H : Type*} [Group H] [Finite H]
    (hH_simple : IsSimpleGroup H) (hH_nsol : ¬ IsSolvable H)
    {t : H} (ht_sq : t * t = 1) (ht_ne_one : t ≠ 1) :
    ∃ x : H, ∃ p : ℕ, p.Prime ∧ Odd p ∧ orderOf x = p ∧ t * x * t = x⁻¹ := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  -- t ∉ O_2(H) since O_2(H) = ⊥ in a simple non-solvable group.
  have hO2_bot : OddOrder.Isaacs.Ch01.opCore 2 H = ⊥ :=
    opCore_eq_bot_of_simple_nonsolvable hH_simple hH_nsol
  have ht_notin : t ∉ OddOrder.Isaacs.Ch01.opCore 2 H := by
    rw [hO2_bot, Subgroup.mem_bot]
    exact ht_ne_one
  exact OddOrder.Isaacs.Ch02.matsuyama ht_sq ht_notin

/-! ### §7D Steps 2-9 — per-step decomposition of the 9-step argument

The original monolithic axiom `noNonsolvableSimplePaQb` (the entire
Goldschmidt-Bender-Matsuyama argument) is here decomposed into the individual
textbook steps.  Steps that are provable from the landed infrastructure appear
as theorems; the heavier steps (4, 8, 9) remain as fine-grained local axioms,
each tracked in issue 0032.  The steps are wired together into
`noNonsolvableSimplePaQb` (now a *theorem*) at the end. -/

/-- **§7D arithmetic helper** — a positive natural dividing `p^a * q^b`
(`p ≠ q` prime) is itself of the form `p^a' * q^b'`.

Both sides have the same `Nat.factorization` (agreeing at `p`, at `q`, and being
`0` elsewhere since the only prime factors are `p` and `q`), so they are equal. -/
theorem card_eq_pow_mul_pow_of_dvd {n p q : ℕ}
    (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q) (hn : n ≠ 0)
    {a b : ℕ} (hdvd : n ∣ p ^ a * q ^ b) :
    n = p ^ n.factorization p * q ^ n.factorization q := by
  -- Every prime factor of n is p or q.
  have hpf : ∀ r, r.Prime → r ∣ n → r = p ∨ r = q := by
    intro r hr_prime hr_dvd
    have hr_dvd_paqb : r ∣ p ^ a * q ^ b := hr_dvd.trans hdvd
    rcases (Nat.Prime.dvd_mul hr_prime).mp hr_dvd_paqb with h | h
    · left; exact (Nat.prime_dvd_prime_iff_eq hr_prime hp).mp (hr_prime.dvd_of_dvd_pow h)
    · right; exact (Nat.prime_dvd_prime_iff_eq hr_prime hq).mp (hr_prime.dvd_of_dvd_pow h)
  -- Compare factorizations.
  apply Nat.eq_of_factorization_eq hn
    (mul_ne_zero (pow_ne_zero _ hp.ne_zero) (pow_ne_zero _ hq.ne_zero))
  intro r
  -- factorization of RHS at r: (n.fact p)*(p.fact r) + (n.fact q)*(q.fact r).
  rw [Nat.factorization_mul (pow_ne_zero _ hp.ne_zero) (pow_ne_zero _ hq.ne_zero),
      Finsupp.add_apply, Nat.factorization_pow, Nat.factorization_pow,
      Finsupp.smul_apply, Finsupp.smul_apply, smul_eq_mul, smul_eq_mul]
  -- Use the explicit single-point factorization of a prime.
  rw [Nat.Prime.factorization hp, Nat.Prime.factorization hq,
      Finsupp.single_apply, Finsupp.single_apply]
  by_cases hrp : r = p
  · subst hrp
    rw [if_pos rfl, if_neg (fun h => hpq h.symm), mul_one, mul_zero, add_zero]
  · by_cases hrq : r = q
    · subst hrq
      rw [if_neg (fun h => hpq h), if_pos rfl, mul_one, mul_zero, zero_add]
    · -- r ∉ {p,q}: n.factorization r = 0 and both single-points miss r.
      rw [if_neg (fun h => hrp h.symm), if_neg (fun h => hrq h.symm), mul_zero, mul_zero, add_zero]
      -- n.factorization r = 0: r is not a prime factor of n.
      by_cases hr_prime : r.Prime
      · exact Nat.factorization_eq_zero_of_not_dvd (fun hdvd_pr => by
          rcases hpf r hr_prime hdvd_pr with h | h; exacts [hrp h, hrq h])
      · exact Nat.factorization_eq_zero_of_not_prime _ hr_prime

/-- **§7D Step 2 — complementary Sylow product** (Isaacs L3973).

In a finite group of order `p^a * q^b` (`p ≠ q` prime), a Sylow `p`-subgroup
and a Sylow `q`-subgroup are complementary: `|P| * |Q| = |G|` and they are
disjoint, so `(P, Q)` is a complement pair.  This packages the textbook fact
"`|PQ| = |P||Q| = |G|` since `P ∩ Q = 1`, and thus `PQ = G`". -/
theorem sylow_isComplement_of_paqb
    {H : Type*} [Group H] [Finite H] {p q : ℕ}
    [Fact p.Prime] [Fact q.Prime] (hpq : p ≠ q)
    {a b : ℕ} (hH_card : Nat.card H = p ^ a * q ^ b)
    (P : Sylow p H) (Q : Sylow q H) :
    Subgroup.IsComplement' (P : Subgroup H) (Q : Subgroup H) := by
  have hp_prime : p.Prime := Fact.out
  have hq_prime : q.Prime := Fact.out
  have hp_ne_dvd_q : ¬ p ∣ q := by
    rw [Nat.prime_dvd_prime_iff_eq hp_prime hq_prime]; exact hpq
  have hq_ne_dvd_p : ¬ q ∣ p := by
    rw [Nat.prime_dvd_prime_iff_eq hq_prime hp_prime]; exact (Ne.symm hpq)
  -- factorization of p^a * q^b at p is a, at q is b.
  have hfact_p : (p ^ a * q ^ b).factorization p = a := by
    rw [Nat.factorization_mul (pow_ne_zero a hp_prime.ne_zero)
        (pow_ne_zero b hq_prime.ne_zero), Finsupp.add_apply,
        Nat.factorization_pow_self hp_prime,
        Nat.factorization_pow, Finsupp.smul_apply,
        Nat.factorization_eq_zero_of_not_dvd hp_ne_dvd_q, smul_eq_mul, mul_zero, add_zero]
  have hfact_q : (p ^ a * q ^ b).factorization q = b := by
    rw [Nat.factorization_mul (pow_ne_zero a hp_prime.ne_zero)
        (pow_ne_zero b hq_prime.ne_zero), Finsupp.add_apply,
        Nat.factorization_pow_self hq_prime,
        Nat.factorization_pow, Finsupp.smul_apply,
        Nat.factorization_eq_zero_of_not_dvd hq_ne_dvd_p, smul_eq_mul, mul_zero, zero_add]
  -- |P| = p ^ a, |Q| = q ^ b.
  have hP_card : Nat.card (P : Subgroup H) = p ^ a := by
    rw [P.card_eq_multiplicity, hH_card, hfact_p]
  have hQ_card : Nat.card (Q : Subgroup H) = q ^ b := by
    rw [Q.card_eq_multiplicity, hH_card, hfact_q]
  -- |P| * |Q| = |G| and coprime ⇒ complement.
  refine Subgroup.isComplement'_of_coprime ?_ ?_
  · rw [hP_card, hQ_card, hH_card]
  · rw [hP_card, hQ_card]
    exact Nat.Coprime.pow a b (hp_prime.coprime_iff_not_dvd.mpr hp_ne_dvd_q)

/-- **§7D Step 2 — join with Sylow `q` is everything** (Isaacs L3973-3978).

If `P ∈ Syl_p(H)` normalizes a nontrivial subgroup `V` of a finite simple
group `H` of order `p^a q^b`, then `⟨V, Q⟩ = H` for every `Q ∈ Syl_q(H)`.

Proof (textbook): `H = PQ`, so for `g = xy` (`x ∈ P`, `y ∈ Q`),
`V^g = V^{xy} = V^y ⊆ ⟨V,Q⟩` since `P` normalizes `V`.  Thus `⟨V,Q⟩` contains
all `H`-conjugates of `V`; by simplicity `V^H = H`, so `⟨V,Q⟩ = H`. -/
theorem step2_join_sylow_q_eq_top
    {H : Type*} [Group H] [Finite H] [IsSimpleGroup H] {p q : ℕ}
    [Fact p.Prime] [Fact q.Prime] (hpq : p ≠ q)
    {a b : ℕ} (hH_card : Nat.card H = p ^ a * q ^ b)
    (P : Sylow p H) (Q : Sylow q H)
    {V : Subgroup H} (hV_ne_bot : V ≠ ⊥)
    (hP_norm : (P : Subgroup H) ≤ Subgroup.normalizer V) :
    V ⊔ (Q : Subgroup H) = ⊤ := by
  -- (Q, P) is a complement pair, so every g factors as y * x with y ∈ Q, x ∈ P.
  have hcompl : Subgroup.IsComplement' (Q : Subgroup H) (P : Subgroup H) :=
    (sylow_isComplement_of_paqb hpq hH_card P Q).symm
  -- ⟨V, Q⟩ = V ⊔ Q contains all conjugates of V.
  have h_contains : ∀ g : H, ∀ v ∈ V, g * v * g⁻¹ ∈ V ⊔ (Q : Subgroup H) := by
    intro g v hv
    -- Factor g = y * x, y ∈ Q, x ∈ P.
    obtain ⟨⟨⟨y, hy⟩, ⟨x, hx⟩⟩, hyx⟩ := hcompl.2 g
    simp only at hyx
    subst hyx
    -- g v g⁻¹ = (y x) v (y x)⁻¹ = y (x v x⁻¹) y⁻¹.
    have hgvg : (y * x) * v * (y * x)⁻¹ = y * (x * v * x⁻¹) * y⁻¹ := by group
    rw [hgvg]
    -- x ∈ P ≤ N(V) ⇒ x * v * x⁻¹ ∈ V.
    have hx_norm : x ∈ Subgroup.normalizer V := hP_norm hx
    have hxvx_mem_V : x * v * x⁻¹ ∈ V :=
      (Subgroup.mem_normalizer_iff.mp hx_norm v).mp hv
    -- Now y * (x v x⁻¹) * y⁻¹ ∈ ⟨V, Q⟩ since x v x⁻¹ ∈ V ≤ join, y ∈ Q ≤ join.
    have hy_join : y ∈ V ⊔ (Q : Subgroup H) := Subgroup.mem_sup_right hy
    have hxvx_join : x * v * x⁻¹ ∈ V ⊔ (Q : Subgroup H) := Subgroup.mem_sup_left hxvx_mem_V
    exact (V ⊔ (Q : Subgroup H)).mul_mem
      ((V ⊔ (Q : Subgroup H)).mul_mem hy_join hxvx_join)
      ((V ⊔ (Q : Subgroup H)).inv_mem hy_join)
  exact eq_top_of_contains_all_conjugates_of_simple hV_ne_bot h_contains

/-- **§7D Step 2 — a full Sylow `p`-subgroup normalizes no nontrivial
`q`-subgroup** (Isaacs L3978-3980, the "in particular" clause).

If `P ∈ Syl_p(H)` (`H` finite simple of order `p^a q^b`) normalized a
nontrivial `q`-subgroup `V`, then by `step2_join_sylow_q_eq_top` we would have
`V ⊔ Q = ⊤` for a suitable `Q ∈ Syl_q` chosen to contain `V`; but then
`V ⊔ Q = Q ≠ ⊤`, a contradiction. -/
theorem step2_pSylow_not_normalizes_nontrivial_qSubgroup
    {H : Type*} [Group H] [Finite H] [IsSimpleGroup H] {p q : ℕ}
    [Fact p.Prime] [Fact q.Prime] (hpq : p ≠ q)
    {a b : ℕ} (hH_card : Nat.card H = p ^ a * q ^ b)
    (hp_dvd : p ∣ Nat.card H)
    (P : Sylow p H) {V : Subgroup H} (hV_ne_bot : V ≠ ⊥)
    (hV_qgroup : IsPGroup q V)
    (hP_norm : (P : Subgroup H) ≤ Subgroup.normalizer V) :
    False := by
  -- Pick a Sylow q-subgroup Q ⊇ V.
  obtain ⟨Q, hVQ⟩ := IsPGroup.exists_le_sylow hV_qgroup
  -- Step 2: V ⊔ Q = ⊤.
  have h_top : V ⊔ (Q : Subgroup H) = ⊤ :=
    step2_join_sylow_q_eq_top hpq hH_card P Q hV_ne_bot hP_norm
  -- But V ≤ Q, so V ⊔ Q = Q, forcing Q = ⊤.
  have h_join_eq_Q : V ⊔ (Q : Subgroup H) = (Q : Subgroup H) := sup_eq_right.mpr hVQ
  rw [h_join_eq_Q] at h_top
  have hp_prime : p.Prime := Fact.out
  have hq_prime : q.Prime := Fact.out
  have hp_ne_dvd_q : ¬ p ∣ q := by
    rw [Nat.prime_dvd_prime_iff_eq hp_prime hq_prime]; exact hpq
  have hq_ne_dvd_p : ¬ q ∣ p := by
    rw [Nat.prime_dvd_prime_iff_eq hq_prime hp_prime]; exact (Ne.symm hpq)
  -- Q = ⊤ ⇒ |H| = |Q| = q^b.  But p ∣ |H| = q^b ⇒ p ∣ q, contradiction.
  have hQ_card : Nat.card (Q : Subgroup H) = q ^ b := by
    rw [Q.card_eq_multiplicity, hH_card]
    congr 1
    rw [Nat.factorization_mul (pow_ne_zero a hp_prime.ne_zero)
        (pow_ne_zero b hq_prime.ne_zero), Finsupp.add_apply,
        Nat.factorization_pow_self hq_prime,
        Nat.factorization_pow, Finsupp.smul_apply,
        Nat.factorization_eq_zero_of_not_dvd hq_ne_dvd_p, smul_eq_mul, mul_zero, zero_add]
  have hH_card_eq_qb : Nat.card H = q ^ b := by
    have : Nat.card (Q : Subgroup H) = Nat.card H := by
      rw [h_top]; exact Nat.card_congr (Subgroup.topEquiv).toEquiv
    rw [← this, hQ_card]
  rw [hH_card_eq_qb] at hp_dvd
  exact hp_ne_dvd_q (hp_prime.dvd_of_dvd_pow hp_dvd)

/-- **§7D Steps 2-3 partition setup** — every maximal subgroup `M` of a simple
group of order `p^a q^b` is `p`-type or `q`-type (Isaacs L3963-3967).

`M` is solvable (proper subgroup, all proper subgroups solvable) and nontrivial,
so its Fitting subgroup is nontrivial; since `|M| ∣ p^a q^b` has prime factors
only among `{p, q}`, and `F(M) = ⨆_{r ∈ primeFactors |M|} O_r(M)`, at least one
of `O_p(M)`, `O_q(M)` is nontrivial. -/
theorem maximal_isPType_or_isQType
    {H : Type*} [Group H] [Finite H] {p q : ℕ}
    [Fact p.Prime] [Fact q.Prime] (hpq : p ≠ q)
    {a b : ℕ} (hH_card : Nat.card H = p ^ a * q ^ b)
    {M : Subgroup H} (hM_max : IsCoatom M) (hM_ne_bot : M ≠ ⊥)
    (hM_solvable : IsSolvable M) :
    IsPType p M ∨ IsQType q M := by
  classical
  have hp_prime : p.Prime := Fact.out
  have hq_prime : q.Prime := Fact.out
  -- M is nontrivial since M ≠ ⊥ (in the §7D application H is non-solvable, so
  -- |H| is not prime and a maximal subgroup is never trivial).
  haveI hM_nontriv : Nontrivial ↥M := (Subgroup.nontrivial_iff_ne_bot M).mpr hM_ne_bot
  -- F(M) ≠ ⊥.
  have hF_ne_bot : OddOrder.Isaacs.Ch01.fitting ↥M ≠ ⊥ :=
    OddOrder.Isaacs.Ch01.fitting_ne_bot_of_solvable_nontrivial ↥M
  -- F(M) = ⨆_{r ∈ primeFactors |M|} O_r(M).
  rw [OddOrder.Isaacs.Ch01.fitting_eq_iSup_primeFactors] at hF_ne_bot
  -- primeFactors |M| ⊆ {p, q}.
  have hM_card_dvd : Nat.card ↥M ∣ p ^ a * q ^ b := by
    rw [← hH_card]; exact M.card_subgroup_dvd_card
  have hpf_sub : ∀ r ∈ (Nat.card ↥M).primeFactors, r = p ∨ r = q := by
    intro r hr
    obtain ⟨hr_prime, hr_dvd, _⟩ := Nat.mem_primeFactors.mp hr
    have hr_dvd_paqb : r ∣ p ^ a * q ^ b := hr_dvd.trans hM_card_dvd
    rcases (Nat.Prime.dvd_mul hr_prime).mp hr_dvd_paqb with h | h
    · left; exact (Nat.prime_dvd_prime_iff_eq hr_prime hp_prime).mp (hr_prime.dvd_of_dvd_pow h)
    · right; exact (Nat.prime_dvd_prime_iff_eq hr_prime hq_prime).mp (hr_prime.dvd_of_dvd_pow h)
  -- Some O_r(M) ≠ ⊥ with r ∈ {p,q}.
  by_contra h_neither
  push Not at h_neither
  obtain ⟨h_notP, h_notQ⟩ := h_neither
  -- h_notP : ¬ IsPType p M, i.e., ¬(IsCoatom M ∧ opCore p ↥M ≠ ⊥).
  have hOp_bot : OddOrder.Isaacs.Ch01.opCore p ↥M = ⊥ := by
    by_contra hne; exact h_notP ⟨hM_max, hne⟩
  have hOq_bot : OddOrder.Isaacs.Ch01.opCore q ↥M = ⊥ := by
    by_contra hne; exact h_notQ ⟨hM_max, hne⟩
  -- Then every generator opCore r ↥M (r ∈ primeFactors) is ⊥, so the sup is ⊥.
  apply hF_ne_bot
  rw [eq_bot_iff]
  refine iSup_le (fun r => ?_)
  rcases hpf_sub r r.2 with hrp | hrq
  · rw [show (r : ℕ) = p from hrp, hOp_bot]
  · rw [show (r : ℕ) = q from hrq, hOq_bot]


/-! ### §7D faithful-action generation bridge (Isaacs Thm 6.20/6.21, L3990-3993)

For the Step 3 contradiction we need the "generated-centralizer" conclusion in
the form Isaacs uses: if an abelian `A ≤ G` normalizes an abelian (more
generally arbitrary) subgroup `N ≤ G` of coprime order, and `A` is **not
cyclic**, then `N = ⟨C_N(a) ∣ 1 ≠ a ∈ A⟩`.  This is Isaacs Thm 6.21
(`nontrivialActionFixedByClosure_eq_top_of_not_isCyclic`) applied to the
conjugation action of `A` on `N` (`Subgroup.normalizerMonoidHom` restricted to
`A`).  Conversely, the *faithfulness* of that conjugation action is `C_N(A)`
trivial, which Isaacs uses for the cyclic-arithmetic final branch. -/

/-- The conjugation action of a subgroup `A ≤ N_G(N)` on the subgroup `N`,
obtained by composing mathlib's conjugation `MulDistribMulAction` of `N_G(N)`
on `N` with the inclusion `A ↪ N_G(N)`.  Under this action
`a • n = ⟨↑a * ↑n * (↑a)⁻¹⟩`. -/
noncomputable def conjActionOfNormalizes {G : Type*} [Group G] (A N : Subgroup G)
    (hAN : A ≤ Subgroup.normalizer N) : MulDistribMulAction ↥A ↥N :=
  MulDistribMulAction.compHom (M := ↥(Subgroup.normalizer N)) ↥N
    (Subgroup.inclusion hAN)

/-- **Isaacs Thm 6.21 bridge (generation form)** — if an abelian `A ≤ G` of
order coprime to `|N|` normalizes `N ≤ G` and is **not cyclic**, then `N` is
generated by the conjugation-centralizers `C_N(a)` of its nonidentity elements.

Concretely: every `n ∈ N` lies in the subgroup generated by
`{x ∈ N ∣ ∃ a ∈ A, a ≠ 1 ∧ a x a⁻¹ = x}`. -/
theorem mem_closure_conjCentralizers_of_not_isCyclic
    {G : Type*} [Group G] [Finite G] {A N : Subgroup G}
    [IsMulCommutative ↥A]
    (hAN : A ≤ Subgroup.normalizer N)
    (hCop : Nat.Coprime (Nat.card ↥A) (Nat.card ↥N))
    (hA_not_cyclic : ¬ IsCyclic ↥A) :
    ∀ n ∈ N, n ∈ Subgroup.closure
      {x : G | x ∈ N ∧ ∃ a : G, a ∈ A ∧ a ≠ 1 ∧ a * x * a⁻¹ = x} := by
  classical
  letI : MulDistribMulAction ↥A ↥N := conjActionOfNormalizes A N hAN
  -- `a • n = ⟨↑a * ↑n * (↑a)⁻¹⟩` for `a : ↥A`, `n : ↥N`.
  have hsmul_coe : ∀ (a : ↥A) (n : ↥N), ((a • n : ↥N) : G) = (↑a) * (↑n) * (↑a)⁻¹ := by
    intro a n; rfl
  -- Thm 6.21: the generated subgroup is ⊤.
  have hTop : OddOrder.Isaacs.Ch06.nontrivialActionFixedByClosure
      (MulDistribMulAction.toMulAut ↥A ↥N) = ⊤ :=
    OddOrder.Isaacs.Ch06.nontrivialActionFixedByClosure_eq_top_of_not_isCyclic
      hCop hA_not_cyclic
  intro n hn
  -- The element `⟨n, hn⟩ : ↥N` lies in the generated closure (= ⊤).
  have hmem : (⟨n, hn⟩ : ↥N) ∈
      OddOrder.Isaacs.Ch06.nontrivialActionFixedByClosure
        (MulDistribMulAction.toMulAut ↥A ↥N) := by
    rw [hTop]; exact Subgroup.mem_top _
  -- Transport closure membership from ↥N to G via the subtype inclusion.
  -- The generators of the ↥N-closure are `{u | ∃ a ≠ 1, u ∈ actionFixedBy φ a}`.
  rw [OddOrder.Isaacs.Ch06.nontrivialActionFixedByClosure] at hmem
  -- Induction over the closure in ↥N.
  refine Subgroup.closure_induction
    (p := fun (u : ↥N) _ => (↑u : G) ∈ Subgroup.closure
      {x : G | x ∈ N ∧ ∃ a : G, a ∈ A ∧ a ≠ 1 ∧ a * x * a⁻¹ = x})
    ?mem ?one ?mul ?inv hmem
  · -- generator: `u ∈ actionFixedBy φ a` for some `a ≠ 1`.
    rintro u ⟨a, ha_ne, hu_fix⟩
    apply Subgroup.subset_closure
    refine ⟨u.2, (a : G), a.2, ?_, ?_⟩
    · -- `a ≠ 1` in `↥A` ⇒ `(a : G) ≠ 1`.
      intro hcontra
      exact ha_ne (Subtype.ext hcontra)
    · -- `a • u = u` ⇒ `↑a * ↑u * (↑a)⁻¹ = ↑u`.
      rw [OddOrder.Isaacs.Ch06.mem_actionFixedBy] at hu_fix
      -- `(toMulAut ↥A ↥N) a u = a • u` definitionally, so `a • u = u`.
      have hau : (a • u : ↥N) = u := hu_fix
      have : ((a • u : ↥N) : G) = (↑u : G) := congrArg _ hau
      rwa [hsmul_coe] at this
  · simpa using Subgroup.one_mem _
  · intro x y _ _ hx hy
    rw [Subgroup.coe_mul]; exact Subgroup.mul_mem _ hx hy
  · intro x _ hx
    rw [Subgroup.coe_inv]; exact Subgroup.inv_mem _ hx

/-- **§7D Step 1 helper** — a characteristic subgroup `W` of `K` (as a subgroup
of `↥K`) has its `H`-image `W.map K.subtype` normalized by `N_H(K)`.

For `g ∈ N_H(K)`, conjugation by `g` restricts to an automorphism of `↥K`; since
`W` is characteristic, that automorphism preserves `W`, so `g` preserves
`W.map K.subtype`.  Used to deduce `M = N_H(K_p)` from `M = N_H(K)` (`K_p`
characteristic in `K`). -/
theorem normalizer_le_normalizer_map_of_characteristic
    {H : Type*} [Group H] {K : Subgroup H} {W : Subgroup ↥K} [W.Characteristic] :
    Subgroup.normalizer (K : Set H) ≤
      Subgroup.normalizer ((W.map K.subtype) : Set H) := by
  intro g hg
  rw [Subgroup.mem_normalizer_iff]
  -- The automorphism of ↥K induced by conjugation by `g ∈ N_H(K)`.
  set cg : ↥K ≃* ↥K := K.normalizerMonoidHom (⟨g, hg⟩ : ↥(Subgroup.normalizer K))
    with hcg_def
  -- W characteristic ⇒ `cg` fixes `W`.
  have hWfix : W.map (cg : ↥K →* ↥K) = W :=
    (Subgroup.characteristic_iff_map_eq.mp ‹W.Characteristic›) cg
  -- `↑(cg w) = g * ↑w * g⁻¹` for `w : ↥K`.
  have hcg_apply : ∀ w : ↥K, ((cg w : ↥K) : H) = g * (w : H) * g⁻¹ := fun w => rfl
  have hcg_symm_apply : ∀ w : ↥K, ((cg.symm w : ↥K) : H) = g⁻¹ * (w : H) * g := by
    intro w
    have h := hcg_apply (cg.symm w)
    rw [cg.apply_symm_apply] at h
    -- h : ↑w = g * ↑(cg.symm w) * g⁻¹  ⇒  ↑(cg.symm w) = g⁻¹ * ↑w * g.
    rw [h]; group
  intro y
  simp only [Subgroup.mem_map, Subgroup.coe_subtype]
  constructor
  · rintro ⟨w, hwW, rfl⟩
    -- y = ↑w, conjugate by g lands in W.map subtype via cg.
    refine ⟨cg w, ?_, ?_⟩
    · -- cg w ∈ W since cg fixes W.
      rw [← hWfix]; exact ⟨w, hwW, rfl⟩
    · rw [hcg_apply]
  · rintro ⟨w, hwW, hyeq⟩
    -- y conjugated back: g⁻¹ y g ∈ W.map subtype.
    refine ⟨cg.symm w, ?_, ?_⟩
    · rw [← hWfix] at hwW
      obtain ⟨w', hw'W, hw'eq⟩ := hwW
      -- cg.symm w = w' ∈ W.
      have : cg.symm w = w' := by rw [← hw'eq]; exact cg.symm_apply_apply w'
      rw [this]; exact hw'W
    · rw [hcg_symm_apply, hyeq]; group

/-- **§7D Step 1 decomposition** — for a finite nilpotent group `N` whose order
divides `p^a * q^b` (`p ≠ q`), `N = O_p(N) ⊔ O_q(N)`: the `p`- and `q`-cores
generate everything.

`N` nilpotent ⇒ `⊤ ≤ F(N)` (`nilpotent_normal_le_fitting`); `F(N) =
⨆_{r ∈ pf(|N|)} O_r(N)` (`fitting_eq_iSup_primeFactors`); `pf(|N|) ⊆ {p, q}`
since `|N| ∣ p^a q^b`. -/
theorem opCore_sup_opCore_eq_top_of_nilpotent_paqb
    {N : Type*} [Group N] [Finite N] [Group.IsNilpotent N] {p q : ℕ}
    [Fact p.Prime] [Fact q.Prime] (hpq : p ≠ q)
    {a b : ℕ} (hN_dvd : Nat.card N ∣ p ^ a * q ^ b) :
    OddOrder.Isaacs.Ch01.opCore p N ⊔ OddOrder.Isaacs.Ch01.opCore q N = ⊤ := by
  classical
  have hp_prime : p.Prime := Fact.out
  have hq_prime : q.Prime := Fact.out
  -- `⊤ ≤ F(N)`.
  have hTop_le_F : (⊤ : Subgroup N) ≤ OddOrder.Isaacs.Ch01.fitting N := by
    have := OddOrder.Isaacs.Ch01.nilpotent_normal_le_fitting (G := N) (N := ⊤)
    simpa using this
  -- `F(N) = ⨆_{r ∈ pf} O_r(N)`.
  rw [OddOrder.Isaacs.Ch01.fitting_eq_iSup_primeFactors] at hTop_le_F
  -- every prime factor of `|N|` is `p` or `q`.
  have hpf_sub : ∀ r ∈ (Nat.card N).primeFactors, r = p ∨ r = q := by
    intro r hr
    obtain ⟨hr_prime, hr_dvd, _⟩ := Nat.mem_primeFactors.mp hr
    have hr_dvd_paqb : r ∣ p ^ a * q ^ b := hr_dvd.trans hN_dvd
    rcases (Nat.Prime.dvd_mul hr_prime).mp hr_dvd_paqb with h | h
    · left; exact (Nat.prime_dvd_prime_iff_eq hr_prime hp_prime).mp (hr_prime.dvd_of_dvd_pow h)
    · right; exact (Nat.prime_dvd_prime_iff_eq hr_prime hq_prime).mp (hr_prime.dvd_of_dvd_pow h)
  -- so `⨆_{r ∈ pf} O_r(N) ≤ O_p(N) ⊔ O_q(N)`.
  refine top_le_iff.mp (hTop_le_F.trans (iSup_le (fun r => ?_)))
  rcases hpf_sub r r.2 with hrp | hrq
  · rw [show (r : ℕ) = p from hrp]; exact le_sup_left
  · rw [show (r : ℕ) = q from hrq]; exact le_sup_right

/-- **§7D Step 1 core (Thm 4.33 application)** — in a finite solvable group `X'`
whose order divides `p^a q^b` (`p ≠ q`), a `q`-subgroup `Y` normalized by the
`p`-local subgroup `N_{X'}(W)` (`W` a nontrivial `p`-subgroup) lies in `O_q(X')`.

This is Isaacs L3970-3973: `M ∩ X = N_X(K_p)` is `p`-local in the solvable `X`;
`K_q ⊴ M ∩ X` is a `p'`-group, so `K_q ⊆ O_{p'}(M∩X) ⊆ O_{p'}(X) = O_q(X)` by
Theorem 4.33.  Here `X'` plays the role of `↥X`, `W = K_p`, `Y = K_q`; the
hypothesis `N_{X'}(W) ≤ N_{X'}(Y)` is `K_q ⊴ M ∩ X`. -/
theorem qSubgroup_le_opCore_of_normal_in_pLocal
    {X' : Type*} [Group X'] [Finite X'] [IsSolvable X'] {p q : ℕ}
    [Fact p.Prime] [Fact q.Prime] (hpq : p ≠ q)
    {a b : ℕ} (hX_dvd : Nat.card X' ∣ p ^ a * q ^ b)
    {W : Subgroup X'} (hW_ne_bot : W ≠ ⊥) (hW_p : IsPGroup p W)
    {Y : Subgroup X'} (hY_q : IsPGroup q Y)
    (hY_le : Y ≤ Subgroup.normalizer (W : Set X'))
    (hY_normalized : Subgroup.normalizer (W : Set X') ≤ Subgroup.normalizer (Y : Set X')) :
    Y ≤ OddOrder.Isaacs.Ch01.opCore q X' := by
  classical
  have hp_prime : p.Prime := Fact.out
  have hq_prime : q.Prime := Fact.out
  haveI : OddOrder.Isaacs.Ch03.IsPiSeparable ({p} : Set ℕ) X' := inferInstance
  set π' : Set ℕ := {r | r ∉ ({p} : Set ℕ)} with hπ'_def
  -- `L = N_{X'}(W)` is `p`-local.
  set L : Subgroup X' := Subgroup.normalizer (W : Set X') with hL_def
  have hL_pLocal : OddOrder.Isaacs.Ch02.IsPLocal p L := ⟨W, hW_ne_bot, hW_p, rfl⟩
  have hY_le_L : Y ≤ L := hY_le
  set Ysub : Subgroup ↥L := Y.subgroupOf L with hYsub_def
  -- `Ysub` is normal in `L` (every `l ∈ L` normalizes `Y` by `hY_normalized`).
  haveI hYsub_normal : Ysub.Normal := by
    rw [hYsub_def]
    refine ⟨fun y hy l => ?_⟩
    have hl_norm : (l : X') ∈ Subgroup.normalizer (Y : Set X') := hY_normalized l.2
    rw [Subgroup.mem_subgroupOf] at hy ⊢
    rw [Subgroup.mem_normalizer_iff] at hl_norm
    exact (hl_norm (y : X')).mp hy
  -- `Ysub` is a `p'`-group: `Y` is a `q`-group, `q ∉ {p}`, transported to `subgroupOf`.
  have hY_pi' : OddOrder.Isaacs.Ch03.Subgroup.IsPiGroup π' Y := by
    intro r hr
    obtain ⟨hr_prime, hr_dvd_Y, _⟩ := Nat.mem_primeFactors.mp hr
    have hr_eq_q : r = q := by
      obtain ⟨k, hk⟩ := (IsPGroup.iff_card.mp hY_q)
      rw [hk] at hr_dvd_Y
      exact (Nat.prime_dvd_prime_iff_eq hr_prime hq_prime).mp (hr_prime.dvd_of_dvd_pow hr_dvd_Y)
    rw [hπ'_def, Set.mem_setOf_eq, Set.mem_singleton_iff, hr_eq_q]; exact hpq.symm
  have hYsub_pi' : OddOrder.Isaacs.Ch03.Subgroup.IsPiGroup π' Ysub :=
    OddOrder.Isaacs.Ch03.Subgroup.IsPiGroup.subgroupOf hY_le_L hY_pi'
  -- `Ysub ≤ O_{p'}(L)`.
  have hYsub_le : Ysub ≤ OddOrder.Isaacs.Ch03.oPiCore π' L :=
    OddOrder.Isaacs.Ch03.Subgroup.IsPiGroup.le_oPiCore hYsub_pi'
  -- Theorem 4.33: `O_{p'}(L).map L.subtype ≤ O_{p'}(X')`.
  have h433 := OddOrder.Isaacs.Ch04.oPiCore_compl_le_oPiCore_compl_of_isPLocal
    (G := X') (p := p) L hL_pLocal
  -- `Y = Ysub.map L.subtype ≤ O_{p'}(L).map L.subtype ≤ O_{p'}(X')`.
  have hY_eq_map : Y = Ysub.map L.subtype := by
    rw [hYsub_def, Subgroup.subgroupOf, Subgroup.map_comap_eq, L.range_subtype]
    exact (inf_eq_right.mpr hY_le_L).symm
  have hY_le_oPi' : Y ≤ OddOrder.Isaacs.Ch03.oPiCore π' X' := by
    rw [hY_eq_map]
    exact (Subgroup.map_mono hYsub_le).trans h433
  -- `O_{p'}(X') = O_q(X')` for a `{p,q}`-group `X'`: `O_{p'}` is a `q`-group ≤ `O_q`.
  have hOpi'_q : OddOrder.Isaacs.Ch03.oPiCore π' X' ≤ OddOrder.Isaacs.Ch01.opCore q X' := by
    set Z := OddOrder.Isaacs.Ch03.oPiCore π' X' with hZ_def
    have hZ_pi : OddOrder.Isaacs.Ch03.Subgroup.IsPiGroup π' Z :=
      OddOrder.Isaacs.Ch03.oPiCore.isPiGroup π'
    have hZ_q : IsPGroup q Z := by
      apply OddOrder.Isaacs.Ch04.isPGroup_of_isPiGroup_singleton
      intro r hr
      obtain ⟨hr_prime, hr_dvd_Z, _⟩ := Nat.mem_primeFactors.mp hr
      have hr_ne_p : r ≠ p := by
        have := hZ_pi r hr
        rwa [hπ'_def, Set.mem_setOf_eq, Set.mem_singleton_iff] at this
      have hr_dvd_X : r ∣ Nat.card X' := hr_dvd_Z.trans Z.card_subgroup_dvd_card
      have hr_dvd_paqb : r ∣ p ^ a * q ^ b := hr_dvd_X.trans hX_dvd
      rcases (Nat.Prime.dvd_mul hr_prime).mp hr_dvd_paqb with h | h
      · exact absurd ((Nat.prime_dvd_prime_iff_eq hr_prime hp_prime).mp
          (hr_prime.dvd_of_dvd_pow h)) hr_ne_p
      · simp only [Set.mem_singleton_iff]
        exact (Nat.prime_dvd_prime_iff_eq hr_prime hq_prime).mp (hr_prime.dvd_of_dvd_pow h)
    haveI : Z.Normal := OddOrder.Isaacs.Ch03.oPiCore.normal π' X'
    exact OddOrder.Isaacs.Ch01.normal_pgroup_le_opCore hZ_q
  exact hY_le_oPi'.trans hOpi'_q

/-- **§7D Step 1** (Isaacs L3969-3981) — *unique maximal containing a nilpotent
subgroup divisible by both primes*.

Let `K ≤ H` be nilpotent with both `p` and `q` dividing `|K|`, and suppose
`M = N_H(K)` is maximal.  Then `M` is the **unique** maximal subgroup of `H`
containing `K`: any maximal `X ⊇ K` equals `M`.

Proof (downward strong induction on `|H| - |K|`, i.e. `K` maximal among
counterexamples): write `K = K_p × K_q` (`K_p = O_p(K)` characteristic in `K`).
`K_p ⊴ M ⇒ M = N_H(K_p)`.  `M ∩ X = N_X(K_p)` is `p`-local in solvable `X`, and
`K_q ⊴ M ∩ X` is a `p'`-group, so by Thm 4.33 `K_q ⊆ O_q(X) =: L_q`; similarly
`K_p ⊆ L_p = O_p(X)`.  With `L = L_p L_q ⊇ K` nilpotent and `X = N_H(L)`, if
`K < L` the IH gives `X` unique maximal `⊇ L`; but `L_q ⊆ C(L_p) ⊆ C(K_p) ⊆ M`
and `L_p ⊆ M`, so `L ⊆ M`, forcing `M = X`.  If `K = L` then
`M = N_H(K) = N_H(L) = X`. -/
theorem step1_unique_maximal_containing_nilpotent
    {H : Type*} [Group H] [Finite H] [IsSimpleGroup H] {p q : ℕ}
    [Fact p.Prime] [Fact q.Prime] (hpq : p ≠ q)
    {a b : ℕ} (hH_card : Nat.card H = p ^ a * q ^ b)
    (hSubgroupsSolvable : ∀ K : Subgroup H, K ≠ ⊤ → IsSolvable K)
    {K : Subgroup H} (hK_nilp : Group.IsNilpotent ↥K)
    (hp_dvd : p ∣ Nat.card ↥K) (hq_dvd : q ∣ Nat.card ↥K)
    (hM_max : IsCoatom (Subgroup.normalizer (K : Set H) : Subgroup H))
    {X : Subgroup H} (hX_max : IsCoatom X) (hKX : K ≤ X) :
    X = (Subgroup.normalizer (K : Set H) : Subgroup H) := by
  classical
  have hp_prime : p.Prime := Fact.out
  have hq_prime : q.Prime := Fact.out
  -- Strong downward induction on `|K|` via the measure `m = |H| - |K|`: the IH
  -- handles any nilpotent `K'` with `|K'| > |K|` (smaller measure).
  suffices hmain : ∀ m : ℕ, ∀ K' : Subgroup H, Group.IsNilpotent ↥K' →
      p ∣ Nat.card ↥K' → q ∣ Nat.card ↥K' →
      IsCoatom (Subgroup.normalizer (K' : Set H) : Subgroup H) →
      Nat.card H - Nat.card ↥K' = m →
      ∀ X' : Subgroup H, IsCoatom X' → K' ≤ X' →
      X' = (Subgroup.normalizer (K' : Set H) : Subgroup H) by
    exact hmain _ K hK_nilp hp_dvd hq_dvd hM_max rfl X hX_max hKX
  intro m
  induction m using Nat.strong_induction_on with
  | _ m ih =>
    intro K hK_nilp hp_dvd hq_dvd hM_max hmeas X hX_max hKX
    -- Notation.
    set M : Subgroup H := Subgroup.normalizer (K : Set H) with hM_def
    -- `K ≤ M` and `M ≠ ⊤`.
    have hK_le_M : K ≤ M := Subgroup.le_normalizer
    have hM_ne_top : M ≠ ⊤ := hM_max.1
    -- `|K| ∣ p^a q^b`.
    have hK_card_dvd : Nat.card ↥K ∣ p ^ a * q ^ b := by
      rw [← hH_card]; exact K.card_subgroup_dvd_card
    -- `K_p = O_p(K).map subtype`, `K_q = O_q(K).map subtype`.
    set Kp : Subgroup H := (OddOrder.Isaacs.Ch01.opCore p ↥K).map K.subtype with hKp_def
    set Kq : Subgroup H := (OddOrder.Isaacs.Ch01.opCore q ↥K).map K.subtype with hKq_def
    -- `O_p(K) ⊔ O_q(K) = ⊤`, hence `Kp ⊔ Kq = K`.
    have hsup_top : OddOrder.Isaacs.Ch01.opCore p ↥K ⊔ OddOrder.Isaacs.Ch01.opCore q ↥K = ⊤ :=
      opCore_sup_opCore_eq_top_of_nilpotent_paqb hpq hK_card_dvd
    have hKp_sup_Kq : Kp ⊔ Kq = K := by
      rw [hKp_def, hKq_def, ← Subgroup.map_sup, hsup_top, ← MonoidHom.range_eq_map,
        K.range_subtype]
    -- `Kp ≤ K`, `Kq ≤ K`.
    have hKp_le_K : Kp ≤ K := hKp_sup_Kq ▸ le_sup_left
    have hKq_le_K : Kq ≤ K := hKp_sup_Kq ▸ le_sup_right
    -- `Kp` is a `p`-group, `Kq` a `q`-group.
    have hKp_pgroup : IsPGroup p Kp :=
      (OddOrder.Isaacs.Ch01.opCore_isPGroup p ↥K).map K.subtype
    have hKq_qgroup : IsPGroup q Kq :=
      (OddOrder.Isaacs.Ch01.opCore_isPGroup q ↥K).map K.subtype
    -- `O_p(K) ≠ ⊥` (`p ∣ |K|`, `K` nilpotent ⇒ normal Sylow-p `≤ O_p(K)` nontrivial).
    have hOpK_ne_bot : OddOrder.Isaacs.Ch01.opCore p ↥K ≠ ⊥ := by
      obtain ⟨P⟩ := Sylow.nonempty (p := p) (G := ↥K)
      have hP_ne_bot : (P : Subgroup ↥K) ≠ ⊥ :=
        OddOrder.Isaacs.Ch07.Sylow.ne_bot_of_dvd_card hp_dvd P
      haveI : (P : Subgroup ↥K).Normal := OddOrder.Isaacs.Ch01.Sylow.normal_of_isNilpotent P
      have hP_le_Op : (P : Subgroup ↥K) ≤ OddOrder.Isaacs.Ch01.opCore p ↥K :=
        OddOrder.Isaacs.Ch01.normal_pgroup_le_opCore P.isPGroup'
      intro hbot
      rw [hbot, le_bot_iff] at hP_le_Op
      exact hP_ne_bot hP_le_Op
    have hOqK_ne_bot : OddOrder.Isaacs.Ch01.opCore q ↥K ≠ ⊥ := by
      obtain ⟨Q⟩ := Sylow.nonempty (p := q) (G := ↥K)
      have hQ_ne_bot : (Q : Subgroup ↥K) ≠ ⊥ :=
        OddOrder.Isaacs.Ch07.Sylow.ne_bot_of_dvd_card hq_dvd Q
      haveI : (Q : Subgroup ↥K).Normal := OddOrder.Isaacs.Ch01.Sylow.normal_of_isNilpotent Q
      have hQ_le_Oq : (Q : Subgroup ↥K) ≤ OddOrder.Isaacs.Ch01.opCore q ↥K :=
        OddOrder.Isaacs.Ch01.normal_pgroup_le_opCore Q.isPGroup'
      intro hbot
      rw [hbot, le_bot_iff] at hQ_le_Oq
      exact hQ_ne_bot hQ_le_Oq
    -- `Kp ≠ ⊥`, `Kq ≠ ⊥` (subtype map is injective).
    have hKp_ne_bot : Kp ≠ ⊥ := by
      rw [hKp_def]; intro hbot
      rw [Subgroup.map_eq_bot_iff_of_injective _ K.subtype_injective] at hbot
      exact hOpK_ne_bot hbot
    have hKq_ne_bot : Kq ≠ ⊥ := by
      rw [hKq_def]; intro hbot
      rw [Subgroup.map_eq_bot_iff_of_injective _ K.subtype_injective] at hbot
      exact hOqK_ne_bot hbot
    -- `Kp` characteristic in `↥K`; hence `M = N_H(K) ≤ N_H(Kp)` and `M = N_H(Kp)`.
    haveI hOpK_char : (OddOrder.Isaacs.Ch01.opCore p ↥K).Characteristic :=
      OddOrder.Isaacs.Ch01.opCore.characteristic p ↥K
    have hM_le_NKp : M ≤ (Subgroup.normalizer (Kp : Set H) : Subgroup H) := by
      rw [hKp_def]
      exact normalizer_le_normalizer_map_of_characteristic
    have hKp_le_M : Kp ≤ M := le_trans hKp_le_K hK_le_M
    have hM_eq_NKp : (Subgroup.normalizer (Kp : Set H) : Subgroup H) = M :=
      maximal_eq_normalizer_of_M_normalizes hM_max hKp_ne_bot hKp_le_M hM_le_NKp
    -- Symmetric facts for `Kq`.
    haveI hOqK_char : (OddOrder.Isaacs.Ch01.opCore q ↥K).Characteristic :=
      OddOrder.Isaacs.Ch01.opCore.characteristic q ↥K
    have hM_le_NKq : M ≤ (Subgroup.normalizer (Kq : Set H) : Subgroup H) := by
      rw [hKq_def]; exact normalizer_le_normalizer_map_of_characteristic
    have hKq_le_M : Kq ≤ M := le_trans hKq_le_K hK_le_M
    have hM_eq_NKq : (Subgroup.normalizer (Kq : Set H) : Subgroup H) = M :=
      maximal_eq_normalizer_of_M_normalizes hM_max hKq_ne_bot hKq_le_M hM_le_NKq
    -- `Kp, Kq ≤ X`.
    have hKp_le_X : Kp ≤ X := le_trans hKp_le_K hKX
    have hKq_le_X : Kq ≤ X := le_trans hKq_le_K hKX
    -- `X` solvable (proper subgroup of simple `H`).
    haveI hX_solv : IsSolvable ↥X := hSubgroupsSolvable X hX_max.1
    have hX_card_dvd : Nat.card ↥X ∣ p ^ a * q ^ b := by
      rw [← hH_card]; exact X.card_subgroup_dvd_card
    -- Reusable: lift "`Kr ≤ O_r(X)`-image" via the Thm-4.33 helper inside `↥X`.
    -- For `Kq`: `Kq` is a `q`-subgroup normalized by `N_X(Kp)` (= the `p`-local).
    have hLq_extract : Kq ≤ (OddOrder.Isaacs.Ch01.opCore q ↥X).map X.subtype := by
      -- Work inside `↥X`: `W = Kp.subgroupOf X`, `Y = Kq.subgroupOf X`.
      set W : Subgroup ↥X := Kp.subgroupOf X with hW_def
      set Y : Subgroup ↥X := Kq.subgroupOf X with hY_def
      have hW_ne_bot : W ≠ ⊥ := by
        rw [hW_def, Ne, Subgroup.subgroupOf_eq_bot]
        exact fun hd => hKp_ne_bot (le_bot_iff.mp (hd le_rfl hKp_le_X))
      have hW_p : IsPGroup p W := hKp_pgroup.comap_subtype
      have hY_q : IsPGroup q Y := hKq_qgroup.comap_subtype
      -- `Y ≤ N_{↥X}(W)`: `Kq ≤ N_H(Kp) = M` (since `Kq ≤ K ≤ M = N(Kp)`).
      have hKq_le_NKp : Kq ≤ (Subgroup.normalizer (Kp : Set H) : Subgroup H) := by
        rw [hM_eq_NKp]; exact hKq_le_M
      have hY_le : Y ≤ Subgroup.normalizer (W : Set ↥X) := by
        rw [hW_def, ← Subgroup.subgroupOf_normalizer_eq hKp_le_X]
        exact Subgroup.subgroupOf_mono X hKq_le_NKp
      -- `N_{↥X}(W) ≤ N_{↥X}(Y)`: `N_H(Kp) = M ≤ N_H(Kq)`.
      have hNKp_le_NKq : (Subgroup.normalizer (Kp : Set H) : Subgroup H) ≤
          (Subgroup.normalizer (Kq : Set H) : Subgroup H) := by
        rw [hM_eq_NKp, hM_eq_NKq]
      have hY_norm : Subgroup.normalizer (W : Set ↥X) ≤ Subgroup.normalizer (Y : Set ↥X) := by
        rw [hW_def, hY_def, ← Subgroup.subgroupOf_normalizer_eq hKp_le_X,
          ← Subgroup.subgroupOf_normalizer_eq hKq_le_X]
        exact Subgroup.subgroupOf_mono X hNKp_le_NKq
      have hY_le_Oq : Y ≤ OddOrder.Isaacs.Ch01.opCore q ↥X :=
        qSubgroup_le_opCore_of_normal_in_pLocal hpq hX_card_dvd hW_ne_bot hW_p hY_q hY_le hY_norm
      -- Map back: `Kq = Y.map subtype ≤ (O_q ↥X).map subtype`.
      have hKq_eq : Kq = Y.map X.subtype := by
        rw [hY_def, Subgroup.subgroupOf, Subgroup.map_comap_eq, X.range_subtype]
        exact (inf_eq_right.mpr hKq_le_X).symm
      rw [hKq_eq]; exact Subgroup.map_mono hY_le_Oq
    -- Symmetric extraction for `Kp` (roles `p ↔ q` swapped).
    have hLp_extract : Kp ≤ (OddOrder.Isaacs.Ch01.opCore p ↥X).map X.subtype := by
      set W : Subgroup ↥X := Kq.subgroupOf X with hW_def
      set Y : Subgroup ↥X := Kp.subgroupOf X with hY_def
      have hW_ne_bot : W ≠ ⊥ := by
        rw [hW_def, Ne, Subgroup.subgroupOf_eq_bot]
        exact fun hd => hKq_ne_bot (le_bot_iff.mp (hd le_rfl hKq_le_X))
      have hW_q : IsPGroup q W := hKq_qgroup.comap_subtype
      have hY_p : IsPGroup p Y := hKp_pgroup.comap_subtype
      have hKp_le_NKq : Kp ≤ (Subgroup.normalizer (Kq : Set H) : Subgroup H) := by
        rw [hM_eq_NKq]; exact hKp_le_M
      have hY_le : Y ≤ Subgroup.normalizer (W : Set ↥X) := by
        rw [hW_def, ← Subgroup.subgroupOf_normalizer_eq hKq_le_X]
        exact Subgroup.subgroupOf_mono X hKp_le_NKq
      have hNKq_le_NKp : (Subgroup.normalizer (Kq : Set H) : Subgroup H) ≤
          (Subgroup.normalizer (Kp : Set H) : Subgroup H) := by
        rw [hM_eq_NKp, hM_eq_NKq]
      have hY_norm : Subgroup.normalizer (W : Set ↥X) ≤ Subgroup.normalizer (Y : Set ↥X) := by
        rw [hW_def, hY_def, ← Subgroup.subgroupOf_normalizer_eq hKq_le_X,
          ← Subgroup.subgroupOf_normalizer_eq hKp_le_X]
        exact Subgroup.subgroupOf_mono X hNKq_le_NKp
      have hX_card_dvd' : Nat.card ↥X ∣ q ^ b * p ^ a := by rw [mul_comm]; exact hX_card_dvd
      have hY_le_Op : Y ≤ OddOrder.Isaacs.Ch01.opCore p ↥X :=
        qSubgroup_le_opCore_of_normal_in_pLocal hpq.symm hX_card_dvd' hW_ne_bot hW_q hY_p hY_le
          hY_norm
      have hKp_eq : Kp = Y.map X.subtype := by
        rw [hY_def, Subgroup.subgroupOf, Subgroup.map_comap_eq, X.range_subtype]
        exact (inf_eq_right.mpr hKp_le_X).symm
      rw [hKp_eq]; exact Subgroup.map_mono hY_le_Op
    -- `L = L_p L_q` where `L_p = O_p(X)`, `L_q = O_q(X)` (images in `H`).
    set OpX : Subgroup ↥X := OddOrder.Isaacs.Ch01.opCore p ↥X with hOpX_def
    set OqX : Subgroup ↥X := OddOrder.Isaacs.Ch01.opCore q ↥X with hOqX_def
    set Lp : Subgroup H := OpX.map X.subtype with hLp_def
    set Lq : Subgroup H := OqX.map X.subtype with hLq_def
    set L : Subgroup H := Lp ⊔ Lq with hL_def
    -- `K ≤ L` (`K = Kp ⊔ Kq ≤ Lp ⊔ Lq`).
    have hK_le_L : K ≤ L := by
      rw [← hKp_sup_Kq, hL_def]
      exact sup_le_sup hLp_extract hLq_extract
    -- `Lp, Lq ≤ X`; `L ≤ X`.
    have hLp_le_X : Lp ≤ X := by
      rw [hLp_def]; rintro _ ⟨z, _, rfl⟩; exact z.2
    have hLq_le_X : Lq ≤ X := by
      rw [hLq_def]; rintro _ ⟨z, _, rfl⟩; exact z.2
    have hL_le_X : L ≤ X := sup_le hLp_le_X hLq_le_X
    -- `L ≠ ⊥` (`Kp ≤ Lp ≤ L`, `Kp ≠ ⊥`).
    have hL_ne_bot : L ≠ ⊥ := by
      intro hbot
      exact hKp_ne_bot (le_bot_iff.mp (le_trans hLp_extract (hbot ▸ le_sup_left)))
    -- `L` nilpotent: `OpX ⊔ OqX` is nilpotent (normal coprime), and `L` is its image.
    haveI hOpX_nilp : Group.IsNilpotent ↥OpX := by
      rw [hOpX_def]; exact (OddOrder.Isaacs.Ch01.opCore_isPGroup p ↥X).isNilpotent
    haveI hOqX_nilp : Group.IsNilpotent ↥OqX := by
      rw [hOqX_def]; exact (OddOrder.Isaacs.Ch01.opCore_isPGroup q ↥X).isNilpotent
    haveI hOpX_normal : OpX.Normal := by rw [hOpX_def]; infer_instance
    haveI hOqX_normal : OqX.Normal := by rw [hOqX_def]; infer_instance
    haveI : Group.IsNilpotent (↥(OpX ⊔ OqX)) :=
      OddOrder.Isaacs.Ch01.sup_isNilpotent_of_normal_nilpotent OpX OqX
    have hL_eq_map : L = (OpX ⊔ OqX).map X.subtype := by
      rw [hL_def, hLp_def, hLq_def, ← Subgroup.map_sup]
    haveI hL_nilp : Group.IsNilpotent ↥L := by
      rw [hL_eq_map]
      exact Group.nilpotent_of_mulEquiv (Subgroup.equivMapOfInjective (OpX ⊔ OqX) X.subtype
        X.subtype_injective)
    -- `p, q ∣ |L|` (`Kp ≤ Lp ≤ L` with `p ∣ |Kp|`, etc.).
    have hKp_card_eq : Nat.card ↥Kp = Nat.card ↥(OddOrder.Isaacs.Ch01.opCore p ↥K) := by
      rw [hKp_def]
      exact Nat.card_congr (Subgroup.equivMapOfInjective
        (OddOrder.Isaacs.Ch01.opCore p ↥K) K.subtype K.subtype_injective).toEquiv.symm
    have hKq_card_eq : Nat.card ↥Kq = Nat.card ↥(OddOrder.Isaacs.Ch01.opCore q ↥K) := by
      rw [hKq_def]
      exact Nat.card_congr (Subgroup.equivMapOfInjective
        (OddOrder.Isaacs.Ch01.opCore q ↥K) K.subtype K.subtype_injective).toEquiv.symm
    have hp_dvd_Kp : p ∣ Nat.card ↥Kp := by
      rw [hKp_card_eq]
      obtain ⟨k, hk⟩ := IsPGroup.iff_card.mp (OddOrder.Isaacs.Ch01.opCore_isPGroup p ↥K)
      rw [hk]; refine dvd_pow_self p ?_
      rintro rfl; rw [pow_zero] at hk
      exact hOpK_ne_bot (Subgroup.eq_bot_of_card_eq _ hk)
    have hq_dvd_Kq : q ∣ Nat.card ↥Kq := by
      rw [hKq_card_eq]
      obtain ⟨k, hk⟩ := IsPGroup.iff_card.mp (OddOrder.Isaacs.Ch01.opCore_isPGroup q ↥K)
      rw [hk]; refine dvd_pow_self q ?_
      rintro rfl; rw [pow_zero] at hk
      exact hOqK_ne_bot (Subgroup.eq_bot_of_card_eq _ hk)
    have hp_dvd_L : p ∣ Nat.card ↥L :=
      hp_dvd_Kp.trans (Subgroup.card_dvd_of_le (le_trans hLp_extract le_sup_left))
    have hq_dvd_L : q ∣ Nat.card ↥L :=
      hq_dvd_Kq.trans (Subgroup.card_dvd_of_le (le_trans hLq_extract le_sup_right))
    -- `X = N_H(L)`: `L` is the image of the characteristic `OpX ⊔ OqX`.
    haveI hOpqX_char : (OpX ⊔ OqX).Characteristic := by
      rw [Subgroup.characteristic_iff_map_eq]
      intro φ
      rw [Subgroup.map_sup,
        Subgroup.characteristic_iff_map_eq.mp (by rw [hOpX_def]; infer_instance) φ,
        Subgroup.characteristic_iff_map_eq.mp (by rw [hOqX_def]; infer_instance) φ]
    have hX_le_NL : X ≤ (Subgroup.normalizer (L : Set H) : Subgroup H) := by
      rw [hL_eq_map]
      exact le_trans Subgroup.le_normalizer
        (normalizer_le_normalizer_map_of_characteristic (K := X) (W := OpX ⊔ OqX))
    have hNL_eq_X : (Subgroup.normalizer (L : Set H) : Subgroup H) = X :=
      maximal_eq_normalizer_of_M_normalizes hX_max hL_ne_bot hL_le_X hX_le_NL
    -- `L_q ⊆ C_H(L_p) ⊆ C_H(K_p) ⊆ N_H(K_p) = M`, similarly `L_p ⊆ M`, so `L ⊆ M`.
    have hLq_Lp_commute : ∀ x ∈ Lp, ∀ y ∈ Lq, Commute x y := by
      rintro _ ⟨xs, hxs, rfl⟩ _ ⟨ys, hys, rfl⟩
      have hcomm : Commute xs ys :=
        Subgroup.commute_of_normal_of_disjoint OpX OqX
          (by rw [hOpX_def]; infer_instance) (by rw [hOqX_def]; infer_instance)
          (IsPGroup.disjoint_of_ne p q hpq _ _
            (OddOrder.Isaacs.Ch01.opCore_isPGroup p ↥X)
            (OddOrder.Isaacs.Ch01.opCore_isPGroup q ↥X)) xs ys hxs hys
      -- transfer commute through the subtype hom.
      have := congrArg (X.subtype) hcomm
      simpa [Commute, SemiconjBy, map_mul] using this
    have hLq_le_centLp : Lq ≤ Subgroup.centralizer (Lp : Set H) := by
      intro y hy
      rw [Subgroup.mem_centralizer_iff]
      intro x hx
      exact hLq_Lp_commute x hx y hy
    have hLp_le_centLq : Lp ≤ Subgroup.centralizer (Lq : Set H) := by
      intro x hx
      rw [Subgroup.mem_centralizer_iff]
      intro y hy
      exact (hLq_Lp_commute x hx y hy).symm
    -- `C_H(Lp) ⊆ C_H(Kp) ⊆ N_H(Kp) = M` (and symmetric).
    have hLq_le_M : Lq ≤ M :=
      le_trans hLq_le_centLp (le_trans
        (Subgroup.centralizer_le (SetLike.coe_subset_coe.mpr hLp_extract))
        (by rw [← hM_eq_NKp]; exact centralizer_le_normalizer Kp))
    have hLp_le_M : Lp ≤ M :=
      le_trans hLp_le_centLq (le_trans
        (Subgroup.centralizer_le (SetLike.coe_subset_coe.mpr hLq_extract))
        (by rw [← hM_eq_NKq]; exact centralizer_le_normalizer Kq))
    have hL_le_M : L ≤ M := sup_le hLp_le_M hLq_le_M
    -- Both cases (`K < L` and `K = L`) give `X = M`.
    rcases eq_or_lt_of_le hK_le_L with hKL_eq | hKL_lt
    · -- `K = L`: `M = N(K) = N(L) = X`.
      have : (Subgroup.normalizer (K : Set H) : Subgroup H)
          = (Subgroup.normalizer (L : Set H) : Subgroup H) := by rw [hKL_eq]
      rw [← hNL_eq_X, ← this]
    · -- `K < L`: IH (smaller measure) gives `M = N(L) = X` since `M` maximal `⊇ L`.
      have hmeas_L : Nat.card H - Nat.card ↥L < m := by
        have hcard_lt : Nat.card ↥K < Nat.card ↥L := by
          have hss : (K : Set H) ⊂ (L : Set H) := SetLike.coe_ssubset_coe.mpr hKL_lt
          have := Set.Finite.card_lt_card (Set.toFinite (L : Set H)) hss
          simpa using this
        have hL_card_le : Nat.card ↥L ≤ Nat.card H :=
          Nat.le_of_dvd Nat.card_pos L.card_subgroup_dvd_card
        have hK_card_pos : 0 < Nat.card ↥K := Nat.card_pos
        omega
      have hNL_max : IsCoatom (Subgroup.normalizer (L : Set H) : Subgroup H) := by
        rw [hNL_eq_X]; exact hX_max
      have hM_eq_NL : M = (Subgroup.normalizer (L : Set H) : Subgroup H) :=
        ih (Nat.card H - Nat.card ↥L) hmeas_L L hL_nilp hp_dvd_L hq_dvd_L hNL_max rfl
          M hM_max hL_le_M
      rw [← hNL_eq_X, ← hM_eq_NL]


end OddOrder.Isaacs.Ch07
